import type { Texte } from "@/texte/de";

/**
 * Die arabischen Texte der Oberfläche. Maschinell übersetzt — vor dem
 * Ausrollen sollte jemand darüberlesen, der die Sprache spricht.
 */
export const ar: Texte = {
  kopf: {
    benutzermenue: "قائمة المستخدم",
    angemeldetAls: "تم تسجيل الدخول باسم",
    uebersicht: "إلى النظرة العامة",
    hilfe: "المساعدة",
    einstellungen: "الإعدادات",
    abmelden: "تسجيل الخروج",
    sprache: "اللغة",
    erscheinungsbild: "المظهر",
    hell: "فاتح",
    dunkel: "داكن",
    system: "حسب النظام",
    meldungenLeer: "App Feedback — لا جديد",
    meldungen: (anzahl: number) => `App Feedback — ${anzahl} لم يُطَّلع عليها بعد`,
    massnahmenLeer: "الإجراءات — لا شيء مفتوح",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `الإجراءات — ${offen} مفتوحة، منها ${ueberfaellig} متأخرة`
        : `الإجراءات — ${offen} مفتوحة`,
    navigation: "التنقل",
    einklappen: "طيّ الشريط الجانبي",
    ausklappen: "توسيع الشريط الجانبي",
    navigationOeffnen: "فتح التنقل",
    navigationSchliessen: "إغلاق التنقل",
    unterseitenZeigen: (name: string) => `${name}: إظهار الصفحات الفرعية`,
    unterseitenVerbergen: (name: string) => `${name}: إخفاء الصفحات الفرعية`,
    werkzeuge: "عوامل التصفية والإجراءات",
    werkzeugeEinklappen: "طيّ شريط التصفية",
    werkzeugeAusklappen: "توسيع شريط التصفية",
    werkzeugeOeffnen: "فتح عوامل التصفية",
    werkzeugeSchliessen: "إغلاق عوامل التصفية",
    kategorien: {
      navigation: "التنقل",
      ansicht: "العرض",
      filter: "عوامل التصفية",
      zeitraum: "الفترة",
      aktionen: "الإجراءات",
    },
    auchGeoeffnet: (namen: string) => `مفتوح أيضًا لدى ${namen}`,
    konflikt: "غيّره شخص آخر في هذه الأثناء — تم تحميل الحالة الحالية.",
    geloeschtVonAnderen: "حذفه شخص آخر في هذه الأثناء.",
  },
  pfad: {
    aria: "المسار",
    start: "البداية",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "التوريدات",
      "/atr/teilekatalog": "كتالوج القطع",
      "/einstellungen": "الإعدادات",
      "/fair": "FAIR",
      "/hilfe": "المساعدة",
      "/hr": "HR",
      "/hr/dokumente": "دورة المستندات",
      "/hr/einarbeitung": "التأهيل",
      "/hr/kennzahlen": "المؤشرات",
      "/hr/kompetenzen": "الكفاءات",
      "/hr/onboarding": "الالتحاق",
      "/hr/organigramm": "الهيكل التنظيمي",
      "/hr/schulungen": "التدريبات",
      "/hr/schulungen/matrix": "المصفوفة",
      "/hr/schulungen/offen": "المتبقّي",
      "/hr/zeugnisse": "شهادات العمل",
      "/kpi": "المؤشرات",
      "/kpi/bewertung": "تقييم KPI والإجراءات",
      "/kpi/einkauf": "المشتريات",
      "/kpi/finanzen": "المالية",
      "/kpi/produktion": "الإنتاج",
      "/kpi/qualitaet": "الجودة",
      "/kpi/vertrieb": "المبيعات",
      "/newsletter": "النشرة",
      "/newsletter/redaktion": "التحرير",
      "/platform/feedback": "App Feedback",
      "/produktion": "الإنتاج",
      "/qualitaet": "الجودة",
      "/sensoren": "المستشعرات",
      "/signage": "Digital Signage",
      "/signage/devices": "الأجهزة",
      "/signage/media": "الوسائط",
      "/signage/pair": "الاقتران",
      "/signage/playlists": "قوائم التشغيل",
      "/signage/schedules": "الجداول الزمنية",
      "/uploads": "الملفات المرفوعة",
    },
  },
  start: {
    titel: "التطبيقات",
    verweigert: (name: string) => `ليست لديك صلاحية فتح «${name}».`,
    keineApp: "لم يُسنَد إلى حسابك أي تطبيق بعد. توجّه إلى إدارة المنصة.",
  },
  anmeldung: {
    benutzer: "المستخدم",
    lokalWechseln: "تسجيل الدخول محليًا",
    adWechseln: "تسجيل الدخول بحساب AD",
    titel: "ACM-Plattform",
    aufforderung: "سجّل الدخول بحسابك.",
    email: "البريد الإلكتروني",
    passwort: "كلمة المرور",
    knopf: "تسجيل الدخول",
    laeuft: "جارٍ تسجيل الدخول …",
  },
  allgemein: {
    laedt: "جارٍ التحميل …",
    speichern: "حفظ",
    abbrechen: "إلغاء",
    loeschen: "حذف",
    stueck: "قطعة",
    loeschenTitel: "تأكيد الحذف",
    loeschenFrage: (was: string) => `سيُحذف «${was}» نهائياً.`,
    loeschenKnopf: (was: string) => `حذف ${was}`,
  },
  zeitraum: {
    aria: "الفترة",
    monat: "هذا الشهر",
    quartal: "هذا الربع",
    jahr: "هذه السنة",
    alles: "كل الفترات",
    frei: "اختر فترة",
    von: "من",
    bis: "إلى",
    vonAria: "الفترة من",
    bisAria: "الفترة إلى",
    verdreht: "النهاية قبل البداية.",
  },
  vergleich: {
    zu: (was: string) => `مقارنةً بـ ${was}`,
    quartal: (q: number) => `الربع ${q}`,
    jahr: (j: number) => `${j}`,
    keinWert: "لا توجد قيمة للمقارنة: البيانات ناقصة في فترة المقارنة أو كانت القيمة صفرًا.",
    gestiegen: "ارتفاع",
    gesunken: "انخفاض",
    unveraendert: "دون تغيير",
  },
  diagramm: {
    art: "نوع الرسم",
    balken: "أعمدة",
    flaeche: "مساحة",
  },
  tabelle: {
    suche: "بحث",
    sucheAria: "البحث في الجدول",
    sucheLeeren: "مسح البحث",
    keineTreffer: "لا توجد نتائج لهذا البحث.",
    leer: "لا توجد إدخالات.",
    bereich: (von: number, bis: number, gesamt: number) => `${von}–${bis} من ${gesamt}`,
    seite: (seite: number, seiten: number) => `الصفحة ${seite} من ${seiten}`,
    zurueck: "الصفحة السابقة",
    weiter: "الصفحة التالية",
    sortieren: (spalte: string) => `الترتيب حسب «${spalte}»`,
    seitengroesse: "عدد صفوف الجدول في الصفحة",
    seitengroesseText: "ينطبق على جميع جداول المنصة ولجميع الأشخاص.",
    gespeichert: "تم حفظ حجم الصفحة.",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `حالة البيانات ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `حالة البيانات ناقصة — ${fehlend} ${anzahl === 1 ? "غير متوفر" : "غير متوفرة"}`,
    heute: "اليوم",
    gestern: "أمس",
    vorTagen: (tage: number) => `قبل ${tage} يوماً`,
    nie: "أبداً",
    arten: {
      umsatz: "الإيرادات",
      auftraege: "الطلبات",
      angebote: "العروض",
      interessenten: "المهتمّون",
      kontakte: "الاتصالات",
      liefertreue: "الالتزام بمواعيد التسليم",
      lagerbewegungen: "حركات المخزون",
      materialpreise: "أسعار المواد",
      lagerpreise: "أسعار المخزون",
      auftragspositionen: "بنود الطلبات",
      lieferscheine: "إشعارات التسليم",
      pruefungen: "الفحوصات",
      acht_d: "تقارير 8D",
      wareneingaenge: "استلامات البضائع",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `تعذّر تحميل المؤشرات: ${meldung}`,
    keineDatenTitel: "لا توجد بيانات لهذه الفترة",
    keineDatenVor: "ارفع تصديرات نظام ERP في ",
    keineDatenNach: "، أو اختر فترة أوسع.",
    keineWerte: "لا قيم في هذه الفترة",
    laedt: "جارٍ التحميل …",
    jeTag: "لكل يوم",
    jeWoche: "لكل أسبوع",
    jeMonat: "لكل شهر",
  },
  vertrieb: {
    umsatz: "الإيرادات",
    umsatzHinweis: "الفواتير ناقص الإشعارات الدائنة",
    auftragswert: "متوسط قيمة الطلب",
    ueberNull: "طلبات تتجاوز 0 €",
    auftraege: "إجمالي الطلبات",
    verlauf: "تطوّر الإيرادات",
    verlaufHinweis: (takt: string) => `${takt}، بعد خصم الإشعارات الدائنة`,
    kundenanteil: "حصة العملاء من الإيرادات",
    kunde: "العميل",
    anteil: "الحصة",
    uebrige: "الباقي",
    jeErfasser: "الطلبات لكل مُدخِل",
    erfasser: "المُدخِل",
    anzahl: "الطلبات",
    summe: "الإجمالي",
    einzelauftraege: "الطلبات الفردية",
    einzelauftraegeHinweis: "الطلبات التي تتجاوز 0 € في الفترة — وهي التي يعدّها «إجمالي الطلبات»",
    auftragsNr: "رقم الطلب",
    datum: "التاريخ",
    gesamt: "الإجمالي",
    kundenanteilAuftraege: "حصة العملاء من الطلبات",
    kundenanteilAuftraegeHinweis: "قيم الطلبات لكل عميل",
    kundenanteilRechnungen: "حصة العملاء من الفواتير",
    kundenanteilRechnungenHinweis: "الفواتير ناقص الإشعارات الدائنة لكل عميل",
    restkunden: (anzahl: number) => `بقية العملاء (${anzahl})`,
    rest: "الباقي",
    weitereKunden: (anzahl: number) => `عرض ${anzahl} إضافيين`,
    nurTop3: "عرض أعلى 3 فقط",
    umsatzIn: (zeitraum: string) => `الإيرادات ${zeitraum}`,
  },
  aktivitaet: {
    titel: "نشاط المبيعات",
    jeWoche: (von: string, bis: string) => `لكل أسبوع تقويمي، من ${von} إلى ${bis}`,
    ladeFehler: (meldung: string) => `تعذّر تحميل نشاط المبيعات: ${meldung}`,
    leer: "لا اتصالات ولا عروض ولا مهتمّون في هذه الفترة.",
    kw: (woche: string) => `الأسبوع ${woche}`,
    ziel: (wert: string) => `الهدف ${wert} / أسبوع`,
    erstkontakte: "الاتصالات الأولى",
    erstkontakteHinweis: "الاتصالات المنجزة من النوع ERS",
    besuche: "الزيارات",
    besucheHinweis: "الميدانية وعبر الإنترنت كلٌّ على حدة",
    besucheOrt: "ميدانية",
    besucheOnline: "عبر الإنترنت",
    interessenten: "المهتمّون",
    interessentenHinweis: "مسجّلون حديثاً، دون إسناد إلى مندوب",
    angebote: "العروض",
    angeboteHinweis: "مجموع العروض المكتوبة",
    auftragseingang: "الطلبات الواردة",
    auftragseingangHinweis: "بعد خصم عمليات الإلغاء",
  },
  einkauf: {
    keineDaten: "لا توجد بنود توريد لهذه الفترة",
    ladeVor: "ارفع تصدير الالتزام بالتسليم في ",
    ladeNach: ".",
    otd: "نسبة OTD",
    otdHinweis: (ziel: string) => `الهدف ${ziel} · في الموعد: تأخير ≤ 0`,
    puenktlich: "البنود في موعدها",
    gesamt: "إجمالي البنود",
    verzugSchnitt: "متوسط التأخير",
    verzugHinweis: "دون البنود بلا قيمة تأخير",
    verlauf: "نسبة OTD عبر الزمن",
    verlaufHinweis: "الفجوات فترات بلا بنود توريد.",
    verlaufTooltip: (positionen: string) => `OTD (${positionen} بنود)`,
    ziellinie: "الهدف",
    ladenhueter: "طلبات للمخزون — أصناف راكدة",
    kapital: (wert: string) => `رأس المال المجمّد: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `أصناف مخزون بلا حركة منذ ${tage} يوماً على الأقل، الأعلى قيمةً أولاً. ` +
      "التاريخ المرجعي هو اليوم — الفترة أعلاه لا تنطبق هنا، لأن الرصيد ليس فترة.",
    artikel: "الصنف",
    bezeichnung: "الوصف",
    bestand: "الرصيد",
    liegtSeit: "راكد منذ",
    stueckpreis: "سعر الوحدة",
    wert: "القيمة",
    positionen: "بنود التوريد",
    positionenHinweis: "الأطول تأخيراً أولاً، والبنود بلا قيمة تأخير في الأعلى.",
    auftrag: "الطلب",
    lieferant: "المورّد",
    zieltermin: "الموعد المستهدف",
    geliefert: "تم التسليم",
    verzug: "التأخير",
    menge: "الكمية",
  },
  produktion: {
    keineDaten: "لا يوجد طلب محدَّد النتيجة في هذه الفترة",
    ladeVor: "ارفع بنود الطلبات وإشعارات التسليم في ",
    ladeNach:
      ". كلاهما مطلوب: ملف يحمل الموعد المستهدف، والآخر التاريخ الفعلي.",
    quote: "نسبة التأخير",
    quoteHinweis: (ziel: string) => `${ziel} كحدٍّ أقصى`,
    inVerzug: "طلبات متأخرة",
    davonOffen: (anzahl: string) => `منها ${anzahl} مفتوحة ومتأخرة`,
    gesamt: "إجمالي الطلبات",
    gesamtHinweis: "دون المفتوحة التي لم يحل موعدها",
    verzugSchnitt: "متوسط التأخير",
    verzugHinweis: "الطلبات في موعدها بقيمة سالبة",
    verlauf: "نسبة التأخير عبر الزمن",
    verlaufHinweis: "حسب الموعد المستهدف. الفجوات فترات بلا طلبات محتسبة.",
    verlaufTooltip: (auftraege: string) => `التأخير (${auftraege} طلبات)`,
    ziellinie: "الهدف",
    ansicht: "عرض الطلبات",
    ansichtVerzug: "طلبات متأخرة",
    ansichtUeberfaellig: "طلبات مفتوحة متجاوزة الموعد",
    hinweisVerzug: "سُلّمت بعد الموعد المستهدف، الأطول تأخيراً أولاً.",
    hinweisUeberfaellig: "بلا إشعار تسليم وقد فات الموعد — تزداد يومياً.",
    leerVerzug: "لم يُسلَّم أي طلب من هذه الفترة متأخراً.",
    leerUeberfaellig: "لا يوجد طلب مفتوح متجاوز للموعد في هذه الفترة.",
    auftrag: "الطلب",
    kunde: "العميل",
    zieltermin: "الموعد المستهدف",
    geliefert: "تم التسليم",
    verzug: "التأخير",
    tageUeberfaellig: "أيام التجاوز",
  },
  finanzen: {
    keineDatenVor:
      "يلزم ثلاثة ملفات: حركات المخزون للاستهلاك، وأسعار المواد (استلام البضائع) للأسعار، " +
      "والإيرادات كمرجع. الثلاثة كلها في ",
    keineDatenNach: ".",
    materialquote: "نسبة تكلفة المواد",
    materialquoteHinweis: "تكاليف المواد / الإيرادات",
    hoechstens: (ziel: string) => `${ziel} كحدٍّ أقصى`,
    materialkosten: "تكاليف المواد",
    umsatz: "الإيرادات",
    personalquote: "نسبة تكلفة العاملين",
    brauchtZeitraum: "تحتاج إلى فترة",
    ohnePreis: "أصناف بلا سعر",
    ohnePreisHinweis: "مستهلكة، لكن غير مقوَّمة",
    jeAbteilung: "تكاليف العاملين لكل قسم",
    abteilung: "القسم",
    personen: "الأشخاص",
    kosten: "التكاليف",
    anteil: "الحصة",
    verlauf: "نسبة تكلفة المواد عبر الزمن",
    verlaufHinweis: "الفجوات فترات بلا إيرادات — وبلا مرجع لا توجد نسبة.",
    ziellinie: "الهدف",
    verbrauch: "استهلاك المواد لكل صنف",
    verbrauchHinweis: "الأعلى تكلفةً أولاً. الأصناف بلا سعر في الآخر — وهي لا تدخل في النسبة.",
    artikel: "الصنف",
    bezeichnung: "الوصف",
    menge: "الاستهلاك",
    stueckpreis: "سعر الوحدة",
    keinPreis: "بلا سعر",
    ansicht: "العرض",
    ansichtMaterial: "المواد",
    ansichtPersonal: "العاملون",
    personalkosten: "تكاليف العاملين",
    personalquoteHinweis: "تكاليف العاملين / الإيرادات",
    mitarbeiter: "الموظفون",
    mitarbeiterHinweis: "ممن لهم تكاليف في الفترة",
    personalVerlauf: "نسبة تكلفة العاملين عبر الزمن",
    quoteBeiKosten: (kosten: string) => `النسبة عند تكاليف ${kosten}`,
  },
  qualitaet: {
    auditart: "نوع التدقيق:",
    reklamationsart: "نوع الشكوى",
    keineArt: "لم يُختر نوع تدقيق. اختر نوعاً واحداً على الأقل، وإلا فلا شيء يُحتسب.",
    keineDaten: "لا توجد نتائج تدقيق لهذه الفترة",
    ladeVor: "ارفع تصدير 8D في ",
    ladeNach: ".",
    behoerde: "جهة رسمية",
    extern: "خارجي",
    intern: "داخلي",
    kunde: "العميل",
    level1: "نتائج التدقيق من المستوى 1",
    level2: "نتائج التدقيق من المستوى 2",
    ohneLevel: "بلا مستوى واضح",
    ohneLevelHinweis: "لا تُحتسب في أي بطاقة",
    hoechstens: (ziel: number) => `${ziel} كحدٍّ أقصى`,
    auditVerlauf: "نتائج التدقيق عبر الزمن",
    auditVerlaufLevel: (level: number) => `نتائج التدقيق المستوى ${level} عبر الزمن`,
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `حصة الكمية بلا شكوى. المرجع: ${bezug}.`,
    fehlerquote: (quote: string) => `نسبة العيوب: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `نسبة العيوب: ${quote} · الهدف ${ziel}`,
    reklamiert: "الكمية المشكو منها",
    bezugsmenge: "الكمية المرجعية",
    bezugsmengeNull: "بدونها لا توجد نسبة",
    mehrAlsBezogen:
      "الكمية المشكو منها أكبر من الكمية المستلمة. الحساب لا يستطيع حل ذلك: " +
      "البسط والمقام يأتيان من ملفين مختلفين لكلٍّ منهما حقول تاريخ خاصة. تحقّق " +
      "من أن الملف المرجعي لهذه الفترة مرفوع كاملاً.",
    reklKunde: "العميل",
    reklIntern: "داخلي",
    reklLieferant: "مورّدو المواد",
    reklWerkbank: "ورش التصنيع",
    bezugKunde: "الكمية المسلَّمة",
    bezugIntern: "الكمية المسلَّمة",
    bezugLieferant: "استلام البضائع دون الخدمات",
    bezugWerkbank: "استلام البضائع لمجموعتي DIENST و SERVIC",
    mengeGesamt: "الكمية المبلَّغ عنها",
    mengeAkzeptiert: "الكمية المقبولة",
    onQualityBezug: (menge: string) => `On Quality (المرجع ${menge})`,
    ziellinie: "الهدف",
    geprueft: "المنتجات المفحوصة",
    geprueftHinweis: "الكمية لكل يوم فاحص. كل حجم يُقسَم على الأيام التي فُحص فيها، والإجمالي على جميعها.",
    gross: "منتجات كبيرة",
    klein: "منتجات صغيرة",
    mindestens: (ziel: number) => `${ziel} على الأقل لكل يوم وفاحص`,
    buchungen: "قيود فحص الجودة",
    buchungenHinweis: "القيد المستبعَد يبقى في القائمة لكنه لا يُحتسب في أي بطاقة.",
    zaehltMit: "يُحتسب",
    datum: "التاريخ",
    pruefer: "الفاحص",
    produkt: "المنتج",
    groesse: "الحجم",
    menge: "الكمية",
    ausschuss: "الهالك",
    mitzaehlen: (datum: string) => `احتساب قيد ${datum}`,
    klasseGross: "كبير",
    klasseKlein: "صغير",
    diagnose: "نتائج بلا مستوى واضح",
    diagnoseHinweis:
      "المستوى مكتوب في الملف المصدر كنصٍّ حر. إن لم يرد فيه «Major … Level 1» ولا " +
      "«Minor … Level 2»، فلا تُحتسب النتيجة في أي مكان. هذه القائمة تبيّن ما يلزم تصحيحه.",
    bericht: "التقرير",
    art: "النوع",
    adresse: "العنوان",
    bezeichnung: "الوصف",
    ansicht: "العرض",
    ansichtAudits: "التدقيقات",
    ansichtReklamationen: "الشكاوى",
    ansichtPruefung: "فحص الجودة",
    artikelart: "نوع الصنف",
    artikelFertig: "أصناف تامة الصنع",
    artikelHalbfertig: "أصناف نصف مصنعة",
    artikelAlle: "جميع الأصناف",
    gesamt: "الإجمالي",
    pruefVerlauf: (klasse: string) => `${klasse} عبر الزمن`,
    personentage: (anzahl: string) => `${anzahl} يوم فاحص`,
    findings: "نظرة عامة على النتائج",
    nr: "رقم",
    kategorie: "الفئة",
    level: "المستوى",
    aussteller: "المُصدِر",
    quelle: "المصدر",
    status: "الحالة",
    reklListe: (art: string) => `الشكاوى · ${art}`,
    akzMenge: "الكمية المقبولة",
    artikel: "الصنف",
  },
  personal: {
    uebersicht: "نظرة عامة",
    keinAbgleich: "لم تُجرَ أي مزامنة بعد. تعمل تلقائياً كل ليلة في 02:15.",
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} أشخاص، ${anwesenheiten} حضور، ${abwesenheiten} غياب`,
    abgleichLaeuft: "جارية …",
    abgleichen: "زامن الآن",
    keineDaten: "لا توجد سجلات حضور لهذه الفترة",
    keineDatenHinweis:
      "إما أن مزامنة Personio لم تعمل بعد، وإما أن الفترة تسبق بداية التسجيل.",
    ueberstunden: "نسبة العمل الإضافي",
    stundenVon: (teil: string, ganz: string) => `${teil} من ${ganz} ساعة`,
    krankheit: "نسبة المرض",
    krankheitsartenFehlen: "أنواع المرض غير مسجَّلة",
    fluktuation: "دوران العمالة",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} حالة مغادرة، بمتوسط ${schnitt} موظفاً`,
    personen: "الأشخاص المسجَّلون",
    personenHinweis: "ممن لديهم حضور في الفترة",
    krankheitHinweisVor:
      "تبقى نسبة المرض فارغة ما لم يُحدَّد أي أنواع غياب Personio تُحتسب مرضاً. " +
      "تُسجَّل في ",
    krankheitHinweisNach: ".",
    verlauf: "التطوّر",
    reiheUeberstunden: "العمل الإضافي",
    reiheKrankheit: "المرض",
    umsatzJeKopf: "الإيراد / موظف إنتاج",
    umsatzJeKopfHinweis: (auftraege: string, koepfe: string) => `${auftraege} طلبات ÷ ${koepfe} موظفين`,
    produktionFehlt: "أقسام الإنتاج غير محددة",
    abgleichStand: (datum: string, alter: string) => `مزامنة Personio ${datum} (${alter})`,
    abgleichFehler: "مع أخطاء",
    reiheUmsatzJeKopf: "الإيراد لكل موظف إنتاج",
    ziel: (wert: string) => `الهدف ${wert}`,
  },
  melden: {
    knopf: "أبلِغ عبر App Feedback",
    titel: "أبلِغ عبر App Feedback",
    frage: "ما الخطأ في هذه الصفحة؟ ترافق البلاغَ صورةٌ للصفحة.",
    abbrechen: "إلغاء",
    senden: "إرسال",
    sendet: "جارٍ الإرسال …",
    beispiel: "مثال: البطاقة تعرض قيمة فارغة رغم وجود بيانات.",
    beschreibung: "الوصف",
    aufnahme: "صورة الصفحة",
    gehtMit: "هذه الصورة ترافق البلاغ.",
    nimmtAuf: "جارٍ تصوير الصفحة …",
    misslungen: "تعذّر تصوير الصفحة — تُرسَل الملاحظات بلا صورة.",
    dankeMitBild: "شكراً — وصلت الملاحظات.",
    dankeOhneBild: "شكراً — وصلت الملاحظات، بلا صورة للصفحة.",
  },
  belegschaft: {
    titel: "القوى العاملة",
    ladeFehler: (meldung: string) => `تعذّر تحميل بيانات القوى العاملة: ${meldung}`,
    beschaeftigte: "الموظفون",
    beschaeftigteHinweis: "حسب حالة Personio «نشط»",
    stichtagHinweis: "الحالة اليوم — لا يحتفظ Personio بسجل تاريخي، لذلك لا يوجد مقارنة سنوية.",
    neuImQuartal: "جدد في هذا الربع",
    bestand: "العدد",
    kompetenzen: "الكفاءات المسجَّلة",
    felderFehlen: "الحقول غير مسجَّلة — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} من ${aktive} حسب تاريخَي الالتحاق والمغادرة`,
    geschlecht: "الجنس",
    beschaeftigungsart: "نوع التوظيف",
    abteilungen: "الأقسام",
    maennlich: "ذكر",
    weiblich: "أنثى",
    divers: "غير محدَّد",
    unbekannt: "مجهول",
    vollzeit: "دوام كامل",
    teilzeit: "دوام جزئي",
    geringfuegig: "عمل محدود",
    extern: "خارجي",
  },
  mitarbeiter: {
    titel: "الموظفون",
    person: "الشخص",
    abteilung: "القسم",
    istStunden: "الساعات الفعلية",
    ueberstunden: "العمل الإضافي",
    quote: "٪ إضافي",
    auswahl: "الاختيار",
    mitUeberstunden: "مع عمل إضافي",
    aktive: "النشطون",
    alle: "الكل",
    name: "الاسم",
    position: "المنصب",
    status: "الحالة",
    wochenstunden: "ساعات/أسبوع",
    leer: "لا أحد ضمن هذا الاختيار.",
    statusWert: { active: "نشط", inactive: "غير نشط", onboarding: "قيد الإعداد", leave: "في إجازة" },
  },
  wochenbericht: {
    titel: "التقرير الأسبوعي",
    ladeFehler: (meldung: string) => `تعذّر تحميل التقرير الأسبوعي: ${meldung}`,
    kalenderwoche: "الأسبوع التقويمي",
    kw: (woche: string, jahr: string) => `الأسبوع ${woche} / ${jahr}`,
    keineDaten: "لا توجد سجلات حضور لهذا الأسبوع.",
    saldo: "رصيد العمل الإضافي",
    saldoHinweis: (personen: string) => `الفعلي ناقص الهدف الفعلي، لكل الأشخاص الـ ${personen}`,
    ueberSoll: "فوق الهدف",
    ueberSollHinweis: (gesamt: string) => `من ${gesamt} شخصاً سجّلوا حضورهم`,
    krankheit: "المرض",
    tage: "أيام",
    stunden: "ساعة",
    krankheitHinweis: "موزَّعة على أيام الغياب التقويمية",
    ist: "الفعلي",
    soll: "الهدف",
    saldoSpalte: "الرصيد",
    fussnote:
      "الهدف هو الهدف الأسبوعي الفعلي: الإجازة والمرض مخصومان، ومن يغيب بلا عذر يكون " +
      "في السالب. في الأسبوع الجاري يُحتسب الهدف حتى آخر يوم مسجَّل فقط.",
    diagrammUeberstunden: "العمل الإضافي لكل شخص",
    diagrammKrankheit: "المرض لكل شخص",
    spitzeHinweis: "أعلى خمس قيم في الأسبوع",
    keineWerte: "لا قيم في هذا الأسبوع",
    pdf: "تصدير كملف PDF",
    pdfLaeuft: "جارٍ إنشاء PDF …",
    seite: (seite: number, gesamt: number) => `صفحة ${seite} من ${gesamt}`,
    erstellt: (zeitpunkt: string) => `أُنشئ في ${zeitpunkt}`,
    einheit: "وحدة المرض",
  },
  titel: {
    schulung: "تدريب",
    zeugnis: "شهادة عمل",
    qualifikationsmatrix: "مصفوفة المؤهلات",
    maschine: "آلة",
    audit: "تدقيق",
    zeichnung: "رسم هندسي",
    lieferung: "توريد",
    offeneSchulungen: "التدريبات المتبقّية",
    schulungsmatrix: "مصفوفة التدريب",
    atrLieferungen: "توريدات ATR",
    atrTeilekatalog: "كتالوج قطع ATR",
    kpiBewertung: "تقييم KPI والإجراءات",
    anmelden: "تسجيل الدخول",
  },
  uploads: {
    dateiWaehlen: "اختر ملفاً",
    verarbeitet: "جارٍ المعالجة …",
    uebersprungen: (datei: string) => `أسطر متجاوَزة من «${datei}»`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `تم اعتماد ${gesamt} سطر، وتجاوز ${fehler}. الأسطر الباقية محفوظة.`,
    zeile: "السطر",
    spalte: "العمود",
    grund: "السبب",
    zuletzt: "أحدث ما رُفع",
    datei: "الملف",
    art: "النوع",
    zeilen: "الأسطر",
    uebersprungenSpalte: "متجاوَز",
    status: "الحالة",
    zeitpunkt: "الوقت",
    nochNichts: "لم يُرفع شيء بعد.",
    keineZeile: (datei: string) => `«${datei}» لا يحتوي على سطر صالح.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `تم اعتماد «${datei}»، وتجاوز ${fehler} سطر.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `تم اعتماد «${datei}»: ${neu} جديد، ${aktualisiert} محدَّث.`,
    fehlgeschlagenMeldung: (meldung: string) => `فشل الرفع: ${meldung}`,
    vollstaendig: "كامل",
    teilweise: "جزئي",
    fehlgeschlagen: "فاشل",
    arten: {
      umsatz: "الإيرادات (فواتير وإشعارات دائنة)",
      umsatzText: "تغذّي بطاقة الإيرادات وتطوّرها. الإشعارات الدائنة سالبة في الملف.",
      auftraege: "الطلبات الواردة",
      auftraegeText: "تغذّي متوسط قيمة الطلب وإجمالي الطلبات والتحليل لكل مُدخِل.",
      auftragspositionen: "بنود الطلبات",
      auftragspositionenText:
        "تحمل الموعد المستهدف لكل بند. ومع إشعارات التسليم ينتج عنها التأخير.",
      lieferscheine: "إشعارات التسليم",
      lieferscheineText: "تحمل تاريخ التسليم الفعلي. ملف Excel، سطر لكل بند إشعار تسليم.",
      wareneingaenge: "استلامات البضائع",
      wareneingaengeText:
        "الكمية المرجعية لنسبة العيوب في جانب المشتريات. مجموعة السلع تفصل مورّدي المواد عن ورش التصنيع.",
      acht_d: "تقارير 8D",
      acht_dText:
        "نتائج التدقيق والشكاوى في ملف واحد. مستوى النتيجة مكتوب كنصٍّ حر ويُستنتج عند القراءة.",
      lagerbewegungen: "حركات المخزون",
      lagerbewegungenText:
        "الاستهلاك لكل صنف لحساب نسبة تكلفة المواد. تستبدل كل الأسطر ضمن المدى الزمني للملف.",
      materialpreise: "أسعار المواد (استلام البضائع)",
      materialpreiseText:
        "أسعار نسبة تكلفة المواد: لكل صنف يُعتمد أحدث استلام. تُحدِّث البنود المطابقة وتضيف الجديدة ولا تحذف شيئاً.",
      lagerpreise: "أسعار أصناف المخزون",
      lagerpreiseText:
        "بيانات أساسية لتقويم المخزون. تستبدل قائمة الأسعار كاملةً، لا الأصناف الواردة فيها فقط.",
      pruefungen: "فحص الجودة",
      pruefungenText:
        "قيود الفحص. تستبدل كل الأسطر ضمن المدى الزمني للملف — والقيود المستبعَدة يدوياً في هذا المدى تعود فتُحتسب.",
      liefertreue: "الالتزام بمواعيد التسليم (المشتريات)",
      liefertreueText:
        "تغذّي نسبة OTD في المشتريات. سطر لكل بند توريد؛ تاريخ التسليم الفعلي يحدد الفترة.",
      kontakte: "الاتصالات (المبيعات)",
      kontakteText:
        "الاتصالات الأولى والزيارات لكل أسبوع. تستبدل كل الأسطر ضمن المدى الزمني للملف — ورفع الفترة نفسها ثانيةً لا يضاعف شيئاً.",
      angebote: "العروض",
      angeboteText:
        "حجم العروض لكل أسبوع ومندوب. العروض بلا مُدخِل لا تظهر في أي عمود.",
      interessenten: "المهتمّون",
      interessentenText:
        "البيانات الأساسية للمهتمّين. المهتمّ الذي يُحفظ من جديد ينتقل بتاريخه الجديد إلى أسبوع آخر.",
    },
  },
  organigramm: {
    suchfeld: "شخص أو منصب أو قسم",
    suchePlatzhalter: "الاسم، المنصب، القسم",
    standort: "الموقع",
    alleStandorte: "كل المواقع",
    personen: (anzahl: number) => `${anzahl} شخصاً`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} بلا رئيس`,
    niemand: "لم يُعثر على أحد",
    niemandText: "جرّب بحثاً آخر أو موقعاً آخر — أو أن مزامنة Personio لم تعمل بعد.",
    aufklappen: (name: string) => `توسيع ${name}`,
    zuklappen: (name: string) => `طيّ ${name}`,
    direkt: (anzahl: number) => `${anzahl} مباشرون`,
    treffer: (anzahl: number) => ` · ${anzahl} نتائج`,
    kontext: "بإطار: النتائج. باهت: المسؤولون للسياق.",
  },
  offeneSchulungen: {
    einleitung: "من يحتاج إلى ماذا. التدريبات النشطة فقط؛ الموقوفة لم تعد تظهر هنا.",
    zumKatalog: "إلى الكتالوج",
    allesOffene: "كل المتبقّي",
    nieAbsolviert: "لم يُنجَز قط",
    ueberfaellig: "متأخر",
    wirdFaellig: "يقترب موعده",
    suchen: "ابحث عن شخص أو تدريب",
    suchenAria: "بحث",
    nichtsOffen: "لا شيء متبقٍّ",
    nichtsOffenText: "كل التدريبات النشطة ضمن دورتها — أو أنه لم يُقرأ شيء بعد.",
    eintraege: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "مدخل" : "مدخلات"}.`,
    person: "الشخص",
    schulung: "التدريب",
    bereich: "المجال",
    zuletzt: "آخر مرة",
    faellig: "الاستحقاق",
    stand: "الحالة",
    nie: "لم يُنجَز قط",
    imTurnus: "ضمن الدورة",
  },
  schulungsmatrix: {
    einleitung:
      "كل الأشخاص مقابل كل التدريبات — النظرة العامة للوحة الإعلانات وللتدقيق. " +
      "ومن لم يشارك في شيء إطلاقاً يظهر بسطر فارغ؛ وهذه بالضبط هي الثغرة " +
      "التي نبحث عنها.",
    wasOffenIst: "ما هو متبقٍّ",
    katalog: "الكتالوج",
    suchfeld: "شخص أو قسم",
    suchePlatzhalter: "الاسم، القسم، الرقم الوظيفي",
    bereich: "المجال",
    alleBereiche: "كل المجالات",
    nurLuecken: "الأشخاص ذوو الثغرات فقط",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} من ${gesamt} شخصاً · ${schulungen} تدريباً`,
    niemand: "لا يوجد شخص مطابق",
    niemandText: "جرّب بحثاً آخر أو مجالاً آخر — أو أنه لا أحد متبقٍّ فعلاً.",
    person: "الشخص",
    nichtZugewiesen: (person: string, schulung: string) =>
      `${person} · ${schulung}: غير مُسنَد`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (يستحق ${datum})`,
    offen: "متبقٍّ",
    personio: "Personio",
    externGepflegt: "مُدار خارجياً",
    ohneTreffer: "بلا تطابق في Personio",
  },
  schulungen: {
    dokumentenlauf: "دورة المستندات",
    bereich: "المجال",
    neueSchulung: "تدريب جديد",
    beispiel: "مثلاً: تعليمات الحماية من الحريق",
    anlegen: "أنشئ",
    wirdGelesen: "جارٍ القراءة …",
    uebersichtEinlesen: "اقرأ النظرة العامة",
    einlesenAria: "قراءة النظرة العامة للتدريبات",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} تدريباً (${neu} جديد)، ${teilnahmen} مشاركة، منها ${zugeordnet} مسنَدة إلى شخص في Personio.`,
    ohneTreffer: "بلا تطابق في Personio: ",
    ohneTrefferNach: ". هذه الأسطر تُنقل مع ذلك بالرقم الوظيفي والاسم.",
    wirdUebernommen: "جارٍ الاعتماد …",
    uebernehmen: "اعتمد",
    abbrechen: "إلغاء",
    keineSchulung: "لا تدريب بعد",
    keineSchulungText: "أنشئ تدريباً أو اقرأ النظرة العامة للتدريبات.",
    schulung: "التدريب",
    turnus: "الدورة",
    frist: "المهلة (أيام)",
    verantwortlich: "المسؤول",
    offen: "متبقٍّ",
    aktiv: "نشط",
    nichtBerechenbar: "(غير قابل للحساب)",
    zahlGroesserNull: "أدخل رقماً أكبر من 0.",
    nieKurz: (anzahl: number) => `${anzahl} لم يُنجَز`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} متأخر`,
    baldKurz: (anzahl: number) => `${anzahl} قريباً`,
    aktivSchalter: (name: string) => `${name} نشط`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} يعني: لا يوجد موعد لهذا الشخص في السجل. ${bald} يعني: خلال الشهرين القادمين. الحالة بتاريخ ${datum}.`,
  },
  schulungenReg: {
    tabBearbeiten: "تحرير التدريب",
    tabZuweisen: "إسناد تدريب",
    tabStand: "حالة الموظفين",
    anforderungsmatrix: "مصفوفة المتطلبات",
    ebene: "المستوى",
    matrixLeer: "لا توجد بيانات للمصفوفة بعد.",
    einzelTitel: "إسناد تدريب فردي",
    einzelHinweis: "يكمّل مصفوفة المتطلبات التي تعمل على مستوى الإدارة — للأفراد.",
    mitarbeiterWaehlen: "اختر موظفًا",
    schulungWaehlen: "اختر تدريبًا",
    zuweisenAktion: "إسناد",
    zugewiesen: "تم إسناد التدريب.",
    schonZugewiesen: "هذا التدريب مُسنَد للشخص بالفعل.",
    sammelTitel: "تسجيل كمنفَّذ (جماعي)",
    sammelHinweis: "تدريب واحد، تاريخ واحد، عدة مشاركين. تحتفظ السجلات المكتملة بتاريخها، ويحل تاريخ أحدث محله.",
    durchgefuehrtAm: "نُفِّذ في",
    teilnehmerSuche: "بحث عن مشاركين",
    standort: "الموقع",
    offeneTitel: "تدريبات مفتوحة",
    abteilung: "الإدارة",
    frist: "الاستحقاق",
    mitarbeiterTitel: "نظرة عامة على الموظفين",
    anzahl: "العدد",
    naechste: "الاستحقاق التالي",
    matrixTitel: "المصفوفة الإجمالية",
    abteilungenTitel: "الإدارات والمشرفون",
    vorgesetzter: "المشرف المسؤول",
    abteilungenHinweis: "يُشتق المشرف من Personio؛ فإن لم يوجد يبقى العمود فارغًا.",
    sammelAktion: (anzahl: number) => `تسجيل ${anzahl} كمنفَّذ`,
    sammelErfolg: (eingetragen: number, unveraendert: number) =>
      `${eingetragen} مُسجَّل${unveraendert ? `، ${unveraendert} دون تغيير` : ""}.`,
    seit: (tage: number) => `منذ ${tage} يوم`,
    in: (tage: number) => `خلال ${tage} يوم`,
  },
  schulung: {
    gibtEsNicht: "هذا التدريب غير موجود",
    gibtEsNichtText: "على الأرجح أنه أُزيل.",
    ohneTurnus: "بلا دورة",
    keineFaelligkeit: " — لا يمكن حساب موعد استحقاق من ذلك",
    zumKatalog: "إلى الكتالوج",
    stammdaten: "البيانات الأساسية",
    turnus: "الدورة",
    turnusBeispiel: "مثلاً: سنوياً",
    turnusHinweis: "النص؛ أما عدد الأشهر فيأتي من القراءة.",
    turnusMonate: "الدورة بالأشهر",
    monateHinweis: "الفراغ يعني: لا يمكن حساب موعد استحقاق.",
    verantwortlich: "المسؤول",
    beschreibung: "الوصف",
    fuerWen: "على من هو إلزامي؟",
    kuerzel: "رمز القسم",
    kuerzelHinweis: "النظام التفصيلي المأخوذ من ملف Excel ‏(NÄH, CUT, WVK …).",
    personioAbteilung: "قسم Personio",
    personioHinweis: "القسم العام كما يحفظه Personio.",
    entfernen: (was: string) => `أزل ${was}`,
    keine: "لا شيء",
    ergaenzen: (was: string) => `أضف ${was}`,
    hinzufuegen: "أضف",
    teilnahmen: "المشاركات",
    nochNiemand: "لا أحد بعد — اقرأ النظرة العامة للتدريبات أو أدخل شخصاً.",
    person: "الشخص",
    abteilungKurz: "القسم",
    erstschulung: "التدريب الأول",
    zuletzt: "آخر مرة",
    faellig: "الاستحقاق",
    stand: "الحالة",
    keinTreffer: "لا تطابق في Personio — يبقى السطر مع ذلك",
    nichtInPersonio: "غير موجود في Personio",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "هذه المشاركة",
    personErgaenzen: "أضف شخصاً",
    nameForm: "اسم العائلة، الاسم الأول",
  },
  kompetenzen: {
    zumDashboard: "إلى لوحة شؤون الموظفين",
    bereich: "المجال",
    wirdGelesen: "جارٍ القراءة …",
    einlesen: "اقرأ ملف المجال",
    vorschauKopf: (datei: string, bereich: string) => `${datei} — هكذا سيبدو ${bereich} بعدها:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} مؤهلاً، ${personen} شخصاً، ${bewertungen} تقييماً.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `عُثر على ${zugeordnet} من ${personen} شخصاً في Personio`,
    platzhalter: (anzahl: number) =>
      `، ${anzahl} ${anzahl === 1 ? "عمود نائب" : "أعمدة نائبة"}`,
    ohneZuordnung: (namen: string) => ` بلا إسناد: ${namen}.`,
    ersetztWarnung:
      "تُستبدل الأوراق المعنية بالكامل — وما أُدير هنا من تعديلات يضيع في هذه العملية.",
    wirdUebernommen: "جارٍ الاعتماد …",
    uebernehmen: "اعتمد",
    abbrechen: "إلغاء",
    keineMatrix: "لا مصفوفة بعد",
    keineMatrixText: "اقرأ ملف مجال — كل ورقة فيه تصبح مصفوفة.",
    blatt: "الورقة",
    titelSpalte: "العنوان",
    stand: "الحالة",
    eingelesen: "قُرئ في",
    produktion: "الإنتاج",
    verwaltung: "الإدارة",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    bausteineTitel: "القوالب النصية",
    bausteineHinweis: "صياغة واحدة لكل مجال تقييم ودرجة. يُحفظ المتغيّر فقط؛ ويُستبدل [NAME] والضمائر عند الإنشاء.",
    speichern: "حفظ",
    gespeichert: "تم الحفظ.",
    note1: "ممتاز",
    note2: "جيد",
    note3: "مُرضٍ",
    note4: "مقبول",
    person: "الشخص",
    waehlen: "— اختر —",
    art: "النوع",
    anlegen: "أنشئ",
    keines: "لا شهادة بعد",
    keinesText: "اختر شخصاً ونوع الشهادة — تأتي البيانات الأساسية من تلقاء نفسها.",
    zeitraum: "الفترة",
    note: "الدرجة",
    stand: "الحالة",
    angelegt: "أُنشئت",
    fertig: "جاهزة",
    entwurf: "مسودة",
    qualifiziert: "شهادة عمل مفصَّلة",
    einfach: "شهادة عمل بسيطة",
    zwischenzeugnis: "شهادة عمل مؤقتة",
    ausbildungszeugnis: "شهادة تدريب مهني",
    praktikumszeugnis: "شهادة تدريب عملي",
  },
  einarbeitung: {
    einleitung:
      "ما يجب أن يتعلمه الشخص الجديد ومن يشرحه له. تُبنى الاستمارة من البنود " +
      "المسجَّلة لقسمه.",
    bogenErzeugen: "أنشئ الاستمارة",
    person: "الشخص",
    waehlen: "— اختر —",
    wirdGebaut: "جارٍ البناء …",
    einarbeitungsplan: "خطة التأهيل",
    keineInhalte: "لا بنود مسجَّلة بعد — ستبقى الاستمارة فارغة.",
    abteilungVon: (abteilung: string) => `قسم ${abteilung}`,
    neuerInhalt: "بند جديد",
    beispiel: "مثلاً: تعليمات السلامة على آلة التفريز",
    anlegen: "أنشئ",
    keinInhalt: "لا بند بعد",
    keinInhaltText:
      "حدّد ما يجب أن يتعلمه الشخص الجديد — ولأي الأقسام ينطبق ذلك.",
    inhalt: "البند",
    ansprechpartner: "جهة الاتصال",
    bereich: "المجال",
    fuerAbteilungen: "لأي الأقسام",
    abteilung: "القسم",
    bereichLeer: "الفراغ يعني: استخدم القسم من المصفوفة",
    entfernen: (was: string) => `أزل ${was}`,
    abteilungHinzu: "+ قسم",
    abteilungFuer: (inhalt: string) => `قسم لـ ${inhalt}`,
  },
  matrix: {
    bearbeiten: "تحرير",
    bearbeitenFertig: "تم",
    ohneKategorie: "بدون فئة",
    gibtEsNicht: "هذه المصفوفة غير موجودة",
    gibtEsNichtText: "على الأرجح أنها استُبدلت.",
    blattStand: (blatt: string) => `الورقة ${blatt}`,
    stand: (datum: string) => ` · الحالة بتاريخ ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} مؤهلاً، ${personen} شخصاً`,
    zurUebersicht: "إلى النظرة العامة",
    qualifikation: "المؤهل",
    keineZeilen: "هذه المصفوفة بلا أسطر بعد.",
    stufenBedeuten: "معنى الدرجات",
    erfuellungsgradHinweis:
      "الرقم الثاني هو درجة الاستيفاء بالنسبة المئوية. الخانة التي لها متطلب واستيفاء " +
      "أقل من 100 ٪ تُعدّ ثغرة وتظهر بلون التحذير.",
    ergaenzen: "أضف",
    neueQualifikation: "مؤهل جديد",
    beispiel: "مثلاً: المخرطة",
    kategorie: "الفئة",
    ohne: "بلا",
    zeile: "السطر",
    neuePerson: "شخص جديد",
    namensform: "الاسم الأول واسم العائلة",
    spalte: "العمود",
    anforderungslevel: "مستوى المتطلب",
    erfuellungsgrad: "درجة الاستيفاء بالنسبة المئوية",
    stufe0: "غير مطلوب",
    stufe1: "معرفة أساسية",
    stufe2: "يعمل تحت إشراف",
    stufe3: "يعمل باستقلالية",
    stufe4: "يستطيع الإرشاد والتدريب",
  },
  zeugnis: {
    gibtEsNicht: "هذه الشهادة غير موجودة",
    gibtEsNichtText: "على الأرجح أنها حُذفت.",
    durchschnitt: (wert: string) => ` · المتوسط ${wert}`,
    zurUebersicht: "إلى النظرة العامة",
    zeugnisVon: (name: string) => `شهادة ${name}`,
    stammdaten: "البيانات الأساسية",
    stammdatenHinweis:
      "نُسخت عند إنشاء الشهادة. التعديلات هنا تسري على هذه الشهادة وحدها — " +
      "ويبقى Personio على حاله.",
    name: "الاسم",
    personalnummer: "الرقم الوظيفي",
    abteilung: "القسم",
    taetigkeit: "المهمة",
    eintritt: "تاريخ الالتحاق",
    austritt: "تاريخ المغادرة",
    geburtsdatum: "تاريخ الميلاد",
    ausstellungsdatum: "تاريخ الإصدار",
    ohneNamen: "لا يمكن المتابعة بلا اسم.",
    anrede: "صيغة المخاطبة",
    frau: "السيدة",
    herr: "السيد",
    anredeHinweis: "تحدّد المخاطبة والضمائر في النص.",
    art: "النوع",
    anlass: "السبب",
    anlassBeispiel: "مثلاً: بناءً على رغبته",
    fuehrungskraft: "قيادي",
    fuehrungskraftHinweis: "قيادي — يُظهر بُعد «القيادة»",
    bewertung: "التقييم",
    bewertungHinweis:
      "درجات مدرسية من 1 إلى 4. صيغة الرضا تنبع من المتوسط — لا العكس.",
    fachwissen: "المعرفة المهنية",
    auffassungsgabe: "سرعة الفهم",
    arbeitsweise: "أسلوب العمل",
    belastbarkeit: "تحمّل الضغط",
    arbeitserfolg: "نتائج العمل",
    sozialverhalten: "السلوك مع الآخرين",
    fuehrung: "القيادة",
    aufgaben: "المهام (نقاط)",
    aufgabenHinweis: "مهمة واحدة في كل سطر — منها تنشأ القائمة في الشهادة.",
    kompetenzen: "كفاءات خاصة",
    kompetenzenHinweis: "تدخل في تقييم الأداء.",
    erfolge: "إنجازات خاصة",
    erfolgeHinweis: "مشاريع، تكريمات، نتائج قابلة للقياس.",
    text: "النص",
    baut: "جارٍ البناء …",
    ausBausteinen: "من وحدات جاهزة",
    formuliert: "جارٍ الصياغة …",
    mitKi: "بالذكاء الاصطناعي",
    textHinweis:
      "الوحدات الجاهزة تكتب بلا شبكة وبلا ذكاء اصطناعي. الذكاء الاصطناعي يصوغ بحرية أكبر — " +
      "ولا يصله سوى المخاطبة والدور والقسم والمدة والدرجات والنصوص الحرة أعلاه. الاسم " +
      "وتاريخ الميلاد والرقم الوظيفي لا تغادر الخادم.",
    nochKeinText: "لا نص بعد. امنح الدرجات ودع النص يُصاغ.",
    fertigSchalter: "الشهادة جاهزة",
    fertigHinweis: "جاهزة — لم تعد قيد العمل",
    unterschriftenFehler: (meldung: string) => `تعذّر تحديد التوقيعات (${meldung}).`,
    darunterSteht: "يوقّع أدناه",
    fachlich: "الرئيس المباشر",
    personalwesen: "شؤون الموظفين",
    niemandHinterlegt: "— لا أحد مسجَّل —",
    unterschriftFehlt:
      "ينقص توقيع. سجّله في الإعدادات ← شهادات العمل، أو أدخل الرئيس في Personio.",
    ausPersonio: "من Personio",
    ausEinstellungen: "من الإعدادات",
    nichtHinterlegt: "غير مسجَّل",
    einleitung: "المقدمة",
    taetigkeitsbeschreibung: "وصف المهام",
    leistungsbeurteilung: "تقييم الأداء",
    schlussformel: "الصيغة الختامية",
    hinweisDeutsch: "شهادة العمل نفسها تُكتب بالألمانية.",
  },
  dokumentenlauf: {
    erstelltAm: "أُنشئ",
    uebergebenAm: "سُلِّم",
    zurueckAm: "أُعيد",
    geprueftAm: "فُحص",
    aktionen: "إجراءات",
    einleitung:
      "استمارات برمز QR: إنشاء، تسليم، استرجاع بعد التعبئة، فحص. رمز QR يعيد ربط " +
      "المسح الضوئي — أياً كان اسم الملف.",
    formblatt: "الاستمارة",
    fuerWen: "لمن",
    personWaehlen: "— اختر شخصاً —",
    erzeugt: "جارٍ الإنشاء …",
    blattErzeugen: "أنشئ استمارة",
    standFilter: "الحالة:",
    alle: "الكل",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} من ${gesamt}`,
    keinVorgang: "لا معاملة",
    keinVorgangText:
      "أنشئ استمارة في الأعلى — تحصل على رمز QR وتُتابَع من تلك اللحظة.",
    person: "الشخص",
    kennung: "الرمز",
    stand: "الحالة",
    vollstaendigSpalte: "مكتملة",
    blatt: "الاستمارة",
    scan: "المسح",
    prueft: "جارٍ الفحص …",
    scanFuer: (name: string) => `ارفع المسح الخاص بـ ${name}`,
    zu: "إغلاق",
    details: "التفاصيل",
    nochNichtGeprueft: "— لم تُفحص بعد",
    vollstaendig: "مكتملة",
    unvollstaendig: "ناقصة",
    umkehren: "اعكس الحكم — القياس يرى فقط ما إذا كان في الخانة حبر",
    pruefung: "الفحص",
    qrGelesen: "— قُرئ رمز QR",
    keinQr: "— لم يُعثر على رمز QR، لا يمكن إسناد الخانات",
    nachweise: "الإثباتات",
    keineNachweise: "لا شيء مسجَّل بعد.",
    welcheZeile: "لأي سطر؟ (اختياري)",
    laedt: "جارٍ الرفع …",
    nachweis: "الإثبات",
    nachweisHoch: "ارفع إثباتاً",
    erstellt: "أُنشئت",
    uebergeben: "سُلّمت",
    zurueck: "أُعيدت",
    geprueft: "فُحصت",
    einarbeitungsplan: "خطة التأهيل",
    schulungsnachweis: "إثبات التدريب",
  },
  onboarding: {
    aktive: "النشطون",
    personenwahl: "أي الأشخاص",
    eintritteTitel: "المنضمون الجدد",
    inhalteTitel: "محتويات التأهيل",
    matrixTitel: "مصفوفة التأهيل",
    matrixHinweis: "أي محتوى تحتاجه كل إدارة. تسري العلامة فورًا.",
    matrixLeer: "لا توجد محتويات أو إدارات بعد.",
    vorgaengeTitel: "إجراءات التأهيل والتدريب",
    matrixZelle: (inhalt: string, abteilung: string) => `${inhalt} – ${abteilung}`,
    nichtsGefehlt: "لم ينقص شيء.",
    angelegt: (anzahl: number) => `أُنشئ ${anzahl} ${anzahl === 1 ? "تدريب" : "تدريباً"}.`,
    neu90: "جدد (آخر 90 يوماً)",
    alle: "الكل",
    personen: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "شخص" : "شخصاً"}`,
    keineEintritte: "لا التحاقات",
    keineEintritteText: "ما إن يأتي من Personio شخص له تاريخ التحاق حتى يظهر هنا.",
    person: "الشخص",
    abteilung: "القسم",
    position: "المنصب",
    eintritt: "تاريخ الالتحاق",
    uebergabe: "التسليم",
    nichtInPersonio: "غير موجود في Personio",
    hierGesetzt: "مضبوط هنا — يتجاوز Personio",
    ausPersonio: "من Personio",
    vermerken: "سجّل الإنجاز",
    paketTitel: "خطة التأهيل والنظرة العامة للتدريبات في ملف PDF واحد",
    paket: "الحزمة",
    uebersichtTitel: "النظرة العامة للتدريبات فقط (الاستمارة 71)",
    uebersicht: "النظرة العامة",
    planZu: "أغلق الخطة",
    plan: "الخطة",
    schulungsplan: "خطة التدريب",
    fehlendeAnlegen: "أنشئ الناقص",
    wirdGerechnet: "جارٍ الحساب …",
    bruecke: "المنصب ← رمز القسم",
    brueckeHinweis:
      "الجسر بين Personio والمستوى التفصيلي في مصفوفة المتطلبات. بلا مدخل لا ينطبق " +
      "المستوى التفصيلي على هذا المنصب — وتقول الخطة ذلك صراحةً.",
    kuerzel: "الرمز",
    positionBeispiel: "مثلاً: مشغّل CNC",
    kuerzelBeispiel: "CNC",
    zuordnen: "أسنِد",
    ohnePersonio: "شخص بلا Personio",
    ohnePersonioHinweis:
      "للملتحقين الذين لم يظهروا في المزامنة بعد — أو الذين لا مكان لهم فيها أصلاً.",
    name: "الاسم",
    anlegen: "أنشئ",
    kuerzelFehlt: (position: string) =>
      `لا رمز قسم مسجَّل للمنصب ${position}. لذلك لا ينطبق المستوى التفصيلي في ` +
      "مصفوفة المتطلبات على هذا الشخص — وقد تنقص تدريبات إلزامية.",
    matrixVerlangtNichts: "مصفوفة المتطلبات لا تطلب شيئاً لهذا القسم.",
    schulung: "التدريب",
    bereich: "المجال",
    turnus: "الدورة",
    pflichtUeber: "إلزامي عبر",
    stand: "الحالة",
    ueberAbteilung: "القسم",
    ueberKuerzel: "الرمز",
    vorhanden: "موجود",
    fehlt: "ناقص",
  },
  audit: {
    zuKennzahlen: "إلى المؤشرات",
    nummer: "الرقم",
    nummerBeispiel: "A-2026-01",
    titel: "العنوان",
    titelBeispiel: "تدقيق نظام EN 9100",
    art: "النوع",
    intern: "داخلي",
    extern: "خارجي",
    phasenvorlage: "قالب المراحل",
    ohne: "بلا",
    anlegen: "أنشئ",
    alle: "الكل",
    neuesAudit: "تدقيق جديد",
    geltungsbereich: "نطاق التطبيق",
    kategorie: "الفئة",
    leadAuditor: "المدقق الرئيسي",
    beginnGeplant: "البداية (مخطط)",
    endeGeplant: "النهاية (مخطط)",
    ohneVorlage: "بدون قالب (تُضاف المراحل لاحقًا)",
    vorlageHinweis:
      "تُنسخ مراحل القالب عند الإنشاء. تغيير القالب لاحقًا لا يغيّر هذا التدقيق.",
    kategoriePflicht: "اختر فئة واحدة على الأقل.",
    zeitraumFehler: "النهاية قبل البداية.",
    angelegt: "تم إنشاء التدقيق.",
    nummerVergeben: "رقم التدقيق هذا موجود بالفعل.",
    keinTreffer: "لا يوجد تدقيق يطابق هذا المرشح.",
    keinAudit: "لا تدقيق بعد",
    keinAuditText: "أنشئ واحداً — ومع قالب مراحل يأتي بقائمة التحقق معه.",
    laufen: (laufend: number, gesamt: number) => `${laufend} من ${gesamt} ما زالت جارية.`,
    status: "الحالة",
    fortschritt: "التقدّم",
    naechsterTermin: "الموعد التالي",
    ueberfaellig: (anzahl: number) => `${anzahl} متأخر`,
    geplant: "مخطط",
    inVorbereitung: "قيد التحضير",
    inDurchfuehrung: "قيد التنفيذ",
    berichtet: "تم التقرير",
    massnahmenOffen: "إجراءات مفتوحة",
    abgeschlossen: "مغلق",
    verschoben: "مؤجل",
    abgesagt: "ملغى",
    phaseOffen: "مفتوحة",
    phaseInArbeit: "قيد العمل",
    phaseErledigt: "منجزة",
    phaseNichtZutreffend: "لا تنطبق",
    system: "النظام",
    prozess: "العملية",
    produkt: "المنتج",
    lieferant: "المورّد",
  },
  wartung: {
    zuKennzahlen: "إلى المؤشرات",
    neueMaschine: "آلة جديدة",
    beispiel: "مثلاً: آلة تفريز 3",
    anlegen: "أنشئ",
    keineMaschine: "لا آلة بعد",
    keineMaschineText: "أنشئ آلة وسجّل مهام صيانتها.",
    maschine: "الآلة",
    inventarnummer: "رقم الأصل",
    standort: "الموقع",
    verantwortlich: "المسؤول",
    status: "الحالة",
    aktiv: "نشطة",
    stillgelegt: "موقوفة",
    angelegt: "تم إنشاء الآلة.",
  },
  sensoren: {
    misst: "جارٍ القياس …",
    jetztMessen: "قِس الآن",
    keinGeraet: "لا جهاز مُعدّ",
    keinGeraetText: "تُنشأ المستشعرات في الإعدادات — الخادم والمعرّف والـ Community.",
    verlauf: "التطوّر",
    stunden: (n: number) => `${n} س`,
    tage: (n: number) => `${n} يوماً`,
    temperatur: "الحرارة",
    luftfeuchte: "الرطوبة",
    zuletzt: (zeit: string) => `آخر قياس ${zeit}`,
    keinMesswert: "لا قياس بعد.",
    nichtsGemessen: "لم يُقَس شيء في هذه الفترة.",
    frisch: "حديث",
    verzoegert: "متأخر",
    offline: "غير متصل",
    unbekannt: "لم يُقَس شيء بعد",
    temperaturverlauf: "درجة الحرارة (°C)",
    feuchteverlauf: "الرطوبة (%)",
    mittelFuenfMinuten: "متوسطات كل 5 دقائق",
    mittelStunde: "متوسطات كل ساعة",
    minMax: (fenster: string) => `الأدنى/الأعلى ${fenster}`,
    ausserhalbGrenzen: "خارج الحدود",
    untergrenze: "الأدنى",
    obergrenze: "الأعلى",
    ladeFehler: "تعذر تحميل القياسات.",
  },
  hilfe: {
    nurDeutsch: "صفحات المساعدة نفسها مكتوبة بالألمانية.",
    suchen: "ابحث في المساعدة",
    nichtsGefunden:
      "لم يُعثر على شيء. إن كان شيء ناقصاً في المساعدة، قُله عبر «أبلِغ عبر App Feedback» أسفل اليسار.",
    alleThemen: "→ كل المواضيع",
    navigation: "مواضيع المساعدة",
  },
  meldungen: {
    stand: (offen: number) => `${offen} مفتوح`,
    neuSeit: (anzahl: number) => ` · ${anzahl} لم يُشاهَد بعد`,
    nichtsGemeldet: "لا App Feedback بعد",
    nichtsGemeldetText:
      "عبر «أبلِغ عبر App Feedback» أسفل اليسار يستطيع كل شخص مسجَّل الدخول أن يبلّغ عما لا يكون على ما يرام في صفحة.",
    unbekannt: "مجهول",
    status: "الحالة",
    offen: "مفتوح",
    inBearbeitung: "قيد المعالجة",
    erledigt: "منجز",
    meldung: "الملاحظة",
    aufnahme: "صورة الصفحة",
    ansicht: "العرض",
    tabelle: "جدول",
    kanban: "كانبان",
    gruppieren: "التجميع حسب",
    nachStatus: "الحالة",
    nachPerson: "الشخص",
    nichtZugewiesen: "غير مُسنَد",
    ziehenHinweis: "اسحب البطاقات إلى عمود آخر لتغيير الحالة أو المسؤول.",
    verschieben: (beschreibung: string) => `نقل: ${beschreibung}`,
    spalte: {
      datum: "التاريخ",
      von: "من",
      seite: "الصفحة",
      beschreibung: "الوصف",
      screenshot: "لقطة الشاشة",
      status: "الحالة",
      zugewiesen: "مُسنَد إلى",
      aktionen: "الإجراءات",
    },
    oeffnen: "افتح",
    ungesehen: "غير مُشاهَد",
    alsGesehen: "علّم كمُشاهَد",
    zuDieserSeite: "ملاحظات التطبيق لهذه الصفحة",
  },
  auditAnsicht: {
    gibtEsNicht: "هذا التدقيق غير موجود",
    gibtEsNichtText: "على الأرجح أنه أُزيل.",
    internesAudit: "تدقيق داخلي",
    externesAudit: "تدقيق خارجي",
    prioritaet: (stufe: string) => ` · الأولوية ${stufe}`,
    erledigt: (prozent: number) => ` · ${prozent} ٪ منجز`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} متأخر`,
    zurUebersicht: "إلى النظرة العامة",
    status: "الحالة",
    stammdaten: "البيانات الأساسية",
    titel: "العنوان",
    bereich: "نطاق التطبيق",
    leitenderAuditor: "المدقق الرئيسي",
    auditteam: "فريق التدقيق",
    geplantVon: "البداية (مخطط)",
    geplantBis: "النهاية (مخطط)",
    prioritaetFeld: "الأولوية",
    niedrig: "منخفضة",
    mittel: "متوسطة",
    hoch: "عالية",
    auditziel: "هدف التدقيق",
    kategorien: "الفئات",
    kategorienHinweis:
      "التدقيق كثيراً ما يكون عدة أشياء في آن واحد — فالبرنامج الداخلي يغطي النظام " +
      "والعملية في موعد واحد. لذلك اختيار متعدد لا مدخل واحد.",
    normbezug: "المرجع المعياري",
    normmatrixLeer: "مصفوفة المعايير فارغة — وتُدار في الإعدادات.",
    nichtGeprueft: "* لم يُراجَع بعد مقابل النص المعياري الموحَّد.",
    phasen: "المراحل",
    keinePhasen: "لا مراحل — أُنشئ هذا التدقيق بلا قالب.",
    phase: "المرحلة",
    verantwortlich: "المسؤول",
    faellig: "الموعد المخطط",
    erledigtAm: "الموعد الفعلي",
    phaseErgaenzen: "أضف مرحلة",
    phaseBeispiel: "مثلاً: تدقيق متابعة",
    verlauf: "السجل",
    verlaufHinweis:
      "تكتبه قاعدة البيانات لا هذه الشاشة — ولا يمكن بعدها تعديله ولا حذفه.",
    nichtsGeschehen: "لم يحدث شيء بعد.",
    warumEntfaellt: "لماذا تسقط هذه المرحلة الإلزامية؟",
    uebernehmen: "اعتمد",
    abbrechen: "إلغاء",
    angelegt: "أُنشئ",
    geaendert: "عُدّل",
    geloescht: "حُذف",
    uebersprungen: "تُجووز",
    bearbeiten: "تحرير",
    gespeichert: "تم الحفظ.",
    pflicht: "إلزامية",
    kommentar: "تعليق",
    begruendung: "سبب «غير منطبق»",
    grundPflicht: "لا يمكن تخطي مرحلة إلزامية إلا مع ذكر السبب.",
    datumPflicht: "«منجز» يتطلب موعدًا فعليًا.",
    phaseSpeichern: "حفظ المرحلة",
    phaseGespeichert: "تم حفظ المرحلة.",
  },
  maschine: {
    gibtEsNicht: "هذه الآلة غير موجودة",
    gibtEsNichtText: "على الأرجح أنها حُذفت.",
    zurUebersicht: "إلى النظرة العامة",
    stammdaten: "البيانات الأساسية",
    name: "الاسم",
    inventarnummer: "رقم الأصل",
    standort: "الموقع",
    hersteller: "الصانع",
    modell: "الطراز",
    verantwortlich: "المسؤول",
    status: "الحالة",
    aktiv: "نشطة",
    stillgelegt: "موقوفة",
    notizen: "ملاحظات",
    wartungsaufgaben: "مهام الصيانة",
    jahr: "السنة",
    halbjahr: "نصف السنة",
    erstesHalbjahr: "الأسابيع 1–26",
    zweitesHalbjahr: "الأسابيع 27–52",
    wirdGebaut: "جارٍ البناء …",
    nachweisbogen: "استمارة الإثبات",
    neueAufgabe: "مهمة جديدة",
    aufgabeBeispiel: "مثلاً: فحص مستوى الزيت",
    intervall: "الفاصل",
    wochen: "أسابيع",
    keineAufgabe: "لا مهمة بعد — ستبقى الاستمارة فارغة.",
    aufgabe: "المهمة",
    dateien: "الملفات",
    planHinterlegen: "أضف خطة",
    nachweisAblegen: "أضف إثباتاً",
    dateienHinweis: "خطة الصانع والاستمارات الموقَّعة الممسوحة ضوئياً.",
    keineDatei: "لا ملف بعد.",
    plan: "الخطة",
    nachweis: "الإثبات",
    laedt: "جارٍ الرفع …",
    taeglich: "يومياً",
    woechentlich: "أسبوعياً",
    monatlich: "شهرياً",
    quartalsweise: "ربع سنوي",
    alleNWochen: "كل N أسابيع",
    alleNWochenZahl: (wochen: number) => `كل ${wochen} أسابيع`,
    bearbeiten: "تحرير",
    gespeichert: "تم الحفظ.",
    nameFehlt: "الاسم مطلوب.",
  },
  atr: {
    teilAnlegen: "أضف قطعة يدوياً",
    teilBeispiel: "رقم القطعة، مثلاً VR-1234-56",
    anlegen: "أنشئ",
    wirdGelesen: "جارٍ القراءة …",
    mappeEinlesen: "اقرأ الملف المرجعي",
    suchen: "بحث",
    suchePlatzhalter: "رقم القطعة أو الوصف أو الرسم",
    nichtsGefunden: "لم يُعثر على شيء",
    katalogLeer: "الكتالوج فارغ",
    keinTeil: "لا قطعة تطابق هذا البحث.",
    katalogLeerText: "اقرأ ملفاً مرجعياً أو أضف قطعة يدوياً.",
    teilenummer: "رقم القطعة",
    bezeichnung: "الوصف",
    zeichnung: "الرسم",
    gewicht: "الوزن كغ",
    kategorie: "الفئة",
    bereich: "القسم",
    lieferungen: "التوريدات",
    teilekatalog: "كتالوج القطع",
    bearbeiten: "تعديل",
    speichern: "حفظ",
    gespeichert: "تم الحفظ.",
    gewichtUngueltig: "يرجى إدخال الوزن كرقم بالكيلوغرام، مثل 0.44.",
    nichtGespeichert: (meldung: string) => `لم يُحفظ: ${meldung}`,
  },
  lieferungen: {
    wirdGelesen: "جارٍ القراءة …",
    einlesen: "اقرأ إشعار تسليم",
    laeuft: "جارٍ التنفيذ …",
    eingangDurchsehen: "راجع الوارد",
    berichtNummer: (nr: string) => ` · رقم ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} بنداً، ${zugeordnet} منها موجودة في الكتالوج.`,
    keinLieferschein: "لا إشعار تسليم بعد",
    keinLieferscheinSchreiben: "اقرأ ملف PDF لإشعار تسليم — ثم ينتظر هنا للمراجعة.",
    keinLieferscheinLesen: "ما إن يُقرأ إشعار تسليم حتى يظهر هنا.",
    lieferschein: "إشعار التسليم",
    datum: "التاريخ",
    programm: "البرنامج",
    msn: "MSN",
    status: "الحالة",
    entwurf: "مسودة",
    erzeugt: "مُنشأ",
    abgelegt: "مُسلَّم",
    atrNummer: "رقم ATR",
    containernummer: "رقم الحاوية",
    erstellt: "تاريخ الإنشاء",
    auswaehlen: (nr: string) => `تحديد التوريد ${nr}`,
    ausgewaehlt: (anzahl: number) => `${anzahl} محدد`,
    auswahlAufheben: "إلغاء التحديد",
    containerbeschriftung: "إنشاء ملصق الحاوية",
    containerFrage: "رقم الحاوية للتوريدات المحددة:",
    containerHinweis: "يعرض الملصق كل التوريدات المخصصة لهذه الحاوية، بما فيها ما كان فيها من قبل.",
    containerErstellt: (nr: string) => `تم التخصيص للحاوية ${nr} – جارٍ تنزيل الملصق`,
    erstellen: "إنشاء",
  },
  durchsicht: {
    nichtGefunden: "لم يُعثر على التوريد.",
    wirdErzeugt: "جارٍ الإنشاء …",
    dokumenteErzeugen: "أنشئ المستندات",
    kopfdaten: "بيانات الرأس",
    atrNummer: "رقم ATR",
    nummerAutomatisch: (n: string) => `تلقائي: ${n}`,
    containernummer: "رقم الحاوية",
    satzTitel: "وصف المجموعة",
    programm: "البرنامج",
    msn: "MSN",
    bereich: "المجال",
    wiegedatum: "تاريخ الوزن",
    pruefdatum: "تاريخ الفحص",
    qsUnterschrift: "توقيع ضمان الجودة",
    hoechstgewicht: "الوزن الأقصى كغ",
    positionen: "البنود",
    pos: "البند",
    menge: "الكمية",
    seriennummern: "الأرقام التسلسلية",
    nichtImKatalog: "غير موجود في الكتالوج",
    poNummer: "رقم PO",
    poPos: "PO Pos",
    speichern: "حفظ",
    gespeichert: "تم الحفظ.",
    aufServerSpeichern: "حفظ على الخادم",
    wirdAbgelegt: "جارٍ الحفظ …",
    aufServerGespeichert: "تم الحفظ على الخادم.",
    ablageGescheitert: (ziele: string) => `لم يتم الحفظ: ${ziele}`,
    seriennummernAbweichung: (anzahl: number, menge: number) => `${anzahl} رقم تسلسلي للكمية ${menge}`,
    seriennummernFeld: (pos: string) => `الأرقام التسلسلية للبند ${pos}`,
  },
  fair: {
    dateiFehlt: (meldung: string) =>
      `تعذّر تحميل الرسم نفسه (${meldung}). الأبعاد مدرجة أدناه على أي حال.`,
    bezeichnungFrei: "الوصف (فارغ = اسم الملف)",
    beispiel: "مثلاً: عمود 12×40، رسم 4711",
    wirdGeladen: "جارٍ الرفع …",
    zeichnungWaehlen: "اختر رسماً",
    keineZeichnung: "لا رسم بعد",
    keineZeichnungSchreiben: "ارفع ملف PDF أو صورة — بعدها يمكن ترقيم الأبعاد ببالونات.",
    keineZeichnungLesen: "ما إن يُرفع رسم حتى يظهر هنا.",
    bezeichnung: "الوصف",
    teilenummer: "رقم القطعة",
    kunde: "العميل",
    hochgeladen: "رُفع في",
    pruefliste: "قائمة الفحص",
    einMass: "بُعد واحد",
    masse: (anzahl: number) => `${anzahl} بُعداً`,
    kopieren: "انسخ",
    csv: "CSV",
    keinMass: "لا بُعد معلَّم بعد.",
    nr: "الرقم",
    seite: "الصفحة",
    wert: "القيمة",
    wertBeispiel: "مثلاً: 12,0 h7",
    wertZu: (nummer: number) => `قيمة الرقم ${nummer}`,
    nachOben: (nummer: number) => `انقل الرقم ${nummer} إلى الأعلى`,
    nachUnten: (nummer: number) => `انقل الرقم ${nummer} إلى الأسفل`,
    nummer: (nummer: number) => `الرقم ${nummer}`,
    drehen: "أدر العرض",
    verkleinern: "تصغير",
    vergroessern: "تكبير",
    einpassen: "ملاءمة",
    darstellung: "العرض",
    bubbleGroesse: "حجم الفقاعات",
    zeichnung: "الرسم",
    ladefehler: "تعذّر تحميل الرسم.",
    alleKunden: "كل العملاء",
    ohneKunde: "بدون عميل",
    kundenfilter: "تصفية حسب العميل",
    artikelnummer: "رقم الصنف",
    artikelnummerLang: "رقم الصنف",
    pn: "P/N",
    bubblesKleiner: "فقاعات أصغر",
    bubblesGroesser: "فقاعات أكبر",
    pdf: "PDF",
    pdfExport: "تصدير PDF",
    pdfWirdErstellt: "جارٍ إنشاء PDF …",
    pdfFehler: (meldung: string) => `تعذّر إنشاء ملف PDF: ${meldung}`,
    ocrNeu: "إعادة تشغيل OCR لهذا السطر",
    ocrLeer: "لم يُتعرَّف على شيء — يرجى كتابة القيمة.",
    ocrFehler: (meldung: string) => `فشل OCR: ${meldung}`,
    ocrGleich: "يقرأ OCR القيمة نفسها.",
    ocrErsetzenTitel: "استبدال القيمة؟",
    ocrErsetzen: (nummer: number, alt: string, neu: string) => `الرقم ${nummer}: استبدال «${alt}» بـ «${neu}»؟`,
    ersetzen: "استبدال",
    ziehen: (nummer: number) => `اسحب الرقم ${nummer} لنقله`,
    nurNummernfolge: "النقل ممكن فقط بترتيب الأرقام — دون بحث ودون فرز حسب الصفحة أو القيمة.",
  },
  newsletter: {
    keineAusgabe: "لا عدد بعد",
    keineAusgabeText: "ما إن تنشر هيئة التحرير عدداً حتى يظهر هنا.",
    zurRedaktion: "إلى التحرير",
    quartalJahr: (quartal: number, jahr: number) => `الربع ${quartal} · ${jahr}`,
    entwurfSuffix: " · مسودة",
    ausgabe: "العدد",
    quartalKurz: (quartal: number, jahr: number) => `ر${quartal} ${jahr}`,
    entwurfKlammer: " (مسودة)",
    alsPdf: "كملف PDF",
    wirdGesetzt: "جارٍ التنضيد …",
    seiteVon: (nr: number, gesamt: number) => `الصفحة ${nr} من ${gesamt} …`,
    redaktion: "التحرير",
    niemandDazu: "لم يلتحق أحد في هذا الربع.",
    beitraege: "المقالات",
    belegschaftInZahlen: "القوى العاملة بالأرقام",
    neuBeiUns: "جدد بيننا",
    zurLeseransicht: "إلى عرض القارئ",
    jahr: "السنة",
    quartal: "الربع",
    ausgabeAnlegen: "أنشئ عدداً",
    ausgabeBearbeiten: "حرّر العدد",
    keineAusgabeRedaktion: "اختر السنة والربع وأنشئ — بعدها تنشأ الفصول هنا.",
    titelDerAusgabe: "عنوان العدد",
    status: "الحالة",
    entwurf: "مسودة",
    veroeffentlicht: "منشور",
    titelbild: "صورة الغلاف",
    rueckseite: "الغلاف الخلفي",
    ersetzen: ": استبدل",
    waehlen: ": اختر",
    ausgabeLoeschen: (quartal: number, jahr: number) => `العدد ر${quartal} ${jahr}`,
    neuesKapitel: "فصل جديد",
    kapitelBeispiel: "مثلاً: من الإنتاج",
    art: "النوع",
    hinzufuegen: "أضف",
    kapiteltitel: "عنوان الفصل",
    kapitelHoch: "انقل الفصل إلى الأعلى",
    kapitelRunter: "انقل الفصل إلى الأسفل",
    ueberschrift: "العنوان الفرعي",
    eintrag: "المدخل",
    textMarkdown: "نص. Markdown مسموح — **عريض**، قوائم، جداول.",
    text: "النص",
    bild: "الصورة",
    bildGroesse: (nr: number) => `حجم الصورة ${nr}`,
    nieEingefroren: "لم يُجمَّد شيء بعد — سيبقى الفصل فارغاً في المجلة.",
    kpiEingefroren: "أرقام القوى العاملة لهذا الربع مجمَّدة.",
    niemandEingefroren: "مجمَّد — لم يلتحق أحد في هذا الربع.",
    zugaengeEingefroren: (anzahl: number) =>
      `مجمَّد: ${anzahl} ${anzahl === 1 ? "ملتحق" : "ملتحقاً"} في هذا الربع.`,
    einfrieren: "جمّد",
    neuEinfrieren: "جمّد من جديد",
    rechtFehlt: (quelle: string) => `تنقص الصلاحية على المصدر: الاطلاع على ${quelle}.`,
    quelleKpi: "المؤشرات",
    quellePersonal: "شؤون الموظفين",
    ausgabeAngelegt: "أُنشئ العدد.",
    ausgabeGeloescht: "حُذف العدد.",
    kapitelAngelegt: "أُنشئ الفصل.",
    standEingefroren: "جُمّدت الحالة.",
  },
  signage: {
    bereiche: "أقسام Signage",
    medien: "الوسائط",
    medienHinzu: "أضف وسائط",
    playlists: "قوائم التشغيل",
    zeitplaene: "الجداول الزمنية",
    geraete: "الأجهزة",
    dateiZiehen: "اسحب الملف إلى هنا",
    dateiWaehlen: "اختر ملفاً",
    dateiHinweis: "صورة أو فيديو أو PDF أو PPTX، حتى 50 ميغابايت",
    wirdUebertragen: "جارٍ النقل …",
    art: "النوع",
    webseite: "صفحة وب (URL)",
    htmlSchnipsel: "مقتطف HTML",
    titel: "العنوان",
    titelBeispiel: "أعياد الميلاد",
    urlHinweis:
      "أدخل العنوان كاملاً. المشغّل يعمل على منفذ خاص به، والمسارات النسبية لا " +
      "تعمل هناك.",
    aufnehmen: "أضف",
    medienFehler: "تعذّر تحميل الوسائط.",
    keineMedien: "لا وسائط بعد",
    keineMedienText:
      "ارفع ملفاً أو أضف عنوان URL. بعدها يمكن تجميع الوسائط في قوائم تشغيل.",
    erneut: "من جديد",
    inVerwendung: "الوسيط قيد الاستخدام",
    inVerwendungText: (titel: string, anzahl: number) =>
      `«${titel}» ما زال مُدرجاً في ${anzahl} قائمة تشغيل. أزله منها أولاً.`,
    verstanden: "فهمت",
    wartet: "ينتظر",
    konvertiert: "قيد التحويل",
    fertig: "جاهز",
    fehlgeschlagen: "فاشل",
    keineHeartbeats: "لم تُسجَّل نبضات بعد.",
    nieGesehen: "لم يُرَ قط",
    online: "متصل",
    vorMinuten: (minuten: number) => `قبل ${minuten} دقيقة`,
    offline: "غير متصل",
    entzogen: "مسحوب",
    keinGeraet: "لا جهاز مقترن بعد",
    keinGeraetText:
      "شغّل شاشةً بالمشغّل. ستعرض رمزاً من ستة أرقام تُدخله هنا.",
    geraetKoppeln: "اقرن جهازاً",
    geraet: "الجهاز",
    status: "الحالة",
    verfuegbarkeit: "التوفّر 24 س",
    ausfaelle: "الانقطاعات 24 س",
    tags: "الوسوم",
    playlist: "قائمة التشغيل",
    zuletztGesehen: "آخر ظهور",
    seiteNeuLaden: "أعد تحميل الصفحة",
    neuStarten: "أعد تشغيل الجهاز",
    bearbeiten: "حرّر",
    zugangEntziehen: "اسحب الوصول",
    geraetBearbeiten: "تحرير الجهاز",
    name: "الاسم",
    bilddrehung: "تدوير الصورة",
    ton: "الصوت",
    tonAktiv: "الصوت مفعَّل",
    abbrechen: "إلغاء",
    speichern: "احفظ",
    tagsHinweis: "تحدد أي قوائم تشغيل وجداول زمنية يتلقاها هذا الجهاز.",
    entziehenText: (name: string) =>
      `«${name}» يفقد وصوله فوراً ويعرض رمز الاقتران من جديد.`,
    neustartText: (name: string) => `«${name}» سيبقى مظلماً نحو دقيقة.`,
    geraetGespeichert: "حُفظ الجهاز.",
    geraetGeloescht: "حُذف الجهاز.",
    keinGeraetGewaehlt: "لم يُختر جهاز",
    neuePlaylist: "قائمة تشغيل جديدة",
    neuePlaylistText: "حدّد الاسم والوسوم المستهدفة. المدخلات تأتي في الخطوة التالية.",
    namensbeispiel: "الاستقبال",
    keinePlaylist: "لا قائمة تشغيل بعد",
    keinePlaylistText:
      "قائمة التشغيل تجمع الوسائط في ترتيب معيّن وتُوزَّع على الأجهزة عبر الوسوم.",
    playlistAnlegen: "أنشئ قائمة تشغيل",
    aktiv: "نشطة",
    erstellt: "أُنشئت",
    kopieren: "انسخ",
    playlistGeloescht: "حُذفت قائمة التشغيل.",
    playlistKopiert: "نُسخت قائمة التشغيل. المدخلات لا تُنسخ معها.",
    playlistInPlan: "لقائمة التشغيل جداول زمنية نشطة",
    zeitplanHinweis:
      "الجدول الزمني له أسبقية على الإسناد بالوسوم وحده. قسّم النافذة التي تعبر " +
      "منتصف الليل إلى جدولين.",
    wochentage: "أيام الأسبوع",
    wochentagKuerzel: ["إث", "ثل", "أر", "خم", "جم", "سب", "أح"],
    von: "من",
    bis: "إلى",
    prioritaet: "الأولوية",
    zeitplanAktiv: "الجدول الزمني نشط",
    keineZeitplaene: "لا جداول زمنية",
    keineZeitplaeneText:
      "بلا جدول زمني يقرر الإسناد بالوسوم وحده أي قائمة تشغيل يعرضها الجهاز. والجدول " +
      "الزمني يقدّم قائمة تشغيل في أيام وأوقات محددة.",
    tage: "الأيام",
    zeitfenster: "النافذة الزمنية",
    aktionen: "الإجراءات",
    zeitplanBearbeiten: "تحرير الجدول الزمني",
    neuerZeitplan: "جدول زمني جديد",
    zeitplaeneFehler: "تعذّر تحميل الجداول الزمنية.",
    endeNachStart: "يجب أن تكون النهاية بعد البداية. للعبور عبر منتصف الليل أنشئ جدولين.",
    mindestensEinTag: "اختر يوماً واحداً على الأقل.",
    playlistWaehlen: "اختر قائمة تشغيل.",
    taeglich: "يومياً",
    zielTags: "الوسوم المستهدفة",
    ueberblenden: "تلاشٍ متداخل",
    harterSchnitt: "قطع حاد",
    ziehpunkt: "مقبض السحب",
    verwerfen: "تجاهل",
    medienHinzufuegen: "أضف وسائط ورتّبها بمقبض السحب.",
    mediumWaehlen: "اختر وسيطاً",
    mediumHinzufuegen: "أضف وسيطاً",
    mediumWaehlenText: "يُضاف الوسيط المختار في نهاية قائمة التشغيل.",
    schliessen: "أغلق",
    keineMedienAnlegen: "لا توجد وسائط بعد. أنشئ وسائط أولاً في قسم الوسائط.",
    unbekanntesMedium: "وسيط مجهول",
    playlistGespeichert: "حُفظت قائمة التشغيل. الأجهزة تعيد التحميل فوراً.",
    kopplungscode: "رمز الاقتران",
    codeBeispiel: "ABC-123",
    geraetename: "اسم الجهاز",
    geraeteBeispiel: "الاستقبال يسار",
    tagsPflicht: "عبر الوسوم يتلقى الجهاز قائمة تشغيله. وبلا وسم تبقى الشاشة فارغة.",
    koppeln: "اقرن",
    formatErwartet: "الصيغة المتوقَّعة XXX-XXX.",
    codeUnbekannt: "الرمز مجهول أو منتهٍ أو مستخدَم. اعرضه من جديد على الشاشة.",
    tagEingeben: "أدخل وسماً واضغط Enter",
  },
  einstellungen: {
    titel: "الإعدادات",
    bereiche: "الأقسام",
    gruppen: {
      kennzahlen: "المؤشرات",
      kennzahlenText:
        "القيم المستهدفة للوحات. تظهر كخط هدف في التطوّر وتحدد متى تنذر البطاقة.",
      personal: "HR",
      personalText:
        "أي أنواع الغياب تُحتسب مرضاً وأي الأقسام تتبع الإنتاج. " +
        "بلا هاتين القائمتين تبقى نسب الموظفين فارغة.",
      atr: "ATR",
      atrText:
        "ما يتكرر بلا تغيير في كل مستند من مستندات برنامج ما، ومن أين تأتي إشعارات التسليم.",
      qualitaet: "الجودة",
      qualitaetText:
        "مصفوفة المعايير التي يستند إليها التدقيق، وقوالب المراحل التي يأخذها التدقيق " +
        "الجديد كقائمة تحقق.",
      sensoren: "المستشعرات",
      sensorenText:
        "أجهزة القياس في الشبكة: أين تقف، وبأي معرّف تسلّم الحرارة والرطوبة، " +
        "ومتى تُعدّ القيمة مرتفعة.",
      zeugnisse: "شهادات العمل",
      zeugnisseText:
        "ما يتكرر في كل شهادة عمل: الشركة والمكان والتوقيعان. التوقيع المهني " +
        "يُستخرج من Personio عند الإنشاء — وهنا يقف بديله فقط.",
      erscheinung: "المظهر",
      erscheinungText:
        "شعار الشركة — أعلى اليمين في التطبيق وفي ترويسة كل ملف يُنشأ: " +
        "خطة التأهيل، إثبات الصيانة، النظرة العامة للتدريبات، شهادة العمل.",
      anzeigen: "الشاشات",
      anzeigenText:
        "العناوين التي تعمل على الشاشات في المبنى. كل عنوان يحمل رمزاً موقَّعاً، " +
        "ويصلح لشاشته وحدها، وينتهي أجله.",
      email: "البريد الإلكتروني",
      emailText:
        "حساب Microsoft 365 الذي ترسل منه المنصة التذكيرات والتقارير. لا يُرسَل شيء إلا بإجراء صريح.",
      ad: "Active Directory",
      adText: "تسجيل الدخول مقابل AD المحلي عبر LDAPS. يتحقق compute من كلمة المرور ويُظهر مجموعات AD؛ ويمنح المسؤول صلاحيات التطبيقات لكل مجموعة.",
      zugaenge: "المستخدمون والمجموعات",
      zugaengeText:
        "أنشئ أشخاصاً وكوّن مجموعات وامنحها صلاحيات التطبيقات. تسري التعديلات ما إن " +
        "يسجّل الشخص المعني دخوله في المرة التالية — فالصلاحيات في رمزه.",
    },
  },
  einstellungenText: {
    appName: "اسم التطبيق",
    appNameHinweis:
      "يظهر في الترويسة بدون شعار وفي عنوان الصفحة وفي صفحة تسجيل الدخول.",
    farbrollen: "أدوار الألوان",
    farbrollenHinweis:
      "اللون الرئيسي للتركيز والروابط والزر الأساسي وسلسلة الرسم الرئيسية، والنص فوقه. مرة للفاتح ومرة للداكن.",
    hellTitel: "فاتح",
    dunkelTitel: "داكن",
    hauptfarbe: "اللون الرئيسي",
    textAufHauptfarbe: "النص فوق اللون الرئيسي",
    kontrastTitel: "تباين غير كافٍ (WCAG 2.2)",
    kontrastZeile: (thema: string, bereich: string, verhaeltnis: string, mindestens: string) =>
      `«${bereich}» (${thema}): التباين ${verhaeltnis}:1، المطلوب ${mindestens}:1`,
    kontrastBereiche: {
      linkSeite: "روابط على الصفحة",
      linkKarte: "روابط على البطاقات",
      fokusFlaeche: "التركيز على سطح رمادي",
      diagramm: "لون الرسم",
      knopfText: "النص على الزر الأساسي",
    },
    farbenGespeichert: "حُفظت الألوان. تسري بعد إعادة التحميل.",
    farbenAufVorgabe: "أُعيد إلى الوضع الافتراضي.",
    farbenZuruecksetzen: "إعادة إلى الافتراضي",
    email: {
      titel: "إرسال البريد (Microsoft 365)",
      einleitung:
        "خدمة مركزية للتذكيرات والتقارير عبر Microsoft Graph.",
      ohneSchluessel:
        "لم يُضبط GEHEIM_SCHLUESSEL على الخادم. ما دام غائبًا لا يمكن تخزين أي سر.",
      gespeichert: "حُفظ.",
      speichert: "يحفظ …",
      speichern: "حفظ",
      speichernFehler: (meldung: string) => `فشل الحفظ: ${meldung}`,
      modus: "النمط",
      modusApp: "إذن التطبيق",
      modusDelegiert: "حساب خاص (مفوَّض)",
      modusAppHinweis: "يرسل عبر حساب تطبيق بإذن Mail.Send؛ يحتاج سرّ عميل وموافقة مسؤول.",
      modusDelegiertHinweis: "يرسل باسم الشخص المسجَّل بعد تسجيل دخول برمز الجهاز؛ دون موافقة مسؤول.",
      tenantId: "معرّف المستأجر",
      clientId: "معرّف العميل",
      clientSecret: "سرّ العميل",
      secretGesetzt: "مُخزَّن — اتركه فارغًا للإبقاء عليه",
      absender: "عنوان المرسِل",
      absenderName: "اسم المرسِل (اختياري)",
      aktivieren: "الإرسال مُفعَّل",
      testTitel: "بريد اختباري",
      testHinweis: "يرسل رسالة إلى العنوان المُدخَل. هذا الإجراء وحده يرسل شيئًا.",
      testEmpfaenger: "المستلِم",
      testSenden: "إرسال بريد اختباري",
      testLaeuft: "يرسل …",
      testOk: "أُرسل البريد الاختباري.",
      testFehler: "فشل الإرسال.",
      delegiertTitel: "تسجيل الدخول عبر Microsoft",
      delegiertAnmelden: "تسجيل الدخول عبر Microsoft",
      delegiertAnleitung:
        "افتح العنوان وأدخل الرمز وسجّل الدخول بحساب Microsoft 365 الخاص بك.",
      delegiertWartet: "بانتظار تسجيل الدخول …",
      verbundenMit: (konto: string) => `مسجَّل الدخول باسم ${konto}`,
      trennen: "قطع الاتصال",
      getrennt: "قُطع الاتصال.",
    },
    speichernFehler: (meldung: string) => `فشل الحفظ: ${meldung}`,
    zielwertGespeichert: "حُفظت القيمة المستهدفة. تعرضها اللوحات بعد إعادة التحميل.",
    zahlAbNull: "أدخل رقماً من 0 فأعلى.",
    personalGespeichert: "حُفظ. تعرضه لوحة شؤون الموظفين بعد إعادة التحميل.",
    krankTypen: "أنواع الغياب التي تُحتسب مرضاً",
    produktionAbteilungen: "أقسام الإنتاج",
    kompetenzAttribute: "حقول Personio التي تُحتسب كفاءة مسجَّلة",
    ausDemBestand: "من الرصيد",
    abteilungenBeispiel: "التصنيع، التجميع",
    firmenlogo: "شعار الشركة",
    anzeigenHinweis:
      "يُنشئ العنوان لمدخل قائمة تشغيل في مشغّل Signage. يصلح للشاشة المختارة وحدها " +
      "وينتهي أجله — فالمدخل الذي لا يعتني به أحد يتوقف عن العرض من تلقاء نفسه.",
    logoHinweis:
      "يقف أعلى اليمين في التطبيق وفي ترويسة كل استمارة تُنشأ — خطة التأهيل، " +
      "إثبات الصيانة، النظرة العامة للتدريبات، شهادة العمل. PNG أو JPEG أو SVG، " +
      "5 ميغابايت كحدٍّ أقصى. وإن لم يكن مسجَّلاً، ظهرت هناك عبارة «ACM-Plattform».",
    communityHinweis: "تُحفظ مشفَّرة ولا تُعرض مرة أخرى",
    verwaltenSchliesstEin: "«الإدارة» في بطاقة المنصة تشمل كل صلاحية أخرى.",
    logoAlt: "شعار الشركة المسجَّل",
    keinsHinterlegt: "لا شيء مسجَّل بعد.",
    laedt: "جارٍ الرفع …",
    ersetzen: "استبدل",
    hochladen: "ارفع",
    logoHochladen: "ارفع شعار الشركة",
    logoHinterlegt: "سُجّل الشعار.",
    anzeige: "الشاشة",
    geburtstage: "أعياد ميلاد الأسبوع",
    neuzugaenge: "جدد في الفريق",
    gueltigTage: "صالح لمدة (أيام)",
    erzeugt: "جارٍ الإنشاء …",
    adresseErzeugen: "أنشئ عنواناً",
    adresseKopiert: "نُسخ العنوان.",
    kopierenFehler: "تعذّر النسخ — حدّده يدوياً.",
    kopieren: "انسخ",
    gespeichert: "حُفظ.",
    speichern: "احفظ",
    speichert: "جارٍ الحفظ …",
    firma: "الشركة",
    ort: "المكان (فوق التاريخ)",
    nameRueckfall: "الاسم (بديل)",
    titelRueckfall: "المسمّى (بديل)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "ملف الجهة المُصدِرة",
    ausstellerHinweis:
      "يقف على كل شهادة. تُستخدم ترويسة ACM ما إن ترد «ACM» في اسم الشركة.",
    linkeUnterschrift: "التوقيع الأيسر — المهني",
    linkeHinweis:
      "عادةً رئيس الشخص المباشر؛ ويُستخرج من Personio عند الإنشاء. وما يقف هنا لا " +
      "يسري إلا إذا لم يقدّم Personio شيئاً — كما هي الحال مع الأشخاص المُدارين خارجياً.",
    rechteUnterschrift: "التوقيع الأيمن — شؤون الموظفين",
    rechteHinweis:
      "واحد لكل الشهادات. وإذا ارتبط بشخص من Personio جاء المسمّى من هناك وبقي " +
      "صحيحاً عند تغيّر المنصب.",
    personAusPersonio: "شخص من Personio",
    keinePerson: "— لا أحد، استخدم النص الحر أدناه —",
    personenFehler: (meldung: string) => `تعذّر تحميل قائمة الأشخاص (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "القوالب",
    vorlagenHinweis:
      "قالب لكل برنامج. بيانات الرأس وملف الهيكل تتكرر بلا تغيير في كل مستند ATR " +
      "من هذا البرنامج. ويُنشأ القالب عند قراءة ملف مرجعي في كتالوج القطع.",
    keineVorlage: "لا قالب بعد",
    keineVorlageText: "اقرأ ملفاً مرجعياً — البرنامج مكتوب فيه في الخانة D2.",
    geruestHinterlegt: "ملف الهيكل مسجَّل.",
    geruestErsetzen: "استبدل الهيكل",
    geruestWaehlen: "اختر هيكلاً",
    keineHinterlegt: "لا شيء مسجَّل بعد",
    kunde: "العميل",
    lieferant: "المورّد",
    arbeitspaket: "حزمة العمل",
    referenz: "المرجع",
    bestellerSpez: "مواصفات الطالب",
    lieferantenSpez: "مواصفات المورّد",
    kundenSpez: "مواصفات العميل",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "فصل ATA",
    waage: "الميزان",
    qsUnterschrift: "توقيع ضمان الجودة",
    eingangsordner: "مجلد الوارد",
    eingangHinweis:
      "يُقرأ إشعار التسليم في مجلد الإدخال ويصبح توريدًا ثم يُنقل إلى الأرشيف.",
    dateiserver: "خادم الملفات",
    dateiserverHinweis:
      "ينطبق الجهاز والمشاركة وحساب الخدمة على مجلد الإدخال وعلى «الحفظ على الخادم». يحدد ATR_SMB_ERLAUBT الأجهزة المسموح بها. كلمة المرور المُدخلة هنا لها الأولوية على ATR_SMB_PASSWORT من البيئة.",
    laeuft: "يعمل",
    aus: "متوقف",
    zuletzt: (zeit: string, text: string) => `آخر مرة ${zeit}: ${text}`,
    nochNichtGelaufen: "لم يعمل بعد.",
    prueft: "جارٍ الفحص …",
    verbindungPruefen: "افحص الاتصال",
    laeuftGerade: "جارٍ التنفيذ …",
    jetztDurchsehen: "راجع الآن",
    verbindungSteht: (dateien: number) =>
      `الاتصال قائم. ${dateien} ${dateien === 1 ? "ملف ينتظر" : "ملفاً تنتظر"} في الوارد.`,
    keineVerbindung: (meldung: string) => `لا اتصال: ${meldung}`,
    unbekannt: "مجهول",
    gelesenAngelegt: (gelesen: number, angelegt: number) =>
      `${gelesen} مقروء، ${angelegt} مُنشأ.`,
    rechner: "الخادم",
    rechnerHinweis: "يجب أن يرد في ATR_SMB_ERLAUBT",
    freigabe: "المشاركة",
    domaene: "النطاق",
    benutzer: "المستخدم",
    eingang: "الوارد",
    ausgang: "الصادر",
    archiv: "الأرشيف",
    ablageziele: "الحفظ على الخادم",
    ablagezieleHinweis: "المجلدات على المشاركة التي يضع فيها «الحفظ على الخادم» المصنف وملف PDF. يُستبدل {jahr} (السنة) و{kw} (الأسبوع التقويمي) عند الحفظ.",
    zielMappeA350: "المصنف A350",
    zielMappeA380: "المصنف A380",
    zielLogistik: "PDF الخدمات اللوجستية",
    zielWeightReport: "PDF تقرير الوزن",
    zielUngueltig: "مجلد الهدف غير صالح: فارغ أو يحتوي على «..» أو على عناصر نائبة غير {jahr} و{kw}.",
    wasEinLaufTut: "ما يفعله التشغيل",
    entwurfAnlegen: "إنشاء مسودة للمراجعة",
    dokumenteErzeugen: "إنشاء المستندات وحفظها",
    intervall: "فاصل الفحص (بالثواني، 0 = متوقف)",
    intervallUngueltig: "يجب أن يكون الفاصل عددًا صحيحًا من 0.",
    passwort: "كلمة مرور حساب الخدمة",
    passwortHinterlegt: "محفوظة — اتركها فارغة للإبقاء عليها",
    passwortUmgebung: "من البيئة (ATR_SMB_PASSWORT) — الإدخال هنا له الأولوية",
    passwortFehlt: "لم تُحفظ بعد",
    passwortOhneSchluessel: "GEHEIM_SCHLUESSEL غير موجود في البيئة — بدونه لا يمكن حفظ كلمة المرور.",
    speichern: "حفظ",
    gespeichert: "تم الحفظ.",
  },
  qualitaetEinstellungen: {
    normmatrix: "مصفوفة المعايير",
    normmatrixHinweis:
      "البنود التي يستند إليها التدقيق. المعيار المستخدَم لا يمكن حذفه — " +
      "بل يُوقَف، وإلا فقد تدقيقٌ أساسه بصمت.",
    schonInMatrix: "هذا البند موجود في المصفوفة أصلاً.",
    regelwerk: "المرجع",
    revision: "المراجعة",
    klausel: "البند",
    kurztext: "نص مختصر",
    kurztextBeispiel: "تدقيق داخلي",
    aufnehmen: "أضف",
    geprueft: "مراجَع",
    aktiv: "نشط",
    geprueftSchalter: (norm: string) => `${norm} مراجَع`,
    aktivSchalter: (norm: string) => `${norm} نشط`,
    phasenvorlagen: "قوالب المراحل",
    phasenvorlagenHinweis:
      "تسلسل الخطوات الذي يأخذه التدقيق الجديد. يُنسخ عند الإنشاء — والتعديل " +
      "اللاحق لا يعيد كتابة أي سجل.",
    neueVorlage: "قالب جديد",
    vorlageBeispiel: "تدقيق نظام قياسي",
    anlegen: "أنشئ",
    schritte: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "خطوة" : "خطوات"}`,
    schrittErgaenzen: "أضف خطوة",
    schrittBeispiel: "مثلاً: اجتماع الافتتاح",
  },
  personioZugang: {
    taktGespeichert: "حُفظ الفاصل الزمني.",
    abgleichTitel: "المزامنة",
    abgleichHinweis:
      "عدد مرات جلب بيانات Personio تلقائيًا، ومزامنة يدوية.",
    intervall: "فاصل المزامنة",
    intervallWahl: {
      "0": "يدوي فقط",
      "1": "كل ساعة",
      "6": "كل 6 ساعات",
      "24": "يوميًا",
      "168": "أسبوعيًا",
    },
    abgleichJetzt: "تحديث البيانات",
    abgleichLaeuft: "تجري المزامنة …",
    abgleichFertig: (mitarbeiter: number, anwesenheiten: number, abwesenheiten: number) =>
      `تمت المزامنة: ${mitarbeiter} موظفًا، ${anwesenheiten} حضورًا، ${abwesenheiten} غيابًا.`,
    abgleichTeilweise: (mitarbeiter: number, fehler: string) =>
      `مزامنة جزئية (${mitarbeiter} موظفًا): ${fehler}`,
    abgleichFehler: (fehler: string) => `فشلت المزامنة: ${fehler}`,
    nachweisTitel: "المستندات إلى Personio",
    nachweisHinweis:
      "يرفع مستندًا إلى ملف Personio بعد تغيير تدريب أو كفاءة. مُعطَّل افتراضيًا.",
    nachweisAktiv: "رفع المستندات",
    nachweisKategorie: "فئة المستند",
    nachweisKategoriePlatzhalter: "معرّف فئة Personio",
    nachweisGespeichert: "حُفظ.",
    titel: "بيانات الدخول إلى Personio",
    einleitung:
      "بيانات دخول تطبيق من تطبيقات Personio API. بدونها تبقى المزامنة " +
      "وصور الملفات وقوائم الاقتراحات فارغة.",
    kennung: "Client-ID",
    geheimnis: "Client-Secret",
    feldHinweis:
      "تُحفظ مشفَّرة ولا تُعرض مرة أخرى. ومن أراد تغييرها أدخل " +
      "بيانات جديدة.",
    speichern: "احفظ",
    gespeichert: "سُجّلت بيانات الدخول.",
    speichernFehler: (meldung: string) => `فشل الحفظ: ${meldung}`,
    entfernen: "أزل",
    entfernt: "أُزيلت بيانات الدخول.",
    pruefen: "افحص الاتصال",
    prueftGerade: "جارٍ الفحص …",
    verbindungSteht: "Personio يقبل بيانات الدخول.",
    verbindungFehlt: "Personio لا يستجيب.",
    laedt: "جارٍ التحميل …",
    keineHinterlegt: "لا بيانات دخول مسجَّلة.",
    ausDerUmgebung: "تسري بيانات الدخول من بيئة الخادم (.env).",
    hinterlegtSeit: (zeitpunkt: string, wer: string | null) =>
      wer
        ? `سُجّلت في ${zeitpunkt} بواسطة ${wer}.`
        : `سُجّلت في ${zeitpunkt}.`,
    ohneSchluessel:
      "لا يوجد GEHEIM_SCHLUESSEL مضبوط على الخادم. وما دام ناقصاً، " +
      "لا يمكن حفظ أي شيء مشفَّراً.",
  },
  sensorEinstellungen: {
    neuesGeraet: "جهاز جديد",
    name: "الاسم",
    nameBeispiel: "غرفة الخوادم",
    rechner: "الخادم",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "يجب أن يرد في SNMP_ERLAUBT",
    community: "Community",
    port: "المنفذ",
    kennungTemperatur: "معرّف الحرارة",
    kennungLuftfeuchte: "معرّف الرطوبة",
    faktorTemperatur: "معامل الحرارة",
    faktorHinweis: "0,1 إذا كان الجهاز يسلّم أعشار الدرجة كعدد صحيح",
    faktorLuftfeuchte: "معامل الرطوبة",
    farbe: "اللون في المخطط",
    farbeHinweis: "مثلاً: #0f6e8c",
    optional: "اختياري",
    anlegen: "أنشئ",
    fragt: "جارٍ الاستعلام …",
    ausprobieren: "جرّب",
    keinGeraet: "لا جهاز بعد",
    keinGeraetText: "أدخل في الأعلى الخادم والـ Community ومعرّفاً واحداً على الأقل.",
    wirdAbgefragt: (name: string) => `يجري الاستعلام من ${name}`,
    communityErsetzen: "استبدل الـ Community",
    unveraendert: "دون تغيير",
    communityErsetzt: "استُبدلت الـ Community.",
    sensorAngelegt: "أُنشئ المستشعر.",
    sensorGeloescht: "حُذف المستشعر بسلسلته الزمنية.",
    zahlEingeben: "أدخل رقماً.",
    taktTitel: "فترة الاستعلام",
    intervall: "فترة الاستعلام (ثوانٍ)",
    intervallHinweis:
      "تسري على جميع المستشعرات. النطاق 5–86400؛ أقل من 60 ثانية يعني عمليًا استعلامًا كل دقيقة.",
    intervallFehler: "يجب أن تكون الفترة عددًا صحيحًا بين 5 و86400.",
    grenzenTitel: "الحدود العامة",
    grenzenHinweis: "تسري على جميع المستشعرات. الحقل الفارغ يعني: بلا حد.",
    temperaturMin: "درجة الحرارة الدنيا (°C)",
    temperaturMax: "درجة الحرارة القصوى (°C)",
    feuchteMin: "الرطوبة الدنيا (%)",
    feuchteMax: "الرطوبة القصوى (%)",
    temperaturFehler: "يجب أن تكون درجة الحرارة الدنيا أقل من القصوى.",
    feuchteFehler: "يجب أن تكون الرطوبة الدنيا أقل من القصوى.",
    einstellungenGespeichert: "تم حفظ الفترة والحدود.",
    verwerfen: "تجاهل",
  },
  zugaenge: {
    stufen: {
      viewer: "عرض",
      editor: "تحرير",
      admin: "إدارة",
    },
    gruppeAngelegt: "أُنشئت المجموعة.",
    gruppeGibtEsSchon: "اسم المجموعة هذا موجود أصلاً.",
    personAngelegt: "أُنشئ الشخص",
    gruppeUmbenannt: "أُعيدت تسمية المجموعة.",
    gruppeGeloescht: "حُذفت المجموعة.",
    mitgliedHinzu: "أُضيف العضو. يسري بعد تسجيل الدخول التالي.",
    schonInGruppe: "هذا الشخص في المجموعة أصلاً.",
    neuesPasswort: "كلمة مرور جديدة",
    mitgliedEntfernt: "أُزيل العضو. يسري بعد تسجيل الدخول التالي.",
    gemeldeteSeiten: "اطّلع على App Feedback",
    neueGruppe: "مجموعة جديدة",
    gruppeBeispiel: "مثلاً: مبيعات داخلية",
    anlegen: "أنشئ",
    neuePerson: "شخص جديد",
    personBeispiel: "vorname.nachname@acm.local",
    keineGruppe: "لا مجموعة بعد",
    keineGruppeText: "أنشئ مجموعة وامنحها صلاحيات التطبيقات وأضف إليها أشخاصاً.",
    verzeichnis: "الدليل",
    ausVerzeichnis: "يأتي من الدليل",
    umbenennen: "أعد التسمية",
    mitRechten: "لديها صلاحيات",
    ohneRechte: "بدون صلاحيات",
    keinZugriff: "لا وصول",
    rechteAnGruppe: "الصلاحيات مرتبطة بالمجموعة لا بالشخص.",
    passwortNurJetzt:
      "كلمة المرور تظهر الآن فقط. بعدها لا يمكن إلا إعادة ضبطها، لا عرضها.",
    fertig: "تم",
    anmeldung: "تسجيل الدخول",
    passwort: "كلمة المرور",
    gruppeUmbenennen: "إعادة تسمية المجموعة",
    abbrechen: "إلغاء",
    speichern: "احفظ",
    gruppenname: "اسم المجموعة",
    mitgliederVon: (name: string) => `أعضاء «${name}»`,
    wirktNachAnmeldung: "تسري التعديلات ما إن يسجّل الشخص دخوله في المرة التالية.",
    schliessen: "أغلق",
    personHinzufuegen: "أضف شخصاً",
    auswaehlen: "— اختر —",
    hinzufuegen: "أضف",
    keineMitglieder: "هذه المجموعة بلا أعضاء بعد.",
    passwortZuruecksetzen: "أعد ضبط كلمة المرور",
    mitgliedEntfernen: "أزل العضو",
    entfernen: "أزل",
  },
  kopftitel: {
    start: "التطبيقات",
    kennzahlen: "لوحة KPI",
    offeneSchulungen: "التدريبات المتبقّية",
    schulungsmatrix: "مصفوفة التدريب",
    atrLieferungen: "توريدات ATR",
    atrTeilekatalog: "كتالوج قطع ATR",
  },
  kennzahlenHub: {
    titel: "لوحة KPI",
    bereiche: {
      "/kpi/vertrieb": "الإيرادات، قيمة الطلب، حصة العملاء",
      "/hr/kennzahlen": "القوى العاملة، دوران العمالة، المرض — صلاحية منفصلة",
      "/kpi/qualitaet": "نتائج التدقيق ونسبة الشكاوى",
      "/kpi/finanzen": "نسبة تكلفة المواد والعاملين",
      "/kpi/einkauf": "التزام المورّدين بمواعيد التسليم",
      "/kpi/produktion": "التأخير، الطلبات المتأخرة",
      "/kpi/bewertung": "قيّم المؤشرات واستخلص الإجراءات ووزّعها وتابعها",
    },
  },
  personalHub: {
    bereiche: {
      "/hr/kennzahlen": "القوى العاملة، دوران العمالة، المرض، العمل الإضافي",
      "/hr/organigramm": "من يرفع تقاريره إلى من",
      "/hr/kompetenzen": "مصفوفة المؤهلات لكل قسم",
      "/hr/schulungen": "التدريبات الإلزامية والمواعيد والإثباتات",
      "/hr/onboarding": "المنضمون الجدد والتأهيل والإجراءات",
      "/hr/einarbeitung": "خطط التأهيل وحالتها",
      "/hr/dokumente": "إنشاء الاستمارات وطباعتها وإعادة قراءتها ممسوحة",
      "/hr/zeugnisse": "كتابة شهادات العمل وإصدارها",
    },
  },
  bewertung: {
    titel: "تقييم KPI والإجراءات",
    uebersichtFehler: (meldung: string) => `تعذّر التحميل: ${meldung}`,
    nurLesen:
      "تستطيع قراءة التقييمات لا كتابتها. لذلك يلزم حق «التحرير» على الإعدادات.",
    bubbles: "الفقاعات",
    bubblesLeer: "لا فقاعات بعد.",
    neu: "جديد",
    alsGesehen: "علّم كمُشاهَد",
    zumDashboard: "إلى اللوحة",
    bubble: (nummer: number) => `فقاعة ${nummer}`,
    ohnePosition: "بلا موضع على المخطط",
    neueMassnahme: "إجراء جديد",
    kpiWaehlen: "اختر المؤشر…",
    ohneBubble: "— بلا فقاعة —",
    titelPlatzhalter: "الإجراء (العنوان)",
    verantwortlichWaehlen: "المسؤول…",
    anlegen: "إجراء",
    massnahmen: "الإجراءات",
    alleStatus: "كل الحالات",
    statusFilter: "تصفية حسب الحالة",
    keineMassnahme: "لا إجراء بعد.",
    nichtZugewiesen: "غير مُسنَد",
    spalte: {
      kpi: "المؤشر",
      massnahme: "الإجراء",
      verantwortlich: "المسؤول",
      faellig: "الاستحقاق",
      prioritaet: "الأولوية",
      status: "الحالة",
      aktionen: "الإجراءات",
    },
    status: {
      offen: "مفتوح",
      laeuft: "قيد العمل",
      erledigt: "منجز",
      verworfen: "مستبعَد",
    },
    prioritaet: {
      niedrig: "منخفضة",
      mittel: "متوسطة",
      hoch: "عالية",
    },
    ampel: {
      keine: "بلا إشارة",
      gruen: "أخضر",
      gelb: "أصفر",
      rot: "أحمر",
    },
    bereiche: {
      vertrieb: "المبيعات",
      einkauf: "المشتريات",
      produktion: "الإنتاج",
      qualitaet: "الجودة",
      finanzen: "المالية",
      personal: "HR",
    },
    verwalten: "الإدارة في الإجراءات",
    anzahlMassnahmen: (anzahl: number) => `${anzahl} إجراء`,
  },
  erklaerung: {
    hinweis: "شرح",
    frage: (titel: string) => `كيف يُحسب «${titel}»؟`,
    knopf: "طريقة الحساب",
    untertitel: "هكذا يُحسب",
    ganzeSeite: "صفحة المساعدة كاملة",
  },
};
