import type { Texte } from "@/texte/de";

/**
 * Die bulgarischen Texte der Oberfläche. Maschinell übersetzt — vor dem
 * Ausrollen sollte jemand darüberlesen, der die Sprache spricht.
 */
export const bg: Texte = {
  kopf: {
    benutzermenue: "Потребителско меню",
    angemeldetAls: "Влезли сте като",
    uebersicht: "Към прегледа",
    hilfe: "Помощ",
    einstellungen: "Настройки",
    abmelden: "Изход",
    sprache: "Език",
    erscheinungsbild: "Изглед",
    hell: "Светъл",
    dunkel: "Тъмен",
    system: "Както системата",
    meldungenLeer: "Сигнали — няма нови",
    meldungen: (anzahl: number) => `Сигнали — ${anzahl} непрегледани`,
    massnahmenLeer: "Мерки — няма открити",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Мерки — ${offen} открити, от тях ${ueberfaellig} просрочени`
        : `Мерки — ${offen} открити`,
  },
  pfad: {
    aria: "Път",
    start: "Начало",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "Доставки",
      "/einstellungen": "Настройки",
      "/fair": "FAIR",
      "/hilfe": "Помощ",
      "/hr": "HR",
      "/hr/dokumente": "Документооборот",
      "/hr/einarbeitung": "Въвеждане",
      "/hr/kennzahlen": "Показатели",
      "/hr/kompetenzen": "Компетенции",
      "/hr/onboarding": "Постъпване",
      "/hr/organigramm": "Органиграма",
      "/hr/schulungen": "Обучения",
      "/hr/schulungen/matrix": "Матрица",
      "/hr/schulungen/offen": "Неизпълнени",
      "/hr/zeugnisse": "Препоръки",
      "/kpi": "Показатели",
      "/kpi/bewertung": "Оценка",
      "/kpi/einkauf": "Снабдяване",
      "/kpi/finanzen": "Финанси",
      "/kpi/produktion": "Производство",
      "/kpi/qualitaet": "Качество",
      "/kpi/vertrieb": "Продажби",
      "/newsletter": "Бюлетин",
      "/newsletter/redaktion": "Редакция",
      "/platform/feedback": "Сигнали",
      "/produktion": "Производство",
      "/qualitaet": "Качество",
      "/sensoren": "Сензори",
      "/signage": "Digital Signage",
      "/signage/devices": "Устройства",
      "/signage/media": "Медии",
      "/signage/pair": "Сдвояване",
      "/signage/playlists": "Плейлисти",
      "/signage/schedules": "Графици",
      "/uploads": "Качвания",
    },
  },
  start: {
    titel: "Приложения",
    verweigert: (name: string) => `Нямате право да отворите „${name}“.`,
    keineApp:
      "На профила ви още не е дадено приложение. Обърнете се към администрацията на платформата.",
  },
  anmeldung: {
    titel: "ACM-Plattform",
    aufforderung: "Влезте с профила си.",
    email: "Имейл",
    passwort: "Парола",
    knopf: "Вход",
    laeuft: "Влизане …",
  },
  allgemein: {
    laedt: "Зарежда се …",
    speichern: "Запази",
    abbrechen: "Отказ",
    loeschen: "Изтрий",
    stueck: "бр.",
    loeschenTitel: "Потвърждение на изтриването",
    loeschenFrage: (was: string) => `„${was}“ ще бъде изтрито окончателно.`,
    loeschenKnopf: (was: string) => `Изтрий ${was}`,
  },
  zeitraum: {
    aria: "Период",
    monat: "Този месец",
    quartal: "Това тримесечие",
    jahr: "Тази година",
    alles: "Всичко",
    frei: "Изберете период",
    von: "от",
    bis: "до",
    vonAria: "Период от",
    bisAria: "Период до",
    verdreht: "Краят е преди началото.",
  },
  vergleich: {
    zu: (was: string) => `спрямо ${was}`,
    quartal: (q: number) => `${q}. тримесечие`,
    jahr: (j: number) => `${j} г.`,
    keinWert: "Няма стойност за сравнение: липсват данни за периода на сравнение или стойността е нула.",
    gestiegen: "нараснало",
    gesunken: "намаляло",
    unveraendert: "без промяна",
  },
  tabelle: {
    suche: "Търсене",
    sucheAria: "Търсене в таблицата",
    sucheLeeren: "Изчистване на търсенето",
    keineTreffer: "Няма резултати за това търсене.",
    leer: "Няма записи.",
    bereich: (von: number, bis: number, gesamt: number) => `${von}–${bis} от ${gesamt}`,
    seite: (seite: number, seiten: number) => `Страница ${seite} от ${seiten}`,
    zurueck: "Предишна страница",
    weiter: "Следваща страница",
    sortieren: (spalte: string) => `Сортиране по „${spalte}“`,
    seitengroesse: "Редове на таблица на страница",
    seitengroesseText: "Важи за всички таблици на платформата, за всички потребители.",
    gespeichert: "Размерът на страницата е запазен.",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Данни към ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Непълни данни — ${fehlend} ${anzahl === 1 ? "липсва" : "липсват"}`,
    heute: "днес",
    gestern: "вчера",
    vorTagen: (tage: number) => `преди ${tage} дни`,
    nie: "никога",
    arten: {
      umsatz: "Оборот",
      auftraege: "Поръчки",
      angebote: "Оферти",
      interessenten: "Потенциални клиенти",
      kontakte: "Контакти",
      liefertreue: "Спазване на срокове",
      lagerbewegungen: "Складови движения",
      lagerpreise: "Складови цени",
      auftragspositionen: "Позиции по поръчки",
      lieferscheine: "Стокови разписки",
      pruefungen: "Проверки",
      acht_d: "8D-отчети",
      wareneingaenge: "Входящи доставки",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `Показателите не можаха да се заредят: ${meldung}`,
    keineDatenTitel: "За този период няма данни",
    keineDatenVor: "Качете ERP експортите в ",
    keineDatenNach: " или изберете по-широк период.",
    keineWerte: "няма стойности в периода",
    laedt: "зарежда се …",
    jeTag: "по дни",
    jeWoche: "по седмици",
    jeMonat: "по месеци",
  },
  vertrieb: {
    umsatz: "Оборот",
    umsatzHinweis: "Фактури минус кредитни известия",
    auftragswert: "Ср. стойност на поръчка",
    ueberNull: "Поръчки над 0 €",
    auftraege: "Поръчки общо",
    verlauf: "Оборот във времето",
    verlaufHinweis: (takt: string) => `${takt}, кредитните известия са приспаднати`,
    kundenanteil: "Дял на клиентите в оборота",
    kunde: "Клиент",
    anteil: "Дял",
    uebrige: "Останали",
    jeErfasser: "Поръчки по търговец",
    erfasser: "Търговец",
    anzahl: "Поръчки",
    summe: "Сума",
  },
  aktivitaet: {
    titel: "Търговска активност",
    jeWoche: (von: string, bis: string) => `по седмици, ${von} до ${bis}`,
    ladeFehler: (meldung: string) => `Търговската активност не можа да се зареди: ${meldung}`,
    leer: "Няма контакти, оферти или потенциални клиенти в този период.",
    kw: (woche: string) => `Седм. ${woche}`,
    ziel: (wert: string) => `Цел ${wert} / седмица`,
    erstkontakte: "Първи контакти",
    erstkontakteHinweis: "приключени контакти от тип ERS",
    besuche: "Посещения",
    besucheHinweis: "на място и онлайн заедно",
    interessenten: "Потенциални клиенти",
    interessentenHinweis: "новозаписани, без определен търговец",
    angebote: "Оферти",
    angeboteHinweis: "сума на издадените оферти",
    auftragseingang: "Приети поръчки",
    auftragseingangHinweis: "анулиранията са приспаднати",
  },
  einkauf: {
    einleitung:
      "Спазване на сроковете от доставчиците. Брои се това, което е пристигнало в периода.",
    keineDaten: "За този период няма позиции по доставки",
    ladeVor: "Качете експорта за спазване на сроковете в ",
    ladeNach: ".",
    otd: "OTD процент",
    otdHinweis: (ziel: string) => `Цел ${ziel} · навреме значи закъснение ≤ 0`,
    puenktlich: "Позиции навреме",
    gesamt: "Позиции общо",
    verzugSchnitt: "Ср. закъснение",
    verzugHinweis: "Позициите без стойност за закъснение не се броят тук",
    verlauf: "OTD процент във времето",
    verlaufHinweis: "Празнините са периоди без позиции по доставки.",
    ladenhueter: "Поръчка за склад — залежали артикули",
    kapital: (wert: string) => `Блокиран капитал: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Складови артикули без движение поне ${tage} дни, най-скъпите първи. ` +
      "Към днешна дата — периодът горе не важи тук, защото наличността не е период.",
    artikel: "Артикул",
    bezeichnung: "Наименование",
    bestand: "Наличност",
    liegtSeit: "Стои от",
    stueckpreis: "Единична цена",
    wert: "Стойност",
    positionen: "Позиции по доставки",
    positionenHinweis:
      "Най-голямото закъснение първо, позициите без стойност за закъснение най-горе. Най-много 500 реда.",
    auftrag: "Поръчка",
    lieferant: "Доставчик",
    zieltermin: "Целева дата",
    geliefert: "Доставено",
    verzug: "Закъснение",
  },
  produktion: {
    einleitung:
      "Закъснели поръчки. Една поръчка се брои чак когато изходът ѝ е ясен.",
    keineDaten: "За този период няма поръчка с изяснен изход",
    ladeVor: "Качете позициите по поръчки и стоковите разписки в ",
    ladeNach:
      ". Нужни са и двата файла: единият носи целевата дата, другият — действителната.",
    quote: "Процент закъснения",
    quoteHinweis: (ziel: string) => `Най-много ${ziel}`,
    inVerzug: "Закъснели поръчки",
    gesamt: "Поръчки общо",
    gesamtHinweis: "без откритите поръчки, чийто срок още не е дошъл",
    verzugSchnitt: "Ср. закъснение",
    verzugHinweis: "поръчките навреме влизат с отрицателен знак",
    verlauf: "Процент закъснения във времето",
    verlaufHinweis: "По целева дата. Празнините са периоди без броени поръчки.",
    ziellinie: "Цел",
    liste: "Закъснели поръчки",
    listeHinweis:
      "Най-голямото закъснение първо. При откритите поръчки то расте всеки ден. Най-много 500 реда.",
    auftrag: "Поръчка",
    kunde: "Клиент",
    stand: "Състояние",
    zieltermin: "Целева дата",
    geliefert: "Доставено",
    verzug: "Закъснение",
    verspaetet: "доставена със закъснение",
    offen: "открита, просрочена",
  },
  finanzen: {
    einleitung: "Материални и разходи за персонал спрямо фактурирания оборот.",
    keineDatenVor:
      "Нужни са три файла: складовите движения за разхода, входящите доставки за " +
      "цените и оборотът като база. И трите се качват в ",
    keineDatenNach: ".",
    materialquote: "Процент материални разходи",
    materialquoteHinweis: "Материални разходи / оборот",
    hoechstens: (ziel: string) => `Най-много ${ziel}`,
    materialkosten: "Материални разходи",
    umsatz: "Оборот",
    personalquote: "Процент разходи за персонал",
    brauchtZeitraum: "изисква период",
    personalHinweis: (kosten: string, personen: string) => `${kosten} при ${personen} души`,
    ohnePreis: "Артикули без цена",
    ohnePreisHinweis: "изразходвани, но неостойностени",
    jeAbteilung: "Разходи за персонал по отдели",
    abteilung: "Отдел",
    personen: "Души",
    kosten: "Разходи",
    anteil: "Дял",
    verlauf: "Процент материални разходи във времето",
    verlaufHinweis: "Празнините са периоди без оборот — без база няма процент.",
    ziellinie: "Цел",
    verbrauch: "Разход на материал по артикули",
    verbrauchHinweis:
      "Най-високите разходи първи. Артикулите без цена стоят най-отдолу — те не влизат в " +
      "процента. Най-много 500 реда.",
    artikel: "Артикул",
    bezeichnung: "Наименование",
    menge: "Разход",
    stueckpreis: "Единична цена",
    keinPreis: "няма цена",
  },
  qualitaet: {
    einleitung: "Одитни констатации, процент рекламации и проверени количества.",
    auditart: "Вид одит:",
    keineArt: "Не е избран вид одит. Изберете поне един, иначе няма какво да се брои.",
    keineDaten: "За този период няма одитни констатации",
    ladeVor: "Качете 8D експорта в ",
    ladeNach: ".",
    behoerde: "Орган",
    extern: "Външен",
    intern: "Вътрешен",
    kunde: "Клиент",
    level1: "Одитни констатации ниво 1",
    level2: "Одитни констатации ниво 2",
    ohneLevel: "Без разпознато ниво",
    ohneLevelHinweis: "не се брои в нито една карта",
    hoechstens: (ziel: number) => `Най-много ${ziel}`,
    auditVerlauf: "Одитни констатации във времето",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `Дял на количеството без рекламация. База: ${bezug}.`,
    fehlerquote: (quote: string) => `Процент дефекти: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Процент дефекти: ${quote} · цел ${ziel}`,
    reklamiert: "Рекламирано количество",
    bezugsmenge: "Базово количество",
    bezugsmengeNull: "без него няма процент",
    mehrAlsBezogen:
      "Рекламирано е повече, отколкото е получено. Изчислението не може да реши това: " +
      "числителят и знаменателят идват от различни файлове със собствени дати. Проверете " +
      "дали базовият файл за този период е качен изцяло.",
    reklKunde: "Клиент",
    reklIntern: "вътрешно",
    reklLieferant: "Доставчици на материали",
    reklWerkbank: "Работни места",
    bezugKunde: "доставено количество",
    bezugIntern: "доставено количество",
    bezugLieferant: "входящи доставки без услуги",
    bezugWerkbank: "входящи доставки от стоковите групи DIENST и SERVIC",
    mengeGesamt: "отчетено количество",
    mengeAkzeptiert: "прието количество",
    onQualityBezug: (menge: string) => `On Quality (база ${menge})`,
    ziellinie: "Цел",
    geprueft: "Проверени продукти",
    geprueftHinweis: (pruefer: string, tage: string) =>
      `Количество на проверяващ и на ден. Делителят е един и същ за двете величини: ${pruefer} проверяващи в ${tage} дни.`,
    gross: "Големи продукти",
    klein: "Малки продукти",
    mindestens: (ziel: number) => `Поне ${ziel} на ден и на проверяващ`,
    buchungen: "Записи от проверката на качеството",
    buchungenHinweis:
      "Изключен запис остава в списъка, но не се брои в нито една карта. " +
      "Най-голямото количество първо, най-много 500 реда.",
    zaehltMit: "Брои се",
    datum: "Дата",
    pruefer: "Проверяващ",
    produkt: "Продукт",
    groesse: "Размер",
    menge: "Количество",
    ausschuss: "Брак",
    mitzaehlen: (datum: string) => `Записът от ${datum} да се брои`,
    klasseGross: "голям",
    klasseKlein: "малък",
    diagnose: "Констатации без разпознато ниво",
    diagnoseHinweis:
      "Нивото стои като свободен текст в изходния файл. Ако там не пише нито „Major … Level 1“, " +
      "нито „Minor … Level 2“, констатацията не се брои никъде. Този списък показва къде да се поправи.",
    bericht: "Отчет",
    art: "Вид",
    adresse: "Адрес",
    bezeichnung: "Наименование",
  },
  personal: {
    einleitung:
      "От синхронизацията с Personio. Дневната норма идва от заложения " +
      "работен режим на всеки човек, а не от общ осемчасов ден.",
    uebersicht: "Преглед",
    standLaedt: "Състоянието на синхронизацията се зарежда …",
    keinAbgleich: "Още няма синхронизация. Тя тръгва сама всяка нощ в 02:15.",
    letzterAbgleich: (zeitpunkt: string, status: string) =>
      `Последна синхронизация ${zeitpunkt} · ${status}`,
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} души, ${anwesenheiten} присъствия, ${abwesenheiten} отсъствия`,
    abgleichLaeuft: "тече …",
    abgleichen: "Синхронизирай сега",
    keineDaten: "За този период няма присъствия",
    keineDatenHinweis:
      "Или синхронизацията с Personio още не е минала, или периодът е " +
      "преди началото на отчитането.",
    ueberstunden: "Процент извънреден труд",
    stundenVon: (teil: string, ganz: string) => `${teil} от ${ganz} ч.`,
    krankheit: "Процент болнични",
    krankheitsartenFehlen: "видовете болнични не са зададени",
    fluktuation: "Текучество",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} напуснали, средно ${schnitt} заети`,
    personen: "Отчетени души",
    personenHinweis: "с присъствие в периода",
    krankheitHinweisVor:
      "Процентът болнични остава празен, докато не е зададено кои " +
      "видове отсъствия в Personio се броят като болнични. Въвежда се в ",
    krankheitHinweisNach: ".",
    verlauf: "Развитие",
    reiheUeberstunden: "Извънреден труд",
    reiheKrankheit: "Болнични",
  },
  melden: {
    knopf: "Сигнал",
    titel: "Подайте сигнал",
    frage: "Какво не е наред на тази страница? Снимка на страницата тръгва заедно със сигнала.",
    abbrechen: "Отказ",
    senden: "Изпрати",
    sendet: "Изпраща се …",
    beispiel: "Например: картата показва празна стойност, въпреки че има данни.",
    beschreibung: "Описание",
    aufnahme: "Снимка на страницата",
    gehtMit: "Тази снимка тръгва заедно със сигнала.",
    nimmtAuf: "Страницата се снима …",
    misslungen: "Страницата не можа да се снима — сигналът тръгва без изображение.",
    dankeMitBild: "Благодарим — сигналът е получен.",
    dankeOhneBild: "Благодарим — сигналът е получен, без изображение на страницата.",
  },
  belegschaft: {
    titel: "Състав на персонала",
    hinweis:
      "Към днешна дата. Разпределенията показват текущите основни данни, а не тези отпреди — " +
      "Personio не пази история. Това, че „заети“ и процентът компетенции имат различни " +
      "знаменатели, е нарочно: едното число следва статуса в Personio, другото — датите на " +
      "постъпване и напускане. И двата пътя идват от стария проект.",
    ladeFehler: (meldung: string) => `Съставът на персонала не можа да се зареди: ${meldung}`,
    beschaeftigte: "Заети",
    beschaeftigteHinweis: "по статус „активен“ в Personio",
    neuImQuartal: "Нови през тримесечието",
    bestand: "Численост",
    kompetenzen: "Попълнени компетенции",
    felderFehlen: "полетата не са зададени — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} от ${aktive} по дати на постъпване и напускане`,
    geschlecht: "Пол",
    beschaeftigungsart: "Вид заетост",
    abteilungen: "Отдели",
    maennlich: "мъже",
    weiblich: "жени",
    divers: "друг",
    unbekannt: "неизвестен",
    vollzeit: "пълно работно време",
    teilzeit: "непълно работно време",
    geringfuegig: "минимална заетост",
    extern: "външни",
  },
  mitarbeiter: {
    titel: "Служители",
    nurMitUeberstunden: "само с извънреден труд",
    ausgeblendet: (anzahl: number) => `(${anzahl} скрити)`,
    person: "Човек",
    abteilung: "Отдел",
    istStunden: "Отраб. часове",
    ueberstunden: "Извънреден труд",
    quote: "Изв. %",
  },
  wochenbericht: {
    titel: "Седмичен отчет",
    ladeFehler: (meldung: string) => `Седмичният отчет не можа да се зареди: ${meldung}`,
    kalenderwoche: "Седмица",
    kw: (woche: string, jahr: string) => `Седм. ${woche} / ${jahr}`,
    keineDaten: "За тази седмица няма присъствия.",
    saldo: "Салдо извънреден труд",
    saldoHinweis: (personen: string) =>
      `Отработено минус ефективната норма, за всички ${personen} души`,
    ueberSoll: "Над нормата",
    ueberSollHinweis: (gesamt: string) => `от ${gesamt} души с отчетено работно време`,
    krankheit: "Болнични",
    tage: "дни",
    stunden: "ч.",
    krankheitHinweis: "разпределени по календарните дни на отсъствието",
    ist: "Отраб.",
    soll: "Норма",
    saldoSpalte: "Салдо",
    fussnote:
      "Нормата е ефективната седмична норма: отпуск и болнични са приспаднати, който " +
      "отсъства без причина, е на минус. В текущата седмица нормата се брои само до " +
      "последния отчетен ден.",
  },
  titel: {
    schulung: "Обучение",
    zeugnis: "Препоръка",
    qualifikationsmatrix: "Квалификационна матрица",
    maschine: "Машина",
    audit: "Одит",
    zeichnung: "Чертеж",
    lieferung: "Доставка",
    offeneSchulungen: "Неизпълнени обучения",
    schulungsmatrix: "Матрица на обученията",
    atrLieferungen: "ATR доставки",
    kpiBewertung: "KPI оценка",
    anmelden: "Вход",
  },
  uploads: {
    einleitung:
      "Зареждане на ERP експортите. Повторното качване на същия файл е безопасно: " +
      "съществуващите редове се обновяват, а не се създават втори път.",
    dateiWaehlen: "Изберете файл",
    verarbeitet: "обработва се …",
    uebersprungen: (datei: string) => `Пропуснати редове от „${datei}“`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `${gesamt} реда поети, ${fehler} пропуснати. Останалите редове са записани.`,
    zeile: "Ред",
    spalte: "Колона",
    grund: "Причина",
    zuletzt: "Последно качени",
    datei: "Файл",
    art: "Вид",
    zeilen: "Редове",
    uebersprungenSpalte: "Пропуснати",
    status: "Състояние",
    zeitpunkt: "Момент",
    nochNichts: "Още нищо не е качено.",
    keineZeile: (datei: string) => `„${datei}“ не съдържаше нито един валиден ред.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `„${datei}“ е поет, ${fehler} реда са пропуснати.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `„${datei}“ е поет: ${neu} нови, ${aktualisiert} обновени.`,
    fehlgeschlagenMeldung: (meldung: string) => `Качването се провали: ${meldung}`,
    vollstaendig: "изцяло",
    teilweise: "частично",
    fehlgeschlagen: "неуспешно",
    arten: {
      umsatz: "Оборот (фактури и кредитни известия)",
      umsatzText:
        "Захранва картата Оборот и графиката на оборота. Кредитните известия стоят с минус във файла.",
      auftraege: "Приети поръчки",
      auftraegeText: "Захранва ср. стойност на поръчка, поръчки общо и разбивката по търговец.",
      auftragspositionen: "Позиции по поръчки",
      auftragspositionenText:
        "Носи целевата дата на всяка позиция. Заедно със стоковите разписки от това излиза закъснението.",
      lieferscheine: "Стокови разписки",
      lieferscheineText:
        "Носи действителната дата на доставка. Excel файл, по един ред на позиция от разписка.",
      wareneingaenge: "Входящи доставки",
      wareneingaengeText:
        "База за процента дефекти откъм снабдяването. Стоковата група разделя доставчиците на материали от работните места.",
      acht_d: "8D-отчети",
      acht_dText:
        "Одитни констатации и рекламации в един файл. Нивото на констатацията стои като свободен текст и се извежда при зареждането.",
      lagerbewegungen: "Складови движения",
      lagerbewegungenText:
        "Разход по артикули за процента материални разходи. Заменя всички редове в периода на файла.",
      lagerpreise: "Складови цени на артикули",
      lagerpreiseText:
        "Основни данни за оценка на склада. Заменя целия ценоразпис, не само съдържащите се артикули.",
      pruefungen: "Проверка на качеството",
      pruefungenText:
        "Записи от проверката. Заменя всички редове в периода на файла — ръчно изключените записи в този период след това отново се броят.",
      liefertreue: "Спазване на срокове (снабдяване)",
      liefertreueText:
        "Захранва OTD процента в снабдяването. По един ред на позиция; действителната дата на доставка определя периода.",
      kontakte: "Контакти (продажби)",
      kontakteText:
        "Първи контакти и посещения по седмици. Заменя всички редове в периода на файла — второ качване на същия период не удвоява нищо.",
      angebote: "Оферти",
      angeboteText:
        "Обем на офертите по седмица и търговец. Оферти без търговец не се появяват в нито една колона.",
      interessenten: "Потенциални клиенти",
      interessentenText:
        "Основни данни за потенциалните клиенти. Записан наново клиент преминава с новата си дата в друга седмица.",
    },
  },
  organigramm: {
    einleitung:
      "От Personio. Който няма зададен ръководител там, стои най-горе — при " +
      "управлението това е вярно, иначе е знак за пропуск в основните данни.",
    suchfeld: "Човек, длъжност или отдел",
    suchePlatzhalter: "Име, длъжност, отдел",
    standort: "Локация",
    alleStandorte: "Всички локации",
    personen: (anzahl: number) => `${anzahl} души`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} без ръководител`,
    niemand: "Никой не е намерен",
    niemandText: "Друго търсене, друга локация — или синхронизацията с Personio още не е минала.",
    aufklappen: (name: string) => `Разгъни ${name}`,
    zuklappen: (name: string) => `Сгъни ${name}`,
    direkt: (anzahl: number) => `${anzahl} пряко`,
  },
  offeneSchulungen: {
    einleitung:
      "Кой от какво има нужда. Само активни обучения; спрените вече не се появяват тук.",
    zumKatalog: "Към каталога",
    allesOffene: "Всичко неизпълнено",
    nieAbsolviert: "Никога невзето",
    ueberfaellig: "Просрочени",
    wirdFaellig: "Предстои падеж",
    suchen: "Търсене на човек или обучение",
    suchenAria: "Търсене",
    nichtsOffen: "Няма неизпълнени",
    nichtsOffenText: "Всички активни обучения са в срок — или още нищо не е заредено.",
    eintraege: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "запис" : "записа"}.`,
    person: "Човек",
    schulung: "Обучение",
    bereich: "Област",
    zuletzt: "Последно",
    faellig: "Падеж",
    stand: "Състояние",
    nie: "никога невзето",
    imTurnus: "в срок",
  },
  schulungsmatrix: {
    einleitung:
      "Всички хора срещу всички обучения — прегледът за таблото и за одита. " +
      "Който няма нито едно участие, стои там с празен ред; точно това е пропускът, " +
      "който се търси.",
    wasOffenIst: "Какво е неизпълнено",
    katalog: "Каталог",
    suchfeld: "Човек или отдел",
    suchePlatzhalter: "Име, отдел, служебен номер",
    bereich: "Област",
    alleBereiche: "Всички области",
    nurLuecken: "Само хора с пропуски",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} от ${gesamt} души · ${schulungen} обучения`,
    niemand: "Никой не отговаря",
    niemandText: "Друго търсене или друга област — или наистина никой няма неизпълнени.",
    person: "Човек",
    nichtZugewiesen: (person: string, schulung: string) =>
      `${person} · ${schulung}: не е зададено`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (падеж ${datum})`,
    offen: "неизпълнено",
    personio: "Personio",
    externGepflegt: "поддържан извън системата",
    ohneTreffer: "без съвпадение в Personio",
  },
  schulungen: {
    einleitung:
      "Каталогът, неговата периодичност и кой я спазва. Падежите се изчисляват от последната " +
      "дата и периодичността, а не се записват.",
    dokumentenlauf: "Документооборот",
    bereich: "Област",
    neueSchulung: "Ново обучение",
    beispiel: "напр. инструктаж по пожарна безопасност",
    anlegen: "Създай",
    wirdGelesen: "Чете се …",
    uebersichtEinlesen: "Зареди прегледа",
    einlesenAria: "Зареди прегледа на обученията",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} обучения (${neu} нови), ${teilnahmen} участия, от тях ${zugeordnet} свързани с човек в Personio.`,
    ohneTreffer: "Без съвпадение в Personio: ",
    ohneTrefferNach: ". Тези редове идват въпреки това със служебен номер и име.",
    wirdUebernommen: "Поема се …",
    uebernehmen: "Поеми",
    abbrechen: "Отказ",
    keineSchulung: "Още няма обучение",
    keineSchulungText: "Създайте едно или заредете прегледа на обученията.",
    schulung: "Обучение",
    turnus: "Периодичност",
    frist: "Срок (дни)",
    verantwortlich: "Отговорник",
    offen: "Неизпълнени",
    aktiv: "Активно",
    nichtBerechenbar: "(не се изчислява)",
    zahlGroesserNull: "Моля, въведете число, по-голямо от 0.",
    nieKurz: (anzahl: number) => `${anzahl} никога`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} просрочени`,
    baldKurz: (anzahl: number) => `${anzahl} скоро`,
    aktivSchalter: (name: string) => `${name} активно`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} значи: за този човек няма дата в историята. ${bald} значи: в следващите два месеца. Към ${datum}.`,
  },
  schulung: {
    gibtEsNicht: "Това обучение не съществува",
    gibtEsNichtText: "Вероятно е премахнато.",
    ohneTurnus: "без периодичност",
    keineFaelligkeit: " — от това не може да се изчисли падеж",
    zumKatalog: "Към каталога",
    stammdaten: "Основни данни",
    turnus: "Периодичност",
    turnusBeispiel: "напр. годишно",
    turnusHinweis: "Текстът; броят месеци идва от зареждането.",
    turnusMonate: "Периодичност в месеци",
    monateHinweis: "Празно значи: не може да се изчисли падеж.",
    verantwortlich: "Отговорник",
    beschreibung: "Описание",
    fuerWen: "За кого е задължително?",
    kuerzel: "Код на отдел",
    kuerzelHinweis: "Подробната схема от Excel (NÄH, CUT, WVK …).",
    personioAbteilung: "Отдел в Personio",
    personioHinweis: "Едрият отдел, както го води Personio.",
    entfernen: (was: string) => `Премахни ${was}`,
    keine: "няма",
    ergaenzen: (was: string) => `Добави ${was}`,
    hinzufuegen: "Добави",
    teilnahmen: "Участия",
    nochNiemand: "Още никой — заредете прегледа на обученията или впишете някого.",
    person: "Човек",
    abteilungKurz: "Отд.",
    erstschulung: "Първо обучение",
    zuletzt: "Последно",
    faellig: "Падеж",
    stand: "Състояние",
    keinTreffer: "Няма съвпадение в Personio — редът се запазва въпреки това",
    nichtInPersonio: "не е в Personio",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "това участие",
    personErgaenzen: "Добави човек",
    nameForm: "Фамилия, име",
  },
  kompetenzen: {
    einleitung:
      "Какво изисква една длъжност и доколко е покрито — по една матрица за всяка област. " +
      "Заредено от файла на областта, след това поддържано тук.",
    zumDashboard: "Към таблото на персонала",
    bereich: "Област",
    wirdGelesen: "Чете се …",
    einlesen: "Зареди файла на областта",
    vorschauKopf: (datei: string, bereich: string) => `${datei} — така би изглеждала ${bereich}:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} квалификации, ${personen} души, ${bewertungen} оценки.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `${zugeordnet} от ${personen} души са намерени в Personio`,
    platzhalter: (anzahl: number) =>
      `, ${anzahl} ${anzahl === 1 ? "колона заместител" : "колони заместители"}`,
    ohneZuordnung: (namen: string) => ` Без съответствие: ${namen}.`,
    ersetztWarnung:
      "Засегнатите листове се заменят изцяло — поддържаните тук промени се губят " +
      "при това.",
    wirdUebernommen: "Поема се …",
    uebernehmen: "Поеми",
    abbrechen: "Отказ",
    keineMatrix: "Още няма матрица",
    keineMatrixText: "Заредете файл на област — всеки лист в него става матрица.",
    blatt: "Лист",
    titelSpalte: "Заглавие",
    stand: "Към дата",
    eingelesen: "Заредено",
    produktion: "Производство",
    verwaltung: "Администрация",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    einleitung:
      "От оценки и кратки бележки става език на препоръката. Основните данни се преписват при " +
      "създаването — издадена препоръка не се променя, защото Personio се е променил.",
    person: "Човек",
    waehlen: "— изберете —",
    art: "Вид",
    anlegen: "Създай",
    keines: "Още няма препоръка",
    keinesText: "Изберете човек и вида препоръка — основните данни идват сами.",
    zeitraum: "Период",
    note: "Оценка",
    stand: "Състояние",
    angelegt: "Създадена",
    fertig: "готова",
    entwurf: "Чернова",
    qualifiziert: "Квалифицирана препоръка",
    einfach: "Проста препоръка",
    zwischenzeugnis: "Междинна препоръка",
    ausbildungszeugnis: "Препоръка за обучение",
    praktikumszeugnis: "Препоръка за стаж",
  },
  einarbeitung: {
    einleitung:
      "Какво трябва да научи новият човек и кой му го показва. Формулярът се съставя от " +
      "темите, заложени за неговия отдел.",
    bogenErzeugen: "Създай формуляр",
    person: "Човек",
    waehlen: "— изберете —",
    wirdGebaut: "Съставя се …",
    einarbeitungsplan: "План за въвеждане",
    keineInhalte: "Още няма заложени теми — формулярът би останал празен.",
    abteilungVon: (abteilung: string) => `Отдел ${abteilung}`,
    neuerInhalt: "Нова тема",
    beispiel: "напр. инструктаж за безопасност на фрезата",
    anlegen: "Създай",
    keinInhalt: "Още няма тема",
    keinInhaltText:
      "Определете какво трябва да научи новият човек — и за кои отдели важи това.",
    inhalt: "Тема",
    ansprechpartner: "Отговорно лице",
    bereich: "Област",
    fuerAbteilungen: "За кои отдели",
    abteilung: "Отдел",
    bereichLeer: "Празно значи: взема се отделът от матрицата",
    entfernen: (was: string) => `Премахни ${was}`,
    abteilungHinzu: "+ отдел",
    abteilungFuer: (inhalt: string) => `Отдел за ${inhalt}`,
  },
  matrix: {
    gibtEsNicht: "Тази матрица не съществува",
    gibtEsNichtText: "Вероятно е заменена.",
    blattStand: (blatt: string) => `Лист ${blatt}`,
    stand: (datum: string) => ` · към ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} квалификации, ${personen} души`,
    zurUebersicht: "Към прегледа",
    qualifikation: "Квалификация",
    keineZeilen: "Тази матрица още няма редове.",
    stufenBedeuten: "Какво значат степените",
    erfuellungsgradHinweis:
      "Второто число е степента на покритие в проценти. Клетка с изискване и " +
      "по-малко от 100 % е пропуск и стои в предупредителен цвят.",
    ergaenzen: "Добави",
    neueQualifikation: "Нова квалификация",
    beispiel: "напр. струг",
    kategorie: "Категория",
    ohne: "без",
    zeile: "Ред",
    neuePerson: "Нов човек",
    namensform: "Име Фамилия",
    spalte: "Колона",
    anforderungslevel: "Изисквано ниво",
    erfuellungsgrad: "Степен на покритие в проценти",
    stufe0: "не се изисква",
    stufe1: "основни познания",
    stufe2: "може да работи под ръководство",
    stufe3: "работи самостоятелно",
    stufe4: "може да ръководи и обучава",
  },
  zeugnis: {
    gibtEsNicht: "Тази препоръка не съществува",
    gibtEsNichtText: "Вероятно е изтрита.",
    durchschnitt: (wert: string) => ` · среден успех ${wert}`,
    zurUebersicht: "Към прегледа",
    zeugnisVon: (name: string) => `Препоръка ${name}`,
    stammdaten: "Основни данни",
    stammdatenHinweis:
      "Преписани при създаването. Промените тук важат само за тази препоръка — Personio " +
      "остава недокоснат.",
    name: "Име",
    personalnummer: "Служебен номер",
    abteilung: "Отдел",
    taetigkeit: "Длъжност",
    eintritt: "Постъпване",
    austritt: "Напускане",
    geburtsdatum: "Дата на раждане",
    ausstellungsdatum: "Дата на издаване",
    ohneNamen: "Без име не става.",
    anrede: "Обръщение",
    frau: "Г-жа",
    herr: "Г-н",
    anredeHinweis: "Определя обръщението и местоименията в текста.",
    art: "Вид",
    anlass: "Повод",
    anlassBeispiel: "напр. по собствено желание",
    fuehrungskraft: "Ръководител",
    fuehrungskraftHinweis: "Ръководител — включва измерението „ръководство“",
    bewertung: "Оценка",
    bewertungHinweis:
      "Училищни оценки от 1 до 4. От средния успех следва формулата за удовлетвореност — не " +
      "обратното.",
    fachwissen: "Професионални знания",
    auffassungsgabe: "Схватливост",
    arbeitsweise: "Начин на работа",
    belastbarkeit: "Устойчивост на натоварване",
    arbeitserfolg: "Резултати от работата",
    sozialverhalten: "Поведение в екипа",
    fuehrung: "Ръководство",
    aufgaben: "Задачи (кратки бележки)",
    aufgabenHinweis: "По една задача на ред — от това става изброяването в препоръката.",
    kompetenzen: "Особени компетенции",
    kompetenzenHinweis: "Влиза в оценката на представянето.",
    erfolge: "Особени постижения",
    erfolgeHinweis: "Проекти, отличия, измерими резултати.",
    text: "Текст",
    baut: "Съставя …",
    ausBausteinen: "От готови блокове",
    formuliert: "Формулира …",
    mitKi: "С изкуствен интелект",
    textHinweis:
      "Наборът от блокове пише без мрежа и без изкуствен интелект. Изкуственият интелект " +
      "формулира по-свободно — до него стигат само обръщение, роля, отдел, срок, оценки и " +
      "свободните текстове горе. Име, дата на раждане и служебен номер не напускат сървъра.",
    nochKeinText: "Още няма текст. Дайте оценките и оставете текстът да се състави.",
    fertigSchalter: "Препоръката е готова",
    fertigHinweis: "Готова — вече не е в работа",
    unterschriftenFehler: (meldung: string) =>
      `Подписите не можаха да бъдат определени (${meldung}).`,
    darunterSteht: "Отдолу стои",
    fachlich: "Пряк ръководител",
    personalwesen: "Човешки ресурси",
    niemandHinterlegt: "— никой не е зададен —",
    unterschriftFehlt:
      "Липсва подпис. Задайте го в Настройки → Препоръки или впишете ръководителя " +
      "в Personio.",
    ausPersonio: "от Personio",
    ausEinstellungen: "от настройките",
    nichtHinterlegt: "не е зададено",
    einleitung: "Въведение",
    taetigkeitsbeschreibung: "Описание на дейността",
    leistungsbeurteilung: "Оценка на представянето",
    schlussformel: "Заключителна формула",
    hinweisDeutsch: "Самата препоръка се изготвя на немски език.",
  },
  dokumentenlauf: {
    einleitung:
      "Формуляри с QR код: създаване, връчване, връщане попълнени, проверка. QR кодът " +
      "свързва сканирането обратно — независимо как се казва файлът.",
    formblatt: "Формуляр",
    fuerWen: "За кого",
    personWaehlen: "— изберете човек —",
    erzeugt: "Създава се …",
    blattErzeugen: "Създай формуляр",
    standFilter: "Състояние:",
    alle: "Всички",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} от ${gesamt}`,
    keinVorgang: "Няма случай",
    keinVorgangText:
      "Създайте формуляр горе — той получава QR код и оттам нататък се проследява.",
    person: "Човек",
    kennung: "Код",
    stand: "Състояние",
    vollstaendigSpalte: "Пълен",
    blatt: "Формуляр",
    scan: "Сканиране",
    prueft: "Проверява …",
    scanFuer: (name: string) => `Качи сканирането за ${name}`,
    zu: "затвори",
    details: "Подробности",
    nochNichtGeprueft: "— още непроверен",
    vollstaendig: "пълен",
    unvollstaendig: "непълен",
    umkehren: "Обърни преценката — измерването вижда само дали в полето има мастило",
    pruefung: "Проверка",
    qrGelesen: "— QR кодът е прочетен",
    keinQr: "— няма намерен QR код, полетата не могат да се свържат",
    nachweise: "Доказателства",
    keineNachweise: "Още няма заложени.",
    welcheZeile: "Към кой ред? (по желание)",
    laedt: "Качва се …",
    nachweis: "Доказателство",
    nachweisHoch: "Качи доказателство",
    erstellt: "създаден",
    uebergeben: "връчен",
    zurueck: "върнат",
    geprueft: "проверен",
    einarbeitungsplan: "План за въвеждане",
    schulungsnachweis: "Удостоверение за обучение",
  },
  onboarding: {
    einleitung:
      "Кой е нов и какви обучения изисква матрицата на изискванията за него. Планът не се " +
      "записва, а се изчислява — промени ли се матрицата, променя се и планът.",
    nichtsGefehlt: "Нищо не липсваше.",
    angelegt: (anzahl: number) =>
      `Създадени са ${anzahl} ${anzahl === 1 ? "обучение" : "обучения"}.`,
    neu90: "Нови (последните 90 дни)",
    alle: "Всички",
    personen: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "човек" : "души"}`,
    keineEintritte: "Няма постъпили",
    keineEintritteText: "Щом от Personio дойде някой с дата на постъпване, той стои тук.",
    person: "Човек",
    abteilung: "Отдел",
    position: "Длъжност",
    eintritt: "Постъпване",
    uebergabe: "Връчване",
    nichtInPersonio: "не е в Personio",
    hierGesetzt: "Зададено тук — има превес над Personio",
    ausPersonio: "От Personio",
    vermerken: "Отбележи",
    paketTitel: "План за въвеждане и преглед на обученията в един PDF",
    paket: "Пакет",
    uebersichtTitel: "Само прегледът на обученията (формуляр 71)",
    uebersicht: "Преглед",
    planZu: "Затвори плана",
    plan: "План",
    schulungsplan: "План за обучения",
    fehlendeAnlegen: "Създай липсващите",
    wirdGerechnet: "изчислява се …",
    bruecke: "Длъжност → код на отдел",
    brueckeHinweis:
      "Мостът между Personio и подробното ниво на матрицата на изискванията. Без запис " +
      "подробното ниво не важи за тази длъжност — планът го казва изрично.",
    kuerzel: "Код",
    positionBeispiel: "напр. CNC оператор",
    kuerzelBeispiel: "CNC",
    zuordnen: "Свържи",
    ohnePersonio: "Човек без Personio",
    ohnePersonioHinweis:
      "За постъпили, които още не са в синхронизацията — или изобщо не спадат там.",
    name: "Име",
    anlegen: "Създай",
    kuerzelFehlt: (position: string) =>
      `За длъжността ${position}няма зададен код на отдел. Затова подробното ниво на ` +
      "матрицата на изискванията не важи за този човек — възможно е да липсват " +
      "задължителни обучения.",
    matrixVerlangtNichts: "Матрицата на изискванията не изисква нищо за този отдел.",
    schulung: "Обучение",
    bereich: "Област",
    turnus: "Периодичност",
    pflichtUeber: "Задължително чрез",
    stand: "Състояние",
    ueberAbteilung: "Отдел",
    ueberKuerzel: "Код",
    vorhanden: "налично",
    fehlt: "липсва",
  },
  audit: {
    einleitung:
      "Одити от планирането до приключването. Всяка промяна на състоянието стои в историята — " +
      "записана от базата данни, не от формата, и след това непроменима.",
    zuKennzahlen: "Към показателите",
    nummer: "Номер",
    nummerBeispiel: "A-2026-01",
    titel: "Заглавие",
    titelBeispiel: "Системен одит EN 9100",
    art: "Вид",
    intern: "вътрешен",
    extern: "външен",
    phasenvorlage: "Шаблон за фази",
    ohne: "без",
    anlegen: "Създай",
    keinAudit: "Още няма одит",
    keinAuditText: "Създайте един — с шаблон за фази той идва веднага със своя контролен списък.",
    laufen: (laufend: number, gesamt: number) => `${laufend} от ${gesamt} още текат.`,
    status: "Състояние",
    fortschritt: "Напредък",
    naechsterTermin: "Следваща дата",
    ueberfaellig: (anzahl: number) => `${anzahl} просрочени`,
    geplant: "Планиран",
    inVorbereitung: "В подготовка",
    inDurchfuehrung: "В изпълнение",
    berichtet: "Отчетен",
    massnahmenOffen: "Открити мерки",
    abgeschlossen: "Приключен",
    verschoben: "Отложен",
    abgesagt: "Отменен",
    phaseOffen: "Открита",
    phaseInArbeit: "В работа",
    phaseErledigt: "Изпълнена",
    phaseNichtZutreffend: "Неприложима",
    system: "Система",
    prozess: "Процес",
    produkt: "Продукт",
    lieferant: "Доставчик",
  },
  wartung: {
    einleitung:
      "Машините и техните повтарящи се задачи по поддръжка. Доказателството се получава като " +
      "формуляр за окачване — на всяко полугодие, с по една колона за седмица.",
    zuKennzahlen: "Към показателите",
    neueMaschine: "Нова машина",
    beispiel: "напр. фреза 3",
    anlegen: "Създай",
    keineMaschine: "Още няма машина",
    keineMaschineText: "Създайте машина и заложете нейните задачи по поддръжка.",
    maschine: "Машина",
    inventarnummer: "Инв. №",
    standort: "Локация",
    verantwortlich: "Отговорник",
    status: "Състояние",
    aktiv: "активна",
    stillgelegt: "спряна",
  },
  sensoren: {
    einleitung:
      "Температура и влажност, отчитани на всеки пет минути. Стойност извън зададените " +
      "граници стои в предупредителен цвят.",
    misst: "Измерва …",
    jetztMessen: "Измери сега",
    keinGeraet: "Няма настроено устройство",
    keinGeraetText: "Сензорите се създават в настройките — хост, идентификатор и community.",
    verlauf: "Развитие",
    stunden: (n: number) => `${n} ч`,
    tage: (n: number) => `${n} дни`,
    temperatur: "Температура",
    luftfeuchte: "Влажност",
    zuletzt: (zeit: string) => `Последно ${zeit}`,
    keinMesswert: "Още няма измерена стойност.",
    nichtsGemessen: "В този период не е измервано нищо.",
    frisch: "актуално",
    verzoegert: "със закъснение",
    offline: "офлайн",
    unbekannt: "още нищо не е измерено",
  },
  hilfe: {
    einleitung:
      "Какво може платформата, как се получават числата и какво да се направи, когато нещо " +
      "не е наред.",
    nurDeutsch: "Самите помощни страници са написани на немски език.",
    suchen: "Търсене в помощта",
    nichtsGefunden:
      "Нищо не е намерено. Ако нещо липсва в помощта, кажете го с бутона за сигнал долу " +
      "вдясно.",
    alleThemen: "← Всички теми",
  },
  meldungen: {
    stand: (offen: number) => `Какво е подадено от изгледите. ${offen} открити`,
    neuSeit: (anzahl: number) => ` · ${anzahl} нови от последното посещение`,
    nichtsGemeldet: "Няма подадени сигнали",
    nichtsGemeldetText:
      "С бутона долу вдясно всеки влязъл човек може да подаде сигнал какво не е наред на " +
      "дадена страница.",
    unbekannt: "неизвестно",
    bild: "Изображение",
    status: "Състояние",
    offen: "открит",
    erledigt: "приключен",
    meldung: "Сигнал",
    aufnahme: "Снимка на страницата",
  },
  auditAnsicht: {
    gibtEsNicht: "Този одит не съществува",
    gibtEsNichtText: "Вероятно е премахнат.",
    internesAudit: "Вътрешен одит",
    externesAudit: "Външен одит",
    prioritaet: (stufe: string) => ` · приоритет ${stufe}`,
    erledigt: (prozent: number) => ` · ${prozent} % изпълнено`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} просрочени`,
    zurUebersicht: "Към прегледа",
    status: "Състояние",
    stammdaten: "Основни данни",
    titel: "Заглавие",
    bereich: "Област",
    leitenderAuditor: "Водещ одитор",
    auditteam: "Одиторски екип",
    geplantVon: "Планиран от",
    geplantBis: "Планиран до",
    prioritaetFeld: "Приоритет",
    niedrig: "нисък",
    mittel: "среден",
    hoch: "висок",
    auditziel: "Цел на одита",
    kategorien: "Категории",
    kategorienHinweis:
      "Един одит често е няколко неща едновременно — вътрешната програма покрива система и " +
      "процес в един термин. Затова множествен избор, а не едно поле.",
    normbezug: "Позоваване на стандарт",
    normmatrixLeer: "Матрицата на стандартите е празна — тя се поддържа в настройките.",
    nichtGeprueft: "* още непроверено спрямо консолидирания текст на стандарта.",
    phasen: "Фази",
    keinePhasen: "Няма фази — този одит е създаден без шаблон.",
    phase: "Фаза",
    verantwortlich: "Отговорник",
    faellig: "Падеж",
    erledigtAm: "Изпълнено на",
    phaseErgaenzen: "Добави фаза",
    phaseBeispiel: "напр. последващ одит",
    verlauf: "История",
    verlaufHinweis:
      "Записана от базата данни, не от тази форма — и след това нито променима, нито " +
      "изтриваема.",
    nichtsGeschehen: "Още нищо не се е случило.",
    warumEntfaellt: "Защо отпада тази задължителна фаза?",
    uebernehmen: "Поеми",
    abbrechen: "Отказ",
    angelegt: "създаден",
    geaendert: "променен",
    geloescht: "изтрит",
    uebersprungen: "пропуснат",
  },
  maschine: {
    gibtEsNicht: "Тази машина не съществува",
    gibtEsNichtText: "Вероятно е изтрита.",
    zurUebersicht: "Към прегледа",
    stammdaten: "Основни данни",
    name: "Име",
    inventarnummer: "Инв. №",
    standort: "Локация",
    hersteller: "Производител",
    modell: "Модел",
    verantwortlich: "Отговорник",
    status: "Състояние",
    aktiv: "активна",
    stillgelegt: "спряна",
    notizen: "Бележки",
    wartungsaufgaben: "Задачи по поддръжка",
    jahr: "Година",
    halbjahr: "Полугодие",
    erstesHalbjahr: "Седм. 1–26",
    zweitesHalbjahr: "Седм. 27–52",
    wirdGebaut: "Съставя се …",
    nachweisbogen: "Формуляр за доказателство",
    neueAufgabe: "Нова задача",
    aufgabeBeispiel: "напр. проверка на нивото на маслото",
    intervall: "Интервал",
    wochen: "седмици",
    keineAufgabe: "Още няма задача — формулярът би останал празен.",
    aufgabe: "Задача",
    dateien: "Файлове",
    planHinterlegen: "Заложи план",
    nachweisAblegen: "Добави доказателство",
    dateienHinweis: "Планът на производителя и сканираните обратно подписани формуляри.",
    keineDatei: "Още няма файл.",
    plan: "План",
    nachweis: "Доказателство",
    laedt: "Качва се …",
    taeglich: "Всеки ден",
    woechentlich: "Всяка седмица",
    monatlich: "Всеки месец",
    quartalsweise: "Всяко тримесечие",
    alleNWochen: "На всеки N седмици",
    alleNWochenZahl: (wochen: number) => `На всеки ${wochen} седмици`,
  },
  atr: {
    einleitung:
      "Каталогът на частите е основата: от него стоковата разписка взема наименование, чертеж " +
      "и тегло. Търси се по номера на частта без украса — броят се само цифрите.",
    zuLieferungen: "Към доставките",
    teilAnlegen: "Създай част на ръка",
    teilBeispiel: "Номер на част, напр. VR-1234-56",
    anlegen: "Създай",
    wirdGelesen: "Чете се …",
    mappeEinlesen: "Зареди референтна папка",
    suchen: "Търсене",
    suchePlatzhalter: "Номер на част, наименование или чертеж",
    nichtsGefunden: "Нищо не е намерено",
    katalogLeer: "Каталогът е празен",
    keinTeil: "Няма част, която да отговаря на това търсене.",
    katalogLeerText: "Заредете референтна папка или създайте част на ръка.",
    teilenummer: "Номер на част",
    bezeichnung: "Наименование",
    zeichnung: "Чертеж",
    gewicht: "Тегло кг",
    kategorie: "Категория",
    nurErste: "Само първите 500 резултата — моля, търсете по-тясно.",
  },
  lieferungen: {
    einleitung:
      "Стоковата разписка се зарежда, сверява се с каталога на частите и се записва като " +
      "чернова. След прегледа се освобождава.",
    zumKatalog: "Към каталога на частите",
    wirdGelesen: "Чете се …",
    einlesen: "Зареди стокова разписка",
    laeuft: "Тече …",
    eingangDurchsehen: "Прегледай входящите",
    berichtNummer: (nr: string) => ` · № ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} позиции, ${zugeordnet} намерени в каталога.`,
    keinLieferschein: "Още няма стокова разписка",
    keinLieferscheinSchreiben:
      "Заредете PDF на стокова разписка — след това тя чака тук за преглед.",
    keinLieferscheinLesen: "Щом бъде заредена стокова разписка, тя стои тук.",
    lieferschein: "Стокова разписка",
    datum: "Дата",
    programm: "Програма",
    msn: "MSN",
    status: "Състояние",
    entwurf: "Чернова",
    freigegeben: "освободена",
  },
  durchsicht: {
    nichtGefunden: "Доставката не е намерена.",
    freigeben: "Освободи",
    zuruecknehmen: "Оттегли освобождаването",
    wirdErzeugt: "Създава се …",
    dokumenteErzeugen: "Създай документите",
    kopfdaten: "Заглавни данни",
    atrNummer: "ATR номер",
    containernummer: "Номер на контейнер",
    satzTitel: "Наименование на комплекта",
    programm: "Програма",
    msn: "MSN",
    bereich: "Област",
    wiegedatum: "Дата на претегляне",
    pruefdatum: "Дата на проверка",
    qsUnterschrift: "Подпис ОТК",
    hoechstgewicht: "Макс. тегло кг",
    positionen: "Позиции",
    pos: "№",
    menge: "Кол.",
    seriennummern: "Серийни номера",
    nichtImKatalog: "не е в каталога",
    festHinweis:
      "Доставката е освободена; позициите са фиксирани. Базата данни отхвърля " +
      "промяна — освобождаването може да се оттегли горе.",
  },
  fair: {
    dateiFehlt: (meldung: string) =>
      `Самият чертеж не се зарежда (${meldung}). Размерите въпреки това са по-долу.`,
    einleitung:
      "Проверка на първи образец: качете чертеж и поставете номериран балон на всеки размер " +
      "за проверка. Номерата ги дава базата данни и ги пази без пропуски.",
    bezeichnungFrei: "Наименование (празно = име на файла)",
    beispiel: "напр. вал 12×40, чертеж 4711",
    wirdGeladen: "Качва се …",
    zeichnungWaehlen: "Изберете чертеж",
    keineZeichnung: "Още няма чертеж",
    keineZeichnungSchreiben: "Качете PDF или изображение — след това размерите могат да се балонират.",
    keineZeichnungLesen: "Щом бъде качен чертеж, той стои тук.",
    bezeichnung: "Наименование",
    teilenummer: "Номер на част",
    kunde: "Клиент",
    hochgeladen: "Качен",
    pruefliste: "Списък за проверка",
    einMass: "1 размер",
    masse: (anzahl: number) => `${anzahl} размера`,
    kopieren: "Копирай",
    csv: "CSV",
    keinMass: "Още няма отбелязан размер.",
    nr: "№",
    seite: "Страница",
    wert: "Стойност",
    wertBeispiel: "напр. 12,0 h7",
    wertZu: (nummer: number) => `Стойност към номер ${nummer}`,
    nachOben: (nummer: number) => `Номер ${nummer} нагоре`,
    nachUnten: (nummer: number) => `Номер ${nummer} надолу`,
    nummer: (nummer: number) => `Номер ${nummer}`,
    drehen: "Завърти изгледа",
    verkleinern: "Намали",
    vergroessern: "Увеличи",
    einpassen: "Побери",
    zeichnung: "Чертеж",
    ladefehler: "Чертежът не можа да се зареди.",
  },
  newsletter: {
    keineAusgabe: "Още няма брой",
    keineAusgabeText: "Щом редакцията публикува брой, той стои тук.",
    zurRedaktion: "Към редакцията",
    quartalJahr: (quartal: number, jahr: number) => `Тримесечие ${quartal} · ${jahr}`,
    entwurfSuffix: " · чернова",
    ausgabe: "Брой",
    quartalKurz: (quartal: number, jahr: number) => `Q${quartal} ${jahr}`,
    entwurfKlammer: " (чернова)",
    alsPdf: "Като PDF",
    wirdGesetzt: "Набира се …",
    seiteVon: (nr: number, gesamt: number) => `Страница ${nr} от ${gesamt} …`,
    redaktion: "Редакция",
    niemandDazu: "През това тримесечие не е дошъл никой нов.",
    beitraege: "Материали",
    belegschaftInZahlen: "Персоналът в числа",
    neuBeiUns: "Нови при нас",
    redaktionEinleitung:
      "По един брой на тримесечие. Главите определят реда в изданието; публикува се " +
      "чак когато е готово.",
    zurLeseransicht: "Към изгледа за четене",
    jahr: "Година",
    quartal: "Тримесечие",
    ausgabeAnlegen: "Създай брой",
    ausgabeBearbeiten: "Редактирай броя",
    keineAusgabeRedaktion: "Изберете година и тримесечие и създайте — след това тук се появяват главите.",
    titelDerAusgabe: "Заглавие на броя",
    status: "Състояние",
    entwurf: "Чернова",
    veroeffentlicht: "публикуван",
    titelbild: "Корица",
    rueckseite: "Задна корица",
    ersetzen: " — замяна",
    waehlen: " — избор",
    ausgabeLoeschen: (quartal: number, jahr: number) => `Брой Q${quartal} ${jahr}`,
    neuesKapitel: "Нова глава",
    kapitelBeispiel: "напр. От производството",
    art: "Вид",
    hinzufuegen: "Добави",
    kapiteltitel: "Заглавие на главата",
    kapitelHoch: "Главата нагоре",
    kapitelRunter: "Главата надолу",
    ueberschrift: "Заглавие",
    eintrag: "Материал",
    textMarkdown: "Текст. Markdown е разрешен — **удебелено**, списъци, таблици.",
    text: "Текст",
    bild: "Изображение",
    bildGroesse: (nr: number) => `Размер на изображение ${nr}`,
    nieEingefroren: "Още нищо не е замразено — главата остава празна в изданието.",
    kpiEingefroren: "Числата за персонала за тримесечието са замразени.",
    niemandEingefroren: "Замразено — през това тримесечие не е дошъл никой нов.",
    zugaengeEingefroren: (anzahl: number) =>
      `Замразено: ${anzahl} ${anzahl === 1 ? "нов колега" : "нови колеги"} през тримесечието.`,
    einfrieren: "Замрази",
    neuEinfrieren: "Замрази наново",
    rechtFehlt: (quelle: string) => `За това липсва правото при източника: да се вижда ${quelle}.`,
    quelleKpi: "Показатели",
    quellePersonal: "Персонал",
    ausgabeAngelegt: "Броят е създаден.",
    ausgabeGeloescht: "Броят е изтрит.",
    kapitelAngelegt: "Главата е създадена.",
    standEingefroren: "Състоянието е замразено.",
  },
  signage: {
    einleitung: "Медии, плейлисти, графици и устройства на екраните.",
    bereiche: "Signage области",
    medien: "Медии",
    medienHinzu: "Добави медии",
    playlists: "Плейлисти",
    zeitplaene: "Графици",
    geraete: "Устройства",
    dateiZiehen: "Пуснете файла тук",
    dateiWaehlen: "Изберете файл",
    dateiHinweis: "Изображение, видео, PDF или PPTX, до 50 MB",
    wirdUebertragen: "прехвърля се …",
    art: "Вид",
    webseite: "Уеб страница (URL)",
    htmlSchnipsel: "HTML откъс",
    titel: "Заглавие",
    titelBeispiel: "Рождени дни",
    urlHinweis:
      "Посочете пълния адрес. Плейърът работи на собствен порт, относителните пътища " +
      "не работят там.",
    aufnehmen: "Добави",
    medienFehler: "Медиите не можаха да се заредят.",
    keineMedien: "Още няма медии",
    keineMedienText:
      "Качете файл или добавете URL. След това медиите могат да се подредят в " +
      "плейлисти.",
    erneut: "отново",
    inVerwendung: "Медията се използва",
    inVerwendungText: (titel: string, anzahl: number) =>
      `„${titel}“ още участва в ${anzahl} плейлист(а). Първо я премахнете там.`,
    verstanden: "Разбрах",
    wartet: "чака",
    konvertiert: "конвертира се",
    fertig: "готово",
    fehlgeschlagen: "неуспешно",
    keineHeartbeats: "Още няма записани сигнали за живот.",
    nieGesehen: "никога не е виждано",
    online: "онлайн",
    vorMinuten: (minuten: number) => `преди ${minuten} мин`,
    offline: "офлайн",
    entzogen: "отнет",
    keinGeraet: "Още няма сдвоено устройство",
    keinGeraetText:
      "Пуснете екран с плейъра. Той показва шестзначен код, който въвеждате тук.",
    geraetKoppeln: "Сдвои устройство",
    geraet: "Устройство",
    status: "Състояние",
    verfuegbarkeit: "Наличност 24 ч",
    ausfaelle: "Прекъсвания 24 ч",
    tags: "Тагове",
    playlist: "Плейлист",
    zuletztGesehen: "Последно видяно",
    seiteNeuLaden: "Презареди страницата",
    neuStarten: "Рестартирай устройството",
    bearbeiten: "Редактирай",
    zugangEntziehen: "Отнеми достъпа",
    geraetBearbeiten: "Редактирай устройството",
    name: "Име",
    bilddrehung: "Завъртане на картината",
    ton: "Звук",
    tonAktiv: "Звукът е включен",
    abbrechen: "Отказ",
    speichern: "Запази",
    tagsHinweis: "Определят кои плейлисти и графици получава това устройство.",
    entziehenText: (name: string) =>
      `„${name}“ губи достъпа си веднага и отново показва кода за сдвояване.`,
    neustartText: (name: string) => `„${name}“ остава черен около минута.`,
    geraetGespeichert: "Устройството е запазено.",
    geraetGeloescht: "Устройството е изтрито.",
    keinGeraetGewaehlt: "няма избрано устройство",
    neuePlaylist: "Нов плейлист",
    neuePlaylistText: "Задайте име и целеви тагове. Записите идват на следващата стъпка.",
    namensbeispiel: "Рецепция",
    keinePlaylist: "Още няма плейлист",
    keinePlaylistText:
      "Плейлистът събира медии в определен ред и се разпределя към устройствата чрез тагове.",
    playlistAnlegen: "Създай плейлист",
    aktiv: "Активен",
    erstellt: "Създаден",
    kopieren: "Копирай",
    playlistGeloescht: "Плейлистът е изтрит.",
    playlistKopiert: "Плейлистът е копиран. Записите не се копират.",
    playlistInPlan: "Плейлистът има активни графици",
    zeitplanHinweis:
      "Графикът има превес над самото разпределение по тагове. Разделете прозорците през " +
      "полунощ на два графика.",
    wochentage: "Дни от седмицата",
    wochentagKuerzel: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд"],
    von: "От",
    bis: "До",
    prioritaet: "Приоритет",
    zeitplanAktiv: "Графикът е активен",
    keineZeitplaene: "Няма графици",
    keineZeitplaeneText:
      "Без график единствено разпределението по тагове решава кой плейлист показва едно " +
      "устройство. Графикът поставя плейлист пред него в определени дни и часове.",
    tage: "Дни",
    zeitfenster: "Времеви прозорец",
    aktionen: "Действия",
    zeitplanBearbeiten: "Редактирай графика",
    neuerZeitplan: "Нов график",
    zeitplaeneFehler: "Графиците не можаха да се заредят.",
    endeNachStart: "Краят трябва да е след началото. През полунощ, моля, създайте два графика.",
    mindestensEinTag: "Изберете поне един ден от седмицата.",
    playlistWaehlen: "Изберете плейлист.",
    taeglich: "всеки ден",
    zielTags: "Целеви тагове",
    ueberblenden: "Плавен преход",
    harterSchnitt: "Рязък преход",
    ziehpunkt: "Дръжка за влачене",
    verwerfen: "Отхвърли",
    medienHinzufuegen: "Добавете медии и ги подредете с дръжката за влачене.",
    mediumWaehlen: "Изберете медия",
    mediumHinzufuegen: "Добави медия",
    mediumWaehlenText: "Избраната медия се добавя в края на плейлиста.",
    schliessen: "Затвори",
    keineMedienAnlegen: "Още няма медии. Първо създайте такива в областта Медии.",
    unbekanntesMedium: "неизвестна медия",
    playlistGespeichert: "Плейлистът е запазен. Устройствата презареждат веднага.",
    kopplungscode: "Код за сдвояване",
    codeBeispiel: "ABC-123",
    geraetename: "Име на устройството",
    geraeteBeispiel: "Рецепция ляво",
    tagsPflicht: "Чрез таговете устройството получава плейлиста си. Без таг екранът остава празен.",
    koppeln: "Сдвои",
    formatErwartet: "Очаква се формат XXX-XXX.",
    codeUnbekannt: "Кодът е непознат, изтекъл или вече зает. Покажете нов на екрана.",
    tagEingeben: "Въведете таг и натиснете Enter",
  },
  einstellungen: {
    titel: "Настройки",
    einleitung: "Какво изчислява, взема и показва платформата — еднакво за всички.",
    bereiche: "Области",
    gruppen: {
      kennzahlen: "Показатели",
      kennzahlenText:
        "Целеви стойности на таблата. Появяват се като целева линия в графиката и решават кога " +
        "една карта предупреждава.",
      personal: "HR",
      personalText:
        "Кои отсъствия се броят като болнични и кои отдели спадат към производството. " +
        "Без тези списъци процентите за персонала остават празни.",
      atr: "ATR",
      atrText:
        "Какво стои еднакво във всеки документ на една програма и откъде идват стоковите разписки.",
      qualitaet: "Качество",
      qualitaetText:
        "Матрицата на стандартите, на която се позовава един одит, и шаблоните за фази, които " +
        "нов одит получава като контролен списък.",
      sensoren: "Сензори",
      sensorenText:
        "Измервателните устройства в мрежата: къде стоят, под какъв идентификатор подават " +
        "температура и влажност и кога една стойност се смята за твърде висока.",
      zeugnisse: "Препоръки",
      zeugnisseText:
        "Какво стои еднакво на всяка препоръка: фирма, град и двата подписа. " +
        "Подписът на прекия ръководител се извежда при създаването от Personio — тук стои само резервният.",
      erscheinung: "Изглед",
      erscheinungText:
        "Фирменото лого — горе вляво в приложението и в заглавната част на всеки създаден файл: " +
        "план за въвеждане, доказателство за поддръжка, преглед на обученията, препоръка.",
      anzeigen: "Табла",
      anzeigenText:
        "Адресите, които вървят по екраните в предприятието. Всеки носи подписан " +
        "токен, важи само за своето табло и изтича.",
      zugaenge: "Потребители и групи",
      zugaengeText:
        "Създаване на хора, изграждане на групи и даване на права за приложения. Промените важат, щом " +
        "засегнатият човек влезе следващия път — правата стоят в неговия токен.",
    },
  },
  einstellungenText: {
    speichernFehler: (meldung: string) => `Запазването се провали: ${meldung}`,
    zielwertGespeichert: "Целевата стойност е запазена. Таблата я показват след презареждане.",
    zahlAbNull: "Моля, въведете число от 0 нагоре.",
    personalGespeichert: "Запазено. Таблото на персонала го показва след презареждане.",
    krankTypen: "Видове отсъствия, които се броят като болнични",
    produktionAbteilungen: "Отдели на производството",
    kompetenzAttribute: "Полета в Personio, които се броят за попълнена компетенция",
    ausDemBestand: "от наличните данни",
    abteilungenBeispiel: "Производство, Монтаж",
    firmenlogo: "Фирмено лого",
    anzeigenHinweis:
      "Създава адреса за един запис в плейлист на Signage плейъра. Той важи само за " +
      "избраното табло и изтича — запис, който никой вече не поддържа, спира сам " +
      "да се показва.",
    logoHinweis:
      "Стои горе вляво в приложението и в заглавната част на всеки създаден формуляр — " +
      "план за въвеждане, доказателство за поддръжка, преглед на обученията, препоръка. PNG или JPEG, " +
      "най-много 5 MB. Ако няма заложено, там стои надписът „ACM-Plattform“.",
    communityHinweis: "записва се шифровано и повече не се показва",
    verwaltenSchliesstEin: "„Управление“ на картата на платформата включва всяко друго право.",
    logoAlt: "Заложеното фирмено лого",
    keinsHinterlegt: "Още няма заложено.",
    laedt: "Качва се …",
    ersetzen: "Замени",
    hochladen: "Качи",
    logoHochladen: "Качи фирмено лого",
    logoHinterlegt: "Логото е заложено.",
    anzeige: "Табло",
    geburtstage: "Рождени дни на седмицата",
    neuzugaenge: "Нови в екипа",
    gueltigTage: "Валиден за (дни)",
    erzeugt: "Създава се …",
    adresseErzeugen: "Създай адрес",
    adresseKopiert: "Адресът е копиран.",
    kopierenFehler: "Копирането не стана — моля, маркирайте на ръка.",
    kopieren: "Копирай",
    gespeichert: "Запазено.",
    speichern: "Запази",
    speichert: "Запазва …",
    firma: "Фирма",
    ort: "Град (над датата)",
    nameRueckfall: "Име (резервно)",
    titelRueckfall: "Длъжност (резервна)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "Профил на издателя",
    ausstellerHinweis:
      "Стои на всяка препоръка. Бланката на ACM се използва, щом „ACM“ стои във " +
      "името на фирмата.",
    linkeUnterschrift: "Ляв подпис — пряк ръководител",
    linkeHinweis:
      "Обикновено ръководителят на човека; той се извежда при създаването от Personio. " +
      "Това, което стои тук, важи само ако Personio не дава нищо — например при хора, " +
      "поддържани извън системата.",
    rechteUnterschrift: "Десен подпис — човешки ресурси",
    rechteHinweis:
      "Един и същ за всички препоръки. Обвързан с човек от Personio, длъжността идва " +
      "оттам и остава вярна, когато позицията се промени.",
    personAusPersonio: "Човек от Personio",
    keinePerson: "— никой, използвайте свободния текст отдолу —",
    personenFehler: (meldung: string) => `Списъкът с хора не можа да се зареди (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "Шаблони",
    vorlagenHinweis:
      "По един шаблон на програма. Заглавните данни и скелетният файл стоят еднакво във всеки " +
      "ATR документ на тази програма. Шаблонът се създава при зареждане на референтна папка в " +
      "каталога на частите.",
    keineVorlage: "Още няма шаблон",
    keineVorlageText: "Заредете референтна папка — програмата стои там в клетка D2.",
    geruestHinterlegt: "Скелетният файл е заложен.",
    geruestErsetzen: "Замени скелета",
    geruestWaehlen: "Изберете скелет",
    keineHinterlegt: "още няма заложен",
    kunde: "Клиент",
    lieferant: "Доставчик",
    arbeitspaket: "Работен пакет",
    referenz: "Референция",
    bestellerSpez: "Спецификация на възложителя",
    lieferantenSpez: "Спецификация на доставчика",
    kundenSpez: "Спецификация на клиента",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "ATA глава",
    waage: "Везна",
    qsUnterschrift: "Подпис ОТК",
    eingangsordner: "Входяща папка",
    eingangHinweis:
      "Стокова разписка във входящата папка се зарежда, става доставка и отива в архива. " +
      "Паролата на служебния профил не стои тук, а като ATR_SMB_PASSWORT в " +
      "средата; кои хостове са допустими, задава ATR_SMB_ERLAUBT.",
    laeuft: "работи",
    aus: "изключено",
    zuletzt: (zeit: string, text: string) => `Последно ${zeit}: ${text}`,
    nochNichtGelaufen: "Още не е работило.",
    prueft: "Проверява …",
    verbindungPruefen: "Провери връзката",
    laeuftGerade: "Работи …",
    jetztDurchsehen: "Прегледай сега",
    verbindungSteht: (dateien: number) =>
      `Връзката работи. ${dateien} ${dateien === 1 ? "файл чака" : "файла чакат"} във входящата папка.`,
    keineVerbindung: (meldung: string) => `Няма връзка: ${meldung}`,
    unbekannt: "неизвестно",
    gelesenAngelegt: (gelesen: number, angelegt: number) =>
      `${gelesen} прочетени, ${angelegt} създадени.`,
    rechner: "Хост",
    rechnerHinweis: "трябва да стои в ATR_SMB_ERLAUBT",
    freigabe: "Споделена папка",
    domaene: "Домейн",
    benutzer: "Потребител",
    eingang: "Вход",
    ausgang: "Изход",
    archiv: "Архив",
    wasEinLaufTut: "Какво прави едно преминаване",
    entwurfAnlegen: "Създай чернова за преглед",
    dokumenteErzeugen: "Създай документите и ги подреди",
    regelmaessig: "Преглеждай редовно",
    regelmaessigHinweis: "Преглеждай редовно — на всеки десет минути, в делник от 5 до 19 ч.",
  },
  qualitaetEinstellungen: {
    normmatrix: "Матрица на стандартите",
    normmatrixHinweis:
      "Клаузи, на които се позовава един одит. Използван стандарт не може да се изтрие — " +
      "той се спира, иначе одитът тихо би загубил основата си.",
    schonInMatrix: "Тази клауза вече стои в матрицата.",
    regelwerk: "Стандарт",
    revision: "Редакция",
    klausel: "Клауза",
    kurztext: "Кратък текст",
    kurztextBeispiel: "Вътрешен одит",
    aufnehmen: "Добави",
    geprueft: "Проверена",
    aktiv: "Активна",
    geprueftSchalter: (norm: string) => `${norm} проверена`,
    aktivSchalter: (norm: string) => `${norm} активна`,
    phasenvorlagen: "Шаблони за фази",
    phasenvorlagenHinweis:
      "Последователността от стъпки, която нов одит получава. Тя се копира при създаването — " +
      "по-късна промяна не пренаписва история.",
    neueVorlage: "Нов шаблон",
    vorlageBeispiel: "Стандартен системен одит",
    anlegen: "Създай",
    schritte: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "стъпка" : "стъпки"}`,
    schrittErgaenzen: "Добави стъпка",
    schrittBeispiel: "напр. откриващ разговор",
  },
  personioZugang: {
    titel: "Данни за достъп до Personio",
    einleitung:
      "Данни за достъп на приложение към Personio API. Без тях синхронизацията, " +
      "профилните снимки и списъците с предложения остават празни.",
    kennung: "Client-ID",
    geheimnis: "Client-Secret",
    feldHinweis:
      "Записват се шифровано и повече не се показват. Който иска да ги смени, " +
      "въвежда нови.",
    speichern: "Запази",
    gespeichert: "Данните за достъп са заложени.",
    speichernFehler: (meldung: string) => `Запазването се провали: ${meldung}`,
    entfernen: "Премахни",
    entfernt: "Данните за достъп са премахнати.",
    pruefen: "Провери връзката",
    prueftGerade: "Проверява …",
    verbindungSteht: "Personio приема данните за достъп.",
    verbindungFehlt: "Personio не отговаря.",
    laedt: "Зарежда се …",
    keineHinterlegt: "Няма заложени данни за достъп.",
    ausDerUmgebung: "Важат данните за достъп от средата на сървъра (.env).",
    hinterlegtSeit: (zeitpunkt: string, wer: string | null) =>
      wer
        ? `Заложени на ${zeitpunkt} от ${wer}.`
        : `Заложени на ${zeitpunkt}.`,
    ohneSchluessel:
      "На сървъра не е зададен GEHEIM_SCHLUESSEL. Докато липсва, " +
      "нищо не може да се запише шифровано.",
  },
  sensorEinstellungen: {
    neuesGeraet: "Ново устройство",
    name: "Име",
    nameBeispiel: "Сървърно помещение",
    rechner: "Хост",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "трябва да стои в SNMP_ERLAUBT",
    community: "Community",
    port: "Порт",
    kennungTemperatur: "OID температура",
    kennungLuftfeuchte: "OID влажност",
    faktorTemperatur: "Коефициент температура",
    faktorHinweis: "0,1 когато устройството подава десети от градуса като цяло число",
    faktorLuftfeuchte: "Коефициент влажност",
    temperaturAb: "Температура от (°C)",
    temperaturBis: "Температура до (°C)",
    feuchteAb: "Влажност от (%)",
    feuchteBis: "Влажност до (%)",
    farbe: "Цвят в графиката",
    farbeHinweis: "напр. #0f6e8c",
    optional: "по желание",
    anlegen: "Създай",
    fragt: "Запитва …",
    ausprobieren: "Пробвай",
    keinGeraet: "Още няма устройство",
    keinGeraetText: "Въведете горе хост, community и поне един OID.",
    wirdAbgefragt: (name: string) => `${name} се запитва`,
    communityErsetzen: "Замени community",
    unveraendert: "непроменено",
    communityErsetzt: "Community е заменено.",
    sensorAngelegt: "Сензорът е създаден.",
    sensorGeloescht: "Сензорът е изтрит заедно с времевия си ред.",
    zahlEingeben: "Моля, въведете число.",
  },
  zugaenge: {
    stufen: {
      viewer: "Преглед",
      editor: "Редактиране",
      admin: "Управление",
    },
    gruppeAngelegt: "Групата е създадена.",
    gruppeGibtEsSchon: "Група с това име вече съществува.",
    personAngelegt: "Човекът е създаден",
    gruppeUmbenannt: "Групата е преименувана.",
    gruppeGeloescht: "Групата е изтрита.",
    mitgliedHinzu: "Членът е добавен. Важи след следващото влизане.",
    schonInGruppe: "Този човек вече е в групата.",
    neuesPasswort: "Нова парола",
    mitgliedEntfernt: "Членът е премахнат. Важи след следващото влизане.",
    gemeldeteSeiten: "Виж сигналите за страници",
    neueGruppe: "Нова група",
    gruppeBeispiel: "напр. Вътрешни продажби",
    anlegen: "Създай",
    neuePerson: "Нов човек",
    personBeispiel: "ime.familiya@acm.local",
    keineGruppe: "Още няма група",
    keineGruppeText: "Създайте група, дайте ѝ права за приложения и добавете хора.",
    verzeichnis: "Директория",
    ausVerzeichnis: "Идва от директорията",
    umbenennen: "Преименувай",
    keinZugriff: "няма достъп",
    rechteAnGruppe: "Правата висят на групата, не на човека.",
    passwortNurJetzt:
      "Паролата стои тук само сега. След това може само да се нулира, не и да се покаже.",
    fertig: "Готово",
    anmeldung: "Вход",
    passwort: "Парола",
    gruppeUmbenennen: "Преименувай групата",
    abbrechen: "Отказ",
    speichern: "Запази",
    gruppenname: "Име на групата",
    mitgliederVon: (name: string) => `Членове на „${name}“`,
    wirktNachAnmeldung: "Промените важат, щом човекът влезе следващия път.",
    schliessen: "Затвори",
    personHinzufuegen: "Добави човек",
    auswaehlen: "— изберете —",
    hinzufuegen: "Добави",
    keineMitglieder: "Тази група още няма членове.",
    passwortZuruecksetzen: "Нулирай паролата",
    mitgliedEntfernen: "Премахни член",
    entfernen: "Премахни",
  },
  kopftitel: {
    start: "Приложения",
    kennzahlen: "KPI табло",
    offeneSchulungen: "Неизпълнени обучения",
    schulungsmatrix: "Матрица на обученията",
    atrLieferungen: "ATR доставки",
  },
  kennzahlenHub: {
    titel: "KPI табло",
    einleitung:
      "Показатели по направления. Данните идват от ERP експортите в Качвания.",
    bereiche: {
      "/kpi/vertrieb": "Оборот, стойност на поръчка, дял на клиентите",
      "/hr/kennzahlen": "Персонал, текучество, болнични — отделно право",
      "/kpi/qualitaet": "Одитни констатации и процент рекламации",
      "/kpi/finanzen": "Процент материални разходи и разходи за персонал",
      "/kpi/einkauf": "Спазване на сроковете от доставчиците",
      "/kpi/produktion": "Закъснения, просрочени поръчки",
      "/kpi/bewertung": "Коментари и мерки към всеки показател",
    },
  },
  personalHub: {
    einleitung:
      "Работата с персонала, по области. Числата са една от тях.",
    bereiche: {
      "/hr/kennzahlen": "Персонал, текучество, болнични, извънреден труд",
      "/hr/organigramm": "Кой на кого се отчита",
      "/hr/kompetenzen": "Квалификационна матрица по отдели",
      "/hr/schulungen": "Задължителни обучения, дати, доказателства",
      "/hr/onboarding": "Постъпили и какво трябва да се направи за тях",
      "/hr/einarbeitung": "Планове за въвеждане и докъде са стигнали",
      "/hr/dokumente": "Създаване, печат и обратно прочитане на формуляри",
      "/hr/zeugnisse": "Писане и издаване на препоръки",
    },
  },
  bewertung: {
    titel: "KPI оценка",
    einleitung:
      "Коментирайте какво означава едно число и запишете какво следва от него. Списъкът са " +
      "показателите с целева стойност — същият списък, който определя и таблата.",
    uebersichtFehler: (meldung: string) =>
      `Прегледът не можа да се зареди: ${meldung}`,
    nurLesen:
      "Можете да четете оценки, но не и да пишете. За това е нужно правото " +
      "„Редактиране“ върху настройките.",
    stand: (offen: number, ueberfaellig: number, erledigt: number, kommentare: number) =>
      `${offen} открити, от тях ${ueberfaellig} просрочени · ${erledigt} изпълнени · ` +
      `${kommentare} ${kommentare === 1 ? "коментар" : "коментара"}`,
    offenTitel: (anzahl: number) => `${anzahl} открити`,
    ueberfaelligTitel: (anzahl: number) => `${anzahl} просрочени`,
    massnahmen: "Мерки",
    wasZuTun: "Какво трябва да се направи",
    zustaendig: "Отговорник",
    faellig: "Падеж",
    anlegen: "Създай",
    ohneZustaendigen: "без отговорник",
    faelligAm: (datum: string) => `падеж ${datum}`,
    erledigtAm: (datum: string) => `изпълнена на ${datum}`,
    massnahmeLoeschen: "Изтрий мярката",
    keineMassnahme: "Още няма мярка към този показател.",
    kommentare: "Коментари",
    kommentarPlatzhalter: "Какво казва това число?",
    kommentarLoeschen: "Изтрий коментара",
    keinKommentar: "Още нищо не е казано за този показател.",
    status: {
      offen: "открита",
      laeuft: "тече",
      erledigt: "изпълнена",
      verworfen: "отхвърлена",
    },
    bereiche: {
      vertrieb: "Продажби",
      einkauf: "Снабдяване",
      produktion: "Производство",
      qualitaet: "Качество",
      finanzen: "Финанси",
      personal: "HR",
    },
  },
  erklaerung: {
    hinweis: "Обяснение",
    frage: (titel: string) => `Как се изчислява „${titel}“?`,
    knopf: "Изчисление",
    untertitel: "Така се изчислява",
    ganzeSeite: "Цялата помощна страница",
  },
};
