import { TITEL, type Pfadtitel } from "@/lib/brotkrumen";

/**
 * Die deutschen Texte der Oberfläche. Diese Datei ist die Vorlage: ihr Typ
 * bestimmt, was jede andere Sprache liefern muss — eine fehlende Übersetzung
 * ist ein Übersetzungsfehler und kein leerer Kasten zur Laufzeit.
 *
 * Es stehen hier nur Texte der **Schale**: Kopfzeile, Pfad, Startbildschirm,
 * Anmeldung. Die Fachseiten kommen bereichsweise dazu. Ein halbes Wörterbuch
 * ist besser als ein ganzes, das zur Hälfte maschinell geraten ist.
 */
export const de = {
  kopf: {
    uebersicht: "Zur Übersicht",
    hilfe: "Hilfe",
    einstellungen: "Einstellungen",
    abmelden: "Abmelden",
    sprache: "Sprache",
    erscheinungsbild: "Erscheinungsbild",
    hell: "Hell",
    dunkel: "Dunkel",
    system: "Wie das System",
    meldungenLeer: "Meldungen — nichts Neues",
    meldungen: (anzahl: number) => `Meldungen — ${anzahl} noch nicht angesehen`,
    massnahmenLeer: "Maßnahmen — keine offen",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Maßnahmen — ${offen} offen, davon ${ueberfaellig} überfällig`
        : `Maßnahmen — ${offen} offen`,
  },
  pfad: {
    aria: "Pfad",
    start: "Start",
    seiten: TITEL as Pfadtitel,
  },
  start: {
    titel: "Apps",
    verweigert: (name: string) => `Für „${name}“ hast du keine Berechtigung.`,
    keineApp:
      "Deinem Konto ist noch keine App zugewiesen. Bitte an die Plattform-Verwaltung wenden.",
  },
  anmeldung: {
    titel: "ACM-Plattform",
    aufforderung: "Mit deinem Konto anmelden.",
    email: "E-Mail",
    passwort: "Passwort",
    knopf: "Anmelden",
    laeuft: "Anmelden …",
  },
  allgemein: {
    laedt: "Wird geladen …",
  },
  zeitraum: {
    monat: "Dieser Monat",
    quartal: "Dieses Quartal",
    jahr: "Dieses Jahr",
    alles: "Alles",
    frei: "Zeitraum wählen",
    von: "von",
    bis: "bis",
    vonAria: "Zeitraum von",
    bisAria: "Zeitraum bis",
    verdreht: "Das Ende liegt vor dem Anfang.",
  },
  vergleich: {
    vorperiode: "zur Vorperiode",
    vormonat: "zum Vormonat",
    vorquartal: "zum Vorquartal",
    vorjahr: "zum Vorjahr",
    zeitraumDavor: "zum Zeitraum davor",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Datenstand ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Datenstand unvollständig — ${fehlend} ${anzahl === 1 ? "fehlt" : "fehlen"}`,
    heute: "heute",
    gestern: "gestern",
    vorTagen: (tage: number) => `vor ${tage} Tagen`,
    nie: "nie",
    arten: {
      umsatz: "Umsatz",
      auftraege: "Aufträge",
      angebote: "Angebote",
      interessenten: "Interessenten",
      kontakte: "Kontakte",
      liefertreue: "Liefertreue",
      lagerbewegungen: "Lagerbewegungen",
      lagerpreise: "Lagerpreise",
      auftragspositionen: "Auftragspositionen",
      lieferscheine: "Lieferscheine",
      pruefungen: "Prüfungen",
      acht_d: "8D-Berichte",
      wareneingaenge: "Wareneingänge",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `Kennzahlen konnten nicht geladen werden: ${meldung}`,
    keineDatenTitel: "Für diesen Zeitraum liegen keine Daten vor",
    keineDatenVor: "Lade die ERP-Exporte unter ",
    keineDatenNach: " hoch, oder wähle einen größeren Zeitraum.",
    keineWerte: "keine Werte im Zeitraum",
    laedt: "wird geladen …",
    jeTag: "je Tag",
    jeWoche: "je Woche",
    jeMonat: "je Monat",
  },
  vertrieb: {
    umsatz: "Umsatz",
    umsatzHinweis: "Rechnungen abzüglich Gutschriften",
    auftragswert: "Ø Auftragswert",
    ueberNull: "Aufträge über 0 €",
    auftraege: "Aufträge gesamt",
    verlauf: "Umsatzverlauf",
    verlaufHinweis: (takt: string) => `${takt}, Gutschriften abgezogen`,
    kundenanteil: "Kundenanteil am Umsatz",
    kunde: "Kunde",
    anteil: "Anteil",
    uebrige: "Übrige",
    jeErfasser: "Aufträge je Erfasser",
    erfasser: "Erfasser",
    anzahl: "Aufträge",
    summe: "Summe",
  },
  aktivitaet: {
    titel: "Vertriebsaktivität",
    jeWoche: (von: string, bis: string) => `je Kalenderwoche, ${von} bis ${bis}`,
    ladeFehler: (meldung: string) => `Vertriebsaktivität konnte nicht geladen werden: ${meldung}`,
    leer: "Keine Kontakte, Angebote oder Interessenten in diesem Zeitraum.",
    kw: (woche: string) => `KW ${woche}`,
    ziel: (wert: string) => `Ziel ${wert} / Woche`,
    erstkontakte: "Erstkontakte",
    erstkontakteHinweis: "erledigte Kontakte vom Typ ERS",
    besuche: "Besuche",
    besucheHinweis: "vor Ort und online zusammen",
    interessenten: "Interessenten",
    interessentenHinweis: "neu erfasst, ohne Vertriebler-Zuordnung",
    angebote: "Angebote",
    angeboteHinweis: "Summe der geschriebenen Angebote",
    auftragseingang: "Auftragseingang",
    auftragseingangHinweis: "Stornos gegengerechnet",
  },
  einkauf: {
    einleitung: "Liefertermintreue der Lieferanten. Gezählt wird, was im Zeitraum angekommen ist.",
    keineDaten: "Für diesen Zeitraum liegen keine Lieferpositionen vor",
    ladeVor: "Lade den Liefertreue-Export unter ",
    ladeNach: " hoch.",
    otd: "OTD-Quote",
    otdHinweis: (ziel: string) => `Ziel ${ziel} · pünktlich heißt Verzug ≤ 0`,
    puenktlich: "Pünktliche Positionen",
    gesamt: "Positionen gesamt",
    verzugSchnitt: "Ø Verzug",
    verzugHinweis: "Positionen ohne Verzugswert zählen hier nicht mit",
    verlauf: "OTD-Quote im Zeitverlauf",
    verlaufHinweis: "Lücken sind Zeiträume ohne Lieferpositionen.",
    ladenhueter: "Bestellung auf Lager — Ladenhüter",
    kapital: (wert: string) => `Gebundenes Kapital: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Lagerartikel ohne Bewegung seit mindestens ${tage} Tagen, höchster Wert zuerst. ` +
      "Stichtag ist heute — der Zeitraum oben gilt hier nicht, weil ein Bestand kein Zeitraum ist.",
    artikel: "Artikel",
    bezeichnung: "Bezeichnung",
    bestand: "Bestand",
    liegtSeit: "Liegt seit",
    stueckpreis: "Stückpreis",
    wert: "Wert",
    positionen: "Lieferpositionen",
    positionenHinweis:
      "Größter Verzug zuerst, Positionen ohne Verzugswert ganz oben. Höchstens 500 Zeilen.",
    auftrag: "Auftrag",
    lieferant: "Lieferant",
    zieltermin: "Zieltermin",
    geliefert: "Geliefert",
    verzug: "Verzug",
  },
  produktion: {
    einleitung: "Aufträge in Verzug. Gezählt wird ein Auftrag erst, wenn sein Ausgang feststeht.",
    keineDaten: "Für diesen Zeitraum liegt kein Auftrag mit feststehendem Ausgang vor",
    ladeVor: "Lade die Auftragspositionen und die Lieferscheine unter ",
    ladeNach:
      " hoch. Beide werden gebraucht: die eine Datei trägt den Zieltermin, die andere das Ist-Datum.",
    quote: "Verzugsquote",
    quoteHinweis: (ziel: string) => `Höchstens ${ziel}`,
    inVerzug: "Aufträge in Verzug",
    gesamt: "Aufträge gesamt",
    gesamtHinweis: "ohne noch nicht fällige offene Aufträge",
    verzugSchnitt: "Ø Verzug",
    verzugHinweis: "pünktliche Aufträge gehen negativ ein",
    verlauf: "Verzugsquote im Zeitverlauf",
    verlaufHinweis: "Nach Zieltermin. Lücken sind Zeiträume ohne gezählte Aufträge.",
    ziellinie: "Ziel",
    liste: "Aufträge in Verzug",
    listeHinweis:
      "Größter Verzug zuerst. Bei offenen Aufträgen wächst er täglich weiter. Höchstens 500 Zeilen.",
    auftrag: "Auftrag",
    kunde: "Kunde",
    stand: "Stand",
    zieltermin: "Zieltermin",
    geliefert: "Geliefert",
    verzug: "Verzug",
    verspaetet: "zu spät geliefert",
    offen: "offen, überfällig",
  },
  finanzen: {
    einleitung: "Material- und Personalkosten im Verhältnis zum Rechnungsumsatz.",
    keineDatenVor:
      "Es braucht drei Dateien: die Lagerbewegungen für den Verbrauch, die Wareneingänge für " +
      "die Preise und den Umsatz als Bezugsgröße. Alle drei liegen unter ",
    keineDatenNach: ".",
    materialquote: "Materialkostenquote",
    materialquoteHinweis: "Materialkosten / Umsatz",
    hoechstens: (ziel: string) => `Höchstens ${ziel}`,
    materialkosten: "Materialkosten",
    umsatz: "Umsatz",
    personalquote: "Personalkostenquote",
    brauchtZeitraum: "braucht einen Zeitraum",
    personalHinweis: (kosten: string, personen: string) => `${kosten} bei ${personen} Personen`,
    ohnePreis: "Artikel ohne Preis",
    ohnePreisHinweis: "verbraucht, aber nicht bewertet",
    jeAbteilung: "Personalkosten je Abteilung",
    abteilung: "Abteilung",
    personen: "Personen",
    kosten: "Kosten",
    anteil: "Anteil",
    verlauf: "Materialkostenquote im Zeitverlauf",
    verlaufHinweis: "Lücken sind Zeiträume ohne Umsatz — ohne Bezugsgröße gibt es keine Quote.",
    ziellinie: "Ziel",
    verbrauch: "Materialverbrauch je Artikel",
    verbrauchHinweis:
      "Höchste Kosten zuerst. Artikel ohne Preis stehen am Ende — sie gehen in die Quote " +
      "nicht ein. Höchstens 500 Zeilen.",
    artikel: "Artikel",
    bezeichnung: "Bezeichnung",
    menge: "Verbrauch",
    stueckpreis: "Stückpreis",
    keinPreis: "kein Preis",
  },
  qualitaet: {
    einleitung: "Audit-Findings, Reklamationsquote und Prüfmengen.",
    auditart: "Auditart:",
    keineArt: "Keine Auditart ausgewählt. Wähle mindestens eine, sonst gibt es nichts zu zählen.",
    keineDaten: "Für diesen Zeitraum liegen keine Audit-Befunde vor",
    ladeVor: "Lade den 8D-Export unter ",
    ladeNach: " hoch.",
    behoerde: "Behörde",
    extern: "Extern",
    intern: "Intern",
    kunde: "Kunde",
    level1: "Audit-Findings Level 1",
    level2: "Audit-Findings Level 2",
    ohneLevel: "Ohne erkennbares Level",
    ohneLevelHinweis: "zählt in keiner Kachel",
    hoechstens: (ziel: number) => `Höchstens ${ziel}`,
    auditVerlauf: "Audit-Findings im Zeitverlauf",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `Anteil der Menge ohne Beanstandung. Bezugsgröße: ${bezug}.`,
    fehlerquote: (quote: string) => `Fehlerquote: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Fehlerquote: ${quote} · Ziel ${ziel}`,
    reklamiert: "Reklamierte Menge",
    bezugsmenge: "Bezugsmenge",
    bezugsmengeNull: "ohne sie gibt es keine Quote",
    mehrAlsBezogen:
      "Es ist mehr reklamiert als bezogen worden. Das kann die Rechnung nicht auflösen: " +
      "Zähler und Nenner kommen aus verschiedenen Dateien mit eigenen Datumsfeldern. Prüfe, " +
      "ob die Bezugsdatei für diesen Zeitraum vollständig hochgeladen ist.",
    reklKunde: "Kunde",
    reklIntern: "intern",
    reklLieferant: "Material-Lieferanten",
    reklWerkbank: "Werkbänke",
    bezugKunde: "gelieferte Menge",
    bezugIntern: "gelieferte Menge",
    bezugLieferant: "Wareneingang ohne Dienstleistung",
    bezugWerkbank: "Wareneingang der Warengruppen DIENST und SERVIC",
    mengeGesamt: "gemeldete Menge",
    mengeAkzeptiert: "akzeptierte Menge",
    onQualityBezug: (menge: string) => `On Quality (Bezug ${menge})`,
    ziellinie: "Ziel",
    geprueft: "Geprüfte Produkte",
    geprueftHinweis: (pruefer: string, tage: string) =>
      `Menge je Prüfer und Prüftag. Der Teiler ist für beide Größen derselbe: ${pruefer} Prüfer an ${tage} Tagen.`,
    gross: "Große Produkte",
    klein: "Kleine Produkte",
    mindestens: (ziel: number) => `Mindestens ${ziel} je Tag und Prüfer`,
    buchungen: "Buchungen der Qualitätsprüfung",
    buchungenHinweis:
      "Eine abgewählte Buchung bleibt stehen, zählt aber in keiner Kachel. " +
      "Größte Menge zuerst, höchstens 500 Zeilen.",
    zaehltMit: "Zählt mit",
    datum: "Datum",
    pruefer: "Prüfer",
    produkt: "Produkt",
    groesse: "Größe",
    menge: "Menge",
    ausschuss: "Ausschuss",
    mitzaehlen: (datum: string) => `Buchung vom ${datum} mitzählen`,
    klasseGross: "groß",
    klasseKlein: "klein",
    diagnose: "Befunde ohne erkennbares Level",
    diagnoseHinweis:
      "Das Level steht in der Quelldatei im Freitext. Steht dort weder „Major … Level 1“ noch " +
      "„Minor … Level 2“, zählt der Befund nirgends. Diese Liste zeigt, wo nachzubessern ist.",
    bericht: "Bericht",
    art: "Art",
    adresse: "Adresse",
    bezeichnung: "Bezeichnung",
  },
  personal: {
    einleitung:
      "Aus dem Personio-Abgleich. Das Tagessoll kommt aus dem hinterlegten " +
      "Arbeitszeitmodell je Person, nicht aus einem pauschalen Achtstundentag.",
    uebersicht: "Übersicht",
    standLaedt: "Abgleichstand wird geladen …",
    keinAbgleich: "Noch kein Abgleich gelaufen. Er läuft nachts um 02:15 von selbst.",
    letzterAbgleich: (zeitpunkt: string, status: string) => `Letzter Abgleich ${zeitpunkt} · ${status}`,
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} Personen, ${anwesenheiten} Anwesenheiten, ${abwesenheiten} Abwesenheiten`,
    abgleichLaeuft: "läuft …",
    abgleichen: "Jetzt abgleichen",
    keineDaten: "Für diesen Zeitraum liegen keine Anwesenheiten vor",
    keineDatenHinweis:
      "Entweder ist der Personio-Abgleich noch nicht gelaufen, oder der Zeitraum liegt " +
      "vor dem Beginn der Aufzeichnung.",
    ueberstunden: "Überstunden-Quote",
    stundenVon: (teil: string, ganz: string) => `${teil} von ${ganz} Std.`,
    krankheit: "Krankheitsquote",
    krankheitsartenFehlen: "Krankheitsarten nicht hinterlegt",
    fluktuation: "Fluktuation",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} Austritte, Ø ${schnitt} Beschäftigte`,
    personen: "Erfasste Personen",
    personenHinweis: "mit Anwesenheit im Zeitraum",
    krankheitHinweisVor:
      "Die Krankheitsquote bleibt leer, solange nicht hinterlegt ist, welche " +
      "Personio-Abwesenheitsarten als Krankheit zählen. Einzutragen unter ",
    krankheitHinweisNach: ".",
    verlauf: "Verlauf",
    reiheUeberstunden: "Überstunden",
    reiheKrankheit: "Krankheit",
  },
  melden: {
    knopf: "Melden",
    titel: "Etwas melden",
    frage: "Was stimmt auf dieser Seite nicht? Ein Bild der Seite geht mit.",
    abbrechen: "Abbrechen",
    senden: "Senden",
    sendet: "Wird gesendet …",
    beispiel: "Zum Beispiel: Die Kachel zeigt einen leeren Wert, obwohl Daten da sind.",
    beschreibung: "Beschreibung",
    aufnahme: "Aufnahme der Seite",
    gehtMit: "Diese Aufnahme geht mit.",
    nimmtAuf: "Die Seite wird aufgenommen …",
    misslungen: "Die Seite ließ sich nicht aufnehmen — die Meldung geht ohne Bild.",
    dankeMitBild: "Danke — die Meldung ist angekommen.",
    dankeOhneBild: "Danke — die Meldung ist angekommen, ohne Bild der Seite.",
  },
  belegschaft: {
    titel: "Belegschaft",
    hinweis:
      "Stand heute. Die Verteilungen zeigen die aktuellen Stammdaten, nicht die von damals — " +
      "Personio liefert keine Historie. Dass „Beschäftigte“ und die Kompetenzquote verschiedene " +
      "Nenner haben, ist Absicht: die eine Zahl folgt dem Personio-Status, die andere Ein- und " +
      "Austrittsdatum. Beide Wege stammen aus dem Altprojekt.",
    ladeFehler: (meldung: string) => `Belegschaft konnte nicht geladen werden: ${meldung}`,
    beschaeftigte: "Beschäftigte",
    beschaeftigteHinweis: "nach Personio-Status „aktiv“",
    neuImQuartal: "Neu im Quartal",
    bestand: "Bestand",
    kompetenzen: "Kompetenzen gepflegt",
    felderFehlen: "Felder nicht hinterlegt — ",
    kompetenzHinweis: (mit: string, aktive: string) => `${mit} von ${aktive} nach Ein- und Austritt`,
    geschlecht: "Geschlecht",
    beschaeftigungsart: "Beschäftigungsart",
    abteilungen: "Abteilungen",
    maennlich: "männlich",
    weiblich: "weiblich",
    divers: "divers",
    unbekannt: "unbekannt",
    vollzeit: "Vollzeit",
    teilzeit: "Teilzeit",
    geringfuegig: "geringfügig",
    extern: "extern",
  },
  mitarbeiter: {
    titel: "Mitarbeiter",
    nurMitUeberstunden: "nur mit Überstunden",
    ausgeblendet: (anzahl: number) => `(${anzahl} ausgeblendet)`,
    person: "Person",
    abteilung: "Abteilung",
    istStunden: "Ist-Std.",
    ueberstunden: "Überstunden",
    quote: "ÜS %",
  },
  wochenbericht: {
    titel: "Wochenbericht",
    ladeFehler: (meldung: string) => `Wochenbericht konnte nicht geladen werden: ${meldung}`,
    kalenderwoche: "Kalenderwoche",
    kw: (woche: string, jahr: string) => `KW ${woche} / ${jahr}`,
    keineDaten: "Für diese Woche liegen keine Anwesenheiten vor.",
    saldo: "Saldo Mehrarbeit",
    saldoHinweis: (personen: string) => `Ist minus effektives Soll, über alle ${personen} Personen`,
    ueberSoll: "Über dem Soll",
    ueberSollHinweis: (gesamt: string) => `von ${gesamt} Personen mit Stempelung`,
    krankheit: "Krankheit",
    tage: "Tage",
    stunden: "Std.",
    krankheitHinweis: "über Kalendertage der Abwesenheit verteilt",
    ist: "Ist",
    soll: "Soll",
    saldoSpalte: "Saldo",
    fussnote:
      "Soll ist das effektive Wochensoll: Urlaub und Krankheit sind abgezogen, wer " +
      "unentschuldigt fehlt steht im Minus. In der laufenden Woche zählt das Soll nur bis zum " +
      "letzten gestempelten Tag.",
  },
  kennzahlenHub: {
    titel: "KPI-Dashboard",
    einleitung: "Kennzahlen je Fachbereich. Die Daten kommen aus den ERP-Exporten unter Uploads.",
    nochNicht: "noch nicht übernommen",
    bereiche: {
      vertrieb: "Umsatz, Auftragswert, Kundenanteil",
      personal: "Belegschaft, Fluktuation, Krankenstand — eigene Berechtigung",
      qualitaet: "Audit-Findings und Reklamationsquote",
      finanzen: "Material- und Personalkostenquote",
      einkauf: "Liefertermintreue der Lieferanten",
      produktion: "Verzug, überfällige Aufträge",
      bewertung: "Kommentare und Maßnahmen zu jeder Kennzahl",
    },
  },
  erklaerung: {
    frage: (titel: string) => `Wie wird „${titel}“ gerechnet?`,
    knopf: "Rechenweg",
    untertitel: "So wird gerechnet",
    ganzeSeite: "Ganze Hilfeseite",
  },
};

export type Texte = typeof de;
