import { TITEL, type Pfadtitel } from "@/lib/brotkrumen";

/**
 * Die deutschen Texte der Oberfläche. Diese Datei ist die Vorlage: ihr Typ
 * bestimmt, was jede andere Sprache liefern muss — eine fehlende Übersetzung
 * ist ein Übersetzungsfehler und kein leerer Kasten zur Laufzeit.
 *
 * Es stehen hier nur Texte der **Schale**: Kopfzeile, Pfad, Startbildschirm,
 * Anmeldung. Die Fachseiten kommen bereichsweise dazu. Ein halbes Wörterbuch
 * ist besser als ein ganzes, das zur Hälfte maschinell geraten ist.
 */
export const de = {
  kopf: {
    benutzermenue: "Benutzermenü",
    angemeldetAls: "Angemeldet als",
    uebersicht: "Zur Übersicht",
    hilfe: "Hilfe",
    einstellungen: "Einstellungen",
    abmelden: "Abmelden",
    sprache: "Sprache",
    erscheinungsbild: "Erscheinungsbild",
    hell: "Hell",
    dunkel: "Dunkel",
    system: "Wie das System",
    meldungenLeer: "App Feedback — nichts Neues",
    meldungen: (anzahl: number) => `App Feedback — ${anzahl} noch nicht angesehen`,
    massnahmenLeer: "Maßnahmen — keine offen",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Maßnahmen — ${offen} offen, davon ${ueberfaellig} überfällig`
        : `Maßnahmen — ${offen} offen`,
    navigation: "Navigation",
    einklappen: "Seitenleiste einklappen",
    ausklappen: "Seitenleiste ausklappen",
    navigationOeffnen: "Navigation öffnen",
    navigationSchliessen: "Navigation schließen",
    unterseitenZeigen: (name: string) => `${name}: Unterseiten zeigen`,
    unterseitenVerbergen: (name: string) => `${name}: Unterseiten verbergen`,
    werkzeuge: "Filter und Aktionen",
    werkzeugeEinklappen: "Filterleiste einklappen",
    werkzeugeAusklappen: "Filterleiste ausklappen",
    werkzeugeOeffnen: "Filter öffnen",
    werkzeugeSchliessen: "Filter schließen",
    kategorien: {
      navigation: "Navigation",
      ansicht: "Ansicht",
      filter: "Filter",
      zeitraum: "Zeitraum",
      aktionen: "Aktionen",
    },
    auchGeoeffnet: (namen: string) => `Auch geöffnet von ${namen}`,
    konflikt: "Inzwischen von jemand anderem geändert — der aktuelle Stand ist geladen.",
    geloeschtVonAnderen: "Inzwischen von jemand anderem gelöscht.",
  },
  pfad: {
    aria: "Pfad",
    start: "Start",
    seiten: TITEL as Pfadtitel,
  },
  start: {
    titel: "Apps",
    verweigert: (name: string) => `Für „${name}“ hast du keine Berechtigung.`,
    keineApp:
      "Deinem Konto ist noch keine App zugewiesen. Bitte an die Plattform-Verwaltung wenden.",
  },
  anmeldung: {
    benutzer: "Benutzer",
    lokalWechseln: "Lokal anmelden",
    adWechseln: "Mit AD-Konto anmelden",
    titel: "ACM-Plattform",
    aufforderung: "Mit deinem Konto anmelden.",
    email: "E-Mail",
    passwort: "Passwort",
    knopf: "Anmelden",
    laeuft: "Anmelden …",
  },
  allgemein: {
    laedt: "Wird geladen …",
    speichern: "Speichern",
    abbrechen: "Abbrechen",
    loeschen: "Löschen",
    stueck: "Stück",
    loeschenTitel: "Löschen bestätigen",
    loeschenFrage: (was: string) => `„${was}“ wird endgültig gelöscht.`,
    loeschenKnopf: (was: string) => `${was} löschen`,
  },
  zeitraum: {
    aria: "Zeitraum",
    monat: "Dieser Monat",
    quartal: "Dieses Quartal",
    jahr: "Dieses Jahr",
    alles: "Alles",
    frei: "Zeitraum wählen",
    von: "von",
    bis: "bis",
    vonAria: "Zeitraum von",
    bisAria: "Zeitraum bis",
    verdreht: "Das Ende liegt vor dem Anfang.",
  },
  vergleich: {
    zu: (was: string) => `zum ${was}`,
    quartal: (q: number) => `${q}. Quartal`,
    jahr: (j: number) => `Jahr ${j}`,
    keinWert: "Kein Vergleichswert: im Vergleichszeitraum fehlen Daten, oder der Wert war null.",
    gestiegen: "gestiegen",
    gesunken: "gesunken",
    unveraendert: "unverändert",
  },
  diagramm: {
    art: "Darstellung",
    balken: "Balken",
    flaeche: "Fläche",
  },
  tabelle: {
    suche: "Suchen",
    sucheAria: "Tabelle durchsuchen",
    sucheLeeren: "Suche leeren",
    keineTreffer: "Keine Treffer für diese Suche.",
    leer: "Keine Einträge.",
    bereich: (von: number, bis: number, gesamt: number) => `${von}–${bis} von ${gesamt}`,
    seite: (seite: number, seiten: number) => `Seite ${seite} von ${seiten}`,
    zurueck: "Vorherige Seite",
    weiter: "Nächste Seite",
    sortieren: (spalte: string) => `Nach „${spalte}“ sortieren`,
    seitengroesse: "Tabelleneinträge pro Seite",
    seitengroesseText: "Gilt für alle Tabellen der Plattform, für alle Personen.",
    gespeichert: "Seitengröße gespeichert.",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Datenstand ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Datenstand unvollständig — ${fehlend} ${anzahl === 1 ? "fehlt" : "fehlen"}`,
    heute: "heute",
    gestern: "gestern",
    vorTagen: (tage: number) => `vor ${tage} Tagen`,
    nie: "nie",
    arten: {
      umsatz: "Umsatz",
      auftraege: "Aufträge",
      angebote: "Angebote",
      interessenten: "Interessenten",
      kontakte: "Kontakte",
      liefertreue: "Liefertreue",
      lagerbewegungen: "Lagerbewegungen",
      materialpreise: "Materialpreise",
      lagerpreise: "Lagerpreise",
      auftragspositionen: "Auftragspositionen",
      lieferscheine: "Lieferscheine",
      pruefungen: "Prüfungen",
      acht_d: "8D-Berichte",
      wareneingaenge: "Wareneingänge",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `Kennzahlen konnten nicht geladen werden: ${meldung}`,
    keineDatenTitel: "Für diesen Zeitraum liegen keine Daten vor",
    keineDatenVor: "Lade die ERP-Exporte unter ",
    keineDatenNach: " hoch, oder wähle einen größeren Zeitraum.",
    keineWerte: "keine Werte im Zeitraum",
    laedt: "wird geladen …",
    jeTag: "je Tag",
    jeWoche: "je Woche",
    jeMonat: "je Monat",
  },
  vertrieb: {
    umsatz: "Umsatz",
    umsatzHinweis: "Rechnungen abzüglich Gutschriften",
    auftragswert: "Ø Auftragswert",
    ueberNull: "Aufträge über 0 €",
    auftraege: "Aufträge gesamt",
    verlauf: "Umsatzverlauf",
    verlaufHinweis: (takt: string) => `${takt}, Gutschriften abgezogen`,
    kundenanteil: "Kundenanteil am Umsatz",
    kunde: "Kunde",
    anteil: "Anteil",
    uebrige: "Übrige",
    jeErfasser: "Aufträge je Erfasser",
    erfasser: "Erfasser",
    anzahl: "Aufträge",
    summe: "Summe",
    einzelauftraege: "Einzelaufträge",
    einzelauftraegeHinweis: "Aufträge über 0 € im Zeitraum — dieselben, die „Aufträge gesamt“ zählt",
    auftragsNr: "Auftrags-Nr.",
    datum: "Datum",
    gesamt: "Gesamt",
    kundenanteilAuftraege: "Kundenanteil Aufträge",
    kundenanteilAuftraegeHinweis: "Auftragswerte je Kunde",
    kundenanteilRechnungen: "Kundenanteil Rechnungen",
    kundenanteilRechnungenHinweis: "Rechnungen abzüglich Gutschriften je Kunde",
    restkunden: (anzahl: number) => `Restkunden (${anzahl})`,
    rest: "Rest",
    weitereKunden: (anzahl: number) => `${anzahl} weitere zeigen`,
    nurTop3: "Nur Top 3 zeigen",
    umsatzIn: (zeitraum: string) => `Umsatz ${zeitraum}`,
  },
  aktivitaet: {
    titel: "Vertriebsaktivität",
    jeWoche: (von: string, bis: string) => `je Kalenderwoche, ${von} bis ${bis}`,
    ladeFehler: (meldung: string) => `Vertriebsaktivität konnte nicht geladen werden: ${meldung}`,
    leer: "Keine Kontakte, Angebote oder Interessenten in diesem Zeitraum.",
    kw: (woche: string) => `KW ${woche}`,
    ziel: (wert: string) => `Ziel ${wert} / Woche`,
    erstkontakte: "Erstkontakte",
    erstkontakteHinweis: "erledigte Kontakte vom Typ ERS",
    besuche: "Besuche",
    besucheHinweis: "vor Ort und online getrennt",
    besucheOrt: "vor Ort",
    besucheOnline: "online",
    interessenten: "Interessenten",
    interessentenHinweis: "neu erfasst, ohne Vertriebler-Zuordnung",
    angebote: "Angebote",
    angeboteHinweis: "Summe der geschriebenen Angebote",
    auftragseingang: "Auftragseingang",
    auftragseingangHinweis: "Stornos gegengerechnet",
  },
  einkauf: {
    keineDaten: "Für diesen Zeitraum liegen keine Lieferpositionen vor",
    ladeVor: "Lade den Liefertreue-Export unter ",
    ladeNach: " hoch.",
    otd: "OTD-Quote",
    otdHinweis: (ziel: string) => `Ziel ${ziel} · pünktlich: Verzug ≤ 0`,
    puenktlich: "Pünktliche Positionen",
    gesamt: "Positionen gesamt",
    verzugSchnitt: "Ø Verzug",
    verzugHinweis: "Positionen ohne Verzugswert ausgenommen",
    verlauf: "OTD-Quote im Zeitverlauf",
    verlaufHinweis: "Lücken sind Zeiträume ohne Lieferpositionen.",
    verlaufTooltip: (positionen: string) => `OTD (${positionen} Positionen)`,
    ziellinie: "Ziel",
    ladenhueter: "Bestellung auf Lager — Ladenhüter",
    kapital: (wert: string) => `Gebundenes Kapital: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Lagerartikel ohne Bewegung seit mindestens ${tage} Tagen, höchster Wert zuerst. ` +
      "Stichtag ist heute — der Zeitraum oben gilt hier nicht, weil ein Bestand kein Zeitraum ist.",
    artikel: "Artikel",
    bezeichnung: "Bezeichnung",
    bestand: "Bestand",
    liegtSeit: "Liegt seit",
    stueckpreis: "Stückpreis",
    wert: "Wert",
    positionen: "Lieferpositionen",
    positionenHinweis: "Größter Verzug zuerst, Positionen ohne Verzugswert ganz oben.",
    auftrag: "Auftrag",
    lieferant: "Lieferant",
    zieltermin: "Zieltermin",
    geliefert: "Geliefert",
    verzug: "Verzug",
    menge: "Menge",
  },
  produktion: {
    keineDaten: "Für diesen Zeitraum liegt kein Auftrag mit feststehendem Ausgang vor",
    ladeVor: "Lade die Auftragspositionen und die Lieferscheine unter ",
    ladeNach:
      " hoch. Beide werden gebraucht: die eine Datei trägt den Zieltermin, die andere das Ist-Datum.",
    quote: "Verzugsquote",
    quoteHinweis: (ziel: string) => `Höchstens ${ziel}`,
    inVerzug: "Aufträge in Verzug",
    davonOffen: (anzahl: string) => `davon ${anzahl} offen und überfällig`,
    gesamt: "Aufträge gesamt",
    gesamtHinweis: "ohne offene, noch nicht fällige",
    verzugSchnitt: "Ø Verzug",
    verzugHinweis: "pünktliche Aufträge zählen negativ",
    verlauf: "Verzugsquote im Zeitverlauf",
    verlaufHinweis: "Nach Zieltermin. Lücken sind Zeiträume ohne gezählte Aufträge.",
    verlaufTooltip: (auftraege: string) => `Verzug (${auftraege} Aufträge)`,
    ziellinie: "Ziel",
    ansicht: "Auftragsansicht",
    ansichtVerzug: "Aufträge in Verzug",
    ansichtUeberfaellig: "Überfällige offene Aufträge",
    hinweisVerzug: "Geliefert nach dem Zieltermin, größter Verzug zuerst.",
    hinweisUeberfaellig: "Ohne Lieferschein, Termin verstrichen — wächst täglich.",
    leerVerzug: "Kein Auftrag dieses Zeitraums wurde zu spät geliefert.",
    leerUeberfaellig: "Kein offener Auftrag dieses Zeitraums ist überfällig.",
    auftrag: "Auftrag",
    kunde: "Kunde",
    zieltermin: "Zieltermin",
    geliefert: "Geliefert",
    verzug: "Verzug",
    tageUeberfaellig: "Tage überfällig",
  },
  finanzen: {
    keineDatenVor:
      "Es braucht drei Dateien: die Lagerbewegungen für den Verbrauch, die Materialpreise " +
      "(Wareneingang) für die Preise und den Umsatz als Bezugsgröße. Alle drei liegen unter ",
    keineDatenNach: ".",
    materialquote: "Materialkostenquote",
    materialquoteHinweis: "Materialkosten / Umsatz",
    hoechstens: (ziel: string) => `Höchstens ${ziel}`,
    materialkosten: "Materialkosten",
    umsatz: "Umsatz",
    personalquote: "Personalkostenquote",
    brauchtZeitraum: "braucht einen Zeitraum",
    ohnePreis: "Artikel ohne Preis",
    ohnePreisHinweis: "verbraucht, aber nicht bewertet",
    jeAbteilung: "Personalkosten je Abteilung",
    abteilung: "Abteilung",
    personen: "Personen",
    kosten: "Kosten",
    anteil: "Anteil",
    verlauf: "Materialkostenquote im Zeitverlauf",
    verlaufHinweis: "Lücken sind Zeiträume ohne Umsatz — ohne Bezugsgröße gibt es keine Quote.",
    ziellinie: "Ziel",
    verbrauch: "Materialverbrauch je Artikel",
    verbrauchHinweis: "Höchste Kosten zuerst. Artikel ohne Preis stehen am Ende — sie gehen in die Quote nicht ein.",
    artikel: "Artikel",
    bezeichnung: "Bezeichnung",
    menge: "Verbrauch",
    stueckpreis: "Stückpreis",
    keinPreis: "kein Preis",
    ansicht: "Ansicht",
    ansichtMaterial: "Material",
    ansichtPersonal: "Personal",
    personalkosten: "Personalkosten",
    personalquoteHinweis: "Personalkosten / Umsatz",
    mitarbeiter: "Mitarbeiter",
    mitarbeiterHinweis: "mit Kosten im Zeitraum",
    personalVerlauf: "Personalkostenquote im Zeitverlauf",
    quoteBeiKosten: (kosten: string) => `Quote bei ${kosten} Kosten`,
  },
  qualitaet: {
    auditart: "Auditart:",
    reklamationsart: "Reklamationsart",
    keineArt: "Keine Auditart ausgewählt. Wähle mindestens eine, sonst gibt es nichts zu zählen.",
    keineDaten: "Für diesen Zeitraum liegen keine Audit-Befunde vor",
    ladeVor: "Lade den 8D-Export unter ",
    ladeNach: " hoch.",
    behoerde: "Behörde",
    extern: "Unterlieferant",
    intern: "Intern",
    kunde: "Kunde",
    level1: "Audit-Findings Level 1",
    level2: "Audit-Findings Level 2",
    ohneLevel: "Ohne erkennbares Level",
    ohneLevelHinweis: "zählt in keiner Kachel",
    hoechstens: (ziel: number) => `Höchstens ${ziel}`,
    auditVerlauf: "Audit-Findings im Zeitverlauf",
    auditVerlaufLevel: (level: number) => `Audit-Findings Level ${level} im Zeitverlauf`,
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `Anteil der Menge ohne Beanstandung. Bezugsgröße: ${bezug}.`,
    fehlerquote: (quote: string) => `Fehlerquote: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Fehlerquote: ${quote} · Ziel ${ziel}`,
    reklamiert: "Reklamierte Menge",
    bezugsmenge: "Bezugsmenge",
    bezugsmengeNull: "ohne sie gibt es keine Quote",
    mehrAlsBezogen:
      "Es ist mehr reklamiert als bezogen worden. Das kann die Rechnung nicht auflösen: " +
      "Zähler und Nenner kommen aus verschiedenen Dateien mit eigenen Datumsfeldern. Prüfe, " +
      "ob die Bezugsdatei für diesen Zeitraum vollständig hochgeladen ist.",
    reklKunde: "Kunde",
    reklIntern: "intern",
    reklLieferant: "Material-Lieferanten",
    reklWerkbank: "Werkbänke",
    bezugKunde: "gelieferte Menge",
    bezugIntern: "gelieferte Menge",
    bezugLieferant: "Wareneingang ohne Dienstleistung",
    bezugWerkbank: "Wareneingang der Warengruppen DIENST und SERVIC",
    mengeGesamt: "gemeldete Menge",
    mengeAkzeptiert: "akzeptierte Menge",
    onQualityBezug: (menge: string) => `On Quality (Bezug ${menge})`,
    ziellinie: "Ziel",
    geprueft: "Geprüfte Produkte",
    geprueftHinweis: "Menge je Prüfer-Tag. Jede Größe teilt durch die Tage, an denen jemand sie geprüft hat; Gesamt durch alle.",
    gross: "Große Produkte",
    klein: "Kleine Produkte",
    mindestens: (ziel: number) => `Mindestens ${ziel} je Tag und Prüfer`,
    buchungen: "Buchungen der Qualitätsprüfung",
    buchungenHinweis: "Eine abgewählte Buchung bleibt stehen, zählt aber in keiner Kachel.",
    zaehltMit: "Zählt mit",
    datum: "Datum",
    pruefer: "Prüfer",
    produkt: "Produkt",
    groesse: "Größe",
    menge: "Menge",
    ausschuss: "Ausschuss",
    mitzaehlen: (datum: string) => `Buchung vom ${datum} mitzählen`,
    klasseGross: "groß",
    klasseKlein: "klein",
    diagnose: "Befunde ohne erkennbares Level",
    diagnoseHinweis:
      "Das Level steht in der Quelldatei im Freitext. Steht dort weder „Major … Level 1“ noch " +
      "„Minor … Level 2“, zählt der Befund nirgends. Diese Liste zeigt, wo nachzubessern ist.",
    bericht: "Bericht",
    art: "Art",
    adresse: "Adresse",
    bezeichnung: "Bezeichnung",
    ansicht: "Ansicht",
    ansichtAudits: "Audits",
    ansichtReklamationen: "Reklamationen",
    ansichtPruefung: "Qualitätsprüfung",
    artikelart: "Artikelart",
    artikelFertig: "Fertigartikel",
    artikelHalbfertig: "Halbfertigartikel",
    artikelAlle: "Alle Artikel",
    gesamt: "Gesamt",
    pruefVerlauf: (klasse: string) => `${klasse} im Zeitverlauf`,
    personentage: (anzahl: string) => `${anzahl} Prüfer-Tage`,
    findings: "Findings-Übersicht",
    nr: "Nr.",
    kategorie: "Kategorie",
    level: "Level",
    aussteller: "Aussteller",
    quelle: "Quelle",
    status: "Status",
    reklListe: (art: string) => `Reklamationen · ${art}`,
    akzMenge: "Akz. Menge",
    artikel: "Artikel",
  },
  personal: {
    uebersicht: "Übersicht",
    keinAbgleich: "Noch kein Abgleich gelaufen. Er läuft nachts um 02:15 von selbst.",
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} Personen, ${anwesenheiten} Anwesenheiten, ${abwesenheiten} Abwesenheiten`,
    abgleichLaeuft: "läuft …",
    abgleichen: "Jetzt abgleichen",
    keineDaten: "Für diesen Zeitraum liegen keine Anwesenheiten vor",
    keineDatenHinweis:
      "Entweder ist der Personio-Abgleich noch nicht gelaufen, oder der Zeitraum liegt " +
      "vor dem Beginn der Aufzeichnung.",
    ueberstunden: "Überstunden-Quote",
    stundenVon: (teil: string, ganz: string) => `${teil} von ${ganz} Std.`,
    krankheit: "Krankheitsquote",
    krankheitsartenFehlen: "Krankheitsarten nicht hinterlegt",
    fluktuation: "Fluktuation",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} Austritte, Ø ${schnitt} Beschäftigte`,
    personen: "Erfasste Personen",
    personenHinweis: "mit Anwesenheit im Zeitraum",
    krankheitHinweisVor:
      "Die Krankheitsquote bleibt leer, solange nicht hinterlegt ist, welche " +
      "Personio-Abwesenheitsarten als Krankheit zählen. Einzutragen unter ",
    krankheitHinweisNach: ".",
    verlauf: "Verlauf",
    reiheUeberstunden: "Überstunden",
    reiheKrankheit: "Krankheit",
    umsatzJeKopf: "Umsatz / Produktions-MA",
    umsatzJeKopfHinweis: (auftraege: string, koepfe: string) => `${auftraege} Aufträge ÷ ${koepfe} Köpfe`,
    produktionFehlt: "Produktionsabteilungen nicht hinterlegt",
    abgleichStand: (datum: string, alter: string) => `Personio-Abgleich ${datum} (${alter})`,
    abgleichFehler: "mit Fehler",
    reiheUmsatzJeKopf: "Umsatz je Produktionskopf",
    ziel: (wert: string) => `Ziel ${wert}`,
  },
  melden: {
    knopf: "App Feedback melden",
    titel: "App Feedback melden",
    frage: "Was stimmt auf dieser Seite nicht? Ein Bild der Seite geht mit.",
    abbrechen: "Abbrechen",
    senden: "Senden",
    sendet: "Wird gesendet …",
    beispiel: "Zum Beispiel: Die Kachel zeigt einen leeren Wert, obwohl Daten da sind.",
    beschreibung: "Beschreibung",
    aufnahme: "Aufnahme der Seite",
    gehtMit: "Diese Aufnahme geht mit.",
    nimmtAuf: "Die Seite wird aufgenommen …",
    misslungen: "Die Seite ließ sich nicht aufnehmen — das Feedback geht ohne Bild.",
    dankeMitBild: "Danke — das Feedback ist angekommen.",
    dankeOhneBild: "Danke — das Feedback ist angekommen, ohne Bild der Seite.",
  },
  belegschaft: {
    titel: "Belegschaft",
    ladeFehler: (meldung: string) => `Belegschaft konnte nicht geladen werden: ${meldung}`,
    beschaeftigte: "Beschäftigte",
    beschaeftigteHinweis: "nach Personio-Status „aktiv“",
    stichtagHinweis: "Heutiger Stand — Personio führt keine Historie, deshalb kein Jahresvergleich.",
    neuImQuartal: "Neu im Quartal",
    bestand: "Bestand",
    kompetenzen: "Kompetenzen gepflegt",
    felderFehlen: "Felder nicht hinterlegt — ",
    kompetenzHinweis: (mit: string, aktive: string) => `${mit} von ${aktive} nach Ein- und Austritt`,
    geschlecht: "Geschlecht",
    beschaeftigungsart: "Beschäftigungsart",
    abteilungen: "Abteilungen",
    maennlich: "männlich",
    weiblich: "weiblich",
    divers: "divers",
    unbekannt: "unbekannt",
    vollzeit: "Vollzeit",
    teilzeit: "Teilzeit",
    geringfuegig: "geringfügig",
    extern: "extern",
  },
  mitarbeiter: {
    titel: "Mitarbeiter",
    person: "Person",
    abteilung: "Abteilung",
    istStunden: "Ist-Std.",
    ueberstunden: "Überstunden",
    quote: "ÜS %",
    auswahl: "Auswahl",
    mitUeberstunden: "Mit Überstunden",
    aktive: "Aktive",
    alle: "Alle",
    name: "Name",
    position: "Position",
    status: "Status",
    wochenstunden: "Std./Woche",
    leer: "Niemand in dieser Auswahl.",
    statusWert: { active: "aktiv", inactive: "inaktiv", onboarding: "Onboarding", leave: "abwesend" },
  },
  wochenbericht: {
    titel: "Wochenbericht",
    ladeFehler: (meldung: string) => `Wochenbericht konnte nicht geladen werden: ${meldung}`,
    kalenderwoche: "Kalenderwoche",
    kw: (woche: string, jahr: string) => `KW ${woche} / ${jahr}`,
    keineDaten: "Für diese Woche liegen keine Anwesenheiten vor.",
    saldo: "Saldo Mehrarbeit",
    saldoHinweis: (personen: string) => `Ist minus effektives Soll, über alle ${personen} Personen`,
    ueberSoll: "Über dem Soll",
    ueberSollHinweis: (gesamt: string) => `von ${gesamt} Personen mit Stempelung`,
    krankheit: "Krankheit",
    tage: "Tage",
    stunden: "Std.",
    krankheitHinweis: "über Kalendertage der Abwesenheit verteilt",
    ist: "Ist",
    soll: "Soll",
    saldoSpalte: "Saldo",
    fussnote:
      "Soll ist das effektive Wochensoll: Urlaub und Krankheit sind abgezogen, wer " +
      "unentschuldigt fehlt steht im Minus. In der laufenden Woche zählt das Soll nur bis zum " +
      "letzten gestempelten Tag.",
    diagrammUeberstunden: "Mehrarbeit je Person",
    diagrammKrankheit: "Krankheit je Person",
    spitzeHinweis: "die fünf höchsten Werte der Woche",
    keineWerte: "Keine Werte in dieser Woche",
    pdf: "Als PDF exportieren",
    pdfLaeuft: "PDF wird erstellt …",
    seite: (seite: number, gesamt: number) => `Seite ${seite} von ${gesamt}`,
    erstellt: (zeitpunkt: string) => `Erstellt am ${zeitpunkt}`,
    einheit: "Einheit der Krankheit",
  },
  titel: {
    /** Detailseiten und Seiten, deren Tab-Titel ausführlicher heißt als die
     *  Krume im Pfad. Alles andere holt seinen Titel von dort. */
    schulung: "Schulung",
    zeugnis: "Zeugnis",
    qualifikationsmatrix: "Qualifikationsmatrix",
    maschine: "Maschine",
    audit: "Audit",
    zeichnung: "Zeichnung",
    lieferung: "Lieferung",
    offeneSchulungen: "Offene Schulungen",
    schulungsmatrix: "Schulungsmatrix",
    atrLieferungen: "ATR-Lieferungen",
    atrTeilekatalog: "ATR-Teilekatalog",
    kpiBewertung: "KPI-Bewertung & Maßnahmen",
    anmelden: "Anmelden",
  },
  uploads: {
    dateiWaehlen: "Datei auswählen",
    verarbeitet: "wird verarbeitet …",
    uebersprungen: (datei: string) => `Übersprungene Zeilen aus „${datei}“`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `${gesamt} Zeile(n) übernommen, ${fehler} übersprungen. Die übrigen Zeilen sind gespeichert.`,
    zeile: "Zeile",
    spalte: "Spalte",
    grund: "Grund",
    zuletzt: "Zuletzt hochgeladen",
    datei: "Datei",
    art: "Art",
    zeilen: "Zeilen",
    uebersprungenSpalte: "Übersprungen",
    status: "Status",
    zeitpunkt: "Zeitpunkt",
    nochNichts: "Noch nichts hochgeladen.",
    keineZeile: (datei: string) => `„${datei}“ enthielt keine gültige Zeile.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `„${datei}“ übernommen, ${fehler} Zeile(n) übersprungen.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `„${datei}“ übernommen: ${neu} neu, ${aktualisiert} aktualisiert.`,
    fehlgeschlagenMeldung: (meldung: string) => `Upload fehlgeschlagen: ${meldung}`,
    vollstaendig: "vollständig",
    teilweise: "teilweise",
    fehlgeschlagen: "fehlgeschlagen",
    arten: {
      umsatz: "Umsatz (Rechnungen und Gutschriften)",
      umsatzText: "Speist die Kachel Umsatz und den Umsatzverlauf. Gutschriften stehen negativ in der Datei.",
      auftraege: "Auftragseingang",
      auftraegeText: "Speist Ø Auftragswert, Aufträge gesamt und die Auswertung je Erfasser.",
      auftragspositionen: "Auftragspositionen",
      auftragspositionenText:
        "Trägt den Zieltermin je Position. Zusammen mit den Lieferscheinen ergibt sich daraus der Verzug.",
      lieferscheine: "Lieferscheine",
      lieferscheineText: "Trägt das Ist-Lieferdatum. Excel-Datei, eine Zeile je Lieferscheinposition.",
      wareneingaenge: "Wareneingänge",
      wareneingaengeText:
        "Bezugsgröße der Fehlerquote auf der Einkaufsseite. Die Warengruppe trennt Material-Lieferanten von Werkbänken.",
      acht_d: "8D-Berichte",
      acht_dText:
        "Audit-Befunde und Reklamationen in einer Datei. Das Level eines Befunds steht im Freitext und wird beim Einlesen abgeleitet.",
      lagerbewegungen: "Lagerbewegungen",
      lagerbewegungenText:
        "Verbrauch je Artikel für die Materialkostenquote. Ersetzt alle Zeilen im Datumsbereich der Datei.",
      materialpreise: "Materialpreise (Wareneingang)",
      materialpreiseText:
        "Preise für die Materialkostenquote: je Artikel gilt der jüngste Wareneingang. Aktualisiert gleiche Positionen, ergänzt neue, löscht nichts.",
      lagerpreise: "Artikelpreise Lager",
      lagerpreiseText:
        "Stammdaten für die Lagerbewertung. Ersetzt die ganze Preisliste, nicht nur die enthaltenen Artikel.",
      pruefungen: "Qualitätsprüfung",
      pruefungenText:
        "Buchungen der Prüfung. Ersetzt alle Zeilen im Datumsbereich der Datei — von Hand abgewählte Buchungen in diesem Bereich zählen danach wieder mit.",
      liefertreue: "Liefertermintreue (Einkauf)",
      liefertreueText:
        "Speist die OTD-Quote im Einkauf. Eine Zeile je Lieferposition; das Ist-Lieferdatum bestimmt den Zeitraum.",
      kontakte: "Kontakte (Vertrieb)",
      kontakteText:
        "Erstkontakte und Besuche je Woche. Ersetzt alle Zeilen im Datumsbereich der Datei — ein zweiter Upload desselben Zeitraums verdoppelt nichts.",
      angebote: "Angebote",
      angeboteText:
        "Angebotsvolumen je Woche und Vertriebler. Angebote ohne Erfasser erscheinen in keinem Balken.",
      interessenten: "Interessenten",
      interessentenText:
        "Stammdaten der Interessenten. Ein erneut gespeicherter Interessent wandert mit seinem neuen Datum in eine andere Woche.",
    },
  },
  organigramm: {
    suchfeld: "Person, Position oder Abteilung",
    suchePlatzhalter: "Name, Position, Abteilung",
    standort: "Standort",
    alleStandorte: "Alle Standorte",
    personen: (anzahl: number) => `${anzahl} Personen`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} ohne Vorgesetzten`,
    niemand: "Niemand gefunden",
    niemandText: "Andere Suche, anderer Standort — oder der Personio-Abgleich lief noch nicht.",
    aufklappen: (name: string) => `${name} aufklappen`,
    zuklappen: (name: string) => `${name} zuklappen`,
    direkt: (anzahl: number) => `${anzahl} direkt`,
    treffer: (anzahl: number) => ` · ${anzahl} Treffer`,
    kontext: "Umrandet: Treffer. Blass: Vorgesetzte als Kontext.",
  },
  offeneSchulungen: {
    einleitung: "Wer was noch braucht. Nur aktive Schulungen; stillgelegte tauchen hier nicht mehr auf.",
    zumKatalog: "Zum Katalog",
    allesOffene: "Alles Offene",
    nieAbsolviert: "Nie absolviert",
    ueberfaellig: "Überfällig",
    wirdFaellig: "Wird fällig",
    suchen: "Person oder Schulung suchen",
    suchenAria: "Suchen",
    nichtsOffen: "Nichts offen",
    nichtsOffenText: "Alle aktiven Schulungen sind im Turnus — oder es ist noch nichts eingelesen.",
    eintraege: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "Eintrag" : "Einträge"}.`,
    person: "Person",
    schulung: "Schulung",
    bereich: "Bereich",
    zuletzt: "Zuletzt",
    faellig: "Fällig",
    stand: "Stand",
    nie: "nie absolviert",
    imTurnus: "im Turnus",
  },
  schulungsmatrix: {
    legende: "Legende",
    nichtZugewiesenKurz: "nicht zugewiesen",
    einleitung:
      "Alle Personen gegen alle Schulungen — die Übersicht für den Aushang und fürs Audit. " +
      "Wer noch gar keine Teilnahme hat, steht mit leerer Zeile darin; genau das ist die Lücke, " +
      "die man sucht.",
    wasOffenIst: "Was offen ist",
    katalog: "Katalog",
    suchfeld: "Person oder Abteilung",
    suchePlatzhalter: "Name, Abteilung, Personalnummer",
    bereich: "Bereich",
    alleBereiche: "Alle Bereiche",
    nurLuecken: "Nur Personen mit Lücken",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} von ${gesamt} Personen · ${schulungen} Schulungen`,
    niemand: "Keine Person passt",
    niemandText: "Andere Suche oder anderer Bereich — oder es ist wirklich niemand offen.",
    person: "Person",
    nichtZugewiesen: (person: string, schulung: string) =>
      `${person} · ${schulung}: nicht zugewiesen`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (fällig ${datum})`,
    offen: "offen",
    personio: "Personio",
    externGepflegt: "extern gepflegt",
    ohneTreffer: "ohne Personio-Treffer",
  },
  schulungen: {
    dokumentenlauf: "Dokumentenlauf",
    bereich: "Bereich",
    neueSchulung: "Neue Schulung",
    beispiel: "z. B. Brandschutzunterweisung",
    anlegen: "Anlegen",
    wirdGelesen: "Wird gelesen …",
    uebersichtEinlesen: "Übersicht einlesen",
    einlesenAria: "Schulungsübersicht einlesen",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} Schulungen (${neu} neu), ${teilnahmen} Teilnahmen, davon ${zugeordnet} einer Person in Personio zugeordnet.`,
    ohneTreffer: "Ohne Personio-Treffer: ",
    ohneTrefferNach: ". Diese Zeilen kommen mit Personalnummer und Namen trotzdem mit.",
    wirdUebernommen: "Wird übernommen …",
    uebernehmen: "Übernehmen",
    abbrechen: "Abbrechen",
    keineSchulung: "Noch keine Schulung",
    keineSchulungText: "Leg eine an oder lies die Schulungsübersicht ein.",
    schulung: "Schulung",
    turnus: "Turnus",
    frist: "Frist (Tage)",
    verantwortlich: "Verantwortlich",
    offen: "Offen",
    aktiv: "Aktiv",
    nichtBerechenbar: "(nicht berechenbar)",
    zahlGroesserNull: "Bitte eine Zahl größer als 0.",
    nieKurz: (anzahl: number) => `${anzahl} nie`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} überfällig`,
    baldKurz: (anzahl: number) => `${anzahl} bald`,
    aktivSchalter: (name: string) => `${name} aktiv`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} heißt: für diese Person steht kein Termin in der Historie. ${bald} heißt: innerhalb der nächsten zwei Monate. Stand vom ${datum}.`,
  },
  schulungenReg: {
    tabBearbeiten: "Schulungen bearbeiten",
    tabZuweisen: "Schulung zuweisen",
    tabStand: "Stand der Mitarbeiter",
    anforderungsmatrix: "Anforderungsmatrix",
    ebene: "Ebene",
    matrixLeer: "Noch keine Daten für die Matrix.",
    einzelTitel: "Einzelne Schulung zuweisen",
    einzelHinweis: "Ergänzt die Anforderungsmatrix, die abteilungsweit wirkt — für einzelne Personen.",
    mitarbeiterWaehlen: "Mitarbeiter wählen",
    schulungWaehlen: "Schulung wählen",
    zuweisenAktion: "Zuweisen",
    zugewiesen: "Schulung zugewiesen.",
    schonZugewiesen: "Diese Schulung ist der Person bereits zugewiesen.",
    sammelTitel: "Als durchgeführt eintragen (Sammel)",
    sammelHinweis: "Eine Schulung, ein Datum, mehrere Teilnehmer. Abgeschlossene Teilnahmen behalten ihr Datum, ein jüngeres rückt nach.",
    durchgefuehrtAm: "Durchgeführt am",
    teilnehmerSuche: "Teilnehmer suchen",
    standort: "Standort",
    offeneTitel: "Offene Schulungen",
    abteilung: "Abteilung",
    frist: "Frist",
    mitarbeiterTitel: "Mitarbeiterübersicht",
    anzahl: "Anzahl",
    naechste: "Nächste Fälligkeit",
    matrixTitel: "Gesamtmatrix",
    abteilungenTitel: "Abteilungen & Vorgesetzte",
    vorgesetzter: "Verantwortlicher Vorgesetzter",
    abteilungenHinweis: "Der Vorgesetzte wird aus Personio abgeleitet; fehlt er, bleibt die Spalte leer.",
    sammelAktion: (anzahl: number) => `${anzahl} als durchgeführt eintragen`,
    sammelErfolg: (eingetragen: number, unveraendert: number) =>
      `${eingetragen} eingetragen${unveraendert ? `, ${unveraendert} unverändert` : ""}.`,
    seit: (tage: number) => `seit ${tage} Tg.`,
    in: (tage: number) => `in ${tage} Tg.`,
  },
  schulung: {
    gibtEsNicht: "Diese Schulung gibt es nicht",
    gibtEsNichtText: "Vermutlich wurde sie entfernt.",
    ohneTurnus: "ohne Turnus",
    keineFaelligkeit: " — daraus lässt sich keine Fälligkeit rechnen",
    zumKatalog: "Zum Katalog",
    stammdaten: "Stammdaten",
    turnus: "Turnus",
    turnusBeispiel: "z. B. jährlich",
    turnusHinweis: "Der Text; die Monatszahl kommt aus dem Einlesen.",
    turnusMonate: "Turnus in Monaten",
    monateHinweis: "Leer heißt: keine Fälligkeit berechenbar.",
    verantwortlich: "Verantwortlich",
    beschreibung: "Beschreibung",
    fuerWen: "Für wen ist sie Pflicht?",
    kuerzel: "Abteilungskürzel",
    kuerzelHinweis: "Das feine Schema aus der Excel (NÄH, CUT, WVK …).",
    personioAbteilung: "Personio-Abteilung",
    personioHinweis: "Die grobe Abteilung, wie Personio sie führt.",
    entfernen: (was: string) => `${was} entfernen`,
    keine: "keine",
    ergaenzen: (was: string) => `${was} ergänzen`,
    hinzufuegen: "Hinzufügen",
    teilnahmen: "Teilnahmen",
    nochNiemand: "Noch niemand — lies die Schulungsübersicht ein oder trag jemanden ein.",
    person: "Person",
    abteilungKurz: "Abt.",
    erstschulung: "Erstschulung",
    zuletzt: "Zuletzt",
    faellig: "Fällig",
    stand: "Stand",
    keinTreffer: "Kein Treffer in Personio — die Zeile bleibt trotzdem erhalten",
    nichtInPersonio: "nicht in Personio",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "diese Teilnahme",
    personErgaenzen: "Person ergänzen",
    nameForm: "Nachname, Vorname",
  },
  kompetenzen: {
    zumDashboard: "Zum HR-Dashboard",
    bereich: "Bereich",
    wirdGelesen: "Wird gelesen …",
    einlesen: "Bereichsdatei einlesen",
    vorschauKopf: (datei: string, bereich: string) => `${datei} — so sähe ${bereich} danach aus:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} Qualifikationen, ${personen} Personen, ${bewertungen} Bewertungen.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `${zugeordnet} von ${personen} Personen in Personio gefunden`,
    platzhalter: (anzahl: number) =>
      `, ${anzahl} ${anzahl === 1 ? "Platzhalterspalte" : "Platzhalterspalten"}`,
    ohneZuordnung: (namen: string) => ` Ohne Zuordnung: ${namen}.`,
    ersetztWarnung:
      "Die betroffenen Blätter werden vollständig ersetzt — hier gepflegte Änderungen gehen " +
      "dabei verloren.",
    wirdUebernommen: "Wird übernommen …",
    uebernehmen: "Übernehmen",
    abbrechen: "Abbrechen",
    keineMatrix: "Noch keine Matrix",
    keineMatrixText: "Lies eine Bereichsdatei ein — die Blätter darin werden je eine Matrix.",
    blatt: "Blatt",
    titelSpalte: "Titel",
    stand: "Stand",
    eingelesen: "Eingelesen",
    produktion: "Produktion",
    verwaltung: "Verwaltung",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    bausteineTitel: "Textbausteine",
    bausteineHinweis: "Je Bewertungsbereich und Note eine Formulierung. Nur Geändertes wird gespeichert; [NAME] und die Pronomen werden beim Erzeugen ersetzt.",
    speichern: "Speichern",
    gespeichert: "Gespeichert.",
    note1: "sehr gut",
    note2: "gut",
    note3: "befriedigend",
    note4: "ausreichend",
    person: "Person",
    waehlen: "— wählen —",
    art: "Art",
    anlegen: "Anlegen",
    keines: "Noch kein Zeugnis",
    keinesText: "Wähl eine Person und die Zeugnisart — die Stammdaten kommen dann von selbst.",
    zeitraum: "Zeitraum",
    note: "Note",
    stand: "Stand",
    angelegt: "Angelegt",
    fertig: "fertig",
    entwurf: "Entwurf",
    qualifiziert: "Qualifiziertes Zeugnis",
    einfach: "Einfaches Zeugnis",
    zwischenzeugnis: "Zwischenzeugnis",
    ausbildungszeugnis: "Ausbildungszeugnis",
    praktikumszeugnis: "Praktikumszeugnis",
  },
  einarbeitung: {
    einleitung:
      "Was eine neue Person lernen muss und wer es ihr zeigt. Der Bogen entsteht aus den " +
      "Inhalten, die für ihre Abteilung hinterlegt sind.",
    bogenErzeugen: "Bogen erzeugen",
    person: "Person",
    waehlen: "— wählen —",
    wirdGebaut: "Wird gebaut …",
    einarbeitungsplan: "Einarbeitungsplan",
    keineInhalte: "Noch keine Inhalte hinterlegt — der Bogen bliebe leer.",
    abteilungVon: (abteilung: string) => `Abteilung ${abteilung}`,
    neuerInhalt: "Neuer Inhalt",
    beispiel: "z. B. Sicherheitsunterweisung an der Fräse",
    anlegen: "Anlegen",
    keinInhalt: "Noch kein Inhalt",
    keinInhaltText:
      "Leg fest, was eine neue Person lernen muss — und für welche Abteilungen das gilt.",
    inhalt: "Inhalt",
    ansprechpartner: "Ansprechpartner",
    bereich: "Bereich",
    fuerAbteilungen: "Für welche Abteilungen",
    abteilung: "Abteilung",
    bereichLeer: "Leer heißt: die Abteilung aus der Matrix einsetzen",
    entfernen: (was: string) => `${was} entfernen`,
    abteilungHinzu: "+ Abteilung",
    abteilungFuer: (inhalt: string) => `Abteilung für ${inhalt}`,
  },
  matrix: {
    bearbeiten: "Bearbeiten",
    bearbeitenFertig: "Fertig",
    ohneKategorie: "Ohne Kategorie",
    gibtEsNicht: "Diese Matrix gibt es nicht",
    gibtEsNichtText: "Vermutlich wurde sie ersetzt.",
    blattStand: (blatt: string) => `Blatt ${blatt}`,
    stand: (datum: string) => ` · Stand ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} Qualifikationen, ${personen} Personen`,
    zurUebersicht: "Zur Übersicht",
    qualifikation: "Qualifikation",
    keineZeilen: "Diese Matrix hat noch keine Zeilen.",
    stufenBedeuten: "Was die Stufen bedeuten",
    erfuellungsgradHinweis:
      "Die zweite Zahl ist der Erfüllungsgrad in Prozent. Eine Zelle mit Anforderung und " +
      "weniger als 100 % ist eine Lücke und steht in Warnfarbe.",
    ergaenzen: "Ergänzen",
    neueQualifikation: "Neue Qualifikation",
    beispiel: "z. B. Drehmaschine",
    kategorie: "Kategorie",
    ohne: "ohne",
    zeile: "Zeile",
    neuePerson: "Neue Person",
    namensform: "Vorname Nachname",
    spalte: "Spalte",
    anforderungslevel: "Anforderungslevel",
    erfuellungsgrad: "Erfüllungsgrad in Prozent",
    stufe0: "nicht erforderlich",
    stufe1: "Grundkenntnisse",
    stufe2: "kann unter Anleitung arbeiten",
    stufe3: "arbeitet selbstständig",
    stufe4: "kann anleiten und schulen",
  },
  zeugnis: {
    gibtEsNicht: "Dieses Zeugnis gibt es nicht",
    gibtEsNichtText: "Vermutlich wurde es gelöscht.",
    durchschnitt: (wert: string) => ` · Durchschnitt ${wert}`,
    zurUebersicht: "Zur Übersicht",
    zeugnisVon: (name: string) => `Zeugnis ${name}`,
    stammdaten: "Stammdaten",
    stammdatenHinweis:
      "Abgeschrieben beim Anlegen. Änderungen hier gelten nur für dieses Zeugnis — Personio " +
      "bleibt unberührt.",
    name: "Name",
    personalnummer: "Personalnummer",
    abteilung: "Abteilung",
    taetigkeit: "Tätigkeit",
    eintritt: "Eintritt",
    austritt: "Austritt",
    geburtsdatum: "Geburtsdatum",
    ausstellungsdatum: "Ausstellungsdatum",
    ohneNamen: "Ohne Namen geht es nicht.",
    anrede: "Anrede",
    frau: "Frau",
    herr: "Herr",
    anredeHinweis: "Steuert Anrede und Pronomen im Text.",
    art: "Art",
    anlass: "Anlass",
    anlassBeispiel: "z. B. eigener Wunsch",
    fuehrungskraft: "Führungskraft",
    fuehrungskraftHinweis: "Führungskraft — blendet die Dimension „Führung“ ein",
    bewertung: "Bewertung",
    bewertungHinweis:
      "Schulnoten von 1 bis 4. Aus dem Durchschnitt folgt die Zufriedenheitsformel — nicht " +
      "umgekehrt.",
    fachwissen: "Fachwissen",
    auffassungsgabe: "Auffassungsgabe",
    arbeitsweise: "Arbeitsweise",
    belastbarkeit: "Belastbarkeit",
    arbeitserfolg: "Arbeitserfolg",
    sozialverhalten: "Sozialverhalten",
    fuehrung: "Führung",
    aufgaben: "Aufgaben (Stichpunkte)",
    aufgabenHinweis: "Eine Aufgabe je Zeile — daraus wird die Aufzählung im Zeugnis.",
    kompetenzen: "Besondere Kompetenzen",
    kompetenzenHinweis: "Fließt in die Leistungsbeurteilung ein.",
    erfolge: "Besondere Erfolge",
    erfolgeHinweis: "Projekte, Auszeichnungen, messbare Ergebnisse.",
    text: "Text",
    baut: "Baut …",
    ausBausteinen: "Aus Bausteinen",
    formuliert: "Formuliert …",
    mitKi: "Mit KI",
    textHinweis:
      "Der Baukasten schreibt ohne Netz und ohne KI. Die KI formuliert freier — an sie gehen nur " +
      "Anrede, Rolle, Abteilung, Dauer, Noten und die Freitexte oben. Name, Geburtsdatum und " +
      "Personalnummer verlassen den Server nicht.",
    nochKeinText: "Noch kein Text. Vergib die Noten und lass ihn bilden.",
    fertigSchalter: "Zeugnis fertig",
    fertigHinweis: "Fertig — nicht mehr in Arbeit",
    unterschriftenFehler: (meldung: string) =>
      `Die Unterschriften konnten nicht ermittelt werden (${meldung}).`,
    darunterSteht: "Darunter steht",
    fachlich: "Fachlich",
    personalwesen: "Personalwesen",
    niemandHinterlegt: "— niemand hinterlegt —",
    unterschriftFehlt:
      "Eine Unterschrift fehlt. Hinterlegen unter Einstellungen → Zeugnisse, oder in Personio " +
      "den Vorgesetzten pflegen.",
    ausPersonio: "aus Personio",
    ausEinstellungen: "aus den Einstellungen",
    nichtHinterlegt: "nicht hinterlegt",
    einleitung: "Einleitung",
    taetigkeitsbeschreibung: "Tätigkeitsbeschreibung",
    leistungsbeurteilung: "Leistungsbeurteilung",
    schlussformel: "Schlussformel",
    hinweisDeutsch: "Das Zeugnis selbst wird auf Deutsch geschrieben.",
  },
  dokumentenlauf: {
    erstelltAm: "Erstellt",
    uebergebenAm: "Übergeben",
    zurueckAm: "Zurück",
    geprueftAm: "Geprüft",
    aktionen: "Aktionen",
    einleitung:
      "Blätter mit QR-Code: erzeugen, aushändigen, ausgefüllt zurücknehmen, prüfen. Der QR " +
      "ordnet den Scan wieder zu — unabhängig davon, wie die Datei heißt.",
    formblatt: "Formblatt",
    fuerWen: "Für wen",
    personWaehlen: "— Person wählen —",
    erzeugt: "Erzeugt …",
    blattErzeugen: "Blatt erzeugen",
    standFilter: "Stand:",
    alle: "Alle",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} von ${gesamt}`,
    keinVorgang: "Kein Vorgang",
    keinVorgangText:
      "Oben ein Blatt erzeugen — es bekommt einen QR-Code und wird von da an verfolgt.",
    person: "Person",
    kennung: "Kennung",
    stand: "Stand",
    vollstaendigSpalte: "Vollständig",
    blatt: "Blatt",
    scan: "Scan",
    prueft: "Prüft …",
    scanFuer: (name: string) => `Scan für ${name} hochladen`,
    zu: "zu",
    details: "Details",
    nochNichtGeprueft: "— noch nicht geprüft",
    vollstaendig: "vollständig",
    unvollstaendig: "unvollständig",
    umkehren: "Urteil umkehren — die Messung sieht nur, ob Tinte im Feld ist",
    pruefung: "Prüfung",
    qrGelesen: "— QR gelesen",
    keinQr: "— kein QR gefunden, Felder nicht zuzuordnen",
    nachweise: "Nachweise",
    keineNachweise: "Noch keine hinterlegt.",
    welcheZeile: "Zu welcher Zeile? (freiwillig)",
    laedt: "Lädt …",
    nachweis: "Nachweis",
    nachweisHoch: "Nachweis hochladen",
    erstellt: "erstellt",
    uebergeben: "übergeben",
    zurueck: "zurück",
    geprueft: "geprüft",
    einarbeitungsplan: "Einarbeitungsplan",
    schulungsnachweis: "Schulungsnachweis",
  },
  onboarding: {
    aktive: "Aktive",
    personenwahl: "Welche Personen",
    eintritteTitel: "Eintritte",
    inhalteTitel: "Einarbeitungsinhalte",
    matrixTitel: "Einarbeitungsmatrix",
    matrixHinweis: "Welcher Inhalt für welche Abteilung nötig ist. Ein Häkchen gilt sofort.",
    matrixLeer: "Noch keine Inhalte oder Abteilungen.",
    vorgaengeTitel: "Einarbeitungs- & Schulungsvorgänge",
    matrixZelle: (inhalt: string, abteilung: string) => `${inhalt} – ${abteilung}`,
    nichtsGefehlt: "Es fehlte nichts.",
    angelegt: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "Schulung" : "Schulungen"} angelegt.`,
    neu90: "Neu (letzte 90 Tage)",
    alle: "Alle",
    personen: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "Person" : "Personen"}`,
    keineEintritte: "Keine Eintritte",
    keineEintritteText: "Sobald jemand mit Eintrittsdatum aus Personio kommt, steht er hier.",
    person: "Person",
    abteilung: "Abteilung",
    position: "Position",
    eintritt: "Eintritt",
    uebergabe: "Übergabe",
    nichtInPersonio: "nicht in Personio",
    hierGesetzt: "Hier gesetzt — übersteuert Personio",
    ausPersonio: "Aus Personio",
    vermerken: "Vermerken",
    paketTitel: "Einarbeitungsplan und Schulungsübersicht als ein PDF",
    paket: "Paket",
    uebersichtTitel: "Nur die Schulungsübersicht (Formblatt 71)",
    uebersicht: "Übersicht",
    planZu: "Plan zu",
    plan: "Plan",
    schulungsplan: "Schulungsplan",
    fehlendeAnlegen: "Fehlende anlegen",
    wirdGerechnet: "wird gerechnet …",
    bruecke: "Position → Abteilungskürzel",
    brueckeHinweis:
      "Die Brücke zwischen Personio und der feinen Ebene der Anforderungsmatrix. Ohne Eintrag " +
      "greift die feine Ebene für diese Position nicht — der Plan sagt das dann ausdrücklich.",
    kuerzel: "Kürzel",
    positionBeispiel: "z. B. CNC Fräser",
    kuerzelBeispiel: "CNC",
    zuordnen: "Zuordnen",
    ohnePersonio: "Person ohne Personio",
    ohnePersonioHinweis:
      "Für Eintritte, die noch nicht im Abgleich stehen — oder gar nicht dorthin gehören.",
    name: "Name",
    anlegen: "Anlegen",
    kuerzelFehlt: (position: string) =>
      `Für die Position ${position}ist kein Abteilungskürzel hinterlegt. Die feine Ebene der ` +
      "Anforderungsmatrix greift für diese Person deshalb nicht — es fehlen möglicherweise " +
      "Pflichtschulungen.",
    matrixVerlangtNichts: "Die Anforderungsmatrix verlangt für diese Abteilung nichts.",
    schulung: "Schulung",
    bereich: "Bereich",
    turnus: "Turnus",
    pflichtUeber: "Pflicht über",
    stand: "Stand",
    ueberAbteilung: "Abteilung",
    ueberKuerzel: "Kürzel",
    vorhanden: "vorhanden",
    fehlt: "fehlt",
  },
  audit: {
    zuKennzahlen: "Zu den Kennzahlen",
    nummer: "Nummer",
    nummerBeispiel: "A-2026-01",
    titel: "Titel",
    titelBeispiel: "EN 9100 Systemaudit",
    art: "Art",
    intern: "intern",
    extern: "extern",
    phasenvorlage: "Phasenvorlage",
    ohne: "ohne",
    anlegen: "Anlegen",
    alle: "Alle",
    neuesAudit: "Neues Audit",
    geltungsbereich: "Geltungsbereich",
    kategorie: "Kategorie",
    leadAuditor: "Lead-Auditor",
    beginnGeplant: "Beginn (geplant)",
    endeGeplant: "Ende (geplant)",
    ohneVorlage: "Ohne Vorlage (Phasen später ergänzen)",
    vorlageHinweis:
      "Die Phasen der Vorlage werden beim Anlegen kopiert. Änderst du die Vorlage später, bleibt " +
      "dieses Audit unverändert.",
    kategoriePflicht: "Mindestens eine Kategorie wählen.",
    zeitraumFehler: "Das Ende liegt vor dem Beginn.",
    angelegt: "Audit angelegt.",
    nummerVergeben: "Diese Auditnummer gibt es schon.",
    keinTreffer: "Kein Audit passt zu diesem Filter.",
    keinAudit: "Noch kein Audit",
    keinAuditText: "Leg eines an — mit einer Phasenvorlage bringt es seine Checkliste gleich mit.",
    laufen: (laufend: number, gesamt: number) => `${laufend} von ${gesamt} laufen noch.`,
    status: "Status",
    fortschritt: "Fortschritt",
    naechsterTermin: "Nächster Termin",
    ueberfaellig: (anzahl: number) => `${anzahl} überfällig`,
    geplant: "Geplant",
    inVorbereitung: "In Vorbereitung",
    inDurchfuehrung: "In Durchführung",
    berichtet: "Berichtet",
    massnahmenOffen: "Maßnahmen offen",
    abgeschlossen: "Abgeschlossen",
    verschoben: "Verschoben",
    abgesagt: "Abgesagt",
    phaseOffen: "Offen",
    phaseInArbeit: "In Arbeit",
    phaseErledigt: "Erledigt",
    phaseNichtZutreffend: "Nicht zutreffend",
    system: "System",
    prozess: "Prozess",
    produkt: "Produkt",
    lieferant: "Lieferant",
  },
  wartung: {
    zuKennzahlen: "Zu den Kennzahlen",
    neueMaschine: "Neue Maschine",
    beispiel: "z. B. Fräse 3",
    anlegen: "Anlegen",
    keineMaschine: "Noch keine Maschine",
    keineMaschineText: "Leg eine Maschine an und hinterlege ihre Wartungsaufgaben.",
    maschine: "Maschine",
    inventarnummer: "Inventar-Nr.",
    standort: "Standort",
    verantwortlich: "Verantwortlich",
    status: "Status",
    aktiv: "aktiv",
    stillgelegt: "stillgelegt",
    angelegt: "Maschine angelegt.",
  },
  sensoren: {
    misst: "Misst …",
    jetztMessen: "Jetzt messen",
    keinGeraet: "Kein Gerät eingerichtet",
    keinGeraetText: "Sensoren werden in den Einstellungen angelegt — Rechner, Kennung und Community.",
    verlauf: "Verlauf",
    stunden: (n: number) => `${n} h`,
    tage: (n: number) => `${n} Tage`,
    temperatur: "Temperatur",
    luftfeuchte: "Luftfeuchtigkeit",
    zuletzt: (zeit: string) => `Zuletzt ${zeit}`,
    keinMesswert: "Noch kein Messwert.",
    nichtsGemessen: "In diesem Zeitraum wurde nichts gemessen.",
    frisch: "aktuell",
    verzoegert: "verzögert",
    offline: "offline",
    unbekannt: "noch nichts gemessen",
    temperaturverlauf: "Temperatur (°C)",
    feuchteverlauf: "Luftfeuchtigkeit (%)",
    mittelFuenfMinuten: "Mittelwerte je 5 Minuten",
    mittelStunde: "Mittelwerte je Stunde",
    minMax: (fenster: string) => `Min/Max ${fenster}`,
    ausserhalbGrenzen: "Außerhalb der Grenzen",
    untergrenze: "Min",
    obergrenze: "Max",
    ladeFehler: "Messwerte konnten nicht geladen werden.",
  },
  hilfe: {
    nurDeutsch: "",
    suchen: "In der Hilfe suchen",
    nichtsGefunden:
      "Nichts gefunden. Steht etwas nicht in der Hilfe, sag es über „App Feedback melden“ unten rechts.",
    alleThemen: "← Alle Themen",
    navigation: "Hilfethemen",
  },
  meldungen: {
    stand: (offen: number) => `${offen} offen`,
    neuSeit: (anzahl: number) => ` · ${anzahl} noch nicht angesehen`,
    nichtsGemeldet: "Noch kein App Feedback",
    nichtsGemeldetText:
      "Über „App Feedback melden“ unten rechts kann jede angemeldete Person melden, was auf " +
      "einer Seite nicht stimmt.",
    unbekannt: "unbekannt",
    status: "Status",
    offen: "offen",
    inBearbeitung: "In Bearbeitung",
    erledigt: "erledigt",
    meldung: "Feedback",
    aufnahme: "Aufnahme der Seite",
    ansicht: "Ansicht",
    tabelle: "Tabelle",
    kanban: "Kanban",
    gruppieren: "Gruppieren nach",
    nachStatus: "Status",
    nachPerson: "Person",
    nichtZugewiesen: "Nicht zugewiesen",
    ziehenHinweis: "Karten in eine andere Spalte ziehen, um Status oder Zuständigkeit zu ändern.",
    verschieben: (beschreibung: string) => `Verschieben: ${beschreibung}`,
    spalte: {
      datum: "Datum",
      von: "Von",
      seite: "Seite",
      beschreibung: "Beschreibung",
      screenshot: "Screenshot",
      status: "Status",
      zugewiesen: "Zugewiesen",
      aktionen: "Aktionen",
    },
    oeffnen: "Öffnen",
    ungesehen: "ungesehen",
    alsGesehen: "Als gesehen markieren",
    zuDieserSeite: "App Feedback zu dieser Seite",
  },
  auditAnsicht: {
    gibtEsNicht: "Dieses Audit gibt es nicht",
    gibtEsNichtText: "Vermutlich wurde es entfernt.",
    internesAudit: "Internes Audit",
    externesAudit: "Externes Audit",
    prioritaet: (stufe: string) => ` · Priorität ${stufe}`,
    erledigt: (prozent: number) => ` · ${prozent} % erledigt`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} überfällig`,
    zurUebersicht: "Zur Übersicht",
    status: "Status",
    stammdaten: "Stammdaten",
    titel: "Titel",
    bereich: "Geltungsbereich",
    leitenderAuditor: "Lead-Auditor",
    auditteam: "Auditteam",
    geplantVon: "Beginn (geplant)",
    geplantBis: "Ende (geplant)",
    prioritaetFeld: "Priorität",
    niedrig: "niedrig",
    mittel: "mittel",
    hoch: "hoch",
    auditziel: "Auditziel",
    kategorien: "Kategorien",
    kategorienHinweis:
      "Ein Audit ist oft mehreres zugleich — das interne Programm fährt System und Prozess in " +
      "einem Termin. Deshalb Mehrfachauswahl und keine einzelne Angabe.",
    normbezug: "Normbezug",
    normmatrixLeer: "Die Normmatrix ist leer — sie wird in den Einstellungen gepflegt.",
    nichtGeprueft: "* noch nicht gegen den konsolidierten Normtext geprüft.",
    phasen: "Phasen",
    keinePhasen: "Keine Phasen — dieses Audit wurde ohne Vorlage angelegt.",
    phase: "Phase",
    verantwortlich: "Verantwortlich",
    faellig: "Soll-Termin",
    erledigtAm: "Ist-Termin",
    phaseErgaenzen: "Phase ergänzen",
    phaseBeispiel: "z. B. Nachaudit",
    verlauf: "Verlauf",
    verlaufHinweis:
      "Geschrieben von der Datenbank, nicht von dieser Maske — und danach weder änderbar noch " +
      "löschbar.",
    nichtsGeschehen: "Noch nichts geschehen.",
    warumEntfaellt: "Warum entfällt diese Pflichtphase?",
    uebernehmen: "Übernehmen",
    abbrechen: "Abbrechen",
    angelegt: "angelegt",
    geaendert: "geändert",
    geloescht: "gelöscht",
    uebersprungen: "übersprungen",
    bearbeiten: "Bearbeiten",
    gespeichert: "Gespeichert.",
    pflicht: "Pflicht",
    kommentar: "Kommentar",
    begruendung: "Begründung für „nicht zutreffend“",
    grundPflicht: "Eine Pflichtphase kannst du nur mit Begründung überspringen.",
    datumPflicht: "„Erledigt“ braucht einen Ist-Termin.",
    phaseSpeichern: "Phase speichern",
    phaseGespeichert: "Phase gespeichert.",
  },
  maschine: {
    gibtEsNicht: "Diese Maschine gibt es nicht",
    gibtEsNichtText: "Sie wurde vermutlich gelöscht.",
    zurUebersicht: "Zur Übersicht",
    stammdaten: "Stammdaten",
    name: "Name",
    inventarnummer: "Inventar-Nr.",
    standort: "Standort",
    hersteller: "Hersteller",
    modell: "Modell",
    verantwortlich: "Verantwortlich",
    status: "Status",
    aktiv: "aktiv",
    stillgelegt: "stillgelegt",
    notizen: "Notizen",
    wartungsaufgaben: "Wartungsaufgaben",
    jahr: "Jahr",
    halbjahr: "Halbjahr",
    erstesHalbjahr: "KW 1–26",
    zweitesHalbjahr: "KW 27–52",
    wirdGebaut: "Wird gebaut …",
    nachweisbogen: "Nachweisbogen",
    neueAufgabe: "Neue Aufgabe",
    aufgabeBeispiel: "z. B. Ölstand prüfen",
    intervall: "Intervall",
    wochen: "Wochen",
    keineAufgabe: "Noch keine Aufgabe — der Bogen bliebe leer.",
    aufgabe: "Aufgabe",
    dateien: "Dateien",
    planHinterlegen: "Plan hinterlegen",
    nachweisAblegen: "Nachweis ablegen",
    dateienHinweis: "Der Herstellerplan und die zurückgescannten, unterschriebenen Bögen.",
    keineDatei: "Noch keine Datei.",
    plan: "Plan",
    nachweis: "Nachweis",
    laedt: "Lädt …",
    taeglich: "Täglich",
    woechentlich: "Wöchentlich",
    monatlich: "Monatlich",
    quartalsweise: "Quartalsweise",
    alleNWochen: "Alle N Wochen",
    alleNWochenZahl: (wochen: number) => `Alle ${wochen} Wochen`,
    bearbeiten: "Bearbeiten",
    gespeichert: "Gespeichert.",
    nameFehlt: "Ohne Namen geht es nicht.",
  },
  atr: {
    teilAnlegen: "Teil von Hand anlegen",
    teilBeispiel: "Teilenummer, z. B. VR-1234-56",
    anlegen: "Anlegen",
    wirdGelesen: "Wird gelesen …",
    mappeEinlesen: "Referenzmappe einlesen",
    suchen: "Suchen",
    suchePlatzhalter: "Teilenummer, Bezeichnung oder Zeichnung",
    nichtsGefunden: "Nichts gefunden",
    katalogLeer: "Der Katalog ist leer",
    keinTeil: "Kein Teil passt zu dieser Suche.",
    katalogLeerText: "Eine Referenzmappe einlesen oder ein Teil von Hand anlegen.",
    teilenummer: "Teilenummer",
    bezeichnung: "Bezeichnung",
    zeichnung: "Zeichnung",
    gewicht: "Gewicht kg",
    kategorie: "Kategorie",
    bereich: "Bereich",
    lieferungen: "Lieferungen",
    teilekatalog: "Teilekatalog",
    bearbeiten: "Bearbeiten",
    speichern: "Speichern",
    gespeichert: "Gespeichert.",
    gewichtUngueltig: "Gewicht bitte als Zahl in kg angeben, z. B. 0,44.",
    nichtGespeichert: (meldung: string) => `Nicht gespeichert: ${meldung}`,
  },
  lieferungen: {
    wirdGelesen: "Wird gelesen …",
    einlesen: "Lieferschein einlesen",
    laeuft: "Läuft …",
    eingangDurchsehen: "Eingang durchsehen",
    berichtNummer: (nr: string) => ` · Nr. ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} Positionen, ${zugeordnet} im Katalog gefunden.`,
    keinLieferschein: "Noch kein Lieferschein",
    keinLieferscheinSchreiben: "Ein Lieferschein-PDF einlesen — danach steht er hier zur Durchsicht.",
    keinLieferscheinLesen: "Sobald ein Lieferschein eingelesen ist, steht er hier.",
    lieferschein: "Lieferschein",
    datum: "Datum",
    programm: "Programm",
    msn: "MSN",
    status: "Status",
    entwurf: "Entwurf",
    erzeugt: "erzeugt",
    abgelegt: "abgelegt",
    atrNummer: "ATR-Nr.",
    containernummer: "Containernummer",
    erstellt: "Erstellt",
    auswaehlen: (nr: string) => `Lieferung ${nr} auswählen`,
    ausgewaehlt: (anzahl: number) => `${anzahl} ausgewählt`,
    auswahlAufheben: "Auswahl aufheben",
    containerbeschriftung: "Containerbeschriftung erstellen",
    containerFrage: "Containernummer für die ausgewählten Lieferungen:",
    containerHinweis: "Das Etikett zeigt alle Lieferungen, die diesem Container zugeordnet sind — auch solche, die schon vorher darin lagen.",
    containerErstellt: (nr: string) => `Container ${nr} zugeordnet – Beschriftung wird heruntergeladen`,
    erstellen: "Erstellen",
    ausgewaehlteLoeschen: "Ausgewählte löschen",
    loeschenFrage: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "Lieferung" : "Lieferungen"} löschen?`,
    loeschenHinweis: "Die ausgewählten Lieferungen werden mit ihren erzeugten Dateien entfernt. Das lässt sich nicht rückgängig machen.",
    loeschenBestaetigen: "Löschen",
    geloescht: (anzahl: number) => `${anzahl} gelöscht.`,
    loeschenTeilweise: (weg: number, offen: number) => `${weg} gelöscht, ${offen} nicht — inzwischen geändert oder schon weg.`,
  },
  durchsicht: {
    nichtGefunden: "Lieferung nicht gefunden.",
    wirdErzeugt: "Wird erzeugt …",
    dokumenteErzeugen: "Dokumente erzeugen",
    kopfdaten: "Kopfdaten",
    atrNummer: "ATR-Nummer",
    nummerAutomatisch: (n: string) => `automatisch: ${n}`,
    containernummer: "Containernummer",
    satzTitel: "Satzbezeichnung",
    programm: "Programm",
    msn: "MSN",
    bereich: "Bereich",
    wiegedatum: "Wiegedatum",
    pruefdatum: "Prüfdatum",
    qsUnterschrift: "QS-Unterschrift",
    hoechstgewicht: "Höchstgewicht kg",
    positionen: "Positionen",
    pos: "Pos",
    menge: "Menge",
    seriennummern: "Seriennummern",
    nichtImKatalog: "nicht im Katalog",
    poNummer: "PO-Nummer",
    poPos: "PO Pos",
    speichern: "Speichern",
    gespeichert: "Gespeichert.",
    aufServerSpeichern: "Auf Server speichern",
    wirdAbgelegt: "Wird abgelegt …",
    aufServerGespeichert: "Auf dem Server abgelegt.",
    ablageGescheitert: (ziele: string) =>
      `Nicht abgelegt: ${ziele}`,
    seriennummernAbweichung: (anzahl: number, menge: number) =>
      `${anzahl} Seriennummer(n) bei Stückzahl ${menge}`,
    seriennummernFeld: (pos: string) => `Seriennummern Position ${pos}`,
  },
  fair: {
    dateiFehlt: (meldung: string) =>
      `Die Zeichnung selbst lässt sich nicht laden (${meldung}). Die Maße stehen ` +
      "trotzdem darunter.",
    bezeichnungFrei: "Bezeichnung (leer = Dateiname)",
    beispiel: "z. B. Welle 12×40, Zeichnung 4711",
    wirdGeladen: "Wird geladen …",
    zeichnungWaehlen: "Zeichnung wählen",
    keineZeichnung: "Noch keine Zeichnung",
    keineZeichnungSchreiben: "PDF oder Bild hochladen — danach lassen sich die Maße ballonieren.",
    keineZeichnungLesen: "Sobald eine Zeichnung hochgeladen ist, steht sie hier.",
    bezeichnung: "Bezeichnung",
    teilenummer: "Teilenummer",
    kunde: "Kunde",
    hochgeladen: "Hochgeladen",
    pruefliste: "Prüfliste",
    einMass: "1 Maß",
    masse: (anzahl: number) => `${anzahl} Maße`,
    kopieren: "Kopieren",
    csv: "CSV",
    keinMass: "Noch kein Maß markiert.",
    nr: "Nr",
    seite: "Seite",
    wert: "Wert",
    wertBeispiel: "z. B. 12,0 h7",
    wertZu: (nummer: number) => `Wert zu Nummer ${nummer}`,
    nachOben: (nummer: number) => `Nummer ${nummer} nach oben`,
    nachUnten: (nummer: number) => `Nummer ${nummer} nach unten`,
    nummer: (nummer: number) => `Nummer ${nummer}`,
    drehen: "Ansicht drehen",
    verkleinern: "Verkleinern",
    vergroessern: "Vergrößern",
    einpassen: "Einpassen",
    darstellung: "Darstellung",
    bubbleGroesse: "Bubble-Größe",
    zeichnung: "Zeichnung",
    ladefehler: "Die Zeichnung ließ sich nicht laden.",
    alleKunden: "Alle Kunden",
    ohneKunde: "Ohne Kunde",
    kundenfilter: "Nach Kunde filtern",
    artikelnummer: "Artikelnr.",
    artikelnummerLang: "Artikelnummer",
    pn: "P/N",
    bubblesKleiner: "Bubbles kleiner",
    bubblesGroesser: "Bubbles größer",
    pdf: "PDF",
    pdfExport: "PDF exportieren",
    pdfWirdErstellt: "PDF wird erstellt …",
    pdfFehler: (meldung: string) => `Das PDF ließ sich nicht erstellen: ${meldung}`,
    ocrNeu: "OCR für diese Zeile neu starten",
    ocrLeer: "Nichts erkannt — bitte den Wert eintippen.",
    ocrFehler: (meldung: string) => `OCR fehlgeschlagen: ${meldung}`,
    ocrGleich: "OCR liest denselben Wert.",
    ocrErsetzenTitel: "Wert ersetzen?",
    ocrErsetzen: (nummer: number, alt: string, neu: string) => `Nummer ${nummer}: „${alt}“ durch „${neu}“ ersetzen?`,
    ersetzen: "Ersetzen",
    ziehen: (nummer: number) => `Nummer ${nummer} ziehen, um sie zu verschieben`,
    nurNummernfolge: "Verschieben geht nur in der Nummernfolge — ohne Suche und nicht nach Seite oder Wert sortiert.",
  },
  newsletter: {
    keineAusgabe: "Noch keine Ausgabe",
    keineAusgabeText: "Sobald die Redaktion eine Ausgabe veröffentlicht, steht sie hier.",
    zurRedaktion: "Zur Redaktion",
    quartalJahr: (quartal: number, jahr: number) => `Quartal ${quartal} · ${jahr}`,
    entwurfSuffix: " · Entwurf",
    ausgabe: "Ausgabe",
    quartalKurz: (quartal: number, jahr: number) => `Q${quartal} ${jahr}`,
    entwurfKlammer: " (Entwurf)",
    alsPdf: "Als PDF",
    wirdGesetzt: "Wird gesetzt …",
    seiteVon: (nr: number, gesamt: number) => `Seite ${nr} von ${gesamt} …`,
    redaktion: "Redaktion",
    niemandDazu: "In diesem Quartal ist niemand dazugekommen.",
    beitraege: "Beiträge",
    belegschaftInZahlen: "Belegschaft in Zahlen",
    neuBeiUns: "Neu bei uns",
    zurLeseransicht: "Zur Leseransicht",
    jahr: "Jahr",
    quartal: "Quartal",
    ausgabeAnlegen: "Ausgabe anlegen",
    ausgabeBearbeiten: "Ausgabe bearbeiten",
    keineAusgabeRedaktion: "Jahr und Quartal wählen und anlegen — danach entstehen hier die Kapitel.",
    titelDerAusgabe: "Titel der Ausgabe",
    status: "Status",
    entwurf: "Entwurf",
    veroeffentlicht: "veröffentlicht",
    titelbild: "Titelbild",
    rueckseite: "Rückseite",
    ersetzen: " ersetzen",
    waehlen: " wählen",
    ausgabeLoeschen: (quartal: number, jahr: number) => `Ausgabe Q${quartal} ${jahr}`,
    neuesKapitel: "Neues Kapitel",
    kapitelBeispiel: "z. B. Aus der Fertigung",
    art: "Art",
    hinzufuegen: "Hinzufügen",
    kapiteltitel: "Kapiteltitel",
    kapitelHoch: "Kapitel nach oben",
    kapitelRunter: "Kapitel nach unten",
    ueberschrift: "Überschrift",
    eintrag: "Eintrag",
    textMarkdown: "Text. Markdown ist erlaubt — **fett**, Listen, Tabellen.",
    text: "Text",
    bild: "Bild",
    bildGroesse: (nr: number) => `Größe Bild ${nr}`,
    nieEingefroren: "Noch nichts eingefroren — das Kapitel bleibt im Heft leer.",
    kpiEingefroren: "Belegschaftszahlen des Quartals sind eingefroren.",
    niemandEingefroren: "Eingefroren — in diesem Quartal ist niemand dazugekommen.",
    zugaengeEingefroren: (anzahl: number) =>
      `Eingefroren: ${anzahl} ${anzahl === 1 ? "Neuzugang" : "Neuzugänge"} im Quartal.`,
    einfrieren: "Einfrieren",
    neuEinfrieren: "Neu einfrieren",
    rechtFehlt: (quelle: string) => `Dafür fehlt das Recht an der Quelle: ${quelle} sehen.`,
    quelleKpi: "Kennzahlen",
    quellePersonal: "HR",
    ausgabeAngelegt: "Ausgabe angelegt.",
    ausgabeGeloescht: "Ausgabe gelöscht.",
    kapitelAngelegt: "Kapitel angelegt.",
    standEingefroren: "Stand eingefroren.",
  },
  signage: {
    bereiche: "Signage-Bereiche",
    medien: "Medien",
    medienHinzu: "Medien hinzufügen",
    playlists: "Playlists",
    zeitplaene: "Zeitpläne",
    geraete: "Geräte",
    dateiZiehen: "Datei hierher ziehen",
    dateiWaehlen: "Datei auswählen",
    dateiHinweis: "Bild, Video, PDF oder PPTX, bis 50 MB",
    wirdUebertragen: "wird übertragen …",
    art: "Art",
    webseite: "Webseite (URL)",
    htmlSchnipsel: "HTML-Schnipsel",
    titel: "Titel",
    titelBeispiel: "Geburtstage",
    urlHinweis:
      "Vollständige Adresse angeben. Der Player läuft auf einem eigenen Port, relative Pfade " +
      "funktionieren dort nicht.",
    aufnehmen: "Aufnehmen",
    medienFehler: "Medien konnten nicht geladen werden.",
    keineMedien: "Noch keine Medien",
    keineMedienText:
      "Lade eine Datei hoch oder nimm eine URL auf. Anschließend lassen sich die Medien in " +
      "Playlists zusammenstellen.",
    erneut: "erneut",
    inVerwendung: "Medium wird verwendet",
    inVerwendungText: (titel: string, anzahl: number) =>
      `„${titel}“ ist noch in ${anzahl} Playlist(s) eingebunden. Entferne es dort zuerst.`,
    verstanden: "Verstanden",
    wartet: "wartet",
    konvertiert: "konvertiert",
    fertig: "fertig",
    fehlgeschlagen: "fehlgeschlagen",
    keineHeartbeats: "Noch keine Heartbeats aufgezeichnet.",
    nieGesehen: "nie gesehen",
    online: "online",
    vorMinuten: (minuten: number) => `vor ${minuten} min`,
    offline: "offline",
    entzogen: "entzogen",
    keinGeraet: "Noch kein Gerät gekoppelt",
    keinGeraetText:
      "Starte einen Bildschirm mit dem Player. Er zeigt einen sechsstelligen Code, den du hier " +
      "eingibst.",
    geraetKoppeln: "Gerät koppeln",
    geraet: "Gerät",
    status: "Status",
    verfuegbarkeit: "Verfügbarkeit 24 h",
    ausfaelle: "Ausfälle 24 h",
    tags: "Tags",
    playlist: "Playlist",
    zuletztGesehen: "Zuletzt gesehen",
    seiteNeuLaden: "Seite neu laden",
    neuStarten: "Gerät neu starten",
    bearbeiten: "Bearbeiten",
    zugangEntziehen: "Zugang entziehen",
    geraetBearbeiten: "Gerät bearbeiten",
    name: "Name",
    bilddrehung: "Bilddrehung",
    ton: "Ton",
    tonAktiv: "Ton aktiv",
    abbrechen: "Abbrechen",
    speichern: "Speichern",
    tagsHinweis: "Bestimmen, welche Playlists und Zeitpläne dieses Gerät bekommt.",
    entziehenText: (name: string) =>
      `„${name}“ verliert sofort seinen Zugang und zeigt wieder den Kopplungscode.`,
    neustartText: (name: string) => `„${name}“ ist etwa eine Minute lang schwarz.`,
    geraetGespeichert: "Gerät gespeichert.",
    geraetGeloescht: "Gerät gelöscht.",
    keinGeraetGewaehlt: "kein Gerät gewählt",
    neuePlaylist: "Neue Playlist",
    neuePlaylistText: "Name und Ziel-Tags festlegen. Die Einträge kommen im nächsten Schritt.",
    namensbeispiel: "Empfang",
    keinePlaylist: "Noch keine Playlist",
    keinePlaylistText:
      "Eine Playlist bündelt Medien in einer Reihenfolge und wird über Tags an Geräte verteilt.",
    playlistAnlegen: "Playlist anlegen",
    aktiv: "Aktiv",
    erstellt: "Erstellt",
    kopieren: "Kopieren",
    playlistGeloescht: "Playlist gelöscht.",
    playlistKopiert: "Playlist kopiert. Die Einträge werden nicht mitkopiert.",
    playlistInPlan: "Playlist hat aktive Zeitpläne",
    zeitplanHinweis:
      "Ein Zeitplan hat Vorrang vor der reinen Tag-Zuordnung. Fenster über Mitternacht in zwei " +
      "Zeitpläne aufteilen.",
    wochentage: "Wochentage",
    wochentagKuerzel: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
    von: "Von",
    bis: "Bis",
    prioritaet: "Priorität",
    zeitplanAktiv: "Zeitplan aktiv",
    keineZeitplaene: "Keine Zeitpläne",
    keineZeitplaeneText:
      "Ohne Zeitplan entscheidet allein die Tag-Zuordnung, welche Playlist ein Gerät zeigt. Ein " +
      "Zeitplan schaltet eine Playlist an bestimmten Tagen und Uhrzeiten davor.",
    tage: "Tage",
    zeitfenster: "Zeitfenster",
    aktionen: "Aktionen",
    zeitplanBearbeiten: "Zeitplan bearbeiten",
    neuerZeitplan: "Neuer Zeitplan",
    zeitplaeneFehler: "Zeitpläne konnten nicht geladen werden.",
    endeNachStart: "Ende muss nach dem Start liegen. Über Mitternacht bitte zwei Zeitpläne anlegen.",
    mindestensEinTag: "Mindestens einen Wochentag wählen.",
    playlistWaehlen: "Playlist auswählen.",
    taeglich: "täglich",
    zielTags: "Ziel-Tags",
    ueberblenden: "Überblenden",
    harterSchnitt: "Harter Schnitt",
    ziehpunkt: "Ziehpunkt",
    verwerfen: "Verwerfen",
    medienHinzufuegen: "Füge Medien hinzu und ordne sie per Ziehpunkt.",
    mediumWaehlen: "Medium auswählen",
    mediumHinzufuegen: "Medium hinzufügen",
    mediumWaehlenText: "Das gewählte Medium wird am Ende der Playlist angefügt.",
    schliessen: "Schließen",
    keineMedienAnlegen: "Es gibt noch keine Medien. Lege zuerst welche im Bereich Medien an.",
    unbekanntesMedium: "unbekanntes Medium",
    playlistGespeichert: "Playlist gespeichert. Die Geräte laden sofort neu.",
    kopplungscode: "Kopplungscode",
    codeBeispiel: "ABC-123",
    geraetename: "Gerätename",
    geraeteBeispiel: "Empfang links",
    tagsPflicht: "Über die Tags bekommt das Gerät seine Playlist. Ohne Tag bleibt der Bildschirm leer.",
    koppeln: "Koppeln",
    formatErwartet: "Format XXX-XXX erwartet.",
    codeUnbekannt: "Code unbekannt, abgelaufen oder schon vergeben. Am Bildschirm neu anzeigen lassen.",
    tagEingeben: "Tag eingeben und Enter drücken",
  },
  einstellungen: {
    titel: "Einstellungen",
    bereiche: "Bereiche",
    gruppen: {
      kennzahlen: "Kennzahlen",
      kennzahlenText:
        "Zielwerte der Dashboards. Sie erscheinen als Ziellinie im Verlauf und entscheiden, ab " +
        "wann eine Kachel warnt.",
      personal: "HR",
      personalText:
        "Welche Abwesenheiten als Krankheit zählen und welche Abteilungen zur Produktion gehören. " +
        "Ohne diese Listen bleiben die Personalquoten leer.",
      atr: "ATR",
      atrText:
        "Was in jedem Dokument eines Programms gleich steht, und woher die Lieferscheine kommen.",
      qualitaet: "Qualität",
      qualitaetText:
        "Die Normmatrix, auf die sich ein Audit beruft, und die Phasenvorlagen, die ein neues " +
        "Audit als Checkliste mitbekommt.",
      sensoren: "Sensoren",
      sensorenText:
        "Die Messgeräte im Netz: wo sie stehen, unter welcher Kennung sie Temperatur und " +
        "Luftfeuchtigkeit liefern und ab wann ein Wert als zu hoch gilt.",
      zeugnisse: "Zeugnisse",
      zeugnisseText:
        "Was auf jedem Arbeitszeugnis gleich steht: Firma, Ort und die beiden Unterschriften. " +
        "Die fachliche wird beim Erzeugen aus Personio aufgelöst — hier steht nur ihr Rückfall.",
      erscheinung: "Erscheinungsbild",
      erscheinungText:
        "Das Firmenlogo — oben links in der Anwendung und in der Kopfzeile jeder erzeugten Datei: " +
        "Einarbeitungsplan, Wartungsnachweis, Schulungsübersicht, Zeugnis.",
      anzeigen: "Anzeigen",
      anzeigenText:
        "Die Adressen, die auf den Bildschirmen im Haus laufen. Jede trägt einen unterschriebenen " +
        "Token, gilt nur für ihre eine Anzeige und läuft ab.",
      email: "E-Mails",
      emailText:
        "Über welches Microsoft-365-Konto die Plattform Erinnerungen und Berichte verschickt. Versendet wird nur auf ausdrückliche Aktion.",
      ad: "Active Directory",
      adText: "Anmeldung gegen das lokale AD per LDAPS. compute prüft das Passwort beim Login und spiegelt die AD-Gruppen; App-Rechte vergibt ein Admin je Gruppe unter „Nutzer und Gruppen“.",
      zugaenge: "Nutzer und Gruppen",
      zugaengeText:
        "Personen anlegen, Gruppen bilden und ihnen App-Rechte geben. Änderungen wirken, sobald " +
        "sich die betroffene Person das nächste Mal anmeldet — die Rechte stehen in ihrem Token.",
    },
  },
  einstellungenText: {
    appName: "App-Name",
    appNameHinweis:
      "Steht in der Kopfzeile ohne Logo, im Seitentitel und auf der Anmeldeseite.",
    farbrollen: "Farbrollen",
    farbrollenHinweis:
      "Die Hauptfarbe trägt Fokus, Links, den Primärknopf und die Hauptreihe der Diagramme; die Schrift steht darauf. Je einmal für hell und dunkel.",
    hellTitel: "Hell",
    dunkelTitel: "Dunkel",
    hauptfarbe: "Hauptfarbe",
    textAufHauptfarbe: "Text auf der Hauptfarbe",
    kontrastTitel: "Zu geringer Kontrast (WCAG 2.2)",
    kontrastZeile: (thema: string, bereich: string, verhaeltnis: string, mindestens: string) =>
      `„${bereich}“ (${thema}): Kontrast ${verhaeltnis}:1, nötig ${mindestens}:1`,
    kontrastBereiche: {
      linkSeite: "Links auf der Seite",
      linkKarte: "Links auf Karten",
      fokusFlaeche: "Fokus auf grauer Fläche",
      diagramm: "Diagrammfarbe",
      knopfText: "Text auf dem Primärknopf",
    },
    farbenGespeichert: "Farben gespeichert. Sie wirken nach dem Neuladen.",
    farbenAufVorgabe: "Auf die Vorgabe zurückgesetzt.",
    farbenZuruecksetzen: "Auf Vorgabe zurücksetzen",
    email: {
      titel: "E-Mail-Versand (Microsoft 365)",
      einleitung:
        "Zentraler Dienst für Erinnerungen und Berichte über Microsoft Graph.",
      ohneSchluessel:
        "Auf dem Server ist kein GEHEIM_SCHLUESSEL gesetzt. Solange er fehlt, lässt sich kein Geheimnis ablegen.",
      gespeichert: "Gespeichert.",
      speichert: "Speichert …",
      speichern: "Speichern",
      speichernFehler: (meldung: string) => `Speichern fehlgeschlagen: ${meldung}`,
      modus: "Betriebsart",
      modusApp: "App-Berechtigung",
      modusDelegiert: "Eigener Account (delegiert)",
      modusAppHinweis: "Sendet über ein App-Konto mit Berechtigung Mail.Send; braucht ein Client-Secret und Admin-Consent.",
      modusDelegiertHinweis: "Sendet als angemeldete Person nach Geräte-Code-Anmeldung; kein Admin-Consent nötig.",
      tenantId: "Tenant-ID",
      clientId: "Client-ID",
      clientSecret: "Client-Secret",
      secretGesetzt: "hinterlegt — leer lassen, um es zu behalten",
      absender: "Absenderadresse",
      absenderName: "Absendername (optional)",
      aktivieren: "Versand aktiviert",
      testTitel: "Test-E-Mail",
      testHinweis: "Schickt eine Nachricht an die eingegebene Adresse. Nur diese Aktion versendet etwas.",
      testEmpfaenger: "Empfänger",
      testSenden: "Test-E-Mail senden",
      testLaeuft: "Sendet …",
      testOk: "Test-E-Mail gesendet.",
      testFehler: "Versand fehlgeschlagen.",
      delegiertTitel: "Anmeldung bei Microsoft",
      delegiertAnmelden: "Bei Microsoft anmelden",
      delegiertAnleitung:
        "Adresse öffnen, den Code eingeben und mit dem eigenen Microsoft-365-Konto anmelden.",
      delegiertWartet: "Wartet auf die Anmeldung …",
      verbundenMit: (konto: string) => `Angemeldet als ${konto}`,
      trennen: "Verbindung trennen",
      getrennt: "Verbindung getrennt.",
    },
    speichernFehler: (meldung: string) => `Speichern fehlgeschlagen: ${meldung}`,
    zielwertGespeichert: "Zielwert gespeichert. Die Dashboards zeigen ihn nach dem Neuladen.",
    zahlAbNull: "Bitte eine Zahl ab 0 eingeben.",
    personalGespeichert: "Gespeichert. Das HR-Dashboard zeigt es nach dem Neuladen.",
    krankTypen: "Abwesenheitsarten, die als Krankheit zählen",
    produktionAbteilungen: "Abteilungen der Produktion",
    kompetenzAttribute: "Personio-Felder, die als gepflegte Kompetenz zählen",
    ausDemBestand: "aus dem Bestand",
    abteilungenBeispiel: "Fertigung, Montage",
    firmenlogo: "Firmenlogo",
    anzeigenHinweis:
      "Erzeugt die Adresse für einen Playlist-Eintrag im Signage-Player. Sie gilt nur für die " +
      "gewählte Anzeige und läuft ab — ein Eintrag, den niemand mehr pflegt, hört damit von " +
      "selbst auf zu zeigen.",
    logoHinweis:
      "Steht oben links in der Anwendung und in der Kopfzeile jedes erzeugten Formblatts — " +
      "Einarbeitungsplan, Wartungsnachweis, Schulungsübersicht, Zeugnis. PNG, JPEG oder SVG, " +
      "höchstens 5 MB. Ist keins hinterlegt, steht dort der Schriftzug „ACM-Plattform“.",
    communityHinweis: "wird verschlüsselt abgelegt und nie wieder angezeigt",
    verwaltenSchliesstEin: "„Verwalten“ auf der Plattform-Kachel schließt jedes andere Recht ein.",
    logoAlt: "Das hinterlegte Firmenlogo",
    keinsHinterlegt: "Noch keins hinterlegt.",
    laedt: "Lädt …",
    ersetzen: "Ersetzen",
    hochladen: "Hochladen",
    logoHochladen: "Firmenlogo hochladen",
    logoHinterlegt: "Logo hinterlegt.",
    anzeige: "Anzeige",
    geburtstage: "Geburtstage der Woche",
    neuzugaenge: "Neu im Team",
    gueltigTage: "Gültig für (Tage)",
    erzeugt: "Erzeugt …",
    adresseErzeugen: "Adresse erzeugen",
    adresseKopiert: "Adresse kopiert.",
    kopierenFehler: "Kopieren ging nicht — bitte von Hand markieren.",
    kopieren: "Kopieren",
    gespeichert: "Gespeichert.",
    speichern: "Speichern",
    speichert: "Speichert …",
    firma: "Firma",
    ort: "Ort (über dem Datum)",
    nameRueckfall: "Name (Rückfall)",
    titelRueckfall: "Titel (Rückfall)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "Ausstellerprofil",
    ausstellerHinweis:
      "Steht auf jedem Zeugnis. Die Briefvorlage der ACM wird verwendet, sobald „ACM“ im " +
      "Firmennamen steht.",
    linkeUnterschrift: "Linke Unterschrift — fachlich",
    linkeHinweis:
      "Normalerweise der oder die Vorgesetzte der Person; die wird beim Erzeugen aus Personio " +
      "aufgelöst. Was hier steht, greift nur, wenn Personio nichts hergibt — bei extern " +
      "gepflegten Personen etwa.",
    rechteUnterschrift: "Rechte Unterschrift — Personalwesen",
    rechteHinweis:
      "Für alle Zeugnisse dieselbe. An eine Person aus Personio gebunden, kommt der Titel von " +
      "dort und bleibt richtig, wenn sich die Position ändert.",
    personAusPersonio: "Person aus Personio",
    keinePerson: "— keine, Freitext unten verwenden —",
    personenFehler: (meldung: string) => `Die Personenliste konnte nicht geladen werden (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "Vorlagen",
    vorlagenHinweis:
      "Eine Vorlage je Programm. Kopfdaten und Gerüstdatei stehen in jedem ATR-Dokument dieses " +
      "Programms gleich. Angelegt wird eine Vorlage beim Einlesen einer Referenzmappe im " +
      "Teilekatalog.",
    keineVorlage: "Noch keine Vorlage",
    keineVorlageText: "Eine Referenzmappe einlesen — das Programm steht dort in Zelle D2.",
    geruestHinterlegt: "Gerüstdatei hinterlegt.",
    geruestErsetzen: "Gerüst ersetzen",
    geruestWaehlen: "Gerüst wählen",
    keineHinterlegt: "noch keine hinterlegt",
    kunde: "Kunde",
    lieferant: "Lieferant",
    arbeitspaket: "Arbeitspaket",
    referenz: "Referenz",
    bestellerSpez: "Bestellerspezifikation",
    lieferantenSpez: "Lieferantenspezifikation",
    kundenSpez: "Kundenspezifikation",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "ATA-Kapitel",
    waage: "Waage",
    qsUnterschrift: "QS-Unterschrift",
    eingangsordner: "Eingangsordner",
    eingangHinweis:
      "Ein Lieferschein im Eingang wird eingelesen, wird zur Lieferung und wandert ins Archiv.",
    dateiserver: "Dateiserver",
    dateiserverHinweis:
      "Rechner, Freigabe und Dienstkonto gelten für den Eingangsordner und für „Auf Server speichern“. Welche Rechner in Frage kommen, gibt ATR_SMB_ERLAUBT vor. Ein hier eingetragenes Passwort geht ATR_SMB_PASSWORT aus der Umgebung vor.",
    laeuft: "läuft",
    aus: "aus",
    zuletzt: (zeit: string, text: string) => `Zuletzt ${zeit}: ${text}`,
    nochNichtGelaufen: "Noch nicht gelaufen.",
    prueft: "Prüfe …",
    verbindungPruefen: "Verbindung prüfen",
    laeuftGerade: "Läuft …",
    jetztDurchsehen: "Jetzt durchsehen",
    verbindungSteht: (dateien: number) =>
      `Verbindung steht. ${dateien} ${dateien === 1 ? "Datei wartet" : "Dateien warten"} im Eingang.`,
    keineVerbindung: (meldung: string) => `Keine Verbindung: ${meldung}`,
    unbekannt: "unbekannt",
    gelesenAngelegt: (gelesen: number, angelegt: number) =>
      `${gelesen} gelesen, ${angelegt} angelegt.`,
    rechner: "Rechner",
    rechnerHinweis: "muss in ATR_SMB_ERLAUBT stehen",
    freigabe: "Freigabe",
    domaene: "Domäne",
    benutzer: "Benutzer",
    eingang: "Eingang",
    ausgang: "Ausgang",
    archiv: "Archiv",
    ablageziele: "Auf Server speichern",
    ablagezieleHinweis: "Ordner unter der Freigabe, in die „Auf Server speichern“ Mappe und PDF legt. {jahr} und {kw} werden beim Ablegen eingesetzt.",
    zielMappeA350: "Mappe A350",
    zielMappeA380: "Mappe A380",
    zielLogistik: "PDF Logistik",
    zielWeightReport: "PDF Weight Report",
    zielUngueltig: "Ein Zielordner ist ungültig: leer, mit „..“ oder mit anderen Platzhaltern als {jahr} und {kw}.",
    wasEinLaufTut: "Was ein Lauf tut",
    entwurfAnlegen: "Entwurf zur Durchsicht anlegen",
    dokumenteErzeugen: "Dokumente erzeugen und ablegen",
    intervall: "Scan-Intervall (Sekunden, 0 = aus)",
    intervallUngueltig: "Das Intervall ist eine ganze Zahl ab 0.",
    passwort: "Passwort des Dienstkontos",
    passwortHinterlegt: "hinterlegt — leer lassen zum Beibehalten",
    passwortUmgebung: "aus der Umgebung (ATR_SMB_PASSWORT) — ein Eintrag hier geht vor",
    passwortFehlt: "noch keines hinterlegt",
    passwortOhneSchluessel: "GEHEIM_SCHLUESSEL fehlt in der Umgebung — ohne ihn lässt sich kein Passwort ablegen.",
    speichern: "Speichern",
    gespeichert: "Gespeichert.",
  },
  qualitaetEinstellungen: {
    normmatrix: "Normmatrix",
    normmatrixHinweis:
      "Klauseln, auf die sich ein Audit beruft. Eine benutzte Norm lässt sich nicht löschen — " +
      "sie wird stillgelegt, sonst verlöre ein Audit still seine Grundlage.",
    schonInMatrix: "Diese Klausel steht schon in der Matrix.",
    regelwerk: "Regelwerk",
    revision: "Revision",
    klausel: "Klausel",
    kurztext: "Kurztext",
    kurztextBeispiel: "Internes Audit",
    aufnehmen: "Aufnehmen",
    geprueft: "Geprüft",
    aktiv: "Aktiv",
    geprueftSchalter: (norm: string) => `${norm} geprüft`,
    aktivSchalter: (norm: string) => `${norm} aktiv`,
    phasenvorlagen: "Phasenvorlagen",
    phasenvorlagenHinweis:
      "Die Schrittfolge, die ein neues Audit mitbekommt. Sie wird beim Anlegen kopiert — eine " +
      "spätere Änderung schreibt keine Historie um.",
    neueVorlage: "Neue Vorlage",
    vorlageBeispiel: "Systemaudit Standard",
    anlegen: "Anlegen",
    schritte: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "Schritt" : "Schritte"}`,
    schrittErgaenzen: "Schritt ergänzen",
    schrittBeispiel: "z. B. Eröffnungsgespräch",
  },
  personioZugang: {
    taktGespeichert: "Intervall gespeichert.",
    abgleichTitel: "Abgleich",
    abgleichHinweis:
      "Wie oft die Plattform die Personio-Daten von selbst holt, und ein Abgleich von Hand.",
    intervall: "Syncintervall",
    intervallWahl: {
      "0": "Nur manuell",
      "1": "Stündlich",
      "6": "Alle 6 Stunden",
      "24": "Täglich",
      "168": "Wöchentlich",
    },
    abgleichJetzt: "Daten aktualisieren",
    abgleichLaeuft: "Wird abgeglichen …",
    abgleichFertig: (mitarbeiter: number, anwesenheiten: number, abwesenheiten: number) =>
      `Abgeglichen: ${mitarbeiter} Mitarbeiter, ${anwesenheiten} Anwesenheiten, ${abwesenheiten} Abwesenheiten.`,
    abgleichTeilweise: (mitarbeiter: number, fehler: string) =>
      `Teilweise abgeglichen (${mitarbeiter} Mitarbeiter): ${fehler}`,
    abgleichFehler: (fehler: string) => `Abgleich fehlgeschlagen: ${fehler}`,
    nachweisTitel: "Nachweise nach Personio",
    nachweisHinweis:
      "Überträgt nach einer Schulungs- oder Kompetenzänderung einen Nachweis ins Personio-Profil. Standardmäßig aus.",
    nachweisAktiv: "Nachweise übertragen",
    nachweisKategorie: "Dokumentenkategorie",
    nachweisKategoriePlatzhalter: "ID der Personio-Kategorie",
    nachweisGespeichert: "Gespeichert.",
    titel: "Personio-Zugangsdaten",
    einleitung:
      "Zugangsdaten einer Personio-API-Anwendung. Ohne sie bleiben Abgleich, " +
      "Profilbilder und die Vorschlagslisten leer.",
    kennung: "Client-ID",
    geheimnis: "Client-Secret",
    feldHinweis:
      "Werden verschlüsselt abgelegt und nie wieder angezeigt. Wer sie wechseln " +
      "will, trägt neue ein.",
    speichern: "Speichern",
    gespeichert: "Zugangsdaten hinterlegt.",
    speichernFehler: (meldung: string) => `Speichern fehlgeschlagen: ${meldung}`,
    entfernen: "Entfernen",
    entfernt: "Zugangsdaten entfernt.",
    pruefen: "Verbindung prüfen",
    prueftGerade: "Prüft …",
    verbindungSteht: "Personio nimmt die Zugangsdaten an.",
    verbindungFehlt: "Personio antwortet nicht.",
    laedt: "Lädt …",
    keineHinterlegt: "Es sind keine Zugangsdaten hinterlegt.",
    ausDerUmgebung: "Es gelten die Zugangsdaten aus der Umgebung des Servers (.env).",
    hinterlegtSeit: (zeitpunkt: string, wer: string | null) =>
      wer
        ? `Hinterlegt am ${zeitpunkt} von ${wer}.`
        : `Hinterlegt am ${zeitpunkt}.`,
    ohneSchluessel:
      "Auf dem Server ist kein GEHEIM_SCHLUESSEL gesetzt. Solange er fehlt, " +
      "lässt sich nichts verschlüsselt ablegen.",
  },
  sensorEinstellungen: {
    neuesGeraet: "Neues Gerät",
    name: "Name",
    nameBeispiel: "Serverraum",
    rechner: "Rechner",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "muss in SNMP_ERLAUBT stehen",
    community: "Community",
    port: "Port",
    kennungTemperatur: "Kennung Temperatur",
    kennungLuftfeuchte: "Kennung Luftfeuchtigkeit",
    faktorTemperatur: "Faktor Temperatur",
    faktorHinweis: "0,1 wenn das Gerät Zehntelgrad als ganze Zahl liefert",
    faktorLuftfeuchte: "Faktor Luftfeuchtigkeit",
    farbe: "Farbe im Verlauf",
    farbeHinweis: "z. B. #0f6e8c",
    optional: "optional",
    anlegen: "Anlegen",
    fragt: "Fragt …",
    ausprobieren: "Ausprobieren",
    keinGeraet: "Noch kein Gerät",
    keinGeraetText: "Trag oben Rechner, Community und mindestens eine Kennung ein.",
    wirdAbgefragt: (name: string) => `${name} wird abgefragt`,
    communityErsetzen: "Community ersetzen",
    unveraendert: "unverändert",
    communityErsetzt: "Community ersetzt.",
    sensorAngelegt: "Sensor angelegt.",
    sensorGeloescht: "Sensor gelöscht, samt Zeitreihe.",
    zahlEingeben: "Bitte eine Zahl eingeben.",
    taktTitel: "Abfrage-Takt",
    intervall: "Abfrage-Intervall (Sekunden, 0 = aus)",
    intervallHinweis:
      "Gilt für alle Sensoren. Bereich 0–86400; 0 schaltet die selbsttätige Abfrage ab. Unter 60 Sekunden wird effektiv jede Minute abgefragt.",
    intervallFehler: "Das Intervall muss eine ganze Zahl zwischen 0 und 86400 sein (0 = aus).",
    grenzenTitel: "Globale Grenzwerte",
    grenzenHinweis: "Gelten für alle Sensoren. Ein leeres Feld heißt: keine Grenze.",
    temperaturMin: "Temperatur min (°C)",
    temperaturMax: "Temperatur max (°C)",
    feuchteMin: "Luftfeuchtigkeit min (%)",
    feuchteMax: "Luftfeuchtigkeit max (%)",
    temperaturFehler: "Temperatur min muss unter max liegen.",
    feuchteFehler: "Luftfeuchtigkeit min muss unter max liegen.",
    einstellungenGespeichert: "Takt und Grenzwerte gespeichert.",
    verwerfen: "Verwerfen",
  },
  zugaenge: {
    stufen: {
      viewer: "Ansehen",
      editor: "Bearbeiten",
      admin: "Verwalten",
    },
    gruppeAngelegt: "Gruppe angelegt.",
    gruppeGibtEsSchon: "Diesen Gruppennamen gibt es schon.",
    personAngelegt: "Person angelegt",
    gruppeUmbenannt: "Gruppe umbenannt.",
    gruppeGeloescht: "Gruppe gelöscht.",
    mitgliedHinzu: "Mitglied hinzugefügt. Es wirkt nach der nächsten Anmeldung.",
    schonInGruppe: "Diese Person ist schon in der Gruppe.",
    neuesPasswort: "Neues Passwort",
    mitgliedEntfernt: "Mitglied entfernt. Es wirkt nach der nächsten Anmeldung.",
    gemeldeteSeiten: "App Feedback ansehen",
    neueGruppe: "Neue Gruppe",
    gruppeBeispiel: "z. B. Vertrieb Innendienst",
    anlegen: "Anlegen",
    neuePerson: "Neue Person",
    personBeispiel: "vorname.nachname@acm.local",
    keineGruppe: "Noch keine Gruppe",
    keineGruppeText: "Lege eine Gruppe an, weise ihr App-Rechte zu und nimm Personen auf.",
    verzeichnis: "Verzeichnis",
    ausVerzeichnis: "Kommt aus dem Verzeichnis",
    umbenennen: "Umbenennen",
    mitRechten: "Mit Rechten",
    ohneRechte: "Ohne Rechte",
    keinZugriff: "kein Zugriff",
    rechteAnGruppe: "Rechte hängen an der Gruppe, nicht an der Person.",
    passwortNurJetzt:
      "Das Passwort steht nur jetzt hier. Danach lässt es sich nur zurücksetzen, nicht anzeigen.",
    fertig: "Fertig",
    anmeldung: "Anmeldung",
    passwort: "Passwort",
    gruppeUmbenennen: "Gruppe umbenennen",
    abbrechen: "Abbrechen",
    speichern: "Speichern",
    gruppenname: "Gruppenname",
    mitgliederVon: (name: string) => `Mitglieder von „${name}“`,
    wirktNachAnmeldung: "Änderungen wirken, sobald sich die Person das nächste Mal anmeldet.",
    schliessen: "Schließen",
    personHinzufuegen: "Person hinzufügen",
    auswaehlen: "— auswählen —",
    hinzufuegen: "Hinzufügen",
    keineMitglieder: "Diese Gruppe hat noch keine Mitglieder.",
    passwortZuruecksetzen: "Passwort zurücksetzen",
    mitgliedEntfernen: "Mitglied entfernen",
    entfernen: "Entfernen",
  },
  kopftitel: {
    start: "Apps",
    kennzahlen: "KPI-Dashboard",
    offeneSchulungen: "Offene Schulungen",
    schulungsmatrix: "Schulungsmatrix",
    atrLieferungen: "ATR-Lieferungen",
    atrTeilekatalog: "ATR-Teilekatalog",
  },
  kennzahlenHub: {
    titel: "KPI-Dashboard",
    bereiche: {
      "/kpi/vertrieb": "Umsatz, Auftragswert, Kundenanteil",
      "/hr/kennzahlen": "Belegschaft, Fluktuation, Krankenstand — eigene Berechtigung",
      "/kpi/qualitaet": "Audit-Findings und Reklamationsquote",
      "/kpi/finanzen": "Material- und Personalkostenquote",
      "/kpi/einkauf": "Liefertermintreue der Lieferanten",
      "/kpi/produktion": "Verzug, überfällige Aufträge",
      "/kpi/bewertung": "Kennzahlen bewerten, Maßnahmen ableiten, zuweisen und verfolgen",
    },
  },
  personalHub: {
    bereiche: {
      "/hr/kennzahlen": "Belegschaft, Fluktuation, Krankenstand, Überstunden",
      "/hr/organigramm": "Wer wem berichtet",
      "/hr/kompetenzen": "Qualifikationsmatrix je Abteilung",
      "/hr/schulungen": "Pflichtschulungen, Termine, Nachweise",
      "/hr/onboarding": "Eintritte, Einarbeitung und Vorgänge",
      "/hr/einarbeitung": "Einarbeitungspläne und ihr Stand",
      "/hr/dokumente": "Formblätter erzeugen, drucken, eingescannt zurücklesen",
      "/hr/zeugnisse": "Arbeitszeugnisse schreiben und ausgeben",
    },
  },
  bewertung: {
    titel: "KPI-Bewertung & Maßnahmen",
    uebersichtFehler: (meldung: string) => `Konnte nicht geladen werden: ${meldung}`,
    nurLesen:
      "Du kannst Bewertungen lesen, aber nicht schreiben. Dafür braucht es das Recht " +
      "„Bearbeiten“ auf den Einstellungen.",
    bubbles: "Bubbles",
    bubblesLeer: "Noch keine Bubbles.",
    neu: "neu",
    alsGesehen: "Als gesehen markieren",
    zumDashboard: "Zum Dashboard",
    bubble: (nummer: number) => `Bubble ${nummer}`,
    ohnePosition: "ohne Position im Diagramm",
    neueMassnahme: "Neue Maßnahme",
    kpiWaehlen: "KPI wählen…",
    ohneBubble: "— ohne Bubble —",
    titelPlatzhalter: "Maßnahme (Titel)",
    verantwortlichWaehlen: "Verantwortlich…",
    anlegen: "Maßnahme",
    massnahmen: "Maßnahmen",
    alleStatus: "Alle Status",
    statusFilter: "Nach Status filtern",
    keineMassnahme: "Noch keine Maßnahme.",
    nichtZugewiesen: "nicht zugewiesen",
    spalte: {
      kpi: "KPI",
      massnahme: "Maßnahme",
      verantwortlich: "Verantwortlich",
      faellig: "Fällig",
      prioritaet: "Priorität",
      status: "Status",
      aktionen: "Aktionen",
    },
    status: {
      offen: "offen",
      laeuft: "in Arbeit",
      erledigt: "erledigt",
      verworfen: "verworfen",
    },
    prioritaet: {
      niedrig: "niedrig",
      mittel: "mittel",
      hoch: "hoch",
    },
    ampel: {
      keine: "keine Ampel",
      gruen: "Grün",
      gelb: "Gelb",
      rot: "Rot",
    },
    bereiche: {
      vertrieb: "Vertrieb",
      einkauf: "Einkauf",
      produktion: "Produktion",
      qualitaet: "Qualität",
      finanzen: "Finanzen",
      personal: "HR",
    },
    verwalten: "In Maßnahmen verwalten →",
    anzahlMassnahmen: (anzahl: number) => `${anzahl} Maßnahme(n)`,
  },
  erklaerung: {
    hinweis: "Erklärung",
    frage: (titel: string) => `Wie wird „${titel}“ gerechnet?`,
    knopf: "Rechenweg",
    untertitel: "So wird gerechnet",
    ganzeSeite: "Ganze Hilfeseite",
  },
};

export type Texte = typeof de;
