import { TITEL, type Pfadtitel } from "@/lib/brotkrumen";

/**
 * Die deutschen Texte der Oberfläche. Diese Datei ist die Vorlage: ihr Typ
 * bestimmt, was jede andere Sprache liefern muss — eine fehlende Übersetzung
 * ist ein Übersetzungsfehler und kein leerer Kasten zur Laufzeit.
 *
 * Es stehen hier nur Texte der **Schale**: Kopfzeile, Pfad, Startbildschirm,
 * Anmeldung. Die Fachseiten kommen bereichsweise dazu. Ein halbes Wörterbuch
 * ist besser als ein ganzes, das zur Hälfte maschinell geraten ist.
 */
export const de = {
  kopf: {
    uebersicht: "Zur Übersicht",
    hilfe: "Hilfe",
    einstellungen: "Einstellungen",
    abmelden: "Abmelden",
    sprache: "Sprache",
    erscheinungsbild: "Erscheinungsbild",
    hell: "Hell",
    dunkel: "Dunkel",
    system: "Wie das System",
    meldungenLeer: "Meldungen — nichts Neues",
    meldungen: (anzahl: number) => `Meldungen — ${anzahl} noch nicht angesehen`,
    massnahmenLeer: "Maßnahmen — keine offen",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Maßnahmen — ${offen} offen, davon ${ueberfaellig} überfällig`
        : `Maßnahmen — ${offen} offen`,
  },
  pfad: {
    aria: "Pfad",
    start: "Start",
    seiten: TITEL as Pfadtitel,
  },
  start: {
    titel: "Apps",
    verweigert: (name: string) => `Für „${name}“ hast du keine Berechtigung.`,
    keineApp:
      "Deinem Konto ist noch keine App zugewiesen. Bitte an die Plattform-Verwaltung wenden.",
  },
  anmeldung: {
    titel: "ACM-Plattform",
    aufforderung: "Mit deinem Konto anmelden.",
    email: "E-Mail",
    passwort: "Passwort",
    knopf: "Anmelden",
    laeuft: "Anmelden …",
  },
  allgemein: {
    laedt: "Wird geladen …",
  },
  zeitraum: {
    monat: "Dieser Monat",
    quartal: "Dieses Quartal",
    jahr: "Dieses Jahr",
    alles: "Alles",
    frei: "Zeitraum wählen",
    von: "von",
    bis: "bis",
    vonAria: "Zeitraum von",
    bisAria: "Zeitraum bis",
    verdreht: "Das Ende liegt vor dem Anfang.",
  },
  vergleich: {
    vorperiode: "zur Vorperiode",
    vormonat: "zum Vormonat",
    vorquartal: "zum Vorquartal",
    vorjahr: "zum Vorjahr",
    zeitraumDavor: "zum Zeitraum davor",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Datenstand ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Datenstand unvollständig — ${fehlend} ${anzahl === 1 ? "fehlt" : "fehlen"}`,
    heute: "heute",
    gestern: "gestern",
    vorTagen: (tage: number) => `vor ${tage} Tagen`,
    nie: "nie",
    arten: {
      umsatz: "Umsatz",
      auftraege: "Aufträge",
      angebote: "Angebote",
      interessenten: "Interessenten",
      kontakte: "Kontakte",
      liefertreue: "Liefertreue",
      lagerbewegungen: "Lagerbewegungen",
      lagerpreise: "Lagerpreise",
      auftragspositionen: "Auftragspositionen",
      lieferscheine: "Lieferscheine",
      pruefungen: "Prüfungen",
      acht_d: "8D-Berichte",
      wareneingaenge: "Wareneingänge",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `Kennzahlen konnten nicht geladen werden: ${meldung}`,
    keineDatenTitel: "Für diesen Zeitraum liegen keine Daten vor",
    keineDatenVor: "Lade die ERP-Exporte unter ",
    keineDatenNach: " hoch, oder wähle einen größeren Zeitraum.",
    keineWerte: "keine Werte im Zeitraum",
    laedt: "wird geladen …",
    jeTag: "je Tag",
    jeWoche: "je Woche",
    jeMonat: "je Monat",
  },
  vertrieb: {
    umsatz: "Umsatz",
    umsatzHinweis: "Rechnungen abzüglich Gutschriften",
    auftragswert: "Ø Auftragswert",
    ueberNull: "Aufträge über 0 €",
    auftraege: "Aufträge gesamt",
    verlauf: "Umsatzverlauf",
    verlaufHinweis: (takt: string) => `${takt}, Gutschriften abgezogen`,
    kundenanteil: "Kundenanteil am Umsatz",
    kunde: "Kunde",
    anteil: "Anteil",
    uebrige: "Übrige",
    jeErfasser: "Aufträge je Erfasser",
    erfasser: "Erfasser",
    anzahl: "Aufträge",
    summe: "Summe",
  },
  aktivitaet: {
    titel: "Vertriebsaktivität",
    jeWoche: (von: string, bis: string) => `je Kalenderwoche, ${von} bis ${bis}`,
    ladeFehler: (meldung: string) => `Vertriebsaktivität konnte nicht geladen werden: ${meldung}`,
    leer: "Keine Kontakte, Angebote oder Interessenten in diesem Zeitraum.",
    kw: (woche: string) => `KW ${woche}`,
    ziel: (wert: string) => `Ziel ${wert} / Woche`,
    erstkontakte: "Erstkontakte",
    erstkontakteHinweis: "erledigte Kontakte vom Typ ERS",
    besuche: "Besuche",
    besucheHinweis: "vor Ort und online zusammen",
    interessenten: "Interessenten",
    interessentenHinweis: "neu erfasst, ohne Vertriebler-Zuordnung",
    angebote: "Angebote",
    angeboteHinweis: "Summe der geschriebenen Angebote",
    auftragseingang: "Auftragseingang",
    auftragseingangHinweis: "Stornos gegengerechnet",
  },
  einkauf: {
    einleitung: "Liefertermintreue der Lieferanten. Gezählt wird, was im Zeitraum angekommen ist.",
    keineDaten: "Für diesen Zeitraum liegen keine Lieferpositionen vor",
    ladeVor: "Lade den Liefertreue-Export unter ",
    ladeNach: " hoch.",
    otd: "OTD-Quote",
    otdHinweis: (ziel: string) => `Ziel ${ziel} · pünktlich heißt Verzug ≤ 0`,
    puenktlich: "Pünktliche Positionen",
    gesamt: "Positionen gesamt",
    verzugSchnitt: "Ø Verzug",
    verzugHinweis: "Positionen ohne Verzugswert zählen hier nicht mit",
    verlauf: "OTD-Quote im Zeitverlauf",
    verlaufHinweis: "Lücken sind Zeiträume ohne Lieferpositionen.",
    ladenhueter: "Bestellung auf Lager — Ladenhüter",
    kapital: (wert: string) => `Gebundenes Kapital: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Lagerartikel ohne Bewegung seit mindestens ${tage} Tagen, höchster Wert zuerst. ` +
      "Stichtag ist heute — der Zeitraum oben gilt hier nicht, weil ein Bestand kein Zeitraum ist.",
    artikel: "Artikel",
    bezeichnung: "Bezeichnung",
    bestand: "Bestand",
    liegtSeit: "Liegt seit",
    stueckpreis: "Stückpreis",
    wert: "Wert",
    positionen: "Lieferpositionen",
    positionenHinweis:
      "Größter Verzug zuerst, Positionen ohne Verzugswert ganz oben. Höchstens 500 Zeilen.",
    auftrag: "Auftrag",
    lieferant: "Lieferant",
    zieltermin: "Zieltermin",
    geliefert: "Geliefert",
    verzug: "Verzug",
  },
  produktion: {
    einleitung: "Aufträge in Verzug. Gezählt wird ein Auftrag erst, wenn sein Ausgang feststeht.",
    keineDaten: "Für diesen Zeitraum liegt kein Auftrag mit feststehendem Ausgang vor",
    ladeVor: "Lade die Auftragspositionen und die Lieferscheine unter ",
    ladeNach:
      " hoch. Beide werden gebraucht: die eine Datei trägt den Zieltermin, die andere das Ist-Datum.",
    quote: "Verzugsquote",
    quoteHinweis: (ziel: string) => `Höchstens ${ziel}`,
    inVerzug: "Aufträge in Verzug",
    gesamt: "Aufträge gesamt",
    gesamtHinweis: "ohne noch nicht fällige offene Aufträge",
    verzugSchnitt: "Ø Verzug",
    verzugHinweis: "pünktliche Aufträge gehen negativ ein",
    verlauf: "Verzugsquote im Zeitverlauf",
    verlaufHinweis: "Nach Zieltermin. Lücken sind Zeiträume ohne gezählte Aufträge.",
    ziellinie: "Ziel",
    liste: "Aufträge in Verzug",
    listeHinweis:
      "Größter Verzug zuerst. Bei offenen Aufträgen wächst er täglich weiter. Höchstens 500 Zeilen.",
    auftrag: "Auftrag",
    kunde: "Kunde",
    stand: "Stand",
    zieltermin: "Zieltermin",
    geliefert: "Geliefert",
    verzug: "Verzug",
    verspaetet: "zu spät geliefert",
    offen: "offen, überfällig",
  },
  finanzen: {
    einleitung: "Material- und Personalkosten im Verhältnis zum Rechnungsumsatz.",
    keineDatenVor:
      "Es braucht drei Dateien: die Lagerbewegungen für den Verbrauch, die Wareneingänge für " +
      "die Preise und den Umsatz als Bezugsgröße. Alle drei liegen unter ",
    keineDatenNach: ".",
    materialquote: "Materialkostenquote",
    materialquoteHinweis: "Materialkosten / Umsatz",
    hoechstens: (ziel: string) => `Höchstens ${ziel}`,
    materialkosten: "Materialkosten",
    umsatz: "Umsatz",
    personalquote: "Personalkostenquote",
    brauchtZeitraum: "braucht einen Zeitraum",
    personalHinweis: (kosten: string, personen: string) => `${kosten} bei ${personen} Personen`,
    ohnePreis: "Artikel ohne Preis",
    ohnePreisHinweis: "verbraucht, aber nicht bewertet",
    jeAbteilung: "Personalkosten je Abteilung",
    abteilung: "Abteilung",
    personen: "Personen",
    kosten: "Kosten",
    anteil: "Anteil",
    verlauf: "Materialkostenquote im Zeitverlauf",
    verlaufHinweis: "Lücken sind Zeiträume ohne Umsatz — ohne Bezugsgröße gibt es keine Quote.",
    ziellinie: "Ziel",
    verbrauch: "Materialverbrauch je Artikel",
    verbrauchHinweis:
      "Höchste Kosten zuerst. Artikel ohne Preis stehen am Ende — sie gehen in die Quote " +
      "nicht ein. Höchstens 500 Zeilen.",
    artikel: "Artikel",
    bezeichnung: "Bezeichnung",
    menge: "Verbrauch",
    stueckpreis: "Stückpreis",
    keinPreis: "kein Preis",
  },
  qualitaet: {
    einleitung: "Audit-Findings, Reklamationsquote und Prüfmengen.",
    auditart: "Auditart:",
    keineArt: "Keine Auditart ausgewählt. Wähle mindestens eine, sonst gibt es nichts zu zählen.",
    keineDaten: "Für diesen Zeitraum liegen keine Audit-Befunde vor",
    ladeVor: "Lade den 8D-Export unter ",
    ladeNach: " hoch.",
    behoerde: "Behörde",
    extern: "Extern",
    intern: "Intern",
    kunde: "Kunde",
    level1: "Audit-Findings Level 1",
    level2: "Audit-Findings Level 2",
    ohneLevel: "Ohne erkennbares Level",
    ohneLevelHinweis: "zählt in keiner Kachel",
    hoechstens: (ziel: number) => `Höchstens ${ziel}`,
    auditVerlauf: "Audit-Findings im Zeitverlauf",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `Anteil der Menge ohne Beanstandung. Bezugsgröße: ${bezug}.`,
    fehlerquote: (quote: string) => `Fehlerquote: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Fehlerquote: ${quote} · Ziel ${ziel}`,
    reklamiert: "Reklamierte Menge",
    bezugsmenge: "Bezugsmenge",
    bezugsmengeNull: "ohne sie gibt es keine Quote",
    mehrAlsBezogen:
      "Es ist mehr reklamiert als bezogen worden. Das kann die Rechnung nicht auflösen: " +
      "Zähler und Nenner kommen aus verschiedenen Dateien mit eigenen Datumsfeldern. Prüfe, " +
      "ob die Bezugsdatei für diesen Zeitraum vollständig hochgeladen ist.",
    reklKunde: "Kunde",
    reklIntern: "intern",
    reklLieferant: "Material-Lieferanten",
    reklWerkbank: "Werkbänke",
    bezugKunde: "gelieferte Menge",
    bezugIntern: "gelieferte Menge",
    bezugLieferant: "Wareneingang ohne Dienstleistung",
    bezugWerkbank: "Wareneingang der Warengruppen DIENST und SERVIC",
    mengeGesamt: "gemeldete Menge",
    mengeAkzeptiert: "akzeptierte Menge",
    onQualityBezug: (menge: string) => `On Quality (Bezug ${menge})`,
    ziellinie: "Ziel",
    geprueft: "Geprüfte Produkte",
    geprueftHinweis: (pruefer: string, tage: string) =>
      `Menge je Prüfer und Prüftag. Der Teiler ist für beide Größen derselbe: ${pruefer} Prüfer an ${tage} Tagen.`,
    gross: "Große Produkte",
    klein: "Kleine Produkte",
    mindestens: (ziel: number) => `Mindestens ${ziel} je Tag und Prüfer`,
    buchungen: "Buchungen der Qualitätsprüfung",
    buchungenHinweis:
      "Eine abgewählte Buchung bleibt stehen, zählt aber in keiner Kachel. " +
      "Größte Menge zuerst, höchstens 500 Zeilen.",
    zaehltMit: "Zählt mit",
    datum: "Datum",
    pruefer: "Prüfer",
    produkt: "Produkt",
    groesse: "Größe",
    menge: "Menge",
    ausschuss: "Ausschuss",
    mitzaehlen: (datum: string) => `Buchung vom ${datum} mitzählen`,
    klasseGross: "groß",
    klasseKlein: "klein",
    diagnose: "Befunde ohne erkennbares Level",
    diagnoseHinweis:
      "Das Level steht in der Quelldatei im Freitext. Steht dort weder „Major … Level 1“ noch " +
      "„Minor … Level 2“, zählt der Befund nirgends. Diese Liste zeigt, wo nachzubessern ist.",
    bericht: "Bericht",
    art: "Art",
    adresse: "Adresse",
    bezeichnung: "Bezeichnung",
  },
  personal: {
    einleitung:
      "Aus dem Personio-Abgleich. Das Tagessoll kommt aus dem hinterlegten " +
      "Arbeitszeitmodell je Person, nicht aus einem pauschalen Achtstundentag.",
    uebersicht: "Übersicht",
    standLaedt: "Abgleichstand wird geladen …",
    keinAbgleich: "Noch kein Abgleich gelaufen. Er läuft nachts um 02:15 von selbst.",
    letzterAbgleich: (zeitpunkt: string, status: string) => `Letzter Abgleich ${zeitpunkt} · ${status}`,
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} Personen, ${anwesenheiten} Anwesenheiten, ${abwesenheiten} Abwesenheiten`,
    abgleichLaeuft: "läuft …",
    abgleichen: "Jetzt abgleichen",
    keineDaten: "Für diesen Zeitraum liegen keine Anwesenheiten vor",
    keineDatenHinweis:
      "Entweder ist der Personio-Abgleich noch nicht gelaufen, oder der Zeitraum liegt " +
      "vor dem Beginn der Aufzeichnung.",
    ueberstunden: "Überstunden-Quote",
    stundenVon: (teil: string, ganz: string) => `${teil} von ${ganz} Std.`,
    krankheit: "Krankheitsquote",
    krankheitsartenFehlen: "Krankheitsarten nicht hinterlegt",
    fluktuation: "Fluktuation",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} Austritte, Ø ${schnitt} Beschäftigte`,
    personen: "Erfasste Personen",
    personenHinweis: "mit Anwesenheit im Zeitraum",
    krankheitHinweisVor:
      "Die Krankheitsquote bleibt leer, solange nicht hinterlegt ist, welche " +
      "Personio-Abwesenheitsarten als Krankheit zählen. Einzutragen unter ",
    krankheitHinweisNach: ".",
    verlauf: "Verlauf",
    reiheUeberstunden: "Überstunden",
    reiheKrankheit: "Krankheit",
  },
  melden: {
    knopf: "Melden",
    titel: "Etwas melden",
    frage: "Was stimmt auf dieser Seite nicht? Ein Bild der Seite geht mit.",
    abbrechen: "Abbrechen",
    senden: "Senden",
    sendet: "Wird gesendet …",
    beispiel: "Zum Beispiel: Die Kachel zeigt einen leeren Wert, obwohl Daten da sind.",
    beschreibung: "Beschreibung",
    aufnahme: "Aufnahme der Seite",
    gehtMit: "Diese Aufnahme geht mit.",
    nimmtAuf: "Die Seite wird aufgenommen …",
    misslungen: "Die Seite ließ sich nicht aufnehmen — die Meldung geht ohne Bild.",
    dankeMitBild: "Danke — die Meldung ist angekommen.",
    dankeOhneBild: "Danke — die Meldung ist angekommen, ohne Bild der Seite.",
  },
  belegschaft: {
    titel: "Belegschaft",
    hinweis:
      "Stand heute. Die Verteilungen zeigen die aktuellen Stammdaten, nicht die von damals — " +
      "Personio liefert keine Historie. Dass „Beschäftigte“ und die Kompetenzquote verschiedene " +
      "Nenner haben, ist Absicht: die eine Zahl folgt dem Personio-Status, die andere Ein- und " +
      "Austrittsdatum. Beide Wege stammen aus dem Altprojekt.",
    ladeFehler: (meldung: string) => `Belegschaft konnte nicht geladen werden: ${meldung}`,
    beschaeftigte: "Beschäftigte",
    beschaeftigteHinweis: "nach Personio-Status „aktiv“",
    neuImQuartal: "Neu im Quartal",
    bestand: "Bestand",
    kompetenzen: "Kompetenzen gepflegt",
    felderFehlen: "Felder nicht hinterlegt — ",
    kompetenzHinweis: (mit: string, aktive: string) => `${mit} von ${aktive} nach Ein- und Austritt`,
    geschlecht: "Geschlecht",
    beschaeftigungsart: "Beschäftigungsart",
    abteilungen: "Abteilungen",
    maennlich: "männlich",
    weiblich: "weiblich",
    divers: "divers",
    unbekannt: "unbekannt",
    vollzeit: "Vollzeit",
    teilzeit: "Teilzeit",
    geringfuegig: "geringfügig",
    extern: "extern",
  },
  mitarbeiter: {
    titel: "Mitarbeiter",
    nurMitUeberstunden: "nur mit Überstunden",
    ausgeblendet: (anzahl: number) => `(${anzahl} ausgeblendet)`,
    person: "Person",
    abteilung: "Abteilung",
    istStunden: "Ist-Std.",
    ueberstunden: "Überstunden",
    quote: "ÜS %",
  },
  wochenbericht: {
    titel: "Wochenbericht",
    ladeFehler: (meldung: string) => `Wochenbericht konnte nicht geladen werden: ${meldung}`,
    kalenderwoche: "Kalenderwoche",
    kw: (woche: string, jahr: string) => `KW ${woche} / ${jahr}`,
    keineDaten: "Für diese Woche liegen keine Anwesenheiten vor.",
    saldo: "Saldo Mehrarbeit",
    saldoHinweis: (personen: string) => `Ist minus effektives Soll, über alle ${personen} Personen`,
    ueberSoll: "Über dem Soll",
    ueberSollHinweis: (gesamt: string) => `von ${gesamt} Personen mit Stempelung`,
    krankheit: "Krankheit",
    tage: "Tage",
    stunden: "Std.",
    krankheitHinweis: "über Kalendertage der Abwesenheit verteilt",
    ist: "Ist",
    soll: "Soll",
    saldoSpalte: "Saldo",
    fussnote:
      "Soll ist das effektive Wochensoll: Urlaub und Krankheit sind abgezogen, wer " +
      "unentschuldigt fehlt steht im Minus. In der laufenden Woche zählt das Soll nur bis zum " +
      "letzten gestempelten Tag.",
  },
  titel: {
    /** Detailseiten und Seiten, deren Tab-Titel ausführlicher heißt als die
     *  Krume im Pfad. Alles andere holt seinen Titel von dort. */
    schulung: "Schulung",
    zeugnis: "Zeugnis",
    qualifikationsmatrix: "Qualifikationsmatrix",
    maschine: "Maschine",
    audit: "Audit",
    zeichnung: "Zeichnung",
    lieferung: "Lieferung",
    offeneSchulungen: "Offene Schulungen",
    schulungsmatrix: "Schulungsmatrix",
    atrLieferungen: "ATR-Lieferungen",
    kpiBewertung: "KPI-Bewertung",
    anmelden: "Anmelden",
  },
  uploads: {
    einleitung:
      "ERP-Exporte einlesen. Dieselbe Datei erneut hochzuladen ist gefahrlos: bestehende " +
      "Zeilen werden aktualisiert, nicht doppelt angelegt.",
    dateiWaehlen: "Datei auswählen",
    verarbeitet: "wird verarbeitet …",
    uebersprungen: (datei: string) => `Übersprungene Zeilen aus „${datei}“`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `${gesamt} Zeile(n) übernommen, ${fehler} übersprungen. Die übrigen Zeilen sind gespeichert.`,
    zeile: "Zeile",
    spalte: "Spalte",
    grund: "Grund",
    zuletzt: "Zuletzt hochgeladen",
    datei: "Datei",
    art: "Art",
    zeilen: "Zeilen",
    uebersprungenSpalte: "Übersprungen",
    status: "Status",
    zeitpunkt: "Zeitpunkt",
    nochNichts: "Noch nichts hochgeladen.",
    keineZeile: (datei: string) => `„${datei}“ enthielt keine gültige Zeile.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `„${datei}“ übernommen, ${fehler} Zeile(n) übersprungen.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `„${datei}“ übernommen: ${neu} neu, ${aktualisiert} aktualisiert.`,
    fehlgeschlagenMeldung: (meldung: string) => `Upload fehlgeschlagen: ${meldung}`,
    vollstaendig: "vollständig",
    teilweise: "teilweise",
    fehlgeschlagen: "fehlgeschlagen",
    arten: {
      umsatz: "Umsatz (Rechnungen und Gutschriften)",
      umsatzText: "Speist die Kachel Umsatz und den Umsatzverlauf. Gutschriften stehen negativ in der Datei.",
      auftraege: "Auftragseingang",
      auftraegeText: "Speist Ø Auftragswert, Aufträge gesamt und die Auswertung je Erfasser.",
      auftragspositionen: "Auftragspositionen",
      auftragspositionenText:
        "Trägt den Zieltermin je Position. Zusammen mit den Lieferscheinen ergibt sich daraus der Verzug.",
      lieferscheine: "Lieferscheine",
      lieferscheineText: "Trägt das Ist-Lieferdatum. Excel-Datei, eine Zeile je Lieferscheinposition.",
      wareneingaenge: "Wareneingänge",
      wareneingaengeText:
        "Bezugsgröße der Fehlerquote auf der Einkaufsseite. Die Warengruppe trennt Material-Lieferanten von Werkbänken.",
      acht_d: "8D-Berichte",
      acht_dText:
        "Audit-Befunde und Reklamationen in einer Datei. Das Level eines Befunds steht im Freitext und wird beim Einlesen abgeleitet.",
      lagerbewegungen: "Lagerbewegungen",
      lagerbewegungenText:
        "Verbrauch je Artikel für die Materialkostenquote. Ersetzt alle Zeilen im Datumsbereich der Datei.",
      lagerpreise: "Artikelpreise Lager",
      lagerpreiseText:
        "Stammdaten für die Lagerbewertung. Ersetzt die ganze Preisliste, nicht nur die enthaltenen Artikel.",
      pruefungen: "Qualitätsprüfung",
      pruefungenText:
        "Buchungen der Prüfung. Ersetzt alle Zeilen im Datumsbereich der Datei — von Hand abgewählte Buchungen in diesem Bereich zählen danach wieder mit.",
      liefertreue: "Liefertermintreue (Einkauf)",
      liefertreueText:
        "Speist die OTD-Quote im Einkauf. Eine Zeile je Lieferposition; das Ist-Lieferdatum bestimmt den Zeitraum.",
      kontakte: "Kontakte (Vertrieb)",
      kontakteText:
        "Erstkontakte und Besuche je Woche. Ersetzt alle Zeilen im Datumsbereich der Datei — ein zweiter Upload desselben Zeitraums verdoppelt nichts.",
      angebote: "Angebote",
      angeboteText:
        "Angebotsvolumen je Woche und Vertriebler. Angebote ohne Erfasser erscheinen in keinem Balken.",
      interessenten: "Interessenten",
      interessentenText:
        "Stammdaten der Interessenten. Ein erneut gespeicherter Interessent wandert mit seinem neuen Datum in eine andere Woche.",
    },
  },
  organigramm: {
    einleitung:
      "Aus Personio. Wer dort keinen Vorgesetzten hinterlegt hat, steht oben — das ist bei der " +
      "Geschäftsführung richtig und sonst ein Hinweis auf eine Lücke in den Stammdaten.",
    suchfeld: "Person, Position oder Abteilung",
    suchePlatzhalter: "Name, Position, Abteilung",
    standort: "Standort",
    alleStandorte: "Alle Standorte",
    personen: (anzahl: number) => `${anzahl} Personen`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} ohne Vorgesetzten`,
    niemand: "Niemand gefunden",
    niemandText: "Andere Suche, anderer Standort — oder der Personio-Abgleich lief noch nicht.",
    aufklappen: (name: string) => `${name} aufklappen`,
    zuklappen: (name: string) => `${name} zuklappen`,
    direkt: (anzahl: number) => `${anzahl} direkt`,
  },
  offeneSchulungen: {
    einleitung: "Wer was noch braucht. Nur aktive Schulungen; stillgelegte tauchen hier nicht mehr auf.",
    zumKatalog: "Zum Katalog",
    allesOffene: "Alles Offene",
    nieAbsolviert: "Nie absolviert",
    ueberfaellig: "Überfällig",
    wirdFaellig: "Wird fällig",
    suchen: "Person oder Schulung suchen",
    suchenAria: "Suchen",
    nichtsOffen: "Nichts offen",
    nichtsOffenText: "Alle aktiven Schulungen sind im Turnus — oder es ist noch nichts eingelesen.",
    eintraege: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "Eintrag" : "Einträge"}.`,
    person: "Person",
    schulung: "Schulung",
    bereich: "Bereich",
    zuletzt: "Zuletzt",
    faellig: "Fällig",
    stand: "Stand",
    nie: "nie absolviert",
    imTurnus: "im Turnus",
  },
  schulungsmatrix: {
    einleitung:
      "Alle Personen gegen alle Schulungen — die Übersicht für den Aushang und fürs Audit. " +
      "Wer noch gar keine Teilnahme hat, steht mit leerer Zeile darin; genau das ist die Lücke, " +
      "die man sucht.",
    wasOffenIst: "Was offen ist",
    katalog: "Katalog",
    suchfeld: "Person oder Abteilung",
    suchePlatzhalter: "Name, Abteilung, Personalnummer",
    bereich: "Bereich",
    alleBereiche: "Alle Bereiche",
    nurLuecken: "Nur Personen mit Lücken",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} von ${gesamt} Personen · ${schulungen} Schulungen`,
    niemand: "Keine Person passt",
    niemandText: "Andere Suche oder anderer Bereich — oder es ist wirklich niemand offen.",
    person: "Person",
    nichtZugewiesen: (person: string, schulung: string) =>
      `${person} · ${schulung}: nicht zugewiesen`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (fällig ${datum})`,
    offen: "offen",
    personio: "Personio",
    externGepflegt: "extern gepflegt",
    ohneTreffer: "ohne Personio-Treffer",
  },
  schulungen: {
    einleitung:
      "Der Katalog, sein Turnus und wer ihn erfüllt. Fälligkeiten werden aus letztem Termin und " +
      "Turnus gerechnet, nicht gespeichert.",
    dokumentenlauf: "Dokumentenlauf",
    bereich: "Bereich",
    neueSchulung: "Neue Schulung",
    beispiel: "z. B. Brandschutzunterweisung",
    anlegen: "Anlegen",
    wirdGelesen: "Wird gelesen …",
    uebersichtEinlesen: "Übersicht einlesen",
    einlesenAria: "Schulungsübersicht einlesen",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} Schulungen (${neu} neu), ${teilnahmen} Teilnahmen, davon ${zugeordnet} einer Person in Personio zugeordnet.`,
    ohneTreffer: "Ohne Personio-Treffer: ",
    ohneTrefferNach: ". Diese Zeilen kommen mit Personalnummer und Namen trotzdem mit.",
    wirdUebernommen: "Wird übernommen …",
    uebernehmen: "Übernehmen",
    abbrechen: "Abbrechen",
    keineSchulung: "Noch keine Schulung",
    keineSchulungText: "Leg eine an oder lies die Schulungsübersicht ein.",
    schulung: "Schulung",
    turnus: "Turnus",
    frist: "Frist (Tage)",
    verantwortlich: "Verantwortlich",
    offen: "Offen",
    aktiv: "Aktiv",
    nichtBerechenbar: "(nicht berechenbar)",
    zahlGroesserNull: "Bitte eine Zahl größer als 0.",
    nieKurz: (anzahl: number) => `${anzahl} nie`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} überfällig`,
    baldKurz: (anzahl: number) => `${anzahl} bald`,
    aktivSchalter: (name: string) => `${name} aktiv`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} heißt: für diese Person steht kein Termin in der Historie. ${bald} heißt: innerhalb der nächsten zwei Monate. Stand vom ${datum}.`,
  },
  schulung: {
    gibtEsNicht: "Diese Schulung gibt es nicht",
    gibtEsNichtText: "Vermutlich wurde sie entfernt.",
    ohneTurnus: "ohne Turnus",
    keineFaelligkeit: " — daraus lässt sich keine Fälligkeit rechnen",
    zumKatalog: "Zum Katalog",
    stammdaten: "Stammdaten",
    turnus: "Turnus",
    turnusBeispiel: "z. B. jährlich",
    turnusHinweis: "Der Text; die Monatszahl kommt aus dem Einlesen.",
    turnusMonate: "Turnus in Monaten",
    monateHinweis: "Leer heißt: keine Fälligkeit berechenbar.",
    verantwortlich: "Verantwortlich",
    beschreibung: "Beschreibung",
    fuerWen: "Für wen ist sie Pflicht?",
    kuerzel: "Abteilungskürzel",
    kuerzelHinweis: "Das feine Schema aus der Excel (NÄH, CUT, WVK …).",
    personioAbteilung: "Personio-Abteilung",
    personioHinweis: "Die grobe Abteilung, wie Personio sie führt.",
    entfernen: (was: string) => `${was} entfernen`,
    keine: "keine",
    ergaenzen: (was: string) => `${was} ergänzen`,
    hinzufuegen: "Hinzufügen",
    teilnahmen: "Teilnahmen",
    nochNiemand: "Noch niemand — lies die Schulungsübersicht ein oder trag jemanden ein.",
    person: "Person",
    abteilungKurz: "Abt.",
    erstschulung: "Erstschulung",
    zuletzt: "Zuletzt",
    faellig: "Fällig",
    stand: "Stand",
    keinTreffer: "Kein Treffer in Personio — die Zeile bleibt trotzdem erhalten",
    nichtInPersonio: "nicht in Personio",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "diese Teilnahme",
    personErgaenzen: "Person ergänzen",
    nameForm: "Nachname, Vorname",
  },
  kompetenzen: {
    einleitung:
      "Was eine Stelle verlangt und wie weit es erfüllt ist — je Bereich eine Matrix. " +
      "Eingelesen aus der Bereichsdatei, danach hier gepflegt.",
    zumDashboard: "Zum Personal-Dashboard",
    bereich: "Bereich",
    wirdGelesen: "Wird gelesen …",
    einlesen: "Bereichsdatei einlesen",
    vorschauKopf: (datei: string, bereich: string) => `${datei} — so sähe ${bereich} danach aus:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} Qualifikationen, ${personen} Personen, ${bewertungen} Bewertungen.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `${zugeordnet} von ${personen} Personen in Personio gefunden`,
    platzhalter: (anzahl: number) =>
      `, ${anzahl} ${anzahl === 1 ? "Platzhalterspalte" : "Platzhalterspalten"}`,
    ohneZuordnung: (namen: string) => ` Ohne Zuordnung: ${namen}.`,
    ersetztWarnung:
      "Die betroffenen Blätter werden vollständig ersetzt — hier gepflegte Änderungen gehen " +
      "dabei verloren.",
    wirdUebernommen: "Wird übernommen …",
    uebernehmen: "Übernehmen",
    abbrechen: "Abbrechen",
    keineMatrix: "Noch keine Matrix",
    keineMatrixText: "Lies eine Bereichsdatei ein — die Blätter darin werden je eine Matrix.",
    blatt: "Blatt",
    titelSpalte: "Titel",
    stand: "Stand",
    eingelesen: "Eingelesen",
    produktion: "Produktion",
    verwaltung: "Verwaltung",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    einleitung:
      "Aus Noten und Stichpunkten wird Zeugnissprache. Die Stammdaten werden beim Anlegen " +
      "abgeschrieben — ein ausgestelltes Zeugnis ändert sich nicht mehr, weil sich Personio ändert.",
    person: "Person",
    waehlen: "— wählen —",
    art: "Art",
    anlegen: "Anlegen",
    keines: "Noch kein Zeugnis",
    keinesText: "Wähl eine Person und die Zeugnisart — die Stammdaten kommen dann von selbst.",
    zeitraum: "Zeitraum",
    note: "Note",
    stand: "Stand",
    angelegt: "Angelegt",
    fertig: "fertig",
    entwurf: "Entwurf",
    qualifiziert: "Qualifiziertes Zeugnis",
    einfach: "Einfaches Zeugnis",
    zwischenzeugnis: "Zwischenzeugnis",
    ausbildungszeugnis: "Ausbildungszeugnis",
    praktikumszeugnis: "Praktikumszeugnis",
  },
  einarbeitung: {
    einleitung:
      "Was eine neue Person lernen muss und wer es ihr zeigt. Der Bogen entsteht aus den " +
      "Inhalten, die für ihre Abteilung hinterlegt sind.",
    bogenErzeugen: "Bogen erzeugen",
    person: "Person",
    waehlen: "— wählen —",
    wirdGebaut: "Wird gebaut …",
    einarbeitungsplan: "Einarbeitungsplan",
    keineInhalte: "Noch keine Inhalte hinterlegt — der Bogen bliebe leer.",
    abteilungVon: (abteilung: string) => `Abteilung ${abteilung}`,
    neuerInhalt: "Neuer Inhalt",
    beispiel: "z. B. Sicherheitsunterweisung an der Fräse",
    anlegen: "Anlegen",
    keinInhalt: "Noch kein Inhalt",
    keinInhaltText:
      "Leg fest, was eine neue Person lernen muss — und für welche Abteilungen das gilt.",
    inhalt: "Inhalt",
    ansprechpartner: "Ansprechpartner",
    bereich: "Bereich",
    fuerAbteilungen: "Für welche Abteilungen",
    abteilung: "Abteilung",
    bereichLeer: "Leer heißt: die Abteilung aus der Matrix einsetzen",
    entfernen: (was: string) => `${was} entfernen`,
    abteilungHinzu: "+ Abteilung",
    abteilungFuer: (inhalt: string) => `Abteilung für ${inhalt}`,
  },
  matrix: {
    gibtEsNicht: "Diese Matrix gibt es nicht",
    gibtEsNichtText: "Vermutlich wurde sie ersetzt.",
    blattStand: (blatt: string) => `Blatt ${blatt}`,
    stand: (datum: string) => ` · Stand ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} Qualifikationen, ${personen} Personen`,
    zurUebersicht: "Zur Übersicht",
    qualifikation: "Qualifikation",
    keineZeilen: "Diese Matrix hat noch keine Zeilen.",
    stufenBedeuten: "Was die Stufen bedeuten",
    erfuellungsgradHinweis:
      "Die zweite Zahl ist der Erfüllungsgrad in Prozent. Eine Zelle mit Anforderung und " +
      "weniger als 100 % ist eine Lücke und steht in Warnfarbe.",
    ergaenzen: "Ergänzen",
    neueQualifikation: "Neue Qualifikation",
    beispiel: "z. B. Drehmaschine",
    kategorie: "Kategorie",
    ohne: "ohne",
    zeile: "Zeile",
    neuePerson: "Neue Person",
    namensform: "Vorname Nachname",
    spalte: "Spalte",
    anforderungslevel: "Anforderungslevel",
    erfuellungsgrad: "Erfüllungsgrad in Prozent",
    stufe0: "nicht erforderlich",
    stufe1: "Grundkenntnisse",
    stufe2: "kann unter Anleitung arbeiten",
    stufe3: "arbeitet selbstständig",
    stufe4: "kann anleiten und schulen",
  },
  zeugnis: {
    gibtEsNicht: "Dieses Zeugnis gibt es nicht",
    gibtEsNichtText: "Vermutlich wurde es gelöscht.",
    durchschnitt: (wert: string) => ` · Durchschnitt ${wert}`,
    zurUebersicht: "Zur Übersicht",
    zeugnisVon: (name: string) => `Zeugnis ${name}`,
    stammdaten: "Stammdaten",
    stammdatenHinweis:
      "Abgeschrieben beim Anlegen. Änderungen hier gelten nur für dieses Zeugnis — Personio " +
      "bleibt unberührt.",
    name: "Name",
    personalnummer: "Personalnummer",
    abteilung: "Abteilung",
    taetigkeit: "Tätigkeit",
    eintritt: "Eintritt",
    austritt: "Austritt",
    geburtsdatum: "Geburtsdatum",
    ausstellungsdatum: "Ausstellungsdatum",
    ohneNamen: "Ohne Namen geht es nicht.",
    anrede: "Anrede",
    frau: "Frau",
    herr: "Herr",
    anredeHinweis: "Steuert Anrede und Pronomen im Text.",
    art: "Art",
    anlass: "Anlass",
    anlassBeispiel: "z. B. eigener Wunsch",
    fuehrungskraft: "Führungskraft",
    fuehrungskraftHinweis: "Führungskraft — blendet die Dimension „Führung“ ein",
    bewertung: "Bewertung",
    bewertungHinweis:
      "Schulnoten von 1 bis 4. Aus dem Durchschnitt folgt die Zufriedenheitsformel — nicht " +
      "umgekehrt.",
    fachwissen: "Fachwissen",
    auffassungsgabe: "Auffassungsgabe",
    arbeitsweise: "Arbeitsweise",
    belastbarkeit: "Belastbarkeit",
    arbeitserfolg: "Arbeitserfolg",
    sozialverhalten: "Sozialverhalten",
    fuehrung: "Führung",
    aufgaben: "Aufgaben (Stichpunkte)",
    aufgabenHinweis: "Eine Aufgabe je Zeile — daraus wird die Aufzählung im Zeugnis.",
    kompetenzen: "Besondere Kompetenzen",
    kompetenzenHinweis: "Fließt in die Leistungsbeurteilung ein.",
    erfolge: "Besondere Erfolge",
    erfolgeHinweis: "Projekte, Auszeichnungen, messbare Ergebnisse.",
    text: "Text",
    baut: "Baut …",
    ausBausteinen: "Aus Bausteinen",
    formuliert: "Formuliert …",
    mitKi: "Mit KI",
    textHinweis:
      "Der Baukasten schreibt ohne Netz und ohne KI. Die KI formuliert freier — an sie gehen nur " +
      "Anrede, Rolle, Abteilung, Dauer, Noten und die Freitexte oben. Name, Geburtsdatum und " +
      "Personalnummer verlassen den Server nicht.",
    nochKeinText: "Noch kein Text. Vergib die Noten und lass ihn bilden.",
    fertigSchalter: "Zeugnis fertig",
    fertigHinweis: "Fertig — nicht mehr in Arbeit",
    unterschriftenFehler: (meldung: string) =>
      `Die Unterschriften konnten nicht ermittelt werden (${meldung}).`,
    darunterSteht: "Darunter steht",
    fachlich: "Fachlich",
    personalwesen: "Personalwesen",
    niemandHinterlegt: "— niemand hinterlegt —",
    unterschriftFehlt:
      "Eine Unterschrift fehlt. Hinterlegen unter Einstellungen → Zeugnisse, oder in Personio " +
      "den Vorgesetzten pflegen.",
    ausPersonio: "aus Personio",
    ausEinstellungen: "aus den Einstellungen",
    nichtHinterlegt: "nicht hinterlegt",
    einleitung: "Einleitung",
    taetigkeitsbeschreibung: "Tätigkeitsbeschreibung",
    leistungsbeurteilung: "Leistungsbeurteilung",
    schlussformel: "Schlussformel",
    hinweisDeutsch: "Das Zeugnis selbst wird auf Deutsch geschrieben.",
  },
  dokumentenlauf: {
    einleitung:
      "Blätter mit QR-Code: erzeugen, aushändigen, ausgefüllt zurücknehmen, prüfen. Der QR " +
      "ordnet den Scan wieder zu — unabhängig davon, wie die Datei heißt.",
    formblatt: "Formblatt",
    fuerWen: "Für wen",
    personWaehlen: "— Person wählen —",
    erzeugt: "Erzeugt …",
    blattErzeugen: "Blatt erzeugen",
    standFilter: "Stand:",
    alle: "Alle",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} von ${gesamt}`,
    keinVorgang: "Kein Vorgang",
    keinVorgangText:
      "Oben ein Blatt erzeugen — es bekommt einen QR-Code und wird von da an verfolgt.",
    person: "Person",
    kennung: "Kennung",
    stand: "Stand",
    vollstaendigSpalte: "Vollständig",
    blatt: "Blatt",
    scan: "Scan",
    prueft: "Prüft …",
    scanFuer: (name: string) => `Scan für ${name} hochladen`,
    zu: "zu",
    details: "Details",
    nochNichtGeprueft: "— noch nicht geprüft",
    vollstaendig: "vollständig",
    unvollstaendig: "unvollständig",
    umkehren: "Urteil umkehren — die Messung sieht nur, ob Tinte im Feld ist",
    pruefung: "Prüfung",
    qrGelesen: "— QR gelesen",
    keinQr: "— kein QR gefunden, Felder nicht zuzuordnen",
    nachweise: "Nachweise",
    keineNachweise: "Noch keine hinterlegt.",
    welcheZeile: "Zu welcher Zeile? (freiwillig)",
    laedt: "Lädt …",
    nachweis: "Nachweis",
    nachweisHoch: "Nachweis hochladen",
    erstellt: "erstellt",
    uebergeben: "übergeben",
    zurueck: "zurück",
    geprueft: "geprüft",
    einarbeitungsplan: "Einarbeitungsplan",
    schulungsnachweis: "Schulungsnachweis",
  },
  onboarding: {
    einleitung:
      "Wer neu ist und welche Schulungen die Anforderungsmatrix für ihn verlangt. Der Plan wird " +
      "nicht gespeichert, sondern gerechnet — ändert sich die Matrix, ändert sich der Plan.",
    nichtsGefehlt: "Es fehlte nichts.",
    angelegt: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "Schulung" : "Schulungen"} angelegt.`,
    neu90: "Neu (letzte 90 Tage)",
    alle: "Alle",
    personen: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "Person" : "Personen"}`,
    keineEintritte: "Keine Eintritte",
    keineEintritteText: "Sobald jemand mit Eintrittsdatum aus Personio kommt, steht er hier.",
    person: "Person",
    abteilung: "Abteilung",
    position: "Position",
    eintritt: "Eintritt",
    uebergabe: "Übergabe",
    nichtInPersonio: "nicht in Personio",
    hierGesetzt: "Hier gesetzt — übersteuert Personio",
    ausPersonio: "Aus Personio",
    vermerken: "Vermerken",
    paketTitel: "Einarbeitungsplan und Schulungsübersicht als ein PDF",
    paket: "Paket",
    uebersichtTitel: "Nur die Schulungsübersicht (Formblatt 71)",
    uebersicht: "Übersicht",
    planZu: "Plan zu",
    plan: "Plan",
    schulungsplan: "Schulungsplan",
    fehlendeAnlegen: "Fehlende anlegen",
    wirdGerechnet: "wird gerechnet …",
    bruecke: "Position → Abteilungskürzel",
    brueckeHinweis:
      "Die Brücke zwischen Personio und der feinen Ebene der Anforderungsmatrix. Ohne Eintrag " +
      "greift die feine Ebene für diese Position nicht — der Plan sagt das dann ausdrücklich.",
    kuerzel: "Kürzel",
    positionBeispiel: "z. B. CNC Fräser",
    kuerzelBeispiel: "CNC",
    zuordnen: "Zuordnen",
    ohnePersonio: "Person ohne Personio",
    ohnePersonioHinweis:
      "Für Eintritte, die noch nicht im Abgleich stehen — oder gar nicht dorthin gehören.",
    name: "Name",
    anlegen: "Anlegen",
    kuerzelFehlt: (position: string) =>
      `Für die Position ${position}ist kein Abteilungskürzel hinterlegt. Die feine Ebene der ` +
      "Anforderungsmatrix greift für diese Person deshalb nicht — es fehlen möglicherweise " +
      "Pflichtschulungen.",
    matrixVerlangtNichts: "Die Anforderungsmatrix verlangt für diese Abteilung nichts.",
    schulung: "Schulung",
    bereich: "Bereich",
    turnus: "Turnus",
    pflichtUeber: "Pflicht über",
    stand: "Stand",
    ueberAbteilung: "Abteilung",
    ueberKuerzel: "Kürzel",
    vorhanden: "vorhanden",
    fehlt: "fehlt",
  },
  audit: {
    einleitung:
      "Audits von der Planung bis zum Abschluss. Jede Statusänderung steht im Verlauf — " +
      "geschrieben von der Datenbank, nicht von der Maske, und danach unveränderlich.",
    zuKennzahlen: "Zu den Kennzahlen",
    nummer: "Nummer",
    nummerBeispiel: "A-2026-01",
    titel: "Titel",
    titelBeispiel: "EN 9100 Systemaudit",
    art: "Art",
    intern: "intern",
    extern: "extern",
    phasenvorlage: "Phasenvorlage",
    ohne: "ohne",
    anlegen: "Anlegen",
    keinAudit: "Noch kein Audit",
    keinAuditText: "Leg eines an — mit einer Phasenvorlage bringt es seine Checkliste gleich mit.",
    laufen: (laufend: number, gesamt: number) => `${laufend} von ${gesamt} laufen noch.`,
    status: "Status",
    fortschritt: "Fortschritt",
    naechsterTermin: "Nächster Termin",
    ueberfaellig: (anzahl: number) => `${anzahl} überfällig`,
    geplant: "Geplant",
    inVorbereitung: "In Vorbereitung",
    inDurchfuehrung: "In Durchführung",
    berichtet: "Berichtet",
    massnahmenOffen: "Maßnahmen offen",
    abgeschlossen: "Abgeschlossen",
    verschoben: "Verschoben",
    abgesagt: "Abgesagt",
    phaseOffen: "Offen",
    phaseInArbeit: "In Arbeit",
    phaseErledigt: "Erledigt",
    phaseNichtZutreffend: "Nicht zutreffend",
    system: "System",
    prozess: "Prozess",
    produkt: "Produkt",
    lieferant: "Lieferant",
  },
  wartung: {
    einleitung:
      "Maschinen und ihre wiederkehrenden Wartungsaufgaben. Der Nachweis entsteht als Bogen zum " +
      "Aushängen — je Halbjahr, mit einer Spalte pro Kalenderwoche.",
    zuKennzahlen: "Zu den Kennzahlen",
    neueMaschine: "Neue Maschine",
    beispiel: "z. B. Fräse 3",
    anlegen: "Anlegen",
    keineMaschine: "Noch keine Maschine",
    keineMaschineText: "Leg eine Maschine an und hinterlege ihre Wartungsaufgaben.",
    maschine: "Maschine",
    inventarnummer: "Inventar-Nr.",
    standort: "Standort",
    verantwortlich: "Verantwortlich",
    status: "Status",
    aktiv: "aktiv",
    stillgelegt: "stillgelegt",
  },
  sensoren: {
    einleitung:
      "Temperatur und Luftfeuchte, alle fünf Minuten abgefragt. Ein Wert außerhalb der " +
      "eingestellten Grenzen steht in Warnfarbe.",
    misst: "Misst …",
    jetztMessen: "Jetzt messen",
    keinGeraet: "Kein Gerät eingerichtet",
    keinGeraetText: "Sensoren werden in den Einstellungen angelegt — Rechner, Kennung und Community.",
    verlauf: "Verlauf",
    stunden: (n: number) => `${n} h`,
    tage: (n: number) => `${n} Tage`,
    temperatur: "Temperatur",
    luftfeuchte: "Luftfeuchte",
    zuletzt: (zeit: string) => `Zuletzt ${zeit}`,
    keinMesswert: "Noch kein Messwert.",
    nichtsGemessen: "In diesem Zeitraum wurde nichts gemessen.",
    frisch: "aktuell",
    verzoegert: "verzögert",
    offline: "offline",
    unbekannt: "noch nichts gemessen",
  },
  hilfe: {
    einleitung:
      "Was die Plattform kann, wie die Zahlen zustande kommen und was zu tun ist, wenn etwas " +
      "nicht stimmt.",
    nurDeutsch: "",
    suchen: "In der Hilfe suchen",
    nichtsGefunden:
      "Nichts gefunden. Steht etwas nicht in der Hilfe, sag es über den Melden-Knopf unten rechts.",
    alleThemen: "← Alle Themen",
  },
  meldungen: {
    stand: (offen: number) => `Was aus den Ansichten gemeldet wurde. ${offen} offen`,
    neuSeit: (anzahl: number) => ` · ${anzahl} neu seit dem letzten Aufruf`,
    nichtsGemeldet: "Nichts gemeldet",
    nichtsGemeldetText:
      "Über den Knopf unten rechts kann jede angemeldete Person melden, was auf einer Seite " +
      "nicht stimmt.",
    unbekannt: "unbekannt",
    bild: "Bild",
    status: "Status",
    offen: "offen",
    erledigt: "erledigt",
    meldung: "Meldung",
    aufnahme: "Aufnahme der Seite",
  },
  auditAnsicht: {
    gibtEsNicht: "Dieses Audit gibt es nicht",
    gibtEsNichtText: "Vermutlich wurde es entfernt.",
    internesAudit: "Internes Audit",
    externesAudit: "Externes Audit",
    prioritaet: (stufe: string) => ` · Priorität ${stufe}`,
    erledigt: (prozent: number) => ` · ${prozent} % erledigt`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} überfällig`,
    zurUebersicht: "Zur Übersicht",
    status: "Status",
    stammdaten: "Stammdaten",
    titel: "Titel",
    bereich: "Bereich",
    leitenderAuditor: "Leitender Auditor",
    auditteam: "Auditteam",
    geplantVon: "Geplant von",
    geplantBis: "Geplant bis",
    prioritaetFeld: "Priorität",
    niedrig: "niedrig",
    mittel: "mittel",
    hoch: "hoch",
    auditziel: "Auditziel",
    kategorien: "Kategorien",
    kategorienHinweis:
      "Ein Audit ist oft mehreres zugleich — das interne Programm fährt System und Prozess in " +
      "einem Termin. Deshalb Mehrfachauswahl und keine einzelne Angabe.",
    normbezug: "Normbezug",
    normmatrixLeer: "Die Normmatrix ist leer — sie wird in den Einstellungen gepflegt.",
    nichtGeprueft: "* noch nicht gegen den konsolidierten Normtext geprüft.",
    phasen: "Phasen",
    keinePhasen: "Keine Phasen — dieses Audit wurde ohne Vorlage angelegt.",
    phase: "Phase",
    verantwortlich: "Verantwortlich",
    faellig: "Fällig",
    erledigtAm: "Erledigt am",
    phaseErgaenzen: "Phase ergänzen",
    phaseBeispiel: "z. B. Nachaudit",
    verlauf: "Verlauf",
    verlaufHinweis:
      "Geschrieben von der Datenbank, nicht von dieser Maske — und danach weder änderbar noch " +
      "löschbar.",
    nichtsGeschehen: "Noch nichts geschehen.",
    warumEntfaellt: "Warum entfällt diese Pflichtphase?",
    uebernehmen: "Übernehmen",
    abbrechen: "Abbrechen",
    angelegt: "angelegt",
    geaendert: "geändert",
    geloescht: "gelöscht",
    uebersprungen: "übersprungen",
  },
  maschine: {
    gibtEsNicht: "Diese Maschine gibt es nicht",
    gibtEsNichtText: "Sie wurde vermutlich gelöscht.",
    zurUebersicht: "Zur Übersicht",
    stammdaten: "Stammdaten",
    name: "Name",
    inventarnummer: "Inventar-Nr.",
    standort: "Standort",
    hersteller: "Hersteller",
    modell: "Modell",
    verantwortlich: "Verantwortlich",
    status: "Status",
    aktiv: "aktiv",
    stillgelegt: "stillgelegt",
    notizen: "Notizen",
    wartungsaufgaben: "Wartungsaufgaben",
    jahr: "Jahr",
    halbjahr: "Halbjahr",
    erstesHalbjahr: "KW 1–26",
    zweitesHalbjahr: "KW 27–52",
    wirdGebaut: "Wird gebaut …",
    nachweisbogen: "Nachweisbogen",
    neueAufgabe: "Neue Aufgabe",
    aufgabeBeispiel: "z. B. Ölstand prüfen",
    intervall: "Intervall",
    wochen: "Wochen",
    keineAufgabe: "Noch keine Aufgabe — der Bogen bliebe leer.",
    aufgabe: "Aufgabe",
    dateien: "Dateien",
    planHinterlegen: "Plan hinterlegen",
    nachweisAblegen: "Nachweis ablegen",
    dateienHinweis: "Der Herstellerplan und die zurückgescannten, unterschriebenen Bögen.",
    keineDatei: "Noch keine Datei.",
    plan: "Plan",
    nachweis: "Nachweis",
    laedt: "Lädt …",
    taeglich: "Täglich",
    woechentlich: "Wöchentlich",
    monatlich: "Monatlich",
    quartalsweise: "Quartalsweise",
    alleNWochen: "Alle N Wochen",
    alleNWochenZahl: (wochen: number) => `Alle ${wochen} Wochen`,
  },
  atr: {
    einleitung:
      "Der Teilekatalog ist die Grundlage: aus ihm holt ein Lieferschein Bezeichnung, Zeichnung " +
      "und Gewicht. Gefunden wird über die Teilenummer ohne Beiwerk — nur die Ziffern zählen.",
    zuLieferungen: "Zu den Lieferungen",
    teilAnlegen: "Teil von Hand anlegen",
    teilBeispiel: "Teilenummer, z. B. VR-1234-56",
    anlegen: "Anlegen",
    wirdGelesen: "Wird gelesen …",
    mappeEinlesen: "Referenzmappe einlesen",
    suchen: "Suchen",
    suchePlatzhalter: "Teilenummer, Bezeichnung oder Zeichnung",
    nichtsGefunden: "Nichts gefunden",
    katalogLeer: "Der Katalog ist leer",
    keinTeil: "Kein Teil passt zu dieser Suche.",
    katalogLeerText: "Eine Referenzmappe einlesen oder ein Teil von Hand anlegen.",
    teilenummer: "Teilenummer",
    bezeichnung: "Bezeichnung",
    zeichnung: "Zeichnung",
    gewicht: "Gewicht kg",
    kategorie: "Kategorie",
    nurErste: "Nur die ersten 500 Treffer — bitte enger suchen.",
  },
  lieferungen: {
    einleitung:
      "Ein Lieferschein wird eingelesen, gegen den Teilekatalog abgeglichen und als Entwurf " +
      "abgelegt. Nach der Durchsicht wird er freigegeben.",
    zumKatalog: "Zum Teilekatalog",
    wirdGelesen: "Wird gelesen …",
    einlesen: "Lieferschein einlesen",
    laeuft: "Läuft …",
    eingangDurchsehen: "Eingang durchsehen",
    berichtNummer: (nr: string) => ` · Nr. ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} Positionen, ${zugeordnet} im Katalog gefunden.`,
    keinLieferschein: "Noch kein Lieferschein",
    keinLieferscheinSchreiben: "Ein Lieferschein-PDF einlesen — danach steht er hier zur Durchsicht.",
    keinLieferscheinLesen: "Sobald ein Lieferschein eingelesen ist, steht er hier.",
    lieferschein: "Lieferschein",
    datum: "Datum",
    programm: "Programm",
    msn: "MSN",
    status: "Status",
    entwurf: "Entwurf",
    freigegeben: "freigegeben",
  },
  durchsicht: {
    nichtGefunden: "Lieferung nicht gefunden.",
    freigeben: "Freigeben",
    zuruecknehmen: "Freigabe zurücknehmen",
    wirdErzeugt: "Wird erzeugt …",
    dokumenteErzeugen: "Dokumente erzeugen",
    kopfdaten: "Kopfdaten",
    atrNummer: "ATR-Nummer",
    containernummer: "Containernummer",
    satzTitel: "Satzbezeichnung",
    programm: "Programm",
    msn: "MSN",
    bereich: "Bereich",
    wiegedatum: "Wiegedatum",
    pruefdatum: "Prüfdatum",
    qsUnterschrift: "QS-Unterschrift",
    hoechstgewicht: "Höchstgewicht kg",
    positionen: "Positionen",
    pos: "Pos",
    menge: "Menge",
    seriennummern: "Seriennummern",
    nichtImKatalog: "nicht im Katalog",
    festHinweis:
      "Die Lieferung ist freigegeben; die Positionen sind fest. Die Datenbank weist eine " +
      "Änderung ab — die Freigabe lässt sich oben zurücknehmen.",
  },
  fair: {
    einleitung:
      "Erstmusterprüfung: eine Zeichnung hochladen und zu jedem zu prüfenden Maß einen " +
      "nummerierten Ballon setzen. Die Nummern vergibt die Datenbank und hält sie lückenlos.",
    bezeichnungFrei: "Bezeichnung (leer = Dateiname)",
    beispiel: "z. B. Welle 12×40, Zeichnung 4711",
    wirdGeladen: "Wird geladen …",
    zeichnungWaehlen: "Zeichnung wählen",
    keineZeichnung: "Noch keine Zeichnung",
    keineZeichnungSchreiben: "PDF oder Bild hochladen — danach lassen sich die Maße ballonieren.",
    keineZeichnungLesen: "Sobald eine Zeichnung hochgeladen ist, steht sie hier.",
    bezeichnung: "Bezeichnung",
    teilenummer: "Teilenummer",
    kunde: "Kunde",
    hochgeladen: "Hochgeladen",
    pruefliste: "Prüfliste",
    einMass: "1 Maß",
    masse: (anzahl: number) => `${anzahl} Maße`,
    kopieren: "Kopieren",
    csv: "CSV",
    keinMass: "Noch kein Maß markiert.",
    nr: "Nr",
    seite: "Seite",
    wert: "Wert",
    wertBeispiel: "z. B. 12,0 h7",
    wertZu: (nummer: number) => `Wert zu Nummer ${nummer}`,
    nachOben: (nummer: number) => `Nummer ${nummer} nach oben`,
    nachUnten: (nummer: number) => `Nummer ${nummer} nach unten`,
    nummer: (nummer: number) => `Nummer ${nummer}`,
    drehen: "Ansicht drehen",
    verkleinern: "Verkleinern",
    vergroessern: "Vergrößern",
    einpassen: "Einpassen",
    zeichnung: "Zeichnung",
    ladefehler: "Die Zeichnung ließ sich nicht laden.",
  },
  kennzahlenHub: {
    titel: "KPI-Dashboard",
    einleitung: "Kennzahlen je Fachbereich. Die Daten kommen aus den ERP-Exporten unter Uploads.",
    nochNicht: "noch nicht übernommen",
    bereiche: {
      vertrieb: "Umsatz, Auftragswert, Kundenanteil",
      personal: "Belegschaft, Fluktuation, Krankenstand — eigene Berechtigung",
      qualitaet: "Audit-Findings und Reklamationsquote",
      finanzen: "Material- und Personalkostenquote",
      einkauf: "Liefertermintreue der Lieferanten",
      produktion: "Verzug, überfällige Aufträge",
      bewertung: "Kommentare und Maßnahmen zu jeder Kennzahl",
    },
  },
  erklaerung: {
    frage: (titel: string) => `Wie wird „${titel}“ gerechnet?`,
    knopf: "Rechenweg",
    untertitel: "So wird gerechnet",
    ganzeSeite: "Ganze Hilfeseite",
  },
};

export type Texte = typeof de;
