import type { Texte } from "@/texte/de";

/**
 * The English strings. Typed as `Texte`, so a missing or renamed key is a
 * compile error and never an empty box at runtime.
 *
 * Page names in `pfad.seiten` follow the paths, not the German words: a link
 * that says "Training" has to lead to the page the German one calls
 * „Schulungen".
 */
export const en: Texte = {
  kopf: {
    uebersicht: "To the overview",
    hilfe: "Help",
    einstellungen: "Settings",
    abmelden: "Sign out",
    sprache: "Language",
    erscheinungsbild: "Appearance",
    hell: "Light",
    dunkel: "Dark",
    system: "Follow the system",
    meldungenLeer: "Reports — nothing new",
    meldungen: (anzahl: number) => `Reports — ${anzahl} not yet looked at`,
    massnahmenLeer: "Actions — none open",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Actions — ${offen} open, ${ueberfaellig} of them overdue`
        : `Actions — ${offen} open`,
  },
  pfad: {
    aria: "Path",
    start: "Home",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "Deliveries",
      "/einstellungen": "Settings",
      "/fair": "FAIR",
      "/hilfe": "Help",
      "/hr": "People",
      "/hr/dokumente": "Document run",
      "/hr/einarbeitung": "Induction",
      "/hr/kompetenzen": "Skills",
      "/hr/onboarding": "Onboarding",
      "/hr/organigramm": "Org chart",
      "/hr/schulungen": "Training",
      "/hr/schulungen/matrix": "Matrix",
      "/hr/schulungen/offen": "Outstanding",
      "/hr/zeugnisse": "References",
      "/kpi": "Metrics",
      "/kpi/bewertung": "Review",
      "/kpi/einkauf": "Purchasing",
      "/kpi/finanzen": "Finance",
      "/kpi/produktion": "Production",
      "/kpi/qualitaet": "Quality",
      "/kpi/vertrieb": "Sales",
      "/newsletter": "Newsletter",
      "/newsletter/redaktion": "Editing",
      "/platform/feedback": "Reports",
      "/produktion": "Production",
      "/qualitaet": "Quality",
      "/sensoren": "Sensors",
      "/signage": "Digital signage",
      "/signage/devices": "Devices",
      "/signage/media": "Media",
      "/signage/pair": "Pairing",
      "/signage/playlists": "Playlists",
      "/signage/schedules": "Schedules",
      "/uploads": "Uploads",
    },
  },
  start: {
    titel: "Apps",
    verweigert: (name: string) => `You are not allowed to open “${name}”.`,
    keineApp: "No app has been assigned to your account yet. Please contact platform admin.",
  },
  anmeldung: {
    titel: "ACM Platform",
    aufforderung: "Sign in with your account.",
    email: "E-mail",
    passwort: "Password",
    knopf: "Sign in",
    laeuft: "Signing in …",
  },
  allgemein: {
    laedt: "Loading …",
  },
  zeitraum: {
    monat: "This month",
    quartal: "This quarter",
    jahr: "This year",
    alles: "All time",
    frei: "Pick a period",
    von: "from",
    bis: "to",
    vonAria: "Period from",
    bisAria: "Period to",
    verdreht: "The end is before the start.",
  },
  vergleich: {
    vorperiode: "vs. previous period",
    vormonat: "vs. previous month",
    vorquartal: "vs. previous quarter",
    vorjahr: "vs. last year",
    zeitraumDavor: "vs. the period before",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Data as of ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Data incomplete — ${fehlend} ${anzahl === 1 ? "is missing" : "are missing"}`,
    heute: "today",
    gestern: "yesterday",
    vorTagen: (tage: number) => `${tage} days ago`,
    nie: "never",
    arten: {
      umsatz: "Revenue",
      auftraege: "Orders",
      angebote: "Quotes",
      interessenten: "Leads",
      kontakte: "Contacts",
      liefertreue: "Delivery reliability",
      lagerbewegungen: "Stock movements",
      lagerpreise: "Stock prices",
      auftragspositionen: "Order lines",
      lieferscheine: "Delivery notes",
      pruefungen: "Inspections",
      acht_d: "8D reports",
      wareneingaenge: "Goods receipts",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `The metrics could not be loaded: ${meldung}`,
    keineDatenTitel: "No data for this period",
    keineDatenVor: "Upload the ERP exports under ",
    keineDatenNach: ", or pick a wider period.",
    keineWerte: "no values in this period",
    laedt: "loading …",
    jeTag: "by day",
    jeWoche: "by week",
    jeMonat: "by month",
  },
  vertrieb: {
    umsatz: "Revenue",
    umsatzHinweis: "Invoices minus credit notes",
    auftragswert: "Avg. order value",
    ueberNull: "Orders above €0",
    auftraege: "Orders total",
    verlauf: "Revenue over time",
    verlaufHinweis: (takt: string) => `${takt}, credit notes deducted`,
    kundenanteil: "Customer share of revenue",
    kunde: "Customer",
    anteil: "Share",
    uebrige: "Others",
    jeErfasser: "Orders by sales rep",
    erfasser: "Sales rep",
    anzahl: "Orders",
    summe: "Total",
  },
  aktivitaet: {
    titel: "Sales activity",
    jeWoche: (von: string, bis: string) => `by calendar week, ${von} to ${bis}`,
    ladeFehler: (meldung: string) => `Sales activity could not be loaded: ${meldung}`,
    leer: "No contacts, quotes or leads in this period.",
    kw: (woche: string) => `W${woche}`,
    ziel: (wert: string) => `Target ${wert} / week`,
    erstkontakte: "First contacts",
    erstkontakteHinweis: "completed contacts of type ERS",
    besuche: "Visits",
    besucheHinweis: "on site and online together",
    interessenten: "Leads",
    interessentenHinweis: "newly recorded, no rep assigned",
    angebote: "Quotes",
    angeboteHinweis: "total of quotes written",
    auftragseingang: "Orders received",
    auftragseingangHinweis: "cancellations netted off",
  },
  einkauf: {
    einleitung: "Supplier delivery reliability. Counted is what arrived within the period.",
    keineDaten: "No delivery lines for this period",
    ladeVor: "Upload the delivery-reliability export under ",
    ladeNach: ".",
    otd: "OTD rate",
    otdHinweis: (ziel: string) => `Target ${ziel} · on time means delay ≤ 0`,
    puenktlich: "Lines on time",
    gesamt: "Lines total",
    verzugSchnitt: "Avg. delay",
    verzugHinweis: "Lines without a delay value are left out here",
    verlauf: "OTD rate over time",
    verlaufHinweis: "Gaps are periods without delivery lines.",
    ladenhueter: "Stock on order — slow movers",
    kapital: (wert: string) => `Capital tied up: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Stock items with no movement for at least ${tage} days, highest value first. ` +
      "As of today — the period above does not apply here, because a stock level is not a period.",
    artikel: "Item",
    bezeichnung: "Description",
    bestand: "Quantity",
    liegtSeit: "Lying since",
    stueckpreis: "Unit price",
    wert: "Value",
    positionen: "Delivery lines",
    positionenHinweis: "Longest delay first, lines without a delay value on top. At most 500 rows.",
    auftrag: "Order",
    lieferant: "Supplier",
    zieltermin: "Due date",
    geliefert: "Delivered",
    verzug: "Delay",
  },
  produktion: {
    einleitung: "Orders running late. An order is counted once its outcome is settled.",
    keineDaten: "No order with a settled outcome in this period",
    ladeVor: "Upload the order lines and the delivery notes under ",
    ladeNach:
      ". Both are needed: one file carries the due date, the other the actual date.",
    quote: "Delay rate",
    quoteHinweis: (ziel: string) => `At most ${ziel}`,
    inVerzug: "Orders running late",
    gesamt: "Orders total",
    gesamtHinweis: "excluding open orders not yet due",
    verzugSchnitt: "Avg. delay",
    verzugHinweis: "orders on time count as negative",
    verlauf: "Delay rate over time",
    verlaufHinweis: "By due date. Gaps are periods without counted orders.",
    ziellinie: "Target",
    liste: "Orders running late",
    listeHinweis:
      "Longest delay first. For open orders it keeps growing daily. At most 500 rows.",
    auftrag: "Order",
    kunde: "Customer",
    stand: "State",
    zieltermin: "Due date",
    geliefert: "Delivered",
    verzug: "Delay",
    verspaetet: "delivered late",
    offen: "open, overdue",
  },
  finanzen: {
    einleitung: "Material and personnel costs against invoiced revenue.",
    keineDatenVor:
      "Three files are needed: the stock movements for consumption, the goods receipts for " +
      "the prices and the revenue as the reference. All three live under ",
    keineDatenNach: ".",
    materialquote: "Material cost ratio",
    materialquoteHinweis: "Material costs / revenue",
    hoechstens: (ziel: string) => `At most ${ziel}`,
    materialkosten: "Material costs",
    umsatz: "Revenue",
    personalquote: "Personnel cost ratio",
    brauchtZeitraum: "needs a period",
    personalHinweis: (kosten: string, personen: string) => `${kosten} for ${personen} people`,
    ohnePreis: "Items without a price",
    ohnePreisHinweis: "consumed, but not valued",
    jeAbteilung: "Personnel costs by department",
    abteilung: "Department",
    personen: "People",
    kosten: "Costs",
    anteil: "Share",
    verlauf: "Material cost ratio over time",
    verlaufHinweis: "Gaps are periods without revenue — without a reference there is no ratio.",
    ziellinie: "Target",
    verbrauch: "Material consumption by item",
    verbrauchHinweis:
      "Highest cost first. Items without a price come last — they do not enter the ratio. " +
      "At most 500 rows.",
    artikel: "Item",
    bezeichnung: "Description",
    menge: "Consumption",
    stueckpreis: "Unit price",
    keinPreis: "no price",
  },
  qualitaet: {
    einleitung: "Audit findings, complaint rate and inspected quantities.",
    auditart: "Audit type:",
    keineArt: "No audit type selected. Pick at least one, otherwise there is nothing to count.",
    keineDaten: "No audit findings for this period",
    ladeVor: "Upload the 8D export under ",
    ladeNach: ".",
    behoerde: "Authority",
    extern: "External",
    intern: "Internal",
    kunde: "Customer",
    level1: "Audit findings level 1",
    level2: "Audit findings level 2",
    ohneLevel: "No level recognised",
    ohneLevelHinweis: "counted in no tile",
    hoechstens: (ziel: number) => `At most ${ziel}`,
    auditVerlauf: "Audit findings over time",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) =>
      `Share of quantity without complaint. Reference: ${bezug}.`,
    fehlerquote: (quote: string) => `Defect rate: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Defect rate: ${quote} · target ${ziel}`,
    reklamiert: "Quantity complained about",
    bezugsmenge: "Reference quantity",
    bezugsmengeNull: "without it there is no rate",
    mehrAlsBezogen:
      "More has been complained about than was received. The calculation cannot resolve this: " +
      "numerator and denominator come from different files with their own date fields. Check " +
      "whether the reference file for this period was uploaded in full.",
    reklKunde: "Customer",
    reklIntern: "internal",
    reklLieferant: "Material suppliers",
    reklWerkbank: "Workbenches",
    bezugKunde: "quantity delivered",
    bezugIntern: "quantity delivered",
    bezugLieferant: "goods receipts excluding services",
    bezugWerkbank: "goods receipts of product groups DIENST and SERVIC",
    mengeGesamt: "quantity reported",
    mengeAkzeptiert: "quantity accepted",
    onQualityBezug: (menge: string) => `On Quality (reference ${menge})`,
    ziellinie: "Target",
    geprueft: "Products inspected",
    geprueftHinweis: (pruefer: string, tage: string) =>
      `Quantity per inspector and inspection day. The divisor is the same for both sizes: ${pruefer} inspectors on ${tage} days.`,
    gross: "Large products",
    klein: "Small products",
    mindestens: (ziel: number) => `At least ${ziel} per day and inspector`,
    buchungen: "Quality inspection entries",
    buchungenHinweis:
      "A deselected entry stays in the list but counts in no tile. " +
      "Largest quantity first, at most 500 rows.",
    zaehltMit: "Counts",
    datum: "Date",
    pruefer: "Inspector",
    produkt: "Product",
    groesse: "Size",
    menge: "Quantity",
    ausschuss: "Scrap",
    mitzaehlen: (datum: string) => `Count the entry from ${datum}`,
    klasseGross: "large",
    klasseKlein: "small",
    diagnose: "Findings without a recognisable level",
    diagnoseHinweis:
      "The level sits in free text in the source file. If it says neither “Major … Level 1” nor " +
      "“Minor … Level 2”, the finding counts nowhere. This list shows where to fix that.",
    bericht: "Report",
    art: "Type",
    adresse: "Address",
    bezeichnung: "Description",
  },
  personal: {
    einleitung:
      "From the Personio sync. The daily target comes from each person's working-time model, " +
      "not from a flat eight-hour day.",
    uebersicht: "Overview",
    standLaedt: "Loading sync status …",
    keinAbgleich: "No sync has run yet. It runs by itself at 02:15 each night.",
    letzterAbgleich: (zeitpunkt: string, status: string) => `Last sync ${zeitpunkt} · ${status}`,
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} people, ${anwesenheiten} attendances, ${abwesenheiten} absences`,
    abgleichLaeuft: "running …",
    abgleichen: "Sync now",
    keineDaten: "No attendances for this period",
    keineDatenHinweis:
      "Either the Personio sync has not run yet, or the period lies before recording began.",
    ueberstunden: "Overtime rate",
    stundenVon: (teil: string, ganz: string) => `${teil} of ${ganz} hrs`,
    krankheit: "Sickness rate",
    krankheitsartenFehlen: "sickness types not configured",
    fluktuation: "Turnover",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} leavers, avg. ${schnitt} employed`,
    personen: "People recorded",
    personenHinweis: "with attendance in the period",
    krankheitHinweisVor:
      "The sickness rate stays empty until it is set which Personio absence types count as " +
      "sickness. To be entered under ",
    krankheitHinweisNach: ".",
    verlauf: "Over time",
    reiheUeberstunden: "Overtime",
    reiheKrankheit: "Sickness",
  },
  melden: {
    knopf: "Report",
    titel: "Report something",
    frage: "What is wrong on this page? A screenshot of the page comes along.",
    abbrechen: "Cancel",
    senden: "Send",
    sendet: "Sending …",
    beispiel: "For example: the tile shows an empty value although there is data.",
    beschreibung: "Description",
    aufnahme: "Screenshot of the page",
    gehtMit: "This screenshot comes along.",
    nimmtAuf: "Capturing the page …",
    misslungen: "The page could not be captured — the report goes without an image.",
    dankeMitBild: "Thank you — the report has arrived.",
    dankeOhneBild: "Thank you — the report has arrived, without an image of the page.",
  },
  belegschaft: {
    titel: "Workforce",
    hinweis:
      "As of today. The distributions show current master data, not what it was back then — " +
      "Personio keeps no history. That “employees” and the skills rate use different " +
      "denominators is deliberate: one figure follows the Personio status, the other the " +
      "joining and leaving dates. Both ways come from the old system.",
    ladeFehler: (meldung: string) => `The workforce data could not be loaded: ${meldung}`,
    beschaeftigte: "Employees",
    beschaeftigteHinweis: "by Personio status “active”",
    neuImQuartal: "New this quarter",
    bestand: "Headcount",
    kompetenzen: "Skills recorded",
    felderFehlen: "fields not configured — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} of ${aktive} by joining and leaving date`,
    geschlecht: "Gender",
    beschaeftigungsart: "Type of employment",
    abteilungen: "Departments",
    maennlich: "male",
    weiblich: "female",
    divers: "diverse",
    unbekannt: "unknown",
    vollzeit: "full time",
    teilzeit: "part time",
    geringfuegig: "marginal",
    extern: "external",
  },
  mitarbeiter: {
    titel: "Employees",
    nurMitUeberstunden: "only with overtime",
    ausgeblendet: (anzahl: number) => `(${anzahl} hidden)`,
    person: "Person",
    abteilung: "Department",
    istStunden: "Hours worked",
    ueberstunden: "Overtime",
    quote: "OT %",
  },
  wochenbericht: {
    titel: "Weekly report",
    ladeFehler: (meldung: string) => `The weekly report could not be loaded: ${meldung}`,
    kalenderwoche: "Calendar week",
    kw: (woche: string, jahr: string) => `W${woche} / ${jahr}`,
    keineDaten: "No attendances for this week.",
    saldo: "Overtime balance",
    saldoHinweis: (personen: string) => `Actual minus effective target, across all ${personen} people`,
    ueberSoll: "Above target",
    ueberSollHinweis: (gesamt: string) => `of ${gesamt} people who clocked in`,
    krankheit: "Sickness",
    tage: "days",
    stunden: "hrs",
    krankheitHinweis: "spread over the calendar days of the absence",
    ist: "Actual",
    soll: "Target",
    saldoSpalte: "Balance",
    fussnote:
      "Target is the effective weekly target: holiday and sickness are deducted, anyone absent " +
      "without notice is in the minus. In the current week the target only counts up to the " +
      "last day clocked.",
  },
  kennzahlenHub: {
    titel: "KPI dashboard",
    einleitung: "Metrics by department. The data comes from the ERP exports under Uploads.",
    nochNicht: "not ported yet",
    bereiche: {
      vertrieb: "Revenue, order value, customer share",
      personal: "Headcount, turnover, sickness — separate permission",
      qualitaet: "Audit findings and complaint rate",
      finanzen: "Material and personnel cost ratio",
      einkauf: "Supplier delivery reliability",
      produktion: "Delays, overdue orders",
      bewertung: "Comments and actions for every metric",
    },
  },
  erklaerung: {
    frage: (titel: string) => `How is “${titel}” calculated?`,
    knopf: "Calculation",
    untertitel: "How this is calculated",
    ganzeSeite: "Full help page",
  },
};
