import type { Texte } from "@/texte/de";

/**
 * The English strings. Typed as `Texte`, so a missing or renamed key is a
 * compile error and never an empty box at runtime.
 *
 * Page names in `pfad.seiten` follow the paths, not the German words: a link
 * that says "Training" has to lead to the page the German one calls
 * „Schulungen".
 */
export const en: Texte = {
  kopf: {
    uebersicht: "To the overview",
    hilfe: "Help",
    einstellungen: "Settings",
    abmelden: "Sign out",
    sprache: "Language",
    erscheinungsbild: "Appearance",
    hell: "Light",
    dunkel: "Dark",
    system: "Follow the system",
    meldungenLeer: "Reports — nothing new",
    meldungen: (anzahl: number) => `Reports — ${anzahl} not yet looked at`,
    massnahmenLeer: "Actions — none open",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Actions — ${offen} open, ${ueberfaellig} of them overdue`
        : `Actions — ${offen} open`,
  },
  pfad: {
    aria: "Path",
    start: "Home",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "Deliveries",
      "/einstellungen": "Settings",
      "/fair": "FAIR",
      "/hilfe": "Help",
      "/hr": "People",
      "/hr/dokumente": "Document run",
      "/hr/einarbeitung": "Induction",
      "/hr/kompetenzen": "Skills",
      "/hr/onboarding": "Onboarding",
      "/hr/organigramm": "Org chart",
      "/hr/schulungen": "Training",
      "/hr/schulungen/matrix": "Matrix",
      "/hr/schulungen/offen": "Outstanding",
      "/hr/zeugnisse": "References",
      "/kpi": "Metrics",
      "/kpi/bewertung": "Review",
      "/kpi/einkauf": "Purchasing",
      "/kpi/finanzen": "Finance",
      "/kpi/produktion": "Production",
      "/kpi/qualitaet": "Quality",
      "/kpi/vertrieb": "Sales",
      "/newsletter": "Newsletter",
      "/newsletter/redaktion": "Editing",
      "/platform/feedback": "Reports",
      "/produktion": "Production",
      "/qualitaet": "Quality",
      "/sensoren": "Sensors",
      "/signage": "Digital signage",
      "/signage/devices": "Devices",
      "/signage/media": "Media",
      "/signage/pair": "Pairing",
      "/signage/playlists": "Playlists",
      "/signage/schedules": "Schedules",
      "/uploads": "Uploads",
    },
  },
  start: {
    titel: "Apps",
    verweigert: (name: string) => `You are not allowed to open “${name}”.`,
    keineApp: "No app has been assigned to your account yet. Please contact platform admin.",
  },
  anmeldung: {
    titel: "ACM Platform",
    aufforderung: "Sign in with your account.",
    email: "E-mail",
    passwort: "Password",
    knopf: "Sign in",
    laeuft: "Signing in …",
  },
  allgemein: {
    laedt: "Loading …",
  },
  zeitraum: {
    monat: "This month",
    quartal: "This quarter",
    jahr: "This year",
    alles: "All time",
    frei: "Pick a period",
    von: "from",
    bis: "to",
    vonAria: "Period from",
    bisAria: "Period to",
    verdreht: "The end is before the start.",
  },
  vergleich: {
    vorperiode: "vs. previous period",
    vormonat: "vs. previous month",
    vorquartal: "vs. previous quarter",
    vorjahr: "vs. last year",
    zeitraumDavor: "vs. the period before",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Data as of ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Data incomplete — ${fehlend} ${anzahl === 1 ? "is missing" : "are missing"}`,
    heute: "today",
    gestern: "yesterday",
    vorTagen: (tage: number) => `${tage} days ago`,
    nie: "never",
    arten: {
      umsatz: "Revenue",
      auftraege: "Orders",
      angebote: "Quotes",
      interessenten: "Leads",
      kontakte: "Contacts",
      liefertreue: "Delivery reliability",
      lagerbewegungen: "Stock movements",
      lagerpreise: "Stock prices",
      auftragspositionen: "Order lines",
      lieferscheine: "Delivery notes",
      pruefungen: "Inspections",
      acht_d: "8D reports",
      wareneingaenge: "Goods receipts",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `The metrics could not be loaded: ${meldung}`,
    keineDatenTitel: "No data for this period",
    keineDatenVor: "Upload the ERP exports under ",
    keineDatenNach: ", or pick a wider period.",
    keineWerte: "no values in this period",
    laedt: "loading …",
    jeTag: "by day",
    jeWoche: "by week",
    jeMonat: "by month",
  },
  vertrieb: {
    umsatz: "Revenue",
    umsatzHinweis: "Invoices minus credit notes",
    auftragswert: "Avg. order value",
    ueberNull: "Orders above €0",
    auftraege: "Orders total",
    verlauf: "Revenue over time",
    verlaufHinweis: (takt: string) => `${takt}, credit notes deducted`,
    kundenanteil: "Customer share of revenue",
    kunde: "Customer",
    anteil: "Share",
    uebrige: "Others",
    jeErfasser: "Orders by sales rep",
    erfasser: "Sales rep",
    anzahl: "Orders",
    summe: "Total",
  },
  aktivitaet: {
    titel: "Sales activity",
    jeWoche: (von: string, bis: string) => `by calendar week, ${von} to ${bis}`,
    ladeFehler: (meldung: string) => `Sales activity could not be loaded: ${meldung}`,
    leer: "No contacts, quotes or leads in this period.",
    kw: (woche: string) => `W${woche}`,
    ziel: (wert: string) => `Target ${wert} / week`,
    erstkontakte: "First contacts",
    erstkontakteHinweis: "completed contacts of type ERS",
    besuche: "Visits",
    besucheHinweis: "on site and online together",
    interessenten: "Leads",
    interessentenHinweis: "newly recorded, no rep assigned",
    angebote: "Quotes",
    angeboteHinweis: "total of quotes written",
    auftragseingang: "Orders received",
    auftragseingangHinweis: "cancellations netted off",
  },
  einkauf: {
    einleitung: "Supplier delivery reliability. Counted is what arrived within the period.",
    keineDaten: "No delivery lines for this period",
    ladeVor: "Upload the delivery-reliability export under ",
    ladeNach: ".",
    otd: "OTD rate",
    otdHinweis: (ziel: string) => `Target ${ziel} · on time means delay ≤ 0`,
    puenktlich: "Lines on time",
    gesamt: "Lines total",
    verzugSchnitt: "Avg. delay",
    verzugHinweis: "Lines without a delay value are left out here",
    verlauf: "OTD rate over time",
    verlaufHinweis: "Gaps are periods without delivery lines.",
    ladenhueter: "Stock on order — slow movers",
    kapital: (wert: string) => `Capital tied up: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Stock items with no movement for at least ${tage} days, highest value first. ` +
      "As of today — the period above does not apply here, because a stock level is not a period.",
    artikel: "Item",
    bezeichnung: "Description",
    bestand: "Quantity",
    liegtSeit: "Lying since",
    stueckpreis: "Unit price",
    wert: "Value",
    positionen: "Delivery lines",
    positionenHinweis: "Longest delay first, lines without a delay value on top. At most 500 rows.",
    auftrag: "Order",
    lieferant: "Supplier",
    zieltermin: "Due date",
    geliefert: "Delivered",
    verzug: "Delay",
  },
  produktion: {
    einleitung: "Orders running late. An order is counted once its outcome is settled.",
    keineDaten: "No order with a settled outcome in this period",
    ladeVor: "Upload the order lines and the delivery notes under ",
    ladeNach:
      ". Both are needed: one file carries the due date, the other the actual date.",
    quote: "Delay rate",
    quoteHinweis: (ziel: string) => `At most ${ziel}`,
    inVerzug: "Orders running late",
    gesamt: "Orders total",
    gesamtHinweis: "excluding open orders not yet due",
    verzugSchnitt: "Avg. delay",
    verzugHinweis: "orders on time count as negative",
    verlauf: "Delay rate over time",
    verlaufHinweis: "By due date. Gaps are periods without counted orders.",
    ziellinie: "Target",
    liste: "Orders running late",
    listeHinweis:
      "Longest delay first. For open orders it keeps growing daily. At most 500 rows.",
    auftrag: "Order",
    kunde: "Customer",
    stand: "State",
    zieltermin: "Due date",
    geliefert: "Delivered",
    verzug: "Delay",
    verspaetet: "delivered late",
    offen: "open, overdue",
  },
  finanzen: {
    einleitung: "Material and personnel costs against invoiced revenue.",
    keineDatenVor:
      "Three files are needed: the stock movements for consumption, the goods receipts for " +
      "the prices and the revenue as the reference. All three live under ",
    keineDatenNach: ".",
    materialquote: "Material cost ratio",
    materialquoteHinweis: "Material costs / revenue",
    hoechstens: (ziel: string) => `At most ${ziel}`,
    materialkosten: "Material costs",
    umsatz: "Revenue",
    personalquote: "Personnel cost ratio",
    brauchtZeitraum: "needs a period",
    personalHinweis: (kosten: string, personen: string) => `${kosten} for ${personen} people`,
    ohnePreis: "Items without a price",
    ohnePreisHinweis: "consumed, but not valued",
    jeAbteilung: "Personnel costs by department",
    abteilung: "Department",
    personen: "People",
    kosten: "Costs",
    anteil: "Share",
    verlauf: "Material cost ratio over time",
    verlaufHinweis: "Gaps are periods without revenue — without a reference there is no ratio.",
    ziellinie: "Target",
    verbrauch: "Material consumption by item",
    verbrauchHinweis:
      "Highest cost first. Items without a price come last — they do not enter the ratio. " +
      "At most 500 rows.",
    artikel: "Item",
    bezeichnung: "Description",
    menge: "Consumption",
    stueckpreis: "Unit price",
    keinPreis: "no price",
  },
  qualitaet: {
    einleitung: "Audit findings, complaint rate and inspected quantities.",
    auditart: "Audit type:",
    keineArt: "No audit type selected. Pick at least one, otherwise there is nothing to count.",
    keineDaten: "No audit findings for this period",
    ladeVor: "Upload the 8D export under ",
    ladeNach: ".",
    behoerde: "Authority",
    extern: "External",
    intern: "Internal",
    kunde: "Customer",
    level1: "Audit findings level 1",
    level2: "Audit findings level 2",
    ohneLevel: "No level recognised",
    ohneLevelHinweis: "counted in no tile",
    hoechstens: (ziel: number) => `At most ${ziel}`,
    auditVerlauf: "Audit findings over time",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) =>
      `Share of quantity without complaint. Reference: ${bezug}.`,
    fehlerquote: (quote: string) => `Defect rate: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Defect rate: ${quote} · target ${ziel}`,
    reklamiert: "Quantity complained about",
    bezugsmenge: "Reference quantity",
    bezugsmengeNull: "without it there is no rate",
    mehrAlsBezogen:
      "More has been complained about than was received. The calculation cannot resolve this: " +
      "numerator and denominator come from different files with their own date fields. Check " +
      "whether the reference file for this period was uploaded in full.",
    reklKunde: "Customer",
    reklIntern: "internal",
    reklLieferant: "Material suppliers",
    reklWerkbank: "Workbenches",
    bezugKunde: "quantity delivered",
    bezugIntern: "quantity delivered",
    bezugLieferant: "goods receipts excluding services",
    bezugWerkbank: "goods receipts of product groups DIENST and SERVIC",
    mengeGesamt: "quantity reported",
    mengeAkzeptiert: "quantity accepted",
    onQualityBezug: (menge: string) => `On Quality (reference ${menge})`,
    ziellinie: "Target",
    geprueft: "Products inspected",
    geprueftHinweis: (pruefer: string, tage: string) =>
      `Quantity per inspector and inspection day. The divisor is the same for both sizes: ${pruefer} inspectors on ${tage} days.`,
    gross: "Large products",
    klein: "Small products",
    mindestens: (ziel: number) => `At least ${ziel} per day and inspector`,
    buchungen: "Quality inspection entries",
    buchungenHinweis:
      "A deselected entry stays in the list but counts in no tile. " +
      "Largest quantity first, at most 500 rows.",
    zaehltMit: "Counts",
    datum: "Date",
    pruefer: "Inspector",
    produkt: "Product",
    groesse: "Size",
    menge: "Quantity",
    ausschuss: "Scrap",
    mitzaehlen: (datum: string) => `Count the entry from ${datum}`,
    klasseGross: "large",
    klasseKlein: "small",
    diagnose: "Findings without a recognisable level",
    diagnoseHinweis:
      "The level sits in free text in the source file. If it says neither “Major … Level 1” nor " +
      "“Minor … Level 2”, the finding counts nowhere. This list shows where to fix that.",
    bericht: "Report",
    art: "Type",
    adresse: "Address",
    bezeichnung: "Description",
  },
  personal: {
    einleitung:
      "From the Personio sync. The daily target comes from each person's working-time model, " +
      "not from a flat eight-hour day.",
    uebersicht: "Overview",
    standLaedt: "Loading sync status …",
    keinAbgleich: "No sync has run yet. It runs by itself at 02:15 each night.",
    letzterAbgleich: (zeitpunkt: string, status: string) => `Last sync ${zeitpunkt} · ${status}`,
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} people, ${anwesenheiten} attendances, ${abwesenheiten} absences`,
    abgleichLaeuft: "running …",
    abgleichen: "Sync now",
    keineDaten: "No attendances for this period",
    keineDatenHinweis:
      "Either the Personio sync has not run yet, or the period lies before recording began.",
    ueberstunden: "Overtime rate",
    stundenVon: (teil: string, ganz: string) => `${teil} of ${ganz} hrs`,
    krankheit: "Sickness rate",
    krankheitsartenFehlen: "sickness types not configured",
    fluktuation: "Turnover",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} leavers, avg. ${schnitt} employed`,
    personen: "People recorded",
    personenHinweis: "with attendance in the period",
    krankheitHinweisVor:
      "The sickness rate stays empty until it is set which Personio absence types count as " +
      "sickness. To be entered under ",
    krankheitHinweisNach: ".",
    verlauf: "Over time",
    reiheUeberstunden: "Overtime",
    reiheKrankheit: "Sickness",
  },
  melden: {
    knopf: "Report",
    titel: "Report something",
    frage: "What is wrong on this page? A screenshot of the page comes along.",
    abbrechen: "Cancel",
    senden: "Send",
    sendet: "Sending …",
    beispiel: "For example: the tile shows an empty value although there is data.",
    beschreibung: "Description",
    aufnahme: "Screenshot of the page",
    gehtMit: "This screenshot comes along.",
    nimmtAuf: "Capturing the page …",
    misslungen: "The page could not be captured — the report goes without an image.",
    dankeMitBild: "Thank you — the report has arrived.",
    dankeOhneBild: "Thank you — the report has arrived, without an image of the page.",
  },
  belegschaft: {
    titel: "Workforce",
    hinweis:
      "As of today. The distributions show current master data, not what it was back then — " +
      "Personio keeps no history. That “employees” and the skills rate use different " +
      "denominators is deliberate: one figure follows the Personio status, the other the " +
      "joining and leaving dates. Both ways come from the old system.",
    ladeFehler: (meldung: string) => `The workforce data could not be loaded: ${meldung}`,
    beschaeftigte: "Employees",
    beschaeftigteHinweis: "by Personio status “active”",
    neuImQuartal: "New this quarter",
    bestand: "Headcount",
    kompetenzen: "Skills recorded",
    felderFehlen: "fields not configured — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} of ${aktive} by joining and leaving date`,
    geschlecht: "Gender",
    beschaeftigungsart: "Type of employment",
    abteilungen: "Departments",
    maennlich: "male",
    weiblich: "female",
    divers: "diverse",
    unbekannt: "unknown",
    vollzeit: "full time",
    teilzeit: "part time",
    geringfuegig: "marginal",
    extern: "external",
  },
  mitarbeiter: {
    titel: "Employees",
    nurMitUeberstunden: "only with overtime",
    ausgeblendet: (anzahl: number) => `(${anzahl} hidden)`,
    person: "Person",
    abteilung: "Department",
    istStunden: "Hours worked",
    ueberstunden: "Overtime",
    quote: "OT %",
  },
  wochenbericht: {
    titel: "Weekly report",
    ladeFehler: (meldung: string) => `The weekly report could not be loaded: ${meldung}`,
    kalenderwoche: "Calendar week",
    kw: (woche: string, jahr: string) => `W${woche} / ${jahr}`,
    keineDaten: "No attendances for this week.",
    saldo: "Overtime balance",
    saldoHinweis: (personen: string) => `Actual minus effective target, across all ${personen} people`,
    ueberSoll: "Above target",
    ueberSollHinweis: (gesamt: string) => `of ${gesamt} people who clocked in`,
    krankheit: "Sickness",
    tage: "days",
    stunden: "hrs",
    krankheitHinweis: "spread over the calendar days of the absence",
    ist: "Actual",
    soll: "Target",
    saldoSpalte: "Balance",
    fussnote:
      "Target is the effective weekly target: holiday and sickness are deducted, anyone absent " +
      "without notice is in the minus. In the current week the target only counts up to the " +
      "last day clocked.",
  },
  titel: {
    schulung: "Training",
    zeugnis: "Reference",
    qualifikationsmatrix: "Qualification matrix",
    maschine: "Machine",
    audit: "Audit",
    zeichnung: "Drawing",
    lieferung: "Delivery",
    offeneSchulungen: "Outstanding training",
    schulungsmatrix: "Training matrix",
    atrLieferungen: "ATR deliveries",
    kpiBewertung: "KPI review",
    anmelden: "Sign in",
  },
  uploads: {
    einleitung:
      "Read in the ERP exports. Uploading the same file again is harmless: existing rows are " +
      "updated, not added twice.",
    dateiWaehlen: "Choose file",
    verarbeitet: "processing …",
    uebersprungen: (datei: string) => `Rows skipped from “${datei}”`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `${gesamt} row(s) taken over, ${fehler} skipped. The remaining rows are saved.`,
    zeile: "Row",
    spalte: "Column",
    grund: "Reason",
    zuletzt: "Recently uploaded",
    datei: "File",
    art: "Type",
    zeilen: "Rows",
    uebersprungenSpalte: "Skipped",
    status: "Status",
    zeitpunkt: "Time",
    nochNichts: "Nothing uploaded yet.",
    keineZeile: (datei: string) => `“${datei}” contained no valid row.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `“${datei}” taken over, ${fehler} row(s) skipped.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `“${datei}” taken over: ${neu} new, ${aktualisiert} updated.`,
    fehlgeschlagenMeldung: (meldung: string) => `Upload failed: ${meldung}`,
    vollstaendig: "complete",
    teilweise: "partial",
    fehlgeschlagen: "failed",
    arten: {
      umsatz: "Revenue (invoices and credit notes)",
      umsatzText: "Feeds the revenue tile and the revenue chart. Credit notes are negative in the file.",
      auftraege: "Orders received",
      auftraegeText: "Feeds average order value, total orders and the breakdown by sales rep.",
      auftragspositionen: "Order lines",
      auftragspositionenText:
        "Carries the due date per line. Together with the delivery notes this gives the delay.",
      lieferscheine: "Delivery notes",
      lieferscheineText: "Carries the actual delivery date. Excel file, one row per delivery note line.",
      wareneingaenge: "Goods receipts",
      wareneingaengeText:
        "Reference quantity for the defect rate on the purchasing side. The product group separates material suppliers from workbenches.",
      acht_d: "8D reports",
      acht_dText:
        "Audit findings and complaints in one file. A finding's level sits in free text and is derived while reading in.",
      lagerbewegungen: "Stock movements",
      lagerbewegungenText:
        "Consumption per item for the material cost ratio. Replaces all rows within the file's date range.",
      lagerpreise: "Stock item prices",
      lagerpreiseText:
        "Master data for stock valuation. Replaces the whole price list, not only the items contained.",
      pruefungen: "Quality inspection",
      pruefungenText:
        "Inspection entries. Replaces all rows within the file's date range — entries deselected by hand in that range count again afterwards.",
      liefertreue: "Delivery reliability (purchasing)",
      liefertreueText:
        "Feeds the OTD rate in purchasing. One row per delivery line; the actual delivery date sets the period.",
      kontakte: "Contacts (sales)",
      kontakteText:
        "First contacts and visits per week. Replaces all rows within the file's date range — a second upload of the same period doubles nothing.",
      angebote: "Quotes",
      angeboteText:
        "Quote volume per week and sales rep. Quotes without a rep appear in no bar.",
      interessenten: "Leads",
      interessentenText:
        "Master data of the leads. A lead saved again moves into a different week with its new date.",
    },
  },
  organigramm: {
    einleitung:
      "From Personio. Anyone without a supervisor recorded there appears at the top — which is " +
      "right for the management and otherwise a sign of a gap in the master data.",
    suchfeld: "Person, position or department",
    suchePlatzhalter: "Name, position, department",
    standort: "Location",
    alleStandorte: "All locations",
    personen: (anzahl: number) => `${anzahl} people`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} without a supervisor`,
    niemand: "Nobody found",
    niemandText: "Another search, another location — or the Personio sync has not run yet.",
    aufklappen: (name: string) => `Expand ${name}`,
    zuklappen: (name: string) => `Collapse ${name}`,
    direkt: (anzahl: number) => `${anzahl} direct`,
  },
  offeneSchulungen: {
    einleitung:
      "Who still needs what. Active training only; retired courses no longer appear here.",
    zumKatalog: "To the catalogue",
    allesOffene: "Everything outstanding",
    nieAbsolviert: "Never taken",
    ueberfaellig: "Overdue",
    wirdFaellig: "Falling due",
    suchen: "Search person or training",
    suchenAria: "Search",
    nichtsOffen: "Nothing outstanding",
    nichtsOffenText: "All active training is within its cycle — or nothing has been read in yet.",
    eintraege: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "entry" : "entries"}.`,
    person: "Person",
    schulung: "Training",
    bereich: "Area",
    zuletzt: "Last taken",
    faellig: "Due",
    stand: "State",
    nie: "never taken",
    imTurnus: "within cycle",
  },
  schulungsmatrix: {
    einleitung:
      "Everyone against every course — the overview for the noticeboard and for the audit. " +
      "Anyone who has attended nothing at all appears with an empty row; that is exactly the gap " +
      "one is looking for.",
    wasOffenIst: "What is outstanding",
    katalog: "Catalogue",
    suchfeld: "Person or department",
    suchePlatzhalter: "Name, department, staff number",
    bereich: "Area",
    alleBereiche: "All areas",
    nurLuecken: "Only people with gaps",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} of ${gesamt} people · ${schulungen} courses`,
    niemand: "No person matches",
    niemandText: "Another search or another area — or really nobody is outstanding.",
    person: "Person",
    nichtZugewiesen: (person: string, schulung: string) => `${person} · ${schulung}: not assigned`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (due ${datum})`,
    offen: "outstanding",
    personio: "Personio",
    externGepflegt: "maintained externally",
    ohneTreffer: "no Personio match",
  },
  schulungen: {
    einleitung:
      "The catalogue, its cycle and who meets it. Due dates are calculated from the last date " +
      "and the cycle, not stored.",
    dokumentenlauf: "Document run",
    bereich: "Area",
    neueSchulung: "New course",
    beispiel: "e.g. fire safety briefing",
    anlegen: "Create",
    wirdGelesen: "Reading …",
    uebersichtEinlesen: "Read in overview",
    einlesenAria: "Read in training overview",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} courses (${neu} new), ${teilnahmen} attendances, ${zugeordnet} of them matched to a person in Personio.`,
    ohneTreffer: "No Personio match: ",
    ohneTrefferNach: ". These rows still come along with staff number and name.",
    wirdUebernommen: "Taking over …",
    uebernehmen: "Take over",
    abbrechen: "Cancel",
    keineSchulung: "No course yet",
    keineSchulungText: "Create one or read in the training overview.",
    schulung: "Course",
    turnus: "Cycle",
    frist: "Notice (days)",
    verantwortlich: "Responsible",
    offen: "Outstanding",
    aktiv: "Active",
    nichtBerechenbar: "(not calculable)",
    zahlGroesserNull: "Please enter a number greater than 0.",
    nieKurz: (anzahl: number) => `${anzahl} never`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} overdue`,
    baldKurz: (anzahl: number) => `${anzahl} soon`,
    aktivSchalter: (name: string) => `${name} active`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} means: no date for this person is on record. ${bald} means: within the next two months. As of ${datum}.`,
  },
  schulung: {
    gibtEsNicht: "This course does not exist",
    gibtEsNichtText: "It was probably removed.",
    ohneTurnus: "no cycle",
    keineFaelligkeit: " — no due date can be calculated from that",
    zumKatalog: "To the catalogue",
    stammdaten: "Master data",
    turnus: "Cycle",
    turnusBeispiel: "e.g. yearly",
    turnusHinweis: "The text; the number of months comes from reading in.",
    turnusMonate: "Cycle in months",
    monateHinweis: "Empty means: no due date can be calculated.",
    verantwortlich: "Responsible",
    beschreibung: "Description",
    fuerWen: "Who is it mandatory for?",
    kuerzel: "Department code",
    kuerzelHinweis: "The fine-grained scheme from the spreadsheet (NÄH, CUT, WVK …).",
    personioAbteilung: "Personio department",
    personioHinweis: "The coarse department as Personio keeps it.",
    entfernen: (was: string) => `Remove ${was}`,
    keine: "none",
    ergaenzen: (was: string) => `Add ${was}`,
    hinzufuegen: "Add",
    teilnahmen: "Attendances",
    nochNiemand: "Nobody yet — read in the training overview or enter someone.",
    person: "Person",
    abteilungKurz: "Dept.",
    erstschulung: "First training",
    zuletzt: "Last taken",
    faellig: "Due",
    stand: "State",
    keinTreffer: "No match in Personio — the row is kept regardless",
    nichtInPersonio: "not in Personio",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "this attendance",
    personErgaenzen: "Add person",
    nameForm: "Surname, first name",
  },
  kompetenzen: {
    einleitung:
      "What a role requires and how far it is met — one matrix per area. Read in from the area " +
      "file, maintained here afterwards.",
    zumDashboard: "To the people dashboard",
    bereich: "Area",
    wirdGelesen: "Reading …",
    einlesen: "Read in area file",
    vorschauKopf: (datei: string, bereich: string) =>
      `${datei} — this is how ${bereich} would look afterwards:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} qualifications, ${personen} people, ${bewertungen} ratings.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `${zugeordnet} of ${personen} people found in Personio`,
    platzhalter: (anzahl: number) =>
      `, ${anzahl} placeholder column${anzahl === 1 ? "" : "s"}`,
    ohneZuordnung: (namen: string) => ` Not matched: ${namen}.`,
    ersetztWarnung:
      "The sheets concerned are replaced in full — changes maintained here are lost in the process.",
    wirdUebernommen: "Taking over …",
    uebernehmen: "Take over",
    abbrechen: "Cancel",
    keineMatrix: "No matrix yet",
    keineMatrixText: "Read in an area file — each sheet in it becomes a matrix.",
    blatt: "Sheet",
    titelSpalte: "Title",
    stand: "As of",
    eingelesen: "Read in",
    produktion: "Production",
    verwaltung: "Administration",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    einleitung:
      "Grades and bullet points become reference language. The master data is copied when the " +
      "reference is created — an issued reference does not change because Personio changes.",
    person: "Person",
    waehlen: "— choose —",
    art: "Type",
    anlegen: "Create",
    keines: "No reference yet",
    keinesText: "Pick a person and the type of reference — the master data follows by itself.",
    zeitraum: "Period",
    note: "Grade",
    stand: "State",
    angelegt: "Created",
    fertig: "done",
    entwurf: "Draft",
    qualifiziert: "Qualified reference",
    einfach: "Simple reference",
    zwischenzeugnis: "Interim reference",
    ausbildungszeugnis: "Apprenticeship reference",
    praktikumszeugnis: "Internship reference",
  },
  einarbeitung: {
    einleitung:
      "What a new person has to learn and who shows them. The sheet is built from the items " +
      "recorded for their department.",
    bogenErzeugen: "Create sheet",
    person: "Person",
    waehlen: "— choose —",
    wirdGebaut: "Building …",
    einarbeitungsplan: "Induction plan",
    keineInhalte: "No items recorded yet — the sheet would stay empty.",
    abteilungVon: (abteilung: string) => `Department ${abteilung}`,
    neuerInhalt: "New item",
    beispiel: "e.g. safety briefing at the milling machine",
    anlegen: "Create",
    keinInhalt: "No item yet",
    keinInhaltText: "Set out what a new person has to learn — and which departments it applies to.",
    inhalt: "Item",
    ansprechpartner: "Contact",
    bereich: "Area",
    fuerAbteilungen: "For which departments",
    abteilung: "Department",
    bereichLeer: "Empty means: use the department from the matrix",
    entfernen: (was: string) => `Remove ${was}`,
    abteilungHinzu: "+ department",
    abteilungFuer: (inhalt: string) => `Department for ${inhalt}`,
  },
  matrix: {
    gibtEsNicht: "This matrix does not exist",
    gibtEsNichtText: "It was probably replaced.",
    blattStand: (blatt: string) => `Sheet ${blatt}`,
    stand: (datum: string) => ` · as of ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} qualifications, ${personen} people`,
    zurUebersicht: "To the overview",
    qualifikation: "Qualification",
    keineZeilen: "This matrix has no rows yet.",
    stufenBedeuten: "What the levels mean",
    erfuellungsgradHinweis:
      "The second number is the degree of fulfilment in percent. A cell with a requirement and " +
      "less than 100 % is a gap and is shown in the warning colour.",
    ergaenzen: "Add",
    neueQualifikation: "New qualification",
    beispiel: "e.g. lathe",
    kategorie: "Category",
    ohne: "none",
    zeile: "Row",
    neuePerson: "New person",
    namensform: "First name Surname",
    spalte: "Column",
    anforderungslevel: "Required level",
    erfuellungsgrad: "Degree of fulfilment in percent",
    stufe0: "not required",
    stufe1: "basic knowledge",
    stufe2: "can work under guidance",
    stufe3: "works independently",
    stufe4: "can guide and train",
  },
  zeugnis: {
    gibtEsNicht: "This reference does not exist",
    gibtEsNichtText: "It was probably deleted.",
    durchschnitt: (wert: string) => ` · average ${wert}`,
    zurUebersicht: "To the overview",
    zeugnisVon: (name: string) => `Reference ${name}`,
    stammdaten: "Master data",
    stammdatenHinweis:
      "Copied when the reference was created. Changes here apply to this reference only — " +
      "Personio stays untouched.",
    name: "Name",
    personalnummer: "Staff number",
    abteilung: "Department",
    taetigkeit: "Role",
    eintritt: "Joined",
    austritt: "Left",
    geburtsdatum: "Date of birth",
    ausstellungsdatum: "Date of issue",
    ohneNamen: "It does not work without a name.",
    anrede: "Salutation",
    frau: "Ms",
    herr: "Mr",
    anredeHinweis: "Controls salutation and pronouns in the text.",
    art: "Type",
    anlass: "Reason",
    anlassBeispiel: "e.g. own request",
    fuehrungskraft: "Manager",
    fuehrungskraftHinweis: "Manager — brings in the “leadership” dimension",
    bewertung: "Rating",
    bewertungHinweis:
      "School grades from 1 to 4. The satisfaction wording follows from the average — not the " +
      "other way round.",
    fachwissen: "Expertise",
    auffassungsgabe: "Grasp",
    arbeitsweise: "Way of working",
    belastbarkeit: "Resilience",
    arbeitserfolg: "Results",
    sozialverhalten: "Conduct",
    fuehrung: "Leadership",
    aufgaben: "Duties (bullet points)",
    aufgabenHinweis: "One duty per line — this becomes the list in the reference.",
    kompetenzen: "Particular skills",
    kompetenzenHinweis: "Feeds into the performance assessment.",
    erfolge: "Particular achievements",
    erfolgeHinweis: "Projects, awards, measurable results.",
    text: "Text",
    baut: "Building …",
    ausBausteinen: "From building blocks",
    formuliert: "Writing …",
    mitKi: "With AI",
    textHinweis:
      "The building blocks write without network and without AI. The AI writes more freely — it " +
      "only receives salutation, role, department, duration, grades and the free text above. " +
      "Name, date of birth and staff number do not leave the server.",
    nochKeinText: "No text yet. Award the grades and have it composed.",
    fertigSchalter: "Reference done",
    fertigHinweis: "Done — no longer in progress",
    unterschriftenFehler: (meldung: string) =>
      `The signatures could not be determined (${meldung}).`,
    darunterSteht: "Signed by",
    fachlich: "Line manager",
    personalwesen: "HR",
    niemandHinterlegt: "— nobody recorded —",
    unterschriftFehlt:
      "A signature is missing. Record it under Settings → References, or maintain the supervisor " +
      "in Personio.",
    ausPersonio: "from Personio",
    ausEinstellungen: "from the settings",
    nichtHinterlegt: "not recorded",
    einleitung: "Introduction",
    taetigkeitsbeschreibung: "Description of duties",
    leistungsbeurteilung: "Performance assessment",
    schlussformel: "Closing formula",
    hinweisDeutsch: "The reference itself is written in German.",
  },
  dokumentenlauf: {
    einleitung:
      "Sheets with a QR code: create, hand out, take back filled in, check. The QR matches the " +
      "scan back up — no matter what the file is called.",
    formblatt: "Form",
    fuerWen: "For whom",
    personWaehlen: "— choose person —",
    erzeugt: "Creating …",
    blattErzeugen: "Create sheet",
    standFilter: "State:",
    alle: "All",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} of ${gesamt}`,
    keinVorgang: "No case",
    keinVorgangText: "Create a sheet above — it gets a QR code and is tracked from then on.",
    person: "Person",
    kennung: "Code",
    stand: "State",
    vollstaendigSpalte: "Complete",
    blatt: "Sheet",
    scan: "Scan",
    prueft: "Checking …",
    scanFuer: (name: string) => `Upload scan for ${name}`,
    zu: "close",
    details: "Details",
    nochNichtGeprueft: "— not checked yet",
    vollstaendig: "complete",
    unvollstaendig: "incomplete",
    umkehren: "Reverse the verdict — the measurement only sees whether there is ink in the field",
    pruefung: "Check",
    qrGelesen: "— QR read",
    keinQr: "— no QR found, fields cannot be matched",
    nachweise: "Evidence",
    keineNachweise: "None recorded yet.",
    welcheZeile: "Which line? (optional)",
    laedt: "Uploading …",
    nachweis: "Evidence",
    nachweisHoch: "Upload evidence",
    erstellt: "created",
    uebergeben: "handed out",
    zurueck: "returned",
    geprueft: "checked",
    einarbeitungsplan: "Induction plan",
    schulungsnachweis: "Training record",
  },
  onboarding: {
    einleitung:
      "Who is new and which courses the requirements matrix asks for. The plan is not stored but " +
      "calculated — if the matrix changes, the plan changes.",
    nichtsGefehlt: "Nothing was missing.",
    angelegt: (anzahl: number) => `${anzahl} course${anzahl === 1 ? "" : "s"} created.`,
    neu90: "New (last 90 days)",
    alle: "All",
    personen: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "person" : "people"}`,
    keineEintritte: "No joiners",
    keineEintritteText: "As soon as someone with a joining date comes from Personio, they appear here.",
    person: "Person",
    abteilung: "Department",
    position: "Position",
    eintritt: "Joined",
    uebergabe: "Handed over",
    nichtInPersonio: "not in Personio",
    hierGesetzt: "Set here — overrides Personio",
    ausPersonio: "From Personio",
    vermerken: "Mark done",
    paketTitel: "Induction plan and training overview as one PDF",
    paket: "Bundle",
    uebersichtTitel: "Training overview only (form 71)",
    uebersicht: "Overview",
    planZu: "Close plan",
    plan: "Plan",
    schulungsplan: "Training plan",
    fehlendeAnlegen: "Create missing ones",
    wirdGerechnet: "calculating …",
    bruecke: "Position → department code",
    brueckeHinweis:
      "The bridge between Personio and the fine-grained level of the requirements matrix. " +
      "Without an entry the fine level does not apply to this position — the plan says so " +
      "explicitly.",
    kuerzel: "Code",
    positionBeispiel: "e.g. CNC machinist",
    kuerzelBeispiel: "CNC",
    zuordnen: "Assign",
    ohnePersonio: "Person without Personio",
    ohnePersonioHinweis:
      "For joiners not yet in the sync — or who do not belong there at all.",
    name: "Name",
    anlegen: "Create",
    kuerzelFehlt: (position: string) =>
      `No department code is recorded for the position ${position}. The fine-grained level of ` +
      "the requirements matrix therefore does not apply to this person — mandatory courses may " +
      "be missing.",
    matrixVerlangtNichts: "The requirements matrix asks for nothing for this department.",
    schulung: "Course",
    bereich: "Area",
    turnus: "Cycle",
    pflichtUeber: "Mandatory via",
    stand: "State",
    ueberAbteilung: "Department",
    ueberKuerzel: "Code",
    vorhanden: "present",
    fehlt: "missing",
  },
  audit: {
    einleitung:
      "Audits from planning to completion. Every change of status is recorded in the history — " +
      "written by the database, not by the form, and unchangeable afterwards.",
    zuKennzahlen: "To the metrics",
    nummer: "Number",
    nummerBeispiel: "A-2026-01",
    titel: "Title",
    titelBeispiel: "EN 9100 system audit",
    art: "Type",
    intern: "internal",
    extern: "external",
    phasenvorlage: "Phase template",
    ohne: "none",
    anlegen: "Create",
    keinAudit: "No audit yet",
    keinAuditText: "Create one — with a phase template it brings its checklist along.",
    laufen: (laufend: number, gesamt: number) => `${laufend} of ${gesamt} still running.`,
    status: "Status",
    fortschritt: "Progress",
    naechsterTermin: "Next date",
    ueberfaellig: (anzahl: number) => `${anzahl} overdue`,
    geplant: "Planned",
    inVorbereitung: "In preparation",
    inDurchfuehrung: "In progress",
    berichtet: "Reported",
    massnahmenOffen: "Actions open",
    abgeschlossen: "Completed",
    verschoben: "Postponed",
    abgesagt: "Cancelled",
    phaseOffen: "Open",
    phaseInArbeit: "In progress",
    phaseErledigt: "Done",
    phaseNichtZutreffend: "Not applicable",
    system: "System",
    prozess: "Process",
    produkt: "Product",
    lieferant: "Supplier",
  },
  wartung: {
    einleitung:
      "Machines and their recurring maintenance tasks. The record is produced as a sheet to put " +
      "up — per half year, with one column per calendar week.",
    zuKennzahlen: "To the metrics",
    neueMaschine: "New machine",
    beispiel: "e.g. milling machine 3",
    anlegen: "Create",
    keineMaschine: "No machine yet",
    keineMaschineText: "Create a machine and record its maintenance tasks.",
    maschine: "Machine",
    inventarnummer: "Asset no.",
    standort: "Location",
    verantwortlich: "Responsible",
    status: "Status",
    aktiv: "active",
    stillgelegt: "retired",
  },
  sensoren: {
    einleitung:
      "Temperature and humidity, polled every five minutes. A value outside the configured " +
      "limits is shown in the warning colour.",
    misst: "Measuring …",
    jetztMessen: "Measure now",
    keinGeraet: "No device configured",
    keinGeraetText: "Sensors are created in the settings — host, identifier and community.",
    verlauf: "Over time",
    stunden: (n: number) => `${n} h`,
    tage: (n: number) => `${n} days`,
    temperatur: "Temperature",
    luftfeuchte: "Humidity",
    zuletzt: (zeit: string) => `Last ${zeit}`,
    keinMesswert: "No reading yet.",
    nichtsGemessen: "Nothing was measured in this period.",
    frisch: "current",
    verzoegert: "delayed",
    offline: "offline",
    unbekannt: "nothing measured yet",
  },
  hilfe: {
    einleitung:
      "What the platform can do, how the figures come about and what to do when something is " +
      "not right.",
    nurDeutsch: "The help pages themselves are written in German.",
    suchen: "Search the help",
    nichtsGefunden:
      "Nothing found. If something is missing from the help, say so with the Report button at the " +
      "bottom right.",
    alleThemen: "← All topics",
  },
  meldungen: {
    stand: (offen: number) => `What was reported from the views. ${offen} open`,
    neuSeit: (anzahl: number) => ` · ${anzahl} new since your last visit`,
    nichtsGemeldet: "Nothing reported",
    nichtsGemeldetText:
      "With the button at the bottom right, anyone signed in can report what is wrong on a page.",
    unbekannt: "unknown",
    bild: "Image",
    status: "Status",
    offen: "open",
    erledigt: "done",
    meldung: "Report",
    aufnahme: "Screenshot of the page",
  },
  auditAnsicht: {
    gibtEsNicht: "This audit does not exist",
    gibtEsNichtText: "It was probably removed.",
    internesAudit: "Internal audit",
    externesAudit: "External audit",
    prioritaet: (stufe: string) => ` · priority ${stufe}`,
    erledigt: (prozent: number) => ` · ${prozent} % done`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} overdue`,
    zurUebersicht: "To the overview",
    status: "Status",
    stammdaten: "Master data",
    titel: "Title",
    bereich: "Area",
    leitenderAuditor: "Lead auditor",
    auditteam: "Audit team",
    geplantVon: "Planned from",
    geplantBis: "Planned to",
    prioritaetFeld: "Priority",
    niedrig: "low",
    mittel: "medium",
    hoch: "high",
    auditziel: "Audit objective",
    kategorien: "Categories",
    kategorienHinweis:
      "An audit is often several things at once — the internal programme covers system and " +
      "process in one appointment. Hence multiple choice and not a single entry.",
    normbezug: "Standard reference",
    normmatrixLeer: "The standards matrix is empty — it is maintained in the settings.",
    nichtGeprueft: "* not yet checked against the consolidated standard text.",
    phasen: "Phases",
    keinePhasen: "No phases — this audit was created without a template.",
    phase: "Phase",
    verantwortlich: "Responsible",
    faellig: "Due",
    erledigtAm: "Done on",
    phaseErgaenzen: "Add phase",
    phaseBeispiel: "e.g. follow-up audit",
    verlauf: "History",
    verlaufHinweis:
      "Written by the database, not by this form — and afterwards neither changeable nor " +
      "deletable.",
    nichtsGeschehen: "Nothing has happened yet.",
    warumEntfaellt: "Why does this mandatory phase not apply?",
    uebernehmen: "Apply",
    abbrechen: "Cancel",
    angelegt: "created",
    geaendert: "changed",
    geloescht: "deleted",
    uebersprungen: "skipped",
  },
  maschine: {
    gibtEsNicht: "This machine does not exist",
    gibtEsNichtText: "It was probably deleted.",
    zurUebersicht: "To the overview",
    stammdaten: "Master data",
    name: "Name",
    inventarnummer: "Asset no.",
    standort: "Location",
    hersteller: "Manufacturer",
    modell: "Model",
    verantwortlich: "Responsible",
    status: "Status",
    aktiv: "active",
    stillgelegt: "retired",
    notizen: "Notes",
    wartungsaufgaben: "Maintenance tasks",
    jahr: "Year",
    halbjahr: "Half year",
    erstesHalbjahr: "W1–26",
    zweitesHalbjahr: "W27–52",
    wirdGebaut: "Building …",
    nachweisbogen: "Record sheet",
    neueAufgabe: "New task",
    aufgabeBeispiel: "e.g. check oil level",
    intervall: "Interval",
    wochen: "weeks",
    keineAufgabe: "No task yet — the sheet would stay empty.",
    aufgabe: "Task",
    dateien: "Files",
    planHinterlegen: "Add plan",
    nachweisAblegen: "Add record",
    dateienHinweis: "The manufacturer's plan and the signed sheets scanned back in.",
    keineDatei: "No file yet.",
    plan: "Plan",
    nachweis: "Record",
    laedt: "Uploading …",
    taeglich: "Daily",
    woechentlich: "Weekly",
    monatlich: "Monthly",
    quartalsweise: "Quarterly",
    alleNWochen: "Every N weeks",
    alleNWochenZahl: (wochen: number) => `Every ${wochen} weeks`,
  },
  atr: {
    einleitung:
      "The parts catalogue is the basis: a delivery note takes description, drawing and weight " +
      "from it. Matching goes by the part number without decoration — only the digits count.",
    zuLieferungen: "To the deliveries",
    teilAnlegen: "Add part by hand",
    teilBeispiel: "Part number, e.g. VR-1234-56",
    anlegen: "Create",
    wirdGelesen: "Reading …",
    mappeEinlesen: "Read in reference folder",
    suchen: "Search",
    suchePlatzhalter: "Part number, description or drawing",
    nichtsGefunden: "Nothing found",
    katalogLeer: "The catalogue is empty",
    keinTeil: "No part matches this search.",
    katalogLeerText: "Read in a reference folder or add a part by hand.",
    teilenummer: "Part number",
    bezeichnung: "Description",
    zeichnung: "Drawing",
    gewicht: "Weight kg",
    kategorie: "Category",
    nurErste: "Only the first 500 hits — please narrow the search.",
  },
  lieferungen: {
    einleitung:
      "A delivery note is read in, matched against the parts catalogue and stored as a draft. " +
      "After review it is released.",
    zumKatalog: "To the parts catalogue",
    wirdGelesen: "Reading …",
    einlesen: "Read in delivery note",
    laeuft: "Running …",
    eingangDurchsehen: "Check the inbox",
    berichtNummer: (nr: string) => ` · no. ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} lines, ${zugeordnet} found in the catalogue.`,
    keinLieferschein: "No delivery note yet",
    keinLieferscheinSchreiben: "Read in a delivery note PDF — it then waits here for review.",
    keinLieferscheinLesen: "As soon as a delivery note is read in, it appears here.",
    lieferschein: "Delivery note",
    datum: "Date",
    programm: "Programme",
    msn: "MSN",
    status: "Status",
    entwurf: "Draft",
    freigegeben: "released",
  },
  durchsicht: {
    nichtGefunden: "Delivery not found.",
    freigeben: "Release",
    zuruecknehmen: "Withdraw release",
    wirdErzeugt: "Creating …",
    dokumenteErzeugen: "Create documents",
    kopfdaten: "Header data",
    atrNummer: "ATR number",
    containernummer: "Container number",
    satzTitel: "Set description",
    programm: "Programme",
    msn: "MSN",
    bereich: "Area",
    wiegedatum: "Weighing date",
    pruefdatum: "Inspection date",
    qsUnterschrift: "QA signature",
    hoechstgewicht: "Max. weight kg",
    positionen: "Lines",
    pos: "No.",
    menge: "Qty",
    seriennummern: "Serial numbers",
    nichtImKatalog: "not in the catalogue",
    festHinweis:
      "The delivery is released; the lines are fixed. The database rejects a change — the " +
      "release can be withdrawn above.",
  },
  fair: {
    einleitung:
      "First article inspection: upload a drawing and put a numbered balloon on every dimension " +
      "to be checked. The database issues the numbers and keeps them gap-free.",
    bezeichnungFrei: "Description (empty = file name)",
    beispiel: "e.g. shaft 12×40, drawing 4711",
    wirdGeladen: "Uploading …",
    zeichnungWaehlen: "Choose drawing",
    keineZeichnung: "No drawing yet",
    keineZeichnungSchreiben: "Upload a PDF or image — then the dimensions can be ballooned.",
    keineZeichnungLesen: "As soon as a drawing is uploaded, it appears here.",
    bezeichnung: "Description",
    teilenummer: "Part number",
    kunde: "Customer",
    hochgeladen: "Uploaded",
    pruefliste: "Check list",
    einMass: "1 dimension",
    masse: (anzahl: number) => `${anzahl} dimensions`,
    kopieren: "Copy",
    csv: "CSV",
    keinMass: "No dimension marked yet.",
    nr: "No.",
    seite: "Page",
    wert: "Value",
    wertBeispiel: "e.g. 12.0 h7",
    wertZu: (nummer: number) => `Value for number ${nummer}`,
    nachOben: (nummer: number) => `Move number ${nummer} up`,
    nachUnten: (nummer: number) => `Move number ${nummer} down`,
    nummer: (nummer: number) => `Number ${nummer}`,
    drehen: "Rotate view",
    verkleinern: "Zoom out",
    vergroessern: "Zoom in",
    einpassen: "Fit",
    zeichnung: "Drawing",
    ladefehler: "The drawing could not be loaded.",
  },
  newsletter: {
    keineAusgabe: "No issue yet",
    keineAusgabeText: "As soon as the editors publish an issue, it appears here.",
    zurRedaktion: "To the editing view",
    quartalJahr: (quartal: number, jahr: number) => `Quarter ${quartal} · ${jahr}`,
    entwurfSuffix: " · draft",
    ausgabe: "Issue",
    quartalKurz: (quartal: number, jahr: number) => `Q${quartal} ${jahr}`,
    entwurfKlammer: " (draft)",
    alsPdf: "As PDF",
    wirdGesetzt: "Typesetting …",
    seiteVon: (nr: number, gesamt: number) => `Page ${nr} of ${gesamt} …`,
    redaktion: "Editing",
    niemandDazu: "Nobody joined in this quarter.",
    beitraege: "Articles",
    belegschaftInZahlen: "The workforce in figures",
    neuBeiUns: "New with us",
    redaktionEinleitung:
      "One issue per quarter. Chapters set the order in the booklet; it is published only when " +
      "it is finished.",
    zurLeseransicht: "To the reading view",
    jahr: "Year",
    quartal: "Quarter",
    ausgabeAnlegen: "Create issue",
    ausgabeBearbeiten: "Edit issue",
    keineAusgabeRedaktion: "Pick year and quarter and create — the chapters then appear here.",
    titelDerAusgabe: "Title of the issue",
    status: "Status",
    entwurf: "Draft",
    veroeffentlicht: "published",
    titelbild: "Cover",
    rueckseite: "Back page",
    ersetzen: ": replace",
    waehlen: ": choose",
    ausgabeLoeschen: (quartal: number, jahr: number) => `Issue Q${quartal} ${jahr}`,
    neuesKapitel: "New chapter",
    kapitelBeispiel: "e.g. From the shop floor",
    art: "Type",
    hinzufuegen: "Add",
    kapiteltitel: "Chapter title",
    kapitelHoch: "Move chapter up",
    kapitelRunter: "Move chapter down",
    ueberschrift: "Heading",
    eintrag: "Article",
    textMarkdown: "Text. Markdown is allowed — **bold**, lists, tables.",
    text: "Text",
    bild: "Image",
    bildGroesse: (nr: number) => `Size of image ${nr}`,
    nieEingefroren: "Nothing frozen yet — the chapter stays empty in the booklet.",
    kpiEingefroren: "The workforce figures for the quarter are frozen.",
    niemandEingefroren: "Frozen — nobody joined in this quarter.",
    zugaengeEingefroren: (anzahl: number) =>
      `Frozen: ${anzahl} new ${anzahl === 1 ? "joiner" : "joiners"} in the quarter.`,
    einfrieren: "Freeze",
    neuEinfrieren: "Freeze again",
    rechtFehlt: (quelle: string) => `The permission at the source is missing: view ${quelle}.`,
    quelleKpi: "metrics",
    quellePersonal: "people",
    ausgabeAngelegt: "Issue created.",
    ausgabeGeloescht: "Issue deleted.",
    kapitelAngelegt: "Chapter created.",
    standEingefroren: "State frozen.",
  },
  signage: {
    einleitung: "Media, playlists, schedules and devices of the screens.",
    bereiche: "Signage areas",
    medien: "Media",
    medienHinzu: "Add media",
    playlists: "Playlists",
    zeitplaene: "Schedules",
    geraete: "Devices",
    dateiZiehen: "Drag a file here",
    dateiWaehlen: "Choose file",
    dateiHinweis: "Image, video, PDF or PPTX, up to 50 MB",
    wirdUebertragen: "uploading …",
    art: "Type",
    webseite: "Web page (URL)",
    htmlSchnipsel: "HTML snippet",
    titel: "Title",
    titelBeispiel: "Birthdays",
    urlHinweis:
      "Give the full address. The player runs on its own port; relative paths do not work there.",
    aufnehmen: "Add",
    medienFehler: "The media could not be loaded.",
    keineMedien: "No media yet",
    keineMedienText:
      "Upload a file or add a URL. The media can then be put together into playlists.",
    erneut: "again",
    inVerwendung: "Medium is in use",
    inVerwendungText: (titel: string, anzahl: number) =>
      `“${titel}” is still part of ${anzahl} playlist(s). Remove it there first.`,
    verstanden: "Understood",
    wartet: "waiting",
    konvertiert: "converting",
    fertig: "done",
    fehlgeschlagen: "failed",
    keineHeartbeats: "No heartbeats recorded yet.",
    nieGesehen: "never seen",
    online: "online",
    vorMinuten: (minuten: number) => `${minuten} min ago`,
    offline: "offline",
    entzogen: "revoked",
    keinGeraet: "No device paired yet",
    keinGeraetText:
      "Start a screen with the player. It shows a six-character code that you enter here.",
    geraetKoppeln: "Pair device",
    geraet: "Device",
    status: "Status",
    verfuegbarkeit: "Availability 24 h",
    ausfaelle: "Outages 24 h",
    tags: "Tags",
    playlist: "Playlist",
    zuletztGesehen: "Last seen",
    seiteNeuLaden: "Reload page",
    neuStarten: "Restart device",
    bearbeiten: "Edit",
    zugangEntziehen: "Revoke access",
    geraetBearbeiten: "Edit device",
    name: "Name",
    bilddrehung: "Screen rotation",
    ton: "Sound",
    tonAktiv: "Sound on",
    abbrechen: "Cancel",
    speichern: "Save",
    tagsHinweis: "They decide which playlists and schedules this device gets.",
    entziehenText: (name: string) =>
      `“${name}” loses its access immediately and shows the pairing code again.`,
    neustartText: (name: string) => `“${name}” stays black for about a minute.`,
    geraetGespeichert: "Device saved.",
    geraetGeloescht: "Device deleted.",
    keinGeraetGewaehlt: "no device chosen",
    neuePlaylist: "New playlist",
    neuePlaylistText: "Set name and target tags. The entries come in the next step.",
    namensbeispiel: "Reception",
    keinePlaylist: "No playlist yet",
    keinePlaylistText:
      "A playlist bundles media in an order and is distributed to devices through tags.",
    playlistAnlegen: "Create playlist",
    aktiv: "Active",
    erstellt: "Created",
    kopieren: "Copy",
    playlistGeloescht: "Playlist deleted.",
    playlistKopiert: "Playlist copied. The entries are not copied along.",
    playlistInPlan: "Playlist has active schedules",
    zeitplanHinweis:
      "A schedule takes precedence over the plain tag assignment. Split windows across midnight " +
      "into two schedules.",
    wochentage: "Weekdays",
    wochentagKuerzel: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    von: "From",
    bis: "To",
    prioritaet: "Priority",
    zeitplanAktiv: "Schedule active",
    keineZeitplaene: "No schedules",
    keineZeitplaeneText:
      "Without a schedule the tag assignment alone decides which playlist a device shows. A " +
      "schedule puts a playlist in front of that on certain days and times.",
    tage: "Days",
    zeitfenster: "Time window",
    aktionen: "Actions",
    zeitplanBearbeiten: "Edit schedule",
    neuerZeitplan: "New schedule",
    zeitplaeneFehler: "The schedules could not be loaded.",
    endeNachStart: "The end must be after the start. Across midnight please create two schedules.",
    mindestensEinTag: "Choose at least one weekday.",
    playlistWaehlen: "Choose a playlist.",
    taeglich: "daily",
    zielTags: "Target tags",
    ueberblenden: "Cross-fade",
    harterSchnitt: "Hard cut",
    ziehpunkt: "Drag handle",
    verwerfen: "Discard",
    medienHinzufuegen: "Add media and order them with the drag handle.",
    mediumWaehlen: "Choose medium",
    mediumHinzufuegen: "Add medium",
    mediumWaehlenText: "The chosen medium is appended at the end of the playlist.",
    schliessen: "Close",
    keineMedienAnlegen: "There are no media yet. Create some under Media first.",
    unbekanntesMedium: "unknown medium",
    playlistGespeichert: "Playlist saved. The devices reload immediately.",
    kopplungscode: "Pairing code",
    codeBeispiel: "ABC-123",
    geraetename: "Device name",
    geraeteBeispiel: "Reception left",
    tagsPflicht: "The device gets its playlist through the tags. Without a tag the screen stays empty.",
    koppeln: "Pair",
    formatErwartet: "Format XXX-XXX expected.",
    codeUnbekannt: "Code unknown, expired or already taken. Have it shown again on the screen.",
    tagEingeben: "Type a tag and press Enter",
  },
  einstellungen: {
    titel: "Settings",
    einleitung: "What the platform calculates, fetches and shows — the same for everyone.",
    bereiche: "Areas",
    gruppen: {
      kennzahlen: "Metrics",
      kennzahlenText:
        "Targets for the dashboards. They appear as a target line in the chart and decide when a " +
        "tile warns.",
      personal: "People",
      personalText:
        "Which absences count as sickness and which departments belong to production. Without " +
        "these lists the people metrics stay empty.",
      atr: "ATR",
      atrText:
        "What is the same in every document of a programme, and where the delivery notes come from.",
      qualitaet: "Quality",
      qualitaetText:
        "The standards matrix an audit refers to, and the phase templates a new audit gets as a " +
        "checklist.",
      sensoren: "Sensors",
      sensorenText:
        "The measuring devices on the network: where they are, under which identifier they " +
        "deliver temperature and humidity, and when a value counts as too high.",
      zeugnisse: "References",
      zeugnisseText:
        "What is the same on every employment reference: company, place and the two signatures. " +
        "The line manager's is resolved from Personio when the document is created — what is " +
        "recorded here is only the fallback.",
      erscheinung: "Appearance",
      erscheinungText:
        "The company logo — top left in the application and in the header of every generated " +
        "file: induction plan, maintenance record, training overview, reference.",
      anzeigen: "Screens",
      anzeigenText:
        "The addresses running on the screens in the building. Each carries a signed token, is " +
        "valid for its one board only and expires.",
      zugaenge: "Users and groups",
      zugaengeText:
        "Create people, form groups and give them app permissions. Changes take effect the next " +
        "time the person signs in — the permissions sit in their token.",
    },
  },
  einstellungenText: {
    speichernFehler: (meldung: string) => `Saving failed: ${meldung}`,
    zielwertGespeichert: "Target saved. The dashboards show it after a reload.",
    zahlAbNull: "Please enter a number from 0 upwards.",
    personalGespeichert: "Saved. The people dashboard shows it after a reload.",
    krankTypen: "Absence types that count as sickness",
    produktionAbteilungen: "Departments belonging to production",
    kompetenzAttribute: "Personio fields that count as a recorded skill",
    ausDemBestand: "from the synced data",
    abteilungenBeispiel: "Production, Assembly",
    firmenlogo: "Company logo",
    anzeigenHinweis:
      "Creates the address for a playlist entry in the signage player. It is valid for the chosen " +
      "board only and expires — an entry nobody maintains any more stops showing by itself.",
    logoHinweis:
      "Appears top left in the application and in the header of every generated form — induction " +
      "plan, maintenance record, training overview, reference. PNG or JPEG, at most 5 MB. If none " +
      "is stored, the words “ACM-Plattform” appear instead.",
    communityHinweis: "is stored encrypted and never shown again",
    verwaltenSchliesstEin: "“Manage” on the platform tile includes every other permission.",
    logoAlt: "The stored company logo",
    keinsHinterlegt: "None stored yet.",
    laedt: "Uploading …",
    ersetzen: "Replace",
    hochladen: "Upload",
    logoHochladen: "Upload company logo",
    logoHinterlegt: "Logo stored.",
    anzeige: "Board",
    geburtstage: "Birthdays of the week",
    neuzugaenge: "New in the team",
    gueltigTage: "Valid for (days)",
    erzeugt: "Creating …",
    adresseErzeugen: "Create address",
    adresseKopiert: "Address copied.",
    kopierenFehler: "Copying did not work — please select it by hand.",
    kopieren: "Copy",
    gespeichert: "Saved.",
    speichern: "Save",
    speichert: "Saving …",
    firma: "Company",
    ort: "Place (above the date)",
    nameRueckfall: "Name (fallback)",
    titelRueckfall: "Title (fallback)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "Issuer profile",
    ausstellerHinweis:
      "Appears on every reference. The ACM letter template is used as soon as “ACM” is part of " +
      "the company name.",
    linkeUnterschrift: "Left signature — line manager",
    linkeHinweis:
      "Normally the person's supervisor; that one is resolved from Personio when the document is " +
      "created. What is recorded here only applies when Personio gives nothing — for externally " +
      "maintained people, for instance.",
    rechteUnterschrift: "Right signature — HR",
    rechteHinweis:
      "The same for all references. Bound to a person from Personio, the title comes from there " +
      "and stays right when the position changes.",
    personAusPersonio: "Person from Personio",
    keinePerson: "— none, use the free text below —",
    personenFehler: (meldung: string) => `The list of people could not be loaded (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "Templates",
    vorlagenHinweis:
      "One template per programme. Header data and skeleton file are the same in every ATR " +
      "document of that programme. A template is created when a reference folder is read in " +
      "under the parts catalogue.",
    keineVorlage: "No template yet",
    keineVorlageText: "Read in a reference folder — the programme is in cell D2 there.",
    geruestHinterlegt: "Skeleton file stored.",
    geruestErsetzen: "Replace skeleton",
    geruestWaehlen: "Choose skeleton",
    keineHinterlegt: "none stored yet",
    kunde: "Customer",
    lieferant: "Supplier",
    arbeitspaket: "Work package",
    referenz: "Reference",
    bestellerSpez: "Purchaser specification",
    lieferantenSpez: "Supplier specification",
    kundenSpez: "Customer specification",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "ATA chapter",
    waage: "Scales",
    qsUnterschrift: "QA signature",
    eingangsordner: "Inbox folder",
    eingangHinweis:
      "A delivery note in the inbox is read in, becomes a delivery and moves into the archive. " +
      "The service account's password is not kept here but as ATR_SMB_PASSWORT in the " +
      "environment; which hosts are eligible is set by ATR_SMB_ERLAUBT.",
    laeuft: "running",
    aus: "off",
    zuletzt: (zeit: string, text: string) => `Last ${zeit}: ${text}`,
    nochNichtGelaufen: "Has not run yet.",
    prueft: "Checking …",
    verbindungPruefen: "Check connection",
    laeuftGerade: "Running …",
    jetztDurchsehen: "Check now",
    verbindungSteht: (dateien: number) =>
      `Connection works. ${dateien} file${dateien === 1 ? "" : "s"} waiting in the inbox.`,
    keineVerbindung: (meldung: string) => `No connection: ${meldung}`,
    unbekannt: "unknown",
    gelesenAngelegt: (gelesen: number, angelegt: number) => `${gelesen} read, ${angelegt} created.`,
    rechner: "Host",
    rechnerHinweis: "must be listed in ATR_SMB_ERLAUBT",
    freigabe: "Share",
    domaene: "Domain",
    benutzer: "User",
    eingang: "Inbox",
    ausgang: "Outbox",
    archiv: "Archive",
    wasEinLaufTut: "What a run does",
    entwurfAnlegen: "Create a draft for review",
    dokumenteErzeugen: "Create documents and file them",
    regelmaessig: "Check regularly",
    regelmaessigHinweis: "Check regularly — every ten minutes, weekdays 5 am to 7 pm",
  },
  qualitaetEinstellungen: {
    normmatrix: "Standards matrix",
    normmatrixHinweis:
      "Clauses an audit refers to. A standard in use cannot be deleted — it is retired, " +
      "otherwise an audit would quietly lose its basis.",
    schonInMatrix: "This clause is already in the matrix.",
    regelwerk: "Standard",
    revision: "Revision",
    klausel: "Clause",
    kurztext: "Short text",
    kurztextBeispiel: "Internal audit",
    aufnehmen: "Add",
    geprueft: "Checked",
    aktiv: "Active",
    geprueftSchalter: (norm: string) => `${norm} checked`,
    aktivSchalter: (norm: string) => `${norm} active`,
    phasenvorlagen: "Phase templates",
    phasenvorlagenHinweis:
      "The sequence of steps a new audit receives. It is copied when the audit is created — a " +
      "later change does not rewrite any history.",
    neueVorlage: "New template",
    vorlageBeispiel: "System audit standard",
    anlegen: "Create",
    schritte: (anzahl: number) => `${anzahl} step${anzahl === 1 ? "" : "s"}`,
    schrittErgaenzen: "Add step",
    schrittBeispiel: "e.g. opening meeting",
  },
  sensorEinstellungen: {
    neuesGeraet: "New device",
    name: "Name",
    nameBeispiel: "Server room",
    rechner: "Host",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "must be listed in SNMP_ERLAUBT",
    community: "Community",
    port: "Port",
    kennungTemperatur: "Temperature OID",
    kennungLuftfeuchte: "Humidity OID",
    faktorTemperatur: "Temperature factor",
    faktorHinweis: "0.1 when the device reports tenths of a degree as a whole number",
    faktorLuftfeuchte: "Humidity factor",
    temperaturAb: "Temperature from (°C)",
    temperaturBis: "Temperature to (°C)",
    feuchteAb: "Humidity from (%)",
    feuchteBis: "Humidity to (%)",
    farbe: "Colour in the chart",
    farbeHinweis: "e.g. #0f6e8c",
    optional: "optional",
    anlegen: "Create",
    fragt: "Polling …",
    ausprobieren: "Try it",
    keinGeraet: "No device yet",
    keinGeraetText: "Enter host, community and at least one OID above.",
    wirdAbgefragt: (name: string) => `${name} is polled`,
    communityErsetzen: "Replace community",
    unveraendert: "unchanged",
    communityErsetzt: "Community replaced.",
    sensorAngelegt: "Sensor created.",
    sensorGeloescht: "Sensor deleted, together with its time series.",
    zahlEingeben: "Please enter a number.",
  },
  zugaenge: {
    gruppeAngelegt: "Group created.",
    gruppeGibtEsSchon: "A group with this name already exists.",
    personAngelegt: "Person created",
    gruppeUmbenannt: "Group renamed.",
    gruppeGeloescht: "Group deleted.",
    mitgliedHinzu: "Member added. It takes effect at the next sign-in.",
    schonInGruppe: "This person is already in the group.",
    neuesPasswort: "New password",
    mitgliedEntfernt: "Member removed. It takes effect at the next sign-in.",
    gemeldeteSeiten: "View reported pages",
    neueGruppe: "New group",
    gruppeBeispiel: "e.g. Inside sales",
    anlegen: "Create",
    neuePerson: "New person",
    personBeispiel: "first.last@acm.local",
    keineGruppe: "No group yet",
    keineGruppeText: "Create a group, give it app permissions and add people.",
    verzeichnis: "Directory",
    ausVerzeichnis: "Comes from the directory",
    umbenennen: "Rename",
    keinZugriff: "no access",
    rechteAnGruppe: "Permissions belong to the group, not to the person.",
    passwortNurJetzt:
      "The password is shown only now. Afterwards it can only be reset, not displayed.",
    fertig: "Done",
    anmeldung: "Sign-in",
    passwort: "Password",
    gruppeUmbenennen: "Rename group",
    abbrechen: "Cancel",
    speichern: "Save",
    gruppenname: "Group name",
    mitgliederVon: (name: string) => `Members of “${name}”`,
    wirktNachAnmeldung: "Changes take effect the next time the person signs in.",
    schliessen: "Close",
    personHinzufuegen: "Add person",
    auswaehlen: "— choose —",
    hinzufuegen: "Add",
    keineMitglieder: "This group has no members yet.",
    passwortZuruecksetzen: "Reset password",
    mitgliedEntfernen: "Remove member",
    entfernen: "Remove",
  },
  kopftitel: {
    start: "Apps",
    kennzahlen: "KPI dashboard",
    offeneSchulungen: "Outstanding training",
    schulungsmatrix: "Training matrix",
    atrLieferungen: "ATR deliveries",
  },
  kennzahlenHub: {
    titel: "KPI dashboard",
    einleitung: "Metrics by department. The data comes from the ERP exports under Uploads.",
    nochNicht: "not ported yet",
    bereiche: {
      vertrieb: "Revenue, order value, customer share",
      personal: "Headcount, turnover, sickness — separate permission",
      qualitaet: "Audit findings and complaint rate",
      finanzen: "Material and personnel cost ratio",
      einkauf: "Supplier delivery reliability",
      produktion: "Delays, overdue orders",
      bewertung: "Comments and actions for every metric",
    },
  },
  erklaerung: {
    frage: (titel: string) => `How is “${titel}” calculated?`,
    knopf: "Calculation",
    untertitel: "How this is calculated",
    ganzeSeite: "Full help page",
  },
};
