import type { Texte } from "@/texte/de";

/**
 * Die persischen Texte der Oberfläche. Maschinell übersetzt — vor dem
 * Ausrollen sollte jemand darüberlesen, der die Sprache spricht.
 */
export const fa: Texte = {
  kopf: {
    benutzermenue: "منوی کاربر",
    angemeldetAls: "واردشده با",
    uebersicht: "به نمای کلی",
    hilfe: "راهنما",
    einstellungen: "تنظیمات",
    abmelden: "خروج",
    sprache: "زبان",
    erscheinungsbild: "ظاهر",
    hell: "روشن",
    dunkel: "تیره",
    system: "مانند سامانه",
    meldungenLeer: "App Feedback — چیز تازه‌ای نیست",
    meldungen: (anzahl: number) => `App Feedback — ${anzahl} مورد دیده‌نشده`,
    massnahmenLeer: "اقدام‌ها — موردی باز نیست",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `اقدام‌ها — ${offen} باز، ${ueberfaellig} مورد با تأخیر`
        : `اقدام‌ها — ${offen} باز`,
    navigation: "پیمایش",
    einklappen: "جمع کردن نوار کناری",
    ausklappen: "گسترش نوار کناری",
    navigationOeffnen: "باز کردن پیمایش",
    navigationSchliessen: "بستن پیمایش",
    unterseitenZeigen: (name: string) => `${name}: نمایش زیرصفحه‌ها`,
    unterseitenVerbergen: (name: string) => `${name}: پنهان کردن زیرصفحه‌ها`,
    werkzeuge: "فیلترها و اقدامات",
    werkzeugeEinklappen: "جمع کردن نوار فیلتر",
    werkzeugeAusklappen: "گسترش نوار فیلتر",
    werkzeugeOeffnen: "باز کردن فیلترها",
    werkzeugeSchliessen: "بستن فیلترها",
    kategorien: {
      navigation: "پیمایش",
      ansicht: "نما",
      filter: "فیلترها",
      zeitraum: "بازهٔ زمانی",
      aktionen: "اقدامات",
    },
    auchGeoeffnet: (namen: string) => `همچنین باز توسط ${namen}`,
    konflikt: "در این فاصله کس دیگری آن را تغییر داده است — وضعیت فعلی بارگذاری شد.",
    geloeschtVonAnderen: "در این فاصله کس دیگری آن را حذف کرده است.",
  },
  pfad: {
    aria: "مسیر",
    start: "خانه",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "محموله‌ها",
      "/atr/teilekatalog": "کاتالوگ قطعات",
      "/einstellungen": "تنظیمات",
      "/fair": "FAIR",
      "/hilfe": "راهنما",
      "/hr": "HR",
      "/hr/dokumente": "گردش مدارک",
      "/hr/einarbeitung": "آشناسازی",
      "/hr/kennzahlen": "شاخص‌ها",
      "/hr/kompetenzen": "صلاحیت‌ها",
      "/hr/onboarding": "ورود کارکنان",
      "/hr/organigramm": "چارت سازمانی",
      "/hr/schulungen": "آموزش‌ها",
      "/hr/schulungen/matrix": "ماتریس",
      "/hr/schulungen/offen": "باقی‌مانده",
      "/hr/zeugnisse": "گواهی‌های کار",
      "/kpi": "شاخص‌ها",
      "/kpi/bewertung": "ارزیابی KPI و اقدام‌ها",
      "/kpi/einkauf": "خرید",
      "/kpi/finanzen": "مالی",
      "/kpi/produktion": "تولید",
      "/kpi/qualitaet": "کیفیت",
      "/kpi/vertrieb": "فروش",
      "/newsletter": "خبرنامه",
      "/newsletter/redaktion": "تحریریه",
      "/platform/feedback": "App Feedback",
      "/produktion": "تولید",
      "/qualitaet": "کیفیت",
      "/sensoren": "حسگرها",
      "/signage": "Digital Signage",
      "/signage/devices": "دستگاه‌ها",
      "/signage/media": "رسانه‌ها",
      "/signage/pair": "جفت‌سازی",
      "/signage/playlists": "فهرست‌های پخش",
      "/signage/schedules": "زمان‌بندی‌ها",
      "/uploads": "بارگذاری‌ها",
    },
  },
  start: {
    titel: "برنامه‌ها",
    verweigert: (name: string) => `برای «${name}» دسترسی ندارید.`,
    keineApp:
      "هنوز هیچ برنامه‌ای به حساب شما اختصاص نیافته است. لطفاً با مدیریت پلتفرم تماس بگیرید.",
  },
  anmeldung: {
    benutzer: "کاربر",
    lokalWechseln: "ورود محلی",
    adWechseln: "ورود با حساب AD",
    titel: "ACM-Plattform",
    aufforderung: "با حساب خود وارد شوید.",
    email: "ایمیل",
    passwort: "گذرواژه",
    knopf: "ورود",
    laeuft: "در حال ورود …",
  },
  allgemein: {
    laedt: "در حال بارگذاری …",
    speichern: "ذخیره",
    abbrechen: "انصراف",
    loeschen: "حذف",
    stueck: "عدد",
    loeschenTitel: "تأیید حذف",
    loeschenFrage: (was: string) => `«${was}» برای همیشه حذف می‌شود.`,
    loeschenKnopf: (was: string) => `حذف ${was}`,
  },
  zeitraum: {
    aria: "بازهٔ زمانی",
    monat: "این ماه",
    quartal: "این فصل",
    jahr: "امسال",
    alles: "همهٔ زمان‌ها",
    frei: "انتخاب بازه",
    von: "از",
    bis: "تا",
    vonAria: "بازه از",
    bisAria: "بازه تا",
    verdreht: "پایان پیش از آغاز است.",
  },
  vergleich: {
    zu: (was: string) => `نسبت به ${was}`,
    quartal: (q: number) => `فصل ${q}`,
    jahr: (j: number) => `${j}`,
    keinWert: "مقداری برای مقایسه نیست: داده‌های دورهٔ مقایسه ناقص است یا مقدار صفر بوده است.",
    gestiegen: "افزایش",
    gesunken: "کاهش",
    unveraendert: "بدون تغییر",
  },
  diagramm: {
    art: "نوع نمودار",
    balken: "ستونی",
    flaeche: "سطحی",
  },
  tabelle: {
    suche: "جستجو",
    sucheAria: "جستجو در جدول",
    sucheLeeren: "پاک کردن جستجو",
    keineTreffer: "برای این جستجو نتیجه‌ای نیست.",
    leer: "موردی وجود ندارد.",
    bereich: (von: number, bis: number, gesamt: number) => `${von}–${bis} از ${gesamt}`,
    seite: (seite: number, seiten: number) => `صفحه ${seite} از ${seiten}`,
    zurueck: "صفحه قبل",
    weiter: "صفحه بعد",
    sortieren: (spalte: string) => `مرتب‌سازی بر اساس «${spalte}»`,
    seitengroesse: "تعداد ردیف جدول در هر صفحه",
    seitengroesseText: "برای همه جدول‌های پلتفرم و همه افراد اعمال می‌شود.",
    gespeichert: "اندازه صفحه ذخیره شد.",
  },
  datenstand: {
    teilweise: "به‌طور جزئی وارد شده",
    stand: (datum: string, alter: string) => `داده‌ها تا ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `داده‌ها ناقص است — ${anzahl} مورد موجود نیست: ${fehlend}`,
    heute: "امروز",
    gestern: "دیروز",
    vorTagen: (tage: number) => `${tage} روز پیش`,
    nie: "هرگز",
    arten: {
      umsatz: "درآمد",
      auftraege: "سفارش‌ها",
      angebote: "پیشنهادهای قیمت",
      interessenten: "مشتریان بالقوه",
      kontakte: "تماس‌ها",
      liefertreue: "پایبندی به موعد تحویل",
      lagerbewegungen: "گردش انبار",
      materialpreise: "قیمت مواد",
      lagerpreise: "قیمت‌های انبار",
      auftragspositionen: "اقلام سفارش",
      lieferscheine: "برگه‌های تحویل",
      pruefungen: "بازرسی‌ها",
      acht_d: "گزارش‌های 8D",
      wareneingaenge: "رسید کالا",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `شاخص‌ها بارگذاری نشد: ${meldung}`,
    keineDatenTitel: "برای این بازه داده‌ای موجود نیست",
    keineDatenVor: "خروجی‌های ERP را در ",
    keineDatenNach: " بارگذاری کنید، یا بازهٔ بزرگ‌تری برگزینید.",
    keineWerte: "مقداری در این بازه نیست",
    laedt: "در حال بارگذاری …",
    jeTag: "روزانه",
    jeWoche: "هفتگی",
    jeMonat: "ماهانه",
  },
  vertrieb: {
    umsatz: "درآمد",
    umsatzHinweis: "فاکتورها منهای برگه‌های بستانکار",
    auftragswert: "میانگین ارزش سفارش",
    ueberNull: "سفارش‌های بیش از 0 €",
    auftraege: "کل سفارش‌ها",
    verlauf: "روند درآمد",
    verlaufHinweis: (takt: string) => `${takt}، با کسر برگه‌های بستانکار`,
    kundenanteil: "سهم مشتریان از درآمد",
    kunde: "مشتری",
    anteil: "سهم",
    uebrige: "سایر",
    jeErfasser: "سفارش‌ها به تفکیک ثبت‌کننده",
    erfasser: "ثبت‌کننده",
    anzahl: "سفارش‌ها",
    summe: "جمع",
    einzelauftraege: "سفارش‌های تکی",
    einzelauftraegeHinweis: "سفارش‌های بیش از 0 € در این بازه — همان‌هایی که «کل سفارش‌ها» می‌شمارد",
    auftragsNr: "شمارهٔ سفارش",
    datum: "تاریخ",
    gesamt: "جمع کل",
    kundenanteilAuftraege: "سهم مشتریان از سفارش‌ها",
    kundenanteilAuftraegeHinweis: "ارزش سفارش‌ها به تفکیک مشتری",
    kundenanteilRechnungen: "سهم مشتریان از فاکتورها",
    kundenanteilRechnungenHinweis: "فاکتورها منهای برگه‌های بستانکار به تفکیک مشتری",
    restkunden: (anzahl: number) => `سایر مشتریان (${anzahl})`,
    rest: "سایر",
    weitereKunden: (anzahl: number) => `نمایش ${anzahl} مورد دیگر`,
    nurTop3: "فقط ۳ مورد نخست",
    umsatzIn: (zeitraum: string) => `درآمد ${zeitraum}`,
  },
  aktivitaet: {
    titel: "فعالیت فروش",
    jeWoche: (von: string, bis: string) => `به تفکیک هفتهٔ تقویمی، ${von} تا ${bis}`,
    ladeFehler: (meldung: string) => `فعالیت فروش بارگذاری نشد: ${meldung}`,
    leer: "در این بازه تماس، پیشنهاد قیمت یا مشتری بالقوه‌ای نیست.",
    kw: (woche: string) => `هفتهٔ ${woche}`,
    ziel: (wert: string) => `هدف ${wert} در هفته`,
    erstkontakte: "تماس‌های نخست",
    erstkontakteHinweis: "تماس‌های انجام‌شده از نوع ERS",
    besuche: "بازدیدها",
    besucheHinweis: "حضوری و برخط جداگانه",
    besucheOrt: "حضوری",
    besucheOnline: "برخط",
    interessenten: "مشتریان بالقوه",
    interessentenHinweis: "تازه ثبت‌شده، بدون تخصیص به فروشنده",
    angebote: "پیشنهادهای قیمت",
    angeboteHinweis: "جمع پیشنهادهای صادرشده",
    auftragseingang: "سفارش‌های دریافتی",
    auftragseingangHinweis: "با کسر ابطال‌ها",
  },
  einkauf: {
    keineDaten: "برای این بازه قلم تحویلی موجود نیست",
    ladeVor: "خروجی پایبندی به موعد تحویل را در ",
    ladeNach: " بارگذاری کنید.",
    otd: "نرخ OTD",
    otdHinweis: (ziel: string) => `هدف ${ziel} · به‌موقع: تأخیر ≤ 0`,
    puenktlich: "اقلام به‌موقع",
    gesamt: "کل اقلام",
    verzugSchnitt: "میانگین تأخیر",
    verzugHinweis: "بدون اقلام فاقد مقدار تأخیر",
    verlauf: "روند نرخ OTD",
    verlaufHinweis: "شکاف‌ها بازه‌هایی بدون قلم تحویلی هستند.",
    verlaufTooltip: (positionen: string) => `OTD (${positionen} قلم)`,
    ziellinie: "هدف",
    ladenhueter: "سفارش برای انبار — اقلام راکد",
    kapital: (wert: string) => `سرمایهٔ خوابیده: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `اقلام انبار که دست‌کم ${tage} روز بی‌حرکت مانده‌اند، بیشترین ارزش نخست. ` +
      "مبنا امروز است — بازهٔ بالا اینجا اثری ندارد، چون موجودی یک بازه نیست.",
    artikel: "کالا",
    bezeichnung: "شرح",
    bestand: "موجودی",
    liegtSeit: "راکد از",
    stueckpreis: "قیمت واحد",
    wert: "ارزش",
    positionen: "اقلام تحویل",
    positionenHinweis: "بیشترین تأخیر نخست، اقلام بدون مقدار تأخیر در بالا.",
    auftrag: "سفارش",
    lieferant: "تأمین‌کننده",
    zieltermin: "موعد مقرر",
    geliefert: "تحویل‌شده",
    verzug: "تأخیر",
    menge: "مقدار",
  },
  produktion: {
    keineDaten: "در این بازه سفارشی با نتیجهٔ روشن موجود نیست",
    ladeVor: "اقلام سفارش و برگه‌های تحویل را در ",
    ladeNach:
      " بارگذاری کنید. هر دو لازم‌اند: یکی موعد مقرر را دارد و دیگری تاریخ واقعی را.",
    quote: "نرخ تأخیر",
    quoteHinweis: (ziel: string) => `حداکثر ${ziel}`,
    inVerzug: "سفارش‌های دارای تأخیر",
    davonOffen: (anzahl: string) => `از جمله ${anzahl} باز و سررسیدگذشته`,
    gesamt: "کل سفارش‌ها",
    gesamtHinweis: "بدون سفارش‌های باز سررسیدنشده",
    verzugSchnitt: "میانگین تأخیر",
    verzugHinweis: "سفارش‌های به‌موقع منفی حساب می‌شوند",
    verlauf: "روند نرخ تأخیر",
    verlaufHinweis: "بر پایهٔ موعد مقرر. شکاف‌ها بازه‌هایی بدون سفارش شمرده‌شده هستند.",
    verlaufTooltip: (auftraege: string) => `تأخیر (${auftraege} سفارش)`,
    ziellinie: "هدف",
    ansicht: "نمای سفارش‌ها",
    ansichtVerzug: "سفارش‌های دارای تأخیر",
    ansichtUeberfaellig: "سفارش‌های باز سررسیدگذشته",
    hinweisVerzug: "پس از موعد مقرر تحویل شده، بیشترین تأخیر نخست.",
    hinweisUeberfaellig: "بدون برگهٔ تحویل و با موعد گذشته — هر روز بیشتر می‌شود.",
    leerVerzug: "هیچ سفارشی از این بازه با تأخیر تحویل نشده است.",
    leerUeberfaellig: "هیچ سفارش بازی از این بازه از موعد نگذشته است.",
    auftrag: "سفارش",
    kunde: "مشتری",
    zieltermin: "موعد مقرر",
    geliefert: "تحویل‌شده",
    verzug: "تأخیر",
    tageUeberfaellig: "روزهای گذشته از موعد",
  },
  finanzen: {
    keineDatenVor:
      "سه فایل لازم است: گردش انبار برای مصرف، قیمت مواد (رسید کالا) برای قیمت‌ها و درآمد " +
      "به‌عنوان مبنا. هر سه در ",
    keineDatenNach: " هستند.",
    materialquote: "نسبت هزینهٔ مواد",
    materialquoteHinweis: "هزینهٔ مواد / درآمد",
    hoechstens: (ziel: string) => `حداکثر ${ziel}`,
    materialkosten: "هزینهٔ مواد",
    umsatz: "درآمد",
    personalquote: "نسبت هزینهٔ پرسنل",
    brauchtZeitraum: "نیازمند یک بازه است",
    ohnePreis: "کالاهای بدون قیمت",
    ohnePreisHinweis: "مصرف‌شده، اما ارزش‌گذاری نشده",
    jeAbteilung: "هزینهٔ پرسنل به تفکیک بخش",
    abteilung: "بخش",
    personen: "نفرات",
    kosten: "هزینه",
    anteil: "سهم",
    verlauf: "روند نسبت هزینهٔ مواد",
    verlaufHinweis: "شکاف‌ها بازه‌هایی بدون درآمد هستند — بدون مبنا نسبتی به دست نمی‌آید.",
    ziellinie: "هدف",
    verbrauch: "مصرف مواد به تفکیک کالا",
    verbrauchHinweis: "بیشترین هزینه نخست. کالاهای بدون قیمت در پایان می‌آیند — در نسبت وارد نمی‌شوند.",
    artikel: "کالا",
    bezeichnung: "شرح",
    menge: "مصرف",
    stueckpreis: "قیمت واحد",
    keinPreis: "بدون قیمت",
    ansicht: "نما",
    ansichtMaterial: "مواد",
    ansichtPersonal: "پرسنل",
    personalkosten: "هزینهٔ پرسنل",
    personalquoteHinweis: "هزینهٔ پرسنل / درآمد",
    mitarbeiter: "کارکنان",
    mitarbeiterHinweis: "دارای هزینه در بازه",
    personalVerlauf: "روند نسبت هزینهٔ پرسنل",
    quoteBeiKosten: (kosten: string) => `نسبت با هزینهٔ ${kosten}`,
  },
  qualitaet: {
    auditart: "نوع ممیزی:",
    reklamationsart: "نوع شکایت",
    keineArt: "هیچ نوع ممیزی برگزیده نشده است. دست‌کم یکی را برگزینید، وگرنه چیزی برای شمردن نیست.",
    keineDaten: "برای این بازه یافتهٔ ممیزی موجود نیست",
    ladeVor: "خروجی 8D را در ",
    ladeNach: " بارگذاری کنید.",
    behoerde: "نهاد نظارتی",
    extern: "تأمین‌کننده فرعی",
    intern: "درونی",
    kunde: "مشتری",
    level1: "یافته‌های ممیزی سطح 1",
    level2: "یافته‌های ممیزی سطح 2",
    ohneLevel: "بدون سطح قابل تشخیص",
    ohneLevelHinweis: "در هیچ کارتی شمرده نمی‌شود",
    hoechstens: (ziel: number) => `حداکثر ${ziel}`,
    auditVerlauf: "روند یافته‌های ممیزی",
    auditVerlaufLevel: (level: number) => `یافته‌های ممیزی سطح ${level} در طول زمان`,
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `سهم مقدار بدون شکایت. مبنا: ${bezug}.`,
    fehlerquote: (quote: string) => `نرخ خطا: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `نرخ خطا: ${quote} · هدف ${ziel}`,
    reklamiert: "مقدار شکایت‌شده",
    bezugsmenge: "مقدار مبنا",
    bezugsmengeNull: "بدون آن نرخی به دست نمی‌آید",
    mehrAlsBezogen:
      "مقدار شکایت‌شده بیش از مقدار دریافتی است. محاسبه این را حل نمی‌کند: صورت و " +
      "مخرج از فایل‌های جداگانه با تاریخ‌های خودشان می‌آیند. بررسی کنید که فایل مبنا " +
      "برای این بازه کامل بارگذاری شده باشد.",
    reklKunde: "مشتری",
    reklIntern: "درونی",
    reklLieferant: "تأمین‌کنندگان مواد",
    reklWerkbank: "کارگاه‌های پیمانکار",
    bezugKunde: "مقدار تحویل‌شده",
    bezugIntern: "مقدار تحویل‌شده",
    bezugLieferant: "رسید کالا بدون خدمات",
    bezugWerkbank: "رسید کالا از گروه کالایی DIENST و SERVIC",
    mengeGesamt: "مقدار اعلام‌شده",
    mengeAkzeptiert: "مقدار پذیرفته‌شده",
    onQualityBezug: (menge: string) => `On Quality (مبنا ${menge})`,
    ziellinie: "هدف",
    geprueft: "محصولات بازرسی‌شده",
    geprueftHinweis: "مقدار به ازای هر روز-بازرس. هر اندازه بر روزهایی تقسیم می‌شود که کسی آن را بازرسی کرده است؛ مجموع بر همهٔ آن‌ها.",
    gross: "محصولات بزرگ",
    klein: "محصولات کوچک",
    mindestens: (ziel: number) => `دست‌کم ${ziel} در هر روز و برای هر بازرس`,
    buchungen: "ثبت‌های بازرسی کیفیت",
    buchungenHinweis: "ثبت کنارگذاشته‌شده در فهرست می‌ماند اما در هیچ کارتی شمرده نمی‌شود.",
    zaehltMit: "شمرده می‌شود",
    datum: "تاریخ",
    pruefer: "بازرس",
    produkt: "محصول",
    groesse: "اندازه",
    menge: "مقدار",
    ausschuss: "ضایعات",
    mitzaehlen: (datum: string) => `ثبت مورخ ${datum} شمرده شود`,
    klasseGross: "بزرگ",
    klasseKlein: "کوچک",
    diagnose: "یافته‌های بدون سطح قابل تشخیص",
    diagnoseHinweis:
      "سطح در فایل مبدأ در متن آزاد آمده است. اگر نه «Major … Level 1» باشد و نه " +
      "«Minor … Level 2»، یافته هیچ‌جا شمرده نمی‌شود. این فهرست نشان می‌دهد کجا باید اصلاح شود.",
    bericht: "گزارش",
    art: "نوع",
    adresse: "نشانی",
    bezeichnung: "شرح",
    ansicht: "نما",
    ansichtAudits: "ممیزی‌ها",
    ansichtReklamationen: "شکایت‌ها",
    ansichtPruefung: "بازرسی کیفیت",
    artikelart: "نوع کالا",
    artikelFertig: "کالای ساخته‌شده",
    artikelHalbfertig: "کالای نیمه‌ساخته",
    artikelAlle: "همهٔ کالاها",
    gesamt: "مجموع",
    pruefVerlauf: (klasse: string) => `روند ${klasse}`,
    personentage: (anzahl: string) => `${anzahl} روز-بازرس`,
    findings: "نمای کلی یافته‌ها",
    nr: "شماره",
    kategorie: "دسته",
    level: "سطح",
    aussteller: "صادرکننده",
    quelle: "منبع",
    status: "وضعیت",
    reklListe: (art: string) => `شکایت‌ها · ${art}`,
    akzMenge: "مقدار پذیرفته",
    artikel: "کالا",
  },
  personal: {
    uebersicht: "نمای کلی",
    keinAbgleich: "هنوز همگام‌سازی‌ای انجام نشده است. هر شب ساعت 02:15 خودبه‌خود اجرا می‌شود.",
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} نفر، ${anwesenheiten} حضور، ${abwesenheiten} غیبت`,
    abgleichLaeuft: "در حال اجرا …",
    abgleichen: "اکنون همگام‌سازی کن",
    keineDaten: "برای این بازه حضوری ثبت نشده است",
    keineDatenHinweis:
      "یا همگام‌سازی Personio هنوز اجرا نشده، یا بازه پیش از آغاز ثبت قرار دارد.",
    ueberstunden: "نرخ اضافه‌کاری",
    stundenVon: (teil: string, ganz: string) => `${teil} از ${ganz} ساعت`,
    krankheit: "نرخ بیماری",
    krankheitsartenFehlen: "انواع بیماری ثبت نشده است",
    fluktuation: "ترک خدمت",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} خروج، میانگین ${schnitt} شاغل`,
    personen: "افراد ثبت‌شده",
    personenHinweis: "با حضور در این بازه",
    krankheitHinweisVor:
      "نرخ بیماری تا زمانی خالی می‌ماند که ثبت نشده باشد کدام انواع غیبت در Personio " +
      "بیماری به شمار می‌آیند. باید در ",
    krankheitHinweisNach: " ثبت شود.",
    verlauf: "روند",
    reiheUeberstunden: "اضافه‌کاری",
    reiheKrankheit: "بیماری",
    umsatzJeKopf: "درآمد / کارمند تولید",
    umsatzJeKopfHinweis: (auftraege: string, koepfe: string) => `${auftraege} سفارش ÷ ${koepfe} نفر`,
    produktionFehlt: "بخش‌های تولید تعیین نشده‌اند",
    letzterErfolg: (datum: string, alter: string) => `آخرین موفقیت: ${datum} (${alter})`,
    abgleichStand: (datum: string, alter: string) => `همگام‌سازی Personio ${datum} (${alter})`,
    abgleichFehler: "با خطا",
    reiheUmsatzJeKopf: "درآمد برای هر کارمند تولید",
    ziel: (wert: string) => `هدف ${wert}`,
  },
  melden: {
    knopf: "ارسال App Feedback",
    titel: "ارسال App Feedback",
    frage: "در این صفحه چه چیزی درست نیست؟ تصویری از صفحه همراه می‌رود.",
    abbrechen: "انصراف",
    senden: "ارسال",
    sendet: "در حال ارسال …",
    beispiel: "برای نمونه: کارت مقدار خالی نشان می‌دهد، با آنکه داده موجود است.",
    beschreibung: "شرح",
    aufnahme: "تصویر صفحه",
    gehtMit: "این تصویر همراه می‌رود.",
    nimmtAuf: "صفحه در حال تصویربرداری است …",
    misslungen: "تصویربرداری از صفحه ممکن نشد — بازخورد بدون تصویر می‌رود.",
    dankeMitBild: "سپاسگزاریم — بازخورد رسید.",
    dankeOhneBild: "سپاسگزاریم — بازخورد رسید، بدون تصویر صفحه.",
  },
  belegschaft: {
    zeitpunkt: "تاریخ مرجع",
    aktuell: "کنونی",
    quartal: "سه‌ماهه",
    titel: "نیروی انسانی",
    ladeFehler: (meldung: string) => `نیروی انسانی بارگذاری نشد: ${meldung}`,
    beschaeftigte: "شاغلان",
    beschaeftigteHinweis: "بر پایهٔ وضعیت «فعال» در Personio",
    stichtagHinweis:
      "شمار کارکنان و جدید/موجود تا تاریخ مرجع دقیق است؛ توزیع‌ها از داده‌های امروز Personio استفاده می‌کنند (بدون تاریخچهٔ کامل).",
    neuImQuartal: "تازه‌واردان این فصل",
    bestand: "تعداد کل",
    kompetenzen: "صلاحیت‌های ثبت‌شده",
    felderFehlen: "فیلدها ثبت نشده‌اند — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} از ${aktive} بر پایهٔ تاریخ ورود و خروج`,
    geschlecht: "جنسیت",
    beschaeftigungsart: "نوع اشتغال",
    abteilungen: "بخش‌ها",
    maennlich: "مرد",
    weiblich: "زن",
    divers: "دیگر",
    unbekannt: "نامشخص",
    vollzeit: "تمام‌وقت",
    teilzeit: "پاره‌وقت",
    geringfuegig: "کم‌ساعت",
    extern: "بیرونی",
  },
  mitarbeiter: {
    titel: "کارمندان",
    person: "نفر",
    abteilung: "بخش",
    istStunden: "ساعت کارکرد",
    ueberstunden: "اضافه‌کاری",
    quote: "٪ اضافه‌کاری",
    auswahl: "انتخاب",
    mitUeberstunden: "دارای اضافه‌کاری",
    aktive: "فعال‌ها",
    alle: "همه",
    name: "نام",
    position: "سمت",
    status: "وضعیت",
    wochenstunden: "ساعت/هفته",
    leer: "هیچ‌کس در این انتخاب نیست.",
    statusWert: { active: "فعال", inactive: "غیرفعال", onboarding: "در حال ورود", leave: "در مرخصی" },
  },
  wochenbericht: {
    titel: "گزارش هفتگی",
    ladeFehler: (meldung: string) => `گزارش هفتگی بارگذاری نشد: ${meldung}`,
    kalenderwoche: "هفتهٔ تقویمی",
    kw: (woche: string, jahr: string) => `هفتهٔ ${woche} / ${jahr}`,
    keineDaten: "برای این هفته حضوری ثبت نشده است.",
    saldo: "ماندهٔ اضافه‌کاری",
    saldoHinweis: (personen: string) => `کارکرد منهای موظفی مؤثر، برای همهٔ ${personen} نفر`,
    ueberSoll: "بالاتر از موظفی",
    ueberSollHinweis: (gesamt: string) => `از ${gesamt} نفر دارای ثبت ورود`,
    krankheit: "بیماری",
    tage: "روز",
    stunden: "ساعت",
    krankheitHinweis: "بر روزهای تقویمی غیبت پخش شده است",
    ist: "کارکرد",
    soll: "موظفی",
    saldoSpalte: "مانده",
    fussnote:
      "موظفی، موظفی مؤثر هفته است: مرخصی و بیماری کسر شده‌اند و هرکس بدون اطلاع غایب " +
      "باشد منفی می‌شود. در هفتهٔ جاری موظفی تنها تا آخرین روز ثبت‌شده شمرده می‌شود.",
    diagrammUeberstunden: "اضافه‌کاری هر نفر",
    diagrammKrankheit: "بیماری هر نفر",
    spitzeHinweis: "پنج مقدار بالای هفته",
    keineWerte: "در این هفته مقداری نیست",
    pdf: "خروجی PDF",
    pdfLaeuft: "PDF در حال ساخت است …",
    seite: (seite: number, gesamt: number) => `صفحه ${seite} از ${gesamt}`,
    erstellt: (zeitpunkt: string) => `ساخته‌شده در ${zeitpunkt}`,
    einheit: "واحد بیماری",
  },
  titel: {
    schulung: "آموزش",
    zeugnis: "گواهی کار",
    qualifikationsmatrix: "ماتریس صلاحیت‌ها",
    maschine: "ماشین",
    audit: "ممیزی",
    zeichnung: "نقشه",
    lieferung: "محموله",
    offeneSchulungen: "آموزش‌های باقی‌مانده",
    schulungsmatrix: "ماتریس آموزش",
    atrLieferungen: "محموله‌های ATR",
    atrTeilekatalog: "کاتالوگ قطعات ATR",
    kpiBewertung: "ارزیابی KPI و اقدام‌ها",
    anmelden: "ورود",
  },
  uploads: {
    dateiWaehlen: "انتخاب فایل",
    verarbeitet: "در حال پردازش …",
    uebersprungen: (datei: string) => `سطرهای ردشده از «${datei}»`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `${gesamt} سطر پذیرفته شد، ${fehler} سطر رد شد. سطرهای دیگر ذخیره شده‌اند.`,
    zeile: "سطر",
    spalte: "ستون",
    grund: "دلیل",
    zuletzt: "آخرین بارگذاری‌ها",
    datei: "فایل",
    art: "نوع",
    zeilen: "سطرها",
    uebersprungenSpalte: "ردشده",
    status: "وضعیت",
    zeitpunkt: "زمان",
    nochNichts: "هنوز چیزی بارگذاری نشده است.",
    keineZeile: (datei: string) => `«${datei}» هیچ سطر معتبری نداشت.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `«${datei}» پذیرفته شد، ${fehler} سطر رد شد.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `«${datei}» پذیرفته شد: ${neu} تازه، ${aktualisiert} به‌روزشده.`,
    fehlgeschlagenMeldung: (meldung: string) => `بارگذاری ناموفق بود: ${meldung}`,
    vollstaendig: "کامل",
    teilweise: "جزئی",
    fehlgeschlagen: "ناموفق",
    arten: {
      umsatz: "درآمد (فاکتورها و برگه‌های بستانکار)",
      umsatzText: "کارت درآمد و روند درآمد را تغذیه می‌کند. برگه‌های بستانکار در فایل منفی‌اند.",
      auftraege: "سفارش‌های دریافتی",
      auftraegeText: "میانگین ارزش سفارش، کل سفارش‌ها و تفکیک بر پایهٔ ثبت‌کننده را تغذیه می‌کند.",
      auftragspositionen: "اقلام سفارش",
      auftragspositionenText:
        "موعد مقرر هر قلم را دارد. همراه با برگه‌های تحویل، تأخیر از آن به دست می‌آید.",
      lieferscheine: "برگه‌های تحویل",
      lieferscheineText: "تاریخ واقعی تحویل را دارد. فایل Excel، یک سطر برای هر قلم برگهٔ تحویل.",
      wareneingaenge: "رسید کالا",
      wareneingaengeText:
        "مبنای نرخ خطا در بخش خرید. گروه کالایی، تأمین‌کنندگان مواد را از کارگاه‌های پیمانکار جدا می‌کند.",
      acht_d: "گزارش‌های 8D",
      acht_dText:
        "یافته‌های ممیزی و شکایت‌ها در یک فایل. سطح هر یافته در متن آزاد است و هنگام خواندن استنتاج می‌شود.",
      lagerbewegungen: "گردش انبار",
      lagerbewegungenText:
        "مصرف هر کالا برای نسبت هزینهٔ مواد. همهٔ سطرهای بازهٔ تاریخی فایل را جایگزین می‌کند.",
      materialpreise: "قیمت مواد (رسید کالا)",
      materialpreiseText:
        "قیمت‌ها برای نسبت هزینهٔ مواد: برای هر کالا جدیدترین رسید معتبر است. ردیف‌های یکسان را به‌روز می‌کند، ردیف‌های تازه را می‌افزاید و چیزی را حذف نمی‌کند.",
      lagerpreise: "قیمت کالاهای انبار",
      lagerpreiseText:
        "داده‌های پایه برای ارزش‌گذاری انبار. کل فهرست قیمت را جایگزین می‌کند، نه فقط کالاهای موجود در فایل.",
      pruefungen: "بازرسی کیفیت",
      pruefungenText:
        "ثبت‌های بازرسی. همهٔ سطرهای بازهٔ تاریخی فایل را جایگزین می‌کند — ثبت‌هایی که در آن بازه دستی کنار گذاشته شده‌اند دوباره شمرده می‌شوند.",
      liefertreue: "پایبندی به موعد تحویل (خرید)",
      liefertreueText:
        "نرخ OTD در خرید را تغذیه می‌کند. یک سطر برای هر قلم تحویل؛ تاریخ واقعی تحویل بازه را تعیین می‌کند.",
      kontakte: "تماس‌ها (فروش)",
      kontakteText:
        "تماس‌های نخست و بازدیدها در هر هفته. همهٔ سطرهای بازهٔ تاریخی فایل را جایگزین می‌کند — بارگذاری دوبارهٔ همان بازه چیزی را دوبرابر نمی‌کند.",
      angebote: "پیشنهادهای قیمت",
      angeboteText:
        "حجم پیشنهادها در هر هفته و برای هر فروشنده. پیشنهادهای بدون ثبت‌کننده در هیچ میله‌ای نمی‌آیند.",
      interessenten: "مشتریان بالقوه",
      interessentenText:
        "داده‌های پایهٔ مشتریان بالقوه. مشتری بالقوه‌ای که دوباره ذخیره شود با تاریخ تازه‌اش به هفتهٔ دیگری می‌رود.",
    },
  },
  organigramm: {
    suchfeld: "نفر، سمت یا بخش",
    suchePlatzhalter: "نام، سمت، بخش",
    standort: "محل",
    alleStandorte: "همهٔ محل‌ها",
    personen: (anzahl: number) => `${anzahl} نفر`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} بدون سرپرست`,
    niemand: "کسی یافت نشد",
    niemandText: "جست‌وجوی دیگر، محل دیگر — یا همگام‌سازی Personio هنوز اجرا نشده است.",
    aufklappen: (name: string) => `${name} باز شود`,
    zuklappen: (name: string) => `${name} بسته شود`,
    direkt: (anzahl: number) => `${anzahl} مستقیم`,
    treffer: (anzahl: number) => ` · ${anzahl} نتیجه`,
    kontext: "با قاب: نتایج. کم‌رنگ: سرپرستان برای زمینه.",
  },
  offeneSchulungen: {
    einleitung:
      "چه کسی به چه چیزی نیاز دارد. فقط آموزش‌های فعال؛ آموزش‌های متوقف‌شده اینجا نمی‌آیند.",
    zumKatalog: "به فهرست آموزش‌ها",
    allesOffene: "همهٔ موارد باقی‌مانده",
    nieAbsolviert: "هرگز گذرانده نشده",
    ueberfaellig: "سررسید گذشته",
    wirdFaellig: "نزدیک سررسید",
    suchen: "جست‌وجوی نفر یا آموزش",
    suchenAria: "جست‌وجو",
    nichtsOffen: "چیزی باقی نمانده",
    nichtsOffenText: "همهٔ آموزش‌های فعال در دورهٔ خود هستند — یا هنوز چیزی خوانده نشده است.",
    eintraege: (anzahl: number) => `${anzahl} مورد.`,
    person: "نفر",
    schulung: "آموزش",
    bereich: "حوزه",
    zuletzt: "آخرین بار",
    faellig: "سررسید",
    stand: "وضعیت",
    nie: "هرگز گذرانده نشده",
    imTurnus: "در دوره",
  },
  schulungsmatrix: {
    legende: "راهنما",
    nichtZugewiesenKurz: "تخصیص‌نیافته",
    einleitung:
      "همهٔ افراد در برابر همهٔ آموزش‌ها — نمای کلی برای تابلوی اعلانات و برای ممیزی. " +
      "هرکس هیچ شرکتی نداشته باشد با سطر خالی در آن می‌آید؛ همین همان خلأیی است که " +
      "دنبالش می‌گردند.",
    wasOffenIst: "آنچه باقی مانده",
    katalog: "فهرست آموزش‌ها",
    suchfeld: "نفر یا بخش",
    suchePlatzhalter: "نام، بخش، شمارهٔ پرسنلی",
    bereich: "حوزه",
    alleBereiche: "همهٔ حوزه‌ها",
    nurLuecken: "فقط افراد دارای خلأ",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} از ${gesamt} نفر · ${schulungen} آموزش`,
    niemand: "کسی همخوان نیست",
    niemandText: "جست‌وجوی دیگر یا حوزهٔ دیگر — یا واقعاً کسی باقی نمانده است.",
    person: "نفر",
    nichtZugewiesen: (person: string, schulung: string) =>
      `${person} · ${schulung}: تخصیص نیافته`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (سررسید ${datum})`,
    offen: "باقی‌مانده",
    personio: "Personio",
    externGepflegt: "بیرون از سامانه نگهداری می‌شود",
    ohneTreffer: "بدون یافتن در Personio",
  },
  schulungen: {
    dokumentenlauf: "گردش مدارک",
    bereich: "حوزه",
    neueSchulung: "آموزش تازه",
    beispiel: "برای نمونه آموزش ایمنی آتش",
    anlegen: "بساز",
    wirdGelesen: "در حال خواندن …",
    uebersichtEinlesen: "خواندن فهرست آموزش‌ها",
    einlesenAria: "خواندن فهرست کلی آموزش‌ها",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} آموزش (${neu} تازه)، ${teilnahmen} شرکت، که ${zugeordnet} مورد به نفری در Personio نسبت داده شد.`,
    ohneTreffer: "بدون یافتن در Personio: ",
    ohneTrefferNach: ". این سطرها با شمارهٔ پرسنلی و نام همچنان همراه می‌آیند.",
    wirdUebernommen: "در حال پذیرش …",
    uebernehmen: "بپذیر",
    abbrechen: "انصراف",
    keineSchulung: "هنوز آموزشی نیست",
    keineSchulungText: "یکی بسازید یا فهرست کلی آموزش‌ها را بخوانید.",
    schulung: "آموزش",
    turnus: "دوره",
    frist: "مهلت (روز)",
    verantwortlich: "مسئول",
    offen: "باقی‌مانده",
    aktiv: "فعال",
    nichtBerechenbar: "(قابل محاسبه نیست)",
    zahlGroesserNull: "لطفاً عددی بزرگ‌تر از 0 وارد کنید.",
    nieKurz: (anzahl: number) => `${anzahl} هرگز`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} سررسید گذشته`,
    baldKurz: (anzahl: number) => `${anzahl} به‌زودی`,
    aktivSchalter: (name: string) => `${name} فعال`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} یعنی: برای این نفر تاریخی در سابقه نیست. ${bald} یعنی: در دو ماه آینده. به تاریخ ${datum}.`,
  },
  schulungenReg: {
    tabBearbeiten: "ویرایش آموزش",
    tabZuweisen: "تخصیص آموزش",
    tabStand: "وضعیت کارکنان",
    anforderungsmatrix: "ماتریس الزامات",
    ebene: "سطح",
    matrixLeer: "هنوز داده‌ای برای ماتریس نیست.",
    einzelTitel: "تخصیص یک آموزش",
    einzelHinweis: "مکمل ماتریس الزامات که در سطح واحد عمل می‌کند — برای افراد.",
    mitarbeiterWaehlen: "انتخاب کارمند",
    schulungWaehlen: "انتخاب آموزش",
    zuweisenAktion: "تخصیص",
    zugewiesen: "آموزش تخصیص یافت.",
    schonZugewiesen: "این آموزش قبلاً به این فرد تخصیص یافته است.",
    sammelTitel: "ثبت به‌عنوان انجام‌شده (گروهی)",
    sammelHinweis: "یک آموزش، یک تاریخ، چند شرکت‌کننده. رکوردهای انجام‌شده تاریخ خود را نگه می‌دارند و تاریخ جدیدتر جایگزین می‌شود.",
    durchgefuehrtAm: "انجام‌شده در",
    teilnehmerSuche: "جست‌وجوی شرکت‌کنندگان",
    standort: "محل",
    offeneTitel: "آموزش‌های باز",
    abteilung: "واحد",
    frist: "سررسید",
    mitarbeiterTitel: "نمای کلی کارکنان",
    anzahl: "تعداد",
    naechste: "سررسید بعدی",
    matrixTitel: "ماتریس کلی",
    abteilungenTitel: "واحدها و سرپرستان",
    vorgesetzter: "سرپرست مسئول",
    abteilungenHinweis: "سرپرست از Personio استخراج می‌شود؛ اگر نباشد ستون خالی می‌ماند.",
    sammelAktion: (anzahl: number) => `ثبت ${anzahl} به‌عنوان انجام‌شده`,
    sammelErfolg: (eingetragen: number, unveraendert: number) =>
      `${eingetragen} ثبت شد${unveraendert ? `، ${unveraendert} بدون تغییر` : ""}.`,
    seit: (tage: number) => `${tage} روز پیش`,
    in: (tage: number) => `تا ${tage} روز`,
  },
  schulung: {
    gibtEsNicht: "این آموزش وجود ندارد",
    gibtEsNichtText: "احتمالاً حذف شده است.",
    ohneTurnus: "بدون دوره",
    keineFaelligkeit: " — از آن سررسیدی محاسبه نمی‌شود",
    zumKatalog: "به فهرست آموزش‌ها",
    stammdaten: "داده‌های پایه",
    turnus: "دوره",
    turnusBeispiel: "برای نمونه سالانه",
    turnusHinweis: "متن آن؛ شمار ماه‌ها از خواندن فایل می‌آید.",
    turnusMonate: "دوره به ماه",
    monateHinweis: "خالی یعنی: سررسیدی محاسبه نمی‌شود.",
    verantwortlich: "مسئول",
    beschreibung: "شرح",
    fuerWen: "برای چه کسانی الزامی است؟",
    kuerzel: "کد بخش",
    kuerzelHinweis: "الگوی ریز از فایل Excel (NÄH، CUT، WVK …).",
    personioAbteilung: "بخش در Personio",
    personioHinweis: "بخش کلی، همان‌گونه که Personio نگه می‌دارد.",
    entfernen: (was: string) => `حذف ${was}`,
    keine: "هیچ",
    ergaenzen: (was: string) => `افزودن ${was}`,
    hinzufuegen: "افزودن",
    teilnahmen: "شرکت‌ها",
    nochNiemand: "هنوز کسی نیست — فهرست کلی آموزش‌ها را بخوانید یا کسی را ثبت کنید.",
    person: "نفر",
    abteilungKurz: "بخش",
    erstschulung: "آموزش نخست",
    zuletzt: "آخرین بار",
    faellig: "سررسید",
    stand: "وضعیت",
    keinTreffer: "در Personio یافت نشد — سطر با این حال می‌ماند",
    nichtInPersonio: "در Personio نیست",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "این شرکت",
    personErgaenzen: "افزودن نفر",
    nameForm: "نام خانوادگی، نام",
  },
  kompetenzen: {
    zumDashboard: "به داشبورد کارکنان",
    bereich: "حوزه",
    wirdGelesen: "در حال خواندن …",
    einlesen: "خواندن فایل حوزه",
    vorschauKopf: (datei: string, bereich: string) => `${datei} — ${bereich} پس از آن چنین می‌شود:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} صلاحیت، ${personen} نفر، ${bewertungen} ارزیابی.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `${zugeordnet} از ${personen} نفر در Personio یافت شد`,
    platzhalter: (anzahl: number) => `، ${anzahl} ستون جانگهدار`,
    ohneZuordnung: (namen: string) => ` بدون تخصیص: ${namen}.`,
    ersetztWarnung:
      "برگه‌های مربوط به‌طور کامل جایگزین می‌شوند — تغییرهایی که اینجا نگهداری شده‌اند " +
      "از دست می‌روند.",
    wirdUebernommen: "در حال پذیرش …",
    uebernehmen: "بپذیر",
    abbrechen: "انصراف",
    keineMatrix: "هنوز ماتریسی نیست",
    keineMatrixText: "یک فایل حوزه بخوانید — هر برگهٔ آن یک ماتریس می‌شود.",
    blatt: "برگه",
    titelSpalte: "عنوان",
    stand: "به تاریخ",
    eingelesen: "خوانده‌شده",
    produktion: "تولید",
    verwaltung: "اداری",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    bausteineTitel: "بلوک‌های متنی",
    bausteineHinweis: "برای هر حوزهٔ ارزیابی و نمره یک عبارت. فقط تغییرات ذخیره می‌شود؛ [NAME] و ضمایر هنگام تولید جایگزین می‌شوند.",
    speichern: "ذخیره",
    gespeichert: "ذخیره شد.",
    note1: "بسیار خوب",
    note2: "خوب",
    note3: "رضایت‌بخش",
    note4: "کافی",
    person: "نفر",
    waehlen: "— برگزینید —",
    art: "نوع",
    anlegen: "بساز",
    keines: "هنوز گواهی‌ای نیست",
    keinesText: "نفری و نوع گواهی را برگزینید — داده‌های پایه خودبه‌خود می‌آیند.",
    zeitraum: "بازه",
    note: "نمره",
    stand: "وضعیت",
    angelegt: "ساخته‌شده",
    fertig: "آماده",
    entwurf: "پیش‌نویس",
    qualifiziert: "گواهی کار مشروح",
    einfach: "گواهی کار ساده",
    zwischenzeugnis: "گواهی کار میان‌دوره",
    ausbildungszeugnis: "گواهی کارآموزی",
    praktikumszeugnis: "گواهی کارورزی",
  },
  einarbeitung: {
    einleitung:
      "آنچه یک نفر تازه‌وارد باید بیاموزد و اینکه چه کسی به او نشان می‌دهد. برگه از " +
      "موضوع‌هایی ساخته می‌شود که برای بخش او ثبت شده‌اند.",
    bogenErzeugen: "ساخت برگه",
    person: "نفر",
    waehlen: "— برگزینید —",
    wirdGebaut: "در حال ساخت …",
    einarbeitungsplan: "برنامهٔ آشناسازی",
    keineInhalte: "هنوز موضوعی ثبت نشده است — برگه خالی می‌ماند.",
    abteilungVon: (abteilung: string) => `بخش ${abteilung}`,
    neuerInhalt: "موضوع تازه",
    beispiel: "برای نمونه آموزش ایمنی کار با فرز",
    anlegen: "بساز",
    keinInhalt: "هنوز موضوعی نیست",
    keinInhaltText:
      "تعیین کنید یک نفر تازه‌وارد چه باید بیاموزد — و این برای کدام بخش‌ها معتبر است.",
    inhalt: "موضوع",
    ansprechpartner: "نفر مرجع",
    bereich: "حوزه",
    fuerAbteilungen: "برای کدام بخش‌ها",
    abteilung: "بخش",
    bereichLeer: "خالی یعنی: بخش از ماتریس گرفته شود",
    entfernen: (was: string) => `حذف ${was}`,
    abteilungHinzu: "+ بخش",
    abteilungFuer: (inhalt: string) => `بخش برای ${inhalt}`,
  },
  matrix: {
    bearbeiten: "ویرایش",
    bearbeitenFertig: "پایان",
    ohneKategorie: "بدون دسته",
    gibtEsNicht: "این ماتریس وجود ندارد",
    gibtEsNichtText: "احتمالاً جایگزین شده است.",
    blattStand: (blatt: string) => `برگهٔ ${blatt}`,
    stand: (datum: string) => ` · به تاریخ ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} صلاحیت، ${personen} نفر`,
    zurUebersicht: "به نمای کلی",
    qualifikation: "صلاحیت",
    keineZeilen: "این ماتریس هنوز سطری ندارد.",
    stufenBedeuten: "معنای سطح‌ها",
    erfuellungsgradHinweis:
      "عدد دوم درجهٔ برآورده‌شدن به درصد است. خانه‌ای که الزام دارد و کمتر از 100 ٪ " +
      "است یک خلأ است و با رنگ هشدار نشان داده می‌شود.",
    ergaenzen: "افزودن",
    neueQualifikation: "صلاحیت تازه",
    beispiel: "برای نمونه ماشین تراش",
    kategorie: "دسته",
    ohne: "بدون",
    zeile: "سطر",
    neuePerson: "نفر تازه",
    namensform: "نام و نام خانوادگی",
    spalte: "ستون",
    anforderungslevel: "سطح مورد نیاز",
    erfuellungsgrad: "درجهٔ برآورده‌شدن به درصد",
    stufe0: "لازم نیست",
    stufe1: "دانش پایه",
    stufe2: "با راهنمایی کار می‌کند",
    stufe3: "مستقل کار می‌کند",
    stufe4: "می‌تواند راهنمایی و آموزش دهد",
  },
  zeugnis: {
    gibtEsNicht: "این گواهی وجود ندارد",
    gibtEsNichtText: "احتمالاً حذف شده است.",
    durchschnitt: (wert: string) => ` · میانگین ${wert}`,
    zurUebersicht: "به نمای کلی",
    zeugnisVon: (name: string) => `گواهی کار ${name}`,
    stammdaten: "داده‌های پایه",
    stammdatenHinweis:
      "هنگام ساخت رونویسی شده است. تغییرها اینجا تنها برای همین گواهی معتبرند — " +
      "Personio دست‌نخورده می‌ماند.",
    name: "نام",
    personalnummer: "شمارهٔ پرسنلی",
    abteilung: "بخش",
    taetigkeit: "سمت",
    eintritt: "تاریخ ورود",
    austritt: "تاریخ خروج",
    geburtsdatum: "تاریخ تولد",
    ausstellungsdatum: "تاریخ صدور",
    ohneNamen: "بدون نام ممکن نیست.",
    anrede: "عنوان خطاب",
    frau: "خانم",
    herr: "آقای",
    anredeHinweis: "عنوان خطاب و ضمیرهای متن را تعیین می‌کند.",
    art: "نوع",
    anlass: "علت",
    anlassBeispiel: "برای نمونه درخواست خود فرد",
    fuehrungskraft: "مدیر",
    fuehrungskraftHinweis: "مدیر — بُعد «رهبری» را نمایان می‌کند",
    bewertung: "ارزیابی",
    bewertungHinweis:
      "نمره‌های 1 تا 4. عبارت رضایت از میانگین برمی‌آید — نه برعکس.",
    fachwissen: "دانش تخصصی",
    auffassungsgabe: "قدرت درک",
    arbeitsweise: "شیوهٔ کار",
    belastbarkeit: "تحمل فشار کاری",
    arbeitserfolg: "نتیجهٔ کار",
    sozialverhalten: "رفتار اجتماعی",
    fuehrung: "رهبری",
    aufgaben: "وظایف (نکته‌وار)",
    aufgabenHinweis: "هر سطر یک وظیفه — از آن فهرست گواهی ساخته می‌شود.",
    kompetenzen: "صلاحیت‌های ویژه",
    kompetenzenHinweis: "در ارزیابی عملکرد وارد می‌شود.",
    erfolge: "دستاوردهای ویژه",
    erfolgeHinweis: "پروژه‌ها، تقدیرها، نتیجه‌های سنجش‌پذیر.",
    text: "متن",
    baut: "در حال ساخت …",
    ausBausteinen: "از قطعه‌های آماده",
    formuliert: "در حال نگارش …",
    mitKi: "با هوش مصنوعی",
    textHinweis:
      "قطعه‌های آماده بدون شبکه و بدون هوش مصنوعی می‌نویسند. هوش مصنوعی آزادتر " +
      "می‌نویسد — تنها عنوان خطاب، سمت، بخش، مدت، نمره‌ها و متن‌های آزاد بالا به آن " +
      "می‌رسد. نام، تاریخ تولد و شمارهٔ پرسنلی سرور را ترک نمی‌کنند.",
    nochKeinText: "هنوز متنی نیست. نمره‌ها را بدهید و متن را بسازید.",
    fertigSchalter: "گواهی آماده است",
    fertigHinweis: "آماده — دیگر در دست کار نیست",
    unterschriftenFehler: (meldung: string) => `امضاها تعیین نشد (${meldung}).`,
    darunterSteht: "امضاکنندگان",
    fachlich: "سرپرست مستقیم",
    personalwesen: "امور کارکنان",
    niemandHinterlegt: "— کسی ثبت نشده —",
    unterschriftFehlt:
      "یک امضا کم است. آن را در تنظیمات ← گواهی‌های کار ثبت کنید، یا سرپرست را در " +
      "Personio نگه دارید.",
    ausPersonio: "از Personio",
    ausEinstellungen: "از تنظیمات",
    nichtHinterlegt: "ثبت نشده",
    einleitung: "مقدمه",
    taetigkeitsbeschreibung: "شرح وظایف",
    leistungsbeurteilung: "ارزیابی عملکرد",
    schlussformel: "عبارت پایانی",
    hinweisDeutsch: "خود گواهی به آلمانی نوشته می‌شود.",
  },
  dokumentenlauf: {
    erstelltAm: "ایجاد",
    uebergebenAm: "تحویل",
    zurueckAm: "بازگشت",
    geprueftAm: "بررسی",
    aktionen: "اقدامات",
    einleitung:
      "برگه‌های دارای QR: ساختن، تحویل دادن، پرشده پس گرفتن، بررسی کردن. QR اسکن را " +
      "دوباره نسبت می‌دهد — فارغ از اینکه نام فایل چیست.",
    formblatt: "فرم",
    fuerWen: "برای چه کسی",
    personWaehlen: "— نفر را برگزینید —",
    erzeugt: "در حال ساخت …",
    blattErzeugen: "ساخت برگه",
    standFilter: "وضعیت:",
    alle: "همه",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} از ${gesamt}`,
    keinVorgang: "هیچ پرونده‌ای نیست",
    keinVorgangText: "بالا یک برگه بسازید — QR می‌گیرد و از آن پس دنبال می‌شود.",
    person: "نفر",
    kennung: "کد",
    stand: "وضعیت",
    vollstaendigSpalte: "کامل",
    blatt: "برگه",
    scan: "اسکن",
    prueft: "در حال بررسی …",
    scanFuer: (name: string) => `بارگذاری اسکن برای ${name}`,
    zu: "بستن",
    details: "جزئیات",
    nochNichtGeprueft: "— هنوز بررسی نشده",
    vollstaendig: "کامل",
    unvollstaendig: "ناقص",
    umkehren: "وارونه‌کردن داوری — سنجش تنها می‌بیند که در خانه جوهری هست یا نه",
    pruefung: "بررسی",
    qrGelesen: "— QR خوانده شد",
    keinQr: "— QR یافت نشد، خانه‌ها قابل نسبت‌دادن نیستند",
    nachweise: "مستندها",
    keineNachweise: "هنوز چیزی ثبت نشده است.",
    welcheZeile: "مربوط به کدام سطر؟ (اختیاری)",
    laedt: "در حال بارگذاری …",
    nachweis: "مستند",
    nachweisHoch: "بارگذاری مستند",
    erstellt: "ساخته‌شده",
    uebergeben: "تحویل‌شده",
    zurueck: "بازگشته",
    geprueft: "بررسی‌شده",
    einarbeitungsplan: "برنامهٔ آشناسازی",
    schulungsnachweis: "مستند آموزش",
  },
  onboarding: {
    aktive: "فعال",
    personenwahl: "کدام افراد",
    eintritteTitel: "ورودهای جدید",
    inhalteTitel: "محتوای آشناسازی",
    matrixTitel: "ماتریس آشناسازی",
    matrixHinweis: "هر واحد به کدام محتوا نیاز دارد. تیک بلافاصله اعمال می‌شود.",
    matrixLeer: "هنوز محتوا یا واحدی وجود ندارد.",
    vorgaengeTitel: "فرایندهای آشناسازی و آموزش",
    matrixZelle: (inhalt: string, abteilung: string) => `${inhalt} – ${abteilung}`,
    nichtsGefehlt: "چیزی کم نبود.",
    angelegt: (anzahl: number) => `${anzahl} آموزش ساخته شد.`,
    neu90: "تازه (90 روز گذشته)",
    alle: "همه",
    personen: (anzahl: number) => `${anzahl} نفر`,
    keineEintritte: "ورودی‌ای نیست",
    keineEintritteText: "به‌محض اینکه کسی با تاریخ ورود از Personio بیاید، اینجا می‌ایستد.",
    person: "نفر",
    abteilung: "بخش",
    position: "سمت",
    eintritt: "تاریخ ورود",
    uebergabe: "تحویل",
    nichtInPersonio: "در Personio نیست",
    hierGesetzt: "اینجا تعیین شده — بر Personio مقدم است",
    ausPersonio: "از Personio",
    vermerken: "ثبت کن",
    paketTitel: "برنامهٔ آشناسازی و فهرست آموزش‌ها در یک PDF",
    paket: "بسته",
    uebersichtTitel: "فقط فهرست آموزش‌ها (فرم 71)",
    uebersicht: "نمای کلی",
    planZu: "بستن برنامه",
    plan: "برنامه",
    schulungsplan: "برنامهٔ آموزش",
    fehlendeAnlegen: "ساختن موارد کم",
    wirdGerechnet: "در حال محاسبه …",
    bruecke: "سمت ← کد بخش",
    brueckeHinweis:
      "پل میان Personio و لایهٔ ریز ماتریس الزام‌ها. بدون ورودی، لایهٔ ریز برای این " +
      "سمت اثر ندارد — برنامه این را صریح می‌گوید.",
    kuerzel: "کد",
    positionBeispiel: "برای نمونه اپراتور فرز CNC",
    kuerzelBeispiel: "CNC",
    zuordnen: "نسبت بده",
    ohnePersonio: "نفر بدون Personio",
    ohnePersonioHinweis:
      "برای ورودی‌هایی که هنوز در همگام‌سازی نیستند — یا اصلاً آنجا جایی ندارند.",
    name: "نام",
    anlegen: "بساز",
    kuerzelFehlt: (position: string) =>
      `برای سمت ${position} کد بخشی ثبت نشده است. لایهٔ ریز ماتریس الزام‌ها ` +
      "به همین دلیل برای این نفر اثر ندارد — ممکن است آموزش‌های الزامی کم باشد.",
    matrixVerlangtNichts: "ماتریس الزام‌ها برای این بخش چیزی نمی‌خواهد.",
    schulung: "آموزش",
    bereich: "حوزه",
    turnus: "دوره",
    pflichtUeber: "الزامی از راه",
    stand: "وضعیت",
    ueberAbteilung: "بخش",
    ueberKuerzel: "کد",
    vorhanden: "موجود",
    fehlt: "کم است",
  },
  audit: {
    zuKennzahlen: "به شاخص‌ها",
    nummer: "شماره",
    nummerBeispiel: "A-2026-01",
    titel: "عنوان",
    titelBeispiel: "ممیزی سامانه EN 9100",
    art: "نوع",
    intern: "درونی",
    extern: "بیرونی",
    phasenvorlage: "الگوی مرحله‌ها",
    ohne: "بدون",
    anlegen: "بساز",
    alle: "همه",
    neuesAudit: "ممیزی جدید",
    geltungsbereich: "دامنه",
    kategorie: "دسته",
    leadAuditor: "سرممیز",
    beginnGeplant: "شروع (برنامه‌ریزی‌شده)",
    endeGeplant: "پایان (برنامه‌ریزی‌شده)",
    ohneVorlage: "بدون الگو (مراحل بعداً افزوده شوند)",
    vorlageHinweis:
      "مراحل الگو هنگام ایجاد کپی می‌شوند. تغییر بعدی الگو این ممیزی را تغییر نمی‌دهد.",
    kategoriePflicht: "دست‌کم یک دسته انتخاب کنید.",
    zeitraumFehler: "پایان پیش از شروع است.",
    angelegt: "ممیزی ایجاد شد.",
    nummerVergeben: "این شماره ممیزی از قبل وجود دارد.",
    keinTreffer: "هیچ ممیزی با این فیلتر مطابقت ندارد.",
    keinAudit: "هنوز ممیزی‌ای نیست",
    keinAuditText: "یکی بسازید — با الگوی مرحله‌ها فهرست بررسی‌اش را همراه می‌آورد.",
    laufen: (laufend: number, gesamt: number) => `${laufend} از ${gesamt} هنوز در جریان است.`,
    status: "وضعیت",
    fortschritt: "پیشرفت",
    naechsterTermin: "موعد بعدی",
    ueberfaellig: (anzahl: number) => `${anzahl} سررسید گذشته`,
    geplant: "برنامه‌ریزی‌شده",
    inVorbereitung: "در حال آماده‌سازی",
    inDurchfuehrung: "در حال اجرا",
    berichtet: "گزارش‌شده",
    massnahmenOffen: "اقدام‌های باز",
    abgeschlossen: "پایان‌یافته",
    verschoben: "به تعویق افتاده",
    abgesagt: "لغوشده",
    phaseOffen: "باز",
    phaseInArbeit: "در دست کار",
    phaseErledigt: "انجام‌شده",
    phaseNichtZutreffend: "بی‌ربط",
    system: "سامانه",
    prozess: "فرایند",
    produkt: "محصول",
    lieferant: "تأمین‌کننده",
  },
  wartung: {
    zuKennzahlen: "به شاخص‌ها",
    neueMaschine: "ماشین تازه",
    beispiel: "برای نمونه فرز 3",
    anlegen: "بساز",
    keineMaschine: "هنوز ماشینی نیست",
    keineMaschineText: "یک ماشین بسازید و کارهای نگهداری‌اش را ثبت کنید.",
    maschine: "ماشین",
    inventarnummer: "شمارهٔ اموال",
    standort: "محل",
    verantwortlich: "مسئول",
    status: "وضعیت",
    aktiv: "فعال",
    stillgelegt: "از کار افتاده",
    angelegt: "دستگاه ایجاد شد.",
  },
  sensoren: {
    misst: "در حال اندازه‌گیری …",
    jetztMessen: "اکنون اندازه بگیر",
    keinGeraet: "دستگاهی تنظیم نشده است",
    keinGeraetText: "حسگرها در تنظیمات ساخته می‌شوند — رایانه، شناسه و Community.",
    verlauf: "روند",
    stunden: (n: number) => `${n} ساعت`,
    tage: (n: number) => `${n} روز`,
    temperatur: "دما",
    luftfeuchte: "رطوبت",
    zuletzt: (zeit: string) => `آخرین بار ${zeit}`,
    keinMesswert: "هنوز اندازه‌ای نیست.",
    nichtsGemessen: "در این بازه چیزی اندازه‌گیری نشده است.",
    frisch: "به‌روز",
    verzoegert: "با تأخیر",
    offline: "آفلاین",
    unbekannt: "هنوز چیزی اندازه‌گیری نشده",
    temperaturverlauf: "دما (°C)",
    feuchteverlauf: "رطوبت (%)",
    mittelFuenfMinuten: "میانگین هر ۵ دقیقه",
    mittelStunde: "میانگین هر ساعت",
    minMax: (fenster: string) => `کمینه/بیشینه ${fenster}`,
    ausserhalbGrenzen: "خارج از حدود",
    untergrenze: "کمینه",
    obergrenze: "بیشینه",
    ladeFehler: "بارگیری اندازه‌گیری‌ها ممکن نشد.",
  },
  hilfe: {
    nurDeutsch: "صفحه‌های راهنما خودشان به آلمانی نوشته شده‌اند.",
    suchen: "جست‌وجو در راهنما",
    nichtsGefunden:
      "چیزی یافت نشد. اگر چیزی در راهنما نیست، آن را با «ارسال App Feedback» در پایین سمت چپ بگویید.",
    alleThemen: "→ همهٔ موضوع‌ها",
    navigation: "موضوع‌های راهنما",
  },
  meldungen: {
    stand: (offen: number) => `${offen} باز`,
    neuSeit: (anzahl: number) => ` · ${anzahl} هنوز دیده نشده`,
    nichtsGemeldet: "هنوز App Feedback ثبت نشده",
    nichtsGemeldetText:
      "با «ارسال App Feedback» در پایین سمت چپ، هر کاربر واردشده می‌تواند گزارش دهد که در " +
      "صفحه چه چیزی درست نیست.",
    unbekannt: "نامشخص",
    status: "وضعیت",
    offen: "باز",
    inBearbeitung: "در دست بررسی",
    erledigt: "انجام‌شده",
    meldung: "بازخورد",
    aufnahme: "تصویر صفحه",
    ansicht: "نما",
    tabelle: "جدول",
    kanban: "کانبان",
    gruppieren: "گروه‌بندی بر اساس",
    nachStatus: "وضعیت",
    nachPerson: "شخص",
    nichtZugewiesen: "واگذارنشده",
    ziehenHinweis: "کارت‌ها را به ستون دیگری بکشید تا وضعیت یا مسئول را تغییر دهید.",
    verschieben: (beschreibung: string) => `جابه‌جایی: ${beschreibung}`,
    spalte: {
      datum: "تاریخ",
      von: "از",
      seite: "صفحه",
      beschreibung: "شرح",
      screenshot: "تصویر صفحه",
      status: "وضعیت",
      zugewiesen: "واگذارشده به",
      aktionen: "کنش‌ها",
    },
    oeffnen: "باز کردن",
    ungesehen: "دیده‌نشده",
    alsGesehen: "علامت دیده‌شده",
    zuDieserSeite: "بازخورد برنامه برای این صفحه",
  },
  auditAnsicht: {
    gibtEsNicht: "این ممیزی وجود ندارد",
    gibtEsNichtText: "احتمالاً حذف شده است.",
    internesAudit: "ممیزی درونی",
    externesAudit: "ممیزی بیرونی",
    prioritaet: (stufe: string) => ` · اولویت ${stufe}`,
    erledigt: (prozent: number) => ` · ${prozent} ٪ انجام‌شده`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} سررسید گذشته`,
    zurUebersicht: "به نمای کلی",
    status: "وضعیت",
    stammdaten: "داده‌های پایه",
    titel: "عنوان",
    bereich: "دامنه",
    leitenderAuditor: "سرممیز",
    auditteam: "تیم ممیزی",
    geplantVon: "شروع (برنامه‌ریزی‌شده)",
    geplantBis: "پایان (برنامه‌ریزی‌شده)",
    prioritaetFeld: "اولویت",
    niedrig: "کم",
    mittel: "متوسط",
    hoch: "زیاد",
    auditziel: "هدف ممیزی",
    kategorien: "دسته‌ها",
    kategorienHinweis:
      "یک ممیزی اغلب چند چیز با هم است — برنامهٔ درونی سامانه و فرایند را در یک نوبت " +
      "پیش می‌برد. از این رو انتخاب چندگانه و نه یک مورد.",
    normbezug: "ارجاع به استاندارد",
    normmatrixLeer: "ماتریس استانداردها خالی است — در تنظیمات نگهداری می‌شود.",
    nichtGeprueft: "* هنوز با متن یکپارچهٔ استاندارد سنجیده نشده است.",
    phasen: "مرحله‌ها",
    keinePhasen: "بدون مرحله — این ممیزی بدون الگو ساخته شده است.",
    phase: "مرحله",
    verantwortlich: "مسئول",
    faellig: "موعد برنامه‌ریزی‌شده",
    erledigtAm: "تاریخ واقعی",
    phaseErgaenzen: "افزودن مرحله",
    phaseBeispiel: "برای نمونه ممیزی پیگیری",
    verlauf: "سابقه",
    verlaufHinweis:
      "نوشتهٔ پایگاه داده، نه این فرم — و پس از آن نه تغییرپذیر و نه حذف‌شدنی.",
    nichtsGeschehen: "هنوز چیزی رخ نداده است.",
    warumEntfaellt: "چرا این مرحلهٔ الزامی حذف می‌شود؟",
    uebernehmen: "بپذیر",
    abbrechen: "انصراف",
    angelegt: "ساخته شد",
    geaendert: "تغییر کرد",
    geloescht: "حذف شد",
    uebersprungen: "رد شد",
    bearbeiten: "ویرایش",
    gespeichert: "ذخیره شد.",
    pflicht: "الزامی",
    kommentar: "توضیح",
    begruendung: "دلیل «نامرتبط»",
    grundPflicht: "مرحله الزامی را فقط با ذکر دلیل می‌توان رد کرد.",
    datumPflicht: "«انجام‌شده» به تاریخ واقعی نیاز دارد.",
    phaseSpeichern: "ذخیره مرحله",
    phaseGespeichert: "مرحله ذخیره شد.",
  },
  maschine: {
    gibtEsNicht: "این ماشین وجود ندارد",
    gibtEsNichtText: "احتمالاً حذف شده است.",
    zurUebersicht: "به نمای کلی",
    stammdaten: "داده‌های پایه",
    name: "نام",
    inventarnummer: "شمارهٔ اموال",
    standort: "محل",
    hersteller: "سازنده",
    modell: "مدل",
    verantwortlich: "مسئول",
    status: "وضعیت",
    aktiv: "فعال",
    stillgelegt: "از کار افتاده",
    notizen: "یادداشت‌ها",
    wartungsaufgaben: "کارهای نگهداری",
    jahr: "سال",
    halbjahr: "نیم‌سال",
    erstesHalbjahr: "هفتهٔ 1–26",
    zweitesHalbjahr: "هفتهٔ 27–52",
    wirdGebaut: "در حال ساخت …",
    nachweisbogen: "برگهٔ مستند",
    neueAufgabe: "کار تازه",
    aufgabeBeispiel: "برای نمونه بررسی سطح روغن",
    intervall: "فاصله",
    wochen: "هفته",
    keineAufgabe: "هنوز کاری نیست — برگه خالی می‌ماند.",
    aufgabe: "کار",
    dateien: "فایل‌ها",
    planHinterlegen: "ثبت برنامه",
    nachweisAblegen: "ثبت مستند",
    dateienHinweis: "برنامهٔ سازنده و برگه‌های امضاشده که اسکن و بازگردانده شده‌اند.",
    keineDatei: "هنوز فایلی نیست.",
    plan: "برنامه",
    nachweis: "مستند",
    laedt: "در حال بارگذاری …",
    taeglich: "روزانه",
    woechentlich: "هفتگی",
    monatlich: "ماهانه",
    quartalsweise: "فصلی",
    alleNWochen: "هر N هفته",
    alleNWochenZahl: (wochen: number) => `هر ${wochen} هفته`,
    bearbeiten: "ویرایش",
    gespeichert: "ذخیره شد.",
    nameFehlt: "نام الزامی است.",
  },
  atr: {
    teilAnlegen: "ساختن دستی قطعه",
    teilBeispiel: "شمارهٔ قطعه، برای نمونه VR-1234-56",
    anlegen: "بساز",
    wirdGelesen: "در حال خواندن …",
    mappeEinlesen: "خواندن پوشهٔ مرجع",
    suchen: "جست‌وجو",
    suchePlatzhalter: "شمارهٔ قطعه، شرح یا نقشه",
    nichtsGefunden: "چیزی یافت نشد",
    katalogLeer: "فهرست قطعه‌ها خالی است",
    keinTeil: "قطعه‌ای با این جست‌وجو همخوان نیست.",
    katalogLeerText: "یک پوشهٔ مرجع بخوانید یا قطعه‌ای را دستی بسازید.",
    teilenummer: "شمارهٔ قطعه",
    bezeichnung: "شرح",
    zeichnung: "نقشه",
    gewicht: "وزن kg",
    kategorie: "دسته",
    bereich: "بخش",
    lieferungen: "محموله‌ها",
    teilekatalog: "کاتالوگ قطعات",
    bearbeiten: "ویرایش",
    speichern: "ذخیره",
    gespeichert: "ذخیره شد.",
    gewichtUngueltig: "لطفاً وزن را به‌صورت عدد به کیلوگرم وارد کنید، مثلاً 0.44.",
    nichtGespeichert: (meldung: string) => `ذخیره نشد: ${meldung}`,
  },
  lieferungen: {
    wirdGelesen: "در حال خواندن …",
    einlesen: "خواندن برگهٔ تحویل",
    laeuft: "در حال اجرا …",
    eingangDurchsehen: "بازبینی صندوق ورودی",
    berichtNummer: (nr: string) => ` · شمارهٔ ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} قلم، ${zugeordnet} مورد در فهرست قطعه‌ها یافت شد.`,
    keinLieferschein: "هنوز برگهٔ تحویلی نیست",
    keinLieferscheinSchreiben: "یک PDF برگهٔ تحویل بخوانید — سپس اینجا برای بازبینی می‌ایستد.",
    keinLieferscheinLesen: "به‌محض اینکه برگهٔ تحویلی خوانده شود، اینجا می‌ایستد.",
    lieferschein: "برگهٔ تحویل",
    datum: "تاریخ",
    programm: "برنامه",
    msn: "MSN",
    status: "وضعیت",
    entwurf: "پیش‌نویس",
    erzeugt: "تولیدشده",
    abgelegt: "تحویل‌شده",
    atrNummer: "شماره ATR",
    containernummer: "شماره کانتینر",
    erstellt: "ایجاد",
    auswaehlen: (nr: string) => `انتخاب محموله ${nr}`,
    ausgewaehlt: (anzahl: number) => `${anzahl} انتخاب‌شده`,
    auswahlAufheben: "لغو انتخاب",
    containerbeschriftung: "ایجاد برچسب کانتینر",
    containerFrage: "شماره کانتینر برای محموله‌های انتخاب‌شده:",
    containerHinweis: "برچسب همه محموله‌های این کانتینر را نشان می‌دهد، از جمله آن‌هایی که از قبل در آن بودند.",
    containerErstellt: (nr: string) => `به کانتینر ${nr} اختصاص یافت – برچسب در حال دانلود است`,
    erstellen: "ایجاد",
    ausgewaehlteLoeschen: "حذف انتخاب‌شده‌ها",
    loeschenFrage: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "تحویل" : "تحویل"} حذف شود؟`,
    loeschenHinweis: "تحویل‌های انتخاب‌شده همراه با فایل‌هایی که ساخته‌اند حذف می‌شوند. این کار برگشت‌پذیر نیست.",
    loeschenBestaetigen: "حذف",
    geloescht: (anzahl: number) => `${anzahl} حذف شد.`,
    loeschenTeilweise: (weg: number, offen: number) => `${weg} حذف شد، ${offen} نشد — در این میان تغییر کرده یا دیگر موجود نیست.`,
  },
  durchsicht: {
    nichtGefunden: "محموله یافت نشد.",
    wirdErzeugt: "در حال ساخت …",
    dokumenteErzeugen: "ساخت مدارک",
    kopfdaten: "داده‌های سربرگ",
    atrNummer: "شمارهٔ ATR",
    nummerAutomatisch: (n: string) => `خودکار: ${n}`,
    containernummer: "شمارهٔ کانتینر",
    satzTitel: "شرح مجموعه",
    programm: "برنامه",
    msn: "MSN",
    bereich: "حوزه",
    wiegedatum: "تاریخ توزین",
    pruefdatum: "تاریخ بازرسی",
    qsUnterschrift: "امضای QS",
    hoechstgewicht: "بیشینهٔ وزن kg",
    positionen: "اقلام",
    pos: "ردیف",
    menge: "مقدار",
    seriennummern: "شماره‌های سریال",
    nichtImKatalog: "در فهرست قطعه‌ها نیست",
    poNummer: "شماره PO",
    poPos: "PO Pos",
    speichern: "ذخیره",
    gespeichert: "ذخیره شد.",
    aufServerSpeichern: "ذخیره روی سرور",
    wirdAbgelegt: "در حال ذخیره …",
    aufServerGespeichert: "روی سرور ذخیره شد.",
    ablageGescheitert: (ziele: string) => `ذخیره نشد: ${ziele}`,
    seriennummernAbweichung: (anzahl: number, menge: number) => `${anzahl} شماره سریال برای تعداد ${menge}`,
    seriennummernFeld: (pos: string) => `شماره‌های سریال ردیف ${pos}`,
  },
  fair: {
    mass: "اندازه",
    alsText: "متن",
    liest: "در حال خواندن …",
    zuPruefen: "بررسی شود",
    zuPruefenHinweis: "بدون شماره قطعه — به‌عنوان نقشهٔ FAIR بررسی یا کنار گذاشته شود.",
    dateiFehlt: (meldung: string) =>
      `خود نقشه بارگذاری نمی‌شود (${meldung}). اندازه‌ها با این حال در پایین آمده‌اند.`,
    bezeichnungFrei: "شرح (خالی = نام فایل)",
    beispiel: "برای نمونه شفت 12×40، نقشهٔ 4711",
    wirdGeladen: "در حال بارگذاری …",
    zeichnungWaehlen: "انتخاب نقشه",
    keineZeichnung: "هنوز نقشه‌ای نیست",
    keineZeichnungSchreiben: "یک PDF یا تصویر بارگذاری کنید — سپس می‌توان اندازه‌ها را بالون‌گذاری کرد.",
    keineZeichnungLesen: "به‌محض اینکه نقشه‌ای بارگذاری شود، اینجا می‌ایستد.",
    bezeichnung: "شرح",
    teilenummer: "شمارهٔ قطعه",
    kunde: "مشتری",
    hochgeladen: "بارگذاری‌شده",
    pruefliste: "فهرست بازرسی",
    einMass: "1 اندازه",
    masse: (anzahl: number) => `${anzahl} اندازه`,
    kopieren: "رونوشت",
    csv: "CSV",
    keinMass: "هنوز اندازه‌ای علامت نخورده است.",
    nr: "شماره",
    seite: "صفحه",
    wert: "مقدار",
    wertBeispiel: "برای نمونه 12.0 h7",
    wertZu: (nummer: number) => `مقدار برای شمارهٔ ${nummer}`,
    nachOben: (nummer: number) => `شمارهٔ ${nummer} به بالا`,
    nachUnten: (nummer: number) => `شمارهٔ ${nummer} به پایین`,
    nummer: (nummer: number) => `شمارهٔ ${nummer}`,
    drehen: "چرخاندن نما",
    verkleinern: "کوچک‌نمایی",
    vergroessern: "بزرگ‌نمایی",
    einpassen: "جای‌دهی",
    darstellung: "نمایش",
    bubbleGroesse: "اندازهٔ حباب‌ها",
    zeichnung: "نقشه",
    ladefehler: "نقشه بارگذاری نشد.",
    alleKunden: "همه مشتریان",
    ohneKunde: "بدون مشتری",
    kundenfilter: "فیلتر بر اساس مشتری",
    artikelnummer: "شماره کالا",
    artikelnummerLang: "شماره کالا",
    pn: "P/N",
    bubblesKleiner: "حباب‌های کوچک‌تر",
    bubblesGroesser: "حباب‌های بزرگ‌تر",
    pdf: "PDF",
    pdfExport: "خروجی PDF",
    pdfWirdErstellt: "در حال ساخت PDF …",
    pdfFehler: (meldung: string) => `ساخت PDF ممکن نشد: ${meldung}`,
    ocrNeu: "اجرای دوباره OCR برای این ردیف",
    ocrLeer: "چیزی تشخیص داده نشد — لطفاً مقدار را وارد کنید.",
    ocrFehler: (meldung: string) => `OCR ناموفق بود: ${meldung}`,
    ocrGleich: "OCR همان مقدار را می‌خواند.",
    ocrErsetzenTitel: "مقدار جایگزین شود؟",
    ocrErsetzen: (nummer: number, alt: string, neu: string) => `شماره ${nummer}: «${alt}» با «${neu}» جایگزین شود؟`,
    ersetzen: "جایگزینی",
    ziehen: (nummer: number) => `شماره ${nummer} را برای جابه‌جایی بکشید`,
    nurNummernfolge: "جابه‌جایی فقط به ترتیب شماره ممکن است — بدون جست‌وجو و بدون مرتب‌سازی بر اساس صفحه یا مقدار.",
  },
  newsletter: {
    keineAusgabe: "هنوز شماره‌ای نیست",
    keineAusgabeText: "به‌محض اینکه تحریریه شماره‌ای منتشر کند، اینجا می‌ایستد.",
    zurRedaktion: "به تحریریه",
    quartalJahr: (quartal: number, jahr: number) => `فصل ${quartal} · ${jahr}`,
    entwurfSuffix: " · پیش‌نویس",
    ausgabe: "شماره",
    quartalKurz: (quartal: number, jahr: number) => `Q${quartal} ${jahr}`,
    entwurfKlammer: " (پیش‌نویس)",
    alsPdf: "به شکل PDF",
    wirdGesetzt: "در حال صفحه‌آرایی …",
    seiteVon: (nr: number, gesamt: number) => `صفحهٔ ${nr} از ${gesamt} …`,
    redaktion: "تحریریه",
    niemandDazu: "در این فصل کسی تازه نیامده است.",
    beitraege: "مطالب",
    belegschaftInZahlen: "نیروی انسانی در اعداد",
    neuBeiUns: "تازه‌واردان",
    zurLeseransicht: "به نمای خواننده",
    jahr: "سال",
    quartal: "فصل",
    ausgabeAnlegen: "ساخت شماره",
    ausgabeBearbeiten: "ویرایش شماره",
    keineAusgabeRedaktion: "سال و فصل را برگزینید و بسازید — سپس فصل‌ها اینجا پدید می‌آیند.",
    titelDerAusgabe: "عنوان شماره",
    status: "وضعیت",
    entwurf: "پیش‌نویس",
    veroeffentlicht: "منتشرشده",
    titelbild: "تصویر جلد",
    rueckseite: "پشت جلد",
    ersetzen: " را جایگزین کن",
    waehlen: " را برگزین",
    ausgabeLoeschen: (quartal: number, jahr: number) => `شمارهٔ Q${quartal} ${jahr}`,
    neuesKapitel: "فصل تازه",
    kapitelBeispiel: "برای نمونه از خط تولید",
    art: "نوع",
    hinzufuegen: "افزودن",
    kapiteltitel: "عنوان فصل",
    kapitelHoch: "فصل به بالا",
    kapitelRunter: "فصل به پایین",
    ueberschrift: "سرتیتر",
    eintrag: "مطلب",
    textMarkdown: "متن. Markdown مجاز است — **پررنگ**، فهرست‌ها، جدول‌ها.",
    text: "متن",
    bild: "تصویر",
    bildGroesse: (nr: number) => `اندازهٔ تصویر ${nr}`,
    nieEingefroren: "هنوز چیزی ثابت نشده است — فصل در دفترچه خالی می‌ماند.",
    kpiEingefroren: "اعداد نیروی انسانی این فصل ثابت شده‌اند.",
    niemandEingefroren: "ثابت شد — در این فصل کسی تازه نیامده است.",
    zugaengeEingefroren: (anzahl: number) => `ثابت شد: ${anzahl} تازه‌وارد در این فصل.`,
    einfrieren: "ثابت کن",
    neuEinfrieren: "دوباره ثابت کن",
    rechtFehlt: (quelle: string) => `برای این کار دسترسی به منبع کم است: دیدن ${quelle}.`,
    quelleKpi: "شاخص‌ها",
    quellePersonal: "کارکنان",
    ausgabeAngelegt: "شماره ساخته شد.",
    ausgabeGeloescht: "شماره حذف شد.",
    kapitelAngelegt: "فصل ساخته شد.",
    standEingefroren: "وضعیت ثابت شد.",
  },
  signage: {
    bereiche: "بخش‌های Signage",
    medien: "رسانه‌ها",
    medienHinzu: "افزودن رسانه",
    playlists: "فهرست‌های پخش",
    zeitplaene: "زمان‌بندی‌ها",
    geraete: "دستگاه‌ها",
    dateiZiehen: "فایل را اینجا بکشید",
    dateiWaehlen: "انتخاب فایل",
    dateiHinweis: "تصویر، ویدئو، PDF یا PPTX، تا 50 MB",
    wirdUebertragen: "در حال انتقال …",
    art: "نوع",
    webseite: "صفحهٔ وب (URL)",
    htmlSchnipsel: "قطعهٔ HTML",
    titel: "عنوان",
    titelBeispiel: "زادروزها",
    urlHinweis:
      "نشانی کامل را بدهید. پخش‌کننده روی پورت جداگانه‌ای اجرا می‌شود و مسیرهای نسبی " +
      "آنجا کار نمی‌کنند.",
    aufnehmen: "بیفزا",
    medienFehler: "رسانه‌ها بارگذاری نشد.",
    keineMedien: "هنوز رسانه‌ای نیست",
    keineMedienText:
      "فایلی بارگذاری کنید یا نشانی‌ای بیفزایید. سپس می‌توان رسانه‌ها را در " +
      "فهرست‌های پخش گرد آورد.",
    erneut: "دوباره",
    inVerwendung: "رسانه در حال استفاده است",
    inVerwendungText: (titel: string, anzahl: number) =>
      `«${titel}» هنوز در ${anzahl} فهرست پخش به کار رفته است. نخست آن را از آنجا بردارید.`,
    verstanden: "فهمیدم",
    wartet: "در انتظار",
    konvertiert: "در حال تبدیل",
    fertig: "آماده",
    fehlgeschlagen: "ناموفق",
    keineHeartbeats: "هنوز ضربانی ثبت نشده است.",
    nieGesehen: "هرگز دیده نشده",
    online: "آنلاین",
    vorMinuten: (minuten: number) => `${minuten} دقیقه پیش`,
    offline: "آفلاین",
    entzogen: "لغوشده",
    keinGeraet: "هنوز دستگاهی جفت نشده است",
    keinGeraetText:
      "نمایشگری را با پخش‌کننده راه بیندازید. کدی شش‌رقمی نشان می‌دهد که اینجا وارد می‌کنید.",
    geraetKoppeln: "جفت‌کردن دستگاه",
    geraet: "دستگاه",
    status: "وضعیت",
    verfuegbarkeit: "در دسترس بودن 24 ساعت",
    ausfaelle: "قطعی‌ها 24 ساعت",
    tags: "برچسب‌ها",
    playlist: "فهرست پخش",
    zuletztGesehen: "آخرین بار دیده‌شده",
    seiteNeuLaden: "بارگذاری دوبارهٔ صفحه",
    neuStarten: "راه‌اندازی دوبارهٔ دستگاه",
    bearbeiten: "ویرایش",
    zugangEntziehen: "لغو دسترسی",
    geraetBearbeiten: "ویرایش دستگاه",
    name: "نام",
    bilddrehung: "چرخش تصویر",
    ton: "صدا",
    tonAktiv: "صدا روشن",
    abbrechen: "انصراف",
    speichern: "ذخیره",
    tagsHinweis: "تعیین می‌کنند این دستگاه کدام فهرست‌های پخش و زمان‌بندی‌ها را می‌گیرد.",
    entziehenText: (name: string) =>
      `«${name}» دسترسی‌اش را بی‌درنگ از دست می‌دهد و دوباره کد جفت‌سازی را نشان می‌دهد.`,
    neustartText: (name: string) => `«${name}» حدود یک دقیقه سیاه می‌ماند.`,
    geraetGespeichert: "دستگاه ذخیره شد.",
    geraetGeloescht: "دستگاه حذف شد.",
    keinGeraetGewaehlt: "دستگاهی برگزیده نشده",
    neuePlaylist: "فهرست پخش تازه",
    neuePlaylistText: "نام و برچسب‌های هدف را تعیین کنید. مدخل‌ها در گام بعد می‌آیند.",
    namensbeispiel: "پذیرش",
    keinePlaylist: "هنوز فهرست پخشی نیست",
    keinePlaylistText:
      "فهرست پخش، رسانه‌ها را در یک ترتیب گرد می‌آورد و از راه برچسب‌ها میان دستگاه‌ها پخش می‌شود.",
    playlistAnlegen: "ساخت فهرست پخش",
    aktiv: "فعال",
    erstellt: "ساخته‌شده",
    kopieren: "رونوشت",
    playlistGeloescht: "فهرست پخش حذف شد.",
    playlistKopiert: "از فهرست پخش رونوشت گرفته شد. مدخل‌ها رونوشت نمی‌شوند.",
    playlistInPlan: "فهرست پخش زمان‌بندی فعال دارد",
    zeitplanHinweis:
      "زمان‌بندی بر تخصیص سادهٔ برچسب مقدم است. بازه‌های گذرنده از نیمه‌شب را به دو " +
      "زمان‌بندی بخش کنید.",
    wochentage: "روزهای هفته",
    wochentagKuerzel: ["دوشنبه", "سه‌شنبه", "چهارشنبه", "پنج‌شنبه", "جمعه", "شنبه", "یکشنبه"],
    von: "از",
    bis: "تا",
    prioritaet: "اولویت",
    zeitplanAktiv: "زمان‌بندی فعال",
    keineZeitplaene: "زمان‌بندی‌ای نیست",
    keineZeitplaeneText:
      "بدون زمان‌بندی تنها تخصیص برچسب تعیین می‌کند دستگاه کدام فهرست پخش را نشان " +
      "دهد. زمان‌بندی، فهرست پخشی را در روزها و ساعت‌های معین جلوتر می‌اندازد.",
    tage: "روزها",
    zeitfenster: "بازهٔ زمانی",
    aktionen: "کنش‌ها",
    zeitplanBearbeiten: "ویرایش زمان‌بندی",
    neuerZeitplan: "زمان‌بندی تازه",
    zeitplaeneFehler: "زمان‌بندی‌ها بارگذاری نشد.",
    endeNachStart: "پایان باید پس از آغاز باشد. برای گذر از نیمه‌شب لطفاً دو زمان‌بندی بسازید.",
    mindestensEinTag: "دست‌کم یک روز هفته را برگزینید.",
    playlistWaehlen: "یک فهرست پخش برگزینید.",
    taeglich: "روزانه",
    zielTags: "برچسب‌های هدف",
    ueberblenden: "محو تدریجی",
    harterSchnitt: "برش تند",
    ziehpunkt: "دستگیرهٔ کشیدن",
    verwerfen: "دورانداختن",
    medienHinzufuegen: "رسانه بیفزایید و با دستگیرهٔ کشیدن مرتبشان کنید.",
    mediumWaehlen: "انتخاب رسانه",
    mediumHinzufuegen: "افزودن رسانه",
    mediumWaehlenText: "رسانهٔ برگزیده در پایان فهرست پخش افزوده می‌شود.",
    schliessen: "بستن",
    keineMedienAnlegen: "هنوز رسانه‌ای نیست. نخست در بخش رسانه‌ها چند مورد بسازید.",
    unbekanntesMedium: "رسانهٔ ناشناخته",
    playlistGespeichert: "فهرست پخش ذخیره شد. دستگاه‌ها بی‌درنگ دوباره بارگذاری می‌کنند.",
    kopplungscode: "کد جفت‌سازی",
    codeBeispiel: "ABC-123",
    geraetename: "نام دستگاه",
    geraeteBeispiel: "پذیرش، سمت چپ",
    tagsPflicht: "دستگاه فهرست پخشش را از راه برچسب‌ها می‌گیرد. بدون برچسب نمایشگر خالی می‌ماند.",
    koppeln: "جفت کن",
    formatErwartet: "قالب XXX-XXX انتظار می‌رود.",
    codeUnbekannt: "کد ناشناخته، منقضی یا پیش‌تر گرفته شده است. روی نمایشگر دوباره نمایش دهید.",
    tagEingeben: "برچسب را بنویسید و Enter بزنید",
  },
  einstellungen: {
    titel: "تنظیمات",
    bereiche: "بخش‌ها",
    gruppen: {
      kennzahlen: "شاخص‌ها",
      kennzahlenText:
        "مقدارهای هدف داشبوردها. در نمودار روند به شکل خط هدف دیده می‌شوند و تعیین " +
        "می‌کنند کارت از چه زمانی هشدار دهد.",
      personal: "HR",
      personalText:
        "اینکه کدام غیبت‌ها بیماری به شمار می‌آیند و کدام بخش‌ها به تولید تعلق دارند. " +
        "بدون این فهرست‌ها نسبت‌های کارکنان خالی می‌مانند.",
      atr: "ATR",
      atrText:
        "آنچه در هر مدرک یک برنامه یکسان است، و اینکه برگه‌های تحویل از کجا می‌آیند.",
      qualitaet: "کیفیت",
      qualitaetText:
        "ماتریس استانداردهایی که ممیزی به آن‌ها استناد می‌کند، و الگوهای مرحله‌ای که " +
        "ممیزی تازه به شکل فهرست بررسی می‌گیرد.",
      sensoren: "حسگرها",
      sensorenText:
        "دستگاه‌های سنجش در شبکه: کجا هستند، با کدام شناسه دما و رطوبت می‌دهند و از " +
        "چه مقداری یک عدد زیاد به شمار می‌آید.",
      zeugnisse: "گواهی‌های کار",
      zeugnisseText:
        "آنچه روی هر گواهی کار یکسان است: شرکت، شهر و دو امضا. امضای سرپرست هنگام " +
        "ساخت از Personio گرفته می‌شود — آنچه اینجا ثبت است تنها پشتیبان آن است.",
      erscheinung: "ظاهر",
      erscheinungText:
        "نشان شرکت — بالا سمت راست در برنامه و در سربرگ هر فایل ساخته‌شده: برنامهٔ " +
        "آشناسازی، مستند نگهداری، فهرست آموزش‌ها، گواهی کار.",
      anzeigen: "نمایشگرها",
      anzeigenText:
        "نشانی‌هایی که روی نمایشگرهای ساختمان اجرا می‌شوند. هر کدام توکنی امضاشده " +
        "دارد، تنها برای همان یک نمایشگر معتبر است و منقضی می‌شود.",
      email: "ایمیل‌ها",
      emailText:
        "پلتفرم یادآوری‌ها و گزارش‌ها را از کدام حساب Microsoft 365 می‌فرستد. چیزی جز با اقدام صریح ارسال نمی‌شود.",
      ad: "Active Directory",
      adText: "ورود در برابر AD محلی از طریق LDAPS. compute گذرواژه را هنگام ورود بررسی می‌کند و گروه‌های AD را بازتاب می‌دهد؛ مدیر حقوق برنامه‌ها را به‌ازای هر گروه می‌دهد.",
      zugaenge: "کاربران و گروه‌ها",
      zugaengeText:
        "ساختن افراد، تشکیل گروه‌ها و دادن دسترسی برنامه‌ها به آن‌ها. تغییرها از ورود " +
        "بعدی فرد اثر می‌گذارند — دسترسی‌ها در توکن او هستند.",
    },
  },
  einstellungenText: {
    appName: "نام برنامه",
    appNameHinweis:
      "در سربرگ بدون لوگو، در عنوان صفحه و در صفحهٔ ورود نمایش داده می‌شود.",
    farbrollen: "نقش‌های رنگ",
    farbrollenHinweis:
      "رنگ اصلی برای فوکوس، پیوندها، دکمهٔ اصلی و سری اصلی نمودار است و متن روی آن قرار می‌گیرد. یک‌بار روشن و یک‌بار تیره.",
    hellTitel: "روشن",
    dunkelTitel: "تیره",
    hauptfarbe: "رنگ اصلی",
    textAufHauptfarbe: "متن روی رنگ اصلی",
    kontrastTitel: "کنتراست ناکافی (WCAG 2.2)",
    kontrastZeile: (thema: string, bereich: string, verhaeltnis: string, mindestens: string) =>
      `«${bereich}» (${thema}): کنتراست ${verhaeltnis}:1، لازم ${mindestens}:1`,
    kontrastBereiche: {
      linkSeite: "پیوندها روی صفحه",
      linkKarte: "پیوندها روی کارت‌ها",
      fokusFlaeche: "فوکوس روی سطح خاکستری",
      diagramm: "رنگ نمودار",
      knopfText: "متن روی دکمهٔ اصلی",
    },
    farbenGespeichert: "رنگ‌ها ذخیره شد. پس از بارگذاری مجدد اعمال می‌شوند.",
    farbenAufVorgabe: "به حالت پیش‌فرض بازگردانده شد.",
    farbenZuruecksetzen: "بازگردانی به پیش‌فرض",
    email: {
      titel: "ارسال ایمیل (Microsoft 365)",
      einleitung:
        "سرویس مرکزی برای یادآوری‌ها و گزارش‌ها از طریق Microsoft Graph.",
      ohneSchluessel:
        "روی سرور GEHEIM_SCHLUESSEL تنظیم نشده است. تا زمانی که نباشد هیچ رازی ذخیره نمی‌شود.",
      gespeichert: "ذخیره شد.",
      speichert: "در حال ذخیره …",
      speichern: "ذخیره",
      speichernFehler: (meldung: string) => `ذخیره ناموفق بود: ${meldung}`,
      modus: "حالت",
      modusApp: "مجوز برنامه",
      modusDelegiert: "حساب شخصی (تفویض‌شده)",
      modusAppHinweis: "از طریق یک حساب برنامه با مجوز Mail.Send ارسال می‌کند؛ به یک راز کلاینت و رضایت مدیر نیاز دارد.",
      modusDelegiertHinweis: "پس از ورود با کد دستگاه، به نام فرد واردشده ارسال می‌کند؛ بدون رضایت مدیر.",
      tenantId: "شناسهٔ Tenant",
      clientId: "شناسهٔ کلاینت",
      clientSecret: "راز کلاینت",
      secretGesetzt: "ذخیره‌شده — برای حفظ آن خالی بگذارید",
      absender: "نشانی فرستنده",
      absenderName: "نام فرستنده (اختیاری)",
      aktivieren: "ارسال فعال است",
      testTitel: "ایمیل آزمایشی",
      testHinweis: "پیامی به نشانی واردشده می‌فرستد. فقط همین اقدام چیزی ارسال می‌کند.",
      testEmpfaenger: "گیرنده",
      testSenden: "ارسال ایمیل آزمایشی",
      testLaeuft: "در حال ارسال …",
      testOk: "ایمیل آزمایشی ارسال شد.",
      testFehler: "ارسال ناموفق بود.",
      delegiertTitel: "ورود با Microsoft",
      delegiertAnmelden: "ورود با Microsoft",
      delegiertAnleitung:
        "نشانی را باز کنید، کد را وارد کنید و با حساب Microsoft 365 خود وارد شوید.",
      delegiertWartet: "در انتظار ورود …",
      verbundenMit: (konto: string) => `واردشده به نام ${konto}`,
      trennen: "قطع اتصال",
      getrennt: "اتصال قطع شد.",
    },
    speichernFehler: (meldung: string) => `ذخیره ناموفق بود: ${meldung}`,
    zielwertGespeichert: "مقدار هدف ذخیره شد. داشبوردها آن را پس از بارگذاری دوباره نشان می‌دهند.",
    zahlAbNull: "لطفاً عددی از 0 به بالا وارد کنید.",
    personalGespeichert: "ذخیره شد. داشبورد کارکنان آن را پس از بارگذاری دوباره نشان می‌دهد.",
    krankTypen: "انواع غیبت که بیماری به شمار می‌آیند",
    produktionAbteilungen: "بخش‌های متعلق به تولید",
    kompetenzAttribute: "فیلدهای Personio که صلاحیت ثبت‌شده به شمار می‌آیند",
    ausDemBestand: "از داده‌های همگام‌شده",
    abteilungenBeispiel: "ساخت، مونتاژ",
    firmenlogo: "نشان شرکت",
    anzeigenHinweis:
      "نشانی یک مدخل فهرست پخش را در پخش‌کنندهٔ Signage می‌سازد. تنها برای نمایشگر " +
      "برگزیده معتبر است و منقضی می‌شود — مدخلی که دیگر کسی نگهش نمی‌دارد خودبه‌خود " +
      "از نمایش می‌ایستد.",
    logoHinweis:
      "بالا سمت راست در برنامه و در سربرگ هر فرم ساخته‌شده دیده می‌شود — برنامهٔ " +
      "آشناسازی، مستند نگهداری، فهرست آموزش‌ها، گواهی کار. PNG، JPEG یا SVG، حداکثر 5 MB. " +
      "اگر چیزی ثبت نشده باشد، به جای آن نوشتهٔ «ACM-Plattform» می‌آید.",
    communityHinweis: "رمزگذاری‌شده ذخیره می‌شود و دیگر هرگز نشان داده نمی‌شود",
    verwaltenSchliesstEin: "«مدیریت» روی کارت پلتفرم هر دسترسی دیگری را در بر می‌گیرد.",
    logoAlt: "نشان شرکت ثبت‌شده",
    keinsHinterlegt: "هنوز چیزی ثبت نشده است.",
    laedt: "در حال بارگذاری …",
    ersetzen: "جایگزین کن",
    hochladen: "بارگذاری",
    logoHochladen: "بارگذاری نشان شرکت",
    logoHinterlegt: "نشان ثبت شد.",
    anzeige: "نمایشگر",
    geburtstage: "زادروزهای هفته",
    neuzugaenge: "تازه‌واردان تیم",
    gueltigTage: "معتبر برای (روز)",
    erzeugt: "در حال ساخت …",
    adresseErzeugen: "ساخت نشانی",
    adresseKopiert: "نشانی رونوشت شد.",
    kopierenFehler: "رونوشت نشد — لطفاً دستی انتخاب کنید.",
    kopieren: "رونوشت",
    gespeichert: "ذخیره شد.",
    speichern: "ذخیره",
    speichert: "در حال ذخیره …",
    firma: "شرکت",
    ort: "شهر (بالای تاریخ)",
    nameRueckfall: "نام (پشتیبان)",
    titelRueckfall: "عنوان (پشتیبان)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "مشخصات صادرکننده",
    ausstellerHinweis:
      "روی هر گواهی می‌آید. سربرگ ACM به کار می‌رود، به‌محض اینکه «ACM» در نام شرکت باشد.",
    linkeUnterschrift: "امضای چپ — سرپرست مستقیم",
    linkeHinweis:
      "معمولاً سرپرست همان فرد؛ او هنگام ساخت از Personio گرفته می‌شود. آنچه اینجا " +
      "می‌آید تنها وقتی اثر دارد که Personio چیزی ندهد — مثلاً برای افرادی که بیرون " +
      "از سامانه نگهداری می‌شوند.",
    rechteUnterschrift: "امضای راست — امور کارکنان",
    rechteHinweis:
      "برای همهٔ گواهی‌ها یکسان. چون به فردی از Personio بسته است، عنوان از آنجا " +
      "می‌آید و با تغییر سمت درست می‌ماند.",
    personAusPersonio: "فرد از Personio",
    keinePerson: "— هیچ‌کس، متن آزاد پایین به کار رود —",
    personenFehler: (meldung: string) => `فهرست افراد بارگذاری نشد (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "الگوها",
    vorlagenHinweis:
      "برای هر برنامه یک الگو. داده‌های سربرگ و فایل اسکلت در هر مدرک ATR آن برنامه " +
      "یکسان‌اند. الگو هنگام خواندن یک پوشهٔ مرجع در فهرست قطعه‌ها ساخته می‌شود.",
    keineVorlage: "هنوز الگویی نیست",
    keineVorlageText: "یک پوشهٔ مرجع بخوانید — نام برنامه آنجا در خانهٔ D2 است.",
    geruestHinterlegt: "فایل اسکلت ثبت شد.",
    geruestErsetzen: "جایگزینی اسکلت",
    geruestWaehlen: "انتخاب اسکلت",
    keineHinterlegt: "هنوز چیزی ثبت نشده",
    kunde: "مشتری",
    lieferant: "تأمین‌کننده",
    arbeitspaket: "بستهٔ کاری",
    referenz: "مرجع",
    bestellerSpez: "مشخصات سفارش‌دهنده",
    lieferantenSpez: "مشخصات تأمین‌کننده",
    kundenSpez: "مشخصات مشتری",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "فصل ATA",
    waage: "ترازو",
    qsUnterschrift: "امضای QS",
    eingangsordner: "پوشهٔ ورودی",
    eingangHinweis:
      "برگه تحویل در پوشه ورودی خوانده می‌شود، به محموله تبدیل و به بایگانی منتقل می‌شود.",
    dateiserver: "سرور فایل",
    dateiserverHinweis:
      "رایانه، اشتراک و حساب سرویس برای پوشه ورودی و «ذخیره روی سرور» به کار می‌روند. رایانه‌های مجاز را ATR_SMB_ERLAUBT تعیین می‌کند. رمزی که اینجا وارد شود بر ATR_SMB_PASSWORT محیط مقدم است.",
    laeuft: "روشن",
    aus: "خاموش",
    zuletzt: (zeit: string, text: string) => `آخرین بار ${zeit}: ${text}`,
    nochNichtGelaufen: "هنوز اجرا نشده است.",
    prueft: "در حال بررسی …",
    verbindungPruefen: "بررسی اتصال",
    laeuftGerade: "در حال اجرا …",
    jetztDurchsehen: "اکنون بازبینی کن",
    verbindungSteht: (dateien: number) =>
      `اتصال برقرار است. ${dateien} فایل در ورودی در انتظار است.`,
    keineVerbindung: (meldung: string) => `اتصالی نیست: ${meldung}`,
    unbekannt: "نامشخص",
    gelesenAngelegt: (gelesen: number, angelegt: number) =>
      `${gelesen} خوانده شد، ${angelegt} ساخته شد.`,
    rechner: "رایانه",
    rechnerHinweis: "باید در ATR_SMB_ERLAUBT باشد",
    freigabe: "پوشهٔ اشتراکی",
    domaene: "دامنه",
    benutzer: "کاربر",
    eingang: "ورودی",
    ausgang: "خروجی",
    archiv: "بایگانی",
    ablageziele: "ذخیره روی سرور",
    ablagezieleHinweis: "پوشه‌هایی روی اشتراک که «ذخیره روی سرور» کارپوشه و PDF را در آن‌ها قرار می‌دهد. {jahr} (سال) و {kw} (هفته تقویمی) هنگام ذخیره جایگزین می‌شوند.",
    zielMappeA350: "کارپوشه A350",
    zielMappeA380: "کارپوشه A380",
    zielLogistik: "PDF لجستیک",
    zielWeightReport: "PDF گزارش وزن",
    zielUngueltig: "یک پوشه مقصد نامعتبر است: خالی، دارای «..» یا دارای جای‌نگاری غیر از {jahr} و {kw}.",
    wasEinLaufTut: "یک اجرا چه می‌کند",
    entwurfAnlegen: "ساخت پیش‌نویس برای بازبینی",
    dokumenteErzeugen: "ساخت مدارک و بایگانی آن‌ها",
    intervall: "فاصله اسکن (ثانیه، 0 = خاموش)",
    intervallUngueltig: "فاصله باید عدد صحیح از 0 باشد.",
    passwort: "رمز حساب سرویس",
    passwortHinterlegt: "ثبت شده — برای حفظ، خالی بگذارید",
    passwortUmgebung: "از محیط (ATR_SMB_PASSWORT) — ورود اینجا مقدم است",
    passwortFehlt: "هنوز ثبت نشده",
    passwortOhneSchluessel: "GEHEIM_SCHLUESSEL در محیط نیست — بدون آن رمز ذخیره نمی‌شود.",
    speichern: "ذخیره",
    gespeichert: "ذخیره شد.",
  },
  qualitaetEinstellungen: {
    normmatrix: "ماتریس استانداردها",
    normmatrixHinweis:
      "بندهایی که ممیزی به آن‌ها استناد می‌کند. استاندارد در حال استفاده حذف نمی‌شود " +
      "— متوقف می‌شود، وگرنه ممیزی بی‌صدا مبنایش را از دست می‌دهد.",
    schonInMatrix: "این بند پیش‌تر در ماتریس هست.",
    regelwerk: "استاندارد",
    revision: "ویرایش",
    klausel: "بند",
    kurztext: "متن کوتاه",
    kurztextBeispiel: "ممیزی درونی",
    aufnehmen: "بیفزا",
    geprueft: "سنجیده‌شده",
    aktiv: "فعال",
    geprueftSchalter: (norm: string) => `${norm} سنجیده‌شده`,
    aktivSchalter: (norm: string) => `${norm} فعال`,
    phasenvorlagen: "الگوهای مرحله",
    phasenvorlagenHinweis:
      "توالی گام‌هایی که ممیزی تازه می‌گیرد. هنگام ساخت رونویسی می‌شود — تغییر بعدی " +
      "سابقه‌ای را بازنویسی نمی‌کند.",
    neueVorlage: "الگوی تازه",
    vorlageBeispiel: "ممیزی سامانه، استاندارد",
    anlegen: "بساز",
    schritte: (anzahl: number) => `${anzahl} گام`,
    schrittErgaenzen: "افزودن گام",
    schrittBeispiel: "برای نمونه جلسهٔ گشایش",
  },
  personioZugang: {
    taktGespeichert: "بازه ذخیره شد.",
    abgleichTitel: "همگام‌سازی",
    abgleichHinweis:
      "پلتفرم هر چند وقت داده‌های Personio را خودکار می‌گیرد، و یک همگام‌سازی دستی.",
    intervall: "بازهٔ همگام‌سازی",
    intervallWahl: {
      "0": "فقط دستی",
      "1": "هر ساعت",
      "6": "هر ۶ ساعت",
      "24": "روزانه",
      "168": "هفتگی",
    },
    abgleichJetzt: "به‌روزرسانی داده‌ها",
    abgleichLaeuft: "در حال همگام‌سازی …",
    abgleichFertig: (mitarbeiter: number, anwesenheiten: number, abwesenheiten: number) =>
      `همگام شد: ${mitarbeiter} کارمند، ${anwesenheiten} حضور، ${abwesenheiten} غیبت.`,
    abgleichTeilweise: (mitarbeiter: number, fehler: string) =>
      `همگام‌سازی جزئی (${mitarbeiter} کارمند): ${fehler}`,
    abgleichFehler: (fehler: string) => `همگام‌سازی ناموفق بود: ${fehler}`,
    nachweisTitel: "مدارک به Personio",
    nachweisHinweis:
      "پس از تغییر آموزش یا شایستگی، مدرکی را در پروفایل Personio بارگذاری می‌کند. به‌طور پیش‌فرض خاموش.",
    nachweisAktiv: "بارگذاری مدارک",
    nachweisKategorie: "دستهٔ سند",
    nachweisKategoriePlatzhalter: "شناسهٔ دستهٔ Personio",
    nachweisGespeichert: "ذخیره شد.",
    titel: "اطلاعات دسترسی Personio",
    einleitung:
      "اطلاعات دسترسی یک برنامهٔ API در Personio. بدون آن‌ها همگام‌سازی، " +
      "تصویرهای نمایه و فهرست‌های پیشنهاد خالی می‌مانند.",
    kennung: "Client-ID",
    geheimnis: "Client-Secret",
    feldHinweis:
      "رمزگذاری‌شده ذخیره می‌شوند و دیگر هرگز نشان داده نمی‌شوند. برای تعویض، " +
      "مقدارهای تازه وارد کنید.",
    speichern: "ذخیره",
    gespeichert: "اطلاعات دسترسی ثبت شد.",
    speichernFehler: (meldung: string) => `ذخیره ناموفق بود: ${meldung}`,
    entfernen: "حذف",
    entfernt: "اطلاعات دسترسی حذف شد.",
    pruefen: "بررسی اتصال",
    prueftGerade: "در حال بررسی …",
    verbindungSteht: "Personio اطلاعات دسترسی را می‌پذیرد.",
    verbindungFehlt: "Personio پاسخ نمی‌دهد.",
    laedt: "در حال بارگذاری …",
    keineHinterlegt: "هیچ اطلاعات دسترسی‌ای ثبت نشده است.",
    ausDerUmgebung: "اطلاعات دسترسی از محیط سرور (.env) معتبر است.",
    hinterlegtSeit: (zeitpunkt: string, wer: string | null) =>
      wer
        ? `ثبت‌شده در ${zeitpunkt} توسط ${wer}.`
        : `ثبت‌شده در ${zeitpunkt}.`,
    ohneSchluessel:
      "روی سرور GEHEIM_SCHLUESSEL تنظیم نشده است. تا وقتی نباشد، چیزی " +
      "رمزگذاری‌شده ذخیره نمی‌شود.",
  },
  sensorEinstellungen: {
    neuesGeraet: "دستگاه تازه",
    name: "نام",
    nameBeispiel: "اتاق سرور",
    rechner: "رایانه",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "باید در SNMP_ERLAUBT باشد",
    community: "Community",
    port: "پورت",
    kennungTemperatur: "شناسهٔ دما",
    kennungLuftfeuchte: "شناسهٔ رطوبت",
    faktorTemperatur: "ضریب دما",
    faktorHinweis: "0.1 اگر دستگاه دهم درجه را به شکل عدد صحیح بدهد",
    faktorLuftfeuchte: "ضریب رطوبت",
    farbe: "رنگ در نمودار",
    farbeHinweis: "برای نمونه #0f6e8c",
    optional: "اختیاری",
    anlegen: "بساز",
    fragt: "در حال پرسش …",
    ausprobieren: "بیازما",
    keinGeraet: "هنوز دستگاهی نیست",
    keinGeraetText: "بالا رایانه، Community و دست‌کم یک شناسه وارد کنید.",
    wirdAbgefragt: (name: string) => `${name} پرسیده می‌شود`,
    communityErsetzen: "جایگزینی Community",
    unveraendert: "بدون تغییر",
    communityErsetzt: "Community جایگزین شد.",
    sensorAngelegt: "حسگر ساخته شد.",
    sensorGeloescht: "حسگر همراه با سری زمانی‌اش حذف شد.",
    zahlEingeben: "لطفاً عددی وارد کنید.",
    taktTitel: "فاصله پرس‌وجو",
    intervall: "فاصله پرس‌وجو (ثانیه، 0 = خاموش)",
    intervallHinweis:
      "برای همه حسگرها. بازه ۰ تا ۸۶۴۰۰؛ ۰ پرس‌وجوی خودکار را خاموش می‌کند. کمتر از ۶۰ ثانیه در عمل یعنی پرس‌وجو در هر دقیقه.",
    intervallFehler: "فاصله باید عددی صحیح بین ۰ و ۸۶۴۰۰ باشد (۰ = خاموش).",
    grenzenTitel: "حدود کلی",
    grenzenHinweis: "برای همه حسگرها. فیلد خالی یعنی: بدون حد.",
    temperaturMin: "دمای کمینه (°C)",
    temperaturMax: "دمای بیشینه (°C)",
    feuchteMin: "رطوبت کمینه (%)",
    feuchteMax: "رطوبت بیشینه (%)",
    temperaturFehler: "دمای کمینه باید کمتر از بیشینه باشد.",
    feuchteFehler: "رطوبت کمینه باید کمتر از بیشینه باشد.",
    einstellungenGespeichert: "فاصله و حدود ذخیره شد.",
    verwerfen: "دور ریختن",
  },
  zugaenge: {
    stufen: {
      viewer: "مشاهده",
      editor: "ویرایش",
      admin: "مدیریت",
    },
    gruppeAngelegt: "گروه ساخته شد.",
    gruppeGibtEsSchon: "گروهی با این نام هست.",
    personAngelegt: "فرد ساخته شد",
    gruppeUmbenannt: "نام گروه تغییر کرد.",
    gruppeGeloescht: "گروه حذف شد.",
    mitgliedHinzu: "عضو افزوده شد. از ورود بعدی اثر می‌گذارد.",
    schonInGruppe: "این فرد پیش‌تر در گروه است.",
    neuesPasswort: "گذرواژهٔ تازه",
    mitgliedEntfernt: "عضو حذف شد. از ورود بعدی اثر می‌گذارد.",
    gemeldeteSeiten: "دیدن App Feedback",
    neueGruppe: "گروه تازه",
    gruppeBeispiel: "برای نمونه فروش داخلی",
    anlegen: "بساز",
    neuePerson: "فرد تازه",
    personBeispiel: "vorname.nachname@acm.local",
    keineGruppe: "هنوز گروهی نیست",
    keineGruppeText: "گروهی بسازید، به آن دسترسی برنامه‌ها بدهید و افراد را در آن بگیرید.",
    verzeichnis: "دایرکتوری",
    ausVerzeichnis: "از دایرکتوری می‌آید",
    umbenennen: "تغییر نام",
    mitRechten: "دارای دسترسی",
    ohneRechte: "بدون دسترسی",
    keinZugriff: "بدون دسترسی",
    rechteAnGruppe: "دسترسی‌ها به گروه بسته‌اند، نه به فرد.",
    passwortNurJetzt:
      "گذرواژه تنها همین حالا اینجاست. پس از آن تنها می‌توان آن را بازنشاند، نه دید.",
    fertig: "پایان",
    anmeldung: "ورود",
    passwort: "گذرواژه",
    gruppeUmbenennen: "تغییر نام گروه",
    abbrechen: "انصراف",
    speichern: "ذخیره",
    gruppenname: "نام گروه",
    mitgliederVon: (name: string) => `اعضای «${name}»`,
    wirktNachAnmeldung: "تغییرها از ورود بعدی فرد اثر می‌گذارند.",
    schliessen: "بستن",
    personHinzufuegen: "افزودن فرد",
    auswaehlen: "— برگزینید —",
    hinzufuegen: "افزودن",
    keineMitglieder: "این گروه هنوز عضوی ندارد.",
    passwortZuruecksetzen: "بازنشاندن گذرواژه",
    mitgliedEntfernen: "حذف عضو",
    entfernen: "حذف",
  },
  kopftitel: {
    start: "برنامه‌ها",
    kennzahlen: "داشبورد KPI",
    offeneSchulungen: "آموزش‌های باقی‌مانده",
    schulungsmatrix: "ماتریس آموزش",
    atrLieferungen: "محموله‌های ATR",
    atrTeilekatalog: "کاتالوگ قطعات ATR",
  },
  kennzahlenHub: {
    titel: "داشبورد KPI",
    bereiche: {
      "/kpi/vertrieb": "درآمد، ارزش سفارش، سهم مشتریان",
      "/hr/kennzahlen": "نیروی انسانی، ترک خدمت، بیماری — دسترسی جداگانه",
      "/kpi/qualitaet": "یافته‌های ممیزی و نرخ شکایت",
      "/kpi/finanzen": "نسبت هزینهٔ مواد و پرسنل",
      "/kpi/einkauf": "پایبندی تأمین‌کنندگان به موعد تحویل",
      "/kpi/produktion": "تأخیر، سفارش‌های سررسیدگذشته",
      "/kpi/bewertung": "ارزیابی شاخص‌ها، تعیین، واگذاری و پیگیری اقدام‌ها",
    },
  },
  personalHub: {
    bereiche: {
      "/hr/kennzahlen": "نیروی انسانی، ترک خدمت، بیماری، اضافه‌کاری",
      "/hr/organigramm": "چه کسی به چه کسی گزارش می‌دهد",
      "/hr/kompetenzen": "ماتریس صلاحیت‌ها به تفکیک بخش",
      "/hr/schulungen": "آموزش‌های الزامی، موعدها، مستندها",
      "/hr/onboarding": "ورودها، آشناسازی و فرایندها",
      "/hr/einarbeitung": "برنامه‌های آشناسازی و وضعیت آن‌ها",
      "/hr/dokumente": "ساختن فرم‌ها، چاپ و بازخوانی اسکن‌ها",
      "/hr/zeugnisse": "نوشتن و صادرکردن گواهی‌های کار",
    },
  },
  bewertung: {
    titel: "ارزیابی KPI و اقدام‌ها",
    uebersichtFehler: (meldung: string) => `بارگذاری نشد: ${meldung}`,
    nurLesen:
      "شما می‌توانید ارزیابی‌ها را بخوانید، اما ننویسید. برای آن دسترسی «ویرایش» بر " +
      "تنظیمات لازم است.",
    bubbles: "حباب‌ها",
    bubblesLeer: "هنوز حبابی نیست.",
    neu: "تازه",
    alsGesehen: "علامت دیده‌شده",
    zumDashboard: "به داشبورد",
    bubble: (nummer: number) => `حباب ${nummer}`,
    ohnePosition: "بدون جایگاه روی نمودار",
    neueMassnahme: "اقدام تازه",
    kpiWaehlen: "انتخاب شاخص…",
    ohneBubble: "— بدون حباب —",
    titelPlatzhalter: "اقدام (عنوان)",
    verantwortlichWaehlen: "مسئول…",
    anlegen: "اقدام",
    massnahmen: "اقدام‌ها",
    alleStatus: "همهٔ وضعیت‌ها",
    statusFilter: "فیلتر بر اساس وضعیت",
    keineMassnahme: "هنوز اقدامی نیست.",
    nichtZugewiesen: "واگذار نشده",
    spalte: {
      kpi: "شاخص",
      massnahme: "اقدام",
      verantwortlich: "مسئول",
      faellig: "سررسید",
      prioritaet: "اولویت",
      status: "وضعیت",
      aktionen: "کنش‌ها",
    },
    status: {
      offen: "باز",
      laeuft: "در حال انجام",
      erledigt: "انجام‌شده",
      verworfen: "کنار گذاشته",
    },
    prioritaet: {
      niedrig: "کم",
      mittel: "متوسط",
      hoch: "زیاد",
    },
    ampel: {
      keine: "بدون چراغ",
      gruen: "سبز",
      gelb: "زرد",
      rot: "قرمز",
    },
    bereiche: {
      vertrieb: "فروش",
      einkauf: "خرید",
      produktion: "تولید",
      qualitaet: "کیفیت",
      finanzen: "مالی",
      personal: "HR",
    },
    verwalten: "مدیریت در اقدام‌ها",
    anzahlMassnahmen: (anzahl: number) => `${anzahl} اقدام`,
  },
  erklaerung: {
    hinweis: "توضیح",
    frage: (titel: string) => `«${titel}» چگونه محاسبه می‌شود؟`,
    knopf: "روش محاسبه",
    untertitel: "چگونه محاسبه می‌شود",
    ganzeSeite: "صفحهٔ کامل راهنما",
  },
};
