import type { Texte } from "@/texte/de";

/**
 * Die persischen Texte der Oberfläche. Maschinell übersetzt — vor dem
 * Ausrollen sollte jemand darüberlesen, der die Sprache spricht.
 */
export const fa: Texte = {
  kopf: {
    uebersicht: "به نمای کلی",
    hilfe: "راهنما",
    einstellungen: "تنظیمات",
    abmelden: "خروج",
    sprache: "زبان",
    erscheinungsbild: "ظاهر",
    hell: "روشن",
    dunkel: "تیره",
    system: "مانند سامانه",
    meldungenLeer: "گزارش‌ها — چیز تازه‌ای نیست",
    meldungen: (anzahl: number) => `گزارش‌ها — ${anzahl} مورد دیده‌نشده`,
    massnahmenLeer: "اقدام‌ها — موردی باز نیست",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `اقدام‌ها — ${offen} باز، ${ueberfaellig} مورد با تأخیر`
        : `اقدام‌ها — ${offen} باز`,
  },
  pfad: {
    aria: "مسیر",
    start: "خانه",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "محموله‌ها",
      "/einstellungen": "تنظیمات",
      "/fair": "FAIR",
      "/hilfe": "راهنما",
      "/hr": "کارکنان",
      "/hr/dokumente": "گردش مدارک",
      "/hr/einarbeitung": "آشناسازی",
      "/hr/kennzahlen": "شاخص‌ها",
      "/hr/kompetenzen": "صلاحیت‌ها",
      "/hr/onboarding": "ورود کارکنان",
      "/hr/organigramm": "چارت سازمانی",
      "/hr/schulungen": "آموزش‌ها",
      "/hr/schulungen/matrix": "ماتریس",
      "/hr/schulungen/offen": "باقی‌مانده",
      "/hr/zeugnisse": "گواهی‌های کار",
      "/kpi": "شاخص‌ها",
      "/kpi/bewertung": "ارزیابی",
      "/kpi/einkauf": "خرید",
      "/kpi/finanzen": "مالی",
      "/kpi/produktion": "تولید",
      "/kpi/qualitaet": "کیفیت",
      "/kpi/vertrieb": "فروش",
      "/newsletter": "خبرنامه",
      "/newsletter/redaktion": "تحریریه",
      "/platform/feedback": "گزارش‌ها",
      "/produktion": "تولید",
      "/qualitaet": "کیفیت",
      "/sensoren": "حسگرها",
      "/signage": "Digital Signage",
      "/signage/devices": "دستگاه‌ها",
      "/signage/media": "رسانه‌ها",
      "/signage/pair": "جفت‌سازی",
      "/signage/playlists": "فهرست‌های پخش",
      "/signage/schedules": "زمان‌بندی‌ها",
      "/uploads": "بارگذاری‌ها",
    },
  },
  start: {
    titel: "برنامه‌ها",
    verweigert: (name: string) => `برای «${name}» دسترسی ندارید.`,
    keineApp:
      "هنوز هیچ برنامه‌ای به حساب شما اختصاص نیافته است. لطفاً با مدیریت پلتفرم تماس بگیرید.",
  },
  anmeldung: {
    titel: "ACM-Plattform",
    aufforderung: "با حساب خود وارد شوید.",
    email: "ایمیل",
    passwort: "گذرواژه",
    knopf: "ورود",
    laeuft: "در حال ورود …",
  },
  allgemein: {
    laedt: "در حال بارگذاری …",
    speichern: "ذخیره",
    abbrechen: "انصراف",
    loeschen: "حذف",
    stueck: "عدد",
    loeschenTitel: "تأیید حذف",
    loeschenFrage: (was: string) => `«${was}» برای همیشه حذف می‌شود.`,
    loeschenKnopf: (was: string) => `حذف ${was}`,
  },
  zeitraum: {
    monat: "این ماه",
    quartal: "این فصل",
    jahr: "امسال",
    alles: "همهٔ زمان‌ها",
    frei: "انتخاب بازه",
    von: "از",
    bis: "تا",
    vonAria: "بازه از",
    bisAria: "بازه تا",
    verdreht: "پایان پیش از آغاز است.",
  },
  vergleich: {
    vorperiode: "نسبت به دورهٔ پیش",
    vormonat: "نسبت به ماه پیش",
    vorquartal: "نسبت به فصل پیش",
    vorjahr: "نسبت به سال پیش",
    zeitraumDavor: "نسبت به بازهٔ پیش از آن",
  },
  tabelle: {
    suche: "جستجو",
    sucheAria: "جستجو در جدول",
    sucheLeeren: "پاک کردن جستجو",
    keineTreffer: "برای این جستجو نتیجه‌ای نیست.",
    leer: "موردی وجود ندارد.",
    bereich: (von: number, bis: number, gesamt: number) => `${von}–${bis} از ${gesamt}`,
    seite: (seite: number, seiten: number) => `صفحه ${seite} از ${seiten}`,
    zurueck: "صفحه قبل",
    weiter: "صفحه بعد",
    sortieren: (spalte: string) => `مرتب‌سازی بر اساس «${spalte}»`,
    seitengroesse: "تعداد ردیف جدول در هر صفحه",
    seitengroesseText: "برای همه جدول‌های پلتفرم و همه افراد اعمال می‌شود.",
    gespeichert: "اندازه صفحه ذخیره شد.",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `داده‌ها تا ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `داده‌ها ناقص است — ${anzahl} مورد موجود نیست: ${fehlend}`,
    heute: "امروز",
    gestern: "دیروز",
    vorTagen: (tage: number) => `${tage} روز پیش`,
    nie: "هرگز",
    arten: {
      umsatz: "درآمد",
      auftraege: "سفارش‌ها",
      angebote: "پیشنهادهای قیمت",
      interessenten: "مشتریان بالقوه",
      kontakte: "تماس‌ها",
      liefertreue: "پایبندی به موعد تحویل",
      lagerbewegungen: "گردش انبار",
      lagerpreise: "قیمت‌های انبار",
      auftragspositionen: "اقلام سفارش",
      lieferscheine: "برگه‌های تحویل",
      pruefungen: "بازرسی‌ها",
      acht_d: "گزارش‌های 8D",
      wareneingaenge: "رسید کالا",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `شاخص‌ها بارگذاری نشد: ${meldung}`,
    keineDatenTitel: "برای این بازه داده‌ای موجود نیست",
    keineDatenVor: "خروجی‌های ERP را در ",
    keineDatenNach: " بارگذاری کنید، یا بازهٔ بزرگ‌تری برگزینید.",
    keineWerte: "مقداری در این بازه نیست",
    laedt: "در حال بارگذاری …",
    jeTag: "روزانه",
    jeWoche: "هفتگی",
    jeMonat: "ماهانه",
  },
  vertrieb: {
    umsatz: "درآمد",
    umsatzHinweis: "فاکتورها منهای برگه‌های بستانکار",
    auftragswert: "میانگین ارزش سفارش",
    ueberNull: "سفارش‌های بیش از 0 €",
    auftraege: "کل سفارش‌ها",
    verlauf: "روند درآمد",
    verlaufHinweis: (takt: string) => `${takt}، با کسر برگه‌های بستانکار`,
    kundenanteil: "سهم مشتریان از درآمد",
    kunde: "مشتری",
    anteil: "سهم",
    uebrige: "سایر",
    jeErfasser: "سفارش‌ها به تفکیک ثبت‌کننده",
    erfasser: "ثبت‌کننده",
    anzahl: "سفارش‌ها",
    summe: "جمع",
  },
  aktivitaet: {
    titel: "فعالیت فروش",
    jeWoche: (von: string, bis: string) => `به تفکیک هفتهٔ تقویمی، ${von} تا ${bis}`,
    ladeFehler: (meldung: string) => `فعالیت فروش بارگذاری نشد: ${meldung}`,
    leer: "در این بازه تماس، پیشنهاد قیمت یا مشتری بالقوه‌ای نیست.",
    kw: (woche: string) => `هفتهٔ ${woche}`,
    ziel: (wert: string) => `هدف ${wert} در هفته`,
    erstkontakte: "تماس‌های نخست",
    erstkontakteHinweis: "تماس‌های انجام‌شده از نوع ERS",
    besuche: "بازدیدها",
    besucheHinweis: "حضوری و برخط با هم",
    interessenten: "مشتریان بالقوه",
    interessentenHinweis: "تازه ثبت‌شده، بدون تخصیص به فروشنده",
    angebote: "پیشنهادهای قیمت",
    angeboteHinweis: "جمع پیشنهادهای صادرشده",
    auftragseingang: "سفارش‌های دریافتی",
    auftragseingangHinweis: "با کسر ابطال‌ها",
  },
  einkauf: {
    einleitung:
      "پایبندی تأمین‌کنندگان به موعد تحویل. آنچه در این بازه رسیده است شمرده می‌شود.",
    keineDaten: "برای این بازه قلم تحویلی موجود نیست",
    ladeVor: "خروجی پایبندی به موعد تحویل را در ",
    ladeNach: " بارگذاری کنید.",
    otd: "نرخ OTD",
    otdHinweis: (ziel: string) => `هدف ${ziel} · به‌موقع یعنی تأخیر ≤ 0`,
    puenktlich: "اقلام به‌موقع",
    gesamt: "کل اقلام",
    verzugSchnitt: "میانگین تأخیر",
    verzugHinweis: "اقلام بدون مقدار تأخیر اینجا شمرده نمی‌شوند",
    verlauf: "روند نرخ OTD",
    verlaufHinweis: "شکاف‌ها بازه‌هایی بدون قلم تحویلی هستند.",
    ladenhueter: "سفارش برای انبار — اقلام راکد",
    kapital: (wert: string) => `سرمایهٔ خوابیده: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `اقلام انبار که دست‌کم ${tage} روز بی‌حرکت مانده‌اند، بیشترین ارزش نخست. ` +
      "مبنا امروز است — بازهٔ بالا اینجا اثری ندارد، چون موجودی یک بازه نیست.",
    artikel: "کالا",
    bezeichnung: "شرح",
    bestand: "موجودی",
    liegtSeit: "راکد از",
    stueckpreis: "قیمت واحد",
    wert: "ارزش",
    positionen: "اقلام تحویل",
    positionenHinweis:
      "بیشترین تأخیر نخست، اقلام بدون مقدار تأخیر در بالا. حداکثر 500 سطر.",
    auftrag: "سفارش",
    lieferant: "تأمین‌کننده",
    zieltermin: "موعد مقرر",
    geliefert: "تحویل‌شده",
    verzug: "تأخیر",
  },
  produktion: {
    einleitung:
      "سفارش‌های دارای تأخیر. سفارش تنها زمانی شمرده می‌شود که نتیجه‌اش روشن باشد.",
    keineDaten: "در این بازه سفارشی با نتیجهٔ روشن موجود نیست",
    ladeVor: "اقلام سفارش و برگه‌های تحویل را در ",
    ladeNach:
      " بارگذاری کنید. هر دو لازم‌اند: یکی موعد مقرر را دارد و دیگری تاریخ واقعی را.",
    quote: "نرخ تأخیر",
    quoteHinweis: (ziel: string) => `حداکثر ${ziel}`,
    inVerzug: "سفارش‌های دارای تأخیر",
    gesamt: "کل سفارش‌ها",
    gesamtHinweis: "بدون سفارش‌های بازی که هنوز سررسید نشده‌اند",
    verzugSchnitt: "میانگین تأخیر",
    verzugHinweis: "سفارش‌های به‌موقع منفی به حساب می‌آیند",
    verlauf: "روند نرخ تأخیر",
    verlaufHinweis: "بر پایهٔ موعد مقرر. شکاف‌ها بازه‌هایی بدون سفارش شمرده‌شده هستند.",
    ziellinie: "هدف",
    liste: "سفارش‌های دارای تأخیر",
    listeHinweis:
      "بیشترین تأخیر نخست. در سفارش‌های باز هر روز بیشتر می‌شود. حداکثر 500 سطر.",
    auftrag: "سفارش",
    kunde: "مشتری",
    stand: "وضعیت",
    zieltermin: "موعد مقرر",
    geliefert: "تحویل‌شده",
    verzug: "تأخیر",
    verspaetet: "با تأخیر تحویل شده",
    offen: "باز، سررسید گذشته",
  },
  finanzen: {
    einleitung: "هزینهٔ مواد و پرسنل در نسبت با درآمد فاکتورشده.",
    keineDatenVor:
      "سه فایل لازم است: گردش انبار برای مصرف، رسید کالا برای قیمت‌ها و درآمد " +
      "به‌عنوان مبنا. هر سه در ",
    keineDatenNach: " هستند.",
    materialquote: "نسبت هزینهٔ مواد",
    materialquoteHinweis: "هزینهٔ مواد / درآمد",
    hoechstens: (ziel: string) => `حداکثر ${ziel}`,
    materialkosten: "هزینهٔ مواد",
    umsatz: "درآمد",
    personalquote: "نسبت هزینهٔ پرسنل",
    brauchtZeitraum: "نیازمند یک بازه است",
    personalHinweis: (kosten: string, personen: string) => `${kosten} برای ${personen} نفر`,
    ohnePreis: "کالاهای بدون قیمت",
    ohnePreisHinweis: "مصرف‌شده، اما ارزش‌گذاری نشده",
    jeAbteilung: "هزینهٔ پرسنل به تفکیک بخش",
    abteilung: "بخش",
    personen: "نفرات",
    kosten: "هزینه",
    anteil: "سهم",
    verlauf: "روند نسبت هزینهٔ مواد",
    verlaufHinweis: "شکاف‌ها بازه‌هایی بدون درآمد هستند — بدون مبنا نسبتی به دست نمی‌آید.",
    ziellinie: "هدف",
    verbrauch: "مصرف مواد به تفکیک کالا",
    verbrauchHinweis:
      "بیشترین هزینه نخست. کالاهای بدون قیمت در پایان می‌آیند — در نسبت وارد " +
      "نمی‌شوند. حداکثر 500 سطر.",
    artikel: "کالا",
    bezeichnung: "شرح",
    menge: "مصرف",
    stueckpreis: "قیمت واحد",
    keinPreis: "بدون قیمت",
  },
  qualitaet: {
    einleitung: "یافته‌های ممیزی، نرخ شکایت و مقدارهای بازرسی‌شده.",
    auditart: "نوع ممیزی:",
    keineArt: "هیچ نوع ممیزی برگزیده نشده است. دست‌کم یکی را برگزینید، وگرنه چیزی برای شمردن نیست.",
    keineDaten: "برای این بازه یافتهٔ ممیزی موجود نیست",
    ladeVor: "خروجی 8D را در ",
    ladeNach: " بارگذاری کنید.",
    behoerde: "نهاد نظارتی",
    extern: "بیرونی",
    intern: "درونی",
    kunde: "مشتری",
    level1: "یافته‌های ممیزی سطح 1",
    level2: "یافته‌های ممیزی سطح 2",
    ohneLevel: "بدون سطح قابل تشخیص",
    ohneLevelHinweis: "در هیچ کارتی شمرده نمی‌شود",
    hoechstens: (ziel: number) => `حداکثر ${ziel}`,
    auditVerlauf: "روند یافته‌های ممیزی",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `سهم مقدار بدون شکایت. مبنا: ${bezug}.`,
    fehlerquote: (quote: string) => `نرخ خطا: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `نرخ خطا: ${quote} · هدف ${ziel}`,
    reklamiert: "مقدار شکایت‌شده",
    bezugsmenge: "مقدار مبنا",
    bezugsmengeNull: "بدون آن نرخی به دست نمی‌آید",
    mehrAlsBezogen:
      "مقدار شکایت‌شده بیش از مقدار دریافتی است. محاسبه این را حل نمی‌کند: صورت و " +
      "مخرج از فایل‌های جداگانه با تاریخ‌های خودشان می‌آیند. بررسی کنید که فایل مبنا " +
      "برای این بازه کامل بارگذاری شده باشد.",
    reklKunde: "مشتری",
    reklIntern: "درونی",
    reklLieferant: "تأمین‌کنندگان مواد",
    reklWerkbank: "کارگاه‌های پیمانکار",
    bezugKunde: "مقدار تحویل‌شده",
    bezugIntern: "مقدار تحویل‌شده",
    bezugLieferant: "رسید کالا بدون خدمات",
    bezugWerkbank: "رسید کالا از گروه کالایی DIENST و SERVIC",
    mengeGesamt: "مقدار اعلام‌شده",
    mengeAkzeptiert: "مقدار پذیرفته‌شده",
    onQualityBezug: (menge: string) => `On Quality (مبنا ${menge})`,
    ziellinie: "هدف",
    geprueft: "محصولات بازرسی‌شده",
    geprueftHinweis: (pruefer: string, tage: string) =>
      `مقدار به ازای هر بازرس و هر روز بازرسی. مخرج برای هر دو یکی است: ${pruefer} بازرس در ${tage} روز.`,
    gross: "محصولات بزرگ",
    klein: "محصولات کوچک",
    mindestens: (ziel: number) => `دست‌کم ${ziel} در هر روز و برای هر بازرس`,
    buchungen: "ثبت‌های بازرسی کیفیت",
    buchungenHinweis:
      "ثبت کنارگذاشته‌شده در فهرست می‌ماند اما در هیچ کارتی شمرده نمی‌شود. " +
      "بیشترین مقدار نخست، حداکثر 500 سطر.",
    zaehltMit: "شمرده می‌شود",
    datum: "تاریخ",
    pruefer: "بازرس",
    produkt: "محصول",
    groesse: "اندازه",
    menge: "مقدار",
    ausschuss: "ضایعات",
    mitzaehlen: (datum: string) => `ثبت مورخ ${datum} شمرده شود`,
    klasseGross: "بزرگ",
    klasseKlein: "کوچک",
    diagnose: "یافته‌های بدون سطح قابل تشخیص",
    diagnoseHinweis:
      "سطح در فایل مبدأ در متن آزاد آمده است. اگر نه «Major … Level 1» باشد و نه " +
      "«Minor … Level 2»، یافته هیچ‌جا شمرده نمی‌شود. این فهرست نشان می‌دهد کجا باید اصلاح شود.",
    bericht: "گزارش",
    art: "نوع",
    adresse: "نشانی",
    bezeichnung: "شرح",
  },
  personal: {
    einleitung:
      "از همگام‌سازی Personio. موظفی روزانه از مدل کاری ثبت‌شدهٔ هر نفر می‌آید، نه از " +
      "یک روز هشت‌ساعتهٔ یکسان.",
    uebersicht: "نمای کلی",
    standLaedt: "وضعیت همگام‌سازی بارگذاری می‌شود …",
    keinAbgleich: "هنوز همگام‌سازی‌ای انجام نشده است. هر شب ساعت 02:15 خودبه‌خود اجرا می‌شود.",
    letzterAbgleich: (zeitpunkt: string, status: string) => `آخرین همگام‌سازی ${zeitpunkt} · ${status}`,
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} نفر، ${anwesenheiten} حضور، ${abwesenheiten} غیبت`,
    abgleichLaeuft: "در حال اجرا …",
    abgleichen: "اکنون همگام‌سازی کن",
    keineDaten: "برای این بازه حضوری ثبت نشده است",
    keineDatenHinweis:
      "یا همگام‌سازی Personio هنوز اجرا نشده، یا بازه پیش از آغاز ثبت قرار دارد.",
    ueberstunden: "نرخ اضافه‌کاری",
    stundenVon: (teil: string, ganz: string) => `${teil} از ${ganz} ساعت`,
    krankheit: "نرخ بیماری",
    krankheitsartenFehlen: "انواع بیماری ثبت نشده است",
    fluktuation: "ترک خدمت",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} خروج، میانگین ${schnitt} شاغل`,
    personen: "افراد ثبت‌شده",
    personenHinweis: "با حضور در این بازه",
    krankheitHinweisVor:
      "نرخ بیماری تا زمانی خالی می‌ماند که ثبت نشده باشد کدام انواع غیبت در Personio " +
      "بیماری به شمار می‌آیند. باید در ",
    krankheitHinweisNach: " ثبت شود.",
    verlauf: "روند",
    reiheUeberstunden: "اضافه‌کاری",
    reiheKrankheit: "بیماری",
  },
  melden: {
    knopf: "گزارش",
    titel: "گزارش یک مشکل",
    frage: "در این صفحه چه چیزی درست نیست؟ تصویری از صفحه همراه می‌رود.",
    abbrechen: "انصراف",
    senden: "ارسال",
    sendet: "در حال ارسال …",
    beispiel: "برای نمونه: کارت مقدار خالی نشان می‌دهد، با آنکه داده موجود است.",
    beschreibung: "شرح",
    aufnahme: "تصویر صفحه",
    gehtMit: "این تصویر همراه می‌رود.",
    nimmtAuf: "صفحه در حال تصویربرداری است …",
    misslungen: "تصویربرداری از صفحه ممکن نشد — گزارش بدون تصویر می‌رود.",
    dankeMitBild: "سپاسگزاریم — گزارش رسید.",
    dankeOhneBild: "سپاسگزاریم — گزارش رسید، بدون تصویر صفحه.",
  },
  belegschaft: {
    titel: "نیروی انسانی",
    hinweis:
      "به تاریخ امروز. توزیع‌ها داده‌های پایهٔ کنونی را نشان می‌دهند، نه داده‌های آن " +
      "زمان را — Personio تاریخچه نگه نمی‌دارد. اینکه «شاغلان» و نرخ صلاحیت مخرج‌های " +
      "متفاوتی دارند عمدی است: یکی از وضعیت Personio پیروی می‌کند و دیگری از تاریخ ورود " +
      "و خروج. هر دو راه از سامانهٔ پیشین آمده‌اند.",
    ladeFehler: (meldung: string) => `نیروی انسانی بارگذاری نشد: ${meldung}`,
    beschaeftigte: "شاغلان",
    beschaeftigteHinweis: "بر پایهٔ وضعیت «فعال» در Personio",
    neuImQuartal: "تازه‌واردان این فصل",
    bestand: "تعداد کل",
    kompetenzen: "صلاحیت‌های ثبت‌شده",
    felderFehlen: "فیلدها ثبت نشده‌اند — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} از ${aktive} بر پایهٔ تاریخ ورود و خروج`,
    geschlecht: "جنسیت",
    beschaeftigungsart: "نوع اشتغال",
    abteilungen: "بخش‌ها",
    maennlich: "مرد",
    weiblich: "زن",
    divers: "دیگر",
    unbekannt: "نامشخص",
    vollzeit: "تمام‌وقت",
    teilzeit: "پاره‌وقت",
    geringfuegig: "کم‌ساعت",
    extern: "بیرونی",
  },
  mitarbeiter: {
    titel: "کارمندان",
    nurMitUeberstunden: "فقط دارای اضافه‌کاری",
    ausgeblendet: (anzahl: number) => `(${anzahl} پنهان)`,
    person: "نفر",
    abteilung: "بخش",
    istStunden: "ساعت کارکرد",
    ueberstunden: "اضافه‌کاری",
    quote: "٪ اضافه‌کاری",
  },
  wochenbericht: {
    titel: "گزارش هفتگی",
    ladeFehler: (meldung: string) => `گزارش هفتگی بارگذاری نشد: ${meldung}`,
    kalenderwoche: "هفتهٔ تقویمی",
    kw: (woche: string, jahr: string) => `هفتهٔ ${woche} / ${jahr}`,
    keineDaten: "برای این هفته حضوری ثبت نشده است.",
    saldo: "ماندهٔ اضافه‌کاری",
    saldoHinweis: (personen: string) => `کارکرد منهای موظفی مؤثر، برای همهٔ ${personen} نفر`,
    ueberSoll: "بالاتر از موظفی",
    ueberSollHinweis: (gesamt: string) => `از ${gesamt} نفر دارای ثبت ورود`,
    krankheit: "بیماری",
    tage: "روز",
    stunden: "ساعت",
    krankheitHinweis: "بر روزهای تقویمی غیبت پخش شده است",
    ist: "کارکرد",
    soll: "موظفی",
    saldoSpalte: "مانده",
    fussnote:
      "موظفی، موظفی مؤثر هفته است: مرخصی و بیماری کسر شده‌اند و هرکس بدون اطلاع غایب " +
      "باشد منفی می‌شود. در هفتهٔ جاری موظفی تنها تا آخرین روز ثبت‌شده شمرده می‌شود.",
  },
  titel: {
    schulung: "آموزش",
    zeugnis: "گواهی کار",
    qualifikationsmatrix: "ماتریس صلاحیت‌ها",
    maschine: "ماشین",
    audit: "ممیزی",
    zeichnung: "نقشه",
    lieferung: "محموله",
    offeneSchulungen: "آموزش‌های باقی‌مانده",
    schulungsmatrix: "ماتریس آموزش",
    atrLieferungen: "محموله‌های ATR",
    kpiBewertung: "ارزیابی KPI",
    anmelden: "ورود",
  },
  uploads: {
    einleitung:
      "خواندن خروجی‌های ERP. بارگذاری دوبارهٔ همان فایل بی‌خطر است: سطرهای موجود " +
      "به‌روز می‌شوند و دوباره ساخته نمی‌شوند.",
    dateiWaehlen: "انتخاب فایل",
    verarbeitet: "در حال پردازش …",
    uebersprungen: (datei: string) => `سطرهای ردشده از «${datei}»`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `${gesamt} سطر پذیرفته شد، ${fehler} سطر رد شد. سطرهای دیگر ذخیره شده‌اند.`,
    zeile: "سطر",
    spalte: "ستون",
    grund: "دلیل",
    zuletzt: "آخرین بارگذاری‌ها",
    datei: "فایل",
    art: "نوع",
    zeilen: "سطرها",
    uebersprungenSpalte: "ردشده",
    status: "وضعیت",
    zeitpunkt: "زمان",
    nochNichts: "هنوز چیزی بارگذاری نشده است.",
    keineZeile: (datei: string) => `«${datei}» هیچ سطر معتبری نداشت.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `«${datei}» پذیرفته شد، ${fehler} سطر رد شد.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `«${datei}» پذیرفته شد: ${neu} تازه، ${aktualisiert} به‌روزشده.`,
    fehlgeschlagenMeldung: (meldung: string) => `بارگذاری ناموفق بود: ${meldung}`,
    vollstaendig: "کامل",
    teilweise: "جزئی",
    fehlgeschlagen: "ناموفق",
    arten: {
      umsatz: "درآمد (فاکتورها و برگه‌های بستانکار)",
      umsatzText: "کارت درآمد و روند درآمد را تغذیه می‌کند. برگه‌های بستانکار در فایل منفی‌اند.",
      auftraege: "سفارش‌های دریافتی",
      auftraegeText: "میانگین ارزش سفارش، کل سفارش‌ها و تفکیک بر پایهٔ ثبت‌کننده را تغذیه می‌کند.",
      auftragspositionen: "اقلام سفارش",
      auftragspositionenText:
        "موعد مقرر هر قلم را دارد. همراه با برگه‌های تحویل، تأخیر از آن به دست می‌آید.",
      lieferscheine: "برگه‌های تحویل",
      lieferscheineText: "تاریخ واقعی تحویل را دارد. فایل Excel، یک سطر برای هر قلم برگهٔ تحویل.",
      wareneingaenge: "رسید کالا",
      wareneingaengeText:
        "مبنای نرخ خطا در بخش خرید. گروه کالایی، تأمین‌کنندگان مواد را از کارگاه‌های پیمانکار جدا می‌کند.",
      acht_d: "گزارش‌های 8D",
      acht_dText:
        "یافته‌های ممیزی و شکایت‌ها در یک فایل. سطح هر یافته در متن آزاد است و هنگام خواندن استنتاج می‌شود.",
      lagerbewegungen: "گردش انبار",
      lagerbewegungenText:
        "مصرف هر کالا برای نسبت هزینهٔ مواد. همهٔ سطرهای بازهٔ تاریخی فایل را جایگزین می‌کند.",
      lagerpreise: "قیمت کالاهای انبار",
      lagerpreiseText:
        "داده‌های پایه برای ارزش‌گذاری انبار. کل فهرست قیمت را جایگزین می‌کند، نه فقط کالاهای موجود در فایل.",
      pruefungen: "بازرسی کیفیت",
      pruefungenText:
        "ثبت‌های بازرسی. همهٔ سطرهای بازهٔ تاریخی فایل را جایگزین می‌کند — ثبت‌هایی که در آن بازه دستی کنار گذاشته شده‌اند دوباره شمرده می‌شوند.",
      liefertreue: "پایبندی به موعد تحویل (خرید)",
      liefertreueText:
        "نرخ OTD در خرید را تغذیه می‌کند. یک سطر برای هر قلم تحویل؛ تاریخ واقعی تحویل بازه را تعیین می‌کند.",
      kontakte: "تماس‌ها (فروش)",
      kontakteText:
        "تماس‌های نخست و بازدیدها در هر هفته. همهٔ سطرهای بازهٔ تاریخی فایل را جایگزین می‌کند — بارگذاری دوبارهٔ همان بازه چیزی را دوبرابر نمی‌کند.",
      angebote: "پیشنهادهای قیمت",
      angeboteText:
        "حجم پیشنهادها در هر هفته و برای هر فروشنده. پیشنهادهای بدون ثبت‌کننده در هیچ میله‌ای نمی‌آیند.",
      interessenten: "مشتریان بالقوه",
      interessentenText:
        "داده‌های پایهٔ مشتریان بالقوه. مشتری بالقوه‌ای که دوباره ذخیره شود با تاریخ تازه‌اش به هفتهٔ دیگری می‌رود.",
    },
  },
  organigramm: {
    einleitung:
      "از Personio. هرکس آنجا سرپرستی برایش ثبت نشده باشد در بالا می‌ایستد — این برای " +
      "مدیریت درست است و در بقیهٔ موارد نشانهٔ خلأ در داده‌های پایه.",
    suchfeld: "نفر، سمت یا بخش",
    suchePlatzhalter: "نام، سمت، بخش",
    standort: "محل",
    alleStandorte: "همهٔ محل‌ها",
    personen: (anzahl: number) => `${anzahl} نفر`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} بدون سرپرست`,
    niemand: "کسی یافت نشد",
    niemandText: "جست‌وجوی دیگر، محل دیگر — یا همگام‌سازی Personio هنوز اجرا نشده است.",
    aufklappen: (name: string) => `${name} باز شود`,
    zuklappen: (name: string) => `${name} بسته شود`,
    direkt: (anzahl: number) => `${anzahl} مستقیم`,
  },
  offeneSchulungen: {
    einleitung:
      "چه کسی به چه چیزی نیاز دارد. فقط آموزش‌های فعال؛ آموزش‌های متوقف‌شده اینجا نمی‌آیند.",
    zumKatalog: "به فهرست آموزش‌ها",
    allesOffene: "همهٔ موارد باقی‌مانده",
    nieAbsolviert: "هرگز گذرانده نشده",
    ueberfaellig: "سررسید گذشته",
    wirdFaellig: "نزدیک سررسید",
    suchen: "جست‌وجوی نفر یا آموزش",
    suchenAria: "جست‌وجو",
    nichtsOffen: "چیزی باقی نمانده",
    nichtsOffenText: "همهٔ آموزش‌های فعال در دورهٔ خود هستند — یا هنوز چیزی خوانده نشده است.",
    eintraege: (anzahl: number) => `${anzahl} مورد.`,
    person: "نفر",
    schulung: "آموزش",
    bereich: "حوزه",
    zuletzt: "آخرین بار",
    faellig: "سررسید",
    stand: "وضعیت",
    nie: "هرگز گذرانده نشده",
    imTurnus: "در دوره",
  },
  schulungsmatrix: {
    einleitung:
      "همهٔ افراد در برابر همهٔ آموزش‌ها — نمای کلی برای تابلوی اعلانات و برای ممیزی. " +
      "هرکس هیچ شرکتی نداشته باشد با سطر خالی در آن می‌آید؛ همین همان خلأیی است که " +
      "دنبالش می‌گردند.",
    wasOffenIst: "آنچه باقی مانده",
    katalog: "فهرست آموزش‌ها",
    suchfeld: "نفر یا بخش",
    suchePlatzhalter: "نام، بخش، شمارهٔ پرسنلی",
    bereich: "حوزه",
    alleBereiche: "همهٔ حوزه‌ها",
    nurLuecken: "فقط افراد دارای خلأ",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} از ${gesamt} نفر · ${schulungen} آموزش`,
    niemand: "کسی همخوان نیست",
    niemandText: "جست‌وجوی دیگر یا حوزهٔ دیگر — یا واقعاً کسی باقی نمانده است.",
    person: "نفر",
    nichtZugewiesen: (person: string, schulung: string) =>
      `${person} · ${schulung}: تخصیص نیافته`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (سررسید ${datum})`,
    offen: "باقی‌مانده",
    personio: "Personio",
    externGepflegt: "بیرون از سامانه نگهداری می‌شود",
    ohneTreffer: "بدون یافتن در Personio",
  },
  schulungen: {
    einleitung:
      "فهرست آموزش‌ها، دورهٔ آن‌ها و اینکه چه کسی آن را برآورده می‌کند. سررسیدها از " +
      "آخرین تاریخ و دوره محاسبه می‌شوند و ذخیره نمی‌شوند.",
    dokumentenlauf: "گردش مدارک",
    bereich: "حوزه",
    neueSchulung: "آموزش تازه",
    beispiel: "برای نمونه آموزش ایمنی آتش",
    anlegen: "بساز",
    wirdGelesen: "در حال خواندن …",
    uebersichtEinlesen: "خواندن فهرست آموزش‌ها",
    einlesenAria: "خواندن فهرست کلی آموزش‌ها",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} آموزش (${neu} تازه)، ${teilnahmen} شرکت، که ${zugeordnet} مورد به نفری در Personio نسبت داده شد.`,
    ohneTreffer: "بدون یافتن در Personio: ",
    ohneTrefferNach: ". این سطرها با شمارهٔ پرسنلی و نام همچنان همراه می‌آیند.",
    wirdUebernommen: "در حال پذیرش …",
    uebernehmen: "بپذیر",
    abbrechen: "انصراف",
    keineSchulung: "هنوز آموزشی نیست",
    keineSchulungText: "یکی بسازید یا فهرست کلی آموزش‌ها را بخوانید.",
    schulung: "آموزش",
    turnus: "دوره",
    frist: "مهلت (روز)",
    verantwortlich: "مسئول",
    offen: "باقی‌مانده",
    aktiv: "فعال",
    nichtBerechenbar: "(قابل محاسبه نیست)",
    zahlGroesserNull: "لطفاً عددی بزرگ‌تر از 0 وارد کنید.",
    nieKurz: (anzahl: number) => `${anzahl} هرگز`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} سررسید گذشته`,
    baldKurz: (anzahl: number) => `${anzahl} به‌زودی`,
    aktivSchalter: (name: string) => `${name} فعال`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} یعنی: برای این نفر تاریخی در سابقه نیست. ${bald} یعنی: در دو ماه آینده. به تاریخ ${datum}.`,
  },
  schulung: {
    gibtEsNicht: "این آموزش وجود ندارد",
    gibtEsNichtText: "احتمالاً حذف شده است.",
    ohneTurnus: "بدون دوره",
    keineFaelligkeit: " — از آن سررسیدی محاسبه نمی‌شود",
    zumKatalog: "به فهرست آموزش‌ها",
    stammdaten: "داده‌های پایه",
    turnus: "دوره",
    turnusBeispiel: "برای نمونه سالانه",
    turnusHinweis: "متن آن؛ شمار ماه‌ها از خواندن فایل می‌آید.",
    turnusMonate: "دوره به ماه",
    monateHinweis: "خالی یعنی: سررسیدی محاسبه نمی‌شود.",
    verantwortlich: "مسئول",
    beschreibung: "شرح",
    fuerWen: "برای چه کسانی الزامی است؟",
    kuerzel: "کد بخش",
    kuerzelHinweis: "الگوی ریز از فایل Excel (NÄH، CUT، WVK …).",
    personioAbteilung: "بخش در Personio",
    personioHinweis: "بخش کلی، همان‌گونه که Personio نگه می‌دارد.",
    entfernen: (was: string) => `حذف ${was}`,
    keine: "هیچ",
    ergaenzen: (was: string) => `افزودن ${was}`,
    hinzufuegen: "افزودن",
    teilnahmen: "شرکت‌ها",
    nochNiemand: "هنوز کسی نیست — فهرست کلی آموزش‌ها را بخوانید یا کسی را ثبت کنید.",
    person: "نفر",
    abteilungKurz: "بخش",
    erstschulung: "آموزش نخست",
    zuletzt: "آخرین بار",
    faellig: "سررسید",
    stand: "وضعیت",
    keinTreffer: "در Personio یافت نشد — سطر با این حال می‌ماند",
    nichtInPersonio: "در Personio نیست",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "این شرکت",
    personErgaenzen: "افزودن نفر",
    nameForm: "نام خانوادگی، نام",
  },
  kompetenzen: {
    einleitung:
      "آنچه یک سمت می‌طلبد و اینکه تا چه اندازه برآورده شده — برای هر حوزه یک ماتریس. " +
      "از فایل حوزه خوانده می‌شود و سپس اینجا نگهداری می‌شود.",
    zumDashboard: "به داشبورد کارکنان",
    bereich: "حوزه",
    wirdGelesen: "در حال خواندن …",
    einlesen: "خواندن فایل حوزه",
    vorschauKopf: (datei: string, bereich: string) => `${datei} — ${bereich} پس از آن چنین می‌شود:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} صلاحیت، ${personen} نفر، ${bewertungen} ارزیابی.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `${zugeordnet} از ${personen} نفر در Personio یافت شد`,
    platzhalter: (anzahl: number) => `، ${anzahl} ستون جانگهدار`,
    ohneZuordnung: (namen: string) => ` بدون تخصیص: ${namen}.`,
    ersetztWarnung:
      "برگه‌های مربوط به‌طور کامل جایگزین می‌شوند — تغییرهایی که اینجا نگهداری شده‌اند " +
      "از دست می‌روند.",
    wirdUebernommen: "در حال پذیرش …",
    uebernehmen: "بپذیر",
    abbrechen: "انصراف",
    keineMatrix: "هنوز ماتریسی نیست",
    keineMatrixText: "یک فایل حوزه بخوانید — هر برگهٔ آن یک ماتریس می‌شود.",
    blatt: "برگه",
    titelSpalte: "عنوان",
    stand: "به تاریخ",
    eingelesen: "خوانده‌شده",
    produktion: "تولید",
    verwaltung: "اداری",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    einleitung:
      "از نمره‌ها و نکته‌ها زبان گواهی ساخته می‌شود. داده‌های پایه هنگام ساخت رونویسی " +
      "می‌شوند — گواهی صادرشده با تغییر Personio تغییر نمی‌کند.",
    person: "نفر",
    waehlen: "— برگزینید —",
    art: "نوع",
    anlegen: "بساز",
    keines: "هنوز گواهی‌ای نیست",
    keinesText: "نفری و نوع گواهی را برگزینید — داده‌های پایه خودبه‌خود می‌آیند.",
    zeitraum: "بازه",
    note: "نمره",
    stand: "وضعیت",
    angelegt: "ساخته‌شده",
    fertig: "آماده",
    entwurf: "پیش‌نویس",
    qualifiziert: "گواهی کار مشروح",
    einfach: "گواهی کار ساده",
    zwischenzeugnis: "گواهی کار میان‌دوره",
    ausbildungszeugnis: "گواهی کارآموزی",
    praktikumszeugnis: "گواهی کارورزی",
  },
  einarbeitung: {
    einleitung:
      "آنچه یک نفر تازه‌وارد باید بیاموزد و اینکه چه کسی به او نشان می‌دهد. برگه از " +
      "موضوع‌هایی ساخته می‌شود که برای بخش او ثبت شده‌اند.",
    bogenErzeugen: "ساخت برگه",
    person: "نفر",
    waehlen: "— برگزینید —",
    wirdGebaut: "در حال ساخت …",
    einarbeitungsplan: "برنامهٔ آشناسازی",
    keineInhalte: "هنوز موضوعی ثبت نشده است — برگه خالی می‌ماند.",
    abteilungVon: (abteilung: string) => `بخش ${abteilung}`,
    neuerInhalt: "موضوع تازه",
    beispiel: "برای نمونه آموزش ایمنی کار با فرز",
    anlegen: "بساز",
    keinInhalt: "هنوز موضوعی نیست",
    keinInhaltText:
      "تعیین کنید یک نفر تازه‌وارد چه باید بیاموزد — و این برای کدام بخش‌ها معتبر است.",
    inhalt: "موضوع",
    ansprechpartner: "نفر مرجع",
    bereich: "حوزه",
    fuerAbteilungen: "برای کدام بخش‌ها",
    abteilung: "بخش",
    bereichLeer: "خالی یعنی: بخش از ماتریس گرفته شود",
    entfernen: (was: string) => `حذف ${was}`,
    abteilungHinzu: "+ بخش",
    abteilungFuer: (inhalt: string) => `بخش برای ${inhalt}`,
  },
  matrix: {
    gibtEsNicht: "این ماتریس وجود ندارد",
    gibtEsNichtText: "احتمالاً جایگزین شده است.",
    blattStand: (blatt: string) => `برگهٔ ${blatt}`,
    stand: (datum: string) => ` · به تاریخ ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} صلاحیت، ${personen} نفر`,
    zurUebersicht: "به نمای کلی",
    qualifikation: "صلاحیت",
    keineZeilen: "این ماتریس هنوز سطری ندارد.",
    stufenBedeuten: "معنای سطح‌ها",
    erfuellungsgradHinweis:
      "عدد دوم درجهٔ برآورده‌شدن به درصد است. خانه‌ای که الزام دارد و کمتر از 100 ٪ " +
      "است یک خلأ است و با رنگ هشدار نشان داده می‌شود.",
    ergaenzen: "افزودن",
    neueQualifikation: "صلاحیت تازه",
    beispiel: "برای نمونه ماشین تراش",
    kategorie: "دسته",
    ohne: "بدون",
    zeile: "سطر",
    neuePerson: "نفر تازه",
    namensform: "نام و نام خانوادگی",
    spalte: "ستون",
    anforderungslevel: "سطح مورد نیاز",
    erfuellungsgrad: "درجهٔ برآورده‌شدن به درصد",
    stufe0: "لازم نیست",
    stufe1: "دانش پایه",
    stufe2: "با راهنمایی کار می‌کند",
    stufe3: "مستقل کار می‌کند",
    stufe4: "می‌تواند راهنمایی و آموزش دهد",
  },
  zeugnis: {
    gibtEsNicht: "این گواهی وجود ندارد",
    gibtEsNichtText: "احتمالاً حذف شده است.",
    durchschnitt: (wert: string) => ` · میانگین ${wert}`,
    zurUebersicht: "به نمای کلی",
    zeugnisVon: (name: string) => `گواهی کار ${name}`,
    stammdaten: "داده‌های پایه",
    stammdatenHinweis:
      "هنگام ساخت رونویسی شده است. تغییرها اینجا تنها برای همین گواهی معتبرند — " +
      "Personio دست‌نخورده می‌ماند.",
    name: "نام",
    personalnummer: "شمارهٔ پرسنلی",
    abteilung: "بخش",
    taetigkeit: "سمت",
    eintritt: "تاریخ ورود",
    austritt: "تاریخ خروج",
    geburtsdatum: "تاریخ تولد",
    ausstellungsdatum: "تاریخ صدور",
    ohneNamen: "بدون نام ممکن نیست.",
    anrede: "عنوان خطاب",
    frau: "خانم",
    herr: "آقای",
    anredeHinweis: "عنوان خطاب و ضمیرهای متن را تعیین می‌کند.",
    art: "نوع",
    anlass: "علت",
    anlassBeispiel: "برای نمونه درخواست خود فرد",
    fuehrungskraft: "مدیر",
    fuehrungskraftHinweis: "مدیر — بُعد «رهبری» را نمایان می‌کند",
    bewertung: "ارزیابی",
    bewertungHinweis:
      "نمره‌های 1 تا 4. عبارت رضایت از میانگین برمی‌آید — نه برعکس.",
    fachwissen: "دانش تخصصی",
    auffassungsgabe: "قدرت درک",
    arbeitsweise: "شیوهٔ کار",
    belastbarkeit: "تحمل فشار کاری",
    arbeitserfolg: "نتیجهٔ کار",
    sozialverhalten: "رفتار اجتماعی",
    fuehrung: "رهبری",
    aufgaben: "وظایف (نکته‌وار)",
    aufgabenHinweis: "هر سطر یک وظیفه — از آن فهرست گواهی ساخته می‌شود.",
    kompetenzen: "صلاحیت‌های ویژه",
    kompetenzenHinweis: "در ارزیابی عملکرد وارد می‌شود.",
    erfolge: "دستاوردهای ویژه",
    erfolgeHinweis: "پروژه‌ها، تقدیرها، نتیجه‌های سنجش‌پذیر.",
    text: "متن",
    baut: "در حال ساخت …",
    ausBausteinen: "از قطعه‌های آماده",
    formuliert: "در حال نگارش …",
    mitKi: "با هوش مصنوعی",
    textHinweis:
      "قطعه‌های آماده بدون شبکه و بدون هوش مصنوعی می‌نویسند. هوش مصنوعی آزادتر " +
      "می‌نویسد — تنها عنوان خطاب، سمت، بخش، مدت، نمره‌ها و متن‌های آزاد بالا به آن " +
      "می‌رسد. نام، تاریخ تولد و شمارهٔ پرسنلی سرور را ترک نمی‌کنند.",
    nochKeinText: "هنوز متنی نیست. نمره‌ها را بدهید و متن را بسازید.",
    fertigSchalter: "گواهی آماده است",
    fertigHinweis: "آماده — دیگر در دست کار نیست",
    unterschriftenFehler: (meldung: string) => `امضاها تعیین نشد (${meldung}).`,
    darunterSteht: "امضاکنندگان",
    fachlich: "سرپرست مستقیم",
    personalwesen: "امور کارکنان",
    niemandHinterlegt: "— کسی ثبت نشده —",
    unterschriftFehlt:
      "یک امضا کم است. آن را در تنظیمات ← گواهی‌های کار ثبت کنید، یا سرپرست را در " +
      "Personio نگه دارید.",
    ausPersonio: "از Personio",
    ausEinstellungen: "از تنظیمات",
    nichtHinterlegt: "ثبت نشده",
    einleitung: "مقدمه",
    taetigkeitsbeschreibung: "شرح وظایف",
    leistungsbeurteilung: "ارزیابی عملکرد",
    schlussformel: "عبارت پایانی",
    hinweisDeutsch: "خود گواهی به آلمانی نوشته می‌شود.",
  },
  dokumentenlauf: {
    einleitung:
      "برگه‌های دارای QR: ساختن، تحویل دادن، پرشده پس گرفتن، بررسی کردن. QR اسکن را " +
      "دوباره نسبت می‌دهد — فارغ از اینکه نام فایل چیست.",
    formblatt: "فرم",
    fuerWen: "برای چه کسی",
    personWaehlen: "— نفر را برگزینید —",
    erzeugt: "در حال ساخت …",
    blattErzeugen: "ساخت برگه",
    standFilter: "وضعیت:",
    alle: "همه",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} از ${gesamt}`,
    keinVorgang: "هیچ پرونده‌ای نیست",
    keinVorgangText: "بالا یک برگه بسازید — QR می‌گیرد و از آن پس دنبال می‌شود.",
    person: "نفر",
    kennung: "کد",
    stand: "وضعیت",
    vollstaendigSpalte: "کامل",
    blatt: "برگه",
    scan: "اسکن",
    prueft: "در حال بررسی …",
    scanFuer: (name: string) => `بارگذاری اسکن برای ${name}`,
    zu: "بستن",
    details: "جزئیات",
    nochNichtGeprueft: "— هنوز بررسی نشده",
    vollstaendig: "کامل",
    unvollstaendig: "ناقص",
    umkehren: "وارونه‌کردن داوری — سنجش تنها می‌بیند که در خانه جوهری هست یا نه",
    pruefung: "بررسی",
    qrGelesen: "— QR خوانده شد",
    keinQr: "— QR یافت نشد، خانه‌ها قابل نسبت‌دادن نیستند",
    nachweise: "مستندها",
    keineNachweise: "هنوز چیزی ثبت نشده است.",
    welcheZeile: "مربوط به کدام سطر؟ (اختیاری)",
    laedt: "در حال بارگذاری …",
    nachweis: "مستند",
    nachweisHoch: "بارگذاری مستند",
    erstellt: "ساخته‌شده",
    uebergeben: "تحویل‌شده",
    zurueck: "بازگشته",
    geprueft: "بررسی‌شده",
    einarbeitungsplan: "برنامهٔ آشناسازی",
    schulungsnachweis: "مستند آموزش",
  },
  onboarding: {
    einleitung:
      "چه کسی تازه‌وارد است و ماتریس الزام‌ها چه آموزش‌هایی برای او می‌خواهد. برنامه " +
      "ذخیره نمی‌شود بلکه محاسبه می‌شود — با تغییر ماتریس، برنامه هم تغییر می‌کند.",
    nichtsGefehlt: "چیزی کم نبود.",
    angelegt: (anzahl: number) => `${anzahl} آموزش ساخته شد.`,
    neu90: "تازه (90 روز گذشته)",
    alle: "همه",
    personen: (anzahl: number) => `${anzahl} نفر`,
    keineEintritte: "ورودی‌ای نیست",
    keineEintritteText: "به‌محض اینکه کسی با تاریخ ورود از Personio بیاید، اینجا می‌ایستد.",
    person: "نفر",
    abteilung: "بخش",
    position: "سمت",
    eintritt: "تاریخ ورود",
    uebergabe: "تحویل",
    nichtInPersonio: "در Personio نیست",
    hierGesetzt: "اینجا تعیین شده — بر Personio مقدم است",
    ausPersonio: "از Personio",
    vermerken: "ثبت کن",
    paketTitel: "برنامهٔ آشناسازی و فهرست آموزش‌ها در یک PDF",
    paket: "بسته",
    uebersichtTitel: "فقط فهرست آموزش‌ها (فرم 71)",
    uebersicht: "نمای کلی",
    planZu: "بستن برنامه",
    plan: "برنامه",
    schulungsplan: "برنامهٔ آموزش",
    fehlendeAnlegen: "ساختن موارد کم",
    wirdGerechnet: "در حال محاسبه …",
    bruecke: "سمت ← کد بخش",
    brueckeHinweis:
      "پل میان Personio و لایهٔ ریز ماتریس الزام‌ها. بدون ورودی، لایهٔ ریز برای این " +
      "سمت اثر ندارد — برنامه این را صریح می‌گوید.",
    kuerzel: "کد",
    positionBeispiel: "برای نمونه اپراتور فرز CNC",
    kuerzelBeispiel: "CNC",
    zuordnen: "نسبت بده",
    ohnePersonio: "نفر بدون Personio",
    ohnePersonioHinweis:
      "برای ورودی‌هایی که هنوز در همگام‌سازی نیستند — یا اصلاً آنجا جایی ندارند.",
    name: "نام",
    anlegen: "بساز",
    kuerzelFehlt: (position: string) =>
      `برای سمت ${position} کد بخشی ثبت نشده است. لایهٔ ریز ماتریس الزام‌ها ` +
      "به همین دلیل برای این نفر اثر ندارد — ممکن است آموزش‌های الزامی کم باشد.",
    matrixVerlangtNichts: "ماتریس الزام‌ها برای این بخش چیزی نمی‌خواهد.",
    schulung: "آموزش",
    bereich: "حوزه",
    turnus: "دوره",
    pflichtUeber: "الزامی از راه",
    stand: "وضعیت",
    ueberAbteilung: "بخش",
    ueberKuerzel: "کد",
    vorhanden: "موجود",
    fehlt: "کم است",
  },
  audit: {
    einleitung:
      "ممیزی‌ها از برنامه‌ریزی تا پایان. هر تغییر وضعیت در سابقه می‌آید — نوشتهٔ " +
      "پایگاه داده، نه فرم، و پس از آن تغییرناپذیر.",
    zuKennzahlen: "به شاخص‌ها",
    nummer: "شماره",
    nummerBeispiel: "A-2026-01",
    titel: "عنوان",
    titelBeispiel: "ممیزی سامانه EN 9100",
    art: "نوع",
    intern: "درونی",
    extern: "بیرونی",
    phasenvorlage: "الگوی مرحله‌ها",
    ohne: "بدون",
    anlegen: "بساز",
    keinAudit: "هنوز ممیزی‌ای نیست",
    keinAuditText: "یکی بسازید — با الگوی مرحله‌ها فهرست بررسی‌اش را همراه می‌آورد.",
    laufen: (laufend: number, gesamt: number) => `${laufend} از ${gesamt} هنوز در جریان است.`,
    status: "وضعیت",
    fortschritt: "پیشرفت",
    naechsterTermin: "موعد بعدی",
    ueberfaellig: (anzahl: number) => `${anzahl} سررسید گذشته`,
    geplant: "برنامه‌ریزی‌شده",
    inVorbereitung: "در حال آماده‌سازی",
    inDurchfuehrung: "در حال اجرا",
    berichtet: "گزارش‌شده",
    massnahmenOffen: "اقدام‌های باز",
    abgeschlossen: "پایان‌یافته",
    verschoben: "به تعویق افتاده",
    abgesagt: "لغوشده",
    phaseOffen: "باز",
    phaseInArbeit: "در دست کار",
    phaseErledigt: "انجام‌شده",
    phaseNichtZutreffend: "بی‌ربط",
    system: "سامانه",
    prozess: "فرایند",
    produkt: "محصول",
    lieferant: "تأمین‌کننده",
  },
  wartung: {
    einleitung:
      "ماشین‌ها و کارهای نگهداری تکرارشوندهٔ آن‌ها. مستند به شکل برگه‌ای برای نصب " +
      "ساخته می‌شود — برای هر نیم‌سال، با یک ستون برای هر هفتهٔ تقویمی.",
    zuKennzahlen: "به شاخص‌ها",
    neueMaschine: "ماشین تازه",
    beispiel: "برای نمونه فرز 3",
    anlegen: "بساز",
    keineMaschine: "هنوز ماشینی نیست",
    keineMaschineText: "یک ماشین بسازید و کارهای نگهداری‌اش را ثبت کنید.",
    maschine: "ماشین",
    inventarnummer: "شمارهٔ اموال",
    standort: "محل",
    verantwortlich: "مسئول",
    status: "وضعیت",
    aktiv: "فعال",
    stillgelegt: "از کار افتاده",
  },
  sensoren: {
    einleitung:
      "دما و رطوبت، هر پنج دقیقه یک بار خوانده می‌شود. مقداری بیرون از مرزهای " +
      "تنظیم‌شده با رنگ هشدار نشان داده می‌شود.",
    misst: "در حال اندازه‌گیری …",
    jetztMessen: "اکنون اندازه بگیر",
    keinGeraet: "دستگاهی تنظیم نشده است",
    keinGeraetText: "حسگرها در تنظیمات ساخته می‌شوند — رایانه، شناسه و Community.",
    verlauf: "روند",
    stunden: (n: number) => `${n} ساعت`,
    tage: (n: number) => `${n} روز`,
    temperatur: "دما",
    luftfeuchte: "رطوبت",
    zuletzt: (zeit: string) => `آخرین بار ${zeit}`,
    keinMesswert: "هنوز اندازه‌ای نیست.",
    nichtsGemessen: "در این بازه چیزی اندازه‌گیری نشده است.",
    frisch: "به‌روز",
    verzoegert: "با تأخیر",
    offline: "آفلاین",
    unbekannt: "هنوز چیزی اندازه‌گیری نشده",
  },
  hilfe: {
    einleitung:
      "پلتفرم چه می‌تواند، عددها چگونه به دست می‌آیند و اگر چیزی درست نبود چه باید کرد.",
    nurDeutsch: "صفحه‌های راهنما خودشان به آلمانی نوشته شده‌اند.",
    suchen: "جست‌وجو در راهنما",
    nichtsGefunden:
      "چیزی یافت نشد. اگر چیزی در راهنما نیست، آن را با دکمهٔ گزارش در پایین سمت چپ بگویید.",
    alleThemen: "→ همهٔ موضوع‌ها",
  },
  meldungen: {
    stand: (offen: number) => `آنچه از نماها گزارش شده است. ${offen} باز`,
    neuSeit: (anzahl: number) => ` · ${anzahl} تازه از آخرین بازدید`,
    nichtsGemeldet: "چیزی گزارش نشده",
    nichtsGemeldetText:
      "با دکمهٔ پایین سمت چپ، هر کاربر واردشده می‌تواند گزارش دهد که در صفحه چه " +
      "چیزی درست نیست.",
    unbekannt: "نامشخص",
    bild: "تصویر",
    status: "وضعیت",
    offen: "باز",
    erledigt: "انجام‌شده",
    meldung: "گزارش",
    aufnahme: "تصویر صفحه",
  },
  auditAnsicht: {
    gibtEsNicht: "این ممیزی وجود ندارد",
    gibtEsNichtText: "احتمالاً حذف شده است.",
    internesAudit: "ممیزی درونی",
    externesAudit: "ممیزی بیرونی",
    prioritaet: (stufe: string) => ` · اولویت ${stufe}`,
    erledigt: (prozent: number) => ` · ${prozent} ٪ انجام‌شده`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} سررسید گذشته`,
    zurUebersicht: "به نمای کلی",
    status: "وضعیت",
    stammdaten: "داده‌های پایه",
    titel: "عنوان",
    bereich: "حوزه",
    leitenderAuditor: "سرممیز",
    auditteam: "تیم ممیزی",
    geplantVon: "برنامه از",
    geplantBis: "برنامه تا",
    prioritaetFeld: "اولویت",
    niedrig: "کم",
    mittel: "متوسط",
    hoch: "زیاد",
    auditziel: "هدف ممیزی",
    kategorien: "دسته‌ها",
    kategorienHinweis:
      "یک ممیزی اغلب چند چیز با هم است — برنامهٔ درونی سامانه و فرایند را در یک نوبت " +
      "پیش می‌برد. از این رو انتخاب چندگانه و نه یک مورد.",
    normbezug: "ارجاع به استاندارد",
    normmatrixLeer: "ماتریس استانداردها خالی است — در تنظیمات نگهداری می‌شود.",
    nichtGeprueft: "* هنوز با متن یکپارچهٔ استاندارد سنجیده نشده است.",
    phasen: "مرحله‌ها",
    keinePhasen: "بدون مرحله — این ممیزی بدون الگو ساخته شده است.",
    phase: "مرحله",
    verantwortlich: "مسئول",
    faellig: "سررسید",
    erledigtAm: "انجام در",
    phaseErgaenzen: "افزودن مرحله",
    phaseBeispiel: "برای نمونه ممیزی پیگیری",
    verlauf: "سابقه",
    verlaufHinweis:
      "نوشتهٔ پایگاه داده، نه این فرم — و پس از آن نه تغییرپذیر و نه حذف‌شدنی.",
    nichtsGeschehen: "هنوز چیزی رخ نداده است.",
    warumEntfaellt: "چرا این مرحلهٔ الزامی حذف می‌شود؟",
    uebernehmen: "بپذیر",
    abbrechen: "انصراف",
    angelegt: "ساخته شد",
    geaendert: "تغییر کرد",
    geloescht: "حذف شد",
    uebersprungen: "رد شد",
  },
  maschine: {
    gibtEsNicht: "این ماشین وجود ندارد",
    gibtEsNichtText: "احتمالاً حذف شده است.",
    zurUebersicht: "به نمای کلی",
    stammdaten: "داده‌های پایه",
    name: "نام",
    inventarnummer: "شمارهٔ اموال",
    standort: "محل",
    hersteller: "سازنده",
    modell: "مدل",
    verantwortlich: "مسئول",
    status: "وضعیت",
    aktiv: "فعال",
    stillgelegt: "از کار افتاده",
    notizen: "یادداشت‌ها",
    wartungsaufgaben: "کارهای نگهداری",
    jahr: "سال",
    halbjahr: "نیم‌سال",
    erstesHalbjahr: "هفتهٔ 1–26",
    zweitesHalbjahr: "هفتهٔ 27–52",
    wirdGebaut: "در حال ساخت …",
    nachweisbogen: "برگهٔ مستند",
    neueAufgabe: "کار تازه",
    aufgabeBeispiel: "برای نمونه بررسی سطح روغن",
    intervall: "فاصله",
    wochen: "هفته",
    keineAufgabe: "هنوز کاری نیست — برگه خالی می‌ماند.",
    aufgabe: "کار",
    dateien: "فایل‌ها",
    planHinterlegen: "ثبت برنامه",
    nachweisAblegen: "ثبت مستند",
    dateienHinweis: "برنامهٔ سازنده و برگه‌های امضاشده که اسکن و بازگردانده شده‌اند.",
    keineDatei: "هنوز فایلی نیست.",
    plan: "برنامه",
    nachweis: "مستند",
    laedt: "در حال بارگذاری …",
    taeglich: "روزانه",
    woechentlich: "هفتگی",
    monatlich: "ماهانه",
    quartalsweise: "فصلی",
    alleNWochen: "هر N هفته",
    alleNWochenZahl: (wochen: number) => `هر ${wochen} هفته`,
  },
  atr: {
    einleitung:
      "فهرست قطعه‌ها پایه است: برگهٔ تحویل شرح، نقشه و وزن را از آن می‌گیرد. جست‌وجو " +
      "بر پایهٔ شمارهٔ قطعه و بدون پیرایه انجام می‌شود — تنها رقم‌ها به شمار می‌آیند.",
    zuLieferungen: "به محموله‌ها",
    teilAnlegen: "ساختن دستی قطعه",
    teilBeispiel: "شمارهٔ قطعه، برای نمونه VR-1234-56",
    anlegen: "بساز",
    wirdGelesen: "در حال خواندن …",
    mappeEinlesen: "خواندن پوشهٔ مرجع",
    suchen: "جست‌وجو",
    suchePlatzhalter: "شمارهٔ قطعه، شرح یا نقشه",
    nichtsGefunden: "چیزی یافت نشد",
    katalogLeer: "فهرست قطعه‌ها خالی است",
    keinTeil: "قطعه‌ای با این جست‌وجو همخوان نیست.",
    katalogLeerText: "یک پوشهٔ مرجع بخوانید یا قطعه‌ای را دستی بسازید.",
    teilenummer: "شمارهٔ قطعه",
    bezeichnung: "شرح",
    zeichnung: "نقشه",
    gewicht: "وزن kg",
    kategorie: "دسته",
    nurErste: "فقط 500 مورد نخست — لطفاً جست‌وجو را محدودتر کنید.",
  },
  lieferungen: {
    einleitung:
      "برگهٔ تحویل خوانده می‌شود، با فهرست قطعه‌ها سنجیده می‌شود و به شکل پیش‌نویس " +
      "ذخیره می‌شود. پس از بازبینی آزاد می‌شود.",
    zumKatalog: "به فهرست قطعه‌ها",
    wirdGelesen: "در حال خواندن …",
    einlesen: "خواندن برگهٔ تحویل",
    laeuft: "در حال اجرا …",
    eingangDurchsehen: "بازبینی صندوق ورودی",
    berichtNummer: (nr: string) => ` · شمارهٔ ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} قلم، ${zugeordnet} مورد در فهرست قطعه‌ها یافت شد.`,
    keinLieferschein: "هنوز برگهٔ تحویلی نیست",
    keinLieferscheinSchreiben: "یک PDF برگهٔ تحویل بخوانید — سپس اینجا برای بازبینی می‌ایستد.",
    keinLieferscheinLesen: "به‌محض اینکه برگهٔ تحویلی خوانده شود، اینجا می‌ایستد.",
    lieferschein: "برگهٔ تحویل",
    datum: "تاریخ",
    programm: "برنامه",
    msn: "MSN",
    status: "وضعیت",
    entwurf: "پیش‌نویس",
    freigegeben: "آزادشده",
  },
  durchsicht: {
    nichtGefunden: "محموله یافت نشد.",
    freigeben: "آزاد کن",
    zuruecknehmen: "پس‌گرفتن آزادسازی",
    wirdErzeugt: "در حال ساخت …",
    dokumenteErzeugen: "ساخت مدارک",
    kopfdaten: "داده‌های سربرگ",
    atrNummer: "شمارهٔ ATR",
    containernummer: "شمارهٔ کانتینر",
    satzTitel: "شرح مجموعه",
    programm: "برنامه",
    msn: "MSN",
    bereich: "حوزه",
    wiegedatum: "تاریخ توزین",
    pruefdatum: "تاریخ بازرسی",
    qsUnterschrift: "امضای QS",
    hoechstgewicht: "بیشینهٔ وزن kg",
    positionen: "اقلام",
    pos: "ردیف",
    menge: "مقدار",
    seriennummern: "شماره‌های سریال",
    nichtImKatalog: "در فهرست قطعه‌ها نیست",
    festHinweis:
      "محموله آزاد شده است؛ اقلام قطعی‌اند. پایگاه داده تغییر را رد می‌کند — " +
      "آزادسازی را می‌توان بالا پس گرفت.",
  },
  fair: {
    dateiFehlt: (meldung: string) =>
      `خود نقشه بارگذاری نمی‌شود (${meldung}). اندازه‌ها با این حال در پایین آمده‌اند.`,
    einleitung:
      "بازرسی نمونهٔ نخست: یک نقشه بارگذاری کنید و برای هر اندازهٔ قابل بازرسی یک " +
      "بالون شماره‌دار بگذارید. شماره‌ها را پایگاه داده می‌دهد و بی‌شکاف نگه می‌دارد.",
    bezeichnungFrei: "شرح (خالی = نام فایل)",
    beispiel: "برای نمونه شفت 12×40، نقشهٔ 4711",
    wirdGeladen: "در حال بارگذاری …",
    zeichnungWaehlen: "انتخاب نقشه",
    keineZeichnung: "هنوز نقشه‌ای نیست",
    keineZeichnungSchreiben: "یک PDF یا تصویر بارگذاری کنید — سپس می‌توان اندازه‌ها را بالون‌گذاری کرد.",
    keineZeichnungLesen: "به‌محض اینکه نقشه‌ای بارگذاری شود، اینجا می‌ایستد.",
    bezeichnung: "شرح",
    teilenummer: "شمارهٔ قطعه",
    kunde: "مشتری",
    hochgeladen: "بارگذاری‌شده",
    pruefliste: "فهرست بازرسی",
    einMass: "1 اندازه",
    masse: (anzahl: number) => `${anzahl} اندازه`,
    kopieren: "رونوشت",
    csv: "CSV",
    keinMass: "هنوز اندازه‌ای علامت نخورده است.",
    nr: "شماره",
    seite: "صفحه",
    wert: "مقدار",
    wertBeispiel: "برای نمونه 12.0 h7",
    wertZu: (nummer: number) => `مقدار برای شمارهٔ ${nummer}`,
    nachOben: (nummer: number) => `شمارهٔ ${nummer} به بالا`,
    nachUnten: (nummer: number) => `شمارهٔ ${nummer} به پایین`,
    nummer: (nummer: number) => `شمارهٔ ${nummer}`,
    drehen: "چرخاندن نما",
    verkleinern: "کوچک‌نمایی",
    vergroessern: "بزرگ‌نمایی",
    einpassen: "جای‌دهی",
    zeichnung: "نقشه",
    ladefehler: "نقشه بارگذاری نشد.",
  },
  newsletter: {
    keineAusgabe: "هنوز شماره‌ای نیست",
    keineAusgabeText: "به‌محض اینکه تحریریه شماره‌ای منتشر کند، اینجا می‌ایستد.",
    zurRedaktion: "به تحریریه",
    quartalJahr: (quartal: number, jahr: number) => `فصل ${quartal} · ${jahr}`,
    entwurfSuffix: " · پیش‌نویس",
    ausgabe: "شماره",
    quartalKurz: (quartal: number, jahr: number) => `Q${quartal} ${jahr}`,
    entwurfKlammer: " (پیش‌نویس)",
    alsPdf: "به شکل PDF",
    wirdGesetzt: "در حال صفحه‌آرایی …",
    seiteVon: (nr: number, gesamt: number) => `صفحهٔ ${nr} از ${gesamt} …`,
    redaktion: "تحریریه",
    niemandDazu: "در این فصل کسی تازه نیامده است.",
    beitraege: "مطالب",
    belegschaftInZahlen: "نیروی انسانی در اعداد",
    neuBeiUns: "تازه‌واردان",
    redaktionEinleitung:
      "برای هر فصل یک شماره. فصل‌ها ترتیب را در دفترچه تعیین می‌کنند؛ انتشار تنها پس " +
      "از آماده‌شدن انجام می‌شود.",
    zurLeseransicht: "به نمای خواننده",
    jahr: "سال",
    quartal: "فصل",
    ausgabeAnlegen: "ساخت شماره",
    ausgabeBearbeiten: "ویرایش شماره",
    keineAusgabeRedaktion: "سال و فصل را برگزینید و بسازید — سپس فصل‌ها اینجا پدید می‌آیند.",
    titelDerAusgabe: "عنوان شماره",
    status: "وضعیت",
    entwurf: "پیش‌نویس",
    veroeffentlicht: "منتشرشده",
    titelbild: "تصویر جلد",
    rueckseite: "پشت جلد",
    ersetzen: " را جایگزین کن",
    waehlen: " را برگزین",
    ausgabeLoeschen: (quartal: number, jahr: number) => `شمارهٔ Q${quartal} ${jahr}`,
    neuesKapitel: "فصل تازه",
    kapitelBeispiel: "برای نمونه از خط تولید",
    art: "نوع",
    hinzufuegen: "افزودن",
    kapiteltitel: "عنوان فصل",
    kapitelHoch: "فصل به بالا",
    kapitelRunter: "فصل به پایین",
    ueberschrift: "سرتیتر",
    eintrag: "مطلب",
    textMarkdown: "متن. Markdown مجاز است — **پررنگ**، فهرست‌ها، جدول‌ها.",
    text: "متن",
    bild: "تصویر",
    bildGroesse: (nr: number) => `اندازهٔ تصویر ${nr}`,
    nieEingefroren: "هنوز چیزی ثابت نشده است — فصل در دفترچه خالی می‌ماند.",
    kpiEingefroren: "اعداد نیروی انسانی این فصل ثابت شده‌اند.",
    niemandEingefroren: "ثابت شد — در این فصل کسی تازه نیامده است.",
    zugaengeEingefroren: (anzahl: number) => `ثابت شد: ${anzahl} تازه‌وارد در این فصل.`,
    einfrieren: "ثابت کن",
    neuEinfrieren: "دوباره ثابت کن",
    rechtFehlt: (quelle: string) => `برای این کار دسترسی به منبع کم است: دیدن ${quelle}.`,
    quelleKpi: "شاخص‌ها",
    quellePersonal: "کارکنان",
    ausgabeAngelegt: "شماره ساخته شد.",
    ausgabeGeloescht: "شماره حذف شد.",
    kapitelAngelegt: "فصل ساخته شد.",
    standEingefroren: "وضعیت ثابت شد.",
  },
  signage: {
    einleitung: "رسانه‌ها، فهرست‌های پخش، زمان‌بندی‌ها و دستگاه‌های نمایشگرها.",
    bereiche: "بخش‌های Signage",
    medien: "رسانه‌ها",
    medienHinzu: "افزودن رسانه",
    playlists: "فهرست‌های پخش",
    zeitplaene: "زمان‌بندی‌ها",
    geraete: "دستگاه‌ها",
    dateiZiehen: "فایل را اینجا بکشید",
    dateiWaehlen: "انتخاب فایل",
    dateiHinweis: "تصویر، ویدئو، PDF یا PPTX، تا 50 MB",
    wirdUebertragen: "در حال انتقال …",
    art: "نوع",
    webseite: "صفحهٔ وب (URL)",
    htmlSchnipsel: "قطعهٔ HTML",
    titel: "عنوان",
    titelBeispiel: "زادروزها",
    urlHinweis:
      "نشانی کامل را بدهید. پخش‌کننده روی پورت جداگانه‌ای اجرا می‌شود و مسیرهای نسبی " +
      "آنجا کار نمی‌کنند.",
    aufnehmen: "بیفزا",
    medienFehler: "رسانه‌ها بارگذاری نشد.",
    keineMedien: "هنوز رسانه‌ای نیست",
    keineMedienText:
      "فایلی بارگذاری کنید یا نشانی‌ای بیفزایید. سپس می‌توان رسانه‌ها را در " +
      "فهرست‌های پخش گرد آورد.",
    erneut: "دوباره",
    inVerwendung: "رسانه در حال استفاده است",
    inVerwendungText: (titel: string, anzahl: number) =>
      `«${titel}» هنوز در ${anzahl} فهرست پخش به کار رفته است. نخست آن را از آنجا بردارید.`,
    verstanden: "فهمیدم",
    wartet: "در انتظار",
    konvertiert: "در حال تبدیل",
    fertig: "آماده",
    fehlgeschlagen: "ناموفق",
    keineHeartbeats: "هنوز ضربانی ثبت نشده است.",
    nieGesehen: "هرگز دیده نشده",
    online: "آنلاین",
    vorMinuten: (minuten: number) => `${minuten} دقیقه پیش`,
    offline: "آفلاین",
    entzogen: "لغوشده",
    keinGeraet: "هنوز دستگاهی جفت نشده است",
    keinGeraetText:
      "نمایشگری را با پخش‌کننده راه بیندازید. کدی شش‌رقمی نشان می‌دهد که اینجا وارد می‌کنید.",
    geraetKoppeln: "جفت‌کردن دستگاه",
    geraet: "دستگاه",
    status: "وضعیت",
    verfuegbarkeit: "در دسترس بودن 24 ساعت",
    ausfaelle: "قطعی‌ها 24 ساعت",
    tags: "برچسب‌ها",
    playlist: "فهرست پخش",
    zuletztGesehen: "آخرین بار دیده‌شده",
    seiteNeuLaden: "بارگذاری دوبارهٔ صفحه",
    neuStarten: "راه‌اندازی دوبارهٔ دستگاه",
    bearbeiten: "ویرایش",
    zugangEntziehen: "لغو دسترسی",
    geraetBearbeiten: "ویرایش دستگاه",
    name: "نام",
    bilddrehung: "چرخش تصویر",
    ton: "صدا",
    tonAktiv: "صدا روشن",
    abbrechen: "انصراف",
    speichern: "ذخیره",
    tagsHinweis: "تعیین می‌کنند این دستگاه کدام فهرست‌های پخش و زمان‌بندی‌ها را می‌گیرد.",
    entziehenText: (name: string) =>
      `«${name}» دسترسی‌اش را بی‌درنگ از دست می‌دهد و دوباره کد جفت‌سازی را نشان می‌دهد.`,
    neustartText: (name: string) => `«${name}» حدود یک دقیقه سیاه می‌ماند.`,
    geraetGespeichert: "دستگاه ذخیره شد.",
    geraetGeloescht: "دستگاه حذف شد.",
    keinGeraetGewaehlt: "دستگاهی برگزیده نشده",
    neuePlaylist: "فهرست پخش تازه",
    neuePlaylistText: "نام و برچسب‌های هدف را تعیین کنید. مدخل‌ها در گام بعد می‌آیند.",
    namensbeispiel: "پذیرش",
    keinePlaylist: "هنوز فهرست پخشی نیست",
    keinePlaylistText:
      "فهرست پخش، رسانه‌ها را در یک ترتیب گرد می‌آورد و از راه برچسب‌ها میان دستگاه‌ها پخش می‌شود.",
    playlistAnlegen: "ساخت فهرست پخش",
    aktiv: "فعال",
    erstellt: "ساخته‌شده",
    kopieren: "رونوشت",
    playlistGeloescht: "فهرست پخش حذف شد.",
    playlistKopiert: "از فهرست پخش رونوشت گرفته شد. مدخل‌ها رونوشت نمی‌شوند.",
    playlistInPlan: "فهرست پخش زمان‌بندی فعال دارد",
    zeitplanHinweis:
      "زمان‌بندی بر تخصیص سادهٔ برچسب مقدم است. بازه‌های گذرنده از نیمه‌شب را به دو " +
      "زمان‌بندی بخش کنید.",
    wochentage: "روزهای هفته",
    wochentagKuerzel: ["دوشنبه", "سه‌شنبه", "چهارشنبه", "پنج‌شنبه", "جمعه", "شنبه", "یکشنبه"],
    von: "از",
    bis: "تا",
    prioritaet: "اولویت",
    zeitplanAktiv: "زمان‌بندی فعال",
    keineZeitplaene: "زمان‌بندی‌ای نیست",
    keineZeitplaeneText:
      "بدون زمان‌بندی تنها تخصیص برچسب تعیین می‌کند دستگاه کدام فهرست پخش را نشان " +
      "دهد. زمان‌بندی، فهرست پخشی را در روزها و ساعت‌های معین جلوتر می‌اندازد.",
    tage: "روزها",
    zeitfenster: "بازهٔ زمانی",
    aktionen: "کنش‌ها",
    zeitplanBearbeiten: "ویرایش زمان‌بندی",
    neuerZeitplan: "زمان‌بندی تازه",
    zeitplaeneFehler: "زمان‌بندی‌ها بارگذاری نشد.",
    endeNachStart: "پایان باید پس از آغاز باشد. برای گذر از نیمه‌شب لطفاً دو زمان‌بندی بسازید.",
    mindestensEinTag: "دست‌کم یک روز هفته را برگزینید.",
    playlistWaehlen: "یک فهرست پخش برگزینید.",
    taeglich: "روزانه",
    zielTags: "برچسب‌های هدف",
    ueberblenden: "محو تدریجی",
    harterSchnitt: "برش تند",
    ziehpunkt: "دستگیرهٔ کشیدن",
    verwerfen: "دورانداختن",
    medienHinzufuegen: "رسانه بیفزایید و با دستگیرهٔ کشیدن مرتبشان کنید.",
    mediumWaehlen: "انتخاب رسانه",
    mediumHinzufuegen: "افزودن رسانه",
    mediumWaehlenText: "رسانهٔ برگزیده در پایان فهرست پخش افزوده می‌شود.",
    schliessen: "بستن",
    keineMedienAnlegen: "هنوز رسانه‌ای نیست. نخست در بخش رسانه‌ها چند مورد بسازید.",
    unbekanntesMedium: "رسانهٔ ناشناخته",
    playlistGespeichert: "فهرست پخش ذخیره شد. دستگاه‌ها بی‌درنگ دوباره بارگذاری می‌کنند.",
    kopplungscode: "کد جفت‌سازی",
    codeBeispiel: "ABC-123",
    geraetename: "نام دستگاه",
    geraeteBeispiel: "پذیرش، سمت چپ",
    tagsPflicht: "دستگاه فهرست پخشش را از راه برچسب‌ها می‌گیرد. بدون برچسب نمایشگر خالی می‌ماند.",
    koppeln: "جفت کن",
    formatErwartet: "قالب XXX-XXX انتظار می‌رود.",
    codeUnbekannt: "کد ناشناخته، منقضی یا پیش‌تر گرفته شده است. روی نمایشگر دوباره نمایش دهید.",
    tagEingeben: "برچسب را بنویسید و Enter بزنید",
  },
  einstellungen: {
    titel: "تنظیمات",
    einleitung: "آنچه پلتفرم محاسبه می‌کند، می‌گیرد و نشان می‌دهد — برای همه یکسان.",
    bereiche: "بخش‌ها",
    gruppen: {
      kennzahlen: "شاخص‌ها",
      kennzahlenText:
        "مقدارهای هدف داشبوردها. در نمودار روند به شکل خط هدف دیده می‌شوند و تعیین " +
        "می‌کنند کارت از چه زمانی هشدار دهد.",
      personal: "کارکنان",
      personalText:
        "اینکه کدام غیبت‌ها بیماری به شمار می‌آیند و کدام بخش‌ها به تولید تعلق دارند. " +
        "بدون این فهرست‌ها نسبت‌های کارکنان خالی می‌مانند.",
      atr: "ATR",
      atrText:
        "آنچه در هر مدرک یک برنامه یکسان است، و اینکه برگه‌های تحویل از کجا می‌آیند.",
      qualitaet: "کیفیت",
      qualitaetText:
        "ماتریس استانداردهایی که ممیزی به آن‌ها استناد می‌کند، و الگوهای مرحله‌ای که " +
        "ممیزی تازه به شکل فهرست بررسی می‌گیرد.",
      sensoren: "حسگرها",
      sensorenText:
        "دستگاه‌های سنجش در شبکه: کجا هستند، با کدام شناسه دما و رطوبت می‌دهند و از " +
        "چه مقداری یک عدد زیاد به شمار می‌آید.",
      zeugnisse: "گواهی‌های کار",
      zeugnisseText:
        "آنچه روی هر گواهی کار یکسان است: شرکت، شهر و دو امضا. امضای سرپرست هنگام " +
        "ساخت از Personio گرفته می‌شود — آنچه اینجا ثبت است تنها پشتیبان آن است.",
      erscheinung: "ظاهر",
      erscheinungText:
        "نشان شرکت — بالا سمت راست در برنامه و در سربرگ هر فایل ساخته‌شده: برنامهٔ " +
        "آشناسازی، مستند نگهداری، فهرست آموزش‌ها، گواهی کار.",
      anzeigen: "نمایشگرها",
      anzeigenText:
        "نشانی‌هایی که روی نمایشگرهای ساختمان اجرا می‌شوند. هر کدام توکنی امضاشده " +
        "دارد، تنها برای همان یک نمایشگر معتبر است و منقضی می‌شود.",
      zugaenge: "کاربران و گروه‌ها",
      zugaengeText:
        "ساختن افراد، تشکیل گروه‌ها و دادن دسترسی برنامه‌ها به آن‌ها. تغییرها از ورود " +
        "بعدی فرد اثر می‌گذارند — دسترسی‌ها در توکن او هستند.",
    },
  },
  einstellungenText: {
    speichernFehler: (meldung: string) => `ذخیره ناموفق بود: ${meldung}`,
    zielwertGespeichert: "مقدار هدف ذخیره شد. داشبوردها آن را پس از بارگذاری دوباره نشان می‌دهند.",
    zahlAbNull: "لطفاً عددی از 0 به بالا وارد کنید.",
    personalGespeichert: "ذخیره شد. داشبورد کارکنان آن را پس از بارگذاری دوباره نشان می‌دهد.",
    krankTypen: "انواع غیبت که بیماری به شمار می‌آیند",
    produktionAbteilungen: "بخش‌های متعلق به تولید",
    kompetenzAttribute: "فیلدهای Personio که صلاحیت ثبت‌شده به شمار می‌آیند",
    ausDemBestand: "از داده‌های همگام‌شده",
    abteilungenBeispiel: "ساخت، مونتاژ",
    firmenlogo: "نشان شرکت",
    anzeigenHinweis:
      "نشانی یک مدخل فهرست پخش را در پخش‌کنندهٔ Signage می‌سازد. تنها برای نمایشگر " +
      "برگزیده معتبر است و منقضی می‌شود — مدخلی که دیگر کسی نگهش نمی‌دارد خودبه‌خود " +
      "از نمایش می‌ایستد.",
    logoHinweis:
      "بالا سمت راست در برنامه و در سربرگ هر فرم ساخته‌شده دیده می‌شود — برنامهٔ " +
      "آشناسازی، مستند نگهداری، فهرست آموزش‌ها، گواهی کار. PNG یا JPEG، حداکثر 5 MB. " +
      "اگر چیزی ثبت نشده باشد، به جای آن نوشتهٔ «ACM-Plattform» می‌آید.",
    communityHinweis: "رمزگذاری‌شده ذخیره می‌شود و دیگر هرگز نشان داده نمی‌شود",
    verwaltenSchliesstEin: "«مدیریت» روی کارت پلتفرم هر دسترسی دیگری را در بر می‌گیرد.",
    logoAlt: "نشان شرکت ثبت‌شده",
    keinsHinterlegt: "هنوز چیزی ثبت نشده است.",
    laedt: "در حال بارگذاری …",
    ersetzen: "جایگزین کن",
    hochladen: "بارگذاری",
    logoHochladen: "بارگذاری نشان شرکت",
    logoHinterlegt: "نشان ثبت شد.",
    anzeige: "نمایشگر",
    geburtstage: "زادروزهای هفته",
    neuzugaenge: "تازه‌واردان تیم",
    gueltigTage: "معتبر برای (روز)",
    erzeugt: "در حال ساخت …",
    adresseErzeugen: "ساخت نشانی",
    adresseKopiert: "نشانی رونوشت شد.",
    kopierenFehler: "رونوشت نشد — لطفاً دستی انتخاب کنید.",
    kopieren: "رونوشت",
    gespeichert: "ذخیره شد.",
    speichern: "ذخیره",
    speichert: "در حال ذخیره …",
    firma: "شرکت",
    ort: "شهر (بالای تاریخ)",
    nameRueckfall: "نام (پشتیبان)",
    titelRueckfall: "عنوان (پشتیبان)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "مشخصات صادرکننده",
    ausstellerHinweis:
      "روی هر گواهی می‌آید. سربرگ ACM به کار می‌رود، به‌محض اینکه «ACM» در نام شرکت باشد.",
    linkeUnterschrift: "امضای چپ — سرپرست مستقیم",
    linkeHinweis:
      "معمولاً سرپرست همان فرد؛ او هنگام ساخت از Personio گرفته می‌شود. آنچه اینجا " +
      "می‌آید تنها وقتی اثر دارد که Personio چیزی ندهد — مثلاً برای افرادی که بیرون " +
      "از سامانه نگهداری می‌شوند.",
    rechteUnterschrift: "امضای راست — امور کارکنان",
    rechteHinweis:
      "برای همهٔ گواهی‌ها یکسان. چون به فردی از Personio بسته است، عنوان از آنجا " +
      "می‌آید و با تغییر سمت درست می‌ماند.",
    personAusPersonio: "فرد از Personio",
    keinePerson: "— هیچ‌کس، متن آزاد پایین به کار رود —",
    personenFehler: (meldung: string) => `فهرست افراد بارگذاری نشد (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "الگوها",
    vorlagenHinweis:
      "برای هر برنامه یک الگو. داده‌های سربرگ و فایل اسکلت در هر مدرک ATR آن برنامه " +
      "یکسان‌اند. الگو هنگام خواندن یک پوشهٔ مرجع در فهرست قطعه‌ها ساخته می‌شود.",
    keineVorlage: "هنوز الگویی نیست",
    keineVorlageText: "یک پوشهٔ مرجع بخوانید — نام برنامه آنجا در خانهٔ D2 است.",
    geruestHinterlegt: "فایل اسکلت ثبت شد.",
    geruestErsetzen: "جایگزینی اسکلت",
    geruestWaehlen: "انتخاب اسکلت",
    keineHinterlegt: "هنوز چیزی ثبت نشده",
    kunde: "مشتری",
    lieferant: "تأمین‌کننده",
    arbeitspaket: "بستهٔ کاری",
    referenz: "مرجع",
    bestellerSpez: "مشخصات سفارش‌دهنده",
    lieferantenSpez: "مشخصات تأمین‌کننده",
    kundenSpez: "مشخصات مشتری",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "فصل ATA",
    waage: "ترازو",
    qsUnterschrift: "امضای QS",
    eingangsordner: "پوشهٔ ورودی",
    eingangHinweis:
      "برگهٔ تحویلی در ورودی خوانده می‌شود، به محموله تبدیل می‌شود و به بایگانی " +
      "می‌رود. گذرواژهٔ حساب سرویس اینجا نیست بلکه به شکل ATR_SMB_PASSWORT در محیط " +
      "است؛ اینکه کدام رایانه‌ها مجازند را ATR_SMB_ERLAUBT تعیین می‌کند.",
    laeuft: "روشن",
    aus: "خاموش",
    zuletzt: (zeit: string, text: string) => `آخرین بار ${zeit}: ${text}`,
    nochNichtGelaufen: "هنوز اجرا نشده است.",
    prueft: "در حال بررسی …",
    verbindungPruefen: "بررسی اتصال",
    laeuftGerade: "در حال اجرا …",
    jetztDurchsehen: "اکنون بازبینی کن",
    verbindungSteht: (dateien: number) =>
      `اتصال برقرار است. ${dateien} فایل در ورودی در انتظار است.`,
    keineVerbindung: (meldung: string) => `اتصالی نیست: ${meldung}`,
    unbekannt: "نامشخص",
    gelesenAngelegt: (gelesen: number, angelegt: number) =>
      `${gelesen} خوانده شد، ${angelegt} ساخته شد.`,
    rechner: "رایانه",
    rechnerHinweis: "باید در ATR_SMB_ERLAUBT باشد",
    freigabe: "پوشهٔ اشتراکی",
    domaene: "دامنه",
    benutzer: "کاربر",
    eingang: "ورودی",
    ausgang: "خروجی",
    archiv: "بایگانی",
    wasEinLaufTut: "یک اجرا چه می‌کند",
    entwurfAnlegen: "ساخت پیش‌نویس برای بازبینی",
    dokumenteErzeugen: "ساخت مدارک و بایگانی آن‌ها",
    regelmaessig: "بازبینی منظم",
    regelmaessigHinweis: "بازبینی منظم — هر ده دقیقه، روزهای کاری 5 تا 19",
  },
  qualitaetEinstellungen: {
    normmatrix: "ماتریس استانداردها",
    normmatrixHinweis:
      "بندهایی که ممیزی به آن‌ها استناد می‌کند. استاندارد در حال استفاده حذف نمی‌شود " +
      "— متوقف می‌شود، وگرنه ممیزی بی‌صدا مبنایش را از دست می‌دهد.",
    schonInMatrix: "این بند پیش‌تر در ماتریس هست.",
    regelwerk: "استاندارد",
    revision: "ویرایش",
    klausel: "بند",
    kurztext: "متن کوتاه",
    kurztextBeispiel: "ممیزی درونی",
    aufnehmen: "بیفزا",
    geprueft: "سنجیده‌شده",
    aktiv: "فعال",
    geprueftSchalter: (norm: string) => `${norm} سنجیده‌شده`,
    aktivSchalter: (norm: string) => `${norm} فعال`,
    phasenvorlagen: "الگوهای مرحله",
    phasenvorlagenHinweis:
      "توالی گام‌هایی که ممیزی تازه می‌گیرد. هنگام ساخت رونویسی می‌شود — تغییر بعدی " +
      "سابقه‌ای را بازنویسی نمی‌کند.",
    neueVorlage: "الگوی تازه",
    vorlageBeispiel: "ممیزی سامانه، استاندارد",
    anlegen: "بساز",
    schritte: (anzahl: number) => `${anzahl} گام`,
    schrittErgaenzen: "افزودن گام",
    schrittBeispiel: "برای نمونه جلسهٔ گشایش",
  },
  personioZugang: {
    titel: "اطلاعات دسترسی Personio",
    einleitung:
      "اطلاعات دسترسی یک برنامهٔ API در Personio. بدون آن‌ها همگام‌سازی، " +
      "تصویرهای نمایه و فهرست‌های پیشنهاد خالی می‌مانند.",
    kennung: "Client-ID",
    geheimnis: "Client-Secret",
    feldHinweis:
      "رمزگذاری‌شده ذخیره می‌شوند و دیگر هرگز نشان داده نمی‌شوند. برای تعویض، " +
      "مقدارهای تازه وارد کنید.",
    speichern: "ذخیره",
    gespeichert: "اطلاعات دسترسی ثبت شد.",
    speichernFehler: (meldung: string) => `ذخیره ناموفق بود: ${meldung}`,
    entfernen: "حذف",
    entfernt: "اطلاعات دسترسی حذف شد.",
    pruefen: "بررسی اتصال",
    prueftGerade: "در حال بررسی …",
    verbindungSteht: "Personio اطلاعات دسترسی را می‌پذیرد.",
    verbindungFehlt: "Personio پاسخ نمی‌دهد.",
    laedt: "در حال بارگذاری …",
    keineHinterlegt: "هیچ اطلاعات دسترسی‌ای ثبت نشده است.",
    ausDerUmgebung: "اطلاعات دسترسی از محیط سرور (.env) معتبر است.",
    hinterlegtSeit: (zeitpunkt: string, wer: string | null) =>
      wer
        ? `ثبت‌شده در ${zeitpunkt} توسط ${wer}.`
        : `ثبت‌شده در ${zeitpunkt}.`,
    ohneSchluessel:
      "روی سرور GEHEIM_SCHLUESSEL تنظیم نشده است. تا وقتی نباشد، چیزی " +
      "رمزگذاری‌شده ذخیره نمی‌شود.",
  },
  sensorEinstellungen: {
    neuesGeraet: "دستگاه تازه",
    name: "نام",
    nameBeispiel: "اتاق سرور",
    rechner: "رایانه",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "باید در SNMP_ERLAUBT باشد",
    community: "Community",
    port: "پورت",
    kennungTemperatur: "شناسهٔ دما",
    kennungLuftfeuchte: "شناسهٔ رطوبت",
    faktorTemperatur: "ضریب دما",
    faktorHinweis: "0.1 اگر دستگاه دهم درجه را به شکل عدد صحیح بدهد",
    faktorLuftfeuchte: "ضریب رطوبت",
    temperaturAb: "دما از (°C)",
    temperaturBis: "دما تا (°C)",
    feuchteAb: "رطوبت از (٪)",
    feuchteBis: "رطوبت تا (٪)",
    farbe: "رنگ در نمودار",
    farbeHinweis: "برای نمونه #0f6e8c",
    optional: "اختیاری",
    anlegen: "بساز",
    fragt: "در حال پرسش …",
    ausprobieren: "بیازما",
    keinGeraet: "هنوز دستگاهی نیست",
    keinGeraetText: "بالا رایانه، Community و دست‌کم یک شناسه وارد کنید.",
    wirdAbgefragt: (name: string) => `${name} پرسیده می‌شود`,
    communityErsetzen: "جایگزینی Community",
    unveraendert: "بدون تغییر",
    communityErsetzt: "Community جایگزین شد.",
    sensorAngelegt: "حسگر ساخته شد.",
    sensorGeloescht: "حسگر همراه با سری زمانی‌اش حذف شد.",
    zahlEingeben: "لطفاً عددی وارد کنید.",
  },
  zugaenge: {
    stufen: {
      viewer: "مشاهده",
      editor: "ویرایش",
      admin: "مدیریت",
    },
    gruppeAngelegt: "گروه ساخته شد.",
    gruppeGibtEsSchon: "گروهی با این نام هست.",
    personAngelegt: "فرد ساخته شد",
    gruppeUmbenannt: "نام گروه تغییر کرد.",
    gruppeGeloescht: "گروه حذف شد.",
    mitgliedHinzu: "عضو افزوده شد. از ورود بعدی اثر می‌گذارد.",
    schonInGruppe: "این فرد پیش‌تر در گروه است.",
    neuesPasswort: "گذرواژهٔ تازه",
    mitgliedEntfernt: "عضو حذف شد. از ورود بعدی اثر می‌گذارد.",
    gemeldeteSeiten: "دیدن صفحه‌های گزارش‌شده",
    neueGruppe: "گروه تازه",
    gruppeBeispiel: "برای نمونه فروش داخلی",
    anlegen: "بساز",
    neuePerson: "فرد تازه",
    personBeispiel: "vorname.nachname@acm.local",
    keineGruppe: "هنوز گروهی نیست",
    keineGruppeText: "گروهی بسازید، به آن دسترسی برنامه‌ها بدهید و افراد را در آن بگیرید.",
    verzeichnis: "دایرکتوری",
    ausVerzeichnis: "از دایرکتوری می‌آید",
    umbenennen: "تغییر نام",
    keinZugriff: "بدون دسترسی",
    rechteAnGruppe: "دسترسی‌ها به گروه بسته‌اند، نه به فرد.",
    passwortNurJetzt:
      "گذرواژه تنها همین حالا اینجاست. پس از آن تنها می‌توان آن را بازنشاند، نه دید.",
    fertig: "پایان",
    anmeldung: "ورود",
    passwort: "گذرواژه",
    gruppeUmbenennen: "تغییر نام گروه",
    abbrechen: "انصراف",
    speichern: "ذخیره",
    gruppenname: "نام گروه",
    mitgliederVon: (name: string) => `اعضای «${name}»`,
    wirktNachAnmeldung: "تغییرها از ورود بعدی فرد اثر می‌گذارند.",
    schliessen: "بستن",
    personHinzufuegen: "افزودن فرد",
    auswaehlen: "— برگزینید —",
    hinzufuegen: "افزودن",
    keineMitglieder: "این گروه هنوز عضوی ندارد.",
    passwortZuruecksetzen: "بازنشاندن گذرواژه",
    mitgliedEntfernen: "حذف عضو",
    entfernen: "حذف",
  },
  kopftitel: {
    start: "برنامه‌ها",
    kennzahlen: "داشبورد KPI",
    offeneSchulungen: "آموزش‌های باقی‌مانده",
    schulungsmatrix: "ماتریس آموزش",
    atrLieferungen: "محموله‌های ATR",
  },
  kennzahlenHub: {
    titel: "داشبورد KPI",
    einleitung: "شاخص‌ها به تفکیک حوزه. داده‌ها از خروجی‌های ERP در بخش بارگذاری‌ها می‌آیند.",
    bereiche: {
      "/kpi/vertrieb": "درآمد، ارزش سفارش، سهم مشتریان",
      "/hr/kennzahlen": "نیروی انسانی، ترک خدمت، بیماری — دسترسی جداگانه",
      "/kpi/qualitaet": "یافته‌های ممیزی و نرخ شکایت",
      "/kpi/finanzen": "نسبت هزینهٔ مواد و پرسنل",
      "/kpi/einkauf": "پایبندی تأمین‌کنندگان به موعد تحویل",
      "/kpi/produktion": "تأخیر، سفارش‌های سررسیدگذشته",
      "/kpi/bewertung": "نظرها و اقدام‌ها برای هر شاخص",
    },
  },
  personalHub: {
    einleitung: "کار با کارکنان، به تفکیک حوزه. عددها یکی از آن‌هاست.",
    bereiche: {
      "/hr/kennzahlen": "نیروی انسانی، ترک خدمت، بیماری، اضافه‌کاری",
      "/hr/organigramm": "چه کسی به چه کسی گزارش می‌دهد",
      "/hr/kompetenzen": "ماتریس صلاحیت‌ها به تفکیک بخش",
      "/hr/schulungen": "آموزش‌های الزامی، موعدها، مستندها",
      "/hr/onboarding": "ورودی‌ها و آنچه برایشان باید انجام شود",
      "/hr/einarbeitung": "برنامه‌های آشناسازی و وضعیت آن‌ها",
      "/hr/dokumente": "ساختن فرم‌ها، چاپ و بازخوانی اسکن‌ها",
      "/hr/zeugnisse": "نوشتن و صادرکردن گواهی‌های کار",
    },
  },
  bewertung: {
    titel: "ارزیابی KPI",
    einleitung:
      "نظر دادن دربارهٔ معنای یک عدد و ثبت‌کردن آنچه از آن برمی‌آید. فهرست، همان " +
      "شاخص‌های دارای مقدار هدف است — همان فهرستی که داشبوردها را هم می‌سازد.",
    uebersichtFehler: (meldung: string) => `نمای کلی بارگذاری نشد: ${meldung}`,
    nurLesen:
      "شما می‌توانید ارزیابی‌ها را بخوانید، اما ننویسید. برای آن دسترسی «ویرایش» بر " +
      "تنظیمات لازم است.",
    stand: (offen: number, ueberfaellig: number, erledigt: number, kommentare: number) =>
      `${offen} باز، ${ueberfaellig} مورد با تأخیر · ${erledigt} انجام‌شده · ` +
      `${kommentare} نظر`,
    offenTitel: (anzahl: number) => `${anzahl} باز`,
    ueberfaelligTitel: (anzahl: number) => `${anzahl} با تأخیر`,
    massnahmen: "اقدام‌ها",
    wasZuTun: "چه باید کرد",
    zustaendig: "مسئول",
    faellig: "سررسید",
    anlegen: "بساز",
    ohneZustaendigen: "بدون مسئول",
    faelligAm: (datum: string) => `سررسید ${datum}`,
    erledigtAm: (datum: string) => `انجام‌شده ${datum}`,
    massnahmeLoeschen: "حذف اقدام",
    keineMassnahme: "هنوز اقدامی برای این شاخص نیست.",
    kommentare: "نظرها",
    kommentarPlatzhalter: "این عدد چه می‌گوید؟",
    kommentarLoeschen: "حذف نظر",
    keinKommentar: "هنوز چیزی دربارهٔ این شاخص گفته نشده است.",
    status: {
      offen: "باز",
      laeuft: "در جریان",
      erledigt: "انجام‌شده",
      verworfen: "کنار گذاشته",
    },
    bereiche: {
      vertrieb: "فروش",
      einkauf: "خرید",
      produktion: "تولید",
      qualitaet: "کیفیت",
      finanzen: "مالی",
      personal: "کارکنان",
    },
  },
  erklaerung: {
    hinweis: "توضیح",
    frage: (titel: string) => `«${titel}» چگونه محاسبه می‌شود؟`,
    knopf: "روش محاسبه",
    untertitel: "چگونه محاسبه می‌شود",
    ganzeSeite: "صفحهٔ کامل راهنما",
  },
};
