import type { Texte } from "@/texte/de";

/**
 * Die polnischen Texte der Oberfläche. Maschinell übersetzt — vor dem
 * Ausrollen sollte jemand darüberlesen, der die Sprache spricht.
 */
export const pl: Texte = {
  kopf: {
    benutzermenue: "Menu użytkownika",
    angemeldetAls: "Zalogowano jako",
    uebersicht: "Do przeglądu",
    hilfe: "Pomoc",
    einstellungen: "Ustawienia",
    abmelden: "Wyloguj się",
    sprache: "Język",
    erscheinungsbild: "Wygląd",
    hell: "Jasny",
    dunkel: "Ciemny",
    system: "Jak w systemie",
    meldungenLeer: "App Feedback — nic nowego",
    meldungen: (anzahl: number) => `App Feedback — ${anzahl} jeszcze nieprzejrzanych`,
    massnahmenLeer: "Działania — brak otwartych",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Działania — ${offen} otwartych, w tym ${ueberfaellig} po terminie`
        : `Działania — ${offen} otwartych`,
    navigation: "Nawigacja",
    einklappen: "Zwiń pasek boczny",
    ausklappen: "Rozwiń pasek boczny",
    navigationOeffnen: "Otwórz nawigację",
    navigationSchliessen: "Zamknij nawigację",
    unterseitenZeigen: (name: string) => `${name}: pokaż podstrony`,
    unterseitenVerbergen: (name: string) => `${name}: ukryj podstrony`,
    werkzeuge: "Filtry i akcje",
    werkzeugeEinklappen: "Zwiń pasek filtrów",
    werkzeugeAusklappen: "Rozwiń pasek filtrów",
    werkzeugeOeffnen: "Otwórz filtry",
    werkzeugeSchliessen: "Zamknij filtry",
    kategorien: {
      navigation: "Nawigacja",
      ansicht: "Widok",
      filter: "Filtry",
      zeitraum: "Okres",
      aktionen: "Akcje",
    },
  },
  pfad: {
    aria: "Ścieżka",
    start: "Start",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "Dostawy",
      "/atr/teilekatalog": "Katalog części",
      "/einstellungen": "Ustawienia",
      "/fair": "FAIR",
      "/hilfe": "Pomoc",
      "/hr": "HR",
      "/hr/dokumente": "Obieg dokumentów",
      "/hr/einarbeitung": "Wdrożenie",
      "/hr/kennzahlen": "Wskaźniki",
      "/hr/kompetenzen": "Kompetencje",
      "/hr/onboarding": "Onboarding",
      "/hr/organigramm": "Schemat organizacyjny",
      "/hr/schulungen": "Szkolenia",
      "/hr/schulungen/matrix": "Macierz",
      "/hr/schulungen/offen": "Zaległe",
      "/hr/zeugnisse": "Świadectwa",
      "/kpi": "Wskaźniki",
      "/kpi/bewertung": "Ocena KPI i działania",
      "/kpi/einkauf": "Zakupy",
      "/kpi/finanzen": "Finanse",
      "/kpi/produktion": "Produkcja",
      "/kpi/qualitaet": "Jakość",
      "/kpi/vertrieb": "Sprzedaż",
      "/newsletter": "Newsletter",
      "/newsletter/redaktion": "Redakcja",
      "/platform/feedback": "App Feedback",
      "/produktion": "Produkcja",
      "/qualitaet": "Jakość",
      "/sensoren": "Czujniki",
      "/signage": "Digital Signage",
      "/signage/devices": "Urządzenia",
      "/signage/media": "Media",
      "/signage/pair": "Parowanie",
      "/signage/playlists": "Playlisty",
      "/signage/schedules": "Harmonogramy",
      "/uploads": "Wczytywanie",
    },
  },
  start: {
    titel: "Aplikacje",
    verweigert: (name: string) => `Nie masz uprawnień do „${name}”.`,
    keineApp:
      "Do Twojego konta nie przypisano jeszcze żadnej aplikacji. Zwróć się do administracji platformy.",
  },
  anmeldung: {
    benutzer: "Użytkownik",
    lokalWechseln: "Zaloguj lokalnie",
    adWechseln: "Zaloguj kontem AD",
    titel: "Platforma ACM",
    aufforderung: "Zaloguj się swoim kontem.",
    email: "E-mail",
    passwort: "Hasło",
    knopf: "Zaloguj się",
    laeuft: "Logowanie …",
  },
  allgemein: {
    laedt: "Wczytywanie …",
    speichern: "Zapisz",
    abbrechen: "Anuluj",
    loeschen: "Usuń",
    stueck: "szt.",
    loeschenTitel: "Potwierdź usunięcie",
    loeschenFrage: (was: string) => `„${was}” zostanie trwale usunięte.`,
    loeschenKnopf: (was: string) => `Usuń ${was}`,
  },
  zeitraum: {
    aria: "Okres",
    monat: "Ten miesiąc",
    quartal: "Ten kwartał",
    jahr: "Ten rok",
    alles: "Wszystko",
    frei: "Wybierz okres",
    von: "od",
    bis: "do",
    vonAria: "Okres od",
    bisAria: "Okres do",
    verdreht: "Koniec wypada przed początkiem.",
  },
  vergleich: {
    zu: (was: string) => `w porównaniu z: ${was}`,
    quartal: (q: number) => `${q}. kwartał`,
    jahr: (j: number) => `rok ${j}`,
    keinWert: "Brak wartości porównawczej: brak danych w okresie porównania lub wartość wynosiła zero.",
    gestiegen: "wzrost",
    gesunken: "spadek",
    unveraendert: "bez zmian",
  },
  diagramm: {
    art: "Rodzaj wykresu",
    balken: "Słupki",
    flaeche: "Obszar",
  },
  tabelle: {
    suche: "Szukaj",
    sucheAria: "Przeszukaj tabelę",
    sucheLeeren: "Wyczyść wyszukiwanie",
    keineTreffer: "Brak wyników dla tego wyszukiwania.",
    leer: "Brak wpisów.",
    bereich: (von: number, bis: number, gesamt: number) => `${von}–${bis} z ${gesamt}`,
    seite: (seite: number, seiten: number) => `Strona ${seite} z ${seiten}`,
    zurueck: "Poprzednia strona",
    weiter: "Następna strona",
    sortieren: (spalte: string) => `Sortuj według „${spalte}”`,
    seitengroesse: "Wierszy tabeli na stronę",
    seitengroesseText: "Dotyczy wszystkich tabel platformy i wszystkich osób.",
    gespeichert: "Zapisano rozmiar strony.",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Dane z ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Dane niekompletne — ${fehlend} ${anzahl === 1 ? "nie został wczytany" : "nie zostały wczytane"}`,
    heute: "dziś",
    gestern: "wczoraj",
    vorTagen: (tage: number) => `${tage} dni temu`,
    nie: "nigdy",
    arten: {
      umsatz: "Obrót",
      auftraege: "Zamówienia",
      angebote: "Oferty",
      interessenten: "Potencjalni klienci",
      kontakte: "Kontakty",
      liefertreue: "Terminowość dostaw",
      lagerbewegungen: "Ruchy magazynowe",
      materialpreise: "Ceny materiałów",
      lagerpreise: "Ceny magazynowe",
      auftragspositionen: "Pozycje zamówień",
      lieferscheine: "Dowody dostawy",
      pruefungen: "Kontrole",
      acht_d: "Raporty 8D",
      wareneingaenge: "Przyjęcia towaru",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `Nie udało się wczytać wskaźników: ${meldung}`,
    keineDatenTitel: "Brak danych za ten okres",
    keineDatenVor: "Wczytaj eksporty ERP w ",
    keineDatenNach: " albo wybierz szerszy okres.",
    keineWerte: "brak wartości w okresie",
    laedt: "wczytywanie …",
    jeTag: "dziennie",
    jeWoche: "tygodniowo",
    jeMonat: "miesięcznie",
  },
  vertrieb: {
    umsatz: "Obrót",
    umsatzHinweis: "Faktury pomniejszone o korekty",
    auftragswert: "Śr. wartość zamówienia",
    ueberNull: "Zamówienia powyżej 0 €",
    auftraege: "Zamówienia łącznie",
    verlauf: "Obrót w czasie",
    verlaufHinweis: (takt: string) => `${takt}, po odliczeniu korekt`,
    kundenanteil: "Udział klientów w obrocie",
    kunde: "Klient",
    anteil: "Udział",
    uebrige: "Pozostali",
    jeErfasser: "Zamówienia wg handlowca",
    erfasser: "Handlowiec",
    anzahl: "Zamówienia",
    summe: "Suma",
    einzelauftraege: "Pojedyncze zamówienia",
    einzelauftraegeHinweis: "Zamówienia powyżej 0 € w okresie — te same, które liczy „Zamówienia łącznie”",
    auftragsNr: "Nr zamówienia",
    datum: "Data",
    gesamt: "Razem",
    kundenanteilAuftraege: "Udział klientów w zamówieniach",
    kundenanteilAuftraegeHinweis: "Wartość zamówień wg klienta",
    kundenanteilRechnungen: "Udział klientów w fakturach",
    kundenanteilRechnungenHinweis: "Faktury pomniejszone o korekty wg klienta",
    restkunden: (anzahl: number) => `Pozostali klienci (${anzahl})`,
    rest: "Reszta",
    weitereKunden: (anzahl: number) => `Pokaż ${anzahl} więcej`,
    nurTop3: "Tylko top 3",
    umsatzIn: (zeitraum: string) => `Obrót ${zeitraum}`,
  },
  aktivitaet: {
    titel: "Aktywność sprzedaży",
    jeWoche: (von: string, bis: string) => `wg tygodnia kalendarzowego, ${von} do ${bis}`,
    ladeFehler: (meldung: string) => `Nie udało się wczytać aktywności sprzedaży: ${meldung}`,
    leer: "Brak kontaktów, ofert i potencjalnych klientów w tym okresie.",
    kw: (woche: string) => `tydz. ${woche}`,
    ziel: (wert: string) => `Cel ${wert} / tydzień`,
    erstkontakte: "Pierwsze kontakty",
    erstkontakteHinweis: "zamknięte kontakty typu ERS",
    besuche: "Wizyty",
    besucheHinweis: "u klienta i online osobno",
    besucheOrt: "u klienta",
    besucheOnline: "online",
    interessenten: "Potencjalni klienci",
    interessentenHinweis: "nowo wprowadzeni, bez przypisanego handlowca",
    angebote: "Oferty",
    angeboteHinweis: "suma wystawionych ofert",
    auftragseingang: "Wpływ zamówień",
    auftragseingangHinweis: "storna odliczone",
  },
  einkauf: {
    einleitung: "Terminowość dostaw dostawców. Liczy się to, co wpłynęło w danym okresie.",
    keineDaten: "Brak pozycji dostaw za ten okres",
    ladeVor: "Wczytaj eksport terminowości dostaw w ",
    ladeNach: ".",
    otd: "Wskaźnik OTD",
    otdHinweis: (ziel: string) => `Cel ${ziel} · terminowo: opóźnienie ≤ 0`,
    puenktlich: "Pozycje terminowe",
    gesamt: "Pozycje łącznie",
    verzugSchnitt: "Śr. opóźnienie",
    verzugHinweis: "Bez pozycji bez wartości opóźnienia",
    verlauf: "Wskaźnik OTD w czasie",
    verlaufHinweis: "Przerwy to okresy bez pozycji dostaw.",
    verlaufTooltip: (positionen: string) => `OTD (${positionen} pozycji)`,
    ziellinie: "Cel",
    ladenhueter: "Zamówienie na magazyn — towar zalegający",
    kapital: (wert: string) => `Zamrożony kapitał: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Artykuły magazynowe bez ruchu od co najmniej ${tage} dni, najwyższa wartość na górze. ` +
      "Dniem odniesienia jest dziś — okres wybrany powyżej tu nie obowiązuje, bo stan magazynu " +
      "nie jest okresem.",
    artikel: "Artykuł",
    bezeichnung: "Nazwa",
    bestand: "Stan",
    liegtSeit: "Leży od",
    stueckpreis: "Cena jedn.",
    wert: "Wartość",
    positionen: "Pozycje dostaw",
    positionenHinweis:
      "Największe opóźnienie na górze, pozycje bez wartości opóźnienia na samej górze.",
    auftrag: "Zamówienie",
    lieferant: "Dostawca",
    zieltermin: "Termin planowany",
    geliefert: "Dostarczono",
    verzug: "Opóźnienie",
    menge: "Ilość",
  },
  produktion: {
    einleitung:
      "Zlecenia opóźnione. Zlecenie liczy się dopiero wtedy, gdy jego wynik jest przesądzony.",
    keineDaten: "Brak zlecenia z przesądzonym wynikiem w tym okresie",
    ladeVor: "Wczytaj pozycje zamówień i dowody dostawy w ",
    ladeNach:
      ". Potrzebne są oba pliki: jeden niesie termin planowany, drugi datę rzeczywistą.",
    quote: "Wskaźnik opóźnień",
    quoteHinweis: (ziel: string) => `Najwyżej ${ziel}`,
    inVerzug: "Zlecenia opóźnione",
    davonOffen: (anzahl: string) => `w tym ${anzahl} otwarte po terminie`,
    gesamt: "Zlecenia łącznie",
    gesamtHinweis: "bez otwartych, jeszcze niewymagalnych",
    verzugSchnitt: "Śr. opóźnienie",
    verzugHinweis: "terminowe zlecenia liczą się ujemnie",
    verlauf: "Wskaźnik opóźnień w czasie",
    verlaufHinweis: "Wg terminu planowanego. Przerwy to okresy bez liczonych zleceń.",
    verlaufTooltip: (auftraege: string) => `Opóźnienie (${auftraege} zleceń)`,
    ziellinie: "Cel",
    ansicht: "Widok zleceń",
    ansichtVerzug: "Zlecenia opóźnione",
    ansichtUeberfaellig: "Zaległe otwarte zlecenia",
    hinweisVerzug: "Dostarczone po terminie planowanym, największe opóźnienie na górze.",
    hinweisUeberfaellig: "Bez dowodu dostawy, termin minął — rośnie z każdym dniem.",
    leerVerzug: "Żadne zlecenie z tego okresu nie zostało dostarczone za późno.",
    leerUeberfaellig: "Żadne otwarte zlecenie z tego okresu nie jest po terminie.",
    auftrag: "Zlecenie",
    kunde: "Klient",
    zieltermin: "Termin planowany",
    geliefert: "Dostarczono",
    verzug: "Opóźnienie",
    tageUeberfaellig: "Dni po terminie",
  },
  finanzen: {
    einleitung: "Koszty materiałów i personelu w stosunku do obrotu z faktur.",
    keineDatenVor:
      "Potrzebne są trzy pliki: ruchy magazynowe dla zużycia, ceny materiałów (przyjęcie towaru) dla cen i " +
      "obrót jako wielkość odniesienia. Wszystkie trzy znajdziesz w ",
    keineDatenNach: ".",
    materialquote: "Udział kosztów materiałów",
    materialquoteHinweis: "Koszty materiałów / obrót",
    hoechstens: (ziel: string) => `Najwyżej ${ziel}`,
    materialkosten: "Koszty materiałów",
    umsatz: "Obrót",
    personalquote: "Udział kosztów personelu",
    brauchtZeitraum: "wymaga okresu",
    ohnePreis: "Artykuły bez ceny",
    ohnePreisHinweis: "zużyte, ale niewycenione",
    jeAbteilung: "Koszty personelu wg działu",
    abteilung: "Dział",
    personen: "Osoby",
    kosten: "Koszty",
    anteil: "Udział",
    verlauf: "Udział kosztów materiałów w czasie",
    verlaufHinweis: "Przerwy to okresy bez obrotu — bez wielkości odniesienia nie ma wskaźnika.",
    ziellinie: "Cel",
    verbrauch: "Zużycie materiału wg artykułu",
    verbrauchHinweis: "Najwyższe koszty na górze. Artykuły bez ceny stoją na końcu — nie wchodzą do wskaźnika.",
    artikel: "Artykuł",
    bezeichnung: "Nazwa",
    menge: "Zużycie",
    stueckpreis: "Cena jedn.",
    keinPreis: "brak ceny",
    ansicht: "Widok",
    ansichtMaterial: "Materiały",
    ansichtPersonal: "Personel",
    personalkosten: "Koszty personelu",
    personalquoteHinweis: "Koszty personelu / obrót",
    mitarbeiter: "Pracownicy",
    mitarbeiterHinweis: "z kosztami w okresie",
    personalVerlauf: "Udział kosztów personelu w czasie",
    quoteBeiKosten: (kosten: string) => `Wskaźnik przy kosztach ${kosten}`,
  },
  qualitaet: {
    einleitung: "Ustalenia z auditów, wskaźnik reklamacji i ilości kontrolowane.",
    auditart: "Rodzaj auditu:",
    reklamationsart: "Rodzaj reklamacji",
    keineArt: "Nie wybrano rodzaju auditu. Wybierz co najmniej jeden, inaczej nie ma czego liczyć.",
    keineDaten: "Brak ustaleń z auditów za ten okres",
    ladeVor: "Wczytaj eksport 8D w ",
    ladeNach: ".",
    behoerde: "Urząd",
    extern: "Zewnętrzny",
    intern: "Wewnętrzny",
    kunde: "Klient",
    level1: "Ustalenia auditu poziom 1",
    level2: "Ustalenia auditu poziom 2",
    ohneLevel: "Bez rozpoznanego poziomu",
    ohneLevelHinweis: "nie liczy się w żadnym kafelku",
    hoechstens: (ziel: number) => `Najwyżej ${ziel}`,
    auditVerlauf: "Ustalenia auditów w czasie",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `Udział ilości bez zastrzeżeń. Odniesienie: ${bezug}.`,
    fehlerquote: (quote: string) => `Wskaźnik błędów: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Wskaźnik błędów: ${quote} · cel ${ziel}`,
    reklamiert: "Ilość reklamowana",
    bezugsmenge: "Ilość odniesienia",
    bezugsmengeNull: "bez niej nie ma wskaźnika",
    mehrAlsBezogen:
      "Zareklamowano więcej, niż wynosi ilość odniesienia. Rachunek tego nie rozwiąże: " +
      "licznik i mianownik pochodzą z różnych plików, każdy z własnym polem daty. Sprawdź, " +
      "czy plik odniesienia jest za ten okres wczytany w całości.",
    reklKunde: "Klient",
    reklIntern: "wewnętrznie",
    reklLieferant: "Dostawcy materiałów",
    reklWerkbank: "Kooperanci",
    bezugKunde: "ilość dostarczona",
    bezugIntern: "ilość dostarczona",
    bezugLieferant: "przyjęcie towaru bez usług",
    bezugWerkbank: "przyjęcie towaru z grup towarowych DIENST i SERVIC",
    mengeGesamt: "ilość zgłoszona",
    mengeAkzeptiert: "ilość przyjęta",
    onQualityBezug: (menge: string) => `On Quality (odniesienie ${menge})`,
    ziellinie: "Cel",
    geprueft: "Skontrolowane wyroby",
    geprueftHinweis: "Ilość na dzień kontrolera. Każda wielkość dzielona przez dni, w których ją kontrolowano; razem przez wszystkie.",
    gross: "Wyroby duże",
    klein: "Wyroby małe",
    mindestens: (ziel: number) => `Co najmniej ${ziel} na dzień i kontrolera`,
    buchungen: "Zapisy kontroli jakości",
    buchungenHinweis: "Odznaczony zapis zostaje, ale nie liczy się w żadnym kafelku.",
    zaehltMit: "Liczy się",
    datum: "Data",
    pruefer: "Kontroler",
    produkt: "Wyrób",
    groesse: "Wielkość",
    menge: "Ilość",
    ausschuss: "Braki",
    mitzaehlen: (datum: string) => `Licz zapis z ${datum}`,
    klasseGross: "duży",
    klasseKlein: "mały",
    diagnose: "Ustalenia bez rozpoznanego poziomu",
    diagnoseHinweis:
      "Poziom stoi w pliku źródłowym w polu tekstowym. Jeśli nie ma tam ani „Major … Level 1”, " +
      "ani „Minor … Level 2”, ustalenie nie liczy się nigdzie. Ta lista pokazuje, gdzie poprawić.",
    bericht: "Raport",
    art: "Rodzaj",
    adresse: "Adres",
    bezeichnung: "Nazwa",
    ansicht: "Widok",
    ansichtAudits: "Audity",
    ansichtReklamationen: "Reklamacje",
    ansichtPruefung: "Kontrola jakości",
    artikelart: "Rodzaj artykułu",
    artikelFertig: "Wyroby gotowe",
    artikelHalbfertig: "Półprodukty",
    artikelAlle: "Wszystkie artykuły",
    gesamt: "Razem",
    pruefVerlauf: (klasse: string) => `${klasse} w czasie`,
    personentage: (anzahl: string) => `${anzahl} dni kontrolerów`,
    findings: "Przegląd ustaleń",
    nr: "Nr",
    kategorie: "Kategoria",
    level: "Poziom",
    aussteller: "Wystawca",
    quelle: "Źródło",
    status: "Status",
    reklListe: (art: string) => `Reklamacje · ${art}`,
    akzMenge: "Przyj. ilość",
    artikel: "Artykuł",
  },
  personal: {
    einleitung:
      "Z synchronizacji z Personio. Norma dzienna pochodzi z zapisanego modelu czasu pracy " +
      "danej osoby, a nie z ryczałtowego ośmiogodzinnego dnia.",
    uebersicht: "Przegląd",
    keinAbgleich: "Synchronizacja jeszcze nie przebiegła. Uruchamia się sama w nocy o 02:15.",
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} osób, ${anwesenheiten} obecności, ${abwesenheiten} nieobecności`,
    abgleichLaeuft: "trwa …",
    abgleichen: "Synchronizuj teraz",
    keineDaten: "Brak obecności za ten okres",
    keineDatenHinweis:
      "Albo synchronizacja z Personio jeszcze nie przebiegła, albo okres wypada przed " +
      "początkiem rejestracji.",
    ueberstunden: "Wskaźnik nadgodzin",
    stundenVon: (teil: string, ganz: string) => `${teil} z ${ganz} godz.`,
    krankheit: "Wskaźnik chorobowy",
    krankheitsartenFehlen: "Nie wskazano rodzajów chorobowego",
    fluktuation: "Fluktuacja",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} odejść, śr. ${schnitt} zatrudnionych`,
    personen: "Zarejestrowane osoby",
    personenHinweis: "z obecnością w okresie",
    krankheitHinweisVor:
      "Wskaźnik chorobowy pozostaje pusty, dopóki nie wskazano, które rodzaje nieobecności " +
      "w Personio liczą się jako choroba. Wpisuje się je w ",
    krankheitHinweisNach: ".",
    verlauf: "Przebieg",
    reiheUeberstunden: "Nadgodziny",
    reiheKrankheit: "Choroba",
    umsatzJeKopf: "Obrót / pracownik produkcji",
    umsatzJeKopfHinweis: (auftraege: string, koepfe: string) => `${auftraege} zamówień ÷ ${koepfe} osób`,
    produktionFehlt: "nie ustawiono działów produkcji",
    abgleichStand: (datum: string, alter: string) => `Synchronizacja Personio ${datum} (${alter})`,
    abgleichFehler: "z błędami",
    reiheUmsatzJeKopf: "Obrót na pracownika produkcji",
    ziel: (wert: string) => `Cel ${wert}`,
  },
  melden: {
    knopf: "Zgłoś App Feedback",
    titel: "Zgłoś App Feedback",
    frage: "Co na tej stronie się nie zgadza? Zrzut strony pójdzie razem.",
    abbrechen: "Anuluj",
    senden: "Wyślij",
    sendet: "Wysyłanie …",
    beispiel: "Na przykład: kafelek pokazuje pustą wartość, choć dane są.",
    beschreibung: "Opis",
    aufnahme: "Zrzut strony",
    gehtMit: "Ten zrzut pójdzie razem.",
    nimmtAuf: "Trwa zrzut strony …",
    misslungen: "Nie udało się zrobić zrzutu strony — feedback pójdzie bez obrazu.",
    dankeMitBild: "Dziękujemy — feedback dotarł.",
    dankeOhneBild: "Dziękujemy — feedback dotarł, bez zrzutu strony.",
  },
  belegschaft: {
    titel: "Załoga",
    hinweis:
      "Stan na dziś. Rozkłady pokazują aktualne dane podstawowe, a nie te sprzed lat — " +
      "Personio nie dostarcza historii. To, że „Zatrudnieni” i wskaźnik kompetencji mają różne " +
      "mianowniki, jest zamierzone: jedna liczba idzie za statusem w Personio, druga za datą " +
      "przyjęcia i odejścia. Obie drogi pochodzą ze starego projektu.",
    ladeFehler: (meldung: string) => `Nie udało się wczytać załogi: ${meldung}`,
    beschaeftigte: "Zatrudnieni",
    beschaeftigteHinweis: "wg statusu „aktywny” w Personio",
    neuImQuartal: "Nowi w kwartale",
    bestand: "Stan",
    kompetenzen: "Kompetencje uzupełnione",
    felderFehlen: "Nie wskazano pól — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} z ${aktive} wg daty przyjęcia i odejścia`,
    geschlecht: "Płeć",
    beschaeftigungsart: "Rodzaj zatrudnienia",
    abteilungen: "Działy",
    maennlich: "mężczyźni",
    weiblich: "kobiety",
    divers: "inna",
    unbekannt: "nieznana",
    vollzeit: "Pełny etat",
    teilzeit: "Niepełny etat",
    geringfuegig: "dorywczo",
    extern: "zewnętrzni",
  },
  mitarbeiter: {
    titel: "Pracownicy",
    person: "Osoba",
    abteilung: "Dział",
    istStunden: "Godz. rzecz.",
    ueberstunden: "Nadgodziny",
    quote: "NG %",
    auswahl: "Wybór",
    mitUeberstunden: "Z nadgodzinami",
    aktive: "Aktywni",
    alle: "Wszyscy",
    name: "Imię i nazwisko",
    position: "Stanowisko",
    status: "Status",
    wochenstunden: "Godz./tydz.",
    leer: "Nikt nie pasuje do tego wyboru.",
    statusWert: { active: "aktywny", inactive: "nieaktywny", onboarding: "wdrażanie", leave: "nieobecny" },
  },
  wochenbericht: {
    titel: "Raport tygodniowy",
    ladeFehler: (meldung: string) => `Nie udało się wczytać raportu tygodniowego: ${meldung}`,
    kalenderwoche: "Tydzień kalendarzowy",
    kw: (woche: string, jahr: string) => `tydz. ${woche} / ${jahr}`,
    keineDaten: "Brak obecności w tym tygodniu.",
    saldo: "Saldo nadgodzin",
    saldoHinweis: (personen: string) =>
      `Czas rzeczywisty minus norma efektywna, dla wszystkich ${personen} osób`,
    ueberSoll: "Powyżej normy",
    ueberSollHinweis: (gesamt: string) => `z ${gesamt} osób z rejestracją czasu`,
    krankheit: "Choroba",
    tage: "Dni",
    stunden: "Godz.",
    krankheitHinweis: "rozłożone na dni kalendarzowe nieobecności",
    ist: "Rzecz.",
    soll: "Norma",
    saldoSpalte: "Saldo",
    fussnote:
      "Norma to efektywna norma tygodniowa: urlop i choroba są odliczone, kto jest nieobecny " +
      "nieusprawiedliwiony, wychodzi na minus. W bieżącym tygodniu norma liczy się tylko do " +
      "ostatniego dnia z rejestracją.",
    diagrammUeberstunden: "Nadgodziny na osobę",
    diagrammKrankheit: "Choroba na osobę",
    spitzeHinweis: "pięć najwyższych wartości tygodnia",
    keineWerte: "Brak wartości w tym tygodniu",
    pdf: "Eksportuj jako PDF",
    pdfLaeuft: "Tworzenie PDF …",
    seite: (seite: number, gesamt: number) => `Strona ${seite} z ${gesamt}`,
    erstellt: (zeitpunkt: string) => `Utworzono ${zeitpunkt}`,
    einheit: "Jednostka choroby",
  },
  titel: {
    /** Detailseiten und Seiten, deren Tab-Titel ausführlicher heißt als die
     *  Krume im Pfad. Alles andere holt seinen Titel von dort. */
    schulung: "Szkolenie",
    zeugnis: "Świadectwo",
    qualifikationsmatrix: "Macierz kwalifikacji",
    maschine: "Maszyna",
    audit: "Audit",
    zeichnung: "Rysunek",
    lieferung: "Dostawa",
    offeneSchulungen: "Zaległe szkolenia",
    schulungsmatrix: "Macierz szkoleń",
    atrLieferungen: "Dostawy ATR",
    atrTeilekatalog: "Katalog części ATR",
    kpiBewertung: "Ocena KPI i działania",
    anmelden: "Logowanie",
  },
  uploads: {
    einleitung:
      "Wczytywanie eksportów ERP. Ponowne wczytanie tego samego pliku jest bezpieczne: " +
      "istniejące wiersze są aktualizowane, a nie zakładane po raz drugi.",
    dateiWaehlen: "Wybierz plik",
    verarbeitet: "przetwarzanie …",
    uebersprungen: (datei: string) => `Pominięte wiersze z „${datei}”`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `Przyjęto ${gesamt} wiersz(y), pominięto ${fehler}. Pozostałe wiersze są zapisane.`,
    zeile: "Wiersz",
    spalte: "Kolumna",
    grund: "Powód",
    zuletzt: "Ostatnio wczytane",
    datei: "Plik",
    art: "Rodzaj",
    zeilen: "Wiersze",
    uebersprungenSpalte: "Pominięte",
    status: "Status",
    zeitpunkt: "Moment",
    nochNichts: "Jeszcze nic nie wczytano.",
    keineZeile: (datei: string) => `„${datei}” nie zawierał żadnego poprawnego wiersza.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `„${datei}” przyjęty, pominięto ${fehler} wiersz(y).`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `„${datei}” przyjęty: ${neu} nowych, ${aktualisiert} zaktualizowanych.`,
    fehlgeschlagenMeldung: (meldung: string) => `Wczytywanie nie powiodło się: ${meldung}`,
    vollstaendig: "w całości",
    teilweise: "częściowo",
    fehlgeschlagen: "nie powiodło się",
    arten: {
      umsatz: "Obrót (faktury i korekty)",
      umsatzText: "Zasila kafelek Obrót i przebieg obrotu. Korekty stoją w pliku ze znakiem ujemnym.",
      auftraege: "Wpływ zamówień",
      auftraegeText: "Zasila śr. wartość zamówienia, zamówienia łącznie i zestawienie wg handlowca.",
      auftragspositionen: "Pozycje zamówień",
      auftragspositionenText:
        "Niesie termin planowany każdej pozycji. Razem z dowodami dostawy daje opóźnienie.",
      lieferscheine: "Dowody dostawy",
      lieferscheineText: "Niesie rzeczywistą datę dostawy. Plik Excel, jeden wiersz na pozycję dowodu.",
      wareneingaenge: "Przyjęcia towaru",
      wareneingaengeText:
        "Wielkość odniesienia wskaźnika błędów po stronie zakupów. Grupa towarowa oddziela dostawców materiałów od kooperantów.",
      acht_d: "Raporty 8D",
      acht_dText:
        "Ustalenia auditów i reklamacje w jednym pliku. Poziom ustalenia stoi w polu tekstowym i jest wyprowadzany przy wczytywaniu.",
      lagerbewegungen: "Ruchy magazynowe",
      lagerbewegungenText:
        "Zużycie wg artykułu dla udziału kosztów materiałów. Zastępuje wszystkie wiersze z zakresu dat pliku.",
      materialpreise: "Ceny materiałów (przyjęcie towaru)",
      materialpreiseText:
        "Ceny dla udziału kosztów materiałów: dla każdego artykułu obowiązuje najnowsze przyjęcie. Aktualizuje te same pozycje, dodaje nowe, niczego nie usuwa.",
      lagerpreise: "Ceny artykułów magazynowych",
      lagerpreiseText:
        "Dane podstawowe do wyceny magazynu. Zastępuje całą listę cen, nie tylko zawarte w niej artykuły.",
      pruefungen: "Kontrola jakości",
      pruefungenText:
        "Zapisy kontroli. Zastępuje wszystkie wiersze z zakresu dat pliku — ręcznie odznaczone zapisy z tego zakresu liczą się potem znowu.",
      liefertreue: "Terminowość dostaw (zakupy)",
      liefertreueText:
        "Zasila wskaźnik OTD w zakupach. Jeden wiersz na pozycję dostawy; rzeczywista data dostawy wyznacza okres.",
      kontakte: "Kontakty (sprzedaż)",
      kontakteText:
        "Pierwsze kontakty i wizyty w ujęciu tygodniowym. Zastępuje wszystkie wiersze z zakresu dat pliku — drugie wczytanie tego samego okresu niczego nie podwaja.",
      angebote: "Oferty",
      angeboteText:
        "Wolumen ofert w ujęciu tygodniowym i wg handlowca. Oferty bez wprowadzającego nie pojawią się w żadnym słupku.",
      interessenten: "Potencjalni klienci",
      interessentenText:
        "Dane podstawowe potencjalnych klientów. Ponownie zapisany rekord przechodzi ze swoją nową datą do innego tygodnia.",
    },
  },
  organigramm: {
    einleitung:
      "Z Personio. Kto nie ma tam wpisanego przełożonego, stoi na górze — u zarządu jest to " +
      "słuszne, w innym razie wskazuje na lukę w danych podstawowych.",
    suchfeld: "Osoba, stanowisko lub dział",
    suchePlatzhalter: "Nazwisko, stanowisko, dział",
    standort: "Lokalizacja",
    alleStandorte: "Wszystkie lokalizacje",
    personen: (anzahl: number) => `${anzahl} osób`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} bez przełożonego`,
    niemand: "Nikogo nie znaleziono",
    niemandText:
      "Inne wyszukiwanie, inna lokalizacja — albo synchronizacja z Personio jeszcze nie przebiegła.",
    aufklappen: (name: string) => `Rozwiń ${name}`,
    zuklappen: (name: string) => `Zwiń ${name}`,
    direkt: (anzahl: number) => `${anzahl} bezpośrednio`,
    treffer: (anzahl: number) => ` · ${anzahl} trafień`,
    kontext: "W ramce: trafienia. Blade: przełożeni jako kontekst.",
  },
  offeneSchulungen: {
    einleitung:
      "Kto czego jeszcze potrzebuje. Tylko szkolenia aktywne; wycofane już się tu nie pojawiają.",
    zumKatalog: "Do katalogu",
    allesOffene: "Wszystko zaległe",
    nieAbsolviert: "Nigdy nieodbyte",
    ueberfaellig: "Po terminie",
    wirdFaellig: "Zbliża się termin",
    suchen: "Szukaj osoby lub szkolenia",
    suchenAria: "Szukaj",
    nichtsOffen: "Nic zaległego",
    nichtsOffenText: "Wszystkie aktywne szkolenia są w cyklu — albo nic jeszcze nie wczytano.",
    eintraege: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "wpis" : "wpisów"}.`,
    person: "Osoba",
    schulung: "Szkolenie",
    bereich: "Obszar",
    zuletzt: "Ostatnio",
    faellig: "Termin",
    stand: "Stan",
    nie: "nigdy nieodbyte",
    imTurnus: "w cyklu",
  },
  schulungsmatrix: {
    einleitung:
      "Wszystkie osoby wobec wszystkich szkoleń — przegląd na tablicę i na audit. " +
      "Kto nie ma jeszcze żadnego udziału, stoi tam z pustym wierszem; właśnie to jest luka, " +
      "której się szuka.",
    wasOffenIst: "Co jest zaległe",
    katalog: "Katalog",
    suchfeld: "Osoba lub dział",
    suchePlatzhalter: "Nazwisko, dział, numer kadrowy",
    bereich: "Obszar",
    alleBereiche: "Wszystkie obszary",
    nurLuecken: "Tylko osoby z lukami",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} z ${gesamt} osób · ${schulungen} szkoleń`,
    niemand: "Żadna osoba nie pasuje",
    niemandText: "Inne wyszukiwanie lub inny obszar — albo naprawdę nikt nie zalega.",
    person: "Osoba",
    nichtZugewiesen: (person: string, schulung: string) =>
      `${person} · ${schulung}: nie przypisano`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (termin ${datum})`,
    offen: "zaległe",
    personio: "Personio",
    externGepflegt: "prowadzone poza Personio",
    ohneTreffer: "bez dopasowania w Personio",
  },
  schulungen: {
    einleitung:
      "Katalog, jego cykl i kto go spełnia. Terminy są liczone z ostatniej daty i cyklu, " +
      "a nie zapisywane.",
    dokumentenlauf: "Obieg dokumentów",
    bereich: "Obszar",
    neueSchulung: "Nowe szkolenie",
    beispiel: "np. instruktaż przeciwpożarowy",
    anlegen: "Załóż",
    wirdGelesen: "Wczytywanie …",
    uebersichtEinlesen: "Wczytaj zestawienie",
    einlesenAria: "Wczytaj zestawienie szkoleń",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} szkoleń (${neu} nowych), ${teilnahmen} udziałów, w tym ${zugeordnet} przypisanych osobie w Personio.`,
    ohneTreffer: "Bez dopasowania w Personio: ",
    ohneTrefferNach: ". Te wiersze wchodzą mimo to, z numerem kadrowym i nazwiskiem.",
    wirdUebernommen: "Przejmowanie …",
    uebernehmen: "Przejmij",
    abbrechen: "Anuluj",
    keineSchulung: "Jeszcze żadnego szkolenia",
    keineSchulungText: "Załóż jedno albo wczytaj zestawienie szkoleń.",
    schulung: "Szkolenie",
    turnus: "Cykl",
    frist: "Termin (dni)",
    verantwortlich: "Odpowiedzialny",
    offen: "Zaległe",
    aktiv: "Aktywne",
    nichtBerechenbar: "(nie do wyliczenia)",
    zahlGroesserNull: "Podaj liczbę większą niż 0.",
    nieKurz: (anzahl: number) => `${anzahl} nigdy`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} po terminie`,
    baldKurz: (anzahl: number) => `${anzahl} wkrótce`,
    aktivSchalter: (name: string) => `${name} aktywne`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} znaczy: dla tej osoby nie ma w historii żadnej daty. ${bald} znaczy: w ciągu najbliższych dwóch miesięcy. Stan z ${datum}.`,
  },
  schulungenReg: {
    tabBearbeiten: "Edytuj szkolenia",
    tabZuweisen: "Przypisz szkolenie",
    tabStand: "Stan pracowników",
    anforderungsmatrix: "Macierz wymagań",
    ebene: "Poziom",
    matrixLeer: "Brak danych do macierzy.",
    einzelTitel: "Przypisz pojedyncze szkolenie",
    einzelHinweis: "Uzupełnia macierz wymagań działającą na poziomie działu — dla osób.",
    mitarbeiterWaehlen: "Wybierz pracownika",
    schulungWaehlen: "Wybierz szkolenie",
    zuweisenAktion: "Przypisz",
    zugewiesen: "Szkolenie przypisane.",
    schonZugewiesen: "To szkolenie jest już przypisane osobie.",
    sammelTitel: "Oznacz jako przeprowadzone (zbiorczo)",
    sammelHinweis: "Jedno szkolenie, jedna data, wielu uczestników. Ukończone wpisy zachowują datę, nowsza ją zastępuje.",
    durchgefuehrtAm: "Przeprowadzono",
    teilnehmerSuche: "Szukaj uczestników",
    standort: "Lokalizacja",
    offeneTitel: "Otwarte szkolenia",
    abteilung: "Dział",
    frist: "Termin",
    mitarbeiterTitel: "Przegląd pracowników",
    anzahl: "Liczba",
    naechste: "Następny termin",
    matrixTitel: "Macierz zbiorcza",
    abteilungenTitel: "Działy i przełożeni",
    vorgesetzter: "Odpowiedzialny przełożony",
    abteilungenHinweis: "Przełożony jest wyprowadzany z Personio; przy braku kolumna pozostaje pusta.",
    sammelAktion: (anzahl: number) => `Oznacz ${anzahl} jako przeprowadzone`,
    sammelErfolg: (eingetragen: number, unveraendert: number) =>
      `${eingetragen} zapisano${unveraendert ? `, ${unveraendert} bez zmian` : ""}.`,
    seit: (tage: number) => `${tage} dni temu`,
    in: (tage: number) => `za ${tage} dni`,
  },
  schulung: {
    gibtEsNicht: "Takiego szkolenia nie ma",
    gibtEsNichtText: "Prawdopodobnie zostało usunięte.",
    ohneTurnus: "bez cyklu",
    keineFaelligkeit: " — nie da się z tego wyliczyć terminu",
    zumKatalog: "Do katalogu",
    stammdaten: "Dane podstawowe",
    turnus: "Cykl",
    turnusBeispiel: "np. corocznie",
    turnusHinweis: "Sam tekst; liczba miesięcy pochodzi z wczytania.",
    turnusMonate: "Cykl w miesiącach",
    monateHinweis: "Puste znaczy: terminu nie da się wyliczyć.",
    verantwortlich: "Odpowiedzialny",
    beschreibung: "Opis",
    fuerWen: "Dla kogo jest obowiązkowe?",
    kuerzel: "Skrót działu",
    kuerzelHinweis: "Drobny schemat z pliku Excel (NÄH, CUT, WVK …).",
    personioAbteilung: "Dział w Personio",
    personioHinweis: "Zgrubny dział, tak jak prowadzi go Personio.",
    entfernen: (was: string) => `Usuń ${was}`,
    keine: "brak",
    ergaenzen: (was: string) => `Dodaj ${was}`,
    hinzufuegen: "Dodaj",
    teilnahmen: "Udziały",
    nochNiemand: "Jeszcze nikt — wczytaj zestawienie szkoleń albo wpisz kogoś.",
    person: "Osoba",
    abteilungKurz: "Dz.",
    erstschulung: "Pierwsze szkolenie",
    zuletzt: "Ostatnio",
    faellig: "Termin",
    stand: "Stan",
    keinTreffer: "Brak dopasowania w Personio — wiersz mimo to zostaje",
    nichtInPersonio: "nie ma w Personio",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "ten udział",
    personErgaenzen: "Dodaj osobę",
    nameForm: "Nazwisko, imię",
  },
  kompetenzen: {
    einleitung:
      "Czego wymaga stanowisko i na ile jest to spełnione — dla każdego obszaru jedna macierz. " +
      "Wczytane z pliku obszaru, potem prowadzone tutaj.",
    zumDashboard: "Do pulpitu kadrowego",
    bereich: "Obszar",
    wirdGelesen: "Wczytywanie …",
    einlesen: "Wczytaj plik obszaru",
    vorschauKopf: (datei: string, bereich: string) => `${datei} — tak wyglądałby potem ${bereich}:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} kwalifikacji, ${personen} osób, ${bewertungen} ocen.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `Znaleziono w Personio ${zugeordnet} z ${personen} osób`,
    platzhalter: (anzahl: number) =>
      `, ${anzahl} ${anzahl === 1 ? "kolumna zastępcza" : "kolumn zastępczych"}`,
    ohneZuordnung: (namen: string) => ` Bez przypisania: ${namen}.`,
    ersetztWarnung:
      "Objęte arkusze zostaną zastąpione w całości — prowadzone tutaj zmiany przy tym " +
      "przepadną.",
    wirdUebernommen: "Przejmowanie …",
    uebernehmen: "Przejmij",
    abbrechen: "Anuluj",
    keineMatrix: "Jeszcze żadnej macierzy",
    keineMatrixText: "Wczytaj plik obszaru — każdy arkusz w nim stanie się macierzą.",
    blatt: "Arkusz",
    titelSpalte: "Tytuł",
    stand: "Stan",
    eingelesen: "Wczytano",
    produktion: "Produkcja",
    verwaltung: "Administracja",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    bausteineTitel: "Bloki tekstowe",
    bausteineHinweis: "Jedno sformułowanie na obszar oceny i ocenę. Zapisywane są tylko zmiany; [NAME] i zaimki są zastępowane przy generowaniu.",
    speichern: "Zapisz",
    gespeichert: "Zapisano.",
    note1: "bardzo dobry",
    note2: "dobry",
    note3: "dostateczny",
    note4: "wystarczający",
    einleitung:
      "Z ocen i punktów powstaje język świadectw. Dane podstawowe są przepisywane przy " +
      "zakładaniu — wystawione świadectwo nie zmienia się już dlatego, że zmienia się Personio.",
    person: "Osoba",
    waehlen: "— wybierz —",
    art: "Rodzaj",
    anlegen: "Załóż",
    keines: "Jeszcze żadnego świadectwa",
    keinesText: "Wybierz osobę i rodzaj świadectwa — dane podstawowe przyjdą same.",
    zeitraum: "Okres",
    note: "Ocena",
    stand: "Stan",
    angelegt: "Założono",
    fertig: "gotowe",
    entwurf: "Szkic",
    qualifiziert: "Świadectwo kwalifikowane",
    einfach: "Świadectwo proste",
    zwischenzeugnis: "Świadectwo okresowe",
    ausbildungszeugnis: "Świadectwo z nauki zawodu",
    praktikumszeugnis: "Świadectwo z praktyki",
  },
  einarbeitung: {
    einleitung:
      "Czego musi nauczyć się nowa osoba i kto jej to pokaże. Formularz powstaje z treści " +
      "zapisanych dla jej działu.",
    bogenErzeugen: "Utwórz formularz",
    person: "Osoba",
    waehlen: "— wybierz —",
    wirdGebaut: "Tworzenie …",
    einarbeitungsplan: "Plan wdrożenia",
    keineInhalte: "Nie zapisano jeszcze żadnej treści — formularz byłby pusty.",
    abteilungVon: (abteilung: string) => `Dział ${abteilung}`,
    neuerInhalt: "Nowa treść",
    beispiel: "np. instruktaż BHP przy frezarce",
    anlegen: "Załóż",
    keinInhalt: "Jeszcze żadnej treści",
    keinInhaltText:
      "Ustal, czego musi nauczyć się nowa osoba — i dla których działów to obowiązuje.",
    inhalt: "Treść",
    ansprechpartner: "Osoba kontaktowa",
    bereich: "Obszar",
    fuerAbteilungen: "Dla których działów",
    abteilung: "Dział",
    bereichLeer: "Puste znaczy: wstawić dział z macierzy",
    entfernen: (was: string) => `Usuń ${was}`,
    abteilungHinzu: "+ Dział",
    abteilungFuer: (inhalt: string) => `Dział dla ${inhalt}`,
  },
  matrix: {
    bearbeiten: "Edytuj",
    bearbeitenFertig: "Gotowe",
    ohneKategorie: "Bez kategorii",
    gibtEsNicht: "Takiej macierzy nie ma",
    gibtEsNichtText: "Prawdopodobnie została zastąpiona.",
    blattStand: (blatt: string) => `Arkusz ${blatt}`,
    stand: (datum: string) => ` · stan ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} kwalifikacji, ${personen} osób`,
    zurUebersicht: "Do przeglądu",
    qualifikation: "Kwalifikacja",
    keineZeilen: "Ta macierz nie ma jeszcze żadnych wierszy.",
    stufenBedeuten: "Co znaczą stopnie",
    erfuellungsgradHinweis:
      "Druga liczba to stopień spełnienia w procentach. Komórka z wymaganiem i wynikiem " +
      "poniżej 100 % jest luką i stoi w kolorze ostrzegawczym.",
    ergaenzen: "Dodaj",
    neueQualifikation: "Nowa kwalifikacja",
    beispiel: "np. tokarka",
    kategorie: "Kategoria",
    ohne: "bez",
    zeile: "Wiersz",
    neuePerson: "Nowa osoba",
    namensform: "Imię Nazwisko",
    spalte: "Kolumna",
    anforderungslevel: "Poziom wymagania",
    erfuellungsgrad: "Stopień spełnienia w procentach",
    stufe0: "niewymagane",
    stufe1: "podstawy",
    stufe2: "pracuje pod nadzorem",
    stufe3: "pracuje samodzielnie",
    stufe4: "potrafi instruować i szkolić",
  },
  zeugnis: {
    gibtEsNicht: "Takiego świadectwa nie ma",
    gibtEsNichtText: "Prawdopodobnie zostało skasowane.",
    durchschnitt: (wert: string) => ` · średnia ${wert}`,
    zurUebersicht: "Do przeglądu",
    zeugnisVon: (name: string) => `Świadectwo ${name}`,
    stammdaten: "Dane podstawowe",
    stammdatenHinweis:
      "Przepisane przy zakładaniu. Zmiany tutaj dotyczą tylko tego świadectwa — Personio " +
      "zostaje nietknięte.",
    name: "Imię i nazwisko",
    personalnummer: "Numer kadrowy",
    abteilung: "Dział",
    taetigkeit: "Stanowisko",
    eintritt: "Przyjęcie",
    austritt: "Odejście",
    geburtsdatum: "Data urodzenia",
    ausstellungsdatum: "Data wystawienia",
    ohneNamen: "Bez nazwiska się nie da.",
    anrede: "Zwrot",
    frau: "Pani",
    herr: "Pan",
    anredeHinweis: "Steruje zwrotem i zaimkami w tekście.",
    art: "Rodzaj",
    anlass: "Powód",
    anlassBeispiel: "np. własne życzenie",
    fuehrungskraft: "Kadra kierownicza",
    fuehrungskraftHinweis: "Kadra kierownicza — włącza wymiar „Kierowanie”",
    bewertung: "Ocena",
    bewertungHinweis:
      "Oceny szkolne od 1 do 4. Ze średniej wynika formuła zadowolenia — nie odwrotnie.",
    fachwissen: "Wiedza fachowa",
    auffassungsgabe: "Zdolność pojmowania",
    arbeitsweise: "Sposób pracy",
    belastbarkeit: "Odporność na obciążenie",
    arbeitserfolg: "Wyniki pracy",
    sozialverhalten: "Zachowanie społeczne",
    fuehrung: "Kierowanie",
    aufgaben: "Zadania (w punktach)",
    aufgabenHinweis: "Jedno zadanie w wierszu — z tego powstaje wyliczenie w świadectwie.",
    kompetenzen: "Szczególne kompetencje",
    kompetenzenHinweis: "Wchodzi do oceny wyników.",
    erfolge: "Szczególne osiągnięcia",
    erfolgeHinweis: "Projekty, wyróżnienia, mierzalne wyniki.",
    text: "Tekst",
    baut: "Składa …",
    ausBausteinen: "Z modułów",
    formuliert: "Formułuje …",
    mitKi: "Z AI",
    textHinweis:
      "Moduły piszą bez sieci i bez AI. AI formułuje swobodniej — trafiają do niej tylko " +
      "zwrot, rola, dział, czas trwania, oceny i teksty powyżej. Nazwisko, data urodzenia i " +
      "numer kadrowy nie opuszczają serwera.",
    nochKeinText: "Jeszcze nie ma tekstu. Wystaw oceny i każ go ułożyć.",
    fertigSchalter: "Świadectwo gotowe",
    fertigHinweis: "Gotowe — już nie w opracowaniu",
    unterschriftenFehler: (meldung: string) =>
      `Nie udało się ustalić podpisów (${meldung}).`,
    darunterSteht: "Pod spodem stoi",
    fachlich: "Merytorycznie",
    personalwesen: "Kadry",
    niemandHinterlegt: "— nikogo nie wskazano —",
    unterschriftFehlt:
      "Brakuje podpisu. Wskaż go w Ustawieniach → Świadectwa albo uzupełnij przełożonego " +
      "w Personio.",
    ausPersonio: "z Personio",
    ausEinstellungen: "z ustawień",
    nichtHinterlegt: "nie wskazano",
    einleitung: "Wstęp",
    taetigkeitsbeschreibung: "Opis stanowiska",
    leistungsbeurteilung: "Ocena wyników",
    schlussformel: "Formuła końcowa",
    hinweisDeutsch: "Samo świadectwo jest pisane po niemiecku.",
  },
  dokumentenlauf: {
    erstelltAm: "Utworzono",
    uebergebenAm: "Przekazano",
    zurueckAm: "Zwrócono",
    geprueftAm: "Sprawdzono",
    aktionen: "Akcje",
    einleitung:
      "Arkusze z kodem QR: utworzyć, wydać, odebrać wypełnione, sprawdzić. Kod QR " +
      "przyporządkowuje skan z powrotem — niezależnie od tego, jak nazywa się plik.",
    formblatt: "Formularz",
    fuerWen: "Dla kogo",
    personWaehlen: "— wybierz osobę —",
    erzeugt: "Tworzenie …",
    blattErzeugen: "Utwórz arkusz",
    standFilter: "Stan:",
    alle: "Wszystkie",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} z ${gesamt}`,
    keinVorgang: "Żadnej sprawy",
    keinVorgangText:
      "Utwórz powyżej arkusz — dostanie kod QR i od tej chwili będzie śledzony.",
    person: "Osoba",
    kennung: "Identyfikator",
    stand: "Stan",
    vollstaendigSpalte: "Kompletny",
    blatt: "Arkusz",
    scan: "Skan",
    prueft: "Sprawdza …",
    scanFuer: (name: string) => `Wczytaj skan dla ${name}`,
    zu: "do",
    details: "Szczegóły",
    nochNichtGeprueft: "— jeszcze niesprawdzone",
    vollstaendig: "kompletny",
    unvollstaendig: "niekompletny",
    umkehren: "Odwróć ocenę — pomiar widzi tylko, czy w polu jest atrament",
    pruefung: "Sprawdzenie",
    qrGelesen: "— odczytano QR",
    keinQr: "— nie znaleziono QR, pól nie da się przyporządkować",
    nachweise: "Dowody",
    keineNachweise: "Jeszcze żadnych.",
    welcheZeile: "Do którego wiersza? (nieobowiązkowo)",
    laedt: "Wczytuje …",
    nachweis: "Dowód",
    nachweisHoch: "Wczytaj dowód",
    erstellt: "utworzony",
    uebergeben: "wydany",
    zurueck: "zwrócony",
    geprueft: "sprawdzony",
    einarbeitungsplan: "Plan wdrożenia",
    schulungsnachweis: "Dowód szkolenia",
  },
  onboarding: {
    aktive: "Aktywni",
    personenwahl: "Które osoby",
    eintritteTitel: "Nowo zatrudnieni",
    inhalteTitel: "Treści wdrożenia",
    matrixTitel: "Macierz wdrożenia",
    matrixHinweis: "Które treści są potrzebne w którym dziale. Zaznaczenie działa od razu.",
    matrixLeer: "Brak treści lub działów.",
    vorgaengeTitel: "Procesy wdrożenia i szkoleń",
    matrixZelle: (inhalt: string, abteilung: string) => `${inhalt} – ${abteilung}`,
    einleitung:
      "Kto jest nowy i jakich szkoleń wymaga dla niego macierz wymagań. Plan nie jest " +
      "zapisywany, tylko liczony — zmienia się macierz, zmienia się plan.",
    nichtsGefehlt: "Nic nie brakowało.",
    angelegt: (anzahl: number) =>
      `Założono ${anzahl} ${anzahl === 1 ? "szkolenie" : "szkoleń"}.`,
    neu90: "Nowi (ostatnie 90 dni)",
    alle: "Wszyscy",
    personen: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "osoba" : "osób"}`,
    keineEintritte: "Żadnych przyjęć",
    keineEintritteText: "Gdy tylko ktoś z datą przyjęcia przyjdzie z Personio, stanie tutaj.",
    person: "Osoba",
    abteilung: "Dział",
    position: "Stanowisko",
    eintritt: "Przyjęcie",
    uebergabe: "Przekazanie",
    nichtInPersonio: "nie ma w Personio",
    hierGesetzt: "Ustawione tutaj — nadpisuje Personio",
    ausPersonio: "Z Personio",
    vermerken: "Odnotuj",
    paketTitel: "Plan wdrożenia i zestawienie szkoleń jako jeden PDF",
    paket: "Pakiet",
    uebersichtTitel: "Tylko zestawienie szkoleń (formularz 71)",
    uebersicht: "Zestawienie",
    planZu: "Plan do",
    plan: "Plan",
    schulungsplan: "Plan szkoleń",
    fehlendeAnlegen: "Załóż brakujące",
    wirdGerechnet: "liczy się …",
    bruecke: "Stanowisko → skrót działu",
    brueckeHinweis:
      "Pomost między Personio a drobnym poziomem macierzy wymagań. Bez wpisu drobny poziom " +
      "nie działa dla tego stanowiska — plan powie to wtedy wyraźnie.",
    kuerzel: "Skrót",
    positionBeispiel: "np. frezer CNC",
    kuerzelBeispiel: "CNC",
    zuordnen: "Przyporządkuj",
    ohnePersonio: "Osoba bez Personio",
    ohnePersonioHinweis:
      "Dla przyjęć, których nie ma jeszcze w synchronizacji — albo które w ogóle tam nie należą.",
    name: "Imię i nazwisko",
    anlegen: "Załóż",
    kuerzelFehlt: (position: string) =>
      `Dla stanowiska ${position}nie wskazano skrótu działu. Drobny poziom macierzy wymagań ` +
      "dlatego nie działa dla tej osoby — możliwe, że brakuje szkoleń obowiązkowych.",
    matrixVerlangtNichts: "Macierz wymagań nie wymaga dla tego działu niczego.",
    schulung: "Szkolenie",
    bereich: "Obszar",
    turnus: "Cykl",
    pflichtUeber: "Obowiązek przez",
    stand: "Stan",
    ueberAbteilung: "Dział",
    ueberKuerzel: "Skrót",
    vorhanden: "jest",
    fehlt: "brak",
  },
  audit: {
    einleitung:
      "Audity od planowania do zamknięcia. Każda zmiana statusu stoi w historii — " +
      "zapisana przez bazę danych, nie przez maskę, i potem niezmienialna.",
    zuKennzahlen: "Do wskaźników",
    nummer: "Numer",
    nummerBeispiel: "A-2026-01",
    titel: "Tytuł",
    titelBeispiel: "EN 9100 audit systemu",
    art: "Rodzaj",
    intern: "wewnętrzny",
    extern: "zewnętrzny",
    phasenvorlage: "Szablon faz",
    ohne: "bez",
    anlegen: "Załóż",
    alle: "Wszystkie",
    neuesAudit: "Nowy audyt",
    geltungsbereich: "Zakres",
    kategorie: "Kategoria",
    leadAuditor: "Audytor wiodący",
    beginnGeplant: "Początek (planowany)",
    endeGeplant: "Koniec (planowany)",
    ohneVorlage: "Bez szablonu (fazy dodać później)",
    vorlageHinweis:
      "Fazy szablonu są kopiowane przy tworzeniu. Późniejsza zmiana szablonu nie zmienia tego " +
      "audytu.",
    kategoriePflicht: "Wybierz co najmniej jedną kategorię.",
    zeitraumFehler: "Koniec jest przed początkiem.",
    angelegt: "Audyt utworzony.",
    nummerVergeben: "Ten numer audytu już istnieje.",
    keinTreffer: "Żaden audyt nie pasuje do tego filtra.",
    keinAudit: "Jeszcze żadnego auditu",
    keinAuditText: "Załóż jeden — z szablonem faz przyniesie od razu swoją listę kontrolną.",
    laufen: (laufend: number, gesamt: number) => `${laufend} z ${gesamt} jeszcze trwa.`,
    status: "Status",
    fortschritt: "Postęp",
    naechsterTermin: "Najbliższy termin",
    ueberfaellig: (anzahl: number) => `${anzahl} po terminie`,
    geplant: "Zaplanowany",
    inVorbereitung: "W przygotowaniu",
    inDurchfuehrung: "W trakcie",
    berichtet: "Zaraportowany",
    massnahmenOffen: "Działania otwarte",
    abgeschlossen: "Zamknięty",
    verschoben: "Przełożony",
    abgesagt: "Odwołany",
    phaseOffen: "Otwarta",
    phaseInArbeit: "W toku",
    phaseErledigt: "Zrobiona",
    phaseNichtZutreffend: "Nie dotyczy",
    system: "System",
    prozess: "Proces",
    produkt: "Wyrób",
    lieferant: "Dostawca",
  },
  wartung: {
    einleitung:
      "Maszyny i ich powtarzające się zadania konserwacyjne. Dowód powstaje jako arkusz do " +
      "wywieszenia — na każde półrocze, z kolumną na każdy tydzień kalendarzowy.",
    zuKennzahlen: "Do wskaźników",
    neueMaschine: "Nowa maszyna",
    beispiel: "np. frezarka 3",
    anlegen: "Załóż",
    keineMaschine: "Jeszcze żadnej maszyny",
    keineMaschineText: "Załóż maszynę i zapisz jej zadania konserwacyjne.",
    maschine: "Maszyna",
    inventarnummer: "Nr inwent.",
    standort: "Lokalizacja",
    verantwortlich: "Odpowiedzialny",
    status: "Status",
    aktiv: "aktywna",
    stillgelegt: "wycofana",
    angelegt: "Maszyna utworzona.",
  },
  sensoren: {
    einleitung:
      "Temperatura i wilgotność w ustawionym interwale odpytywania. Wartość poza globalnymi " +
      "granicami jest wyróżniona kolorem ostrzegawczym.",
    misst: "Mierzy …",
    jetztMessen: "Zmierz teraz",
    keinGeraet: "Nie skonfigurowano urządzenia",
    keinGeraetText: "Czujniki zakłada się w ustawieniach — host, identyfikator i community.",
    verlauf: "Przebieg",
    stunden: (n: number) => `${n} h`,
    tage: (n: number) => `${n} dni`,
    temperatur: "Temperatura",
    luftfeuchte: "Wilgotność",
    zuletzt: (zeit: string) => `Ostatnio ${zeit}`,
    keinMesswert: "Jeszcze żadnego pomiaru.",
    nichtsGemessen: "W tym okresie nic nie zmierzono.",
    frisch: "aktualny",
    verzoegert: "opóźniony",
    offline: "offline",
    unbekannt: "jeszcze nic nie zmierzono",
    temperaturverlauf: "Temperatura (°C)",
    feuchteverlauf: "Wilgotność (%)",
    mittelFuenfMinuten: "Średnie 5-minutowe",
    mittelStunde: "Średnie godzinowe",
    minMax: (fenster: string) => `Min/maks ${fenster}`,
    ausserhalbGrenzen: "Poza granicami",
    untergrenze: "Min",
    obergrenze: "Maks",
    ladeFehler: "Nie udało się wczytać pomiarów.",
  },
  hilfe: {
    einleitung:
      "Co potrafi platforma, jak powstają liczby i co robić, gdy coś się nie zgadza.",
    nurDeutsch: "Same strony pomocy są napisane po niemiecku.",
    suchen: "Szukaj w pomocy",
    nichtsGefunden:
      "Nic nie znaleziono. Jeśli czegoś w pomocy brakuje, powiedz to przez " +
      "„Zgłoś App Feedback” na dole po prawej.",
    alleThemen: "← Wszystkie tematy",
    navigation: "Tematy pomocy",
  },
  meldungen: {
    stand: (offen: number) => `Co zgłoszono z widoków jako App Feedback. Otwartych: ${offen}`,
    neuSeit: (anzahl: number) => ` · ${anzahl} jeszcze nieobejrzanych`,
    nichtsGemeldet: "Brak App Feedback",
    nichtsGemeldetText:
      "Przez „Zgłoś App Feedback” na dole po prawej każda zalogowana osoba może zgłosić, co " +
      "na stronie się nie zgadza.",
    unbekannt: "nieznany",
    status: "Status",
    offen: "otwarte",
    inBearbeitung: "W toku",
    erledigt: "załatwione",
    meldung: "Feedback",
    aufnahme: "Zrzut strony",
    ansicht: "Widok",
    tabelle: "Tabela",
    kanban: "Kanban",
    gruppieren: "Grupuj według",
    nachStatus: "Status",
    nachPerson: "Osoba",
    nichtZugewiesen: "Nieprzypisane",
    ziehenHinweis: "Przeciągnij karty do innej kolumny, aby zmienić status lub osobę odpowiedzialną.",
    verschieben: (beschreibung: string) => `Przenieś: ${beschreibung}`,
    spalte: {
      datum: "Data",
      von: "Od",
      seite: "Strona",
      beschreibung: "Opis",
      screenshot: "Zrzut",
      status: "Status",
      zugewiesen: "Przypisane do",
      aktionen: "Akcje",
    },
    oeffnen: "Otwórz",
    ungesehen: "nieobejrzane",
    alsGesehen: "Oznacz jako obejrzane",
  },
  auditAnsicht: {
    gibtEsNicht: "Takiego auditu nie ma",
    gibtEsNichtText: "Prawdopodobnie został usunięty.",
    internesAudit: "Audit wewnętrzny",
    externesAudit: "Audit zewnętrzny",
    prioritaet: (stufe: string) => ` · priorytet ${stufe}`,
    erledigt: (prozent: number) => ` · ${prozent} % zrobione`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} po terminie`,
    zurUebersicht: "Do przeglądu",
    status: "Status",
    stammdaten: "Dane podstawowe",
    titel: "Tytuł",
    bereich: "Zakres",
    leitenderAuditor: "Audytor wiodący",
    auditteam: "Zespół auditowy",
    geplantVon: "Początek (planowany)",
    geplantBis: "Koniec (planowany)",
    prioritaetFeld: "Priorytet",
    niedrig: "niski",
    mittel: "średni",
    hoch: "wysoki",
    auditziel: "Cel auditu",
    kategorien: "Kategorie",
    kategorienHinweis:
      "Audit jest często kilkoma rzeczami naraz — program wewnętrzny prowadzi system i proces " +
      "w jednym terminie. Dlatego wybór wielokrotny, a nie pojedyncze wskazanie.",
    normbezug: "Odniesienie do normy",
    normmatrixLeer: "Macierz norm jest pusta — prowadzi się ją w ustawieniach.",
    nichtGeprueft: "* jeszcze niesprawdzone wobec skonsolidowanego tekstu normy.",
    phasen: "Fazy",
    keinePhasen: "Brak faz — ten audit założono bez szablonu.",
    phase: "Faza",
    verantwortlich: "Odpowiedzialny",
    faellig: "Termin planowany",
    erledigtAm: "Termin rzeczywisty",
    phaseErgaenzen: "Dodaj fazę",
    phaseBeispiel: "np. audit uzupełniający",
    verlauf: "Historia",
    verlaufHinweis:
      "Zapisana przez bazę danych, a nie przez tę maskę — i potem ani nie do zmiany, ani nie " +
      "do skasowania.",
    nichtsGeschehen: "Jeszcze nic się nie wydarzyło.",
    warumEntfaellt: "Dlaczego ta faza obowiązkowa odpada?",
    uebernehmen: "Przejmij",
    abbrechen: "Anuluj",
    angelegt: "założono",
    geaendert: "zmieniono",
    geloescht: "skasowano",
    uebersprungen: "pominięto",
    bearbeiten: "Edytuj",
    gespeichert: "Zapisano.",
    pflicht: "Obowiązkowa",
    kommentar: "Komentarz",
    begruendung: "Uzasadnienie dla „nie dotyczy“",
    grundPflicht: "Fazę obowiązkową można pominąć tylko z uzasadnieniem.",
    datumPflicht: "„Zakończona“ wymaga rzeczywistego terminu.",
    phaseSpeichern: "Zapisz fazę",
    phaseGespeichert: "Faza zapisana.",
  },
  maschine: {
    gibtEsNicht: "Takiej maszyny nie ma",
    gibtEsNichtText: "Prawdopodobnie została skasowana.",
    zurUebersicht: "Do przeglądu",
    stammdaten: "Dane podstawowe",
    name: "Nazwa",
    inventarnummer: "Nr inwent.",
    standort: "Lokalizacja",
    hersteller: "Producent",
    modell: "Model",
    verantwortlich: "Odpowiedzialny",
    status: "Status",
    aktiv: "aktywna",
    stillgelegt: "wycofana",
    notizen: "Notatki",
    wartungsaufgaben: "Zadania konserwacyjne",
    jahr: "Rok",
    halbjahr: "Półrocze",
    erstesHalbjahr: "tydz. 1–26",
    zweitesHalbjahr: "tydz. 27–52",
    wirdGebaut: "Tworzenie …",
    nachweisbogen: "Arkusz dowodowy",
    neueAufgabe: "Nowe zadanie",
    aufgabeBeispiel: "np. sprawdzić poziom oleju",
    intervall: "Interwał",
    wochen: "Tygodnie",
    keineAufgabe: "Jeszcze żadnego zadania — arkusz byłby pusty.",
    aufgabe: "Zadanie",
    dateien: "Pliki",
    planHinterlegen: "Zapisz plan",
    nachweisAblegen: "Odłóż dowód",
    dateienHinweis: "Plan producenta i zeskanowane z powrotem, podpisane arkusze.",
    keineDatei: "Jeszcze żadnego pliku.",
    plan: "Plan",
    nachweis: "Dowód",
    laedt: "Wczytuje …",
    taeglich: "Codziennie",
    woechentlich: "Co tydzień",
    monatlich: "Co miesiąc",
    quartalsweise: "Co kwartał",
    alleNWochen: "Co N tygodni",
    alleNWochenZahl: (wochen: number) => `Co ${wochen} tygodni`,
    bearbeiten: "Edytuj",
    gespeichert: "Zapisano.",
    nameFehlt: "Nazwa jest wymagana.",
  },
  atr: {
    einleitung:
      "Katalog części jest podstawą: z niego dowód dostawy bierze nazwę, rysunek i wagę. " +
      "Wyszukiwanie idzie po numerze części bez dodatków — liczą się tylko cyfry.",
    teilAnlegen: "Załóż część ręcznie",
    teilBeispiel: "Numer części, np. VR-1234-56",
    anlegen: "Załóż",
    wirdGelesen: "Wczytywanie …",
    mappeEinlesen: "Wczytaj teczkę referencyjną",
    suchen: "Szukaj",
    suchePlatzhalter: "Numer części, nazwa lub rysunek",
    nichtsGefunden: "Nic nie znaleziono",
    katalogLeer: "Katalog jest pusty",
    keinTeil: "Żadna część nie pasuje do tego wyszukiwania.",
    katalogLeerText: "Wczytaj teczkę referencyjną albo załóż część ręcznie.",
    teilenummer: "Numer części",
    bezeichnung: "Nazwa",
    zeichnung: "Rysunek",
    gewicht: "Waga kg",
    kategorie: "Kategoria",
    bereich: "Sekcja",
    lieferungen: "Dostawy",
    teilekatalog: "Katalog części",
    bearbeiten: "Edytuj",
    speichern: "Zapisz",
    gespeichert: "Zapisano.",
    gewichtUngueltig: "Podaj wagę jako liczbę w kg, np. 0,44.",
    nichtGespeichert: (meldung: string) => `Nie zapisano: ${meldung}`,
  },
  lieferungen: {
    einleitung:
      "Dowód dostawy zostaje wczytany, porównany z katalogiem części i zapisany jako szkic. Z dokumentami ma status „wygenerowano”; gdy automatyczne skanowanie zapisze je w folderze wyjściowym — „przekazano”.",
    wirdGelesen: "Wczytywanie …",
    einlesen: "Wczytaj dowód dostawy",
    laeuft: "Trwa …",
    eingangDurchsehen: "Przejrzyj folder wejściowy",
    berichtNummer: (nr: string) => ` · nr ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} pozycji, ${zugeordnet} znaleziono w katalogu.`,
    keinLieferschein: "Jeszcze żadnego dowodu dostawy",
    keinLieferscheinSchreiben: "Wczytaj PDF dowodu dostawy — potem stanie tu do przejrzenia.",
    keinLieferscheinLesen: "Gdy tylko dowód dostawy zostanie wczytany, stanie tutaj.",
    lieferschein: "Dowód dostawy",
    datum: "Data",
    programm: "Program",
    msn: "MSN",
    status: "Status",
    entwurf: "Szkic",
    erzeugt: "wygenerowano",
    abgelegt: "przekazano",
    atrNummer: "Nr ATR",
    containernummer: "Numer kontenera",
    erstellt: "Utworzono",
    auswaehlen: (nr: string) => `Zaznacz dostawę ${nr}`,
    ausgewaehlt: (anzahl: number) => `Zaznaczono: ${anzahl}`,
    auswahlAufheben: "Wyczyść zaznaczenie",
    containerbeschriftung: "Utwórz etykietę kontenera",
    containerFrage: "Numer kontenera dla zaznaczonych dostaw:",
    containerHinweis: "Etykieta pokazuje wszystkie dostawy przypisane do tego kontenera — także te, które już w nim były.",
    containerErstellt: (nr: string) => `Przypisano kontener ${nr} – etykieta jest pobierana`,
    erstellen: "Utwórz",
  },
  durchsicht: {
    nichtGefunden: "Nie znaleziono dostawy.",
    wirdErzeugt: "Tworzenie …",
    dokumenteErzeugen: "Utwórz dokumenty",
    kopfdaten: "Dane nagłówka",
    atrNummer: "Numer ATR",
    containernummer: "Numer kontenera",
    satzTitel: "Nazwa zestawu",
    programm: "Program",
    msn: "MSN",
    bereich: "Obszar",
    wiegedatum: "Data ważenia",
    pruefdatum: "Data kontroli",
    qsUnterschrift: "Podpis QS",
    hoechstgewicht: "Waga maks. kg",
    positionen: "Pozycje",
    pos: "Poz",
    menge: "Ilość",
    seriennummern: "Numery seryjne",
    nichtImKatalog: "nie ma w katalogu",
    poNummer: "Numer PO",
    poPos: "PO Pos",
    speichern: "Zapisz",
    gespeichert: "Zapisano.",
    seriennummernAbweichung: (anzahl: number, menge: number) => `${anzahl} nr seryjnych przy ilości ${menge}`,
    seriennummernFeld: (pos: string) => `Numery seryjne pozycji ${pos}`,
  },
  fair: {
    dateiFehlt: (meldung: string) =>
      `Samego rysunku nie da się wczytać (${meldung}). Wymiary mimo to są poniżej.`,
    einleitung:
      "Badanie pierwszej sztuki: wczytać rysunek i przy każdym wymiarze do sprawdzenia " +
      "postawić numerowany balonik. Numery nadaje baza danych i trzyma je bez luk.",
    bezeichnungFrei: "Nazwa (puste = nazwa pliku)",
    beispiel: "np. wałek 12×40, rysunek 4711",
    wirdGeladen: "Wczytywanie …",
    zeichnungWaehlen: "Wybierz rysunek",
    keineZeichnung: "Jeszcze żadnego rysunku",
    keineZeichnungSchreiben: "Wczytaj PDF albo obraz — potem da się balonikować wymiary.",
    keineZeichnungLesen: "Gdy tylko rysunek zostanie wczytany, stanie tutaj.",
    bezeichnung: "Nazwa",
    teilenummer: "Numer części",
    kunde: "Klient",
    hochgeladen: "Wczytano",
    pruefliste: "Lista kontrolna",
    einMass: "1 wymiar",
    masse: (anzahl: number) => `${anzahl} wymiarów`,
    kopieren: "Kopiuj",
    csv: "CSV",
    keinMass: "Jeszcze żadnego wymiaru.",
    nr: "Nr",
    seite: "Strona",
    wert: "Wartość",
    wertBeispiel: "np. 12,0 h7",
    wertZu: (nummer: number) => `Wartość do numeru ${nummer}`,
    nachOben: (nummer: number) => `Numer ${nummer} w górę`,
    nachUnten: (nummer: number) => `Numer ${nummer} w dół`,
    nummer: (nummer: number) => `Numer ${nummer}`,
    drehen: "Obróć widok",
    verkleinern: "Pomniejsz",
    vergroessern: "Powiększ",
    einpassen: "Dopasuj",
    darstellung: "Widok",
    bubbleGroesse: "Rozmiar dymków",
    zeichnung: "Rysunek",
    ladefehler: "Nie udało się wczytać rysunku.",
    alleKunden: "Wszyscy klienci",
    ohneKunde: "Bez klienta",
    kundenfilter: "Filtruj według klienta",
    artikelnummer: "Nr art.",
    artikelnummerLang: "Numer artykułu",
    pn: "P/N",
    bubblesKleiner: "Mniejsze bąbelki",
    bubblesGroesser: "Większe bąbelki",
    pdf: "PDF",
    pdfExport: "Eksportuj PDF",
    pdfWirdErstellt: "Tworzenie PDF …",
    pdfFehler: (meldung: string) => `Nie udało się utworzyć PDF: ${meldung}`,
    ocrNeu: "Uruchom ponownie OCR dla tego wiersza",
    ocrLeer: "Nic nie rozpoznano — wpisz wartość ręcznie.",
    ocrFehler: (meldung: string) => `OCR nie powiódł się: ${meldung}`,
    ocrGleich: "OCR odczytuje tę samą wartość.",
    ocrErsetzenTitel: "Zastąpić wartość?",
    ocrErsetzen: (nummer: number, alt: string, neu: string) => `Numer ${nummer}: zastąpić „${alt}” przez „${neu}”?`,
    ersetzen: "Zastąp",
    ziehen: (nummer: number) => `Przeciągnij numer ${nummer}, aby go przesunąć`,
    nurNummernfolge: "Przesuwanie działa tylko w kolejności numerów — bez wyszukiwania i bez sortowania według strony lub wartości.",
  },
  newsletter: {
    keineAusgabe: "Jeszcze żadnego wydania",
    keineAusgabeText: "Gdy tylko redakcja opublikuje wydanie, stanie tutaj.",
    zurRedaktion: "Do redakcji",
    quartalJahr: (quartal: number, jahr: number) => `Kwartał ${quartal} · ${jahr}`,
    entwurfSuffix: " · szkic",
    ausgabe: "Wydanie",
    quartalKurz: (quartal: number, jahr: number) => `Q${quartal} ${jahr}`,
    entwurfKlammer: " (szkic)",
    alsPdf: "Jako PDF",
    wirdGesetzt: "Składanie …",
    seiteVon: (nr: number, gesamt: number) => `Strona ${nr} z ${gesamt} …`,
    redaktion: "Redakcja",
    niemandDazu: "W tym kwartale nikt nie doszedł.",
    beitraege: "Artykuły",
    belegschaftInZahlen: "Załoga w liczbach",
    neuBeiUns: "Nowi u nas",
    redaktionEinleitung:
      "Jedno wydanie na kwartał. Rozdziały wyznaczają kolejność w numerze; publikuje się je " +
      "dopiero, gdy są gotowe.",
    zurLeseransicht: "Do widoku czytelnika",
    jahr: "Rok",
    quartal: "Kwartał",
    ausgabeAnlegen: "Załóż wydanie",
    ausgabeBearbeiten: "Edytuj wydanie",
    keineAusgabeRedaktion: "Wybierz rok i kwartał i załóż — potem powstaną tu rozdziały.",
    titelDerAusgabe: "Tytuł wydania",
    status: "Status",
    entwurf: "Szkic",
    veroeffentlicht: "opublikowane",
    titelbild: "Okładka",
    rueckseite: "Tylna strona",
    ersetzen: ": zastąp",
    waehlen: ": wybierz",
    ausgabeLoeschen: (quartal: number, jahr: number) => `Wydanie Q${quartal} ${jahr}`,
    neuesKapitel: "Nowy rozdział",
    kapitelBeispiel: "np. Z hali produkcyjnej",
    art: "Rodzaj",
    hinzufuegen: "Dodaj",
    kapiteltitel: "Tytuł rozdziału",
    kapitelHoch: "Rozdział w górę",
    kapitelRunter: "Rozdział w dół",
    ueberschrift: "Nagłówek",
    eintrag: "Wpis",
    textMarkdown: "Tekst. Markdown jest dozwolony — **pogrubienie**, listy, tabele.",
    text: "Tekst",
    bild: "Obraz",
    bildGroesse: (nr: number) => `Rozmiar obrazu ${nr}`,
    nieEingefroren: "Jeszcze nic nie zamrożone — rozdział zostanie w numerze pusty.",
    kpiEingefroren: "Liczby załogi za kwartał są zamrożone.",
    niemandEingefroren: "Zamrożone — w tym kwartale nikt nie doszedł.",
    zugaengeEingefroren: (anzahl: number) =>
      `Zamrożone: ${anzahl} ${anzahl === 1 ? "nowa osoba" : "nowych osób"} w kwartale.`,
    einfrieren: "Zamroź",
    neuEinfrieren: "Zamroź na nowo",
    rechtFehlt: (quelle: string) => `Brakuje do tego prawa przy źródle: zobaczyć ${quelle}.`,
    quelleKpi: "Wskaźniki",
    quellePersonal: "Kadry",
    ausgabeAngelegt: "Wydanie założone.",
    ausgabeGeloescht: "Wydanie skasowane.",
    kapitelAngelegt: "Rozdział założony.",
    standEingefroren: "Stan zamrożony.",
  },
  signage: {
    einleitung: "Media, playlisty, harmonogramy i urządzenia ekranów.",
    bereiche: "Obszary Signage",
    medien: "Media",
    medienHinzu: "Dodaj media",
    playlists: "Playlisty",
    zeitplaene: "Harmonogramy",
    geraete: "Urządzenia",
    dateiZiehen: "Przeciągnij plik tutaj",
    dateiWaehlen: "Wybierz plik",
    dateiHinweis: "Obraz, wideo, PDF lub PPTX, do 50 MB",
    wirdUebertragen: "przesyłanie …",
    art: "Rodzaj",
    webseite: "Strona internetowa (URL)",
    htmlSchnipsel: "Fragment HTML",
    titel: "Tytuł",
    titelBeispiel: "Urodziny",
    urlHinweis:
      "Podaj pełny adres. Player działa na własnym porcie, ścieżki względne tam nie " +
      "działają.",
    aufnehmen: "Dodaj",
    medienFehler: "Nie udało się wczytać mediów.",
    keineMedien: "Jeszcze żadnych mediów",
    keineMedienText:
      "Wczytaj plik albo dodaj URL. Następnie da się zestawić media w playlisty.",
    erneut: "ponownie",
    inVerwendung: "Medium jest w użyciu",
    inVerwendungText: (titel: string, anzahl: number) =>
      `„${titel}” jest jeszcze wpięty w ${anzahl} playlist(y). Usuń go tam najpierw.`,
    verstanden: "Rozumiem",
    wartet: "czeka",
    konvertiert: "konwertuje",
    fertig: "gotowe",
    fehlgeschlagen: "nie powiodło się",
    keineHeartbeats: "Jeszcze nie zapisano żadnych heartbeatów.",
    nieGesehen: "nigdy niewidziane",
    online: "online",
    vorMinuten: (minuten: number) => `${minuten} min temu`,
    offline: "offline",
    entzogen: "odebrany",
    keinGeraet: "Jeszcze żadnego sparowanego urządzenia",
    keinGeraetText:
      "Uruchom ekran z playerem. Pokaże sześciocyfrowy kod, który tu wpiszesz.",
    geraetKoppeln: "Sparuj urządzenie",
    geraet: "Urządzenie",
    status: "Status",
    verfuegbarkeit: "Dostępność 24 h",
    ausfaelle: "Awarie 24 h",
    tags: "Tagi",
    playlist: "Playlista",
    zuletztGesehen: "Ostatnio widziane",
    seiteNeuLaden: "Przeładuj stronę",
    neuStarten: "Uruchom urządzenie ponownie",
    bearbeiten: "Edytuj",
    zugangEntziehen: "Odbierz dostęp",
    geraetBearbeiten: "Edytuj urządzenie",
    name: "Nazwa",
    bilddrehung: "Obrót obrazu",
    ton: "Dźwięk",
    tonAktiv: "Dźwięk włączony",
    abbrechen: "Anuluj",
    speichern: "Zapisz",
    tagsHinweis: "Wyznaczają, które playlisty i harmonogramy dostaje to urządzenie.",
    entziehenText: (name: string) =>
      `„${name}” traci natychmiast dostęp i pokazuje znowu kod parowania.`,
    neustartText: (name: string) => `„${name}” będzie czarny przez około minutę.`,
    geraetGespeichert: "Urządzenie zapisane.",
    geraetGeloescht: "Urządzenie skasowane.",
    keinGeraetGewaehlt: "nie wybrano urządzenia",
    neuePlaylist: "Nowa playlista",
    neuePlaylistText: "Ustal nazwę i tagi docelowe. Wpisy przyjdą w następnym kroku.",
    namensbeispiel: "Recepcja",
    keinePlaylist: "Jeszcze żadnej playlisty",
    keinePlaylistText:
      "Playlista wiąże media w kolejność i jest rozdzielana na urządzenia przez tagi.",
    playlistAnlegen: "Załóż playlistę",
    aktiv: "Aktywna",
    erstellt: "Utworzono",
    kopieren: "Kopiuj",
    playlistGeloescht: "Playlista skasowana.",
    playlistKopiert: "Playlista skopiowana. Wpisy nie są kopiowane.",
    playlistInPlan: "Playlista ma aktywne harmonogramy",
    zeitplanHinweis:
      "Harmonogram ma pierwszeństwo przed samym przypisaniem tagów. Okno przez północ " +
      "podziel na dwa harmonogramy.",
    wochentage: "Dni tygodnia",
    wochentagKuerzel: ["Pn", "Wt", "Śr", "Cz", "Pt", "So", "Nd"],
    von: "Od",
    bis: "Do",
    prioritaet: "Priorytet",
    zeitplanAktiv: "Harmonogram aktywny",
    keineZeitplaene: "Brak harmonogramów",
    keineZeitplaeneText:
      "Bez harmonogramu o tym, którą playlistę pokazuje urządzenie, decyduje samo " +
      "przypisanie tagów. Harmonogram włącza playlistę przed nimi w określone dni i godziny.",
    tage: "Dni",
    zeitfenster: "Okno czasowe",
    aktionen: "Akcje",
    zeitplanBearbeiten: "Edytuj harmonogram",
    neuerZeitplan: "Nowy harmonogram",
    zeitplaeneFehler: "Nie udało się wczytać harmonogramów.",
    endeNachStart: "Koniec musi być po początku. Przez północ załóż proszę dwa harmonogramy.",
    mindestensEinTag: "Wybierz co najmniej jeden dzień tygodnia.",
    playlistWaehlen: "Wybierz playlistę.",
    taeglich: "codziennie",
    zielTags: "Tagi docelowe",
    ueberblenden: "Przenikanie",
    harterSchnitt: "Twarde cięcie",
    ziehpunkt: "Uchwyt",
    verwerfen: "Odrzuć",
    medienHinzufuegen: "Dodaj media i ułóż je uchwytem.",
    mediumWaehlen: "Wybierz medium",
    mediumHinzufuegen: "Dodaj medium",
    mediumWaehlenText: "Wybrane medium zostanie dołączone na końcu playlisty.",
    schliessen: "Zamknij",
    keineMedienAnlegen: "Nie ma jeszcze mediów. Załóż najpierw jakieś w obszarze Media.",
    unbekanntesMedium: "nieznane medium",
    playlistGespeichert: "Playlista zapisana. Urządzenia przeładują się natychmiast.",
    kopplungscode: "Kod parowania",
    codeBeispiel: "ABC-123",
    geraetename: "Nazwa urządzenia",
    geraeteBeispiel: "Recepcja lewa",
    tagsPflicht: "Przez tagi urządzenie dostaje swoją playlistę. Bez taga ekran zostanie pusty.",
    koppeln: "Sparuj",
    formatErwartet: "Oczekiwany format XXX-XXX.",
    codeUnbekannt: "Kod nieznany, wygasł albo już zajęty. Każ wyświetlić nowy na ekranie.",
    tagEingeben: "Wpisz tag i naciśnij Enter",
  },
  einstellungen: {
    titel: "Ustawienia",
    einleitung: "Co platforma liczy, pobiera i pokazuje — dla wszystkich tak samo.",
    bereiche: "Obszary",
    gruppen: {
      kennzahlen: "Wskaźniki",
      kennzahlenText:
        "Wartości docelowe pulpitów. Pojawiają się jako linia celu w przebiegu i decydują, " +
        "od kiedy kafelek ostrzega.",
      personal: "HR",
      personalText:
        "Które nieobecności liczą się jako choroba i które działy należą do produkcji. " +
        "Bez tych list wskaźniki kadrowe zostaną puste.",
      atr: "ATR",
      atrText:
        "Co w każdym dokumencie danego programu stoi tak samo i skąd biorą się dowody dostawy.",
      qualitaet: "Jakość",
      qualitaetText:
        "Macierz norm, na którą powołuje się audit, i szablony faz, które nowy audit dostaje " +
        "jako listę kontrolną.",
      sensoren: "Czujniki",
      sensorenText:
        "Urządzenia pomiarowe w sieci: gdzie stoją, pod jakim identyfikatorem dostarczają " +
        "temperaturę i wilgotność i od kiedy wartość uchodzi za zbyt wysoką.",
      zeugnisse: "Świadectwa",
      zeugnisseText:
        "Co na każdym świadectwie pracy stoi tak samo: firma, miejscowość i oba podpisy. " +
        "Merytoryczny jest przy tworzeniu rozwiązywany z Personio — tu stoi tylko zapasowy.",
      erscheinung: "Wygląd",
      erscheinungText:
        "Logo firmy — u góry po lewej w aplikacji i w nagłówku każdego tworzonego pliku: " +
        "planu wdrożenia, dowodu konserwacji, zestawienia szkoleń, świadectwa.",
      anzeigen: "Ekrany",
      anzeigenText:
        "Adresy, które działają na ekranach w firmie. Każdy niesie podpisany token, " +
        "obowiązuje tylko dla swojego jednego ekranu i wygasa.",
      email: "E-maile",
      emailText:
        "Z jakiego konta Microsoft 365 platforma wysyła przypomnienia i raporty. Nic nie jest wysyłane bez wyraźnego działania.",
      ad: "Active Directory",
      adText: "Logowanie do lokalnego AD przez LDAPS. compute sprawdza hasło przy logowaniu i odwzorowuje grupy AD; administrator nadaje prawa aplikacji dla każdej grupy.",
      zugaenge: "Użytkownicy i grupy",
      zugaengeText:
        "Zakładanie osób, tworzenie grup i nadawanie im praw do aplikacji. Zmiany działają, " +
        "gdy tylko dana osoba zaloguje się następnym razem — prawa stoją w jej tokenie.",
    },
  },
  einstellungenText: {
    appName: "Nazwa aplikacji",
    appNameHinweis:
      "Pokazywana w nagłówku bez logo, w tytule strony i na stronie logowania.",
    farbrollen: "Role kolorów",
    farbrollenHinweis:
      "Kolor główny niesie fokus, linki, przycisk główny i główną serię wykresu; tekst leży na nim. Osobno dla trybu jasnego i ciemnego.",
    hellTitel: "Jasny",
    dunkelTitel: "Ciemny",
    hauptfarbe: "Kolor główny",
    textAufHauptfarbe: "Tekst na kolorze głównym",
    kontrastTitel: "Za mały kontrast (WCAG 2.2)",
    kontrastZeile: (thema: string, bereich: string, verhaeltnis: string, mindestens: string) =>
      `„${bereich}” (${thema}): kontrast ${verhaeltnis}:1, wymagane ${mindestens}:1`,
    kontrastBereiche: {
      linkSeite: "Linki na stronie",
      linkKarte: "Linki na kartach",
      fokusFlaeche: "Fokus na szarej powierzchni",
      diagramm: "Kolor wykresu",
      knopfText: "Tekst na przycisku głównym",
    },
    farbenGespeichert: "Kolory zapisane. Działają po ponownym załadowaniu.",
    farbenAufVorgabe: "Przywrócono domyślne.",
    farbenZuruecksetzen: "Przywróć domyślne",
    email: {
      titel: "Wysyłka e-maili (Microsoft 365)",
      einleitung:
        "Centralna usługa przypomnień i raportów przez Microsoft Graph.",
      ohneSchluessel:
        "Na serwerze nie ustawiono GEHEIM_SCHLUESSEL. Dopóki go nie ma, nie da się zapisać sekretu.",
      gespeichert: "Zapisano.",
      speichert: "Zapisywanie …",
      speichern: "Zapisz",
      speichernFehler: (meldung: string) => `Zapis nie powiódł się: ${meldung}`,
      modus: "Tryb",
      modusApp: "Uprawnienie aplikacji",
      modusDelegiert: "Własne konto (delegowane)",
      modusAppHinweis: "Wysyła przez konto aplikacji z uprawnieniem Mail.Send; wymaga sekretu klienta i zgody administratora.",
      modusDelegiertHinweis: "Wysyła jako zalogowana osoba po logowaniu kodem urządzenia; bez zgody administratora.",
      tenantId: "Identyfikator Tenant",
      clientId: "Identyfikator klienta",
      clientSecret: "Sekret klienta",
      secretGesetzt: "zapisany — zostaw puste, aby zachować",
      absender: "Adres nadawcy",
      absenderName: "Nazwa nadawcy (opcjonalnie)",
      aktivieren: "Wysyłka włączona",
      testTitel: "E-mail testowy",
      testHinweis: "Wysyła wiadomość na podany adres. Tylko to działanie coś wysyła.",
      testEmpfaenger: "Odbiorca",
      testSenden: "Wyślij e-mail testowy",
      testLaeuft: "Wysyłanie …",
      testOk: "E-mail testowy wysłany.",
      testFehler: "Wysyłka nie powiodła się.",
      delegiertTitel: "Logowanie przez Microsoft",
      delegiertAnmelden: "Zaloguj przez Microsoft",
      delegiertAnleitung:
        "Otwórz adres, wpisz kod i zaloguj się własnym kontem Microsoft 365.",
      delegiertWartet: "Oczekiwanie na logowanie …",
      verbundenMit: (konto: string) => `Zalogowano jako ${konto}`,
      trennen: "Rozłącz",
      getrennt: "Rozłączono.",
    },
    speichernFehler: (meldung: string) => `Zapis nie powiódł się: ${meldung}`,
    zielwertGespeichert: "Wartość docelowa zapisana. Pulpity pokażą ją po przeładowaniu.",
    zahlAbNull: "Podaj liczbę od 0.",
    personalGespeichert: "Zapisano. Pulpit kadrowy pokaże to po przeładowaniu.",
    krankTypen: "Rodzaje nieobecności, które liczą się jako choroba",
    produktionAbteilungen: "Działy produkcji",
    kompetenzAttribute: "Pola Personio, które liczą się jako uzupełniona kompetencja",
    ausDemBestand: "z zasobu",
    abteilungenBeispiel: "Wytwarzanie, Montaż",
    firmenlogo: "Logo firmy",
    anzeigenHinweis:
      "Tworzy adres dla wpisu playlisty w playerze Signage. Obowiązuje tylko dla wybranego " +
      "ekranu i wygasa — wpis, którego nikt już nie prowadzi, sam przez to przestaje " +
      "pokazywać.",
    logoHinweis:
      "Stoi u góry po lewej w aplikacji i w nagłówku każdego tworzonego formularza — " +
      "planu wdrożenia, dowodu konserwacji, zestawienia szkoleń, świadectwa. PNG, JPEG albo SVG, " +
      "najwyżej 5 MB. Jeśli nic nie wskazano, stoi tam napis „ACM-Plattform”.",
    communityHinweis: "jest odkładane zaszyfrowane i nigdy więcej nie pokazywane",
    verwaltenSchliesstEin: "„Zarządzanie” na kafelku platformy zawiera każde inne prawo.",
    logoAlt: "Wskazane logo firmy",
    keinsHinterlegt: "Jeszcze nic nie wskazano.",
    laedt: "Wczytuje …",
    ersetzen: "Zastąp",
    hochladen: "Wczytaj",
    logoHochladen: "Wczytaj logo firmy",
    logoHinterlegt: "Logo zapisane.",
    anzeige: "Ekran",
    geburtstage: "Urodziny tygodnia",
    neuzugaenge: "Nowi w zespole",
    gueltigTage: "Ważne przez (dni)",
    erzeugt: "Tworzy …",
    adresseErzeugen: "Utwórz adres",
    adresseKopiert: "Adres skopiowany.",
    kopierenFehler: "Kopiowanie się nie udało — zaznacz proszę ręcznie.",
    kopieren: "Kopiuj",
    gespeichert: "Zapisano.",
    speichern: "Zapisz",
    speichert: "Zapisuje …",
    firma: "Firma",
    ort: "Miejscowość (nad datą)",
    nameRueckfall: "Nazwisko (zapasowe)",
    titelRueckfall: "Tytuł (zapasowy)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "Profil wystawcy",
    ausstellerHinweis:
      "Stoi na każdym świadectwie. Wzór pisma ACM jest używany, gdy tylko w nazwie firmy " +
      "stoi „ACM”.",
    linkeUnterschrift: "Lewy podpis — merytoryczny",
    linkeHinweis:
      "Zwykle przełożony danej osoby; jest on przy tworzeniu rozwiązywany z Personio. " +
      "To, co stoi tutaj, działa tylko wtedy, gdy Personio nic nie daje — na przykład przy " +
      "osobach prowadzonych poza nim.",
    rechteUnterschrift: "Prawy podpis — kadry",
    rechteHinweis:
      "Dla wszystkich świadectw ten sam. Związany z osobą z Personio, tytuł przychodzi " +
      "stamtąd i pozostaje właściwy, gdy zmienia się stanowisko.",
    personAusPersonio: "Osoba z Personio",
    keinePerson: "— żadna, użyj pola tekstowego poniżej —",
    personenFehler: (meldung: string) => `Nie udało się wczytać listy osób (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "Szablony",
    vorlagenHinweis:
      "Jeden szablon na program. Dane nagłówka i plik szkieletowy stoją tak samo w każdym " +
      "dokumencie ATR tego programu. Szablon zakłada się przy wczytaniu teczki referencyjnej " +
      "w katalogu części.",
    keineVorlage: "Jeszcze żadnego szablonu",
    keineVorlageText: "Wczytaj teczkę referencyjną — program stoi tam w komórce D2.",
    geruestHinterlegt: "Plik szkieletowy zapisany.",
    geruestErsetzen: "Zastąp szkielet",
    geruestWaehlen: "Wybierz szkielet",
    keineHinterlegt: "jeszcze nic nie wskazano",
    kunde: "Klient",
    lieferant: "Dostawca",
    arbeitspaket: "Pakiet roboczy",
    referenz: "Referencja",
    bestellerSpez: "Specyfikacja zamawiającego",
    lieferantenSpez: "Specyfikacja dostawcy",
    kundenSpez: "Specyfikacja klienta",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "Rozdział ATA",
    waage: "Waga",
    qsUnterschrift: "Podpis QS",
    eingangsordner: "Folder wejściowy",
    eingangHinweis:
      "Dowód dostawy z folderu wejściowego zostaje wczytany, staje się dostawą i trafia do archiwum. Dozwolone serwery określa ATR_SMB_ERLAUBT. Hasło wpisane tutaj ma pierwszeństwo przed ATR_SMB_PASSWORT ze środowiska.",
    laeuft: "działa",
    aus: "wyłączone",
    zuletzt: (zeit: string, text: string) => `Ostatnio ${zeit}: ${text}`,
    nochNichtGelaufen: "Jeszcze nie przebiegło.",
    prueft: "Sprawdza …",
    verbindungPruefen: "Sprawdź połączenie",
    laeuftGerade: "Trwa …",
    jetztDurchsehen: "Przejrzyj teraz",
    verbindungSteht: (dateien: number) =>
      `Połączenie działa. ${dateien} ${dateien === 1 ? "plik czeka" : "plików czeka"} w folderze wejściowym.`,
    keineVerbindung: (meldung: string) => `Brak połączenia: ${meldung}`,
    unbekannt: "nieznany",
    gelesenAngelegt: (gelesen: number, angelegt: number) =>
      `${gelesen} wczytanych, ${angelegt} założonych.`,
    rechner: "Host",
    rechnerHinweis: "musi stać w ATR_SMB_ERLAUBT",
    freigabe: "Udział sieciowy",
    domaene: "Domena",
    benutzer: "Użytkownik",
    eingang: "Wejście",
    ausgang: "Wyjście",
    archiv: "Archiwum",
    wasEinLaufTut: "Co robi przebieg",
    entwurfAnlegen: "Załóż szkic do przejrzenia",
    dokumenteErzeugen: "Utwórz dokumenty i odłóż",
    intervall: "Interwał skanowania (sekundy, 0 = wył.)",
    intervallUngueltig: "Interwał musi być liczbą całkowitą od 0.",
    passwort: "Hasło konta usługi",
    passwortHinterlegt: "zapisane — zostaw puste, aby zachować",
    passwortUmgebung: "ze środowiska (ATR_SMB_PASSWORT) — wpis tutaj ma pierwszeństwo",
    passwortFehlt: "jeszcze nie zapisano",
    passwortOhneSchluessel: "Brak GEHEIM_SCHLUESSEL w środowisku — bez niego nie można zapisać hasła.",
    speichern: "Zapisz",
    gespeichert: "Zapisano.",
  },
  qualitaetEinstellungen: {
    normmatrix: "Macierz norm",
    normmatrixHinweis:
      "Klauzule, na które powołuje się audit. Użytej normy nie da się skasować — " +
      "zostaje wycofana, inaczej audit straciłby po cichu swoją podstawę.",
    schonInMatrix: "Ta klauzula stoi już w macierzy.",
    regelwerk: "Zbiór przepisów",
    revision: "Rewizja",
    klausel: "Klauzula",
    kurztext: "Krótki tekst",
    kurztextBeispiel: "Audit wewnętrzny",
    aufnehmen: "Dodaj",
    geprueft: "Sprawdzona",
    aktiv: "Aktywna",
    geprueftSchalter: (norm: string) => `${norm} sprawdzona`,
    aktivSchalter: (norm: string) => `${norm} aktywna`,
    phasenvorlagen: "Szablony faz",
    phasenvorlagenHinweis:
      "Kolejność kroków, którą dostaje nowy audit. Jest kopiowana przy zakładaniu — " +
      "późniejsza zmiana nie przepisuje historii.",
    neueVorlage: "Nowy szablon",
    vorlageBeispiel: "Audit systemu standard",
    anlegen: "Załóż",
    schritte: (anzahl: number) => `${anzahl} ${anzahl === 1 ? "krok" : "kroków"}`,
    schrittErgaenzen: "Dodaj krok",
    schrittBeispiel: "np. spotkanie otwierające",
  },
  personioZugang: {
    taktGespeichert: "Interwał zapisany.",
    abgleichTitel: "Synchronizacja",
    abgleichHinweis:
      "Jak często platforma sama pobiera dane z Personio, oraz synchronizacja ręczna.",
    intervall: "Interwał synchronizacji",
    intervallWahl: {
      "0": "Tylko ręcznie",
      "1": "Co godzinę",
      "6": "Co 6 godzin",
      "24": "Codziennie",
      "168": "Co tydzień",
    },
    abgleichJetzt: "Odśwież dane",
    abgleichLaeuft: "Synchronizacja …",
    abgleichFertig: (mitarbeiter: number, anwesenheiten: number, abwesenheiten: number) =>
      `Zsynchronizowano: ${mitarbeiter} pracowników, ${anwesenheiten} obecności, ${abwesenheiten} nieobecności.`,
    abgleichTeilweise: (mitarbeiter: number, fehler: string) =>
      `Częściowo zsynchronizowano (${mitarbeiter} pracowników): ${fehler}`,
    abgleichFehler: (fehler: string) => `Synchronizacja nie powiodła się: ${fehler}`,
    nachweisTitel: "Dokumenty do Personio",
    nachweisHinweis:
      "Przesyła dokument do profilu Personio po zmianie szkolenia lub kompetencji. Domyślnie wyłączone.",
    nachweisAktiv: "Przesyłaj dokumenty",
    nachweisKategorie: "Kategoria dokumentu",
    nachweisKategoriePlatzhalter: "ID kategorii Personio",
    nachweisGespeichert: "Zapisano.",
    titel: "Dane dostępowe Personio",
    einleitung:
      "Dane dostępowe aplikacji API Personio. Bez nich synchronizacja, " +
      "zdjęcia profilowe i listy podpowiedzi zostaną puste.",
    kennung: "Client-ID",
    geheimnis: "Client-Secret",
    feldHinweis:
      "Są odkładane zaszyfrowane i nigdy więcej nie pokazywane. Kto chce je " +
      "zmienić, wpisuje nowe.",
    speichern: "Zapisz",
    gespeichert: "Dane dostępowe zapisane.",
    speichernFehler: (meldung: string) => `Zapis nie powiódł się: ${meldung}`,
    entfernen: "Usuń",
    entfernt: "Dane dostępowe usunięte.",
    pruefen: "Sprawdź połączenie",
    prueftGerade: "Sprawdza …",
    verbindungSteht: "Personio przyjmuje dane dostępowe.",
    verbindungFehlt: "Personio nie odpowiada.",
    laedt: "Wczytuje …",
    keineHinterlegt: "Nie zapisano żadnych danych dostępowych.",
    ausDerUmgebung: "Obowiązują dane dostępowe ze środowiska serwera (.env).",
    hinterlegtSeit: (zeitpunkt: string, wer: string | null) =>
      wer
        ? `Zapisane ${zeitpunkt} przez ${wer}.`
        : `Zapisane ${zeitpunkt}.`,
    ohneSchluessel:
      "Na serwerze nie ustawiono GEHEIM_SCHLUESSEL. Dopóki go brakuje, " +
      "nic nie da się odłożyć zaszyfrowane.",
  },
  sensorEinstellungen: {
    neuesGeraet: "Nowe urządzenie",
    name: "Nazwa",
    nameBeispiel: "Serwerownia",
    rechner: "Host",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "musi stać w SNMP_ERLAUBT",
    community: "Community",
    port: "Port",
    kennungTemperatur: "Identyfikator temperatury",
    kennungLuftfeuchte: "Identyfikator wilgotności",
    faktorTemperatur: "Współczynnik temperatury",
    faktorHinweis: "0,1 gdy urządzenie podaje dziesiąte części stopnia jako liczbę całkowitą",
    faktorLuftfeuchte: "Współczynnik wilgotności",
    farbe: "Kolor w przebiegu",
    farbeHinweis: "np. #0f6e8c",
    optional: "opcjonalnie",
    anlegen: "Załóż",
    fragt: "Odpytuje …",
    ausprobieren: "Wypróbuj",
    keinGeraet: "Jeszcze żadnego urządzenia",
    keinGeraetText: "Wpisz powyżej host, community i co najmniej jeden identyfikator.",
    wirdAbgefragt: (name: string) => `${name} jest odpytywany`,
    communityErsetzen: "Zastąp community",
    unveraendert: "bez zmian",
    communityErsetzt: "Community zastąpione.",
    sensorAngelegt: "Czujnik założony.",
    sensorGeloescht: "Czujnik skasowany, wraz z szeregiem czasowym.",
    zahlEingeben: "Podaj liczbę.",
    taktTitel: "Interwał odpytywania",
    intervall: "Interwał odpytywania (sekundy)",
    intervallHinweis:
      "Dotyczy wszystkich czujników. Zakres 5–86400; poniżej 60 sekund odpytywanie następuje w praktyce co minutę.",
    intervallFehler: "Interwał musi być liczbą całkowitą od 5 do 86400.",
    grenzenTitel: "Globalne wartości graniczne",
    grenzenHinweis: "Dotyczą wszystkich czujników. Puste pole oznacza: brak granicy.",
    temperaturMin: "Temperatura min (°C)",
    temperaturMax: "Temperatura maks (°C)",
    feuchteMin: "Wilgotność min (%)",
    feuchteMax: "Wilgotność maks (%)",
    temperaturFehler: "Temperatura min musi być niższa niż maks.",
    feuchteFehler: "Wilgotność min musi być niższa niż maks.",
    einstellungenGespeichert: "Interwał i granice zapisane.",
    verwerfen: "Odrzuć",
  },
  zugaenge: {
    stufen: {
      viewer: "Podgląd",
      editor: "Edytowanie",
      admin: "Zarządzanie",
    },
    gruppeAngelegt: "Grupa założona.",
    gruppeGibtEsSchon: "Taka nazwa grupy już istnieje.",
    personAngelegt: "Osoba założona",
    gruppeUmbenannt: "Grupa przemianowana.",
    gruppeGeloescht: "Grupa skasowana.",
    mitgliedHinzu: "Członek dodany. Zadziała po następnym zalogowaniu.",
    schonInGruppe: "Ta osoba jest już w grupie.",
    neuesPasswort: "Nowe hasło",
    mitgliedEntfernt: "Członek usunięty. Zadziała po następnym zalogowaniu.",
    gemeldeteSeiten: "Zobacz App Feedback",
    neueGruppe: "Nowa grupa",
    gruppeBeispiel: "np. Sprzedaż wewnętrzna",
    anlegen: "Załóż",
    neuePerson: "Nowa osoba",
    personBeispiel: "imie.nazwisko@acm.local",
    keineGruppe: "Jeszcze żadnej grupy",
    keineGruppeText: "Załóż grupę, przypisz jej prawa do aplikacji i przyjmij osoby.",
    verzeichnis: "Katalog",
    ausVerzeichnis: "Pochodzi z katalogu",
    umbenennen: "Przemianuj",
    mitRechten: "Z uprawnieniami",
    ohneRechte: "Bez uprawnień",
    keinZugriff: "brak dostępu",
    rechteAnGruppe: "Prawa wiszą przy grupie, a nie przy osobie.",
    passwortNurJetzt:
      "Hasło stoi tu tylko teraz. Potem da się je już tylko zresetować, nie pokazać.",
    fertig: "Gotowe",
    anmeldung: "Logowanie",
    passwort: "Hasło",
    gruppeUmbenennen: "Przemianuj grupę",
    abbrechen: "Anuluj",
    speichern: "Zapisz",
    gruppenname: "Nazwa grupy",
    mitgliederVon: (name: string) => `Członkowie grupy „${name}”`,
    wirktNachAnmeldung: "Zmiany zadziałają, gdy tylko osoba zaloguje się następnym razem.",
    schliessen: "Zamknij",
    personHinzufuegen: "Dodaj osobę",
    auswaehlen: "— wybierz —",
    hinzufuegen: "Dodaj",
    keineMitglieder: "Ta grupa nie ma jeszcze członków.",
    passwortZuruecksetzen: "Zresetuj hasło",
    mitgliedEntfernen: "Usuń członka",
    entfernen: "Usuń",
  },
  kopftitel: {
    start: "Aplikacje",
    kennzahlen: "Pulpit KPI",
    offeneSchulungen: "Zaległe szkolenia",
    schulungsmatrix: "Macierz szkoleń",
    atrLieferungen: "Dostawy ATR",
    atrTeilekatalog: "Katalog części ATR",
  },
  kennzahlenHub: {
    titel: "Pulpit KPI",
    einleitung:
      "Wskaźniki wg działów. Dane pochodzą z eksportów ERP w sekcji Wczytywanie.",
    bereiche: {
      "/kpi/vertrieb": "Obrót, wartość zamówienia, udział klientów",
      "/hr/kennzahlen": "Załoga, fluktuacja, chorobowe — osobne uprawnienie",
      "/kpi/qualitaet": "Ustalenia auditów i wskaźnik reklamacji",
      "/kpi/finanzen": "Udział kosztów materiałów i personelu",
      "/kpi/einkauf": "Terminowość dostaw dostawców",
      "/kpi/produktion": "Opóźnienia, zlecenia po terminie",
      "/kpi/bewertung": "Ocena wskaźników, wyprowadzanie, przydzielanie i śledzenie działań",
    },
  },
  personalHub: {
    einleitung:
      "Praca kadrowa, wg obszarów. Liczby są jednym z nich.",
    bereiche: {
      "/hr/kennzahlen": "Załoga, fluktuacja, chorobowe, nadgodziny",
      "/hr/organigramm": "Kto komu podlega",
      "/hr/kompetenzen": "Macierz kwalifikacji wg działu",
      "/hr/schulungen": "Szkolenia obowiązkowe, terminy, dowody",
      "/hr/onboarding": "Nowo zatrudnieni, wdrożenie i procesy",
      "/hr/einarbeitung": "Plany wdrożenia i ich stan",
      "/hr/dokumente": "Tworzenie i drukowanie formularzy, wczytywanie skanów",
      "/hr/zeugnisse": "Pisanie i wydawanie świadectw pracy",
    },
  },
  bewertung: {
    titel: "Ocena KPI i działania",
    einleitung: "Oceniaj wskaźniki, wyprowadzaj działania, przydzielaj je i śledź.",
    uebersichtFehler: (meldung: string) => `Nie udało się wczytać: ${meldung}`,
    nurLesen:
      "Możesz czytać oceny, ale nie możesz ich pisać. Do tego potrzebne jest prawo " +
      "„Edytowanie” w ustawieniach.",
    bubbles: "Dymki",
    bubblesLeer: "Jeszcze nie ma dymków.",
    neu: "nowy",
    alsGesehen: "Oznacz jako obejrzany",
    zumDashboard: "Do pulpitu",
    bubble: (nummer: number) => `Dymek ${nummer}`,
    ohnePosition: "bez położenia na wykresie",
    neueMassnahme: "Nowe działanie",
    kpiWaehlen: "Wybierz KPI…",
    ohneBubble: "— bez dymka —",
    titelPlatzhalter: "Działanie (tytuł)",
    verantwortlichWaehlen: "Odpowiedzialny…",
    anlegen: "Działanie",
    massnahmen: "Działania",
    alleStatus: "Wszystkie statusy",
    statusFilter: "Filtruj według statusu",
    keineMassnahme: "Jeszcze żadnego działania.",
    nichtZugewiesen: "nieprzydzielone",
    spalte: {
      kpi: "KPI",
      massnahme: "Działanie",
      verantwortlich: "Odpowiedzialny",
      faellig: "Termin",
      prioritaet: "Priorytet",
      status: "Status",
      aktionen: "Akcje",
    },
    status: {
      offen: "otwarte",
      laeuft: "w toku",
      erledigt: "załatwione",
      verworfen: "odrzucone",
    },
    prioritaet: {
      niedrig: "niski",
      mittel: "średni",
      hoch: "wysoki",
    },
    ampel: {
      keine: "bez sygnalizacji",
      gruen: "Zielony",
      gelb: "Żółty",
      rot: "Czerwony",
    },
    bereiche: {
      vertrieb: "Sprzedaż",
      einkauf: "Zakupy",
      produktion: "Produkcja",
      qualitaet: "Jakość",
      finanzen: "Finanse",
      personal: "HR",
    },
    verwalten: "Zarządzaj w działaniach →",
    anzahlMassnahmen: (anzahl: number) => `Działań: ${anzahl}`,
  },
  erklaerung: {
    hinweis: "Wyjaśnienie",
    frage: (titel: string) => `Jak liczone jest „${titel}”?`,
    knopf: "Sposób liczenia",
    untertitel: "Tak się to liczy",
    ganzeSeite: "Cała strona pomocy",
  },
};
