import type { Texte } from "@/texte/de";

/**
 * Die ukrainischen Texte der Oberfläche. Maschinell übersetzt — vor dem
 * Ausrollen sollte jemand darüberlesen, der die Sprache spricht.
 */
export const uk: Texte = {
  kopf: {
    benutzermenue: "Меню користувача",
    angemeldetAls: "Ви увійшли як",
    uebersicht: "До огляду",
    hilfe: "Довідка",
    einstellungen: "Налаштування",
    abmelden: "Вийти",
    sprache: "Мова",
    erscheinungsbild: "Оформлення",
    hell: "Світле",
    dunkel: "Темне",
    system: "Як у системі",
    meldungenLeer: "App Feedback — нічого нового",
    meldungen: (anzahl: number) => `App Feedback — ${anzahl} ще не переглянуто`,
    massnahmenLeer: "Заходи — відкритих немає",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Заходи — ${offen} відкритих, з них ${ueberfaellig} прострочених`
        : `Заходи — ${offen} відкритих`,
    navigation: "Навігація",
    einklappen: "Згорнути бічну панель",
    ausklappen: "Розгорнути бічну панель",
    navigationOeffnen: "Відкрити навігацію",
    navigationSchliessen: "Закрити навігацію",
    unterseitenZeigen: (name: string) => `${name}: показати підсторінки`,
    unterseitenVerbergen: (name: string) => `${name}: приховати підсторінки`,
    werkzeuge: "Фільтри та дії",
    werkzeugeEinklappen: "Згорнути панель фільтрів",
    werkzeugeAusklappen: "Розгорнути панель фільтрів",
    werkzeugeOeffnen: "Відкрити фільтри",
    werkzeugeSchliessen: "Закрити фільтри",
    kategorien: {
      navigation: "Навігація",
      ansicht: "Вигляд",
      filter: "Фільтри",
      zeitraum: "Період",
      aktionen: "Дії",
    },
    auchGeoeffnet: (namen: string) => `Також відкрито: ${namen}`,
    konflikt: "Тим часом змінено іншою особою — завантажено актуальний стан.",
    geloeschtVonAnderen: "Тим часом видалено іншою особою.",
  },
  pfad: {
    aria: "Шлях",
    start: "Початок",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "Поставки",
      "/atr/teilekatalog": "Каталог деталей",
      "/einstellungen": "Налаштування",
      "/fair": "FAIR",
      "/hilfe": "Довідка",
      "/hr": "HR",
      "/hr/dokumente": "Обіг документів",
      "/hr/einarbeitung": "Адаптація",
      "/hr/kennzahlen": "Показники",
      "/hr/kompetenzen": "Компетенції",
      "/hr/onboarding": "Онбординг",
      "/hr/organigramm": "Оргструктура",
      "/hr/schulungen": "Навчання",
      "/hr/schulungen/matrix": "Матриця",
      "/hr/schulungen/offen": "Відкриті",
      "/hr/zeugnisse": "Характеристики",
      "/kpi": "Показники",
      "/kpi/bewertung": "Оцінка KPI і заходи",
      "/kpi/einkauf": "Закупівлі",
      "/kpi/finanzen": "Фінанси",
      "/kpi/produktion": "Виробництво",
      "/kpi/qualitaet": "Якість",
      "/kpi/vertrieb": "Збут",
      "/newsletter": "Вісник",
      "/newsletter/redaktion": "Редакція",
      "/platform/feedback": "App Feedback",
      "/produktion": "Виробництво",
      "/qualitaet": "Якість",
      "/sensoren": "Датчики",
      "/signage": "Digital Signage",
      "/signage/devices": "Пристрої",
      "/signage/media": "Медіа",
      "/signage/pair": "Підключення",
      "/signage/playlists": "Плейлисти",
      "/signage/schedules": "Розклади",
      "/uploads": "Завантаження",
    },
  },
  start: {
    titel: "Застосунки",
    verweigert: (name: string) => `Немає дозволу на «${name}».`,
    keineApp:
      "Вашому обліковому запису ще не призначено жодного застосунку. Зверніться до " +
      "адміністрації платформи.",
  },
  anmeldung: {
    benutzer: "Користувач",
    lokalWechseln: "Локальний вхід",
    adWechseln: "Увійти через обліковий запис AD",
    titel: "ACM-Plattform",
    aufforderung: "Увійдіть за своїм обліковим записом.",
    email: "Ел. пошта",
    passwort: "Пароль",
    knopf: "Увійти",
    laeuft: "Вхід …",
  },
  allgemein: {
    laedt: "Завантаження …",
    speichern: "Зберегти",
    abbrechen: "Скасувати",
    loeschen: "Видалити",
    stueck: "шт.",
    loeschenTitel: "Підтвердити видалення",
    loeschenFrage: (was: string) => `«${was}» буде видалено остаточно.`,
    loeschenKnopf: (was: string) => `Видалити ${was}`,
  },
  zeitraum: {
    aria: "Період",
    monat: "Цей місяць",
    quartal: "Цей квартал",
    jahr: "Цей рік",
    alles: "Увесь час",
    frei: "Вибрати період",
    von: "з",
    bis: "по",
    vonAria: "Період з",
    bisAria: "Період по",
    verdreht: "Кінець раніше за початок.",
  },
  vergleich: {
    zu: (was: string) => `порівняно з: ${was}`,
    quartal: (q: number) => `${q}-й квартал`,
    jahr: (j: number) => `${j} рік`,
    keinWert: "Немає значення для порівняння: у періоді порівняння бракує даних або значення дорівнювало нулю.",
    gestiegen: "зросло",
    gesunken: "знизилося",
    unveraendert: "без змін",
  },
  diagramm: {
    art: "Тип діаграми",
    balken: "Стовпці",
    flaeche: "Площа",
  },
  tabelle: {
    suche: "Пошук",
    sucheAria: "Пошук у таблиці",
    sucheLeeren: "Очистити пошук",
    keineTreffer: "За цим запитом нічого не знайдено.",
    leer: "Немає записів.",
    bereich: (von: number, bis: number, gesamt: number) => `${von}–${bis} з ${gesamt}`,
    seite: (seite: number, seiten: number) => `Сторінка ${seite} з ${seiten}`,
    zurueck: "Попередня сторінка",
    weiter: "Наступна сторінка",
    sortieren: (spalte: string) => `Сортувати за «${spalte}»`,
    seitengroesse: "Рядків таблиці на сторінці",
    seitengroesseText: "Діє для всіх таблиць платформи та для всіх користувачів.",
    gespeichert: "Розмір сторінки збережено.",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Дані станом на ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Дані неповні — ${fehlend} ${anzahl === 1 ? "відсутній" : "відсутні"}`,
    heute: "сьогодні",
    gestern: "учора",
    vorTagen: (tage: number) => `${tage} дн. тому`,
    nie: "ніколи",
    arten: {
      umsatz: "Оборот",
      auftraege: "Замовлення",
      angebote: "Пропозиції",
      interessenten: "Потенційні клієнти",
      kontakte: "Контакти",
      liefertreue: "Дотримання термінів постачання",
      lagerbewegungen: "Рух складу",
      materialpreise: "Ціни матеріалів",
      lagerpreise: "Ціни складу",
      auftragspositionen: "Позиції замовлень",
      lieferscheine: "Накладні",
      pruefungen: "Перевірки",
      acht_d: "Звіти 8D",
      wareneingaenge: "Надходження товару",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `Не вдалося завантажити показники: ${meldung}`,
    keineDatenTitel: "За цей період даних немає",
    keineDatenVor: "Завантажте експорти з ERP у розділі ",
    keineDatenNach: " або виберіть ширший період.",
    keineWerte: "у періоді немає значень",
    laedt: "завантаження …",
    jeTag: "за днями",
    jeWoche: "за тижнями",
    jeMonat: "за місяцями",
  },
  vertrieb: {
    umsatz: "Оборот",
    umsatzHinweis: "Рахунки мінус кредит-ноти",
    auftragswert: "Сер. сума замовлення",
    ueberNull: "Замовлення понад 0 €",
    auftraege: "Замовлень усього",
    verlauf: "Динаміка обороту",
    verlaufHinweis: (takt: string) => `${takt}, кредит-ноти відняті`,
    kundenanteil: "Частка клієнтів в обороті",
    kunde: "Клієнт",
    anteil: "Частка",
    uebrige: "Інші",
    jeErfasser: "Замовлення за оформлювачами",
    erfasser: "Оформлювач",
    anzahl: "Замовлення",
    summe: "Сума",
    einzelauftraege: "Окремі замовлення",
    einzelauftraegeHinweis: "Замовлення понад 0 € за період — ті самі, що рахує «Замовлень усього»",
    auftragsNr: "№ замовлення",
    datum: "Дата",
    gesamt: "Разом",
    kundenanteilAuftraege: "Частка клієнтів у замовленнях",
    kundenanteilAuftraegeHinweis: "Суми замовлень за клієнтами",
    kundenanteilRechnungen: "Частка клієнтів у рахунках",
    kundenanteilRechnungenHinweis: "Рахунки мінус кредит-ноти за клієнтами",
    restkunden: (anzahl: number) => `Інші клієнти (${anzahl})`,
    rest: "Інші",
    weitereKunden: (anzahl: number) => `Показати ще ${anzahl}`,
    nurTop3: "Лише топ-3",
    umsatzIn: (zeitraum: string) => `Оборот ${zeitraum}`,
  },
  aktivitaet: {
    titel: "Активність збуту",
    jeWoche: (von: string, bis: string) => `за календарними тижнями, ${von} — ${bis}`,
    ladeFehler: (meldung: string) => `Не вдалося завантажити активність збуту: ${meldung}`,
    leer: "За цей період немає контактів, пропозицій чи потенційних клієнтів.",
    kw: (woche: string) => `Т${woche}`,
    ziel: (wert: string) => `Ціль ${wert} / тиждень`,
    erstkontakte: "Перші контакти",
    erstkontakteHinweis: "завершені контакти типу ERS",
    besuche: "Візити",
    besucheHinweis: "на місці та онлайн окремо",
    besucheOrt: "на місці",
    besucheOnline: "онлайн",
    interessenten: "Потенційні клієнти",
    interessentenHinweis: "нові записи, без прив’язки до збутовика",
    angebote: "Пропозиції",
    angeboteHinweis: "сума виставлених пропозицій",
    auftragseingang: "Надходження замовлень",
    auftragseingangHinweis: "сторно враховано зі знаком мінус",
  },
  einkauf: {
    keineDaten: "За цей період немає позицій постачання",
    ladeVor: "Завантажте експорт дотримання термінів у розділі ",
    ladeNach: ".",
    otd: "Показник OTD",
    otdHinweis: (ziel: string) => `Ціль ${ziel} · вчасно: затримка ≤ 0`,
    puenktlich: "Позицій вчасно",
    gesamt: "Позицій усього",
    verzugSchnitt: "Сер. затримка",
    verzugHinweis: "Без позицій без значення затримки",
    verlauf: "Показник OTD у часі",
    verlaufHinweis: "Прогалини — це періоди без позицій постачання.",
    verlaufTooltip: (positionen: string) => `OTD (${positionen} позицій)`,
    ziellinie: "Ціль",
    ladenhueter: "Замовлення на склад — неліквіди",
    kapital: (wert: string) => `Заморожений капітал: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Складські артикули без руху щонайменше ${tage} дн., найдорожчі спершу. ` +
      "Станом на сьогодні — період угорі тут не діє, бо залишок не є періодом.",
    artikel: "Артикул",
    bezeichnung: "Назва",
    bestand: "Залишок",
    liegtSeit: "Лежить від",
    stueckpreis: "Ціна за од.",
    wert: "Вартість",
    positionen: "Позиції постачання",
    positionenHinweis: "Найбільша затримка спершу, позиції без значення затримки вгорі.",
    auftrag: "Замовлення",
    lieferant: "Постачальник",
    zieltermin: "Планова дата",
    geliefert: "Доставлено",
    verzug: "Затримка",
    menge: "Кількість",
  },
  produktion: {
    keineDaten: "За цей період немає жодного замовлення з відомим результатом",
    ladeVor: "Завантажте позиції замовлень і накладні у розділі ",
    ladeNach: ". Потрібні обидва файли: один несе планову дату, інший — фактичну.",
    quote: "Частка затримок",
    quoteHinweis: (ziel: string) => `Не більше ${ziel}`,
    inVerzug: "Замовлень із затримкою",
    davonOffen: (anzahl: string) => `з них ${anzahl} відкриті й прострочені`,
    gesamt: "Замовлень усього",
    gesamtHinweis: "без відкритих, строк яких не настав",
    verzugSchnitt: "Сер. затримка",
    verzugHinweis: "вчасні замовлення — зі знаком мінус",
    verlauf: "Частка затримок у часі",
    verlaufHinweis: "За плановою датою. Прогалини — це періоди без врахованих замовлень.",
    verlaufTooltip: (auftraege: string) => `Затримка (${auftraege} замовлень)`,
    ziellinie: "Ціль",
    ansicht: "Подання замовлень",
    ansichtVerzug: "Замовлення із затримкою",
    ansichtUeberfaellig: "Прострочені відкриті замовлення",
    hinweisVerzug: "Доставлено після планової дати, найбільша затримка спершу.",
    hinweisUeberfaellig: "Без накладної, строк минув — дні щодня зростають.",
    leerVerzug: "Жодне замовлення цього періоду не доставлено із запізненням.",
    leerUeberfaellig: "Жодне відкрите замовлення цього періоду не прострочене.",
    auftrag: "Замовлення",
    kunde: "Клієнт",
    zieltermin: "Планова дата",
    geliefert: "Доставлено",
    verzug: "Затримка",
    tageUeberfaellig: "Днів прострочення",
  },
  finanzen: {
    keineDatenVor:
      "Потрібні три файли: рух складу для витрати, ціни матеріалів (надходження товару) для цін і оборот як " +
      "база. Усі три лежать у розділі ",
    keineDatenNach: ".",
    materialquote: "Частка витрат на матеріали",
    materialquoteHinweis: "Витрати на матеріали / оборот",
    hoechstens: (ziel: string) => `Не більше ${ziel}`,
    materialkosten: "Витрати на матеріали",
    umsatz: "Оборот",
    personalquote: "Частка витрат на персонал",
    brauchtZeitraum: "потрібен період",
    ohnePreis: "Артикули без ціни",
    ohnePreisHinweis: "витрачені, але не оцінені",
    jeAbteilung: "Витрати на персонал за відділами",
    abteilung: "Відділ",
    personen: "Осіб",
    kosten: "Витрати",
    anteil: "Частка",
    verlauf: "Частка витрат на матеріали у часі",
    verlaufHinweis: "Прогалини — це періоди без обороту: без бази немає і частки.",
    ziellinie: "Ціль",
    verbrauch: "Витрата матеріалів за артикулами",
    verbrauchHinweis: "Найбільші витрати спершу. Артикули без ціни стоять у кінці — вони не входять у частку.",
    artikel: "Артикул",
    bezeichnung: "Назва",
    menge: "Витрата",
    stueckpreis: "Ціна за од.",
    keinPreis: "немає ціни",
    ansicht: "Подання",
    ansichtMaterial: "Матеріали",
    ansichtPersonal: "Персонал",
    personalkosten: "Витрати на персонал",
    personalquoteHinweis: "Витрати на персонал / оборот",
    mitarbeiter: "Працівники",
    mitarbeiterHinweis: "з витратами в періоді",
    personalVerlauf: "Частка витрат на персонал у часі",
    quoteBeiKosten: (kosten: string) => `Частка при витратах ${kosten}`,
  },
  qualitaet: {
    auditart: "Вид аудиту:",
    reklamationsart: "Тип рекламації",
    keineArt: "Не вибрано жодного виду аудиту. Виберіть хоча б один, інакше нема чого рахувати.",
    keineDaten: "За цей період немає невідповідностей аудиту",
    ladeVor: "Завантажте експорт 8D у розділі ",
    ladeNach: ".",
    behoerde: "Орган влади",
    extern: "Зовнішній",
    intern: "Внутрішній",
    kunde: "Клієнт",
    level1: "Невідповідності аудиту рівня 1",
    level2: "Невідповідності аудиту рівня 2",
    ohneLevel: "Без розпізнаного рівня",
    ohneLevelHinweis: "не входить у жодну плитку",
    hoechstens: (ziel: number) => `Не більше ${ziel}`,
    auditVerlauf: "Невідповідності аудиту у часі",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) => `Частка кількості без рекламацій. База: ${bezug}.`,
    fehlerquote: (quote: string) => `Частка дефектів: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Частка дефектів: ${quote} · ціль ${ziel}`,
    reklamiert: "Рекламована кількість",
    bezugsmenge: "Базова кількість",
    bezugsmengeNull: "без неї частки не буде",
    mehrAlsBezogen:
      "Рекламовано більше, ніж отримано. Розрахунок цього не розв’яже: чисельник і " +
      "знаменник походять з різних файлів із власними полями дати. Перевірте, чи повністю " +
      "завантажено базовий файл за цей період.",
    reklKunde: "Клієнт",
    reklIntern: "внутрішні",
    reklLieferant: "Постачальники матеріалів",
    reklWerkbank: "Верстаки",
    bezugKunde: "доставлена кількість",
    bezugIntern: "доставлена кількість",
    bezugLieferant: "надходження товару без послуг",
    bezugWerkbank: "надходження товару товарних груп DIENST і SERVIC",
    mengeGesamt: "заявлена кількість",
    mengeAkzeptiert: "прийнята кількість",
    onQualityBezug: (menge: string) => `On Quality (база ${menge})`,
    ziellinie: "Ціль",
    geprueft: "Перевірені вироби",
    geprueftHinweis: "Кількість на день контролера. Кожен розмір ділиться на дні, коли його перевіряли; разом — на всі.",
    gross: "Великі вироби",
    klein: "Малі вироби",
    mindestens: (ziel: number) => `Щонайменше ${ziel} на день і контролера`,
    buchungen: "Записи контролю якості",
    buchungenHinweis: "Знятий запис лишається в списку, але не входить у жодну плитку.",
    zaehltMit: "Рахується",
    datum: "Дата",
    pruefer: "Контролер",
    produkt: "Виріб",
    groesse: "Розмір",
    menge: "Кількість",
    ausschuss: "Брак",
    mitzaehlen: (datum: string) => `Рахувати запис від ${datum}`,
    klasseGross: "великий",
    klasseKlein: "малий",
    diagnose: "Невідповідності без розпізнаного рівня",
    diagnoseHinweis:
      "Рівень стоїть у вихідному файлі у вільному тексті. Якщо там немає ні «Major … Level 1», " +
      "ні «Minor … Level 2», невідповідність не рахується ніде. Цей список показує, де це " +
      "виправити.",
    bericht: "Звіт",
    art: "Вид",
    adresse: "Адреса",
    bezeichnung: "Назва",
    ansicht: "Вигляд",
    ansichtAudits: "Аудити",
    ansichtReklamationen: "Рекламації",
    ansichtPruefung: "Контроль якості",
    artikelart: "Вид артикула",
    artikelFertig: "Готові вироби",
    artikelHalbfertig: "Напівфабрикати",
    artikelAlle: "Усі артикули",
    gesamt: "Разом",
    pruefVerlauf: (klasse: string) => `${klasse} у часі`,
    personentage: (anzahl: string) => `${anzahl} днів контролерів`,
    findings: "Огляд невідповідностей",
    nr: "№",
    kategorie: "Категорія",
    level: "Рівень",
    aussteller: "Видавець",
    quelle: "Джерело",
    status: "Статус",
    reklListe: (art: string) => `Рекламації · ${art}`,
    akzMenge: "Прийн. к-сть",
    artikel: "Артикул",
  },
  personal: {
    uebersicht: "Огляд",
    keinAbgleich: "Синхронізація ще не виконувалася. Вона запускається щоночі о 02:15.",
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} осіб, ${anwesenheiten} присутностей, ${abwesenheiten} відсутностей`,
    abgleichLaeuft: "виконується …",
    abgleichen: "Синхронізувати зараз",
    keineDaten: "За цей період немає даних про присутність",
    keineDatenHinweis:
      "Або синхронізація Personio ще не виконувалася, або період передує початку обліку.",
    ueberstunden: "Частка понаднормових",
    stundenVon: (teil: string, ganz: string) => `${teil} із ${ganz} год`,
    krankheit: "Частка хвороб",
    krankheitsartenFehlen: "види хвороб не задані",
    fluktuation: "Плинність",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} звільнень, у сер. ${schnitt} працівників`,
    personen: "Облікованих осіб",
    personenHinweis: "з присутністю в періоді",
    krankheitHinweisVor:
      "Частка хвороб лишається порожньою, доки не задано, які види відсутності Personio " +
      "рахуються як хвороба. Задати можна в розділі ",
    krankheitHinweisNach: ".",
    verlauf: "Динаміка",
    reiheUeberstunden: "Понаднормові",
    reiheKrankheit: "Хвороба",
    umsatzJeKopf: "Виручка / працівник виробництва",
    umsatzJeKopfHinweis: (auftraege: string, koepfe: string) => `${auftraege} замовлень ÷ ${koepfe} осіб`,
    produktionFehlt: "виробничі відділи не задано",
    abgleichStand: (datum: string, alter: string) => `Синхронізація Personio ${datum} (${alter})`,
    abgleichFehler: "з помилками",
    reiheUmsatzJeKopf: "Виручка на працівника виробництва",
    ziel: (wert: string) => `Ціль ${wert}`,
  },
  melden: {
    knopf: "Надіслати App Feedback",
    titel: "Надіслати App Feedback",
    frage: "Що на цій сторінці не так? Знімок сторінки додається.",
    abbrechen: "Скасувати",
    senden: "Надіслати",
    sendet: "Надсилання …",
    beispiel: "Наприклад: плитка показує порожнє значення, хоча дані є.",
    beschreibung: "Опис",
    aufnahme: "Знімок сторінки",
    gehtMit: "Цей знімок буде надіслано.",
    nimmtAuf: "Знімок сторінки створюється …",
    misslungen: "Знімок сторінки не вдався — відгук піде без зображення.",
    dankeMitBild: "Дякуємо — відгук надійшов.",
    dankeOhneBild: "Дякуємо — відгук надійшов, без зображення сторінки.",
  },
  belegschaft: {
    titel: "Штат",
    ladeFehler: (meldung: string) => `Не вдалося завантажити дані про штат: ${meldung}`,
    beschaeftigte: "Працівники",
    beschaeftigteHinweis: "за статусом Personio «активний»",
    neuImQuartal: "Нових у кварталі",
    bestand: "Чисельність",
    kompetenzen: "Компетенції заповнено",
    felderFehlen: "поля не задані — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} із ${aktive} за датами прийняття і звільнення`,
    geschlecht: "Стать",
    beschaeftigungsart: "Вид зайнятості",
    abteilungen: "Відділи",
    maennlich: "чоловіча",
    weiblich: "жіноча",
    divers: "інша",
    unbekannt: "невідомо",
    vollzeit: "повна зайнятість",
    teilzeit: "неповна зайнятість",
    geringfuegig: "мінімальна зайнятість",
    extern: "зовнішні",
  },
  mitarbeiter: {
    titel: "Працівники",
    person: "Особа",
    abteilung: "Відділ",
    istStunden: "Факт. год",
    ueberstunden: "Понаднормові",
    quote: "ПН %",
    auswahl: "Вибір",
    mitUeberstunden: "З понаднормовими",
    aktive: "Активні",
    alle: "Усі",
    name: "Ім’я",
    position: "Посада",
    status: "Статус",
    wochenstunden: "Год./тиждень",
    leer: "У цьому виборі нікого немає.",
    statusWert: { active: "активний", inactive: "неактивний", onboarding: "онбординг", leave: "у відпустці" },
  },
  wochenbericht: {
    titel: "Тижневий звіт",
    ladeFehler: (meldung: string) => `Не вдалося завантажити тижневий звіт: ${meldung}`,
    kalenderwoche: "Календарний тиждень",
    kw: (woche: string, jahr: string) => `Т${woche} / ${jahr}`,
    keineDaten: "За цей тиждень немає даних про присутність.",
    saldo: "Сальдо понаднормових",
    saldoHinweis: (personen: string) => `Факт мінус ефективна норма, по всіх ${personen} особах`,
    ueberSoll: "Понад норму",
    ueberSollHinweis: (gesamt: string) => `із ${gesamt} осіб із відмітками`,
    krankheit: "Хвороба",
    tage: "дн.",
    stunden: "год",
    krankheitHinweis: "розподілено по календарних днях відсутності",
    ist: "Факт",
    soll: "Норма",
    saldoSpalte: "Сальдо",
    fussnote:
      "Норма — це ефективна тижнева норма: відпустка і хвороба відняті, хто відсутній без " +
      "пояснення, іде в мінус. У поточному тижні норма рахується лише до останнього " +
      "відміченого дня.",
    diagrammUeberstunden: "Понаднормові за особою",
    diagrammKrankheit: "Хвороба за особою",
    spitzeHinweis: "п’ять найвищих значень тижня",
    keineWerte: "Цього тижня значень немає",
    pdf: "Експортувати як PDF",
    pdfLaeuft: "PDF створюється …",
    seite: (seite: number, gesamt: number) => `Сторінка ${seite} з ${gesamt}`,
    erstellt: (zeitpunkt: string) => `Створено ${zeitpunkt}`,
    einheit: "Одиниця хвороби",
  },
  titel: {
    schulung: "Навчання",
    zeugnis: "Характеристика",
    qualifikationsmatrix: "Матриця кваліфікацій",
    maschine: "Обладнання",
    audit: "Аудит",
    zeichnung: "Креслення",
    lieferung: "Поставка",
    offeneSchulungen: "Відкриті навчання",
    schulungsmatrix: "Матриця навчань",
    atrLieferungen: "Поставки ATR",
    atrTeilekatalog: "Каталог деталей ATR",
    kpiBewertung: "Оцінка KPI і заходи",
    anmelden: "Вхід",
  },
  uploads: {
    dateiWaehlen: "Вибрати файл",
    verarbeitet: "обробляється …",
    uebersprungen: (datei: string) => `Пропущені рядки з «${datei}»`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `Прийнято рядків: ${gesamt}, пропущено: ${fehler}. Решта рядків збережена.`,
    zeile: "Рядок",
    spalte: "Стовпець",
    grund: "Причина",
    zuletzt: "Нещодавно завантажені",
    datei: "Файл",
    art: "Вид",
    zeilen: "Рядки",
    uebersprungenSpalte: "Пропущено",
    status: "Стан",
    zeitpunkt: "Час",
    nochNichts: "Ще нічого не завантажено.",
    keineZeile: (datei: string) => `«${datei}» не містив жодного дійсного рядка.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `«${datei}» прийнято, пропущено рядків: ${fehler}.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `«${datei}» прийнято: ${neu} нових, ${aktualisiert} оновлених.`,
    fehlgeschlagenMeldung: (meldung: string) => `Завантаження не вдалося: ${meldung}`,
    vollstaendig: "повністю",
    teilweise: "частково",
    fehlgeschlagen: "не вдалося",
    arten: {
      umsatz: "Оборот (рахунки і кредит-ноти)",
      umsatzText:
        "Живить плитку обороту і графік обороту. Кредит-ноти стоять у файлі зі знаком мінус.",
      auftraege: "Надходження замовлень",
      auftraegeText:
        "Живить сер. суму замовлення, кількість замовлень і розподіл за оформлювачами.",
      auftragspositionen: "Позиції замовлень",
      auftragspositionenText:
        "Несе планову дату кожної позиції. Разом із накладними з цього виходить затримка.",
      lieferscheine: "Накладні",
      lieferscheineText:
        "Несе фактичну дату постачання. Файл Excel, один рядок на позицію накладної.",
      wareneingaenge: "Надходження товару",
      wareneingaengeText:
        "База частки дефектів на стороні закупівель. Товарна група відділяє постачальників матеріалів від верстаків.",
      acht_d: "Звіти 8D",
      acht_dText:
        "Невідповідності аудитів і рекламації в одному файлі. Рівень невідповідності стоїть у вільному тексті й виводиться під час зчитування.",
      lagerbewegungen: "Рух складу",
      lagerbewegungenText:
        "Витрата на артикул для частки витрат на матеріали. Замінює всі рядки в діапазоні дат файлу.",
      materialpreise: "Ціни матеріалів (надходження товару)",
      materialpreiseText:
        "Ціни для частки витрат на матеріали: для кожного артикула діє найновіше надходження. Оновлює ті самі позиції, додає нові, нічого не видаляє.",
      lagerpreise: "Ціни складських артикулів",
      lagerpreiseText:
        "Основні дані для оцінки складу. Замінює весь прайс-лист, а не лише наявні в ньому артикули.",
      pruefungen: "Контроль якості",
      pruefungenText:
        "Записи перевірок. Замінює всі рядки в діапазоні дат файлу — зняті вручну записи в цьому діапазоні після цього знову рахуються.",
      liefertreue: "Дотримання термінів постачання (закупівлі)",
      liefertreueText:
        "Живить показник OTD у закупівлях. Один рядок на позицію постачання; фактична дата постачання задає період.",
      kontakte: "Контакти (збут)",
      kontakteText:
        "Перші контакти і візити за тижнями. Замінює всі рядки в діапазоні дат файлу — повторне завантаження того самого періоду нічого не подвоює.",
      angebote: "Пропозиції",
      angeboteText:
        "Обсяг пропозицій за тижнями і збутовиками. Пропозиції без оформлювача не потрапляють у жоден стовпчик.",
      interessenten: "Потенційні клієнти",
      interessentenText:
        "Основні дані потенційних клієнтів. Повторно збережений запис переходить із новою датою в інший тиждень.",
    },
  },
  organigramm: {
    suchfeld: "Особа, посада або відділ",
    suchePlatzhalter: "Ім’я, посада, відділ",
    standort: "Локація",
    alleStandorte: "Усі локації",
    personen: (anzahl: number) => `Осіб: ${anzahl}`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} без керівника`,
    niemand: "Нікого не знайдено",
    niemandText: "Інший запит, інша локація — або синхронізація Personio ще не виконувалася.",
    aufklappen: (name: string) => `Розгорнути ${name}`,
    zuklappen: (name: string) => `Згорнути ${name}`,
    direkt: (anzahl: number) => `${anzahl} напряму`,
    treffer: (anzahl: number) => ` · збігів: ${anzahl}`,
    kontext: "У рамці: збіги. Бліді: керівники для контексту.",
  },
  offeneSchulungen: {
    einleitung:
      "Кому чого ще бракує. Лише активні навчання; зняті з обігу тут більше не з’являються.",
    zumKatalog: "До каталогу",
    allesOffene: "Усе відкрите",
    nieAbsolviert: "Ніколи не пройдено",
    ueberfaellig: "Прострочено",
    wirdFaellig: "Наближається строк",
    suchen: "Шукати особу або навчання",
    suchenAria: "Пошук",
    nichtsOffen: "Нічого відкритого",
    nichtsOffenText: "Усі активні навчання в межах періодичності — або ще нічого не зчитано.",
    eintraege: (anzahl: number) => `Записів: ${anzahl}.`,
    person: "Особа",
    schulung: "Навчання",
    bereich: "Напрям",
    zuletzt: "Востаннє",
    faellig: "Строк",
    stand: "Стан",
    nie: "ніколи не пройдено",
    imTurnus: "у межах періодичності",
  },
  schulungsmatrix: {
    einleitung:
      "Усі особи проти всіх навчань — огляд для стенда і для аудиту. Хто ще не має жодної " +
      "участі, стоїть у ній із порожнім рядком; саме це та прогалина, яку шукають.",
    wasOffenIst: "Що відкрито",
    katalog: "Каталог",
    suchfeld: "Особа або відділ",
    suchePlatzhalter: "Ім’я, відділ, табельний номер",
    bereich: "Напрям",
    alleBereiche: "Усі напрями",
    nurLuecken: "Лише особи з прогалинами",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} із ${gesamt} осіб · навчань: ${schulungen}`,
    niemand: "Жодна особа не підходить",
    niemandText: "Інший запит або інший напрям — або справді ні в кого немає відкритого.",
    person: "Особа",
    nichtZugewiesen: (person: string, schulung: string) => `${person} · ${schulung}: не призначено`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (строк ${datum})`,
    offen: "відкрито",
    personio: "Personio",
    externGepflegt: "ведеться зовні",
    ohneTreffer: "без збігу в Personio",
  },
  schulungen: {
    dokumentenlauf: "Обіг документів",
    bereich: "Напрям",
    neueSchulung: "Нове навчання",
    beispiel: "напр., інструктаж із пожежної безпеки",
    anlegen: "Створити",
    wirdGelesen: "Зчитування …",
    uebersichtEinlesen: "Зчитати огляд",
    einlesenAria: "Зчитати огляд навчань",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `Навчань: ${schulungen} (нових: ${neu}), участей: ${teilnahmen}, з них ${zugeordnet} зіставлено з особою в Personio.`,
    ohneTreffer: "Без збігу в Personio: ",
    ohneTrefferNach: ". Ці рядки все одно переносяться з табельним номером і прізвищем.",
    wirdUebernommen: "Застосування …",
    uebernehmen: "Застосувати",
    abbrechen: "Скасувати",
    keineSchulung: "Ще немає навчань",
    keineSchulungText: "Створіть його або зчитайте огляд навчань.",
    schulung: "Навчання",
    turnus: "Періодичність",
    frist: "Строк попередження (дні)",
    verantwortlich: "Відповідальний",
    offen: "Відкрито",
    aktiv: "Активне",
    nichtBerechenbar: "(не обчислюється)",
    zahlGroesserNull: "Введіть число більше за 0.",
    nieKurz: (anzahl: number) => `${anzahl} ніколи`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} прострочено`,
    baldKurz: (anzahl: number) => `${anzahl} незабаром`,
    aktivSchalter: (name: string) => `${name} активне`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} означає: для цієї особи в історії немає жодної дати. ${bald} означає: протягом наступних двох місяців. Станом на ${datum}.`,
  },
  schulungenReg: {
    tabBearbeiten: "Редагувати навчання",
    tabZuweisen: "Призначити навчання",
    tabStand: "Стан працівників",
    anforderungsmatrix: "Матриця вимог",
    ebene: "Рівень",
    matrixLeer: "Ще немає даних для матриці.",
    einzelTitel: "Призначити окреме навчання",
    einzelHinweis: "Доповнює матрицю вимог, що діє на рівні відділу — для окремих осіб.",
    mitarbeiterWaehlen: "Обрати працівника",
    schulungWaehlen: "Обрати навчання",
    zuweisenAktion: "Призначити",
    zugewiesen: "Навчання призначено.",
    schonZugewiesen: "Це навчання вже призначено особі.",
    sammelTitel: "Позначити як проведене (гуртом)",
    sammelHinweis: "Одне навчання, одна дата, кілька учасників. Завершені записи зберігають дату, новіша заміщує її.",
    durchgefuehrtAm: "Проведено",
    teilnehmerSuche: "Пошук учасників",
    standort: "Локація",
    offeneTitel: "Відкриті навчання",
    abteilung: "Відділ",
    frist: "Термін",
    mitarbeiterTitel: "Огляд працівників",
    anzahl: "Кількість",
    naechste: "Наступний термін",
    matrixTitel: "Загальна матриця",
    abteilungenTitel: "Відділи та керівники",
    vorgesetzter: "Відповідальний керівник",
    abteilungenHinweis: "Керівник виводиться з Personio; якщо немає, стовпець лишається порожнім.",
    sammelAktion: (anzahl: number) => `Позначити ${anzahl} як проведені`,
    sammelErfolg: (eingetragen: number, unveraendert: number) =>
      `${eingetragen} внесено${unveraendert ? `, ${unveraendert} без змін` : ""}.`,
    seit: (tage: number) => `${tage} дн. тому`,
    in: (tage: number) => `за ${tage} дн.`,
  },
  schulung: {
    gibtEsNicht: "Такого навчання немає",
    gibtEsNichtText: "Імовірно, його було видалено.",
    ohneTurnus: "без періодичності",
    keineFaelligkeit: " — з цього не обчислити строку",
    zumKatalog: "До каталогу",
    stammdaten: "Основні дані",
    turnus: "Періодичність",
    turnusBeispiel: "напр., щороку",
    turnusHinweis: "Текст; кількість місяців береться зі зчитування.",
    turnusMonate: "Періодичність у місяцях",
    monateHinweis: "Порожньо означає: строк не обчислюється.",
    verantwortlich: "Відповідальний",
    beschreibung: "Опис",
    fuerWen: "Для кого воно обов’язкове?",
    kuerzel: "Код відділу",
    kuerzelHinweis: "Детальна схема з Excel (NÄH, CUT, WVK …).",
    personioAbteilung: "Відділ у Personio",
    personioHinweis: "Узагальнений відділ, як його веде Personio.",
    entfernen: (was: string) => `Видалити ${was}`,
    keine: "немає",
    ergaenzen: (was: string) => `Додати ${was}`,
    hinzufuegen: "Додати",
    teilnahmen: "Участі",
    nochNiemand: "Ще нікого — зчитайте огляд навчань або внесіть когось.",
    person: "Особа",
    abteilungKurz: "Від.",
    erstschulung: "Перше навчання",
    zuletzt: "Востаннє",
    faellig: "Строк",
    stand: "Стан",
    keinTreffer: "Немає збігу в Personio — рядок усе одно зберігається",
    nichtInPersonio: "немає в Personio",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "цю участь",
    personErgaenzen: "Додати особу",
    nameForm: "Прізвище, ім’я",
  },
  kompetenzen: {
    zumDashboard: "До дашборда персоналу",
    bereich: "Напрям",
    wirdGelesen: "Зчитування …",
    einlesen: "Зчитати файл напряму",
    vorschauKopf: (datei: string, bereich: string) =>
      `${datei} — так виглядав би ${bereich} після цього:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `Кваліфікацій: ${qualifikationen}, осіб: ${personen}, оцінок: ${bewertungen}.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `${zugeordnet} із ${personen} осіб знайдено в Personio`,
    platzhalter: (anzahl: number) => `, стовпців-заповнювачів: ${anzahl}`,
    ohneZuordnung: (namen: string) => ` Без зіставлення: ${namen}.`,
    ersetztWarnung:
      "Відповідні аркуші замінюються повністю — внесені тут зміни при цьому втрачаються.",
    wirdUebernommen: "Застосування …",
    uebernehmen: "Застосувати",
    abbrechen: "Скасувати",
    keineMatrix: "Ще немає матриці",
    keineMatrixText: "Зчитайте файл напряму — кожен аркуш у ньому стане матрицею.",
    blatt: "Аркуш",
    titelSpalte: "Назва",
    stand: "Станом на",
    eingelesen: "Зчитано",
    produktion: "Виробництво",
    verwaltung: "Адміністрація",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    bausteineTitel: "Текстові блоки",
    bausteineHinweis: "Одне формулювання на область оцінювання та оцінку. Зберігаються лише зміни; [NAME] і займенники підставляються при формуванні.",
    speichern: "Зберегти",
    gespeichert: "Збережено.",
    note1: "дуже добре",
    note2: "добре",
    note3: "задовільно",
    note4: "достатньо",
    person: "Особа",
    waehlen: "— вибрати —",
    art: "Вид",
    anlegen: "Створити",
    keines: "Ще немає характеристики",
    keinesText: "Виберіть особу і вид характеристики — основні дані підтягнуться самі.",
    zeitraum: "Період",
    note: "Оцінка",
    stand: "Стан",
    angelegt: "Створено",
    fertig: "готово",
    entwurf: "Чернетка",
    qualifiziert: "Розгорнута характеристика",
    einfach: "Проста характеристика",
    zwischenzeugnis: "Проміжна характеристика",
    ausbildungszeugnis: "Характеристика про навчання",
    praktikumszeugnis: "Характеристика про практику",
  },
  einarbeitung: {
    einleitung:
      "Що має вивчити нова особа і хто їй це показує. Бланк постає з пунктів, заданих для " +
      "її відділу.",
    bogenErzeugen: "Створити бланк",
    person: "Особа",
    waehlen: "— вибрати —",
    wirdGebaut: "Формується …",
    einarbeitungsplan: "План адаптації",
    keineInhalte: "Ще немає жодного пункту — бланк лишився б порожнім.",
    abteilungVon: (abteilung: string) => `Відділ ${abteilung}`,
    neuerInhalt: "Новий пункт",
    beispiel: "напр., інструктаж з безпеки на фрезерному верстаті",
    anlegen: "Створити",
    keinInhalt: "Ще немає пунктів",
    keinInhaltText: "Визначте, що має вивчити нова особа — і для яких відділів це діє.",
    inhalt: "Пункт",
    ansprechpartner: "Контактна особа",
    bereich: "Напрям",
    fuerAbteilungen: "Для яких відділів",
    abteilung: "Відділ",
    bereichLeer: "Порожньо означає: узяти відділ із матриці",
    entfernen: (was: string) => `Видалити ${was}`,
    abteilungHinzu: "+ відділ",
    abteilungFuer: (inhalt: string) => `Відділ для ${inhalt}`,
  },
  matrix: {
    bearbeiten: "Редагувати",
    bearbeitenFertig: "Готово",
    ohneKategorie: "Без категорії",
    gibtEsNicht: "Такої матриці немає",
    gibtEsNichtText: "Імовірно, її було замінено.",
    blattStand: (blatt: string) => `Аркуш ${blatt}`,
    stand: (datum: string) => ` · станом на ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · кваліфікацій: ${qualifikationen}, осіб: ${personen}`,
    zurUebersicht: "До огляду",
    qualifikation: "Кваліфікація",
    keineZeilen: "Ця матриця ще не має рядків.",
    stufenBedeuten: "Що означають рівні",
    erfuellungsgradHinweis:
      "Друге число — ступінь виконання у відсотках. Клітинка з вимогою і менш ніж 100 % є " +
      "прогалиною і позначається кольором попередження.",
    ergaenzen: "Додати",
    neueQualifikation: "Нова кваліфікація",
    beispiel: "напр., токарний верстат",
    kategorie: "Категорія",
    ohne: "без",
    zeile: "Рядок",
    neuePerson: "Нова особа",
    namensform: "Ім’я Прізвище",
    spalte: "Стовпець",
    anforderungslevel: "Рівень вимоги",
    erfuellungsgrad: "Ступінь виконання у відсотках",
    stufe0: "не потрібно",
    stufe1: "базові знання",
    stufe2: "може працювати під наглядом",
    stufe3: "працює самостійно",
    stufe4: "може навчати й інструктувати",
  },
  zeugnis: {
    gibtEsNicht: "Такої характеристики немає",
    gibtEsNichtText: "Імовірно, її було видалено.",
    durchschnitt: (wert: string) => ` · середнє ${wert}`,
    zurUebersicht: "До огляду",
    zeugnisVon: (name: string) => `Характеристика ${name}`,
    stammdaten: "Основні дані",
    stammdatenHinweis:
      "Переписані під час створення. Зміни тут діють лише для цієї характеристики — Personio " +
      "лишається недоторканим.",
    name: "Прізвище та ім’я",
    personalnummer: "Табельний номер",
    abteilung: "Відділ",
    taetigkeit: "Посада",
    eintritt: "Прийнято",
    austritt: "Звільнено",
    geburtsdatum: "Дата народження",
    ausstellungsdatum: "Дата видачі",
    ohneNamen: "Без імені не вийде.",
    anrede: "Звертання",
    frau: "Пані",
    herr: "Пан",
    anredeHinweis: "Керує звертанням і займенниками в тексті.",
    art: "Вид",
    anlass: "Підстава",
    anlassBeispiel: "напр., власне бажання",
    fuehrungskraft: "Керівник",
    fuehrungskraftHinweis: "Керівник — вмикає вимір «керівництво»",
    bewertung: "Оцінювання",
    bewertungHinweis:
      "Шкільні оцінки від 1 до 4. Із середнього випливає формула задоволеності — не навпаки.",
    fachwissen: "Фахові знання",
    auffassungsgabe: "Кмітливість",
    arbeitsweise: "Спосіб роботи",
    belastbarkeit: "Стресостійкість",
    arbeitserfolg: "Результати роботи",
    sozialverhalten: "Поведінка в колективі",
    fuehrung: "Керівництво",
    aufgaben: "Завдання (тези)",
    aufgabenHinweis: "Одне завдання на рядок — з цього постане перелік у характеристиці.",
    kompetenzen: "Особливі компетенції",
    kompetenzenHinweis: "Входить в оцінку результатів.",
    erfolge: "Особливі досягнення",
    erfolgeHinweis: "Проєкти, відзнаки, вимірні результати.",
    text: "Текст",
    baut: "Формується …",
    ausBausteinen: "З блоків",
    formuliert: "Формулюється …",
    mitKi: "За допомогою ШІ",
    textHinweis:
      "Конструктор пише без мережі й без ШІ. ШІ формулює вільніше — їй ідуть лише звертання, " +
      "посада, відділ, тривалість, оцінки і вільні тексти вище. Прізвище, дата народження і " +
      "табельний номер сервера не залишають.",
    nochKeinText: "Ще немає тексту. Виставте оцінки і дайте його скласти.",
    fertigSchalter: "Характеристика готова",
    fertigHinweis: "Готово — більше не в роботі",
    unterschriftenFehler: (meldung: string) => `Не вдалося визначити підписи (${meldung}).`,
    darunterSteht: "Підписують",
    fachlich: "Безпосередній керівник",
    personalwesen: "Кадрова служба",
    niemandHinterlegt: "— нікого не задано —",
    unterschriftFehlt:
      "Бракує підпису. Задайте його в Налаштуваннях → Характеристики або внесіть керівника " +
      "в Personio.",
    ausPersonio: "з Personio",
    ausEinstellungen: "з налаштувань",
    nichtHinterlegt: "не задано",
    einleitung: "Вступ",
    taetigkeitsbeschreibung: "Опис обов’язків",
    leistungsbeurteilung: "Оцінка результатів",
    schlussformel: "Прикінцева формула",
    hinweisDeutsch: "Сама характеристика складається німецькою.",
  },
  dokumentenlauf: {
    erstelltAm: "Створено",
    uebergebenAm: "Передано",
    zurueckAm: "Повернуто",
    geprueftAm: "Перевірено",
    aktionen: "Дії",
    einleitung:
      "Бланки з QR-кодом: створити, видати, прийняти заповненими, перевірити. QR прив’язує " +
      "скан назад — незалежно від того, як названо файл.",
    formblatt: "Бланк",
    fuerWen: "Для кого",
    personWaehlen: "— вибрати особу —",
    erzeugt: "Створення …",
    blattErzeugen: "Створити бланк",
    standFilter: "Стан:",
    alle: "Усі",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} із ${gesamt}`,
    keinVorgang: "Немає жодної справи",
    keinVorgangText: "Створіть бланк угорі — він отримає QR-код і відтоді відстежується.",
    person: "Особа",
    kennung: "Код",
    stand: "Стан",
    vollstaendigSpalte: "Повнота",
    blatt: "Бланк",
    scan: "Скан",
    prueft: "Перевірка …",
    scanFuer: (name: string) => `Завантажити скан для ${name}`,
    zu: "закрити",
    details: "Деталі",
    nochNichtGeprueft: "— ще не перевірено",
    vollstaendig: "повний",
    unvollstaendig: "неповний",
    umkehren: "Змінити висновок на протилежний — вимірювання бачить лише, чи є в полі чорнило",
    pruefung: "Перевірка",
    qrGelesen: "— QR прочитано",
    keinQr: "— QR не знайдено, поля не прив’язати",
    nachweise: "Підтвердження",
    keineNachweise: "Ще нічого не додано.",
    welcheZeile: "До якого рядка? (необов’язково)",
    laedt: "Завантаження …",
    nachweis: "Підтвердження",
    nachweisHoch: "Завантажити підтвердження",
    erstellt: "створено",
    uebergeben: "видано",
    zurueck: "повернено",
    geprueft: "перевірено",
    einarbeitungsplan: "План адаптації",
    schulungsnachweis: "Свідчення про навчання",
  },
  onboarding: {
    aktive: "Активні",
    personenwahl: "Які особи",
    eintritteTitel: "Нові працівники",
    inhalteTitel: "Зміст адаптації",
    matrixTitel: "Матриця адаптації",
    matrixHinweis: "Який зміст потрібен якому відділу. Позначка діє одразу.",
    matrixLeer: "Ще немає змісту або відділів.",
    vorgaengeTitel: "Процеси адаптації та навчання",
    matrixZelle: (inhalt: string, abteilung: string) => `${inhalt} – ${abteilung}`,
    nichtsGefehlt: "Нічого не бракувало.",
    angelegt: (anzahl: number) => `Створено навчань: ${anzahl}.`,
    neu90: "Нові (останні 90 днів)",
    alle: "Усі",
    personen: (anzahl: number) => `Осіб: ${anzahl}`,
    keineEintritte: "Немає прийнятих",
    keineEintritteText: "Щойно з Personio надійде хтось із датою прийняття, він з’явиться тут.",
    person: "Особа",
    abteilung: "Відділ",
    position: "Посада",
    eintritt: "Прийнято",
    uebergabe: "Видано",
    nichtInPersonio: "немає в Personio",
    hierGesetzt: "Задано тут — перекриває Personio",
    ausPersonio: "З Personio",
    vermerken: "Відмітити",
    paketTitel: "План адаптації і огляд навчань одним PDF",
    paket: "Пакет",
    uebersichtTitel: "Лише огляд навчань (бланк 71)",
    uebersicht: "Огляд",
    planZu: "Закрити план",
    plan: "План",
    schulungsplan: "План навчання",
    fehlendeAnlegen: "Створити відсутні",
    wirdGerechnet: "обчислюється …",
    bruecke: "Посада → код відділу",
    brueckeHinweis:
      "Місток між Personio і детальним рівнем матриці вимог. Без запису детальний рівень для " +
      "цієї посади не діє — і план тоді прямо про це каже.",
    kuerzel: "Код",
    positionBeispiel: "напр., фрезерувальник ЧПК",
    kuerzelBeispiel: "CNC",
    zuordnen: "Зіставити",
    ohnePersonio: "Особа без Personio",
    ohnePersonioHinweis:
      "Для прийнятих, яких ще немає в синхронізації — або яких там і не має бути.",
    name: "Прізвище та ім’я",
    anlegen: "Створити",
    kuerzelFehlt: (position: string) =>
      `Для посади ${position}не задано коду відділу. Детальний рівень матриці вимог для цієї ` +
      "особи тому не діє — можливо, бракує обов’язкових навчань.",
    matrixVerlangtNichts: "Матриця вимог для цього відділу нічого не вимагає.",
    schulung: "Навчання",
    bereich: "Напрям",
    turnus: "Періодичність",
    pflichtUeber: "Обов’язкове через",
    stand: "Стан",
    ueberAbteilung: "Відділ",
    ueberKuerzel: "Код",
    vorhanden: "є",
    fehlt: "бракує",
  },
  audit: {
    zuKennzahlen: "До показників",
    nummer: "Номер",
    nummerBeispiel: "A-2026-01",
    titel: "Назва",
    titelBeispiel: "Системний аудит EN 9100",
    art: "Вид",
    intern: "внутрішній",
    extern: "зовнішній",
    phasenvorlage: "Шаблон фаз",
    ohne: "без",
    anlegen: "Створити",
    alle: "Усі",
    neuesAudit: "Новий аудит",
    geltungsbereich: "Сфера застосування",
    kategorie: "Категорія",
    leadAuditor: "Провідний аудитор",
    beginnGeplant: "Початок (план)",
    endeGeplant: "Кінець (план)",
    ohneVorlage: "Без шаблону (фази додати пізніше)",
    vorlageHinweis:
      "Фази шаблону копіюються під час створення. Пізніша зміна шаблону не змінює цей аудит.",
    kategoriePflicht: "Виберіть щонайменше одну категорію.",
    zeitraumFehler: "Кінець раніше за початок.",
    angelegt: "Аудит створено.",
    nummerVergeben: "Такий номер аудиту вже існує.",
    keinTreffer: "Жоден аудит не відповідає цьому фільтру.",
    keinAudit: "Ще немає аудиту",
    keinAuditText: "Створіть його — із шаблоном фаз він одразу отримає свій контрольний список.",
    laufen: (laufend: number, gesamt: number) => `${laufend} із ${gesamt} ще тривають.`,
    status: "Статус",
    fortschritt: "Поступ",
    naechsterTermin: "Наступна дата",
    ueberfaellig: (anzahl: number) => `${anzahl} прострочено`,
    geplant: "Заплановано",
    inVorbereitung: "У підготовці",
    inDurchfuehrung: "Виконується",
    berichtet: "Звіт подано",
    massnahmenOffen: "Заходи відкриті",
    abgeschlossen: "Завершено",
    verschoben: "Перенесено",
    abgesagt: "Скасовано",
    phaseOffen: "Відкрито",
    phaseInArbeit: "У роботі",
    phaseErledigt: "Виконано",
    phaseNichtZutreffend: "Не застосовно",
    system: "Система",
    prozess: "Процес",
    produkt: "Виріб",
    lieferant: "Постачальник",
  },
  wartung: {
    zuKennzahlen: "До показників",
    neueMaschine: "Нове обладнання",
    beispiel: "напр., фрезерний верстат 3",
    anlegen: "Створити",
    keineMaschine: "Ще немає обладнання",
    keineMaschineText: "Створіть одиницю обладнання і задайте її завдання з обслуговування.",
    maschine: "Обладнання",
    inventarnummer: "Інвентарний №",
    standort: "Місце",
    verantwortlich: "Відповідальний",
    status: "Статус",
    aktiv: "активне",
    stillgelegt: "виведене з експлуатації",
    angelegt: "Машину створено.",
  },
  sensoren: {
    misst: "Вимірювання …",
    jetztMessen: "Виміряти зараз",
    keinGeraet: "Жодного пристрою не налаштовано",
    keinGeraetText: "Датчики створюються в налаштуваннях — хост, ідентифікатор і community.",
    verlauf: "Динаміка",
    stunden: (n: number) => `${n} год`,
    tage: (n: number) => `${n} дн.`,
    temperatur: "Температура",
    luftfeuchte: "Вологість",
    zuletzt: (zeit: string) => `Востаннє ${zeit}`,
    keinMesswert: "Ще немає жодного вимірювання.",
    nichtsGemessen: "У цьому періоді нічого не вимірювалося.",
    frisch: "актуально",
    verzoegert: "із затримкою",
    offline: "офлайн",
    unbekannt: "ще нічого не виміряно",
    temperaturverlauf: "Температура (°C)",
    feuchteverlauf: "Вологість (%)",
    mittelFuenfMinuten: "Середні за 5 хвилин",
    mittelStunde: "Середні за годину",
    minMax: (fenster: string) => `Мін/макс ${fenster}`,
    ausserhalbGrenzen: "Поза межами",
    untergrenze: "Мін",
    obergrenze: "Макс",
    ladeFehler: "Не вдалося завантажити вимірювання.",
  },
  hilfe: {
    nurDeutsch: "Самі сторінки довідки написані німецькою.",
    suchen: "Шукати в довідці",
    nichtsGefunden:
      "Нічого не знайдено. Якщо чогось у довідці бракує, скажіть про це кнопкою «Надіслати App Feedback» " +
      "внизу праворуч.",
    alleThemen: "← Усі теми",
    navigation: "Теми довідки",
  },
  meldungen: {
    stand: (offen: number) => `${offen} відкрито`,
    neuSeit: (anzahl: number) => ` · ${anzahl} ще не переглянуто`,
    nichtsGemeldet: "Ще немає App Feedback",
    nichtsGemeldetText:
      "Кнопкою «Надіслати App Feedback» внизу праворуч кожна авторизована особа може повідомити, що на сторінці не так.",
    unbekannt: "невідомо",
    status: "Статус",
    offen: "відкрито",
    inBearbeitung: "В роботі",
    erledigt: "виконано",
    meldung: "Відгук",
    aufnahme: "Знімок сторінки",
    ansicht: "Вигляд",
    tabelle: "Таблиця",
    kanban: "Канбан",
    gruppieren: "Групувати за",
    nachStatus: "Статус",
    nachPerson: "Особа",
    nichtZugewiesen: "Не призначено",
    ziehenHinweis: "Перетягніть картки в іншу колонку, щоб змінити статус або відповідальну особу.",
    verschieben: (beschreibung: string) => `Перемістити: ${beschreibung}`,
    spalte: {
      datum: "Дата",
      von: "Від",
      seite: "Сторінка",
      beschreibung: "Опис",
      screenshot: "Знімок",
      status: "Статус",
      zugewiesen: "Призначено",
      aktionen: "Дії",
    },
    oeffnen: "Відкрити",
    ungesehen: "не переглянуто",
    alsGesehen: "Позначити як переглянуте",
    zuDieserSeite: "Відгуки про застосунок для цієї сторінки",
  },
  auditAnsicht: {
    gibtEsNicht: "Такого аудиту немає",
    gibtEsNichtText: "Імовірно, його було видалено.",
    internesAudit: "Внутрішній аудит",
    externesAudit: "Зовнішній аудит",
    prioritaet: (stufe: string) => ` · пріоритет ${stufe}`,
    erledigt: (prozent: number) => ` · виконано ${prozent} %`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} прострочено`,
    zurUebersicht: "До огляду",
    status: "Статус",
    stammdaten: "Основні дані",
    titel: "Назва",
    bereich: "Сфера застосування",
    leitenderAuditor: "Провідний аудитор",
    auditteam: "Команда аудиту",
    geplantVon: "Початок (план)",
    geplantBis: "Кінець (план)",
    prioritaetFeld: "Пріоритет",
    niedrig: "низький",
    mittel: "середній",
    hoch: "високий",
    auditziel: "Мета аудиту",
    kategorien: "Категорії",
    kategorienHinweis:
      "Аудит часто є кількома речами водночас — внутрішня програма охоплює систему і процес " +
      "в одному заході. Тому множинний вибір, а не одне значення.",
    normbezug: "Посилання на стандарт",
    normmatrixLeer: "Матриця стандартів порожня — вона ведеться в налаштуваннях.",
    nichtGeprueft: "* ще не звірено з консолідованим текстом стандарту.",
    phasen: "Фази",
    keinePhasen: "Немає фаз — цей аудит створено без шаблону.",
    phase: "Фаза",
    verantwortlich: "Відповідальний",
    faellig: "Плановий термін",
    erledigtAm: "Фактичний термін",
    phaseErgaenzen: "Додати фазу",
    phaseBeispiel: "напр., повторний аудит",
    verlauf: "Історія",
    verlaufHinweis:
      "Пише база даних, а не ця форма — і потім вона ні змінюється, ні видаляється.",
    nichtsGeschehen: "Ще нічого не сталося.",
    warumEntfaellt: "Чому ця обов’язкова фаза не застосовується?",
    uebernehmen: "Застосувати",
    abbrechen: "Скасувати",
    angelegt: "створено",
    geaendert: "змінено",
    geloescht: "видалено",
    uebersprungen: "пропущено",
    bearbeiten: "Редагувати",
    gespeichert: "Збережено.",
    pflicht: "Обов’язкова",
    kommentar: "Коментар",
    begruendung: "Обґрунтування для «не застосовується»",
    grundPflicht: "Обов’язкову фазу можна пропустити лише з обґрунтуванням.",
    datumPflicht: "Для «виконано» потрібен фактичний термін.",
    phaseSpeichern: "Зберегти фазу",
    phaseGespeichert: "Фазу збережено.",
  },
  maschine: {
    gibtEsNicht: "Такого обладнання немає",
    gibtEsNichtText: "Імовірно, його було видалено.",
    zurUebersicht: "До огляду",
    stammdaten: "Основні дані",
    name: "Назва",
    inventarnummer: "Інвентарний №",
    standort: "Місце",
    hersteller: "Виробник",
    modell: "Модель",
    verantwortlich: "Відповідальний",
    status: "Статус",
    aktiv: "активне",
    stillgelegt: "виведене з експлуатації",
    notizen: "Нотатки",
    wartungsaufgaben: "Завдання з обслуговування",
    jahr: "Рік",
    halbjahr: "Півріччя",
    erstesHalbjahr: "Т 1–26",
    zweitesHalbjahr: "Т 27–52",
    wirdGebaut: "Формується …",
    nachweisbogen: "Бланк обліку",
    neueAufgabe: "Нове завдання",
    aufgabeBeispiel: "напр., перевірити рівень мастила",
    intervall: "Інтервал",
    wochen: "тижнів",
    keineAufgabe: "Ще немає завдань — бланк лишився б порожнім.",
    aufgabe: "Завдання",
    dateien: "Файли",
    planHinterlegen: "Додати план",
    nachweisAblegen: "Додати підтвердження",
    dateienHinweis: "План виробника і відскановані назад підписані бланки.",
    keineDatei: "Ще немає файлів.",
    plan: "План",
    nachweis: "Підтвердження",
    laedt: "Завантаження …",
    taeglich: "Щодня",
    woechentlich: "Щотижня",
    monatlich: "Щомісяця",
    quartalsweise: "Щокварталу",
    alleNWochen: "Кожні N тижнів",
    alleNWochenZahl: (wochen: number) => `Кожні ${wochen} тиж.`,
    bearbeiten: "Редагувати",
    gespeichert: "Збережено.",
    nameFehlt: "Потрібна назва.",
  },
  atr: {
    teilAnlegen: "Створити деталь вручну",
    teilBeispiel: "Номер деталі, напр., VR-1234-56",
    anlegen: "Створити",
    wirdGelesen: "Зчитування …",
    mappeEinlesen: "Зчитати довідкову теку",
    suchen: "Пошук",
    suchePlatzhalter: "Номер деталі, назва або креслення",
    nichtsGefunden: "Нічого не знайдено",
    katalogLeer: "Каталог порожній",
    keinTeil: "Жодна деталь не підходить під цей запит.",
    katalogLeerText: "Зчитайте довідкову теку або створіть деталь вручну.",
    teilenummer: "Номер деталі",
    bezeichnung: "Назва",
    zeichnung: "Креслення",
    gewicht: "Вага кг",
    kategorie: "Категорія",
    bereich: "Розділ",
    lieferungen: "Поставки",
    teilekatalog: "Каталог деталей",
    bearbeiten: "Редагувати",
    speichern: "Зберегти",
    gespeichert: "Збережено.",
    gewichtUngueltig: "Вкажіть вагу числом у кг, напр. 0,44.",
    nichtGespeichert: (meldung: string) => `Не збережено: ${meldung}`,
  },
  lieferungen: {
    wirdGelesen: "Зчитування …",
    einlesen: "Зчитати накладну",
    laeuft: "Виконується …",
    eingangDurchsehen: "Переглянути вхідні",
    berichtNummer: (nr: string) => ` · № ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `Позицій: ${positionen}, знайдено в каталозі: ${zugeordnet}.`,
    keinLieferschein: "Ще немає накладних",
    keinLieferscheinSchreiben: "Зчитайте PDF накладної — після цього вона чекає тут на перегляд.",
    keinLieferscheinLesen: "Щойно накладну зчитано, вона з’являється тут.",
    lieferschein: "Накладна",
    datum: "Дата",
    programm: "Програма",
    msn: "MSN",
    status: "Статус",
    entwurf: "Чернетка",
    erzeugt: "створено",
    abgelegt: "передано",
    atrNummer: "№ ATR",
    containernummer: "Номер контейнера",
    erstellt: "Створено",
    auswaehlen: (nr: string) => `Вибрати поставку ${nr}`,
    ausgewaehlt: (anzahl: number) => `Вибрано: ${anzahl}`,
    auswahlAufheben: "Скасувати вибір",
    containerbeschriftung: "Створити етикетку контейнера",
    containerFrage: "Номер контейнера для вибраних поставок:",
    containerHinweis: "Етикетка показує всі поставки цього контейнера — також ті, що були в ньому раніше.",
    containerErstellt: (nr: string) => `Призначено контейнер ${nr} – етикетка завантажується`,
    erstellen: "Створити",
  },
  durchsicht: {
    nichtGefunden: "Поставку не знайдено.",
    wirdErzeugt: "Створення …",
    dokumenteErzeugen: "Створити документи",
    kopfdaten: "Дані шапки",
    atrNummer: "Номер ATR",
    containernummer: "Номер контейнера",
    satzTitel: "Назва комплекту",
    programm: "Програма",
    msn: "MSN",
    bereich: "Напрям",
    wiegedatum: "Дата зважування",
    pruefdatum: "Дата перевірки",
    qsUnterschrift: "Підпис ВТК",
    hoechstgewicht: "Макс. вага кг",
    positionen: "Позиції",
    pos: "Поз.",
    menge: "К-ть",
    seriennummern: "Серійні номери",
    nichtImKatalog: "немає в каталозі",
    poNummer: "Номер PO",
    poPos: "PO Pos",
    speichern: "Зберегти",
    gespeichert: "Збережено.",
    aufServerSpeichern: "Зберегти на сервері",
    wirdAbgelegt: "Збереження …",
    aufServerGespeichert: "Збережено на сервері.",
    ablageGescheitert: (ziele: string) => `Не збережено: ${ziele}`,
    seriennummernAbweichung: (anzahl: number, menge: number) =>
      `${anzahl} серійн. номер(ів) при кількості ${menge}`,
    seriennummernFeld: (pos: string) => `Серійні номери позиції ${pos}`,
  },
  fair: {
    dateiFehlt: (meldung: string) =>
      `Саме креслення не завантажується (${meldung}). Розміри все одно наведені нижче.`,
    bezeichnungFrei: "Назва (порожньо = ім’я файлу)",
    beispiel: "напр., вал 12×40, креслення 4711",
    wirdGeladen: "Завантаження …",
    zeichnungWaehlen: "Вибрати креслення",
    keineZeichnung: "Ще немає креслень",
    keineZeichnungSchreiben: "Завантажте PDF або зображення — після цього розміри можна балонувати.",
    keineZeichnungLesen: "Щойно креслення завантажено, воно з’являється тут.",
    bezeichnung: "Назва",
    teilenummer: "Номер деталі",
    kunde: "Клієнт",
    hochgeladen: "Завантажено",
    pruefliste: "Список перевірки",
    einMass: "1 розмір",
    masse: (anzahl: number) => `Розмірів: ${anzahl}`,
    kopieren: "Копіювати",
    csv: "CSV",
    keinMass: "Ще не позначено жодного розміру.",
    nr: "№",
    seite: "Сторінка",
    wert: "Значення",
    wertBeispiel: "напр., 12,0 h7",
    wertZu: (nummer: number) => `Значення до номера ${nummer}`,
    nachOben: (nummer: number) => `Номер ${nummer} вище`,
    nachUnten: (nummer: number) => `Номер ${nummer} нижче`,
    nummer: (nummer: number) => `Номер ${nummer}`,
    drehen: "Повернути вигляд",
    verkleinern: "Зменшити",
    vergroessern: "Збільшити",
    einpassen: "Вписати",
    darstellung: "Відображення",
    bubbleGroesse: "Розмір бульбашок",
    zeichnung: "Креслення",
    ladefehler: "Не вдалося завантажити креслення.",
    alleKunden: "Усі клієнти",
    ohneKunde: "Без клієнта",
    kundenfilter: "Фільтр за клієнтом",
    artikelnummer: "Арт. №",
    artikelnummerLang: "Номер артикула",
    pn: "P/N",
    bubblesKleiner: "Менші бульбашки",
    bubblesGroesser: "Більші бульбашки",
    pdf: "PDF",
    pdfExport: "Експортувати PDF",
    pdfWirdErstellt: "PDF створюється …",
    pdfFehler: (meldung: string) => `Не вдалося створити PDF: ${meldung}`,
    ocrNeu: "Перезапустити OCR для цього рядка",
    ocrLeer: "Нічого не розпізнано — введіть значення вручну.",
    ocrFehler: (meldung: string) => `OCR не вдалося: ${meldung}`,
    ocrGleich: "OCR зчитує те саме значення.",
    ocrErsetzenTitel: "Замінити значення?",
    ocrErsetzen: (nummer: number, alt: string, neu: string) => `Номер ${nummer}: замінити «${alt}» на «${neu}»?`,
    ersetzen: "Замінити",
    ziehen: (nummer: number) => `Перетягніть номер ${nummer}, щоб перемістити`,
    nurNummernfolge: "Переміщення можливе лише в порядку номерів — без пошуку й без сортування за сторінкою чи значенням.",
  },
  newsletter: {
    keineAusgabe: "Ще немає випусків",
    keineAusgabeText: "Щойно редакція опублікує випуск, він з’явиться тут.",
    zurRedaktion: "До редакції",
    quartalJahr: (quartal: number, jahr: number) => `Квартал ${quartal} · ${jahr}`,
    entwurfSuffix: " · чернетка",
    ausgabe: "Випуск",
    quartalKurz: (quartal: number, jahr: number) => `${quartal} кв. ${jahr}`,
    entwurfKlammer: " (чернетка)",
    alsPdf: "Як PDF",
    wirdGesetzt: "Верстання …",
    seiteVon: (nr: number, gesamt: number) => `Сторінка ${nr} з ${gesamt} …`,
    redaktion: "Редакція",
    niemandDazu: "Цього кварталу ніхто не долучився.",
    beitraege: "Матеріали",
    belegschaftInZahlen: "Штат у цифрах",
    neuBeiUns: "Нові в команді",
    zurLeseransicht: "До читацького вигляду",
    jahr: "Рік",
    quartal: "Квартал",
    ausgabeAnlegen: "Створити випуск",
    ausgabeBearbeiten: "Редагувати випуск",
    keineAusgabeRedaktion: "Виберіть рік і квартал і створіть — після цього тут постануть розділи.",
    titelDerAusgabe: "Назва випуску",
    status: "Статус",
    entwurf: "Чернетка",
    veroeffentlicht: "опубліковано",
    titelbild: "Обкладинка",
    rueckseite: "Зворот",
    ersetzen: " замінити",
    waehlen: " вибрати",
    ausgabeLoeschen: (quartal: number, jahr: number) => `Випуск ${quartal} кв. ${jahr}`,
    neuesKapitel: "Новий розділ",
    kapitelBeispiel: "напр., З виробництва",
    art: "Вид",
    hinzufuegen: "Додати",
    kapiteltitel: "Назва розділу",
    kapitelHoch: "Розділ вище",
    kapitelRunter: "Розділ нижче",
    ueberschrift: "Заголовок",
    eintrag: "Матеріал",
    textMarkdown: "Текст. Markdown дозволено — **жирний**, списки, таблиці.",
    text: "Текст",
    bild: "Зображення",
    bildGroesse: (nr: number) => `Розмір зображення ${nr}`,
    nieEingefroren: "Ще нічого не зафіксовано — розділ лишиться в номері порожнім.",
    kpiEingefroren: "Дані про штат за квартал зафіксовано.",
    niemandEingefroren: "Зафіксовано — цього кварталу ніхто не долучився.",
    zugaengeEingefroren: (anzahl: number) => `Зафіксовано: нових у кварталі — ${anzahl}.`,
    einfrieren: "Зафіксувати",
    neuEinfrieren: "Зафіксувати наново",
    rechtFehlt: (quelle: string) => `Для цього бракує права в джерелі: переглядати ${quelle}.`,
    quelleKpi: "показники",
    quellePersonal: "персонал",
    ausgabeAngelegt: "Випуск створено.",
    ausgabeGeloescht: "Випуск видалено.",
    kapitelAngelegt: "Розділ створено.",
    standEingefroren: "Стан зафіксовано.",
  },
  signage: {
    bereiche: "Розділи Signage",
    medien: "Медіа",
    medienHinzu: "Додати медіа",
    playlists: "Плейлисти",
    zeitplaene: "Розклади",
    geraete: "Пристрої",
    dateiZiehen: "Перетягніть файл сюди",
    dateiWaehlen: "Вибрати файл",
    dateiHinweis: "Зображення, відео, PDF або PPTX, до 50 МБ",
    wirdUebertragen: "передавання …",
    art: "Вид",
    webseite: "Вебсторінка (URL)",
    htmlSchnipsel: "Фрагмент HTML",
    titel: "Назва",
    titelBeispiel: "Дні народження",
    urlHinweis:
      "Вкажіть повну адресу. Плеєр працює на власному порту, відносні шляхи там не працюють.",
    aufnehmen: "Додати",
    medienFehler: "Не вдалося завантажити медіа.",
    keineMedien: "Ще немає медіа",
    keineMedienText:
      "Завантажте файл або додайте URL. Далі медіа можна зібрати в плейлисти.",
    erneut: "ще раз",
    inVerwendung: "Медіафайл використовується",
    inVerwendungText: (titel: string, anzahl: number) =>
      `«${titel}» ще входить у ${anzahl} плейлист(ів). Спершу приберіть його звідти.`,
    verstanden: "Зрозуміло",
    wartet: "очікує",
    konvertiert: "конвертується",
    fertig: "готово",
    fehlgeschlagen: "не вдалося",
    keineHeartbeats: "Сигналів ще не записано.",
    nieGesehen: "ніколи не бачено",
    online: "онлайн",
    vorMinuten: (minuten: number) => `${minuten} хв тому`,
    offline: "офлайн",
    entzogen: "відкликано",
    keinGeraet: "Ще не підключено жодного пристрою",
    keinGeraetText:
      "Запустіть екран із плеєром. Він покаже шестизначний код, який ви вводите тут.",
    geraetKoppeln: "Підключити пристрій",
    geraet: "Пристрій",
    status: "Статус",
    verfuegbarkeit: "Доступність 24 год",
    ausfaelle: "Збої 24 год",
    tags: "Теги",
    playlist: "Плейлист",
    zuletztGesehen: "Востаннє бачено",
    seiteNeuLaden: "Перезавантажити сторінку",
    neuStarten: "Перезапустити пристрій",
    bearbeiten: "Редагувати",
    zugangEntziehen: "Відкликати доступ",
    geraetBearbeiten: "Редагувати пристрій",
    name: "Назва",
    bilddrehung: "Поворот зображення",
    ton: "Звук",
    tonAktiv: "Звук увімкнено",
    abbrechen: "Скасувати",
    speichern: "Зберегти",
    tagsHinweis: "Вони визначають, які плейлисти і розклади отримує цей пристрій.",
    entziehenText: (name: string) =>
      `«${name}» одразу втрачає доступ і знову показує код підключення.`,
    neustartText: (name: string) => `«${name}» приблизно хвилину буде чорним.`,
    geraetGespeichert: "Пристрій збережено.",
    geraetGeloescht: "Пристрій видалено.",
    keinGeraetGewaehlt: "пристрій не вибрано",
    neuePlaylist: "Новий плейлист",
    neuePlaylistText: "Задайте назву і цільові теги. Записи додаються на наступному кроці.",
    namensbeispiel: "Приймальня",
    keinePlaylist: "Ще немає плейлистів",
    keinePlaylistText:
      "Плейлист об’єднує медіа в певному порядку і розподіляється на пристрої через теги.",
    playlistAnlegen: "Створити плейлист",
    aktiv: "Активний",
    erstellt: "Створено",
    kopieren: "Копіювати",
    playlistGeloescht: "Плейлист видалено.",
    playlistKopiert: "Плейлист скопійовано. Записи не копіюються.",
    playlistInPlan: "Плейлист має активні розклади",
    zeitplanHinweis:
      "Розклад має перевагу над простим призначенням за тегами. Вікна через північ " +
      "розділяйте на два розклади.",
    wochentage: "Дні тижня",
    wochentagKuerzel: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд"],
    von: "З",
    bis: "По",
    prioritaet: "Пріоритет",
    zeitplanAktiv: "Розклад активний",
    keineZeitplaene: "Немає розкладів",
    keineZeitplaeneText:
      "Без розкладу лише призначення за тегами вирішує, який плейлист показує пристрій. " +
      "Розклад ставить плейлист попереду в певні дні й години.",
    tage: "Дні",
    zeitfenster: "Часове вікно",
    aktionen: "Дії",
    zeitplanBearbeiten: "Редагувати розклад",
    neuerZeitplan: "Новий розклад",
    zeitplaeneFehler: "Не вдалося завантажити розклади.",
    endeNachStart: "Кінець має бути після початку. Через північ створіть, будь ласка, два розклади.",
    mindestensEinTag: "Виберіть щонайменше один день тижня.",
    playlistWaehlen: "Виберіть плейлист.",
    taeglich: "щодня",
    zielTags: "Цільові теги",
    ueberblenden: "Плавний перехід",
    harterSchnitt: "Різка зміна",
    ziehpunkt: "Маркер перетягування",
    verwerfen: "Відхилити",
    medienHinzufuegen: "Додайте медіа і впорядкуйте їх маркером перетягування.",
    mediumWaehlen: "Вибрати медіафайл",
    mediumHinzufuegen: "Додати медіафайл",
    mediumWaehlenText: "Вибраний медіафайл додається в кінець плейлиста.",
    schliessen: "Закрити",
    keineMedienAnlegen: "Медіа ще немає. Спершу створіть їх у розділі «Медіа».",
    unbekanntesMedium: "невідомий медіафайл",
    playlistGespeichert: "Плейлист збережено. Пристрої одразу перезавантажуються.",
    kopplungscode: "Код підключення",
    codeBeispiel: "ABC-123",
    geraetename: "Назва пристрою",
    geraeteBeispiel: "Приймальня ліворуч",
    tagsPflicht: "Через теги пристрій отримує свій плейлист. Без тега екран лишається порожнім.",
    koppeln: "Підключити",
    formatErwartet: "Очікується формат XXX-XXX.",
    codeUnbekannt: "Код невідомий, прострочений або вже використаний. Покажіть новий на екрані.",
    tagEingeben: "Введіть тег і натисніть Enter",
  },
  einstellungen: {
    titel: "Налаштування",
    bereiche: "Розділи",
    gruppen: {
      kennzahlen: "Показники",
      kennzahlenText:
        "Цільові значення дашбордів. Вони з’являються як лінія цілі в динаміці й вирішують, " +
        "з якого моменту плитка попереджає.",
      personal: "HR",
      personalText:
        "Які відсутності рахуються як хвороба і які відділи належать до виробництва. Без цих " +
        "списків показники персоналу лишаються порожніми.",
      atr: "ATR",
      atrText:
        "Що однакове в кожному документі програми і звідки надходять накладні.",
      qualitaet: "Якість",
      qualitaetText:
        "Матриця стандартів, на яку посилається аудит, і шаблони фаз, які новий аудит " +
        "отримує як контрольний список.",
      sensoren: "Датчики",
      sensorenText:
        "Вимірювальні пристрої в мережі: де вони стоять, під яким ідентифікатором дають " +
        "температуру і вологість і з якого значення воно вважається зависоким.",
      zeugnisse: "Характеристики",
      zeugnisseText:
        "Що однакове в кожній характеристиці: фірма, місто і два підписи. Фаховий " +
        "визначається з Personio під час створення — тут стоїть лише запасний варіант.",
      erscheinung: "Оформлення",
      erscheinungText:
        "Логотип фірми — угорі ліворуч у застосунку і в шапці кожного створеного файлу: план " +
        "адаптації, підтвердження обслуговування, огляд навчань, характеристика.",
      anzeigen: "Екрани",
      anzeigenText:
        "Адреси, що працюють на екранах у будівлі. Кожна несе підписаний токен, діє лише для " +
        "свого екрана і має строк.",
      email: "Електронна пошта",
      emailText:
        "З якого облікового запису Microsoft 365 платформа надсилає нагадування та звіти. Нічого не надсилається без явної дії.",
      ad: "Active Directory",
      adText: "Вхід у локальний AD через LDAPS. compute перевіряє пароль під час входу та віддзеркалює групи AD; адміністратор надає права застосунків для кожної групи.",
      zugaenge: "Користувачі та групи",
      zugaengeText:
        "Створювати осіб, формувати групи і давати їм права на застосунки. Зміни діють, " +
        "щойно відповідна особа наступного разу ввійде — права стоять у її токені.",
    },
  },
  einstellungenText: {
    appName: "Назва застосунку",
    appNameHinweis:
      "Показується в шапці без логотипа, у заголовку сторінки та на сторінці входу.",
    farbrollen: "Ролі кольорів",
    farbrollenHinweis:
      "Основний колір несе фокус, посилання, головну кнопку й основну серію діаграм; текст лежить зверху. Окремо для світлої та темної теми.",
    hellTitel: "Світла",
    dunkelTitel: "Темна",
    hauptfarbe: "Основний колір",
    textAufHauptfarbe: "Текст на основному кольорі",
    kontrastTitel: "Недостатній контраст (WCAG 2.2)",
    kontrastZeile: (thema: string, bereich: string, verhaeltnis: string, mindestens: string) =>
      `«${bereich}» (${thema}): контраст ${verhaeltnis}:1, потрібно ${mindestens}:1`,
    kontrastBereiche: {
      linkSeite: "Посилання на сторінці",
      linkKarte: "Посилання на картках",
      fokusFlaeche: "Фокус на сірій поверхні",
      diagramm: "Колір діаграми",
      knopfText: "Текст на головній кнопці",
    },
    farbenGespeichert: "Кольори збережено. Діють після перезавантаження.",
    farbenAufVorgabe: "Повернуто до типових.",
    farbenZuruecksetzen: "Повернути до типових",
    email: {
      titel: "Надсилання пошти (Microsoft 365)",
      einleitung:
        "Центральна служба для нагадувань і звітів через Microsoft Graph.",
      ohneSchluessel:
        "На сервері не задано GEHEIM_SCHLUESSEL. Доки його немає, жоден секрет не зберігається.",
      gespeichert: "Збережено.",
      speichert: "Збереження …",
      speichern: "Зберегти",
      speichernFehler: (meldung: string) => `Не вдалося зберегти: ${meldung}`,
      modus: "Режим",
      modusApp: "Дозвіл застосунку",
      modusDelegiert: "Власний обліковий запис (делегований)",
      modusAppHinweis: "Надсилає через обліковий запис застосунку з дозволом Mail.Send; потрібні секрет клієнта та згода адміністратора.",
      modusDelegiertHinweis: "Надсилає від імені особи, що ввійшла, після входу за кодом пристрою; згода адміністратора не потрібна.",
      tenantId: "Ідентифікатор Tenant",
      clientId: "Ідентифікатор клієнта",
      clientSecret: "Секрет клієнта",
      secretGesetzt: "збережено — залиште порожнім, щоб зберегти",
      absender: "Адреса відправника",
      absenderName: "Ім’я відправника (необов’язково)",
      aktivieren: "Надсилання ввімкнено",
      testTitel: "Тестовий лист",
      testHinweis: "Надсилає повідомлення на введену адресу. Лише ця дія щось надсилає.",
      testEmpfaenger: "Одержувач",
      testSenden: "Надіслати тестовий лист",
      testLaeuft: "Надсилання …",
      testOk: "Тестовий лист надіслано.",
      testFehler: "Не вдалося надіслати.",
      delegiertTitel: "Вхід через Microsoft",
      delegiertAnmelden: "Увійти через Microsoft",
      delegiertAnleitung:
        "Відкрийте адресу, введіть код і ввійдіть власним обліковим записом Microsoft 365.",
      delegiertWartet: "Очікування входу …",
      verbundenMit: (konto: string) => `Увійшли як ${konto}`,
      trennen: "Від’єднати",
      getrennt: "Від’єднано.",
    },
    speichernFehler: (meldung: string) => `Збереження не вдалося: ${meldung}`,
    zielwertGespeichert: "Цільове значення збережено. Дашборди покажуть його після перезавантаження.",
    zahlAbNull: "Введіть число від 0.",
    personalGespeichert: "Збережено. Дашборд персоналу покаже це після перезавантаження.",
    krankTypen: "Види відсутності, що рахуються як хвороба",
    produktionAbteilungen: "Відділи виробництва",
    kompetenzAttribute: "Поля Personio, що рахуються як заповнена компетенція",
    ausDemBestand: "із наявних даних",
    abteilungenBeispiel: "Виробництво, Монтаж",
    firmenlogo: "Логотип фірми",
    anzeigenHinweis:
      "Створює адресу для запису плейлиста в плеєрі Signage. Вона діє лише для вибраного " +
      "екрана і має строк — запис, який більше ніхто не веде, сам собою перестає " +
      "показуватися.",
    logoHinweis:
      "Стоїть угорі ліворуч у застосунку і в шапці кожного створеного бланка — план " +
      "адаптації, підтвердження обслуговування, огляд навчань, характеристика. PNG, JPEG або SVG, " +
      "щонайбільше 5 МБ. Якщо нічого не задано, там стоїть напис «ACM-Plattform».",
    communityHinweis: "зберігається зашифровано і більше ніколи не показується",
    verwaltenSchliesstEin: "«Керувати» на плитці платформи включає будь-яке інше право.",
    logoAlt: "Заданий логотип фірми",
    keinsHinterlegt: "Ще нічого не задано.",
    laedt: "Завантаження …",
    ersetzen: "Замінити",
    hochladen: "Завантажити",
    logoHochladen: "Завантажити логотип фірми",
    logoHinterlegt: "Логотип задано.",
    anzeige: "Екран",
    geburtstage: "Дні народження тижня",
    neuzugaenge: "Нові в команді",
    gueltigTage: "Діє (днів)",
    erzeugt: "Створення …",
    adresseErzeugen: "Створити адресу",
    adresseKopiert: "Адресу скопійовано.",
    kopierenFehler: "Скопіювати не вдалося — позначте, будь ласка, вручну.",
    kopieren: "Копіювати",
    gespeichert: "Збережено.",
    speichern: "Зберегти",
    speichert: "Збереження …",
    firma: "Фірма",
    ort: "Місто (над датою)",
    nameRueckfall: "Прізвище (запасне)",
    titelRueckfall: "Посада (запасна)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "Профіль видавця",
    ausstellerHinweis:
      "Стоїть на кожній характеристиці. Бланк листа ACM використовується, щойно «ACM» є в " +
      "назві фірми.",
    linkeUnterschrift: "Лівий підпис — фаховий",
    linkeHinweis:
      "Зазвичай керівник особи; він визначається з Personio під час створення. Те, що стоїть " +
      "тут, діє лише тоді, коли Personio нічого не дає — наприклад, для осіб, яких ведуть " +
      "зовні.",
    rechteUnterschrift: "Правий підпис — кадрова служба",
    rechteHinweis:
      "Для всіх характеристик однаковий. Прив’язаний до особи з Personio, посада береться " +
      "звідти і лишається правильною, коли посада змінюється.",
    personAusPersonio: "Особа з Personio",
    keinePerson: "— нікого, використати вільний текст нижче —",
    personenFehler: (meldung: string) => `Не вдалося завантажити список осіб (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "Шаблони",
    vorlagenHinweis:
      "Один шаблон на програму. Дані шапки і файл-каркас однакові в кожному документі ATR " +
      "цієї програми. Шаблон створюється під час зчитування довідкової теки в каталозі " +
      "деталей.",
    keineVorlage: "Ще немає шаблонів",
    keineVorlageText: "Зчитайте довідкову теку — програма стоїть там у клітинці D2.",
    geruestHinterlegt: "Файл-каркас задано.",
    geruestErsetzen: "Замінити каркас",
    geruestWaehlen: "Вибрати каркас",
    keineHinterlegt: "ще нічого не задано",
    kunde: "Клієнт",
    lieferant: "Постачальник",
    arbeitspaket: "Робочий пакет",
    referenz: "Посилання",
    bestellerSpez: "Специфікація замовника",
    lieferantenSpez: "Специфікація постачальника",
    kundenSpez: "Специфікація клієнта",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "Розділ ATA",
    waage: "Ваги",
    qsUnterschrift: "Підпис ВТК",
    eingangsordner: "Тека вхідних",
    eingangHinweis:
      "Накладна у вхідній папці зчитується, стає поставкою і переходить в архів. Дозволені сервери задає ATR_SMB_ERLAUBT. Пароль, введений тут, має перевагу над ATR_SMB_PASSWORT із середовища.",
    laeuft: "працює",
    aus: "вимкнено",
    zuletzt: (zeit: string, text: string) => `Востаннє ${zeit}: ${text}`,
    nochNichtGelaufen: "Ще не запускалося.",
    prueft: "Перевірка …",
    verbindungPruefen: "Перевірити зв’язок",
    laeuftGerade: "Виконується …",
    jetztDurchsehen: "Переглянути зараз",
    verbindungSteht: (dateien: number) => `Зв’язок є. У вхідних чекає файлів: ${dateien}.`,
    keineVerbindung: (meldung: string) => `Немає зв’язку: ${meldung}`,
    unbekannt: "невідомо",
    gelesenAngelegt: (gelesen: number, angelegt: number) =>
      `Прочитано: ${gelesen}, створено: ${angelegt}.`,
    rechner: "Хост",
    rechnerHinweis: "має бути в ATR_SMB_ERLAUBT",
    freigabe: "Спільний ресурс",
    domaene: "Домен",
    benutzer: "Користувач",
    eingang: "Вхідні",
    ausgang: "Вихідні",
    archiv: "Архів",
    wasEinLaufTut: "Що робить прогін",
    entwurfAnlegen: "Створити чернетку на перегляд",
    dokumenteErzeugen: "Створити документи і покласти їх",
    intervall: "Інтервал сканування (секунди, 0 = вимк.)",
    intervallUngueltig: "Інтервал — ціле число від 0.",
    passwort: "Пароль службового облікового запису",
    passwortHinterlegt: "збережено — залиште порожнім, щоб не змінювати",
    passwortUmgebung: "із середовища (ATR_SMB_PASSWORT) — запис тут має перевагу",
    passwortFehlt: "ще не збережено",
    passwortOhneSchluessel: "У середовищі немає GEHEIM_SCHLUESSEL — без нього пароль не зберегти.",
    speichern: "Зберегти",
    gespeichert: "Збережено.",
  },
  qualitaetEinstellungen: {
    normmatrix: "Матриця стандартів",
    normmatrixHinweis:
      "Пункти, на які посилається аудит. Використовуваний стандарт видалити не можна — його " +
      "виводять з обігу, інакше аудит тихо втратив би свою основу.",
    schonInMatrix: "Цей пункт уже є в матриці.",
    regelwerk: "Звід правил",
    revision: "Редакція",
    klausel: "Пункт",
    kurztext: "Короткий текст",
    kurztextBeispiel: "Внутрішній аудит",
    aufnehmen: "Додати",
    geprueft: "Звірено",
    aktiv: "Активний",
    geprueftSchalter: (norm: string) => `${norm} звірено`,
    aktivSchalter: (norm: string) => `${norm} активний`,
    phasenvorlagen: "Шаблони фаз",
    phasenvorlagenHinweis:
      "Послідовність кроків, яку отримує новий аудит. Вона копіюється під час створення — " +
      "пізніша зміна не переписує жодної історії.",
    neueVorlage: "Новий шаблон",
    vorlageBeispiel: "Системний аудит, стандарт",
    anlegen: "Створити",
    schritte: (anzahl: number) => `Кроків: ${anzahl}`,
    schrittErgaenzen: "Додати крок",
    schrittBeispiel: "напр., вступна нарада",
  },
  personioZugang: {
    taktGespeichert: "Інтервал збережено.",
    abgleichTitel: "Синхронізація",
    abgleichHinweis:
      "Як часто платформа сама отримує дані Personio, і ручна синхронізація.",
    intervall: "Інтервал синхронізації",
    intervallWahl: {
      "0": "Лише вручну",
      "1": "Щогодини",
      "6": "Кожні 6 годин",
      "24": "Щодня",
      "168": "Щотижня",
    },
    abgleichJetzt: "Оновити дані",
    abgleichLaeuft: "Синхронізація …",
    abgleichFertig: (mitarbeiter: number, anwesenheiten: number, abwesenheiten: number) =>
      `Синхронізовано: ${mitarbeiter} працівників, ${anwesenheiten} присутностей, ${abwesenheiten} відсутностей.`,
    abgleichTeilweise: (mitarbeiter: number, fehler: string) =>
      `Частково синхронізовано (${mitarbeiter} працівників): ${fehler}`,
    abgleichFehler: (fehler: string) => `Помилка синхронізації: ${fehler}`,
    nachweisTitel: "Документи до Personio",
    nachweisHinweis:
      "Завантажує документ у профіль Personio після зміни навчання чи компетенції. Типово вимкнено.",
    nachweisAktiv: "Завантажувати документи",
    nachweisKategorie: "Категорія документа",
    nachweisKategoriePlatzhalter: "Ідентифікатор категорії Personio",
    nachweisGespeichert: "Збережено.",
    titel: "Дані доступу Personio",
    einleitung:
      "Дані доступу застосунку Personio API. Без них синхронізація, " +
      "фотографії профілів і списки пропозицій лишаються порожніми.",
    kennung: "Client-ID",
    geheimnis: "Client-Secret",
    feldHinweis:
      "Зберігаються зашифровано і більше ніколи не показуються. Щоб їх " +
      "змінити, введіть нові.",
    speichern: "Зберегти",
    gespeichert: "Дані доступу збережено.",
    speichernFehler: (meldung: string) => `Збереження не вдалося: ${meldung}`,
    entfernen: "Видалити",
    entfernt: "Дані доступу видалено.",
    pruefen: "Перевірити зв’язок",
    prueftGerade: "Перевірка …",
    verbindungSteht: "Personio приймає дані доступу.",
    verbindungFehlt: "Personio не відповідає.",
    laedt: "Завантаження …",
    keineHinterlegt: "Даних доступу не задано.",
    ausDerUmgebung: "Діють дані доступу з оточення сервера (.env).",
    hinterlegtSeit: (zeitpunkt: string, wer: string | null) =>
      wer
        ? `Задано ${zeitpunkt}, автор ${wer}.`
        : `Задано ${zeitpunkt}.`,
    ohneSchluessel:
      "На сервері не задано GEHEIM_SCHLUESSEL. Поки його немає, нічого " +
      "не можна зберегти зашифровано.",
  },
  sensorEinstellungen: {
    neuesGeraet: "Новий пристрій",
    name: "Назва",
    nameBeispiel: "Серверна",
    rechner: "Хост",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "має бути в SNMP_ERLAUBT",
    community: "Community",
    port: "Порт",
    kennungTemperatur: "Ідентифікатор температури",
    kennungLuftfeuchte: "Ідентифікатор вологості",
    faktorTemperatur: "Коефіцієнт температури",
    faktorHinweis: "0,1 якщо пристрій дає десяті частки градуса цілим числом",
    faktorLuftfeuchte: "Коефіцієнт вологості",
    farbe: "Колір у графіку",
    farbeHinweis: "напр., #0f6e8c",
    optional: "необов’язково",
    anlegen: "Створити",
    fragt: "Опитування …",
    ausprobieren: "Спробувати",
    keinGeraet: "Ще немає пристроїв",
    keinGeraetText: "Введіть угорі хост, community і щонайменше один ідентифікатор.",
    wirdAbgefragt: (name: string) => `${name} опитується`,
    communityErsetzen: "Замінити community",
    unveraendert: "без змін",
    communityErsetzt: "Community замінено.",
    sensorAngelegt: "Датчик створено.",
    sensorGeloescht: "Датчик видалено разом із часовим рядом.",
    zahlEingeben: "Введіть, будь ласка, число.",
    taktTitel: "Інтервал опитування",
    intervall: "Інтервал опитування (секунди)",
    intervallHinweis:
      "Діє для всіх датчиків. Діапазон 5–86400; менше 60 секунд фактично означає опитування щохвилини.",
    intervallFehler: "Інтервал має бути цілим числом від 5 до 86400.",
    grenzenTitel: "Глобальні граничні значення",
    grenzenHinweis: "Діють для всіх датчиків. Порожнє поле означає: без межі.",
    temperaturMin: "Температура мін (°C)",
    temperaturMax: "Температура макс (°C)",
    feuchteMin: "Вологість мін (%)",
    feuchteMax: "Вологість макс (%)",
    temperaturFehler: "Мінімальна температура має бути нижчою за максимальну.",
    feuchteFehler: "Мінімальна вологість має бути нижчою за максимальну.",
    einstellungenGespeichert: "Інтервал і межі збережено.",
    verwerfen: "Скасувати зміни",
  },
  zugaenge: {
    stufen: {
      viewer: "Перегляд",
      editor: "Редагування",
      admin: "Керування",
    },
    gruppeAngelegt: "Групу створено.",
    gruppeGibtEsSchon: "Група з такою назвою вже є.",
    personAngelegt: "Особу створено",
    gruppeUmbenannt: "Групу перейменовано.",
    gruppeGeloescht: "Групу видалено.",
    mitgliedHinzu: "Учасника додано. Діє після наступного входу.",
    schonInGruppe: "Ця особа вже в групі.",
    neuesPasswort: "Новий пароль",
    mitgliedEntfernt: "Учасника вилучено. Діє після наступного входу.",
    gemeldeteSeiten: "Переглянути App Feedback",
    neueGruppe: "Нова група",
    gruppeBeispiel: "напр., Збут, внутрішня служба",
    anlegen: "Створити",
    neuePerson: "Нова особа",
    personBeispiel: "imia.prizvyshche@acm.local",
    keineGruppe: "Ще немає груп",
    keineGruppeText: "Створіть групу, дайте їй права на застосунки і додайте осіб.",
    verzeichnis: "Каталог",
    ausVerzeichnis: "Походить із каталогу",
    umbenennen: "Перейменувати",
    mitRechten: "З правами",
    ohneRechte: "Без прав",
    keinZugriff: "немає доступу",
    rechteAnGruppe: "Права належать групі, а не особі.",
    passwortNurJetzt:
      "Пароль показується лише зараз. Потім його можна лише скинути, а не переглянути.",
    fertig: "Готово",
    anmeldung: "Вхід",
    passwort: "Пароль",
    gruppeUmbenennen: "Перейменувати групу",
    abbrechen: "Скасувати",
    speichern: "Зберегти",
    gruppenname: "Назва групи",
    mitgliederVon: (name: string) => `Учасники «${name}»`,
    wirktNachAnmeldung: "Зміни діють, щойно особа наступного разу ввійде.",
    schliessen: "Закрити",
    personHinzufuegen: "Додати особу",
    auswaehlen: "— вибрати —",
    hinzufuegen: "Додати",
    keineMitglieder: "У цій групі ще немає учасників.",
    passwortZuruecksetzen: "Скинути пароль",
    mitgliedEntfernen: "Вилучити учасника",
    entfernen: "Видалити",
  },
  kopftitel: {
    start: "Застосунки",
    kennzahlen: "Дашборд KPI",
    offeneSchulungen: "Відкриті навчання",
    schulungsmatrix: "Матриця навчань",
    atrLieferungen: "Поставки ATR",
    atrTeilekatalog: "Каталог деталей ATR",
  },
  kennzahlenHub: {
    titel: "Дашборд KPI",
    bereiche: {
      "/kpi/vertrieb": "Оборот, сума замовлення, частка клієнтів",
      "/hr/kennzahlen": "Штат, плинність, хвороби — окреме право",
      "/kpi/qualitaet": "Невідповідності аудитів і частка рекламацій",
      "/kpi/finanzen": "Частка витрат на матеріали і персонал",
      "/kpi/einkauf": "Дотримання постачальниками термінів",
      "/kpi/produktion": "Затримки, прострочені замовлення",
      "/kpi/bewertung": "Оцінювати показники, визначати, призначати й відстежувати заходи",
    },
  },
  personalHub: {
    bereiche: {
      "/hr/kennzahlen": "Штат, плинність, хвороби, понаднормові",
      "/hr/organigramm": "Хто кому підпорядковується",
      "/hr/kompetenzen": "Матриця кваліфікацій за відділами",
      "/hr/schulungen": "Обов’язкові навчання, дати, підтвердження",
      "/hr/onboarding": "Нові працівники, адаптація та процеси",
      "/hr/einarbeitung": "Плани адаптації та їхній стан",
      "/hr/dokumente": "Створювати бланки, друкувати, зчитувати скани назад",
      "/hr/zeugnisse": "Писати і видавати характеристики",
    },
  },
  bewertung: {
    titel: "Оцінка KPI і заходи",
    uebersichtFehler: (meldung: string) => `Не вдалося завантажити: ${meldung}`,
    nurLesen:
      "Ви можете читати оцінки, але не писати. Для цього потрібне право «Редагувати» на " +
      "налаштуваннях.",
    bubbles: "Бульбашки",
    bubblesLeer: "Ще немає бульбашок.",
    neu: "нове",
    alsGesehen: "Позначити як переглянуте",
    zumDashboard: "До дашборду",
    bubble: (nummer: number) => `Бульбашка ${nummer}`,
    ohnePosition: "без позиції на діаграмі",
    neueMassnahme: "Новий захід",
    kpiWaehlen: "Вибрати KPI…",
    ohneBubble: "— без бульбашки —",
    titelPlatzhalter: "Захід (назва)",
    verantwortlichWaehlen: "Відповідальний…",
    anlegen: "Захід",
    massnahmen: "Заходи",
    alleStatus: "Усі статуси",
    statusFilter: "Фільтр за статусом",
    keineMassnahme: "Ще немає заходів.",
    nichtZugewiesen: "не призначено",
    spalte: {
      kpi: "KPI",
      massnahme: "Захід",
      verantwortlich: "Відповідальний",
      faellig: "Строк",
      prioritaet: "Пріоритет",
      status: "Статус",
      aktionen: "Дії",
    },
    status: {
      offen: "відкрито",
      laeuft: "в роботі",
      erledigt: "виконано",
      verworfen: "відхилено",
    },
    prioritaet: {
      niedrig: "низький",
      mittel: "середній",
      hoch: "високий",
    },
    ampel: {
      keine: "без світлофора",
      gruen: "Зелений",
      gelb: "Жовтий",
      rot: "Червоний",
    },
    bereiche: {
      vertrieb: "Збут",
      einkauf: "Закупівлі",
      produktion: "Виробництво",
      qualitaet: "Якість",
      finanzen: "Фінанси",
      personal: "HR",
    },
    verwalten: "Керувати в заходах →",
    anzahlMassnahmen: (anzahl: number) => `заходів: ${anzahl}`,
  },
  erklaerung: {
    hinweis: "Пояснення",
    frage: (titel: string) => `Як обчислюється «${titel}»?`,
    knopf: "Розрахунок",
    untertitel: "Як це обчислюється",
    ganzeSeite: "Уся сторінка довідки",
  },
};
