import type { Texte } from "@/texte/de";

/**
 * Die vietnamesischen Texte der Oberfläche. Maschinell übersetzt — vor dem
 * Ausrollen sollte jemand darüberlesen, der die Sprache spricht.
 */
export const vi: Texte = {
  kopf: {
    benutzermenue: "Menu người dùng",
    angemeldetAls: "Đăng nhập với",
    uebersicht: "Về trang tổng quan",
    hilfe: "Trợ giúp",
    einstellungen: "Cài đặt",
    abmelden: "Đăng xuất",
    sprache: "Ngôn ngữ",
    erscheinungsbild: "Giao diện",
    hell: "Sáng",
    dunkel: "Tối",
    system: "Theo hệ thống",
    meldungenLeer: "Phản hồi — không có gì mới",
    meldungen: (anzahl: number) => `Phản hồi — ${anzahl} mục chưa xem`,
    massnahmenLeer: "Biện pháp — không còn mục nào",
    massnahmen: (offen: number, ueberfaellig: number) =>
      ueberfaellig > 0
        ? `Biện pháp — ${offen} đang mở, trong đó ${ueberfaellig} quá hạn`
        : `Biện pháp — ${offen} đang mở`,
  },
  pfad: {
    aria: "Đường dẫn",
    start: "Trang đầu",
    seiten: {
      "/atr": "ATR",
      "/atr/lieferungen": "Lô giao",
      "/einstellungen": "Cài đặt",
      "/fair": "FAIR",
      "/hilfe": "Trợ giúp",
      "/hr": "HR",
      "/hr/dokumente": "Luồng tài liệu",
      "/hr/einarbeitung": "Hội nhập",
      "/hr/kennzahlen": "Chỉ số",
      "/hr/kompetenzen": "Năng lực",
      "/hr/onboarding": "Onboarding",
      "/hr/organigramm": "Sơ đồ tổ chức",
      "/hr/schulungen": "Đào tạo",
      "/hr/schulungen/matrix": "Ma trận",
      "/hr/schulungen/offen": "Còn thiếu",
      "/hr/zeugnisse": "Thư chứng nhận",
      "/kpi": "Chỉ số",
      "/kpi/bewertung": "Đánh giá",
      "/kpi/einkauf": "Mua hàng",
      "/kpi/finanzen": "Tài chính",
      "/kpi/produktion": "Sản xuất",
      "/kpi/qualitaet": "Chất lượng",
      "/kpi/vertrieb": "Kinh doanh",
      "/newsletter": "Newsletter",
      "/newsletter/redaktion": "Biên tập",
      "/platform/feedback": "Phản hồi",
      "/produktion": "Sản xuất",
      "/qualitaet": "Chất lượng",
      "/sensoren": "Cảm biến",
      "/signage": "Digital Signage",
      "/signage/devices": "Thiết bị",
      "/signage/media": "Phương tiện",
      "/signage/pair": "Ghép nối",
      "/signage/playlists": "Danh sách phát",
      "/signage/schedules": "Lịch phát",
      "/uploads": "Tải lên",
    },
  },
  start: {
    titel: "Ứng dụng",
    verweigert: (name: string) => `Bạn không có quyền mở “${name}”.`,
    keineApp:
      "Tài khoản của bạn chưa được gán ứng dụng nào. Vui lòng liên hệ quản trị nền tảng.",
  },
  anmeldung: {
    titel: "ACM-Plattform",
    aufforderung: "Đăng nhập bằng tài khoản của bạn.",
    email: "E-mail",
    passwort: "Mật khẩu",
    knopf: "Đăng nhập",
    laeuft: "Đang đăng nhập …",
  },
  allgemein: {
    laedt: "Đang tải …",
    speichern: "Lưu",
    abbrechen: "Hủy",
    loeschen: "Xóa",
    stueck: "cái",
    loeschenTitel: "Xác nhận xóa",
    loeschenFrage: (was: string) => `“${was}” sẽ bị xóa vĩnh viễn.`,
    loeschenKnopf: (was: string) => `Xóa ${was}`,
  },
  zeitraum: {
    aria: "Khoảng thời gian",
    monat: "Tháng này",
    quartal: "Quý này",
    jahr: "Năm nay",
    alles: "Toàn bộ",
    frei: "Chọn khoảng thời gian",
    von: "từ",
    bis: "đến",
    vonAria: "Khoảng thời gian từ",
    bisAria: "Khoảng thời gian đến",
    verdreht: "Ngày kết thúc nằm trước ngày bắt đầu.",
  },
  vergleich: {
    zu: (was: string) => `so với ${was}`,
    quartal: (q: number) => `Quý ${q}`,
    jahr: (j: number) => `năm ${j}`,
    keinWert: "Không có giá trị so sánh: thiếu dữ liệu trong kỳ so sánh hoặc giá trị bằng không.",
    gestiegen: "tăng",
    gesunken: "giảm",
    unveraendert: "không đổi",
  },
  diagramm: {
    art: "Kiểu biểu đồ",
    balken: "Cột",
    flaeche: "Vùng",
  },
  tabelle: {
    suche: "Tìm kiếm",
    sucheAria: "Tìm trong bảng",
    sucheLeeren: "Xóa tìm kiếm",
    keineTreffer: "Không có kết quả cho tìm kiếm này.",
    leer: "Không có mục nào.",
    bereich: (von: number, bis: number, gesamt: number) => `${von}–${bis} / ${gesamt}`,
    seite: (seite: number, seiten: number) => `Trang ${seite} / ${seiten}`,
    zurueck: "Trang trước",
    weiter: "Trang sau",
    sortieren: (spalte: string) => `Sắp xếp theo “${spalte}”`,
    seitengroesse: "Số dòng bảng mỗi trang",
    seitengroesseText: "Áp dụng cho mọi bảng trên nền tảng, cho mọi người.",
    gespeichert: "Đã lưu số dòng mỗi trang.",
  },
  datenstand: {
    stand: (datum: string, alter: string) => `Dữ liệu đến ${datum} (${alter})`,
    unvollstaendig: (fehlend: string, anzahl: number) =>
      `Dữ liệu chưa đầy đủ — thiếu ${anzahl} mục: ${fehlend}`,
    heute: "hôm nay",
    gestern: "hôm qua",
    vorTagen: (tage: number) => `${tage} ngày trước`,
    nie: "chưa bao giờ",
    arten: {
      umsatz: "Doanh thu",
      auftraege: "Đơn hàng",
      angebote: "Báo giá",
      interessenten: "Khách hàng tiềm năng",
      kontakte: "Liên hệ",
      liefertreue: "Độ đúng hẹn giao hàng",
      lagerbewegungen: "Biến động kho",
      lagerpreise: "Giá hàng kho",
      auftragspositionen: "Hạng mục đơn hàng",
      lieferscheine: "Phiếu giao hàng",
      pruefungen: "Lượt kiểm tra",
      acht_d: "Báo cáo 8D",
      wareneingaenge: "Hàng nhập kho",
    },
  },
  dashboard: {
    ladeFehler: (meldung: string) => `Không tải được các chỉ số: ${meldung}`,
    keineDatenTitel: "Không có dữ liệu cho khoảng thời gian này",
    keineDatenVor: "Hãy tải các tệp xuất ERP lên tại ",
    keineDatenNach: ", hoặc chọn khoảng thời gian rộng hơn.",
    keineWerte: "không có giá trị trong kỳ",
    laedt: "đang tải …",
    jeTag: "theo ngày",
    jeWoche: "theo tuần",
    jeMonat: "theo tháng",
  },
  vertrieb: {
    umsatz: "Doanh thu",
    umsatzHinweis: "Hóa đơn trừ giấy báo có",
    auftragswert: "Ø Giá trị đơn hàng",
    ueberNull: "Đơn hàng trên 0 €",
    auftraege: "Tổng số đơn hàng",
    verlauf: "Diễn biến doanh thu",
    verlaufHinweis: (takt: string) => `${takt}, đã trừ giấy báo có`,
    kundenanteil: "Tỷ trọng khách hàng trong doanh thu",
    kunde: "Khách hàng",
    anteil: "Tỷ trọng",
    uebrige: "Còn lại",
    jeErfasser: "Đơn hàng theo người nhập",
    erfasser: "Người nhập",
    anzahl: "Đơn hàng",
    summe: "Tổng",
    einzelauftraege: "Từng đơn hàng",
    einzelauftraegeHinweis: "Đơn hàng trên 0 € trong kỳ — chính là các đơn mà “Tổng số đơn hàng” đếm",
    auftragsNr: "Số đơn hàng",
    datum: "Ngày",
    gesamt: "Tổng cộng",
    kundenanteilAuftraege: "Tỷ trọng khách hàng trong đơn hàng",
    kundenanteilAuftraegeHinweis: "Giá trị đơn hàng theo khách hàng",
    kundenanteilRechnungen: "Tỷ trọng khách hàng trong hóa đơn",
    kundenanteilRechnungenHinweis: "Hóa đơn trừ giấy báo có theo khách hàng",
    restkunden: (anzahl: number) => `Khách hàng khác (${anzahl})`,
    rest: "Còn lại",
    weitereKunden: (anzahl: number) => `Hiện thêm ${anzahl}`,
    nurTop3: "Chỉ top 3",
    umsatzIn: (zeitraum: string) => `Doanh thu ${zeitraum}`,
  },
  aktivitaet: {
    titel: "Hoạt động kinh doanh",
    jeWoche: (von: string, bis: string) => `theo tuần lịch, ${von} đến ${bis}`,
    ladeFehler: (meldung: string) => `Không tải được hoạt động kinh doanh: ${meldung}`,
    leer: "Không có liên hệ, báo giá hay khách hàng tiềm năng nào trong kỳ này.",
    kw: (woche: string) => `Tuần ${woche}`,
    ziel: (wert: string) => `Mục tiêu ${wert} / tuần`,
    erstkontakte: "Liên hệ lần đầu",
    erstkontakteHinweis: "liên hệ đã hoàn tất thuộc loại ERS",
    besuche: "Lượt thăm",
    besucheHinweis: "tại chỗ và trực tuyến gộp lại",
    besucheOrt: "tại chỗ",
    besucheOnline: "trực tuyến",
    interessenten: "Khách hàng tiềm năng",
    interessentenHinweis: "mới ghi nhận, chưa gán nhân viên kinh doanh",
    angebote: "Báo giá",
    angeboteHinweis: "tổng giá trị báo giá đã lập",
    auftragseingang: "Đơn hàng nhận được",
    auftragseingangHinweis: "đã trừ các đơn hủy",
  },
  einkauf: {
    einleitung:
      "Độ đúng hẹn giao hàng của nhà cung cấp. Tính theo những gì đã về trong kỳ.",
    keineDaten: "Không có hạng mục giao hàng nào trong kỳ này",
    ladeVor: "Hãy tải tệp xuất độ đúng hẹn giao hàng lên tại ",
    ladeNach: ".",
    otd: "Tỷ lệ OTD",
    otdHinweis: (ziel: string) => `Mục tiêu ${ziel} · đúng hẹn nghĩa là chậm ≤ 0`,
    puenktlich: "Hạng mục đúng hẹn",
    gesamt: "Tổng số hạng mục",
    verzugSchnitt: "Ø Chậm",
    verzugHinweis: "Hạng mục không có giá trị chậm trễ không được tính ở đây",
    verlauf: "Tỷ lệ OTD theo thời gian",
    verlaufHinweis: "Chỗ trống là những kỳ không có hạng mục giao hàng.",
    ladenhueter: "Đặt hàng vào kho — hàng nằm lâu",
    kapital: (wert: string) => `Vốn bị giữ: ${wert}`,
    ladenhueterHinweis: (tage: number) =>
      `Hàng kho không có biến động ít nhất ${tage} ngày, giá trị cao nhất lên trước. ` +
      "Tính đến hôm nay — khoảng thời gian ở trên không áp dụng ở đây, vì tồn kho không phải là một khoảng thời gian.",
    artikel: "Mặt hàng",
    bezeichnung: "Mô tả",
    bestand: "Tồn kho",
    liegtSeit: "Nằm từ",
    stueckpreis: "Đơn giá",
    wert: "Giá trị",
    positionen: "Hạng mục giao hàng",
    positionenHinweis:
      "Chậm nhiều nhất lên trước, hạng mục không có giá trị chậm trễ lên đầu. Tối đa 500 dòng.",
    auftrag: "Đơn hàng",
    lieferant: "Nhà cung cấp",
    zieltermin: "Hạn giao",
    geliefert: "Đã giao",
    verzug: "Chậm",
  },
  produktion: {
    einleitung: "Đơn hàng bị chậm. Một đơn chỉ được tính khi đã rõ kết cục của nó.",
    keineDaten: "Không có đơn hàng nào đã rõ kết cục trong kỳ này",
    ladeVor: "Hãy tải hạng mục đơn hàng và phiếu giao hàng lên tại ",
    ladeNach:
      ". Cần cả hai: một tệp mang hạn giao, tệp kia mang ngày giao thực tế.",
    quote: "Tỷ lệ chậm",
    quoteHinweis: (ziel: string) => `Tối đa ${ziel}`,
    inVerzug: "Đơn hàng bị chậm",
    gesamt: "Tổng số đơn hàng",
    gesamtHinweis: "không tính đơn còn mở chưa đến hạn",
    verzugSchnitt: "Ø Chậm",
    verzugHinweis: "đơn đúng hẹn được tính là số âm",
    verlauf: "Tỷ lệ chậm theo thời gian",
    verlaufHinweis: "Theo hạn giao. Chỗ trống là những kỳ không có đơn nào được tính.",
    ziellinie: "Mục tiêu",
    liste: "Đơn hàng bị chậm",
    listeHinweis:
      "Chậm nhiều nhất lên trước. Với đơn còn mở, mức chậm tăng thêm mỗi ngày. Tối đa 500 dòng.",
    auftrag: "Đơn hàng",
    kunde: "Khách hàng",
    stand: "Trạng thái",
    zieltermin: "Hạn giao",
    geliefert: "Đã giao",
    verzug: "Chậm",
    verspaetet: "giao muộn",
    offen: "còn mở, quá hạn",
  },
  finanzen: {
    einleitung: "Chi phí vật tư và nhân sự so với doanh thu xuất hóa đơn.",
    keineDatenVor:
      "Cần ba tệp: biến động kho cho lượng tiêu hao, hàng nhập kho cho giá và " +
      "doanh thu làm cơ sở quy chiếu. Cả ba đều nằm ở ",
    keineDatenNach: ".",
    materialquote: "Tỷ lệ chi phí vật tư",
    materialquoteHinweis: "Chi phí vật tư / doanh thu",
    hoechstens: (ziel: string) => `Tối đa ${ziel}`,
    materialkosten: "Chi phí vật tư",
    umsatz: "Doanh thu",
    personalquote: "Tỷ lệ chi phí nhân sự",
    brauchtZeitraum: "cần một khoảng thời gian",
    personalHinweis: (kosten: string, personen: string) => `${kosten} cho ${personen} người`,
    ohnePreis: "Mặt hàng không có giá",
    ohnePreisHinweis: "đã tiêu hao nhưng chưa định giá",
    jeAbteilung: "Chi phí nhân sự theo bộ phận",
    abteilung: "Bộ phận",
    personen: "Người",
    kosten: "Chi phí",
    anteil: "Tỷ trọng",
    verlauf: "Tỷ lệ chi phí vật tư theo thời gian",
    verlaufHinweis:
      "Chỗ trống là những kỳ không có doanh thu — không có cơ sở quy chiếu thì không có tỷ lệ.",
    ziellinie: "Mục tiêu",
    verbrauch: "Lượng vật tư tiêu hao theo mặt hàng",
    verbrauchHinweis:
      "Chi phí cao nhất lên trước. Mặt hàng không có giá nằm cuối — chúng không vào " +
      "tỷ lệ. Tối đa 500 dòng.",
    artikel: "Mặt hàng",
    bezeichnung: "Mô tả",
    menge: "Tiêu hao",
    stueckpreis: "Đơn giá",
    keinPreis: "không có giá",
  },
  qualitaet: {
    einleitung: "Phát hiện audit, tỷ lệ khiếu nại và sản lượng kiểm tra.",
    auditart: "Loại audit:",
    keineArt:
      "Chưa chọn loại audit nào. Hãy chọn ít nhất một loại, nếu không thì không có gì để đếm.",
    keineDaten: "Không có phát hiện audit nào trong kỳ này",
    ladeVor: "Hãy tải tệp xuất 8D lên tại ",
    ladeNach: ".",
    behoerde: "Cơ quan",
    extern: "Bên ngoài",
    intern: "Nội bộ",
    kunde: "Khách hàng",
    level1: "Phát hiện audit mức 1",
    level2: "Phát hiện audit mức 2",
    ohneLevel: "Không nhận ra mức",
    ohneLevelHinweis: "không tính vào ô nào",
    hoechstens: (ziel: number) => `Tối đa ${ziel}`,
    auditVerlauf: "Phát hiện audit theo thời gian",
    onQuality: "On Quality",
    onQualityHinweis: (bezug: string) =>
      `Tỷ lệ sản lượng không bị khiếu nại. Cơ sở quy chiếu: ${bezug}.`,
    fehlerquote: (quote: string) => `Tỷ lệ lỗi: ${quote}`,
    fehlerquoteZiel: (quote: string, ziel: string) => `Tỷ lệ lỗi: ${quote} · mục tiêu ${ziel}`,
    reklamiert: "Sản lượng bị khiếu nại",
    bezugsmenge: "Sản lượng quy chiếu",
    bezugsmengeNull: "không có nó thì không có tỷ lệ",
    mehrAlsBezogen:
      "Số lượng bị khiếu nại nhiều hơn số lượng đã nhận. Phép tính không giải được điều " +
      "này: tử số và mẫu số đến từ những tệp khác nhau với trường ngày riêng. Hãy kiểm tra " +
      "xem tệp quy chiếu cho kỳ này đã được tải lên đầy đủ chưa.",
    reklKunde: "Khách hàng",
    reklIntern: "nội bộ",
    reklLieferant: "Nhà cung cấp vật tư",
    reklWerkbank: "Đơn vị gia công",
    bezugKunde: "sản lượng đã giao",
    bezugIntern: "sản lượng đã giao",
    bezugLieferant: "hàng nhập kho không tính dịch vụ",
    bezugWerkbank: "hàng nhập kho thuộc nhóm hàng DIENST và SERVIC",
    mengeGesamt: "sản lượng đã báo",
    mengeAkzeptiert: "sản lượng được chấp nhận",
    onQualityBezug: (menge: string) => `On Quality (quy chiếu ${menge})`,
    ziellinie: "Mục tiêu",
    geprueft: "Sản phẩm đã kiểm tra",
    geprueftHinweis: (pruefer: string, tage: string) =>
      `Sản lượng theo mỗi người kiểm tra và mỗi ngày kiểm. Mẫu số giống nhau cho cả hai cỡ: ${pruefer} người kiểm tra trong ${tage} ngày.`,
    gross: "Sản phẩm lớn",
    klein: "Sản phẩm nhỏ",
    mindestens: (ziel: number) => `Ít nhất ${ziel} mỗi ngày và mỗi người kiểm tra`,
    buchungen: "Bản ghi kiểm tra chất lượng",
    buchungenHinweis:
      "Bản ghi bị bỏ chọn vẫn nằm trong danh sách nhưng không tính vào ô nào. " +
      "Số lượng lớn nhất lên trước, tối đa 500 dòng.",
    zaehltMit: "Được tính",
    datum: "Ngày",
    pruefer: "Người kiểm tra",
    produkt: "Sản phẩm",
    groesse: "Cỡ",
    menge: "Số lượng",
    ausschuss: "Phế phẩm",
    mitzaehlen: (datum: string) => `Tính bản ghi ngày ${datum}`,
    klasseGross: "lớn",
    klasseKlein: "nhỏ",
    diagnose: "Phát hiện không nhận ra mức",
    diagnoseHinweis:
      "Mức nằm trong phần văn bản tự do của tệp nguồn. Nếu ở đó không có “Major … Level 1” " +
      "cũng không có “Minor … Level 2” thì phát hiện đó không được tính ở đâu cả. Danh sách " +
      "này cho thấy chỗ cần sửa.",
    bericht: "Báo cáo",
    art: "Loại",
    adresse: "Địa chỉ",
    bezeichnung: "Mô tả",
  },
  personal: {
    einleitung:
      "Từ đợt đồng bộ Personio. Số giờ định mức mỗi ngày lấy từ mô hình thời gian làm " +
      "việc của từng người, không phải từ ngày tám tiếng cào bằng.",
    uebersicht: "Tổng quan",
    standLaedt: "Đang tải trạng thái đồng bộ …",
    keinAbgleich: "Chưa có đợt đồng bộ nào. Nó tự chạy lúc 02:15 mỗi đêm.",
    letzterAbgleich: (zeitpunkt: string, status: string) => `Đồng bộ lần cuối ${zeitpunkt} · ${status}`,
    bestand: (personen: string, anwesenheiten: string, abwesenheiten: string) =>
      `${personen} người, ${anwesenheiten} lượt có mặt, ${abwesenheiten} lượt vắng`,
    abgleichLaeuft: "đang chạy …",
    abgleichen: "Đồng bộ ngay",
    keineDaten: "Không có dữ liệu có mặt trong kỳ này",
    keineDatenHinweis:
      "Hoặc đợt đồng bộ Personio chưa chạy, hoặc khoảng thời gian nằm trước lúc bắt đầu " +
      "ghi nhận.",
    ueberstunden: "Tỷ lệ giờ làm thêm",
    stundenVon: (teil: string, ganz: string) => `${teil} trên ${ganz} giờ`,
    krankheit: "Tỷ lệ nghỉ ốm",
    krankheitsartenFehlen: "chưa khai báo loại nghỉ ốm",
    fluktuation: "Biến động nhân sự",
    fluktuationHinweis: (austritte: string, schnitt: string) =>
      `${austritte} người nghỉ việc, Ø ${schnitt} người làm việc`,
    personen: "Số người ghi nhận",
    personenHinweis: "có mặt trong kỳ",
    krankheitHinweisVor:
      "Tỷ lệ nghỉ ốm còn để trống chừng nào chưa khai báo loại vắng mặt nào của " +
      "Personio được tính là nghỉ ốm. Khai báo tại ",
    krankheitHinweisNach: ".",
    verlauf: "Diễn biến",
    reiheUeberstunden: "Giờ làm thêm",
    reiheKrankheit: "Nghỉ ốm",
  },
  melden: {
    knopf: "Phản hồi",
    titel: "Gửi phản hồi",
    frage: "Trang này có gì không đúng? Một ảnh chụp trang sẽ được gửi kèm.",
    abbrechen: "Hủy",
    senden: "Gửi",
    sendet: "Đang gửi …",
    beispiel: "Ví dụ: ô chỉ số hiện giá trị rỗng mặc dù đã có dữ liệu.",
    beschreibung: "Mô tả",
    aufnahme: "Ảnh chụp trang",
    gehtMit: "Ảnh chụp này sẽ được gửi kèm.",
    nimmtAuf: "Đang chụp trang …",
    misslungen: "Không chụp được trang — phản hồi sẽ gửi đi không kèm ảnh.",
    dankeMitBild: "Cảm ơn — phản hồi đã đến nơi.",
    dankeOhneBild: "Cảm ơn — phản hồi đã đến nơi, không kèm ảnh trang.",
  },
  belegschaft: {
    titel: "Lực lượng lao động",
    hinweis:
      "Tính đến hôm nay. Các phân bố hiển thị dữ liệu gốc hiện tại chứ không phải dữ liệu " +
      "lúc đó — Personio không lưu lịch sử. Việc “Nhân viên” và tỷ lệ năng lực có mẫu số " +
      "khác nhau là cố ý: một con số theo trạng thái Personio, con số kia theo ngày vào và " +
      "ngày nghỉ. Cả hai cách đều lấy từ hệ thống cũ.",
    ladeFehler: (meldung: string) => `Không tải được dữ liệu lực lượng lao động: ${meldung}`,
    beschaeftigte: "Nhân viên",
    beschaeftigteHinweis: "theo trạng thái Personio “hoạt động”",
    neuImQuartal: "Mới trong quý",
    bestand: "Quân số",
    kompetenzen: "Năng lực đã khai báo",
    felderFehlen: "chưa khai báo trường — ",
    kompetenzHinweis: (mit: string, aktive: string) =>
      `${mit} trên ${aktive} theo ngày vào và ngày nghỉ`,
    geschlecht: "Giới tính",
    beschaeftigungsart: "Hình thức làm việc",
    abteilungen: "Bộ phận",
    maennlich: "nam",
    weiblich: "nữ",
    divers: "khác",
    unbekannt: "không rõ",
    vollzeit: "toàn thời gian",
    teilzeit: "bán thời gian",
    geringfuegig: "việc làm phụ",
    extern: "bên ngoài",
  },
  mitarbeiter: {
    titel: "Nhân viên",
    nurMitUeberstunden: "chỉ người có giờ làm thêm",
    ausgeblendet: (anzahl: number) => `(đã ẩn ${anzahl})`,
    person: "Người",
    abteilung: "Bộ phận",
    istStunden: "Giờ thực tế",
    ueberstunden: "Giờ làm thêm",
    quote: "LT %",
  },
  wochenbericht: {
    titel: "Báo cáo tuần",
    ladeFehler: (meldung: string) => `Không tải được báo cáo tuần: ${meldung}`,
    kalenderwoche: "Tuần lịch",
    kw: (woche: string, jahr: string) => `Tuần ${woche} / ${jahr}`,
    keineDaten: "Không có dữ liệu có mặt trong tuần này.",
    saldo: "Chênh lệch giờ làm thêm",
    saldoHinweis: (personen: string) =>
      `Thực tế trừ định mức hiệu lực, trên toàn bộ ${personen} người`,
    ueberSoll: "Vượt định mức",
    ueberSollHinweis: (gesamt: string) => `trên ${gesamt} người có chấm công`,
    krankheit: "Nghỉ ốm",
    tage: "ngày",
    stunden: "giờ",
    krankheitHinweis: "phân bổ trên các ngày lịch của đợt vắng",
    ist: "Thực tế",
    soll: "Định mức",
    saldoSpalte: "Chênh lệch",
    fussnote:
      "Định mức là định mức tuần hiệu lực: nghỉ phép và nghỉ ốm đã được trừ, ai vắng " +
      "không phép thì bị âm. Trong tuần đang chạy, định mức chỉ tính đến ngày chấm công " +
      "cuối cùng.",
  },
  titel: {
    schulung: "Khóa đào tạo",
    zeugnis: "Thư chứng nhận",
    qualifikationsmatrix: "Ma trận năng lực",
    maschine: "Máy",
    audit: "Audit",
    zeichnung: "Bản vẽ",
    lieferung: "Lô giao",
    offeneSchulungen: "Đào tạo còn thiếu",
    schulungsmatrix: "Ma trận đào tạo",
    atrLieferungen: "Lô giao ATR",
    kpiBewertung: "Đánh giá KPI",
    anmelden: "Đăng nhập",
  },
  uploads: {
    einleitung:
      "Đọc vào các tệp xuất ERP. Tải lại cùng một tệp là vô hại: dòng đã có sẽ được cập " +
      "nhật chứ không tạo thêm lần nữa.",
    dateiWaehlen: "Chọn tệp",
    verarbeitet: "đang xử lý …",
    uebersprungen: (datei: string) => `Các dòng bị bỏ qua từ “${datei}”`,
    uebersprungenHinweis: (gesamt: string, fehler: number) =>
      `Đã nhận ${gesamt} dòng, bỏ qua ${fehler} dòng. Các dòng còn lại đã được lưu.`,
    zeile: "Dòng",
    spalte: "Cột",
    grund: "Lý do",
    zuletzt: "Tải lên gần đây",
    datei: "Tệp",
    art: "Loại",
    zeilen: "Dòng",
    uebersprungenSpalte: "Bỏ qua",
    status: "Trạng thái",
    zeitpunkt: "Thời điểm",
    nochNichts: "Chưa tải lên gì.",
    keineZeile: (datei: string) => `“${datei}” không chứa dòng hợp lệ nào.`,
    teilweiseUebernommen: (datei: string, fehler: number) =>
      `Đã nhận “${datei}”, bỏ qua ${fehler} dòng.`,
    uebernommen: (datei: string, neu: number, aktualisiert: number) =>
      `Đã nhận “${datei}”: ${neu} dòng mới, ${aktualisiert} dòng cập nhật.`,
    fehlgeschlagenMeldung: (meldung: string) => `Tải lên thất bại: ${meldung}`,
    vollstaendig: "đầy đủ",
    teilweise: "một phần",
    fehlgeschlagen: "thất bại",
    arten: {
      umsatz: "Doanh thu (hóa đơn và giấy báo có)",
      umsatzText: "Cấp dữ liệu cho ô doanh thu và biểu đồ doanh thu. Giấy báo có nằm ở dạng số âm trong tệp.",
      auftraege: "Đơn hàng nhận được",
      auftraegeText: "Cấp dữ liệu cho giá trị đơn hàng trung bình, tổng số đơn hàng và phân tích theo người nhập.",
      auftragspositionen: "Hạng mục đơn hàng",
      auftragspositionenText:
        "Mang hạn giao của từng hạng mục. Cùng với phiếu giao hàng, từ đó tính ra mức chậm.",
      lieferscheine: "Phiếu giao hàng",
      lieferscheineText: "Mang ngày giao thực tế. Tệp Excel, mỗi dòng một hạng mục phiếu giao hàng.",
      wareneingaenge: "Hàng nhập kho",
      wareneingaengeText:
        "Cơ sở quy chiếu của tỷ lệ lỗi phía mua hàng. Nhóm hàng tách nhà cung cấp vật tư khỏi đơn vị gia công.",
      acht_d: "Báo cáo 8D",
      acht_dText:
        "Phát hiện audit và khiếu nại trong cùng một tệp. Mức của một phát hiện nằm trong văn bản tự do và được suy ra khi đọc vào.",
      lagerbewegungen: "Biến động kho",
      lagerbewegungenText:
        "Lượng tiêu hao theo mặt hàng cho tỷ lệ chi phí vật tư. Thay thế toàn bộ dòng trong khoảng ngày của tệp.",
      lagerpreise: "Giá mặt hàng kho",
      lagerpreiseText:
        "Dữ liệu gốc để định giá tồn kho. Thay thế cả bảng giá, không chỉ những mặt hàng có trong tệp.",
      pruefungen: "Kiểm tra chất lượng",
      pruefungenText:
        "Bản ghi kiểm tra. Thay thế toàn bộ dòng trong khoảng ngày của tệp — những bản ghi bị bỏ chọn bằng tay trong khoảng đó sẽ được tính trở lại.",
      liefertreue: "Độ đúng hẹn giao hàng (mua hàng)",
      liefertreueText:
        "Cấp dữ liệu cho tỷ lệ OTD ở mua hàng. Mỗi dòng một hạng mục giao hàng; ngày giao thực tế quyết định khoảng thời gian.",
      kontakte: "Liên hệ (kinh doanh)",
      kontakteText:
        "Liên hệ lần đầu và lượt thăm theo tuần. Thay thế toàn bộ dòng trong khoảng ngày của tệp — tải lên lần hai cùng kỳ không nhân đôi gì cả.",
      angebote: "Báo giá",
      angeboteText:
        "Giá trị báo giá theo tuần và theo nhân viên kinh doanh. Báo giá không có người nhập không xuất hiện ở cột nào.",
      interessenten: "Khách hàng tiềm năng",
      interessentenText:
        "Dữ liệu gốc của khách hàng tiềm năng. Một khách hàng tiềm năng được lưu lại sẽ chuyển sang tuần khác theo ngày mới của nó.",
    },
  },
  organigramm: {
    einleitung:
      "Từ Personio. Ai ở đó không có cấp trên thì đứng trên cùng — điều đó đúng với ban " +
      "giám đốc, còn lại là dấu hiệu của một lỗ hổng trong dữ liệu gốc.",
    suchfeld: "Người, vị trí hoặc bộ phận",
    suchePlatzhalter: "Tên, vị trí, bộ phận",
    standort: "Địa điểm",
    alleStandorte: "Tất cả địa điểm",
    personen: (anzahl: number) => `${anzahl} người`,
    ohneVorgesetzten: (anzahl: number) => ` · ${anzahl} người không có cấp trên`,
    niemand: "Không tìm thấy ai",
    niemandText: "Đổi từ khóa, đổi địa điểm — hoặc đợt đồng bộ Personio chưa chạy.",
    aufklappen: (name: string) => `Mở ${name}`,
    zuklappen: (name: string) => `Thu gọn ${name}`,
    direkt: (anzahl: number) => `${anzahl} trực tiếp`,
  },
  offeneSchulungen: {
    einleitung:
      "Ai còn thiếu gì. Chỉ các khóa đang hoạt động; khóa đã ngừng không còn xuất hiện ở đây.",
    zumKatalog: "Đến danh mục",
    allesOffene: "Tất cả còn thiếu",
    nieAbsolviert: "Chưa từng học",
    ueberfaellig: "Quá hạn",
    wirdFaellig: "Sắp đến hạn",
    suchen: "Tìm người hoặc khóa đào tạo",
    suchenAria: "Tìm",
    nichtsOffen: "Không còn thiếu gì",
    nichtsOffenText: "Mọi khóa đang hoạt động đều trong chu kỳ — hoặc chưa đọc vào dữ liệu nào.",
    eintraege: (anzahl: number) => `${anzahl} mục.`,
    person: "Người",
    schulung: "Khóa đào tạo",
    bereich: "Lĩnh vực",
    zuletzt: "Gần nhất",
    faellig: "Đến hạn",
    stand: "Trạng thái",
    nie: "chưa từng học",
    imTurnus: "trong chu kỳ",
  },
  schulungsmatrix: {
    einleitung:
      "Mọi người đối chiếu mọi khóa — bảng tổng quan để dán bảng tin và cho audit. Ai chưa " +
      "tham gia gì cả thì có một dòng trống; đó chính là lỗ hổng cần tìm.",
    wasOffenIst: "Những gì còn thiếu",
    katalog: "Danh mục",
    suchfeld: "Người hoặc bộ phận",
    suchePlatzhalter: "Tên, bộ phận, mã nhân viên",
    bereich: "Lĩnh vực",
    alleBereiche: "Tất cả lĩnh vực",
    nurLuecken: "Chỉ người có lỗ hổng",
    zaehlung: (gezeigt: number, gesamt: number, schulungen: number) =>
      `${gezeigt} trên ${gesamt} người · ${schulungen} khóa đào tạo`,
    niemand: "Không có người nào khớp",
    niemandText: "Đổi từ khóa hoặc đổi lĩnh vực — hoặc thật sự không còn ai thiếu.",
    person: "Người",
    nichtZugewiesen: (person: string, schulung: string) =>
      `${person} · ${schulung}: chưa được gán`,
    zelle: (person: string, schulung: string, stand: string) =>
      `${person} · ${schulung}: ${stand}`,
    faelligAm: (datum: string) => ` (đến hạn ${datum})`,
    offen: "còn thiếu",
    personio: "Personio",
    externGepflegt: "quản lý bên ngoài",
    ohneTreffer: "không khớp với Personio",
  },
  schulungen: {
    einleitung:
      "Danh mục, chu kỳ của nó và ai đáp ứng. Hạn được tính từ lần học cuối và chu kỳ, " +
      "chứ không lưu sẵn.",
    dokumentenlauf: "Luồng tài liệu",
    bereich: "Lĩnh vực",
    neueSchulung: "Khóa đào tạo mới",
    beispiel: "ví dụ: huấn luyện phòng cháy",
    anlegen: "Tạo",
    wirdGelesen: "Đang đọc …",
    uebersichtEinlesen: "Đọc vào bảng tổng quan",
    einlesenAria: "Đọc vào bảng tổng quan đào tạo",
    vorschau: (schulungen: number, neu: number, teilnahmen: number, zugeordnet: number) =>
      `${schulungen} khóa đào tạo (${neu} mới), ${teilnahmen} lượt tham gia, trong đó ${zugeordnet} lượt khớp với một người trong Personio.`,
    ohneTreffer: "Không khớp với Personio: ",
    ohneTrefferNach: ". Những dòng này vẫn được nhận cùng mã nhân viên và tên.",
    wirdUebernommen: "Đang nhận …",
    uebernehmen: "Nhận",
    abbrechen: "Hủy",
    keineSchulung: "Chưa có khóa đào tạo nào",
    keineSchulungText: "Hãy tạo một khóa hoặc đọc vào bảng tổng quan đào tạo.",
    schulung: "Khóa đào tạo",
    turnus: "Chu kỳ",
    frist: "Báo trước (ngày)",
    verantwortlich: "Người phụ trách",
    offen: "Còn thiếu",
    aktiv: "Hoạt động",
    nichtBerechenbar: "(không tính được)",
    zahlGroesserNull: "Vui lòng nhập một số lớn hơn 0.",
    nieKurz: (anzahl: number) => `${anzahl} chưa học`,
    ueberfaelligKurz: (anzahl: number) => `${anzahl} quá hạn`,
    baldKurz: (anzahl: number) => `${anzahl} sắp tới`,
    aktivSchalter: (name: string) => `${name} hoạt động`,
    fussnote: (nie: string, bald: string, datum: string) =>
      `${nie} nghĩa là: không có mốc thời gian nào của người này trong lịch sử. ${bald} nghĩa là: trong vòng hai tháng tới. Tính đến ${datum}.`,
  },
  schulung: {
    gibtEsNicht: "Khóa đào tạo này không tồn tại",
    gibtEsNichtText: "Có lẽ nó đã bị xóa.",
    ohneTurnus: "không có chu kỳ",
    keineFaelligkeit: " — từ đó không tính được hạn nào",
    zumKatalog: "Đến danh mục",
    stammdaten: "Dữ liệu gốc",
    turnus: "Chu kỳ",
    turnusBeispiel: "ví dụ: hằng năm",
    turnusHinweis: "Phần chữ; số tháng đến từ lúc đọc vào.",
    turnusMonate: "Chu kỳ tính bằng tháng",
    monateHinweis: "Để trống nghĩa là: không tính được hạn.",
    verantwortlich: "Người phụ trách",
    beschreibung: "Mô tả",
    fuerWen: "Bắt buộc với ai?",
    kuerzel: "Mã bộ phận",
    kuerzelHinweis: "Hệ mã chi tiết lấy từ tệp Excel (NÄH, CUT, WVK …).",
    personioAbteilung: "Bộ phận Personio",
    personioHinweis: "Bộ phận thô như Personio ghi nhận.",
    entfernen: (was: string) => `Xóa ${was}`,
    keine: "không có",
    ergaenzen: (was: string) => `Thêm ${was}`,
    hinzufuegen: "Thêm",
    teilnahmen: "Lượt tham gia",
    nochNiemand: "Chưa có ai — hãy đọc vào bảng tổng quan đào tạo hoặc nhập một người.",
    person: "Người",
    abteilungKurz: "BP.",
    erstschulung: "Lần học đầu",
    zuletzt: "Gần nhất",
    faellig: "Đến hạn",
    stand: "Trạng thái",
    keinTreffer: "Không khớp trong Personio — dòng vẫn được giữ lại",
    nichtInPersonio: "không có trong Personio",
    exzel: (wert: string) => `Excel: ${wert}`,
    dieseTeilnahme: "lượt tham gia này",
    personErgaenzen: "Thêm người",
    nameForm: "Họ, tên",
  },
  kompetenzen: {
    einleitung:
      "Một vị trí đòi hỏi gì và đã đáp ứng tới đâu — mỗi lĩnh vực một ma trận. Đọc vào từ " +
      "tệp lĩnh vực, sau đó quản lý tại đây.",
    zumDashboard: "Đến bảng chỉ số nhân sự",
    bereich: "Lĩnh vực",
    wirdGelesen: "Đang đọc …",
    einlesen: "Đọc vào tệp lĩnh vực",
    vorschauKopf: (datei: string, bereich: string) =>
      `${datei} — sau đó ${bereich} sẽ trông như thế này:`,
    blattZeile: (qualifikationen: number, personen: number, bewertungen: number) =>
      `${qualifikationen} năng lực, ${personen} người, ${bewertungen} lượt đánh giá.`,
    gefunden: (zugeordnet: number, personen: number) =>
      `Tìm thấy ${zugeordnet} trên ${personen} người trong Personio`,
    platzhalter: (anzahl: number) => `, ${anzahl} cột giữ chỗ`,
    ohneZuordnung: (namen: string) => ` Không khớp: ${namen}.`,
    ersetztWarnung:
      "Các trang tính liên quan sẽ bị thay thế hoàn toàn — những thay đổi quản lý tại đây " +
      "sẽ mất.",
    wirdUebernommen: "Đang nhận …",
    uebernehmen: "Nhận",
    abbrechen: "Hủy",
    keineMatrix: "Chưa có ma trận nào",
    keineMatrixText: "Hãy đọc vào một tệp lĩnh vực — mỗi trang tính trong đó thành một ma trận.",
    blatt: "Trang tính",
    titelSpalte: "Tiêu đề",
    stand: "Tính đến",
    eingelesen: "Đã đọc vào",
    produktion: "Sản xuất",
    verwaltung: "Hành chính",
    safety: "Safety",
    quality: "Quality",
  },
  zeugnisse: {
    einleitung:
      "Từ điểm số và các gạch đầu dòng thành ngôn ngữ thư chứng nhận. Dữ liệu gốc được " +
      "chép lại lúc tạo — một thư đã cấp không đổi theo khi Personio thay đổi.",
    person: "Người",
    waehlen: "— chọn —",
    art: "Loại",
    anlegen: "Tạo",
    keines: "Chưa có thư chứng nhận nào",
    keinesText: "Hãy chọn một người và loại thư — dữ liệu gốc sẽ tự đến.",
    zeitraum: "Khoảng thời gian",
    note: "Điểm",
    stand: "Trạng thái",
    angelegt: "Đã tạo",
    fertig: "xong",
    entwurf: "Bản nháp",
    qualifiziert: "Thư chứng nhận đầy đủ",
    einfach: "Thư chứng nhận đơn giản",
    zwischenzeugnis: "Thư chứng nhận tạm thời",
    ausbildungszeugnis: "Thư chứng nhận học nghề",
    praktikumszeugnis: "Thư chứng nhận thực tập",
  },
  einarbeitung: {
    einleitung:
      "Một người mới phải học gì và ai chỉ cho họ. Phiếu được dựng từ những nội dung đã " +
      "khai báo cho bộ phận của họ.",
    bogenErzeugen: "Tạo phiếu",
    person: "Người",
    waehlen: "— chọn —",
    wirdGebaut: "Đang dựng …",
    einarbeitungsplan: "Kế hoạch hội nhập",
    keineInhalte: "Chưa khai báo nội dung nào — phiếu sẽ trống.",
    abteilungVon: (abteilung: string) => `Bộ phận ${abteilung}`,
    neuerInhalt: "Nội dung mới",
    beispiel: "ví dụ: hướng dẫn an toàn tại máy phay",
    anlegen: "Tạo",
    keinInhalt: "Chưa có nội dung nào",
    keinInhaltText:
      "Hãy xác định một người mới phải học gì — và điều đó áp dụng cho những bộ phận nào.",
    inhalt: "Nội dung",
    ansprechpartner: "Người hướng dẫn",
    bereich: "Lĩnh vực",
    fuerAbteilungen: "Cho những bộ phận nào",
    abteilung: "Bộ phận",
    bereichLeer: "Để trống nghĩa là: lấy bộ phận từ ma trận",
    entfernen: (was: string) => `Xóa ${was}`,
    abteilungHinzu: "+ bộ phận",
    abteilungFuer: (inhalt: string) => `Bộ phận cho ${inhalt}`,
  },
  matrix: {
    gibtEsNicht: "Ma trận này không tồn tại",
    gibtEsNichtText: "Có lẽ nó đã bị thay thế.",
    blattStand: (blatt: string) => `Trang tính ${blatt}`,
    stand: (datum: string) => ` · tính đến ${datum}`,
    umfang: (qualifikationen: number, personen: number) =>
      ` · ${qualifikationen} năng lực, ${personen} người`,
    zurUebersicht: "Về trang tổng quan",
    qualifikation: "Năng lực",
    keineZeilen: "Ma trận này chưa có dòng nào.",
    stufenBedeuten: "Các bậc có nghĩa gì",
    erfuellungsgradHinweis:
      "Con số thứ hai là mức đáp ứng tính theo phần trăm. Một ô có yêu cầu và dưới 100 % " +
      "là một lỗ hổng và được tô màu cảnh báo.",
    ergaenzen: "Thêm",
    neueQualifikation: "Năng lực mới",
    beispiel: "ví dụ: máy tiện",
    kategorie: "Nhóm",
    ohne: "không có",
    zeile: "Dòng",
    neuePerson: "Người mới",
    namensform: "Tên Họ",
    spalte: "Cột",
    anforderungslevel: "Bậc yêu cầu",
    erfuellungsgrad: "Mức đáp ứng theo phần trăm",
    stufe0: "không yêu cầu",
    stufe1: "kiến thức cơ bản",
    stufe2: "làm được khi có hướng dẫn",
    stufe3: "làm việc độc lập",
    stufe4: "hướng dẫn và đào tạo được người khác",
  },
  zeugnis: {
    gibtEsNicht: "Thư chứng nhận này không tồn tại",
    gibtEsNichtText: "Có lẽ nó đã bị xóa.",
    durchschnitt: (wert: string) => ` · trung bình ${wert}`,
    zurUebersicht: "Về trang tổng quan",
    zeugnisVon: (name: string) => `Thư chứng nhận ${name}`,
    stammdaten: "Dữ liệu gốc",
    stammdatenHinweis:
      "Chép lại lúc tạo. Thay đổi tại đây chỉ áp dụng cho thư này — Personio không bị " +
      "đụng đến.",
    name: "Tên",
    personalnummer: "Mã nhân viên",
    abteilung: "Bộ phận",
    taetigkeit: "Công việc",
    eintritt: "Ngày vào",
    austritt: "Ngày nghỉ",
    geburtsdatum: "Ngày sinh",
    ausstellungsdatum: "Ngày cấp",
    ohneNamen: "Không có tên thì không được.",
    anrede: "Xưng hô",
    frau: "Bà",
    herr: "Ông",
    anredeHinweis: "Quyết định cách xưng hô và đại từ trong văn bản.",
    art: "Loại",
    anlass: "Lý do",
    anlassBeispiel: "ví dụ: theo nguyện vọng cá nhân",
    fuehrungskraft: "Cán bộ quản lý",
    fuehrungskraftHinweis: "Cán bộ quản lý — hiện thêm tiêu chí “lãnh đạo”",
    bewertung: "Đánh giá",
    bewertungHinweis:
      "Điểm từ 1 đến 4. Công thức hài lòng suy ra từ điểm trung bình — không phải ngược " +
      "lại.",
    fachwissen: "Kiến thức chuyên môn",
    auffassungsgabe: "Khả năng tiếp thu",
    arbeitsweise: "Cách làm việc",
    belastbarkeit: "Sức chịu áp lực",
    arbeitserfolg: "Kết quả công việc",
    sozialverhalten: "Ứng xử",
    fuehrung: "Lãnh đạo",
    aufgaben: "Nhiệm vụ (gạch đầu dòng)",
    aufgabenHinweis: "Mỗi dòng một nhiệm vụ — từ đó thành danh sách trong thư.",
    kompetenzen: "Năng lực nổi bật",
    kompetenzenHinweis: "Được đưa vào phần đánh giá kết quả.",
    erfolge: "Thành tích nổi bật",
    erfolgeHinweis: "Dự án, khen thưởng, kết quả đo được.",
    text: "Văn bản",
    baut: "Đang dựng …",
    ausBausteinen: "Từ các mô-đun",
    formuliert: "Đang soạn …",
    mitKi: "Bằng AI",
    textHinweis:
      "Bộ mô-đun soạn thảo không cần mạng và không cần AI. AI soạn tự do hơn — nó chỉ nhận " +
      "cách xưng hô, vai trò, bộ phận, thời gian làm việc, điểm số và các đoạn văn tự do ở " +
      "trên. Tên, ngày sinh và mã nhân viên không rời khỏi máy chủ.",
    nochKeinText: "Chưa có văn bản. Hãy cho điểm rồi để nó soạn.",
    fertigSchalter: "Thư chứng nhận đã xong",
    fertigHinweis: "Xong — không còn đang soạn",
    unterschriftenFehler: (meldung: string) =>
      `Không xác định được chữ ký (${meldung}).`,
    darunterSteht: "Ký tên",
    fachlich: "Cấp trên chuyên môn",
    personalwesen: "Nhân sự",
    niemandHinterlegt: "— chưa khai báo ai —",
    unterschriftFehlt:
      "Thiếu một chữ ký. Khai báo tại Cài đặt → Thư chứng nhận, hoặc cập nhật cấp trên " +
      "trong Personio.",
    ausPersonio: "từ Personio",
    ausEinstellungen: "từ phần cài đặt",
    nichtHinterlegt: "chưa khai báo",
    einleitung: "Mở đầu",
    taetigkeitsbeschreibung: "Mô tả công việc",
    leistungsbeurteilung: "Đánh giá kết quả",
    schlussformel: "Lời kết",
    hinweisDeutsch: "Bản thân thư chứng nhận được viết bằng tiếng Đức.",
  },
  dokumentenlauf: {
    einleitung:
      "Phiếu có mã QR: tạo, phát ra, nhận lại khi đã điền, kiểm tra. Mã QR gán bản quét " +
      "về đúng chỗ — bất kể tệp tên là gì.",
    formblatt: "Biểu mẫu",
    fuerWen: "Cho ai",
    personWaehlen: "— chọn người —",
    erzeugt: "Đang tạo …",
    blattErzeugen: "Tạo phiếu",
    standFilter: "Trạng thái:",
    alle: "Tất cả",
    vonGesamt: (gezeigt: number, gesamt: number) => `${gezeigt} trên ${gesamt}`,
    keinVorgang: "Chưa có hồ sơ nào",
    keinVorgangText:
      "Hãy tạo một phiếu ở trên — nó nhận một mã QR và được theo dõi từ đó.",
    person: "Người",
    kennung: "Mã",
    stand: "Trạng thái",
    vollstaendigSpalte: "Đầy đủ",
    blatt: "Phiếu",
    scan: "Bản quét",
    prueft: "Đang kiểm tra …",
    scanFuer: (name: string) => `Tải bản quét cho ${name}`,
    zu: "đóng",
    details: "Chi tiết",
    nochNichtGeprueft: "— chưa kiểm tra",
    vollstaendig: "đầy đủ",
    unvollstaendig: "chưa đầy đủ",
    umkehren: "Đảo kết luận — phép đo chỉ thấy trong ô có mực hay không",
    pruefung: "Kiểm tra",
    qrGelesen: "— đã đọc QR",
    keinQr: "— không tìm thấy QR, không gán được các ô",
    nachweise: "Bằng chứng",
    keineNachweise: "Chưa khai báo gì.",
    welcheZeile: "Thuộc dòng nào? (không bắt buộc)",
    laedt: "Đang tải lên …",
    nachweis: "Bằng chứng",
    nachweisHoch: "Tải bằng chứng lên",
    erstellt: "đã tạo",
    uebergeben: "đã phát",
    zurueck: "đã nhận lại",
    geprueft: "đã kiểm tra",
    einarbeitungsplan: "Kế hoạch hội nhập",
    schulungsnachweis: "Hồ sơ đào tạo",
  },
  onboarding: {
    einleitung:
      "Ai là người mới và ma trận yêu cầu đòi hỏi những khóa nào cho họ. Kế hoạch không " +
      "được lưu mà được tính — ma trận đổi thì kế hoạch đổi theo.",
    nichtsGefehlt: "Không thiếu gì.",
    angelegt: (anzahl: number) => `Đã tạo ${anzahl} khóa đào tạo.`,
    neu90: "Mới (90 ngày qua)",
    alle: "Tất cả",
    personen: (anzahl: number) => `${anzahl} người`,
    keineEintritte: "Không có người vào mới",
    keineEintritteText: "Ngay khi có người kèm ngày vào từ Personio, họ sẽ xuất hiện ở đây.",
    person: "Người",
    abteilung: "Bộ phận",
    position: "Vị trí",
    eintritt: "Ngày vào",
    uebergabe: "Đã bàn giao",
    nichtInPersonio: "không có trong Personio",
    hierGesetzt: "Đặt tại đây — ghi đè Personio",
    ausPersonio: "Từ Personio",
    vermerken: "Ghi nhận",
    paketTitel: "Kế hoạch hội nhập và bảng tổng quan đào tạo trong một PDF",
    paket: "Gói",
    uebersichtTitel: "Chỉ bảng tổng quan đào tạo (biểu mẫu 71)",
    uebersicht: "Tổng quan",
    planZu: "Đóng kế hoạch",
    plan: "Kế hoạch",
    schulungsplan: "Kế hoạch đào tạo",
    fehlendeAnlegen: "Tạo những khóa còn thiếu",
    wirdGerechnet: "đang tính …",
    bruecke: "Vị trí → mã bộ phận",
    brueckeHinweis:
      "Cầu nối giữa Personio và tầng chi tiết của ma trận yêu cầu. Không có mục nào thì " +
      "tầng chi tiết không áp dụng cho vị trí này — kế hoạch sẽ nói rõ điều đó.",
    kuerzel: "Mã",
    positionBeispiel: "ví dụ: thợ phay CNC",
    kuerzelBeispiel: "CNC",
    zuordnen: "Gán",
    ohnePersonio: "Người không có trong Personio",
    ohnePersonioHinweis:
      "Dành cho người vào mới chưa có trong đợt đồng bộ — hoặc vốn không thuộc về đó.",
    name: "Tên",
    anlegen: "Tạo",
    kuerzelFehlt: (position: string) =>
      `Chưa khai báo mã bộ phận cho vị trí ${position}. Vì vậy tầng chi tiết của ma trận ` +
      "yêu cầu không áp dụng cho người này — có thể thiếu các khóa đào tạo bắt buộc.",
    matrixVerlangtNichts: "Ma trận yêu cầu không đòi hỏi gì cho bộ phận này.",
    schulung: "Khóa đào tạo",
    bereich: "Lĩnh vực",
    turnus: "Chu kỳ",
    pflichtUeber: "Bắt buộc qua",
    stand: "Trạng thái",
    ueberAbteilung: "Bộ phận",
    ueberKuerzel: "Mã",
    vorhanden: "đã có",
    fehlt: "còn thiếu",
  },
  audit: {
    einleitung:
      "Audit từ lúc lập kế hoạch đến lúc kết thúc. Mọi thay đổi trạng thái đều nằm trong " +
      "lịch sử — do cơ sở dữ liệu ghi chứ không phải màn hình nhập, và sau đó không sửa được.",
    zuKennzahlen: "Đến các chỉ số",
    nummer: "Số",
    nummerBeispiel: "A-2026-01",
    titel: "Tiêu đề",
    titelBeispiel: "Audit hệ thống EN 9100",
    art: "Loại",
    intern: "nội bộ",
    extern: "bên ngoài",
    phasenvorlage: "Mẫu giai đoạn",
    ohne: "không có",
    anlegen: "Tạo",
    keinAudit: "Chưa có audit nào",
    keinAuditText: "Hãy tạo một audit — kèm mẫu giai đoạn, nó mang theo luôn danh sách kiểm.",
    laufen: (laufend: number, gesamt: number) => `${laufend} trên ${gesamt} audit còn đang chạy.`,
    status: "Trạng thái",
    fortschritt: "Tiến độ",
    naechsterTermin: "Mốc tiếp theo",
    ueberfaellig: (anzahl: number) => `${anzahl} quá hạn`,
    geplant: "Đã lên kế hoạch",
    inVorbereitung: "Đang chuẩn bị",
    inDurchfuehrung: "Đang thực hiện",
    berichtet: "Đã báo cáo",
    massnahmenOffen: "Biện pháp còn mở",
    abgeschlossen: "Đã kết thúc",
    verschoben: "Đã hoãn",
    abgesagt: "Đã hủy",
    phaseOffen: "Chưa làm",
    phaseInArbeit: "Đang làm",
    phaseErledigt: "Xong",
    phaseNichtZutreffend: "Không áp dụng",
    system: "Hệ thống",
    prozess: "Quy trình",
    produkt: "Sản phẩm",
    lieferant: "Nhà cung cấp",
  },
  wartung: {
    einleitung:
      "Máy móc và các công việc bảo trì định kỳ. Hồ sơ được tạo thành phiếu để dán lên — " +
      "mỗi nửa năm một phiếu, mỗi tuần lịch một cột.",
    zuKennzahlen: "Đến các chỉ số",
    neueMaschine: "Máy mới",
    beispiel: "ví dụ: máy phay 3",
    anlegen: "Tạo",
    keineMaschine: "Chưa có máy nào",
    keineMaschineText: "Hãy tạo một máy và khai báo các công việc bảo trì của nó.",
    maschine: "Máy",
    inventarnummer: "Số tài sản",
    standort: "Vị trí",
    verantwortlich: "Người phụ trách",
    status: "Trạng thái",
    aktiv: "hoạt động",
    stillgelegt: "đã ngừng",
  },
  sensoren: {
    einleitung:
      "Nhiệt độ và độ ẩm, hỏi năm phút một lần. Giá trị nằm ngoài giới hạn đã đặt sẽ được " +
      "tô màu cảnh báo.",
    misst: "Đang đo …",
    jetztMessen: "Đo ngay",
    keinGeraet: "Chưa thiết lập thiết bị nào",
    keinGeraetText: "Cảm biến được tạo trong phần cài đặt — máy chủ, mã nhận dạng và community.",
    verlauf: "Diễn biến",
    stunden: (n: number) => `${n} h`,
    tage: (n: number) => `${n} ngày`,
    temperatur: "Nhiệt độ",
    luftfeuchte: "Độ ẩm",
    zuletzt: (zeit: string) => `Lần cuối ${zeit}`,
    keinMesswert: "Chưa có giá trị đo nào.",
    nichtsGemessen: "Trong khoảng thời gian này không đo được gì.",
    frisch: "hiện thời",
    verzoegert: "trễ",
    offline: "offline",
    unbekannt: "chưa đo gì",
  },
  hilfe: {
    einleitung:
      "Nền tảng làm được gì, các con số hình thành ra sao và phải làm gì khi có điều gì " +
      "không đúng.",
    nurDeutsch: "Bản thân các trang trợ giúp được viết bằng tiếng Đức.",
    suchen: "Tìm trong trợ giúp",
    nichtsGefunden:
      "Không tìm thấy gì. Nếu trợ giúp còn thiếu điều gì, hãy nói qua nút Phản hồi ở dưới bên phải.",
    alleThemen: "← Tất cả chủ đề",
  },
  meldungen: {
    stand: (offen: number) => `Những gì đã được phản ánh từ các màn hình. ${offen} đang mở`,
    neuSeit: (anzahl: number) => ` · ${anzahl} mới kể từ lần xem trước`,
    nichtsGemeldet: "Chưa có phản hồi nào",
    nichtsGemeldetText:
      "Qua nút ở dưới bên phải, bất kỳ người nào đã đăng nhập đều có thể báo điều gì " +
      "không đúng trên một trang.",
    unbekannt: "không rõ",
    bild: "Ảnh",
    status: "Trạng thái",
    offen: "đang mở",
    erledigt: "đã xong",
    meldung: "Phản hồi",
    aufnahme: "Ảnh chụp trang",
  },
  auditAnsicht: {
    gibtEsNicht: "Audit này không tồn tại",
    gibtEsNichtText: "Có lẽ nó đã bị xóa.",
    internesAudit: "Audit nội bộ",
    externesAudit: "Audit bên ngoài",
    prioritaet: (stufe: string) => ` · ưu tiên ${stufe}`,
    erledigt: (prozent: number) => ` · đã xong ${prozent} %`,
    ueberfaellig: (anzahl: number) => ` · ${anzahl} quá hạn`,
    zurUebersicht: "Về trang tổng quan",
    status: "Trạng thái",
    stammdaten: "Dữ liệu gốc",
    titel: "Tiêu đề",
    bereich: "Lĩnh vực",
    leitenderAuditor: "Trưởng đoàn audit",
    auditteam: "Đoàn audit",
    geplantVon: "Dự kiến từ",
    geplantBis: "Dự kiến đến",
    prioritaetFeld: "Mức ưu tiên",
    niedrig: "thấp",
    mittel: "trung bình",
    hoch: "cao",
    auditziel: "Mục tiêu audit",
    kategorien: "Phân loại",
    kategorienHinweis:
      "Một cuộc audit thường là nhiều thứ cùng lúc — chương trình nội bộ chạy cả hệ thống " +
      "lẫn quy trình trong một buổi. Vì vậy chọn nhiều chứ không phải một mục duy nhất.",
    normbezug: "Tham chiếu tiêu chuẩn",
    normmatrixLeer: "Ma trận tiêu chuẩn còn trống — nó được quản lý trong phần cài đặt.",
    nichtGeprueft: "* chưa đối chiếu với bản tiêu chuẩn hợp nhất.",
    phasen: "Giai đoạn",
    keinePhasen: "Không có giai đoạn nào — audit này được tạo không theo mẫu.",
    phase: "Giai đoạn",
    verantwortlich: "Người phụ trách",
    faellig: "Đến hạn",
    erledigtAm: "Xong ngày",
    phaseErgaenzen: "Thêm giai đoạn",
    phaseBeispiel: "ví dụ: audit theo dõi",
    verlauf: "Lịch sử",
    verlaufHinweis:
      "Do cơ sở dữ liệu ghi chứ không phải màn hình này — và sau đó không sửa cũng không " +
      "xóa được.",
    nichtsGeschehen: "Chưa có gì xảy ra.",
    warumEntfaellt: "Vì sao giai đoạn bắt buộc này không áp dụng?",
    uebernehmen: "Nhận",
    abbrechen: "Hủy",
    angelegt: "đã tạo",
    geaendert: "đã đổi",
    geloescht: "đã xóa",
    uebersprungen: "đã bỏ qua",
  },
  maschine: {
    gibtEsNicht: "Máy này không tồn tại",
    gibtEsNichtText: "Có lẽ nó đã bị xóa.",
    zurUebersicht: "Về trang tổng quan",
    stammdaten: "Dữ liệu gốc",
    name: "Tên",
    inventarnummer: "Số tài sản",
    standort: "Vị trí",
    hersteller: "Nhà sản xuất",
    modell: "Kiểu máy",
    verantwortlich: "Người phụ trách",
    status: "Trạng thái",
    aktiv: "hoạt động",
    stillgelegt: "đã ngừng",
    notizen: "Ghi chú",
    wartungsaufgaben: "Công việc bảo trì",
    jahr: "Năm",
    halbjahr: "Nửa năm",
    erstesHalbjahr: "Tuần 1–26",
    zweitesHalbjahr: "Tuần 27–52",
    wirdGebaut: "Đang dựng …",
    nachweisbogen: "Phiếu hồ sơ",
    neueAufgabe: "Công việc mới",
    aufgabeBeispiel: "ví dụ: kiểm tra mức dầu",
    intervall: "Chu kỳ",
    wochen: "tuần",
    keineAufgabe: "Chưa có công việc nào — phiếu sẽ trống.",
    aufgabe: "Công việc",
    dateien: "Tệp",
    planHinterlegen: "Đưa kế hoạch vào",
    nachweisAblegen: "Lưu hồ sơ",
    dateienHinweis: "Kế hoạch của nhà sản xuất và các phiếu đã ký được quét lại.",
    keineDatei: "Chưa có tệp nào.",
    plan: "Kế hoạch",
    nachweis: "Hồ sơ",
    laedt: "Đang tải lên …",
    taeglich: "Hằng ngày",
    woechentlich: "Hằng tuần",
    monatlich: "Hằng tháng",
    quartalsweise: "Hằng quý",
    alleNWochen: "Mỗi N tuần",
    alleNWochenZahl: (wochen: number) => `Mỗi ${wochen} tuần`,
  },
  atr: {
    einleitung:
      "Danh mục linh kiện là nền tảng: một phiếu giao hàng lấy từ đó mô tả, bản vẽ và khối " +
      "lượng. Việc khớp dựa trên mã linh kiện không kèm phụ tố — chỉ các chữ số mới tính.",
    zuLieferungen: "Đến các lô giao",
    teilAnlegen: "Thêm linh kiện bằng tay",
    teilBeispiel: "Mã linh kiện, ví dụ VR-1234-56",
    anlegen: "Tạo",
    wirdGelesen: "Đang đọc …",
    mappeEinlesen: "Đọc vào tập tham chiếu",
    suchen: "Tìm",
    suchePlatzhalter: "Mã linh kiện, mô tả hoặc bản vẽ",
    nichtsGefunden: "Không tìm thấy gì",
    katalogLeer: "Danh mục còn trống",
    keinTeil: "Không có linh kiện nào khớp với tìm kiếm này.",
    katalogLeerText: "Hãy đọc vào một tập tham chiếu hoặc thêm một linh kiện bằng tay.",
    teilenummer: "Mã linh kiện",
    bezeichnung: "Mô tả",
    zeichnung: "Bản vẽ",
    gewicht: "Khối lượng kg",
    kategorie: "Nhóm",
    nurErste: "Chỉ 500 kết quả đầu — vui lòng thu hẹp tìm kiếm.",
  },
  lieferungen: {
    einleitung:
      "Một phiếu giao hàng được đọc vào, đối chiếu với danh mục linh kiện và lưu thành " +
      "bản nháp. Sau khi rà soát, nó được phát hành.",
    zumKatalog: "Đến danh mục linh kiện",
    wirdGelesen: "Đang đọc …",
    einlesen: "Đọc vào phiếu giao hàng",
    laeuft: "Đang chạy …",
    eingangDurchsehen: "Rà soát hộp đến",
    berichtNummer: (nr: string) => ` · số ${nr}`,
    berichtZeile: (positionen: number, zugeordnet: number) =>
      `${positionen} hạng mục, ${zugeordnet} tìm thấy trong danh mục.`,
    keinLieferschein: "Chưa có phiếu giao hàng nào",
    keinLieferscheinSchreiben: "Hãy đọc vào một PDF phiếu giao hàng — sau đó nó chờ ở đây để rà soát.",
    keinLieferscheinLesen: "Ngay khi một phiếu giao hàng được đọc vào, nó sẽ xuất hiện ở đây.",
    lieferschein: "Phiếu giao hàng",
    datum: "Ngày",
    programm: "Chương trình",
    msn: "MSN",
    status: "Trạng thái",
    entwurf: "Bản nháp",
    freigegeben: "đã phát hành",
  },
  durchsicht: {
    nichtGefunden: "Không tìm thấy lô giao.",
    freigeben: "Phát hành",
    zuruecknehmen: "Thu hồi phát hành",
    wirdErzeugt: "Đang tạo …",
    dokumenteErzeugen: "Tạo tài liệu",
    kopfdaten: "Dữ liệu đầu trang",
    atrNummer: "Số ATR",
    containernummer: "Số container",
    satzTitel: "Tên bộ",
    programm: "Chương trình",
    msn: "MSN",
    bereich: "Lĩnh vực",
    wiegedatum: "Ngày cân",
    pruefdatum: "Ngày kiểm tra",
    qsUnterschrift: "Chữ ký QA",
    hoechstgewicht: "Khối lượng tối đa kg",
    positionen: "Hạng mục",
    pos: "STT",
    menge: "SL",
    seriennummern: "Số sê-ri",
    nichtImKatalog: "không có trong danh mục",
    festHinweis:
      "Lô giao đã được phát hành; các hạng mục đã chốt. Cơ sở dữ liệu từ chối mọi thay " +
      "đổi — có thể thu hồi phát hành ở trên.",
  },
  fair: {
    dateiFehlt: (meldung: string) =>
      `Không tải được bản vẽ (${meldung}). Các kích thước vẫn được liệt kê bên dưới.`,
    einleitung:
      "Kiểm tra mẫu đầu: tải lên một bản vẽ và đặt một bong bóng đánh số lên mỗi kích " +
      "thước cần kiểm. Số do cơ sở dữ liệu cấp và giữ liền mạch.",
    bezeichnungFrei: "Mô tả (để trống = tên tệp)",
    beispiel: "ví dụ: trục 12×40, bản vẽ 4711",
    wirdGeladen: "Đang tải lên …",
    zeichnungWaehlen: "Chọn bản vẽ",
    keineZeichnung: "Chưa có bản vẽ nào",
    keineZeichnungSchreiben: "Hãy tải lên một PDF hoặc ảnh — sau đó có thể đánh bong bóng các kích thước.",
    keineZeichnungLesen: "Ngay khi một bản vẽ được tải lên, nó sẽ xuất hiện ở đây.",
    bezeichnung: "Mô tả",
    teilenummer: "Mã linh kiện",
    kunde: "Khách hàng",
    hochgeladen: "Đã tải lên",
    pruefliste: "Danh sách kiểm",
    einMass: "1 kích thước",
    masse: (anzahl: number) => `${anzahl} kích thước`,
    kopieren: "Sao chép",
    csv: "CSV",
    keinMass: "Chưa đánh dấu kích thước nào.",
    nr: "Số",
    seite: "Trang",
    wert: "Giá trị",
    wertBeispiel: "ví dụ: 12,0 h7",
    wertZu: (nummer: number) => `Giá trị cho số ${nummer}`,
    nachOben: (nummer: number) => `Đưa số ${nummer} lên trên`,
    nachUnten: (nummer: number) => `Đưa số ${nummer} xuống dưới`,
    nummer: (nummer: number) => `Số ${nummer}`,
    drehen: "Xoay khung nhìn",
    verkleinern: "Thu nhỏ",
    vergroessern: "Phóng to",
    einpassen: "Vừa khung",
    zeichnung: "Bản vẽ",
    ladefehler: "Không tải được bản vẽ.",
  },
  newsletter: {
    keineAusgabe: "Chưa có số nào",
    keineAusgabeText: "Ngay khi ban biên tập phát hành một số, nó sẽ xuất hiện ở đây.",
    zurRedaktion: "Đến trang biên tập",
    quartalJahr: (quartal: number, jahr: number) => `Quý ${quartal} · ${jahr}`,
    entwurfSuffix: " · bản nháp",
    ausgabe: "Số",
    quartalKurz: (quartal: number, jahr: number) => `Q${quartal} ${jahr}`,
    entwurfKlammer: " (bản nháp)",
    alsPdf: "Dạng PDF",
    wirdGesetzt: "Đang dàn trang …",
    seiteVon: (nr: number, gesamt: number) => `Trang ${nr} trên ${gesamt} …`,
    redaktion: "Biên tập",
    niemandDazu: "Quý này không có ai vào mới.",
    beitraege: "Bài viết",
    belegschaftInZahlen: "Lực lượng lao động qua các con số",
    neuBeiUns: "Người mới của chúng ta",
    redaktionEinleitung:
      "Mỗi quý một số. Các chương quyết định thứ tự trong tập; số chỉ được phát hành khi " +
      "đã xong.",
    zurLeseransicht: "Đến trang đọc",
    jahr: "Năm",
    quartal: "Quý",
    ausgabeAnlegen: "Tạo số",
    ausgabeBearbeiten: "Sửa số",
    keineAusgabeRedaktion: "Chọn năm và quý rồi tạo — sau đó các chương sẽ hình thành ở đây.",
    titelDerAusgabe: "Tiêu đề của số",
    status: "Trạng thái",
    entwurf: "Bản nháp",
    veroeffentlicht: "đã phát hành",
    titelbild: "Ảnh bìa",
    rueckseite: "Trang bìa sau",
    ersetzen: ": thay",
    waehlen: ": chọn",
    ausgabeLoeschen: (quartal: number, jahr: number) => `Số Q${quartal} ${jahr}`,
    neuesKapitel: "Chương mới",
    kapitelBeispiel: "ví dụ: Từ xưởng sản xuất",
    art: "Loại",
    hinzufuegen: "Thêm",
    kapiteltitel: "Tiêu đề chương",
    kapitelHoch: "Đưa chương lên trên",
    kapitelRunter: "Đưa chương xuống dưới",
    ueberschrift: "Tiêu đề",
    eintrag: "Bài",
    textMarkdown: "Văn bản. Cho phép Markdown — **đậm**, danh sách, bảng.",
    text: "Văn bản",
    bild: "Ảnh",
    bildGroesse: (nr: number) => `Kích cỡ ảnh ${nr}`,
    nieEingefroren: "Chưa đóng băng gì — chương sẽ trống trong tập.",
    kpiEingefroren: "Các con số lực lượng lao động của quý đã được đóng băng.",
    niemandEingefroren: "Đã đóng băng — quý này không có ai vào mới.",
    zugaengeEingefroren: (anzahl: number) =>
      `Đã đóng băng: ${anzahl} người vào mới trong quý.`,
    einfrieren: "Đóng băng",
    neuEinfrieren: "Đóng băng lại",
    rechtFehlt: (quelle: string) => `Thiếu quyền ở nguồn: xem ${quelle}.`,
    quelleKpi: "chỉ số",
    quellePersonal: "nhân sự",
    ausgabeAngelegt: "Đã tạo số.",
    ausgabeGeloescht: "Đã xóa số.",
    kapitelAngelegt: "Đã tạo chương.",
    standEingefroren: "Đã đóng băng hiện trạng.",
  },
  signage: {
    einleitung: "Phương tiện, playlist, lịch phát và thiết bị của các màn hình.",
    bereiche: "Các mục Signage",
    medien: "Phương tiện",
    medienHinzu: "Thêm phương tiện",
    playlists: "Playlist",
    zeitplaene: "Lịch phát",
    geraete: "Thiết bị",
    dateiZiehen: "Kéo tệp vào đây",
    dateiWaehlen: "Chọn tệp",
    dateiHinweis: "Ảnh, video, PDF hoặc PPTX, tối đa 50 MB",
    wirdUebertragen: "đang truyền …",
    art: "Loại",
    webseite: "Trang web (URL)",
    htmlSchnipsel: "Đoạn HTML",
    titel: "Tiêu đề",
    titelBeispiel: "Sinh nhật",
    urlHinweis:
      "Hãy nhập địa chỉ đầy đủ. Player chạy trên một cổng riêng, đường dẫn tương đối " +
      "không hoạt động ở đó.",
    aufnehmen: "Thêm vào",
    medienFehler: "Không tải được phương tiện.",
    keineMedien: "Chưa có phương tiện nào",
    keineMedienText:
      "Hãy tải lên một tệp hoặc thêm một URL. Sau đó có thể ghép các phương tiện thành " +
      "playlist.",
    erneut: "lại",
    inVerwendung: "Phương tiện đang được dùng",
    inVerwendungText: (titel: string, anzahl: number) =>
      `“${titel}” vẫn nằm trong ${anzahl} playlist. Hãy gỡ khỏi đó trước.`,
    verstanden: "Đã hiểu",
    wartet: "đang chờ",
    konvertiert: "đang chuyển đổi",
    fertig: "xong",
    fehlgeschlagen: "thất bại",
    keineHeartbeats: "Chưa ghi nhận heartbeat nào.",
    nieGesehen: "chưa từng thấy",
    online: "online",
    vorMinuten: (minuten: number) => `${minuten} phút trước`,
    offline: "offline",
    entzogen: "đã thu hồi",
    keinGeraet: "Chưa ghép nối thiết bị nào",
    keinGeraetText:
      "Hãy khởi động một màn hình với player. Nó hiện một mã sáu ký tự để bạn nhập vào đây.",
    geraetKoppeln: "Ghép nối thiết bị",
    geraet: "Thiết bị",
    status: "Trạng thái",
    verfuegbarkeit: "Khả dụng 24 h",
    ausfaelle: "Gián đoạn 24 h",
    tags: "Tags",
    playlist: "Playlist",
    zuletztGesehen: "Thấy lần cuối",
    seiteNeuLaden: "Tải lại trang",
    neuStarten: "Khởi động lại thiết bị",
    bearbeiten: "Sửa",
    zugangEntziehen: "Thu hồi quyền truy cập",
    geraetBearbeiten: "Sửa thiết bị",
    name: "Tên",
    bilddrehung: "Xoay hình",
    ton: "Âm thanh",
    tonAktiv: "Bật âm thanh",
    abbrechen: "Hủy",
    speichern: "Lưu",
    tagsHinweis: "Chúng quyết định thiết bị này nhận playlist và lịch phát nào.",
    entziehenText: (name: string) =>
      `“${name}” mất quyền truy cập ngay lập tức và hiện lại mã ghép nối.`,
    neustartText: (name: string) => `“${name}” sẽ tối màn hình khoảng một phút.`,
    geraetGespeichert: "Đã lưu thiết bị.",
    geraetGeloescht: "Đã xóa thiết bị.",
    keinGeraetGewaehlt: "chưa chọn thiết bị",
    neuePlaylist: "Playlist mới",
    neuePlaylistText: "Đặt tên và tags đích. Các mục sẽ thêm ở bước sau.",
    namensbeispiel: "Lễ tân",
    keinePlaylist: "Chưa có playlist nào",
    keinePlaylistText:
      "Một playlist gom các phương tiện theo thứ tự và được phân phối tới thiết bị qua tags.",
    playlistAnlegen: "Tạo playlist",
    aktiv: "Hoạt động",
    erstellt: "Đã tạo",
    kopieren: "Sao chép",
    playlistGeloescht: "Đã xóa playlist.",
    playlistKopiert: "Đã sao chép playlist. Các mục không được chép theo.",
    playlistInPlan: "Playlist có lịch phát đang hoạt động",
    zeitplanHinweis:
      "Lịch phát được ưu tiên hơn việc gán tags đơn thuần. Khung giờ vắt qua nửa đêm hãy " +
      "tách thành hai lịch phát.",
    wochentage: "Các ngày trong tuần",
    wochentagKuerzel: ["T2", "T3", "T4", "T5", "T6", "T7", "CN"],
    von: "Từ",
    bis: "Đến",
    prioritaet: "Mức ưu tiên",
    zeitplanAktiv: "Lịch phát hoạt động",
    keineZeitplaene: "Không có lịch phát",
    keineZeitplaeneText:
      "Không có lịch phát thì chỉ việc gán tags quyết định thiết bị hiện playlist nào. Một " +
      "lịch phát đặt một playlist lên trước điều đó vào những ngày và giờ nhất định.",
    tage: "Ngày",
    zeitfenster: "Khung giờ",
    aktionen: "Thao tác",
    zeitplanBearbeiten: "Sửa lịch phát",
    neuerZeitplan: "Lịch phát mới",
    zeitplaeneFehler: "Không tải được lịch phát.",
    endeNachStart: "Giờ kết thúc phải sau giờ bắt đầu. Vắt qua nửa đêm thì hãy tạo hai lịch phát.",
    mindestensEinTag: "Hãy chọn ít nhất một ngày trong tuần.",
    playlistWaehlen: "Hãy chọn một playlist.",
    taeglich: "hằng ngày",
    zielTags: "Tags đích",
    ueberblenden: "Chuyển mờ",
    harterSchnitt: "Cắt thẳng",
    ziehpunkt: "Tay kéo",
    verwerfen: "Bỏ",
    medienHinzufuegen: "Thêm phương tiện và sắp thứ tự bằng tay kéo.",
    mediumWaehlen: "Chọn phương tiện",
    mediumHinzufuegen: "Thêm phương tiện",
    mediumWaehlenText: "Phương tiện đã chọn sẽ được nối vào cuối playlist.",
    schliessen: "Đóng",
    keineMedienAnlegen: "Chưa có phương tiện nào. Hãy tạo ở mục Phương tiện trước.",
    unbekanntesMedium: "phương tiện không rõ",
    playlistGespeichert: "Đã lưu playlist. Các thiết bị tải lại ngay.",
    kopplungscode: "Mã ghép nối",
    codeBeispiel: "ABC-123",
    geraetename: "Tên thiết bị",
    geraeteBeispiel: "Lễ tân trái",
    tagsPflicht: "Thiết bị nhận playlist qua tags. Không có tag thì màn hình để trống.",
    koppeln: "Ghép nối",
    formatErwartet: "Cần định dạng XXX-XXX.",
    codeUnbekannt: "Mã không đúng, đã hết hạn hoặc đã được dùng. Hãy cho hiện lại trên màn hình.",
    tagEingeben: "Nhập tag rồi nhấn Enter",
  },
  einstellungen: {
    titel: "Cài đặt",
    einleitung: "Những gì nền tảng tính, lấy về và hiển thị — giống nhau cho tất cả.",
    bereiche: "Các mục",
    gruppen: {
      kennzahlen: "Chỉ số",
      kennzahlenText:
        "Giá trị mục tiêu của các bảng chỉ số. Chúng xuất hiện thành đường mục tiêu trong " +
        "biểu đồ và quyết định khi nào một ô cảnh báo.",
      personal: "HR",
      personalText:
        "Những loại vắng mặt nào tính là nghỉ ốm và những bộ phận nào thuộc sản xuất. " +
        "Không có các danh sách này thì các tỷ lệ nhân sự còn để trống.",
      atr: "ATR",
      atrText:
        "Những gì giống nhau trong mọi tài liệu của một chương trình, và phiếu giao hàng đến từ đâu.",
      qualitaet: "Chất lượng",
      qualitaetText:
        "Ma trận tiêu chuẩn mà một cuộc audit viện dẫn, và các mẫu giai đoạn mà một audit " +
        "mới nhận làm danh sách kiểm.",
      sensoren: "Cảm biến",
      sensorenText:
        "Các thiết bị đo trong mạng: chúng đứng ở đâu, gửi nhiệt độ và độ ẩm dưới mã nhận " +
        "dạng nào và từ mức nào thì một giá trị bị coi là quá cao.",
      zeugnisse: "Thư chứng nhận",
      zeugnisseText:
        "Những gì giống nhau trên mọi thư chứng nhận công việc: công ty, nơi lập và hai " +
        "chữ ký. Chữ ký chuyên môn được tra từ Personio lúc tạo — ở đây chỉ ghi phương án " +
        "dự phòng.",
      erscheinung: "Giao diện",
      erscheinungText:
        "Logo công ty — ở trên bên trái trong ứng dụng và trên đầu mỗi tệp được tạo ra: " +
        "kế hoạch hội nhập, hồ sơ bảo trì, bảng tổng quan đào tạo, thư chứng nhận.",
      anzeigen: "Màn hình",
      anzeigenText:
        "Các địa chỉ đang chạy trên những màn hình trong nhà. Mỗi địa chỉ mang một token " +
        "đã ký, chỉ dùng cho đúng một màn hình và sẽ hết hạn.",
      zugaenge: "Người dùng và nhóm",
      zugaengeText:
        "Tạo người dùng, lập nhóm và cấp quyền ứng dụng cho họ. Thay đổi có hiệu lực ngay " +
        "khi người liên quan đăng nhập lần sau — quyền nằm trong token của họ.",
    },
  },
  einstellungenText: {
    speichernFehler: (meldung: string) => `Lưu thất bại: ${meldung}`,
    zielwertGespeichert: "Đã lưu giá trị mục tiêu. Các bảng chỉ số hiện nó sau khi tải lại.",
    zahlAbNull: "Vui lòng nhập một số từ 0 trở lên.",
    personalGespeichert: "Đã lưu. Bảng chỉ số nhân sự hiện nó sau khi tải lại.",
    krankTypen: "Các loại vắng mặt tính là nghỉ ốm",
    produktionAbteilungen: "Các bộ phận thuộc sản xuất",
    kompetenzAttribute: "Các trường Personio tính là năng lực đã khai báo",
    ausDemBestand: "từ dữ liệu đã đồng bộ",
    abteilungenBeispiel: "Sản xuất, Lắp ráp",
    firmenlogo: "Logo công ty",
    anzeigenHinweis:
      "Tạo địa chỉ cho một mục playlist trong Signage-Player. Nó chỉ dùng cho màn hình đã " +
      "chọn và sẽ hết hạn — một mục không còn ai chăm sóc sẽ tự ngừng hiển thị.",
    logoHinweis:
      "Xuất hiện ở trên bên trái trong ứng dụng và trên đầu mỗi biểu mẫu được tạo ra — kế " +
      "hoạch hội nhập, hồ sơ bảo trì, bảng tổng quan đào tạo, thư chứng nhận. PNG hoặc " +
      "JPEG, tối đa 5 MB. Nếu chưa có logo, ở đó hiện dòng chữ “ACM-Plattform”.",
    communityHinweis: "được lưu mã hóa và không bao giờ hiện lại",
    verwaltenSchliesstEin: "“Quản lý” trên ô nền tảng bao gồm mọi quyền khác.",
    logoAlt: "Logo công ty đã lưu",
    keinsHinterlegt: "Chưa lưu logo nào.",
    laedt: "Đang tải lên …",
    ersetzen: "Thay",
    hochladen: "Tải lên",
    logoHochladen: "Tải logo công ty lên",
    logoHinterlegt: "Đã lưu logo.",
    anzeige: "Màn hình",
    geburtstage: "Sinh nhật trong tuần",
    neuzugaenge: "Người mới trong đội",
    gueltigTage: "Có hiệu lực (ngày)",
    erzeugt: "Đang tạo …",
    adresseErzeugen: "Tạo địa chỉ",
    adresseKopiert: "Đã sao chép địa chỉ.",
    kopierenFehler: "Sao chép không được — vui lòng bôi đen bằng tay.",
    kopieren: "Sao chép",
    gespeichert: "Đã lưu.",
    speichern: "Lưu",
    speichert: "Đang lưu …",
    firma: "Công ty",
    ort: "Nơi lập (trên dòng ngày)",
    nameRueckfall: "Tên (dự phòng)",
    titelRueckfall: "Chức danh (dự phòng)",
  },
  zeugnisEinstellungen: {
    ausstellerprofil: "Hồ sơ bên cấp",
    ausstellerHinweis:
      "Xuất hiện trên mọi thư chứng nhận. Mẫu thư của ACM được dùng ngay khi trong tên " +
      "công ty có “ACM”.",
    linkeUnterschrift: "Chữ ký trái — chuyên môn",
    linkeHinweis:
      "Thông thường là cấp trên của người đó; cấp trên được tra từ Personio lúc tạo. " +
      "Những gì ghi ở đây chỉ có hiệu lực khi Personio không cho gì — chẳng hạn với người " +
      "được quản lý bên ngoài.",
    rechteUnterschrift: "Chữ ký phải — nhân sự",
    rechteHinweis:
      "Giống nhau cho mọi thư. Khi gắn với một người từ Personio, chức danh lấy từ đó và " +
      "vẫn đúng khi vị trí thay đổi.",
    personAusPersonio: "Người từ Personio",
    keinePerson: "— không có, dùng văn bản tự do bên dưới —",
    personenFehler: (meldung: string) => `Không tải được danh sách người (${meldung}).`,
  },
  atrEinstellungen: {
    vorlagen: "Mẫu",
    vorlagenHinweis:
      "Mỗi chương trình một mẫu. Dữ liệu đầu trang và tệp khung giống nhau trong mọi tài " +
      "liệu ATR của chương trình đó. Mẫu được tạo khi đọc vào một tập tham chiếu trong " +
      "danh mục linh kiện.",
    keineVorlage: "Chưa có mẫu nào",
    keineVorlageText: "Hãy đọc vào một tập tham chiếu — chương trình nằm ở ô D2 trong đó.",
    geruestHinterlegt: "Đã lưu tệp khung.",
    geruestErsetzen: "Thay tệp khung",
    geruestWaehlen: "Chọn tệp khung",
    keineHinterlegt: "chưa lưu tệp nào",
    kunde: "Khách hàng",
    lieferant: "Nhà cung cấp",
    arbeitspaket: "Gói công việc",
    referenz: "Tham chiếu",
    bestellerSpez: "Đặc tả bên đặt hàng",
    lieferantenSpez: "Đặc tả nhà cung cấp",
    kundenSpez: "Đặc tả khách hàng",
    atp: "ATP",
    nscm: "NSCM",
    ataKapitel: "Chương ATA",
    waage: "Cân",
    qsUnterschrift: "Chữ ký QA",
    eingangsordner: "Thư mục hộp đến",
    eingangHinweis:
      "Một phiếu giao hàng trong hộp đến được đọc vào, thành một lô giao và chuyển vào " +
      "kho lưu. Mật khẩu của tài khoản dịch vụ không nằm ở đây mà nằm trong " +
      "ATR_SMB_PASSWORT của môi trường; những máy nào được phép thì do ATR_SMB_ERLAUBT quy định.",
    laeuft: "đang chạy",
    aus: "tắt",
    zuletzt: (zeit: string, text: string) => `Lần cuối ${zeit}: ${text}`,
    nochNichtGelaufen: "Chưa chạy lần nào.",
    prueft: "Đang kiểm tra …",
    verbindungPruefen: "Kiểm tra kết nối",
    laeuftGerade: "Đang chạy …",
    jetztDurchsehen: "Rà soát ngay",
    verbindungSteht: (dateien: number) =>
      `Kết nối tốt. ${dateien} tệp đang chờ trong hộp đến.`,
    keineVerbindung: (meldung: string) => `Không có kết nối: ${meldung}`,
    unbekannt: "không rõ",
    gelesenAngelegt: (gelesen: number, angelegt: number) =>
      `Đã đọc ${gelesen}, đã tạo ${angelegt}.`,
    rechner: "Máy chủ",
    rechnerHinweis: "phải có trong ATR_SMB_ERLAUBT",
    freigabe: "Thư mục chia sẻ",
    domaene: "Miền",
    benutzer: "Người dùng",
    eingang: "Hộp đến",
    ausgang: "Hộp đi",
    archiv: "Kho lưu",
    wasEinLaufTut: "Một lượt chạy làm gì",
    entwurfAnlegen: "Tạo bản nháp để rà soát",
    dokumenteErzeugen: "Tạo tài liệu và lưu lại",
    regelmaessig: "Rà soát định kỳ",
    regelmaessigHinweis: "Rà soát định kỳ — mười phút một lần, ngày làm việc 5–19 giờ",
  },
  qualitaetEinstellungen: {
    normmatrix: "Ma trận tiêu chuẩn",
    normmatrixHinweis:
      "Các điều khoản mà một cuộc audit viện dẫn. Một tiêu chuẩn đang dùng thì không xóa " +
      "được — nó được ngừng sử dụng, nếu không một cuộc audit sẽ âm thầm mất cơ sở.",
    schonInMatrix: "Điều khoản này đã có trong ma trận.",
    regelwerk: "Bộ tiêu chuẩn",
    revision: "Phiên bản",
    klausel: "Điều khoản",
    kurztext: "Mô tả ngắn",
    kurztextBeispiel: "Audit nội bộ",
    aufnehmen: "Thêm vào",
    geprueft: "Đã đối chiếu",
    aktiv: "Hoạt động",
    geprueftSchalter: (norm: string) => `${norm} đã đối chiếu`,
    aktivSchalter: (norm: string) => `${norm} hoạt động`,
    phasenvorlagen: "Mẫu giai đoạn",
    phasenvorlagenHinweis:
      "Trình tự các bước mà một audit mới nhận được. Nó được sao lại lúc tạo — thay đổi về " +
      "sau không viết lại lịch sử nào.",
    neueVorlage: "Mẫu mới",
    vorlageBeispiel: "Audit hệ thống chuẩn",
    anlegen: "Tạo",
    schritte: (anzahl: number) => `${anzahl} bước`,
    schrittErgaenzen: "Thêm bước",
    schrittBeispiel: "ví dụ: họp khai mạc",
  },
  personioZugang: {
    titel: "Thông tin đăng nhập Personio",
    einleitung:
      "Thông tin đăng nhập của một ứng dụng API Personio. Không có nó thì đợt đồng bộ, " +
      "ảnh hồ sơ và các danh sách gợi ý còn để trống.",
    kennung: "Client-ID",
    geheimnis: "Client-Secret",
    feldHinweis:
      "Được lưu mã hóa và không bao giờ hiện lại. Ai muốn đổi thì nhập " +
      "thông tin mới.",
    speichern: "Lưu",
    gespeichert: "Đã lưu thông tin đăng nhập.",
    speichernFehler: (meldung: string) => `Lưu thất bại: ${meldung}`,
    entfernen: "Xóa",
    entfernt: "Đã xóa thông tin đăng nhập.",
    pruefen: "Kiểm tra kết nối",
    prueftGerade: "Đang kiểm tra …",
    verbindungSteht: "Personio chấp nhận thông tin đăng nhập.",
    verbindungFehlt: "Personio không trả lời.",
    laedt: "Đang tải …",
    keineHinterlegt: "Chưa lưu thông tin đăng nhập nào.",
    ausDerUmgebung: "Áp dụng thông tin đăng nhập từ môi trường của máy chủ (.env).",
    hinterlegtSeit: (zeitpunkt: string, wer: string | null) =>
      wer
        ? `Đã lưu ngày ${zeitpunkt} bởi ${wer}.`
        : `Đã lưu ngày ${zeitpunkt}.`,
    ohneSchluessel:
      "Trên máy chủ chưa đặt GEHEIM_SCHLUESSEL. Chừng nào còn thiếu, " +
      "không lưu mã hóa được gì.",
  },
  sensorEinstellungen: {
    neuesGeraet: "Thiết bị mới",
    name: "Tên",
    nameBeispiel: "Phòng máy chủ",
    rechner: "Máy chủ",
    rechnerBeispiel: "sensor-01.acm.local",
    rechnerHinweis: "phải có trong SNMP_ERLAUBT",
    community: "Community",
    port: "Port",
    kennungTemperatur: "Mã nhận dạng nhiệt độ",
    kennungLuftfeuchte: "Mã nhận dạng độ ẩm",
    faktorTemperatur: "Hệ số nhiệt độ",
    faktorHinweis: "0,1 nếu thiết bị gửi phần mười độ dưới dạng số nguyên",
    faktorLuftfeuchte: "Hệ số độ ẩm",
    temperaturAb: "Nhiệt độ từ (°C)",
    temperaturBis: "Nhiệt độ đến (°C)",
    feuchteAb: "Độ ẩm từ (%)",
    feuchteBis: "Độ ẩm đến (%)",
    farbe: "Màu trong biểu đồ",
    farbeHinweis: "ví dụ: #0f6e8c",
    optional: "không bắt buộc",
    anlegen: "Tạo",
    fragt: "Đang hỏi …",
    ausprobieren: "Thử",
    keinGeraet: "Chưa có thiết bị nào",
    keinGeraetText: "Hãy nhập máy chủ, community và ít nhất một mã nhận dạng ở trên.",
    wirdAbgefragt: (name: string) => `Đang hỏi ${name}`,
    communityErsetzen: "Thay community",
    unveraendert: "không đổi",
    communityErsetzt: "Đã thay community.",
    sensorAngelegt: "Đã tạo cảm biến.",
    sensorGeloescht: "Đã xóa cảm biến cùng chuỗi thời gian của nó.",
    zahlEingeben: "Vui lòng nhập một số.",
  },
  zugaenge: {
    stufen: {
      viewer: "Xem",
      editor: "Chỉnh sửa",
      admin: "Quản lý",
    },
    gruppeAngelegt: "Đã tạo nhóm.",
    gruppeGibtEsSchon: "Tên nhóm này đã tồn tại.",
    personAngelegt: "Đã tạo người dùng",
    gruppeUmbenannt: "Đã đổi tên nhóm.",
    gruppeGeloescht: "Đã xóa nhóm.",
    mitgliedHinzu: "Đã thêm thành viên. Có hiệu lực sau lần đăng nhập tới.",
    schonInGruppe: "Người này đã ở trong nhóm.",
    neuesPasswort: "Mật khẩu mới",
    mitgliedEntfernt: "Đã xóa thành viên. Có hiệu lực sau lần đăng nhập tới.",
    gemeldeteSeiten: "Xem các trang đã phản hồi",
    neueGruppe: "Nhóm mới",
    gruppeBeispiel: "ví dụ: Kinh doanh nội bộ",
    anlegen: "Tạo",
    neuePerson: "Người dùng mới",
    personBeispiel: "ho.ten@acm.local",
    keineGruppe: "Chưa có nhóm nào",
    keineGruppeText: "Hãy tạo một nhóm, cấp quyền ứng dụng cho nhóm và thêm người vào.",
    verzeichnis: "Thư mục người dùng",
    ausVerzeichnis: "Đến từ thư mục người dùng",
    umbenennen: "Đổi tên",
    keinZugriff: "không có quyền",
    rechteAnGruppe: "Quyền gắn với nhóm, không gắn với từng người.",
    passwortNurJetzt:
      "Mật khẩu chỉ hiện lúc này. Sau đó chỉ có thể đặt lại chứ không xem được.",
    fertig: "Xong",
    anmeldung: "Đăng nhập",
    passwort: "Mật khẩu",
    gruppeUmbenennen: "Đổi tên nhóm",
    abbrechen: "Hủy",
    speichern: "Lưu",
    gruppenname: "Tên nhóm",
    mitgliederVon: (name: string) => `Thành viên của “${name}”`,
    wirktNachAnmeldung: "Thay đổi có hiệu lực ngay khi người đó đăng nhập lần sau.",
    schliessen: "Đóng",
    personHinzufuegen: "Thêm người",
    auswaehlen: "— chọn —",
    hinzufuegen: "Thêm",
    keineMitglieder: "Nhóm này chưa có thành viên.",
    passwortZuruecksetzen: "Đặt lại mật khẩu",
    mitgliedEntfernen: "Xóa thành viên",
    entfernen: "Xóa",
  },
  kopftitel: {
    start: "Ứng dụng",
    kennzahlen: "Bảng chỉ số KPI",
    offeneSchulungen: "Đào tạo còn thiếu",
    schulungsmatrix: "Ma trận đào tạo",
    atrLieferungen: "Lô giao ATR",
  },
  kennzahlenHub: {
    titel: "Bảng chỉ số KPI",
    einleitung: "Chỉ số theo từng bộ phận chuyên môn. Dữ liệu đến từ các tệp xuất ERP ở mục Tải lên.",
    bereiche: {
      "/kpi/vertrieb": "Doanh thu, giá trị đơn hàng, tỷ trọng khách hàng",
      "/hr/kennzahlen": "Lực lượng lao động, biến động nhân sự, nghỉ ốm — quyền riêng",
      "/kpi/qualitaet": "Phát hiện audit và tỷ lệ khiếu nại",
      "/kpi/finanzen": "Tỷ lệ chi phí vật tư và nhân sự",
      "/kpi/einkauf": "Độ đúng hẹn giao hàng của nhà cung cấp",
      "/kpi/produktion": "Chậm trễ, đơn hàng quá hạn",
      "/kpi/bewertung": "Bình luận và biện pháp cho từng chỉ số",
    },
  },
  personalHub: {
    einleitung:
      "Công tác nhân sự, theo từng mảng. Các con số chỉ là một trong số đó.",
    bereiche: {
      "/hr/kennzahlen": "Lực lượng lao động, biến động nhân sự, nghỉ ốm, giờ làm thêm",
      "/hr/organigramm": "Ai báo cáo cho ai",
      "/hr/kompetenzen": "Ma trận năng lực theo bộ phận",
      "/hr/schulungen": "Đào tạo bắt buộc, lịch học, hồ sơ",
      "/hr/onboarding": "Người vào mới và những việc phải làm",
      "/hr/einarbeitung": "Kế hoạch hội nhập và tiến độ",
      "/hr/dokumente": "Tạo biểu mẫu, in ra, quét trả lại",
      "/hr/zeugnisse": "Soạn và cấp thư chứng nhận công việc",
    },
  },
  bewertung: {
    titel: "Đánh giá KPI",
    einleitung:
      "Bình luận xem một con số có nghĩa gì và ghi lại điều rút ra từ đó. Danh sách là các " +
      "chỉ số có giá trị mục tiêu — đúng danh sách đang định hình các bảng chỉ số.",
    uebersichtFehler: (meldung: string) =>
      `Không tải được trang tổng quan: ${meldung}`,
    nurLesen:
      "Bạn đọc được các đánh giá nhưng không ghi được. Việc đó cần quyền “Sửa” trên phần " +
      "cài đặt.",
    stand: (offen: number, ueberfaellig: number, erledigt: number, kommentare: number) =>
      `${offen} đang mở, trong đó ${ueberfaellig} quá hạn · ${erledigt} đã xong · ` +
      `${kommentare} bình luận`,
    offenTitel: (anzahl: number) => `${anzahl} đang mở`,
    ueberfaelligTitel: (anzahl: number) => `${anzahl} quá hạn`,
    massnahmen: "Biện pháp",
    wasZuTun: "Phải làm gì",
    zustaendig: "Người phụ trách",
    faellig: "Đến hạn",
    anlegen: "Tạo",
    ohneZustaendigen: "chưa có người phụ trách",
    faelligAm: (datum: string) => `đến hạn ${datum}`,
    erledigtAm: (datum: string) => `xong ${datum}`,
    massnahmeLoeschen: "Xóa biện pháp",
    keineMassnahme: "Chưa có biện pháp nào cho chỉ số này.",
    kommentare: "Bình luận",
    kommentarPlatzhalter: "Con số này nói lên điều gì?",
    kommentarLoeschen: "Xóa bình luận",
    keinKommentar: "Chưa có ai nói gì về chỉ số này.",
    status: {
      offen: "đang mở",
      laeuft: "đang làm",
      erledigt: "đã xong",
      verworfen: "đã bỏ",
    },
    bereiche: {
      vertrieb: "Kinh doanh",
      einkauf: "Mua hàng",
      produktion: "Sản xuất",
      qualitaet: "Chất lượng",
      finanzen: "Tài chính",
      personal: "HR",
    },
  },
  erklaerung: {
    hinweis: "Giải thích",
    frage: (titel: string) => `“${titel}” được tính như thế nào?`,
    knopf: "Cách tính",
    untertitel: "Cách tính như sau",
    ganzeSeite: "Toàn bộ trang trợ giúp",
  },
};
